### ISSUE TITLE
if tests are parallelized in maven's surefire, first run fails while fetching resources

### ISSUE THREAD

**Issue by davcamer** [robolectric/robolectric#1000]
Two different types of stack traces show up repeatedly. One early in the run, and another later on.

The early one:
shouldLaunchTheLibraryActivityXXX(com.XXX.activities.TheActivity)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:224)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.lang.RuntimeException: java.util.zip.ZipException: error in opening zip file
    at org.robolectric.res.Fs$JarFs.<init>(Fs.java:57)
    at org.robolectric.res.Fs.fromJar(Fs.java:23)
    at org.robolectric.SdkEnvironment.createSystemResourceLoader(SdkEnvironment.java:30)
    at org.robolectric.SdkEnvironment.getSystemResourceLoader(SdkEnvironment.java:38)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:219)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.<init>(ZipFile.java:128)
    at java.util.jar.JarFile.<init>(JarFile.java:136)
    at java.util.jar.JarFile.<init>(JarFile.java:100)
    at org.robolectric.res.Fs$JarFs.<init>(Fs.java:50)
    at org.robolectric.res.Fs.fromJar(Fs.java:23)
    at org.robolectric.SdkEnvironment.createSystemResourceLoader(SdkEnvironment.java:30)
    at org.robolectric.SdkEnvironment.getSystemResourceLoader(SdkEnvironment.java:38)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:219)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

And then later:
shouldIncrementTimeOnClickOfCountUp(com.XXX.activities.CountdownConfigurationActivityTest)  Time elapsed: 0.105 sec  <<< ERROR!
org.fest.reflect.exception.ReflectionError: Unable to load class 'com.android.internal.policy.impl.PhoneWindow' using class loader org.robolectric.bytecode.AsmInstrumentingClassLoader@3951f910
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.loadClass(AsmInstrumentingClassLoader.java:85)
    at org.fest.reflect.type.TypeLoader.loadType(TypeLoader.java:97)
    at org.fest.reflect.type.TypeLoader.load(TypeLoader.java:57)
    at org.fest.reflect.type.Type.load(Type.java:70)
    at org.robolectric.shadows.ShadowWindow.create(ShadowWindow.java:23)
    at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.bytecode.ShadowWrangler$5.call(ShadowWrangler.java:237)
    at org.robolectric.bytecode.ShadowWrangler.intercept(ShadowWrangler.java:216)
    at org.robolectric.bytecode.RobolectricInternals.intercept(RobolectricInternals.java:83)
    at android.app.Activity.$$robo$$Activity_c57b_attach(Activity.java:4969)
    at android.app.Activity.attach(Activity.java)
    at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:90)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:114)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:256)
    at org.robolectric.util.ActivityController.create(ActivityController.java:111)
    at org.robolectric.util.ActivityController.create(ActivityController.java:123)
    at com.XXX.activities.CountdownConfigurationActivityTest.setUp(CountdownConfigurationActivityTest.java:65)

**Comment by xian** [comment]
Please reopen if this is still an issue. Thanks!
