### ISSUE TITLE
java.lang.NoSuchFieldError: fFeatures with Cobertura

### ISSUE THREAD

**Issue by rick-li** [robolectric/robolectric#1026]
```
12:28:30.448 [DEBUG] [TestEventLogger]     java.lang.NoSuchFieldError: fFeatures
12:28:30.448 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.XML11Configuration.<init>(Unknown Source)
12:28:30.448 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.XML11Configuration.<init>(Unknown Source)
12:28:30.448 [DEBUG] [TestEventLogger]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12:28:30.448 [DEBUG] [TestEventLogger]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
12:28:30.449 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:28:30.449 [DEBUG] [TestEventLogger]         at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
12:28:30.449 [DEBUG] [TestEventLogger]         at java.lang.Class.newInstance0(Class.java:372)
12:28:30.449 [DEBUG] [TestEventLogger]         at java.lang.Class.newInstance(Class.java:325)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.ObjectFactory.newInstance(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.ObjectFactory.findJarServiceProvider(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.ObjectFactory.createObject(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.DOMParser.<init>(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.parsers.DOMParser.<init>(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(Unknown Source)
12:28:30.449 [DEBUG] [TestEventLogger]         at org.robolectric.AndroidManifest.parseAndroidManifest(AndroidManifest.java:135)

```

A simple testcase is here
https://github.com/rick-li/robo-cobertura
`gradle cobertura -d`

Related [discussion](https://groups.google.com/forum/?hl=en#!topic/robolectric/eb1nD3ENbMw)

**Comment by WonderCsabo** [comment]
It seems `cobertura-maven-plugin` version 2.7 and Robolectric 2.4 can work with together, i no longer see this issue. I guess this can be closed.
