### ISSUE TITLE
Tests broke after AndroidManifest parsing fix

### ISSUE THREAD

**Issue by mjurkus** [robolectric/robolectric#1029]
All my tests tarted failing 2 days ago. It looks like this https://github.com/robolectric/robolectric/commit/2412fe482281ad9a8858ffd2166c233ee594f500 caused problems below.

Is my assumption correct or should I look for problems in my tests?

``` JAVA
java.lang.RuntimeException: java.lang.RuntimeException: no ResourceLoader found for com.application.dev
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: no ResourceLoader found for com.application.dev
    at org.robolectric.res.RoutingResourceLoader.pickFor(RoutingResourceLoader.java:91)
    at org.robolectric.res.RoutingResourceLoader.pickFor(RoutingResourceLoader.java:80)
    at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
    at org.robolectric.AndroidManifest$MetaData.init(AndroidManifest.java:627)
    at org.robolectric.AndroidManifest.initMetaData(AndroidManifest.java:304)
    at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:355)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:77)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    ... 35 more
```

**Comment by giorgio-zamparelli** [comment]
This was never raised as a new issue?
@mjurkus did you find a solution or gave up?

**Comment by mjurkus** [comment]
Yes, solved it. Everything runs fine now.

**Comment by giorgio-zamparelli** [comment]
I incurred in the same android.content.res.Resources$NotFoundException: no such label com.application.dev:string/app_name, 
do you remember how you solved it?

**Comment by mjurkus** [comment]
Hard to tell now if that was the actual fix, but I think changing `AndroidManifestExt` to `AndroidManifest` in custom `RobolectricTestRunner` did the trick. Can't be sure now.

**Comment by giorgio-zamparelli** [comment]
Thanks

2015-03-24 14:04 GMT+01:00 Martynas Jurkus <notifications@github.com>:
