### ISSUE TITLE
android.view.InflateException ... Error inflating class fragment

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#1062]
I cannot execute a test properly.
This is the stacktrace (internal names/packages blurred with XXX):

android.view.InflateException: XML file C:\XXX\application\res\layout\XXX.xml line #-1 (sorry, not yet implemented): Error inflating class fragment
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:267)
    at android.app.Activity.setContentView(Activity.java:1895)
    at XXX.onCreate(XXX.java:31)
    at XXXTest.OnCreate_Always_OpensSlidingPaneLayout(XXXTest.java:40)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.IllegalArgumentException: XML file C:\XXX.xml line #-1 (sorry, not yet implemented): Duplicate id 0x7f0e0007, tag null, or parent id 0x7f0e0006 with another fragment for XXXFragment
    at android.app.Activity.onCreateView(Activity.java:4751)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
    ... 30 more

Test code:
        activity = Robolectric.buildActivity(XXXActivity.class).create().get();
        activity.onCreate(new Bundle());

Code (XXXActivity):
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.XXX); <-- crash

Code (XXX.xml):
<?xml version="1.0" encoding="utf-8"?>

<android.support.v4.widget.SlidingPaneLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools" android:id="@+id/slidingpane_XXX"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

```
<FrameLayout
        android:id="@+id/content_XXX_fragment_list"
        android:layout_width="@dimen/sliding_pane_width"
        android:layout_height="match_parent">
    <fragment android:id="@+id/XXX"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            class="XXXFragment" tools:layout="@layout/XXX"/>

</FrameLayout>

<FrameLayout
        android:id="@+id/container_XXX_fragment_details"
        android:layout_width="@dimen/sliding_pane_width"
        android:layout_height="match_parent"
        android:layout_weight="1" />
```

</android.support.v4.widget.SlidingPaneLayout>

**Comment by jaredsburrows** [comment]
What is the status of this? Have you tried this in Robolectric 3.0?

**Comment by jaredsburrows** [comment]
@erd Can we close this if he does not reply? It looks he was trying to implement the Navigation DrawerLayout using `class="XXXFragment"` with `<fragment`.

**Comment by alixwar** [comment]
Hi, I'm not sure that I can upgrade to 3.0 since our API target level is set to 19. Can you confirm that it's supported to run the newer version of Robolectric?

**Comment by jaredsburrows** [comment]
Yes, please read here: https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues.

Robolectric supports APIs 16, 17, 18, 19 and 21.

**Comment by hidroh** [comment]
According to the stacktrace looks like it's expecting you to give `<fragment>` an `android:tag` attribute.

**Comment by jaredsburrows** [comment]
This is so old and should be closed. What is the testing case?

**Comment by hidroh** [comment]
I just encounter similar issue, due to missing tag, after upgrading to support 23.0.1, I suppose it's a must now. It's now a robolectric issue though, as our app also crashed when running.

**Comment by jaredsburrows** [comment]
Are you talking about in your `Materialistic` app? So if you add a `<fragment>` without `android:tag`, it crashes?

**Comment by hidroh** [comment]
Ah no it's my company app, it was missing `android:tag` in one of `<fragment>` element before, and robolectric (3.0) correctly catches this. It just that this never happens before we upgrade to 23.0.1.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

testImplementation "org.robolectric:robolectric:4.0.1"

android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}

Add to your gradle.properties

enableUnitTestBinaryResources=true

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
