### ISSUE TITLE
NullPointerException with Google Analytics from Google Play Services (gms)?

### ISSUE THREAD

**Issue by loeschg** [robolectric/robolectric#1075]
I'm getting the following stacktrace on a Travis box that I'm unable to reproduce locally. It also doesn't happen consistently on the build box. I've had it pass and then fail in subsequent runs. 

I've posted on SO (http://stackoverflow.com/questions/23528087/google-analytics-nullpointerexception-in-test), and I haven't gotten any responses. I'm not sure if this is technically a Robolectric issue or not. 

Can anyone shed light on what my problem might be? I don't enable google analytics for Robolectric tests. 

https://gist.github.com/loeschg/f2d95e2ab6a5955d32cd

```
    java.lang.NullPointerException
        at com.google.android.gms.analytics.c$a.onServiceConnected(Unknown Source)
        at com.google.android.gms.analytics.c$a.onServiceConnected(Unknown Source)
        at org.robolectric.shadows.ShadowApplication$2.run(ShadowApplication.java:257)
        at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:162)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:107)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:92)
        at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:68)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:25)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:228)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:267)
        at org.robolectric.util.ActivityController.create(ActivityController.java:144)
        at org.robolectric.util.ActivityController.create(ActivityController.java:154)
        at com.company.search.activities.loginjoin.LoginActivityTest.setup(LoginActivityTest.java:20)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jiahaoliuliu** [comment]
The solution of felipecsl works for me. This is what I use for robolectric 3.0:

    import org.robolectric.RuntimeEnvironment;
    import org.robolectric.Shadows;
    import org.robolectric.shadows.ShadowApplication;

    ShadowApplication shadowApplication = Shadows.shadowOf(RuntimeEnvironment.application);
    shadowApplication.declareActionUnbindable("com.google.android.gms.analytics.service.START");

**Comment by jaredsburrows** [comment]
public class TestBase {

      @Before
      public void setUp() throws Exception {
          // Turn off Google Analytics - Does not need to work anymore
          final ShadowApplication shadowApplication = Shadows.shadowOf(RuntimeEnvironment.application);
          shadowApplication.declareActionUnbindable("com.google.android.gms.analytics.service.START");

          // Force success
          ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable(ConnectionResult.SUCCESS);
      }

      @After
      public void tearDown() throws Exception {

      }
  }

  public MyTestClass extends TestBase {

  }
