### ISSUE TITLE
Concurrent problem lead to android.content.res.Resources$NotFoundException?

### ISSUE THREAD

**Issue by bxgong** [robolectric/robolectric#1083]
i also occurs the following errors [ERROR 1]:
i use robolectric test a project with 2 different flavor
sometimes the test will pass,but sometimes will failed by the following [ERROR 2],
it seems there are some multi thread problem that lead to the resources store in the 
private final Map> types = new LinkedHashMap>();
will be removed?

can anybody check if 
the code in ResBunch.java seems will exist some problem when run in multithread ?
types = new LinkedHashMap 's process no thread safe protect?

ResMap<TypedResource> valuesMap = getValuesMap(attrType);
Values values = valuesMap.find(resName);
values.add(new Value(xmlContext.getQualifiers(), value, xmlContext));
Collections.sort(values); 
###### 

[ERROR 2]
Caused by: android.content.res.Resources$NotFoundException: can't find file for ResName{com.xxxxx.xxx.xxx:drawable/close_icon_unfocused}
at org.robolectric.shadows.Converter.convertAndFill(Converter.java:89)
at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:236)
at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:211)

[ERROR 1]
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:819)
at java.util.ArrayList$ListItr.set(ArrayList.java:860)
at java.util.Collections.sort(Collections.java:159)
at org.robolectric.res.ResBunch.put(ResBunch.java:32)
at org.robolectric.res.ValueResourceLoader.processNode(ValueResourceLoader.java:36)
at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
at org.robolectric.res.ValueResourceLoader.processResourceXml(ValueResourceLoader.java:19)
at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:50)
at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:72)
at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:61)
at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:42)
at org.robolectric.res.PackageResourceLoader.loadEverything(PackageResourceLoader.java:30)
at org.robolectric.res.PackageResourceLoader.doInitialize(PackageResourceLoader.java:17)
at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
at org.robolectric.res.OverlayResourceLoader.doInitialize(OverlayResourceLoader.java:22)
at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:53)
at org.robolectric.res.OverlayResourceLoader.getValue(OverlayResourceLoader.java:56)
at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:277)
at org.robolectric.shadows.ShadowAssetManager.getResourceTextArray(ShadowAssetManager.java:100)
at org.robolectric.shadows.ShadowAssetManager.getResourceStringArray(ShadowAssetManager.java:74)
at android.content.res.AssetManager.getResourceStringArray(AssetManager.java)
at android.content.res.Resources.getStringArray(Resources.java:447)
..............................
..............................
..............................
at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(StClassProcessor.java:50)
at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
at $Proxy2.processTestClass(Unknown Source)
at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:103)
at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

**Comment by thomasaw** [comment]
Isn't this the same as the issue here: https://github.com/robolectric/robolectric/issues/1564

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. Mind giving this a try with 4.0 + binary resources and reopen if its still an issue.
