### ISSUE TITLE
java.lang.RuntimeException: huh? ResName{android:interpolator/accelerate_decelerate}

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#1084]
Calling this production code from Robolectric fails:

    getFragmentManager().beginTransaction().setCustomAnimations(
                R.anim.card_flip_right_in, R.anim.card_flip_right_out,
                R.anim.card_flip_left_in, R.anim.card_flip_left_out)
                .replace(R.id.container_login, new AboutFragment(), AboutFragment.TAG)
                .addToBackStack(null)
                .commit();

The error:

java.lang.RuntimeException: huh? ResName{android:interpolator/accelerate_decelerate}
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:98)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:236)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:211)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:494)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:404)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:185)
	at android.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:161)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:117)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:126)
	at android.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:93)
	at android.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:72)
	at android.app.FragmentManagerImpl.loadAnimator(FragmentManager.java:738)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:953)
	at android.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1162)
	at android.app.BackStackRecord.run(BackStackRecord.java:639)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:207)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:51)
	at android.os.Handler.post(Handler.java)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.app.BackStackRecord.commit(BackStackRecord.java:574)

**Comment by ericfri** [comment]
I'm trying to learn how to use Robolectric and am receiving the same error.  Any help?

**Comment by erd** [comment]
@ericfri which version of Robolectric are you using?

**Comment by ericfri** [comment]
Version 2.4

**Comment by erd** [comment]
This should be fixed by d7c87e4a951f2e1e38cc65a2af7ddf31844abd4c
