### ISSUE TITLE
Deadlock in Robolectric 2.3

### ISSUE THREAD

**Issue by ngutman** [robolectric/robolectric#1100]
Hey guys,
We've upgraded to robolectric 2.3 couple of weeks ago and since the upgrade we started experiencing random deadlocks when running tests that use robolectric.

I've attached a thread dump of such locked session, the two threads that are causing the culprit are `pool-2-thread-1@3223` and `pool-3-thread-1@3228`.

I tried to dig a bit into it but all I could understand is that it's related to a Class instance getting locked.

Would really appreciate help understanding if it's our fault or some nasty bug.

Thanks,
Guti

```
Full thread dump

"pool-2-thread-1@3223" prio=5 tid=0x1e nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     blocks pool-3-thread-1@3228
     waiting for pool-3-thread-1@3228 to release lock on <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.ShadowWrangler.getShadowConfig(ShadowWrangler.java:154)
      at org.robolectric.bytecode.ShadowWrangler.getShadowClassName(ShadowWrangler.java:373)
      at org.robolectric.bytecode.ShadowWrangler.createShadowFor(ShadowWrangler.java:339)
      at org.robolectric.bytecode.ShadowWrangler.initializing(ShadowWrangler.java:81)
      at org.robolectric.bytecode.RobolectricInternals.initializing(RobolectricInternals.java:72)
      at android.os.Looper.$$robo$init(Looper.java:-1)
      at android.os.Looper.<init>(Looper.java:-1)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-1)
      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
      at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
      at org.robolectric.bytecode.RobolectricInternals.newInstanceOf(RobolectricInternals.java:25)
      at org.robolectric.Robolectric.newInstanceOf(Robolectric.java:348)
      at org.robolectric.Robolectric$Reflection.newInstanceOf(Robolectric.java:1402)
      at org.robolectric.shadows.ShadowLooper.createLooper(ShadowLooper.java:40)
      at org.robolectric.shadows.ShadowLooper.access$000(ShadowLooper.java:22)
      at org.robolectric.shadows.ShadowLooper$1.create(ShadowLooper.java:34)
      at org.robolectric.shadows.ShadowLooper$1.create(ShadowLooper.java:32)
      at org.robolectric.util.SoftThreadLocal$1.initialValue(SoftThreadLocal.java:8)
      at org.robolectric.util.SoftThreadLocal$1.initialValue(SoftThreadLocal.java:6)
      at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:141)
      at java.lang.ThreadLocal.get(ThreadLocal.java:131)
      at org.robolectric.util.SoftThreadLocal.get(SoftThreadLocal.java:13)
      - locked <0xea0> (a org.robolectric.shadows.ShadowLooper$1)
      at org.robolectric.shadows.ShadowLooper.myLooper(ShadowLooper.java:77)
      - locked <0x602> (a java.lang.Class)
      at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source:-1)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
      at java.lang.reflect.Method.invoke(Method.java:597)
      at org.robolectric.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:473)
      at android.os.Looper.myLooper(Looper.java:-1)
      at android.database.sqlite.SQLiteDatabase.$$robo$$SQLiteDatabase_ab15_isMainThread(SQLiteDatabase.java:390)
      at android.database.sqlite.SQLiteDatabase.isMainThread(SQLiteDatabase.java:-1)
      at android.database.sqlite.SQLiteDatabase.$$robo$$SQLiteDatabase_ab15_getThreadDefaultConnectionFlags(SQLiteDatabase.java:381)
      at android.database.sqlite.SQLiteDatabase.getThreadDefaultConnectionFlags(SQLiteDatabase.java:-1)
      at android.database.sqlite.SQLiteProgram.$$robo$$SQLiteProgram_e9aa_getConnectionFlags(SQLiteProgram.java:106)
      at android.database.sqlite.SQLiteProgram.getConnectionFlags(SQLiteProgram.java:-1)
      at android.database.sqlite.SQLiteQuery.$$robo$$SQLiteQuery_756e_fillWindow(SQLiteQuery.java:62)
      at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:-1)
      at android.database.sqlite.SQLiteCursor.$$robo$$SQLiteCursor_4b70_fillWindow(SQLiteCursor.java:143)
      at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:-1)
      at android.database.sqlite.SQLiteCursor.$$robo$$SQLiteCursor_4b70_getCount(SQLiteCursor.java:133)
      at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:-1)
      at com.tapreason.sdk.ap.f(SourceFile:253)
      at com.tapreason.sdk.ap.e(SourceFile:88)
      at com.tapreason.sdk.au.b(SourceFile:120)
      - locked <0xea1> (a com.tapreason.sdk.au)
      at com.tapreason.sdk.k$2.run(SourceFile:692)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
      at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
      at java.util.concurrent.FutureTask.run(FutureTask.java:138)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206)
      at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
      at java.lang.Thread.run(Thread.java:695)

"pool-3-thread-1@3228" prio=5 tid=0x1f nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     blocks pool-2-thread-1@3223
     blocks pool-4-thread-1@2356
     blocks GAThread@2169
     blocks Finalizer@3739
     blocks main@1
     waiting for pool-2-thread-1@3223 to release lock on <0x602> (a java.lang.Class)
      at java.lang.Class.initAnnotationsIfNecessary(Class.java:3124)
      at java.lang.Class.getAnnotation(Class.java:3086)
      at org.robolectric.bytecode.ShadowWrangler.getShadowedClass(ShadowWrangler.java:195)
      at org.robolectric.bytecode.ShadowWrangler.calculatePlan(ShadowWrangler.java:129)
      at org.robolectric.bytecode.ShadowWrangler.methodInvoked(ShadowWrangler.java:88)
      - locked <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.RobolectricInternals.methodInvoked(RobolectricInternals.java:77)
      at android.os.Looper.getMainLooper(Looper.java:-1)
      at android.database.sqlite.SQLiteDatabase.$$robo$$SQLiteDatabase_ab15_isMainThread(SQLiteDatabase.java:391)
      at android.database.sqlite.SQLiteDatabase.isMainThread(SQLiteDatabase.java:-1)
      at android.database.sqlite.SQLiteDatabase.$$robo$$SQLiteDatabase_ab15_getThreadDefaultConnectionFlags(SQLiteDatabase.java:381)
      at android.database.sqlite.SQLiteDatabase.getThreadDefaultConnectionFlags(SQLiteDatabase.java:-1)
      at android.database.sqlite.SQLiteProgram.$$robo$$SQLiteProgram_e9aa_getConnectionFlags(SQLiteProgram.java:106)
      at android.database.sqlite.SQLiteProgram.getConnectionFlags(SQLiteProgram.java:-1)
      at android.database.sqlite.SQLiteQuery.$$robo$$SQLiteQuery_756e_fillWindow(SQLiteQuery.java:62)
      at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:-1)
      at android.database.sqlite.SQLiteCursor.$$robo$$SQLiteCursor_4b70_fillWindow(SQLiteCursor.java:143)
      at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:-1)
      at android.database.sqlite.SQLiteCursor.$$robo$$SQLiteCursor_4b70_getCount(SQLiteCursor.java:133)
      at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:-1)
      at com.tapreason.sdk.ai.b(SourceFile:63)
      at com.tapreason.sdk.k$4.run(SourceFile:752)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
      at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
      at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
      at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
      at java.lang.Thread.run(Thread.java:695)

"main@1" prio=5 tid=0x1 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     waiting for pool-3-thread-1@3228 to release lock on <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.ShadowWrangler.getShadowConfig(ShadowWrangler.java:154)
      at org.robolectric.bytecode.ShadowWrangler.getShadowClassName(ShadowWrangler.java:373)
      at org.robolectric.bytecode.ShadowWrangler.createShadowFor(ShadowWrangler.java:339)
      at org.robolectric.bytecode.ShadowWrangler.initializing(ShadowWrangler.java:81)
      at org.robolectric.bytecode.RobolectricInternals.initializing(RobolectricInternals.java:72)
      at android.content.Intent.$$robo$init(Intent.java:-1)
      at android.content.Intent.<init>(Intent.java:3449)
      at org.robolectric.DefaultTestLifecycle.addManifestActivitiesToPackageManager(DefaultTestLifecycle.java:70)
      at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:56)
      at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:13)
      at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:118)
      at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
      at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
      at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
      at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
      at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
      at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
      at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
      at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
      at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
      at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
      at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)

"GAThread@2169" prio=5 tid=0x16 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     blocks Failed Connect@3723
     waiting for pool-3-thread-1@3228 to release lock on <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.ShadowWrangler.getShadowConfig(ShadowWrangler.java:154)
      at org.robolectric.bytecode.ShadowWrangler.getShadowClassName(ShadowWrangler.java:373)
      at org.robolectric.bytecode.ShadowWrangler.createShadowFor(ShadowWrangler.java:339)
      at org.robolectric.bytecode.ShadowWrangler.initializing(ShadowWrangler.java:81)
      at org.robolectric.bytecode.RobolectricInternals.initializing(RobolectricInternals.java:72)
      at android.content.Intent.$$robo$init(Intent.java:-1)
      at android.content.Intent.<init>(Intent.java:3449)
      at com.google.analytics.tracking.android.AnalyticsGmsCoreClient.connect(AnalyticsGmsCoreClient.java:75)
      at com.google.analytics.tracking.android.GAServiceProxy.connectToService(GAServiceProxy.java:330)
      - locked <0xe9e> (a com.google.analytics.tracking.android.GAServiceProxy)
      at com.google.analytics.tracking.android.GAServiceProxy.createService(GAServiceProxy.java:210)
      at com.google.analytics.tracking.android.GAThread.init(GAThread.java:90)
      at com.google.analytics.tracking.android.GAThread.run(GAThread.java:358)

"pool-4-thread-1@2356" prio=5 tid=0x18 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     waiting for pool-3-thread-1@3228 to release lock on <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.ShadowWrangler.methodInvoked(ShadowWrangler.java:86)
      at org.robolectric.bytecode.RobolectricInternals.methodInvoked(RobolectricInternals.java:77)
      at android.text.TextUtils.isEmpty(TextUtils.java:-1)
      at com.tapreason.sdk.c.run(SourceFile:147)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
      at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
      at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
      at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
      at java.lang.Thread.run(Thread.java:695)

"pool-5-thread-1@3399" prio=5 tid=0x20 nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
      at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
      at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
      at java.lang.Thread.run(Thread.java:695)

"pool-1-thread-4@1743" prio=5 tid=0x14 nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
      at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
      at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
      at java.lang.Thread.run(Thread.java:695)

"pool-1-thread-3@1364" prio=5 tid=0x13 nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
      at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
      at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
      at java.lang.Thread.run(Thread.java:695)

"pool-1-thread-2@1363" prio=5 tid=0x12 nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
      at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
      at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
      at java.lang.Thread.run(Thread.java:695)

"pool-1-thread-1@1362" prio=5 tid=0x11 nid=NA waiting
  java.lang.Thread.State: WAITING
      at sun.misc.Unsafe.park(Unsafe.java:-1)
      at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
      at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
      at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
      at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
      at java.lang.Thread.run(Thread.java:695)

"Failed Connect@3723" prio=5 tid=0x21 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     waiting for GAThread@2169 to release lock on <0xe9e> (a com.google.analytics.tracking.android.GAServiceProxy)
      at com.google.analytics.tracking.android.GAServiceProxy.useStore(GAServiceProxy.java:304)
      at com.google.analytics.tracking.android.GAServiceProxy.access$500(GAServiceProxy.java:28)
      at com.google.analytics.tracking.android.GAServiceProxy$FailedConnectTask.run(GAServiceProxy.java:406)
      at java.util.TimerThread.mainLoop(Timer.java:512)
      at java.util.TimerThread.run(Timer.java:462)

"AWT-Shutdown@3737" prio=5 tid=0x25 nid=NA waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:284)
      at java.lang.Thread.run(Thread.java:695)

"Java2D Disposer@2973" daemon prio=10 tid=0x1d nid=NA waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
      at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
      at sun.java2d.Disposer.run(Disposer.java:125)
      at java.lang.Thread.run(Thread.java:695)

"Finalizer@3739" daemon prio=8 tid=0x3 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
     waiting for pool-3-thread-1@3228 to release lock on <0xe9f> (a org.robolectric.bytecode.ShadowWrangler)
      at org.robolectric.bytecode.ShadowWrangler.methodInvoked(ShadowWrangler.java:86)
      at org.robolectric.bytecode.RobolectricInternals.methodInvoked(RobolectricInternals.java:77)
      at android.content.res.AssetManager.finalize(AssetManager.java:-1)
      at java.lang.ref.Finalizer.invokeFinalizeMethod(Finalizer.java:-1)
      at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:83)
      at java.lang.ref.Finalizer.access$100(Finalizer.java:14)
      at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)

"Reference Handler@3740" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
      at java.lang.Object.wait(Object.java:-1)
      at java.lang.Object.wait(Object.java:485)
      at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)

"AWT-AppKit@2890" daemon prio=5 tid=0x1a nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@3738" daemon prio=9 tid=0x6 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

```

**Comment by chariotsystems** [comment]
Whilst this is fixed on 3.1-SNAPSHOT there are a number of reasons why you would not want to move off 3.0.  These are:
A number of the APIs have changed specifically:
 SharedPreferences preferences = ShadowPreferenceManager.getDefaultSharedPreferences(app);

Secondly 3.1 will not run against sdk 23 because it drags in version 18 of shadow-core which is no longer available in any of the maven repos.

I have found a workaround which allows you to use 3.0 and still have the fix that works:

public class CorporateTestRunner extends RobolectricGradleTestRunner {

    public CorporateTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    protected ClassHandler createClassHandler(ShadowMap shadowMap, SdkConfig sdkConfig) {
        ClassHandler classHandler = new ShadowWrangler(shadowMap);
        try {
            Field field = classHandler.getClass().getDeclaredField("shadowConfigCache");
            field.setAccessible(true);
            field.set(classHandler, new ConcurrentHashMap<Class, ShadowConfig>());
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
        return classHandler;
    }

...
}
