### ISSUE TITLE
Robolectric 2.3 failing to create a custom view with custom attributes.

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#1102]
We are using a custom view in the same project where the robolectric tests are running (it isn't an apklib).  The view has custom attributes which are defined in the the values/attrs.xml as a styeable reference.

```
 <declare-styleable name="SlidingDrawer">

    <!-- Identifier for the child that represents the drawer's handle. -->
    <attr name="handle" format="reference" />
    <!-- Identifier for the child that represents the drawer's content. -->
    <attr name="content" format="reference" />
    <!-- Orientation of the SlidingDrawer. -->
    <attr name="orientation" format="enum">
        <enum name="topDown" value="1" />
        <enum name="bottomUp" value="2" />
        <enum name="leftToRight" value="4" />
        <enum name="rightToLeft" value="8" />
    </attr>
    <!--
         Indicates whether the drawer can be opened/closed by a single tap
         on the handle.  (If false, the user must drag or fling, or click
         using the trackball, to open/close the drawer.)  Default is true.
    -->
    <attr name="collapsedOffset" format="dimension" />
    <attr name="expandedOffset" format="dimension" />
    <attr name="allowSingleTap" format="boolean" />
    <!--
         Indicates whether the drawer should be opened/closed with an animation
         when the user clicks the handle. Default is true.
    -->
    <attr name="animateOnClick" format="boolean" />
</declare-styleable>
```

We get the following error.

```
  android.view.InflateException: XML file /Users/davidcarver/Work/IQ/git/fusion-android/fusion-  common/res/layout/activity_navigator.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
at android.view.LayoutInflater.createView(LayoutInflater.java:620)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:267)
at android.app.Activity.setContentView(Activity.java:1895)
at com.example.android.activities.student.StudentActivity.onCreate(StudentActivity.java:324)
at android.app.Activity.performCreate(Activity.java:5133)
at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
at org.robolectric.util.ActivityController$1.run(ActivityController.java:113)
at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:265)
at org.robolectric.util.ActivityController.create(ActivityController.java:110)
at org.robolectric.util.ActivityController.create(ActivityController.java:120)
at com.example.android.activities.student.StudentActivityTest.setUp(StudentActivityTest.java:55)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
 Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedConstructorAccessor104.newInstance(Unknown Source)
at   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:594)
at android.view.LayoutInflater.createView(LayoutInflater.java)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createViewFromTag(LayoutInflater.java:696)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:755)
at android.view.LayoutInflater.rInflate(LayoutInflater.java)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:492)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:397)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:353)
at android.view.LayoutInflater.inflate(LayoutInflater.java)
at com.android.internal.policy.impl.PhoneWindow.$$robo$$PhoneWindow_1a87_setContentView(PhoneWindow.java:267)
at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
at android.app.Activity.$$robo$$Activity_c57b_setContentView(Activity.java:1895)
at android.app.Activity.setContentView(Activity.java)
at com.example.android.activities.student.StudentActivity.onCreate(StudentActivity.java:324)
at android.app.Activity.$$robo$$Activity_c57b_performCreate(Activity.java:5133)
at android.app.Activity.performCreate(Activity.java)
at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
at org.robolectric.util.ActivityController$1.run(ActivityController.java:113)
at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:265)
at org.robolectric.util.ActivityController.create(ActivityController.java:110)
at org.robolectric.util.ActivityController.create(ActivityController.java:120)
at com.example.android.activities.student.StudentActivityTest.setUp(StudentActivityTest.java:55)
at sun.reflect.GeneratedMethodAccessor105.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
... 20 more
    Caused by: java.lang.IllegalArgumentException: The handle attribute is required and must refer to a valid child.
at com.example.android.widget.SlidingDrawer.<init>(SlidingDrawer.java:298)
at com.example.android.widget.SlidingDrawer.<init>(SlidingDrawer.java:252)
... 54 more
```

SlidingDrawer looks to see that a custom attribute handle has been set and if it detects it hasn't will throw the IllegalArgument exception.  The layout is setting the attribute, but Robolectric doesn't seem to be setting the attribute.

XML looks similar to:

```
 <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
          android:id="@+id/mainActivityContentAndStatusLayout"
          xmlns:widget="http://schemas.android.com/apk/res-auto"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          android:background="@color/fragment_background_color"
          >

<!-- The content frame -->
<FrameLayout
        android:id="@+id/activityContentFrame"
        android:layout_alignParentRight="true"
        android:layout_marginLeft="5dp"
        android:layout_width="fill_parent"
        android:layout_height="match_parent"
        />

    <com.example.android.widget.SlidingDrawer
            android:id="@+id/vogelsSweetSlidingDrawer"
            android:layout_alignParentLeft="true"
            android:layout_width="378dp"
            android:layout_height="match_parent"
            android:background="@android:color/transparent"
            widget:handle="@+id/navigatorDrawerButton"
            widget:content="@+id/navigatorFrame"
            widget:orientation="leftToRight"
            widget:allowSingleTap="true"
            widget:animateOnClick="false" >
```

..
...
..

**Comment by eygraber** [comment]
This is a really frustrating bug.

**Comment by jongerrish** [comment]
That is an old version of Robolectric and is not likely anyone will fix it
in that version. Can you try 2.4 and see if the issue still persists?

**Comment by eygraber** [comment]
This occurred using 3.0 Snapshot

**Comment by eygraber** [comment]
This issue is still occurring with the 3.0 Snapshot. I believe the problem was introduced here - https://github.com/robolectric/robolectric/pull/1272#issuecomment-61844670

**Comment by markcerqueira** [comment]
Issue is still occurring; I'm using 3.0-rc3.

**Comment by lonelyym** [comment]
Issue is still occurring with 3.0 Snapshot, any suggestion?

**Comment by ericbrandwein** [comment]
+1

**Comment by jongerrish** [comment]
Can you create a really simple test case to demonstrate?

**Comment by AlexanderTolstykh** [comment]
I had a similar problem, but with library's custom views. See more info here - http://stackoverflow.com/a/32609188/2308720
Hope, that can help.

**Comment by acieslinski** [comment]
+1

**Comment by srsudar** [comment]
I encountered this in a project a few days ago with a custom view. I got around it by setting the values programmatically rather than in XML and made a note to come back to it. Trying some basic cases now (an `integer` and `reference` type attribute on either an `EditText` or `LinearLayout` subclass), I'm not able to recreate it. What is more, it looks like Robolectric uses custom attributes in its own tests, suggesting that it isn't just any basic case of custom attributes that causes it to fail:

[`CustomView`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/util/CustomView.java) has custom attributes specified in [`attrs.xml`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/resources/res/values/attrs.xml#L3). It is defined in a tag in [`custom_layout.xml`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/resources/res/layout/custom_layout.xml) and inflated without problem in [`ShadowContextWrapperTests`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowContextWrapperTest.java#L341).

Something is wrong with the custom attribute code, however, as `string` is specified as the value for `custom:itemType` in [`custom_layout.xml`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/resources/res/layout/custom_layout.xml#L8). This should fail, as it is not a valid enum value (which should be either `marsupial` or `ungulate`--great names) as specified in [`attrs.xml`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/resources/res/values/attrs.xml#L4).

I'm going to try and dig into my revision history to find a test case I can recreate, but if someone else has a simple example or a project they can link to where the problem manifests, links would be appreciated.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. Mind giving this a try with 4.0 + binary resources and reopen if its still an issue.
