### ISSUE TITLE
@NotNull annotation on ResName constructor causes an IllegalStateException

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1106]
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'type' of org/robolectric/res/ResName.<init> must not be null
	at org.robolectric.res.ResName.<init>(ResName.java)
	at org.robolectric.res.ResName.qualifyResName(ResName.java:54)
	at org.robolectric.res.ResName.qualifyResourceName(ResName.java:39)
	at org.robolectric.res.ResName.getResourceId(ResName.java:68)
	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:380)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:77)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
	at org.robolectric.RobolectricTestRunner.evaluate(RobolectricTestRunner.java:236)

I believe this is being caused by the following resource:-

<?xml version="1.0" encoding="utf-8"?>
<resources>
  ...
  <string name="the_hub">The Hub</string>
  ...
  </string>
</resources>

in file res/values/strings.xml

but I'm not sure why.

Removing the @NotNull annotation fixes the issue and the tests pass.

**Comment by erd** [comment]
Closing old issues. Please re-open if this is still a problem.

**Comment by SeanJanis** [comment]
Received a similar Robolectric 3.0 issue when my AndroidManifest's Application android:label was empty. Filling in the android:label fixes the error.

java.lang.IllegalStateException: "<class_name>" is not fully qualified
    	at org.robolectric.res.ResName.<init>(ResName.java:28)
    	at org.robolectric.res.ResName.getResourceId(ResName.java:71)
    	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:380)
    	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:77)
    	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
    	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
