### ISSUE TITLE
NullPointerException building a notification with action buttons

### ISSUE THREAD

**Issue by eladmallel** [robolectric/robolectric#1110]
Hi,

We're using robolectric version 2.3 with emulateSdk=17.
I've attached some sample code with a comment on the line that throws the exception. Below the code you can find an example of the exception.

_Note: this does not happen if I remove the action buttons from the notification._

Can you please help me overcome this issue?

Thanks!

```
public Notification createNotification() {
        NotificationCompat.Builder notificationBuilder = createBuilder();
        Notification notification = notificationBuilder.build(); // this line throws the NullPointerException
        return notification;
}

private NotificationCompat.Builder createBuilder() {
        return new NotificationCompat.Builder(context)
                .setSmallIcon(R.drawable.notification_small_icon)
                .setLargeIcon(getLargeIcon())
                .setContentText("some content text")
                .setLights(0xff0000ff, 300, 1000)
                .setDefaults(Notification.DEFAULT_SOUND)
                .setAutoCancel(true)
                .setStyle(new NotificationCompat.BigTextStyle().bigText("some content text"))
                .addAction(R.drawable.icon_one_32x32, "Fix Now", createFixNowIntent())
                .addAction(R.drawable.icon_two_32x32, "Remind Me Later", createRemindMeLaterIntent())
                .setContentIntent(createIntent())
                .setContentTitle("some content title")
                .setTicker("some ticker");
    }
```

The exception:

```
java.lang.NullPointerException
    at android.widget.RemoteViews.configureRemoteViewsAsChild(RemoteViews.java:1170)
    at android.widget.RemoteViews.access$300(RemoteViews.java:63)
    at android.widget.RemoteViews$ViewGroupAction.__constructor__(RemoteViews.java:1189)
    at android.widget.RemoteViews$ViewGroupAction.<init>(RemoteViews.java:1185)
    at android.widget.RemoteViews.addView(RemoteViews.java:1698)
    at android.app.Notification$Builder.applyStandardTemplateWithActions(Notification.java:1532)
    at android.app.Notification$Builder.makeBigContentView(Notification.java:1563)
    at android.app.Notification$Builder.buildUnstyled(Notification.java:1604)
    at android.app.Notification$Builder.access$500(Notification.java:934)
    at android.app.Notification$BigTextStyle.build(Notification.java:1883)
    at android.app.Notification$Builder.build(Notification.java:1640)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.shadows.ShadowNotification$ShadowBuilder.build(ShadowNotification.java:114)
    at android.app.Notification$Builder.build(Notification.java)
    at android.support.v4.app.NotificationCompatJellybean.build(NotificationCompatJellybean.java:102)
    at android.support.v4.app.NotificationCompat$NotificationCompatImplJellybean.build(NotificationCompat.java:148)
    at android.support.v4.app.NotificationCompat$Builder.build(NotificationCompat.java:595)
    at com.billguard.services.NotificationPresenter.createNotification(NotificationPresenter.java:80)
    at com.billguard.services.NotificationPresenterTest.createNotificationWorks(NotificationPresenterTest.java:329)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

```

**Comment by pnandita** [comment]
I am still seeing this issue with the latest Robolectric 3.0 shapshot.

**Comment by pnandita** [comment]
to elaborate further, I am trying to add a desktop shortcut by calling the following method:
remoteViews.addView(remoteid, this);

Now with Robolectric I am seeing the following error:
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="1" hostname="rcdn6-vm67-82" name="null" tests="1" time="4.484" timestamp="2015-04-10T16:16:31">
  <properties />
  <testcase classname="com.example.desktopwidget.ShortCutTests" name="testHelloEmpty" time="4.411">
    <failure type="testHelloEmpty(com.cisco.desktopwidget.ShortCutTests)">java.lang.NullPointerException
	at android.widget.RemoteViews.configureRemoteViewsAsChild(RemoteViews.java:1061)
	at android.widget.RemoteViews.access$300(RemoteViews.java:63)
	at android.widget.RemoteViews$ViewGroupAction.__constructor__(RemoteViews.java:1080)
	at android.widget.RemoteViews$ViewGroupAction.&lt;init&gt;(RemoteViews.java)
	at android.widget.RemoteViews.addView(RemoteViews.java:1579)

**Comment by thenuge** [comment]
There's a related problem that #1126 doesn't fix (and in some sense introduces): if you use a MediaStyle with setShowActionsInCompactView, you get a similar IllegalArgumentException from makeMediaContentView when building the notification. 

The problem is that makeMediaContentView accesses builder.mActions directly. This is usually updated by the real builder.addAction, but Robolectric now intercepts that method and doesn't update mActions.

A workaround is to use addAction(Action) instead, which isn't intercepted. (Fair warning, that was added in API 20.) Ideally we could call the real addAction from the Robolectric implementation, but the comment #1126 notes that there's an issue with RemoteViews there.
