### ISSUE TITLE
SQLiteLibraryLoader fails on Linux when /tmp is mounted noexec

### ISSUE THREAD

**Issue by nomis** [robolectric/robolectric#1134]
This should fallback to user.dir + /.cache/robolectric/libs/ (possibly via XDG_CACHE_HOME from http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html if set).
## Test set: org.robolectric.util.SQLiteLibraryLoaderTest

Tests run: 13, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.259 sec <<< FAILURE!
shouldExtractNativeLibrary(org.robolectric.util.SQLiteLibraryLoaderTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.RuntimeException: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /tmp/robolectric-libs/libsqlite4java.so: /tmp/robolectric-libs/libsqlite4java.so: failed to map segment from shared object: Operation not permitted
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
    at java.lang.Runtime.load0(Runtime.java:795)
    at java.lang.System.load(System.java:1062)
    at com.almworks.sqlite4java.Internal.tryLoadFromPath(Internal.java:337)
    at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:110)
    at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
    at com.almworks.sqlite4java.SQLite.getSQLiteVersion(SQLite.java:114)
    at org.robolectric.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:145)
    at org.robolectric.util.SQLiteLibraryLoader.extractAndLoad(SQLiteLibraryLoader.java:136)
    at org.robolectric.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:66)
    at org.robolectric.util.SQLiteLibraryLoaderTest.shouldExtractNativeLibrary(SQLiteLibraryLoaderTest.java:44)

**Comment by hewhomustnotbenamed** [comment]
Hey, 
We are facing the same issue. Have you found out any solution that has worked for you?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
