### ISSUE TITLE
unknown resources when using applicationIdSuffix in gradle build

### ISSUE THREAD

**Issue by dodgex** [robolectric/robolectric#1150]
I have a project where i use `applicationIdSuffix ".dev"` for my debug buildType this causes either `android.content.res.Resources$NotFoundException: unknown resource 2131624007` in case of having `getString(R.string.xxx)` or if i comment this one out i get

```
android.content.res.Resources$NotFoundException: no such label my.package.name.dev:string/app_name                                                                      
        at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:96)                                                                                
        at org.robolectric.util.ActivityController.attach(ActivityController.java:53)                                                                                          
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:112)                                                                                          
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:265)                                                                                               
        at org.robolectric.util.ActivityController.create(ActivityController.java:110)                                                                                         
        at org.robolectric.util.ActivityController.create(ActivityController.java:120)                                                                                         
        at my.package.name.activities.MainActivityTest.testSomething(MainActivityTest.java:19)
```

for now i'm ok with not using applicationIdSuffix (former packageNameSuffix) but i would love to see a fix or an option to give robolectric a packageName to use for resources.

i'm using robolectic 2.3 and robolectric-gradle-plugin 0.11.+

**Comment by jakubkrolewski** [comment]
I'm having the same problem with Robolectric 3.0 rc2 and rc3.
To reproduce the problem, checkout the example app
https://github.com/mutexkid/android-studio-robolectric-example
and add
```
debug {
            applicationIdSuffix ".debug"
        }
```
to build.gradle#20

**Comment by srinisoundar** [comment]
@jakubkrolewski  is it resolved for you? I'm also facing the same problem.

**Comment by jakubkrolewski** [comment]
@srinisoundar  Currently it works fine for me. I'm using robolectric 3.0 and have the "packageName" property defined in the robolectric.properties file:
packageName = <original package name without any suffix>

**Comment by srinisoundar** [comment]
@jakubkrolewski  thank you.....

**Comment by nolanlawson** [comment]
Nothing is working for me except removing the `applicationIdSuffix ".debug"` line. I'll file an issue.

**Comment by srinisoundar** [comment]
@nolanlawson try this https://github.com/robolectric/robolectric/issues/1796#issuecomment-151805898 it worked for me
