### ISSUE TITLE
Calling com.facebook.Session.closeAndClearTokenInformation throws java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by w2ji** [robolectric/robolectric#1212]
java.lang.IllegalArgumentException: Host of origin may not be null
     at org.apache.http.cookie.CookieOrigin.<init>(CookieOrigin.java:53) 
     at org.robolectric.shadows.ShadowCookieManager.getOrigin(ShadowCookieManager.java:172)
     at org.robolectric.shadows.ShadowCookieManager.getCookie(ShadowCookieManager.java:55)
     at android.webkit.CookieManager.getCookie(CookieManager.java)
     at com.facebook.internal.Utility.clearCookiesForDomain(Utility.java:291)
     at com.facebook.internal.Utility.clearFacebookCookies(Utility.java:311)
     at com.facebook.Session.closeAndClearTokenInformation(Session.java:614)
     at com.myService.logout(TestService.java:237)

The tests that I had worked for roboletric version 2.2 but when I upgrade to version 2.3 it starts throwing java.lang.IllegalArgumentException. This is using Facebook version 3.5.2+. I notice that the ShadowCookieManager has been redesigned from 2.2 to 2.3.

**Comment by stephanenicolas** [comment]
If I submit a new PR, should I still have to wait 4 months until I get a feedback eventually saying that the PR is rejected because the maintainers couldn't rebase it ?
It's quite an exciting perspective...

**Comment by erd** [comment]
That's a distinct possibility.

**Comment by Macarse** [comment]
@erd Was this fixed?

**Comment by stephanenicolas** [comment]
@erd I am gonna work now on submitting the PR against master. Is there any chance to include it in 3.0 release ? (I only saw 3.0-rc2 on central)

**Comment by erd** [comment]
> Is there any chance to include it in 3.0 release ? (I only saw 3.0-rc2 on central)

There will be another RC.
