### ISSUE TITLE
Unqualified name not prefixed with dot in manifest causes crash

### ISSUE THREAD

**Issue by mr-jolly** [robolectric/robolectric#1213]
Although the App Manifest page (http://developer.android.com/guide/topics/manifest/manifest-intro.html#filec - Declaring class names) only mentions class name shorthand being class name preceded by a dot, the aapt source code (platform/framework/base repository, tools/aapt/Resource.cpp file, fullyQualifyClassName function) allows the shorthand form to be a class name without the preceding dot.

The code in org.robolectric.shadows.ShadowApplication.replaceLastDotWith$IfInnerStaticClass(ShadowApplication.java:128) crashes because it doesn't adhere to this unpublished aapt behavior. The easy fix is to either always fully qualify class names or to use the shorthand with a preceding dot in the app manifest file, but the code would be much more solid if it allowed for the abovementioned case that aapt allows.

**Example:**

`<manifest . . . >`
`<application . . . >`
`<service android:name="com.example.project.SecretService" . . . >`
`. . .`
`</service>`
`. . .`
`</application>`
`</manifest>`

The android:name element can be shortened to the following:

`<manifest package="com.example.project" . . . >`
`<application . . . >`
`<service android:name=".SecretService" . . . >`
`. . .`
`</service>`
`. . .`
`</application>`
`</manifest>`

but aapt also allows this as shorthand:

`<manifest package="com.example.project" . . . >`
`<application . . . >`
`<service android:name="SecretService" . . . >`
`. . .`
`</service>`
`. . .`
`</application>`
`</manifest>`

This last case crashes in Robolectric.

**Stack Crawl:**
java.lang.ArrayIndexOutOfBoundsException: -1
    at org.robolectric.shadows.ShadowApplication.replaceLastDotWith$IfInnerStaticClass(ShadowApplication.java:128)
    at org.robolectric.shadows.ShadowApplication.registerBroadcastReceivers(ShadowApplication.java:120)
    at org.robolectric.shadows.ShadowApplication.bind(ShadowApplication.java:110)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:136)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:430)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by dgl** [comment]
Any chance this could be fixed? This cost me a lot of time :(

**Comment by jaredsburrows** [comment]
@erd @mr-jolly I have never seen this in Robolectric 2.3 to Robolectric 3.0-rc2. Can we close this?

@mr-jolly When is the last time you tried this? Any status?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.
