### ISSUE TITLE
ShadowObjectAnimator doesn't fully support ofFloat method

### ISSUE THREAD

**Issue by mazoni** [robolectric/robolectric#1235]
Whenever I try to create a ObjectAnimator using the ofFloat factory method, if use properties instead of the string to say which property I want to change it throws a null pointer exception. I had to change my code from: 
ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(previewInfoLayout, View.ALPHA, 0f, 1f);
to:
ObjectAnimator objectAnimator = ObjectAnimator.ofFloat(previewInfoLayout, "alpha", 1f);
Here's the exception:
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowObjectAnimator.start(ShadowObjectAnimator.java:144)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java)
	at com.hp.link.widget.PreviewInfoFragment.showPreviewInfoLayout(PreviewInfoFragment.java:92)
	at com.hp.link.widget.PreviewInfoFragment.onViewCreated(PreviewInfoFragment.java:66)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:207)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:51)
	at android.os.Handler.post(Handler.java)

Another thing that I notice (but I'll probably create another issue for that) is that: whenever I inform more then one value, as I did in the first try, the shadowObjectAnimator would throw anArrayIndexOutOfBoundsException:

java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.robolectric.shadows.ShadowObjectAnimator$AnimationRunnable.run(ShadowObjectAnimator.java:246)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:207)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
	at android.os.Handler.postDelayed(Handler.java)
	at org.robolectric.shadows.ShadowObjectAnimator.start(ShadowObjectAnimator.java:166)

Let me know if there's anything else I can do to help. Regards

**Comment by erd** [comment]
I think this is solved by #1537.
