### ISSUE TITLE
NullPointerException when Activity.startActionMode() is called multiple times

### ISSUE THREAD

**Issue by estebanflores** [robolectric/robolectric#1291]
We have troubles to test classes that are currently using activity.startActionMode(). We are using Robolectric 2.2 and the issue appears when there is an interaction between objects with animations. 

See the following test example.

``` java
package com.crash.robolectric.test;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.util.ActivityController;

import android.app.Activity;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.view.ActionMode;
import android.view.ActionMode.Callback;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.animation.AnimationUtils;

@RunWith( RobolectricTestRunner.class )
public class RobolectrictActionModeTest
{

   @Test
   public void crashTest()
   {
      final ActivityController<TestActionModeActivity> activityController = Robolectric
         .buildActivity( TestActionModeActivity.class );

      final TestActionModeActivity activity = activityController.get();

      activityController.create().visible().start();

      startFragmentOnActivity( new Fragment(), activity );

      startAndFinishActionMode( activity );
      startAndFinishActionMode( activity );
   }


   private void startAndFinishActionMode( final Activity activity )
   {
      final ActionMode actionMode = activity.startActionMode( new Callback()
      {

         @Override
         public boolean onPrepareActionMode( final ActionMode mode, final Menu menu )
         {
            return true;
         }

         @Override
         public void onDestroyActionMode( final ActionMode mode )
         {
         }

         @Override
         public boolean onCreateActionMode( final ActionMode mode, final Menu menu )
         {
            return true;
         }

         @Override
         public boolean onActionItemClicked( final ActionMode mode, final MenuItem item )
         {
            return true;
         }
      } );
      actionMode.finish();
   }


   public static void startFragmentOnActivity( final Fragment fragment, final FragmentActivity fragmentActivity )
   {
      // Add this fragment to the SupportFragmentManager
      fragmentActivity
         .getSupportFragmentManager()
         .beginTransaction()
         .add( TestActionModeActivity.PARENT_VIEW_ID, fragment, null )
         .commit();

      fragment.onViewStateRestored( null );
   }

   public class CrashFragment extends Fragment
   {
      @Override
      public void onStart()
      {
         super.onStart();
         final View rootView = getActivity().findViewById( android.R.id.content );
         rootView.setAnimation( AnimationUtils.loadAnimation( getActivity(), android.R.anim.fade_in ) );
         rootView.animate();
      }
   }

}

```

``` java
package com.crash.robolectric.test;

import android.content.Intent;
import android.content.ServiceConnection;
import android.os.Bundle;
import android.support.v4.app.FragmentActivity;
import android.widget.FrameLayout;

public class TestActionModeActivity extends FragmentActivity
{
   public TestActionModeActivity()
   {
   }

   /** Id of the parent view. */
   public static final int PARENT_VIEW_ID = 1;

   @Override
   protected void onCreate( final Bundle savedInstanceState )
   {
      setTheme( android.R.style.Theme_Holo );
      super.onCreate( savedInstanceState );
      final FrameLayout frameLayout = new FrameLayout( this );
      frameLayout.setId( PARENT_VIEW_ID );
      setContentView( frameLayout );
   }

   @Override
   public boolean bindService( final Intent service, final ServiceConnection conn, final int flags )
   {
      // noop, services not really supported by Robolectric 2.2
      return false;
   }

   @Override
   public void unbindService( final ServiceConnection conn )
   {
      // noop, services not really supported by Robolectric 2.2
   }

}

```

Stacktrace of NullPointerException

``` log
java.lang.NullPointerException
    at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:390)
    at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1031)
    at android.animation.ValueAnimator.end(ValueAnimator.java:956)
    at android.animation.AnimatorSet.end(AnimatorSet.java:341)
    at com.android.internal.widget.ActionBarContextView.finishAnimation(ActionBarContextView.java:271)
    at com.android.internal.widget.ActionBarContextView.killMode(ActionBarContextView.java:276)
    at com.android.internal.app.ActionBarImpl.startActionMode(ActionBarImpl.java:444)
    at android.app.Activity.onWindowStartingActionMode(Activity.java:4801)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.startActionMode(PhoneWindow.java:2228)
    at android.app.Activity.startActionMode(Activity.java:4784)
    at com.crash.robolectric.test.RobolectrictActionModeTest.startAndFinishActionMode(RobolectrictActionModeTest.java:42)
    at com.crash.robolectric.test.RobolectrictActionModeTest.crashTest(RobolectrictActionModeTest.java:36)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)


```

In our real test it crash inside _ShadowObjectAnimator.start()#run_ as workaround we have copied your _ShadowObjectAnimator_ and catching NullpointerExceptions.

Is this Bug already known? 

Best Regards

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
