### ISSUE TITLE
Unknown font id 0 when using Typeface.createFromFile

### ISSUE THREAD

**Issue by vekexasia** [robolectric/robolectric#1304]
Hello there,

I'm trying to create a typeface from a font file but it looks like something goes wrong. Looking at the stacktrace it looks like nativeCreatefromFile from the shadow object doesn't get called.

Here's the stacktrace
```
Caused by: java.lang.RuntimeException: unknown font id 0
	at org.robolectric.shadows.ShadowTypeface.findById(ShadowTypeface.java:102)
	at org.robolectric.shadows.ShadowTypeface.__constructor__(ShadowTypeface.java:30)
	at android.graphics.Typeface.<init>(Typeface.java:173)
	at android.graphics.Typeface.createFromFile(Typeface.java:169)

```

**Comment by erd** [comment]
This should be fixed in d7c87e4a951f2e1e38cc65a2af7ddf31844abd4c.
