### ISSUE TITLE
Robolectric 2.3: Error inflating class <unknown> / Mac OSX 10.8.5 / JDK 1.7.0_21

### ISSUE THREAD

**Issue by jtrivett** [robolectric/robolectric#1305]
My team is evaluating Robolectric as a means to implement some actual unit tests for the Android apps we support. Our test cases are executing successfully in Eclipse and Maven builds on our Windows 7 and Mac OS X 10.9.4 development machines, but they are failing during the Maven build on our Mac OS X 10.8.5 build machine with an `Error inflating class <unknown>` error when attempting to inflate our splash screen layout. The layout is relatively simple, consisting of a LinearLayout with two ImageViews and one TextView.

**Robolectric Details:**
Version 2.3, emulateSdk=17

**Environment Details:**
Dev 1 - Windows 7 SP1, x86 32-bit, JDK 1.7.0_55, Maven 3.0.5 [success]
Dev 2 - Mac OS X 10.9.4, x86 ??, JDK 1.6.0_??, Maven 3.2.1 [success]
Build Server - Mac OS X 10.8.5, x86 64-bit, JDK 1.7.0_21, Maven 3.0.5 [test errors]

**Stack Trace:**
```
android.view.InflateException: XML file /Users/hudson/jenkins-slave/workspace/UFI/UFI Android/UFI-Android - 1 - Build - UT Refactor/res/layout/splash.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1833)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1730)
	at java.lang.Runtime.loadLibrary0(Runtime.java:823)
	at java.lang.System.loadLibrary(System.java:1044)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:50)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1605)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1627)
	at sun.awt.AppContext$2.run(AppContext.java:240)
	at sun.awt.AppContext$2.run(AppContext.java:226)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.initMainAppContext(AppContext.java:226)
	at sun.awt.AppContext.access$200(AppContext.java:112)
	at sun.awt.AppContext$3.run(AppContext.java:306)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.AppContext.getAppContext(AppContext.java:287)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:137)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:48)
	at org.robolectric.shadows.ShadowBitmapFactory.getImageSizeFromStream(ShadowBitmapFactory.java:208)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:89)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:355)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeResourceStream(ShadowBitmapFactory.java:40)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java)
	at org.robolectric.shadows.ShadowDrawable.createFromResourceStream(ShadowDrawable.java:64)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java)
	at android.content.res.Resources.loadDrawable(Resources.java:1965)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:514)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
	at android.view.View.__constructor__(View.java:3330)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowView.__constructor__(ShadowView.java:63)
	at android.view.View.<init>(View.java:3281)
	at android.view.ViewGroup.<init>(ViewGroup.java:431)
	at android.widget.LinearLayout.<init>(LinearLayout.java:176)
	at android.widget.LinearLayout.<init>(LinearLayout.java:172)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
	at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:38)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:270)
	at android.app.Activity.setContentView(Activity.java:1881)
	at com.xyz.android.ufi.ui.SplashScreen.onCreate(SplashScreen.java:92)
	at android.app.Activity.performCreate(Activity.java:5104)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:113)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:265)
	at org.robolectric.util.ActivityController.create(ActivityController.java:110)
	at org.robolectric.util.ActivityController.create(ActivityController.java:120)
	at com.xyz.android.ufi.ui.TestSplashScreen.getActivity(TestSplashScreen.java:115)
	at com.xyz.android.ufi.ui.TestSplashScreen.splashScreen_LaunchesTermsAndConditions_OnFirstAppLaunch(TestSplashScreen.java:51)
```

**splash.xml:**
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:background="@drawable/ufi_background"
    android:gravity="center_vertical"
    android:orientation="vertical" >
     
    <ImageView
        android:id="@+id/logo"
        style="@style/ufi_large_icon"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:adjustViewBounds="true"
        android:contentDescription="@string/contentDescription_logo" />

    <ImageView
        android:id="@+id/line"
        style="@style/ufi_line"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:contentDescription="@string/contentDescription_divider"
        android:src="@drawable/ufi_line" />

    <TextView
        android:id="@+id/splashText"
        style="@style/ufi_splash_text"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:contentDescription="@string/contentDescription_splash_text"
        android:text="@string/ufi_splash_text" />

</LinearLayout>
```

**Comment by erd** [comment]
Closing, since it sounds like this is an issue with Apple's JDK.
