### ISSUE TITLE
Getting this below error while running robolectric with ant build with eclipse

### ISSUE THREAD

**Issue by achakra21** [robolectric/robolectric#1311]
Note I am using the following Library in my lib folder

fest-android-1.0.8.jar
fest-assert-core-2.0M10.jar
fest-util-1.1.6.jar
hamcrest-core-1.3.jar
junit-4.11-sources.jar
junit-4.11.jar
junit.jar
mockito-core-1.9.5.jar
robolectric-2.3-jar-with-dependencies.jar(this from robolectric)
robolectric-with-dependencies.jar(This is from xtreamlabs)

org.fest.reflect.exception.ReflectionError: Unable to find method '$$robo$getData' in com.android.test.my_app.MyActivity with parameter type(s) []
    at org.fest.reflect.method.Invoker.lookupInClassHierarchy(Invoker.java:78)
    at org.fest.reflect.method.Invoker.createInvoker(Invoker.java:60)
    at org.fest.reflect.method.Invoker.newInvoker(Invoker.java:55)
    at org.fest.reflect.method.MethodReturnType.in(MethodReturnType.java:66)
    at org.robolectric.bytecode.ShadowWrangler.shadowOf(ShadowWrangler.java:434)
    at org.robolectric.Robolectric.shadowOf_(Robolectric.java:1034)
    at org.robolectric.util.ComponentController.<init>(ComponentController.java:36)
    at org.robolectric.util.ActivityController.<init>(ActivityController.java:45)
    at org.robolectric.util.ActivityController.<init>(ActivityController.java:41)
    at org.robolectric.Robolectric.buildActivity(Robolectric.java:1376)
    at com.android.test.my_app.MyActivityTest.testPressingTheButtonShouldStartActivityMain(MyActivityTest.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at com.xtremelabs.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:284)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by filip-zymek** [comment]
I am facing the same problem here, but I am not allowed to access internet for downloading dependencies (company rules). Is there a way to fix if for offline build?

**Comment by achakra21** [comment]
Please try this hope this would work for you

Troubleshooting

While running the robolectric first time it will try to download the dependencies from repository, you might face some errors due to the absence of settings.xml inside your .m2 directory, for that you need to create a settings.xml as given below with your proxy setting.
settings.xml

This is a reference for the user-specific configuration for Maven.
Includes things that should not be distributed with the pom.xml file, such as developer identity, along with local settings, like proxy information.

The default location for the settings file is User/UserId/.m2/settings.xml

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <localRepository/>
  <interactiveMode/>
  <usePluginRegistry/>
  <offline/>
  <pluginGroups/>
  <servers/>
  <mirrors/>
  
  <proxies>
      <proxy>
      <id>optional</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>your User ID</username>
      <password>password</password>
      <host>Proxy address ex:(10.187....)</host>
      <port>port address(my case 8080)</port>
      <nonProxyHosts>local.net|some.host.com</nonProxyHosts>
    </proxy>
  </proxies>
  <profiles/>
  <activeProfiles/>
</settings>
