### ISSUE TITLE
android.content.res.Resources$NotFoundException when running test via Jenkins

### ISSUE THREAD

**Issue by timnew** [robolectric/robolectric#1321]
Hi guys,

I met a wield issue that the tests works fine either in Android Studio or terminal.
But once I tried to run the tests in Jenkins via gradle, and yield Resources$NotFoundException error on multiple tests.

Here are some stack trace that I got:
```
android.view.InflateException: XML file jar:/Users/Shared/Jenkins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res/layout/screen_action_bar.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2823)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2886)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:282)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:276)
	at android.app.Activity.setContentView(Activity.java:1915)
	at me.timnew.robolectric.utils.ViewTestUtil.prepareView(ViewTestUtil.java:16)
	at net.zentertain.launcher.tile.TileViewTest.setup(TileViewTest.java:33)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:353)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$PhoneWindow_1a87_generateLayout(PhoneWindow.java:2823)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$PhoneWindow_1a87_installDecor(PhoneWindow.java:2886)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$PhoneWindow_1a87_setContentView(PhoneWindow.java:282)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$PhoneWindow_1a87_setContentView(PhoneWindow.java:276)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$Activity_c57b_setContentView(Activity.java:1915)
	at android.app.Activity.setContentView(Activity.java)
	at me.timnew.robolectric.utils.ViewTestUtil.prepareView(ViewTestUtil.java:16)
	at net.zentertain.launcher.tile.TileViewTest.setup(TileViewTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	... 7 more
Caused by: android.content.res.Resources$NotFoundException: File jar:/Users/Shared/Jenkins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res/drawable-hdpi/ab_solid_dark_holo.9.png from drawable resource ID #0x114001e
	at android.content.res.Resources.loadDrawable(Resources.java:2111)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:514)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
	at android.view.View.__constructor__(View.java:3364)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowView.__constructor__(ShadowView.java:63)
	at android.view.View.<init>(View.java:3315)
	at android.view.ViewGroup.<init>(ViewGroup.java:457)
	at android.widget.FrameLayout.<init>(FrameLayout.java:101)
	at android.widget.FrameLayout.<init>(FrameLayout.java:97)
	at com.android.internal.widget.ActionBarContainer.<init>(ActionBarContainer.java:52)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2823)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2886)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:282)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:276)
	at android.app.Activity.setContentView(Activity.java:1915)
	at me.timnew.robolectric.utils.ViewTestUtil.prepareView(ViewTestUtil.java:16)
	at net.zentertain.launcher.tile.TileViewTest.setup(TileViewTest.java:33)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	... 7 more
Caused by: org.fest.reflect.exception.ReflectionError: Unable to invoke method '$$robo$$BitmapFactory_c0f7_decodeResourceStream' with arguments [android.content.res.Resources@4deafe13, TypedValue{t=0x3/d=0xc "jar:/Users/Shared/Jenkins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res/drawable-hdpi/ab_solid_dark_holo.9.png" a=766081 r=0x114001e}, java.io.ByteArrayInputStream@7eceb95b, Rect(0, 0 - 0, 0), android.graphics.BitmapFactory$Options@35eb4667]
	at org.fest.reflect.method.Invoker.cannotInvokeMethod(Invoker.java:124)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:116)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeResourceStream(ShadowBitmapFactory.java:40)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java)
	at org.robolectric.shadows.ShadowDrawable.createFromResourceStream(ShadowDrawable.java:64)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java)
	at android.content.res.Resources.loadDrawable(Resources.java:2105)
	... 58 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at org.robolectric.shadows.ShadowBitmapFactory.getImageSizeFromStream(ShadowBitmapFactory.java:208)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:89)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:356)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	... 63 more
```

Another one
```
android.content.res.Resources$NotFoundException: File jar:/Users/Shared/Jenkins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res/drawable-hdpi/ic_menu_call.png from drawable resource ID #0x1080036
	at android.content.res.Resources.loadDrawable(Resources.java:2111)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:514)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.Resources.getDrawable(Resources.java:695)
	at net.zentertain.launcher.dock.DockAdapter.reload(DockAdapter.java:92)
	at net.zentertain.launcher.dock.DockFragment.afterViews(DockFragment.java:35)
	at net.zentertain.launcher.dock.DockFragment_.onViewChanged(DockFragment_.java:102)
	at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
	at net.zentertain.launcher.dock.DockFragment_.onViewCreated(DockFragment_.java:62)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:899)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:207)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:51)
	at android.os.Handler.post(Handler.java)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.app.BackStackRecord.commit(BackStackRecord.java:574)
	at org.robolectric.util.FragmentTestUtil.startFragment(FragmentTestUtil.java:14)
	at net.zentertain.launcher.dock.DockFragmentTest.setup(DockFragmentTest.java:56)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: org.fest.reflect.exception.ReflectionError: Unable to invoke method '$$robo$$BitmapFactory_c0f7_decodeResourceStream' with arguments [android.content.res.Resources@23c29a26, TypedValue{t=0x3/d=0x0 "jar:/Users/Shared/Jenkins/.m2/repository/org/robolectric/android-all/4.3_r2-robolectric-0/android-all-4.3_r2-robolectric-0.jar!/res/drawable-hdpi/ic_menu_call.png" a=765654}, java.io.ByteArrayInputStream@3d164721, Rect(0, 0 - 0, 0), android.graphics.BitmapFactory$Options@197e6dc]
	at org.fest.reflect.method.Invoker.cannotInvokeMethod(Invoker.java:124)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:116)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeResourceStream(ShadowBitmapFactory.java:40)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java)
	at org.robolectric.shadows.ShadowDrawable.createFromResourceStream(ShadowDrawable.java:64)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java)
	at android.content.res.Resources.loadDrawable(Resources.java:2105)
	... 56 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at org.robolectric.shadows.ShadowBitmapFactory.getImageSizeFromStream(ShadowBitmapFactory.java:208)
	at org.robolectric.shadows.ShadowBitmapFactory.decodeStream(ShadowBitmapFactory.java:89)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:356)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	... 61 more
```

The cause of the issue seems to be that Robolectric fails to locate the resource file contained in Android SDK. But not sure why.

**Comment by erd** [comment]
Make sure your Jenkins build is using one of the Oracle JDKs. `ShadowBitmap` uses `javax.imageio.ImageIO` which is not supported on OpenJDK.

**Comment by theGlenn** [comment]
Up Hello, 2016 I got the same problem. I'm using Jenkins too.
