### ISSUE TITLE
Support Lollipop

### ISSUE THREAD

**Issue by emilesvt** [robolectric/robolectric#1324]
Built the 2.4-SNAPSHOT myself and used that for the build.  Getting several NoSuchMethodErrors, mostly around View.setElevation from the ViewCompat21.

build.gradle snippets
```
...
    compileSdkVersion 21
    buildToolsVersion "21.0.0"
...
        minSdkVersion 14
        targetSdkVersion 21
...
compile 'com.android.support:support-v4:21.0+'
compile 'com.android.support:support-v13:21.0+'
...
```

And the errors
```
Caused by: java.lang.NoSuchMethodError: android.view.View.setElevation(F)V
	at android.support.v4.view.ViewCompatApi21.setElevation(ViewCompatApi21.java:37)
	at android.support.v4.view.ViewCompat$Api21ViewCompatImpl.setElevation(ViewCompat.java:1125)
	at android.support.v4.view.ViewCompat.setElevation(ViewCompat.java:2156)
	at android.support.v4.widget.CircleImageView.__constructor__(CircleImageView.java:64)
	at android.support.v4.widget.CircleImageView.<init>(CircleImageView.java:53)
	at android.support.v4.widget.SwipeRefreshLayout.createProgressView(SwipeRefreshLayout.java:309)
	at android.support.v4.widget.SwipeRefreshLayout.__constructor__(SwipeRefreshLayout.java:286)
	at android.support.v4.widget.SwipeRefreshLayout.<init>(SwipeRefreshLayout.java:268)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.mycompany.MyFragment.onCreateView(MyFragment.java:96)
	at android.app.Fragment.performCreateView(Fragment.java:1695)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:207)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:51)
	at android.os.Handler.post(Handler.java)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.app.BackStackRecord.commit(BackStackRecord.java:574)
	at com.mycompany.MyTest.setUp(MyTest.java:89)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:267)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
```

**Comment by erd** [comment]
Lollipop support is working in master.
