### ISSUE TITLE
Multidex support

### ISSUE THREAD

**Issue by benoitdion** [robolectric/robolectric#1328]
Running into the following after converting my application to a MultiDexApplication:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 46
Exception Details:
  Location:
    android/support/multidex/MultiDexApplication.<init>()V @18: ifnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2ab7 001f 2ab6 0022 1224 0312 02b8 002a
    0x0000010: 4c2b c600 1c2b 2a2a b600 2e03 bd00 30b9
    0x0000020: 0036 0400 57a7 0014 4d2c b800 3abf 2ab7
    0x0000030: 001a b14d 2cb8 003a bfb1               
  Exception Handler Table:
    bci [21, 37] => handler: 40
    bci [46, 50] => handler: 51

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by kschults** [comment]
@felipecsl How do you configure that workaround so that it works for every test? Or is the MyTestApplication the application class you're using for your main app source?

**Comment by sschuberth** [comment]
@kschults Yes, that code goes to the app under test, not to the test app. However, I'm using a slightly extended version that only ignores the `RuntimeException` if the app is really built against Robolectric:

    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);

        try {
            MultiDex.install(this);
        } catch (RuntimeException multiDexException) {
            // Work around Robolectric causing multi dex installation to fail, see
            // https://code.google.com/p/android/issues/detail?id=82007.
            boolean isUnderUnitTest;

            try {
                Class<?> robolectric = Class.forName("org.robolectric.Robolectric");
                isUnderUnitTest = (robolectric != null);
            } catch (ClassNotFoundException e) {
                isUnderUnitTest = false;
            }

            if (!isUnderUnitTest) {
                // Re-throw if this does not seem to be triggered by Robolectric.
                throw multiDexException;
            }
        }
    }

**Comment by jongerrish** [comment]
You will need to implement a shadow for MultiDex, the instructions are
here:- http://robolectric.org/extending/

I think it should be upstreamed into Robolectric into a new subproject for
v7 support library, similar to this one:-

https://github.com/robolectric/robolectric/tree/master/robolectric-shadows/shadows-support-v4

**Comment by kschults** [comment]
@jongerrish how do you declare the shadow for all your tests? I'd rather not have to do `@Config(shadows={MyShadow.class})` on every test class.

**Comment by sschuberth** [comment]
@kschults You should be able to use a `org.robolectric.Config.properties` file, see [Configuring Robolectric](http://robolectric.org/configuring/).

**Comment by jongerrish** [comment]
There are several ways, I'm not at my desk right now but your can specify
this in your properties file or override RobolectricTestRunner. If you
contribute this into Robolectric then you won't need to do anything ;-)

**Comment by spardhan** [comment]
I tried using @felipecsl 's solution but it still doesn't work for me. This is my stack trace:

```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.robolectric.AndroidManifest$MetaData.init(AndroidManifest.java:736)
	at org.robolectric.AndroidManifest.initMetaData(AndroidManifest.java:395)
	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:366)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:68)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	... 35 more

```

I am using 
    androidTestCompile 'org.robolectric:android-all:+'
    androidTestCompile('org.robolectric:robolectric:2.4')

Any ideas? Thanks!

**Comment by jongerrish** [comment]
What version of Robolectric are you using?

I think it could be that you are depending on a library or you have a
library AndroidManifest.xml without an <application> element.

**Comment by spardhan** [comment]
Hi @jongerrish would it matter if I am adding google play services as part of my application. I am not sure if this could be the issue

```
<meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
```

Also I was looking at this thread https://github.com/robolectric/robolectric/pull/1457 and I am wondering if I need to add shadow for play services.

**Comment by jongerrish** [comment]
Probably ;-)

This meta-data element is really a private implementation detail of the
Google Play Services client library, and _shouldn't_ be declared by your
application. Actually your Build system should merge all the library
manifests for you to build the APK so you should never see this. Our build
system does this and I believe Gradle does also? These kinds of build
system will also merge the resources needed so everything typically works.

If for some reason your build system doesn't do this merging for you and
you are _forced_ to do add that line to your manifest then Robolectric will
also need to be able to resolve the resources for Google Play Services
which is where that resource is defined. If you are using a build system
like this then you can add the library projects using project.properties

I think you can probably get around the issue though by using the following
Shadow:-

https://github.com/robolectric/robolectric/blob/48ff6860036de421752a334a69ae890b63006742/robolectric-shadows/shadows-play-services/src/main/java/org/robolectric/shadows/ShadowGooglePlayServicesUtil.java

If memory services me correctly, GooglePlayServicesUtil is the class that
checks that value, so using this shadow will avoid the check.

**Comment by adauvalter** [comment]
This Workaround is a solution, but with it i receive an empty list with
`assetManager = new Activity().getAssets()` and NullPointerException after applying list on it. Without this Workaround run everything ok.

**Comment by jongerrish** [comment]
Don't use new Activity() in your tests. Better to use
Robolectric.{setup,build}Activity() since this will ensure that your
Activity has a base context attached to it. Same applies for Services etc.

**Comment by jonneymendoza** [comment]
Has this been properly fixed yet on robolectric?

**Comment by jongerrish** [comment]
See
https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-multidex/src/main/java/org/robolectric/shadows/ShadowMultiDex.java

**Comment by dfpalomar** [comment]
The link @jongerrish suggest is broken, this is the correct one: https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-multidex/src/main/java/org/robolectric/shadows/multidex/ShadowMultiDex.java

**Comment by Aeiric** [comment]
@spardhan hi,i got the same problem,have you solved this ,any good ideas?thanks~

**Comment by Aeiric** [comment]
@dfpalomar i have tried the solution you mentioned above,but still failed ,and https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-multidex/src/main/java/org/robolectric/shadows/multidex/ShadowMultiDex.java is not clear,could you paste your code ?0.0

**Comment by pnadar** [comment]
I used 
```
    if (!"robolectric".equals(Build.FINGERPRINT)) {
      MultiDex.install(this);
    }
```
