### ISSUE TITLE
Could not find any resource  from reference ResName{com.company.app:style/Theme_AppCompat_Light_NoActionBar}

### ISSUE THREAD

**Issue by loeschg** [robolectric/robolectric#1334]
My tests have started failing since adding appcompat-v7 (21.0.0) due to what seems is a missing style/theme resource. All of my activities now inherit from ActionBarActivity. I was following this issue (https://github.com/robolectric/robolectric/issues/1332), but I was told to open a separate issue with my specific problem.

I have tried setting `@config(reportSdk = 18, emulateSdk = 18)` and have also tried using the 2.4-SNAPSHOT.

In case it's of relevance, I've set up my robolectric tests as a separate module (following this - http://blog.blundell-apps.com/android-gradle-app-with-robolectric-junit-tests/).

```
java.lang.RuntimeException: Could not find any resource  from reference ResName{com.company.app:style/Theme_AppCompat_Light_NoActionBar} from style StyleData{name='AppTheme_Base', parent='Theme_AppCompat_Light_NoActionBar'} with theme null
    at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getParent(ShadowAssetManager.java:456)
    at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:394)
    at org.robolectric.shadows.ShadowResources.getOverlayedThemeValue(ShadowResources.java:297)
    at org.robolectric.shadows.ShadowResources.findAttributeValue(ShadowResources.java:286)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:189)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:48)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:494)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:489)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:484)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:380)
    at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:143)
    at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:139)
    at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
    at com.company.app.view.activity.BaseActivity.onCreate(BaseActivity.java:31)
    at com.company.app.view.activity.HomeActivity.onCreate(HomeActivity.java:36)
    at android.app.Activity.performCreate(Activity.java:5133)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:113)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:265)
    at org.robolectric.util.ActivityController.create(ActivityController.java:110)
    at org.robolectric.util.ActivityController.create(ActivityController.java:120)
    at com.company.app.view.activity.HomeActivityTest.setup(HomeActivityTest.java:16)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:267)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:194)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by loeschg** [comment]
(Mainly to remind myself when I google this months later)

Also, remember to change your project.properties file when you update the support library in your build.gradle file.

**Comment by benwilcock** [comment]
I appreciate this thread is closed, but just in case it's helpful I've created a sample Gradle project that integrates Robolectric, Robotium, Android Instrumentation and standard Java JUnit 4 tests. It works with Android Studio 1.1 P1 and provides a starting template for new projects or just clues for configuring your own project. Thanks to @sjorsgeelen and @loeschg above for figuring out the Robolectric 'AppCompat' path issue!

The Code Sample / Gradle Template project can be found here:- 

https://github.com/benwilcock/android-alltest-gradle-sample

Good luck!

**Comment by RomainPiel** [comment]
I'm wondering if this issue is related to something in particular in the aar? I'm not having any issues with support libraries but it's failing with another third party library. Any idea?

**Comment by RomainPiel** [comment]
Oh I figured it's the same problem at the end. This library depends on appcompat-v7
