### ISSUE TITLE
Resource$NotFoundException influenced from previous tests

### ISSUE THREAD

**Issue by emartynov** [robolectric/robolectric#1373]
I'm discovering tests interference. We added new tests for one (DiaryEntryActivity) activity and it started producing exception for another (LoginActivity) activity first test.

If I carefully review stacktrace for  failed test I see that showing ProgressDialog from second activity is trying to inflate options for first activity:
```
   android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0001
        at android.content.res.Resources.getValue(Resources.java:1118)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
        at android.content.res.Resources.getLayout(Resources.java:934)
        at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:115)
        at com.minddistrict.android.ui.activity.DiaryEntryActivity.onCreateOptionsMenu(DiaryEntryActivity.java:197)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2504)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
        at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
        at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
        at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
        at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
        at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
        at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
        at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:34)
        at android.view.ViewGroup.addView(ViewGroup.java)
        at android.view.ViewGroup.addView(ViewGroup.java:3353)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.app.ProgressDialog.onCreate(ProgressDialog.java:164)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:355)
        at android.app.Dialog.show(Dialog.java:260)
        at org.robolectric.shadows.ShadowDialog.show(ShadowDialog.java:65)
        at org.robolectric.shadows.ShadowAlertDialog.show(ShadowAlertDialog.java:99)
        at android.app.Dialog.show(Dialog.java)
        at com.minddistrict.android.ui.activity.BaseActivity.showRequestProgressDialog(BaseActivity.java:164)
        at com.minddistrict.android.ui.activity.LoginActivity.startForgotEmail(LoginActivity.java:184)
...
```

What can be the issue?

**Comment by emartynov** [comment]
Issue resolved with answer from here:
https://github.com/robolectric/robolectric/issues/898
