### ISSUE TITLE
Android resource not found

### ISSUE THREAD

**Issue by romainpiel** [robolectric/robolectric#1375]
I'm having a hard time with robolectric because I'm trying to use and android resource and robolectric doesn't find it. The resource I'm trying to inflate contains this:

```
        < MultiAutoCompleteTextView
            android:layout_height="wrap_content"
            android:layout_width="match_parent"
            android:popupBackground="@android:drawable/dialog_holo_light_frame"
            android:dropDownAnchor="@id/address_bar"
            android:dropDownVerticalOffset="@dimen/space_small"/>
```

Robolectric fails on the resource `@android:drawable/dialog_holo_light_frame`. Here is the stack trace:

```
.....
Caused by: android.content.res.Resources$NotFoundException: can't find file for ResName{android:drawable/dialog_holo_light_frame}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:90)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:51)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:226)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:201)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:44)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:491)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:416)
    at android.widget.PopupWindow.__constructor__(PopupWindow.java:183)
    at android.widget.PopupWindow.<init>(PopupWindow.java:179)
    at android.widget.ListPopupWindow.__constructor__(ListPopupWindow.java:199)
    at android.widget.ListPopupWindow.<init>(ListPopupWindow.java:197)
    at android.widget.ListPopupWindow.<init>(ListPopupWindow.java:185)
    at android.widget.AutoCompleteTextView.__constructor__(AutoCompleteTextView.java:139)
    at android.widget.AutoCompleteTextView.<init>(AutoCompleteTextView.java:137)
    at android.widget.MultiAutoCompleteTextView.<init>(MultiAutoCompleteTextView.java:71)
    at android.widget.MultiAutoCompleteTextView.<init>(MultiAutoCompleteTextView.java:67)
.....
```

Any ideas?

If there's no direct solution for now. Is there a way to mock the resource instead of looking for it?

**Comment by tomykaira** [comment]
I got into the same problem, and resolved by tweaking at `ResourceLoader`.
This technique is only applicable when the resource itself has nothing to do with test results, but better at not tainting production code.
https://gist.github.com/tomykaira/0c11df447cc1728b6e88
