### ISSUE TITLE
BluetoothAdapter.getDefaultAdapter() causes NoClassDefFoundError on API 16

### ISSUE THREAD

**Issue by ctsimmonds** [robolectric/robolectric#1384]
I'm testing some code targeting API level 16 that calls BluetoothAdapter.getDefaultAdapter(), and when I do, it generates an exception:
java.lang.NoClassDefFoundError: android/bluetooth/BluetoothAdapter$LeScanCallback
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.getMethod0(Class.java:2856)
	at java.lang.Class.getMethod(Class.java:1668)
	at org.robolectric.bytecode.ShadowWrangler.getMethod(ShadowWrangler.java:172)
	at org.robolectric.bytecode.ShadowWrangler.getShadowedMethod(ShadowWrangler.java:167)
	at org.robolectric.bytecode.ShadowWrangler.calculatePlan(ShadowWrangler.java:106)
	at org.robolectric.bytecode.ShadowWrangler.methodInvoked(ShadowWrangler.java:80)
	at org.robolectric.bytecode.RobolectricInternals.methodInvoked(RobolectricInternals.java:47)
	at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java)
	at com.avaya.android.flare.util.AudioProfileManagerImpl.<init>(AudioProfileManagerImpl.java:195)
	at sun.reflect.GeneratedConstructorAccessor42.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:85)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	... 35 more

The problem is that the interface LeScanCallback is only available in API 18 and higher, so the references to it inside ShadowBluetoothAdapter are causing this exception.

**Comment by erd** [comment]
This should be fixed in c639b9951bc8a740361255c4a3f7946e18bd3b8e.
