### ISSUE TITLE
Drawable references can't be inflated (Resources$NotFoundException)

### ISSUE THREAD

**Issue by jbruchanov** [robolectric/robolectric#1395]
Create simple resource xml file in res/values
Add drawable reference
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <drawable name="promo_header_product_background">@drawable/button_black_background</drawable>
</resources>
```

Btw. would be hard to create some global inflation factory to be able hook up similar cases when robolectric can't inflate whatever and provide expected value by own code ?
I guess it would be really helpful for similar resource related issues...

Stack:
```
Caused by: android.content.res.Resources$NotFoundException: can't find file for ResName{com.scurab.sampleit:drawable/promo_header_product_background}
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:90)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:51)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:226)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:201)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:44)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:491)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:416)
	at android.view.View.__constructor__(View.java:3317)
	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
	at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
	at org.robolectric.bytecode.RobolectricInternals.invokeConstructor(RobolectricInternals.java:148)
	at org.robolectric.shadows.ShadowView.__constructor__(ShadowView.java:64)
	at android.view.View.<init>(View.java:3315)
	at android.widget.TextView.<init>(TextView.java:619)
	at android.widget.TextView.<init>(TextView.java:614)
	at com.scurab.sampleit.widget.FontTextView.<init>(FontTextView.java:24)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.scurab.sampleit.samples.SamplesFragment.onInflateView(SamplesFragment.java:70)
	at com.scurab.sampleit.fragment.BaseFragment.onCreateView(BaseFragment.java:44)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1504)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
	at android.support.v4.app.Fragment.performStart(Fragment.java:1525)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:972)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:450)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:48)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:210)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:58)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:53)
	at android.os.Handler.post(Handler.java)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1390)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
	at com.scurab.sampleit.TestHelper.startFragment(TestHelper.java:57)
	at com.scurab.sampleit.TestHelper.startFragment(TestHelper.java:48)
	at com.scurab.sampleit.TestHelper.startFragment(TestHelper.java:38)
	at com.scurab.sampleit.TestHelper.startFragment(TestHelper.java:34)
	at com.scurab.sampleit.samples.SamplesMainFragmentTest.testOpensSamplesFragmentByDefault(SamplesMainFragmentTest.java:32)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:77)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	... 1 more
```

**Comment by erd** [comment]
Consolidating this into #1554.
