### ISSUE TITLE
NullPointerException when trying to getWritableDatabase

### ISSUE THREAD

**Issue by wuman** [robolectric/robolectric#1408]
Running into problems with robolectric version 2.4 when trying to getWritableDatabase.

```
java.lang.NullPointerException
    at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:295)
    at java.util.ComparableTimSort.sort(ComparableTimSort.java:171)
    at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
    at java.util.Arrays.sort(Arrays.java:472)
    at java.util.Collections.sort(Collections.java:155)
    at org.robolectric.res.ResBunch.put(ResBunch.java:34)
    at org.robolectric.res.ValueResourceLoader.processNode(ValueResourceLoader.java:36)
    at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
    at org.robolectric.res.ValueResourceLoader.processResourceXml(ValueResourceLoader.java:19)
    at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:50)
    at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:72)
    at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:61)
    at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:42)
    at org.robolectric.res.PackageResourceLoader.loadEverything(PackageResourceLoader.java:30)
    at org.robolectric.res.PackageResourceLoader.doInitialize(PackageResourceLoader.java:17)
    at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
    at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:53)
    at org.robolectric.res.PackageResourceLoader.getValue(PackageResourceLoader.java:3)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:316)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:312)
    at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:69)
    at android.content.res.AssetManager.getResourceText(AssetManager.java)
    at android.content.res.Resources.getText(Resources.java:235)
    at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:363)
    at android.content.res.Resources.getText(Resources.java)
    at android.content.res.Resources.getString(Resources.java:325)
    at android.database.sqlite.SQLiteGlobal.getDefaultJournalMode(SQLiteGlobal.java:74)
    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:717)
    at org.robolectric.shadows.ShadowContext.openOrCreateDatabase(ShadowContext.java:136)
    at org.robolectric.shadows.ShadowContextWrapper.openOrCreateDatabase(ShadowContextWrapper.java:370)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
```

**Comment by rockerhieu** [comment]
I got another NPE:
```
java.lang.NullPointerException
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:321)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:717)
	at org.robolectric.shadows.ShadowContext.openOrCreateDatabase(ShadowContext.java:133)
	at org.robolectric.shadows.ShadowContextWrapper.openOrCreateDatabase(ShadowContextWrapper.java:385)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
```

**Comment by jongerrish** [comment]
I see the same thing. Can you open an issue for this, I'll take a look soon.

**Comment by rockerhieu** [comment]
@jongerrish here it is https://github.com/robolectric/robolectric/issues/1465

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
