### ISSUE TITLE
NullPointerException when making activity visible in 3.0

### ISSUE THREAD

**Issue by miketrewartha** [robolectric/robolectric#1443]
I'm in the process of migrating up to 3.0 (trying it out because of the support for API 21, mostly) and I'm not quite sure if I'm doing something wrong or this is a legit bug. I'm getting a lot of NPEs when making activities visible... all of this code worked great when running 2.4, so I know my activities themselves are set up properly. Am I supposed to be doing anything differently in 3.0 in regards to using ActivityControllers? I'm basically doing this:

`Robolectric.buildActivity(MyActivity.class).withIntent(intent).create().visible();`

Sometimes I'm also doing the other methods like `start()`, `resume()`, etc... Here's the stack trace I'm getting. Any idea what gives?

```
java.lang.NullPointerException
	at android.text.StaticLayout.generate(StaticLayout.java:366)
	at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
	at android.text.DynamicLayout.__constructor__(DynamicLayout.java:171)
	at android.text.DynamicLayout.<init>(DynamicLayout.java:100)
	at android.widget.TextView.makeSingleLayout(TextView.java:6389)
	at android.widget.TextView.makeNewLayout(TextView.java:6287)
	at android.widget.TextView.onMeasure(TextView.java:6644)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:447)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:682)
	at org.robolectric.shadows.ShadowHandler.routeMessage(ShadowHandler.java:126)
	at org.robolectric.shadows.ShadowHandler.access$100(ShadowHandler.java:26)
	at org.robolectric.shadows.ShadowHandler$1.run(ShadowHandler.java:111)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:250)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:289)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.visible(ActivityController.java:165)
	<last line is whatever line is in the tests, calling visible() on the activity controller>
```

**Comment by erd** [comment]
I ran into this last week and I think it has to do with how `TextView` performs layout. There's a native method in API 21 that's not shadowed by Robolectric, which leads to this exception. I should have a fix for this in the next few days.

**Comment by miketrewartha** [comment]
Very nice, appreciate it!
