### ISSUE TITLE
PrepareForTest android.os.Handler

### ISSUE THREAD

**Issue by ebortolini** [robolectric/robolectric#1452]
Hi,
I am trying to use PowerMockito.whenNew in a class that extends from "android.os.Handler".

In my test class:

@Config(emulateSdk = 18)
@RunWith(RobolectricTestRunner.class)
@PowerMockIgnore({ "org.mockito._", "org.robolectric._", "android.*" })
@PrepareForTest(SendOperationLogsHandler.class)
public class SendOperationLogsHandlerTests {
       @Rule
    public final PowerMockRule rule = new PowerMockRule();
.....

@Test
    public void handleMessageWithSuccess() throws Exception {
....
final OperationLog operationLog = Mockito.mock(OperationLog.class);
        PowerMockito.whenNew(OperationLog.class).withAnyArguments().thenReturn(operationLog);
....
}

}

SendOperationLogsHandler.class this class extends from Handler class.

I used this scenario other times with other classes and worked fine, but looks that extending from Handler causes some problems ... When I try to run this the following error occurs:

com.thoughtworks.xstream.converters.ConversionException: Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
---- Debugging information ----
message             : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
cause-exception     : java.lang.IllegalStateException
cause-message       : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
class               : org.junit.internal.runners.statements.InvokeMethod
required-type       : org.junit.internal.runners.statements.InvokeMethod
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/fNext/fTarget
line number         : 12
class[1]            : org.junit.internal.runners.statements.RunBefores
class[2]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[3]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available

I have no idea why this error happens.

**Comment by ebortolini** [comment]
Thank you very much for your help.

I already used this scenario with success, similar with cases that are posted in your link. I suspect that can be something related to the specific class that I am using, but I don't know what.
If I don't extends Handler class in SendOperationLogsHandler works fine.

Best Regards

**Comment by psmorandi** [comment]
@erd Actually, Robolectric indeed works with PowerMock. The issue #1058 that you refer has some example of this. @WonderCsabo has some example in his github showing how to integrate both. @ebortolini can you paste the stacktrace of this exception?

**Comment by ebortolini** [comment]
stacktrace of exception:

 com.thoughtworks.xstream.converters.ConversionException: Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
---- Debugging information ----
message             : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
cause-exception     : java.lang.IllegalStateException
cause-message       : Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
class               : org.junit.internal.runners.statements.InvokeMethod
required-type       : org.junit.internal.runners.statements.InvokeMethod
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/fNext/fTarget
line number         : 12
class[1]            : org.junit.internal.runners.statements.RunBefores
class[2]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[3]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1040)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1031)
	at org.powermock.classloading.DeepCloner.clone(DeepCloner.java:54)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:89)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:250)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:177)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: Failed to transform class with name android.os.Handler. Reason: android.os.IMessenger
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:256)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:180)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:259)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:180)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.buildMap(FieldDictionary.java:136)
	at com.thoughtworks.xstream.converters.reflection.FieldDictionary.fieldOrNull(FieldDictionary.java:113)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.getFieldOrNull(PureJavaReflectionProvider.java:193)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.canAccess(AbstractReflectionConverter.java:61)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.canConvert(ReflectionConverter.java:41)
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:56)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:498)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:56)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 48 more
Caused by: javassist.NotFoundException: android.os.IMessenger
	at javassist.ClassPool.get(ClassPool.java:450)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:592)
	at javassist.bytecode.Descriptor.getReturnType(Descriptor.java:489)
	at javassist.CtBehavior.getReturnType0(CtBehavior.java:306)
	at javassist.CtMethod.getReturnType(CtMethod.java:217)
	at org.powermock.core.transformers.impl.MainMockTransformer.modifyMethod(MainMockTransformer.java:172)
	at org.powermock.core.transformers.impl.MainMockTransformer.allowMockingOfStaticAndFinalAndNativeMethods(MainMockTransformer.java:142)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:65)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:251)
	... 73 more

I used the same approach for other classes and worked fine, looks that extending Handler class is messing something.

**Comment by WonderCsabo** [comment]
@psmorandi i am afraid this will not work with my method. I use `@PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*" })`, so `PowerMock` does not mess up classes which will be shadowed by `Robolectric`. Unfortunately @ebortolini want to mock an Android class which is on the ignore list.

**Comment by ebortolini** [comment]
Actually I am testing only the extended class, I don't need explicitly test Handler class. There is a way to tell PowerMock to ignore Hanlder class?

**Comment by WonderCsabo** [comment]
@ebortolini You already told `PowerMock` to ignore that in the `@PowerMockIgnore({ "org.mockito.", "org.robolectric.", "android.*" })` annotation, that is the problem. Unfortunately it seems `PowerMock` must transform the parent classes as well.
