### ISSUE TITLE
Error inflating class android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by thincal** [robolectric/robolectric#1453]
**test env**
android studio:1.0.1
robolectric:2.4
sdk-17

**build.gradle**
dependencies {
    // needed libraries
    compile 'com.android.support:support-v4:+'
    compile ('com.android.support:recyclerview-v7:+')

    // Test libraries
    androidTestCompile 'junit:junit:4.11'
    androidTestCompile 'org.robolectric:robolectric:2.4'
}

**error info**
build is ok, but when running the test, it reports bellow error:

android.view.InflateException: XML file /home/zhaoliang/git/test-glass-apps/launcher/build/intermediates/res/debug/layout/card_launcher.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.widget.RecyclerView
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at cn.test.glasswidget.cardview.GlassCardListView.init(GlassCardListView.java:103)
	at cn.test.glasswidget.cardview.GlassCardListView.<init>(GlassCardListView.java:59)
	at cn.test.glasslauncher.launcher.GlassLauncherActivity.onCreate(GlassLauncherActivity.java:34)
	at android.app.Activity.performCreate(Activity.java:5104)
	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
	at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:1388)
	at cn.test.glasslauncher.launcher.GlassLauncherActivityTest.testActivityFound(GlassLauncherActivityTest.java:27)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)

**Comment by thincal** [comment]
Btw the card_launcher.xml is:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="cn.test.glasslauncher.launcher.GlassLauncherActivity" >

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerview_horizontal"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="horizontal" />

</LinearLayout>

**Comment by thincal** [comment]
I test with another TestView created by myself, and inflate it from a related xml file, it still reports the error:
**line #-1 (sorry, not yet implemented): Error inflating class cn.test.TestView.**

And the layout inflate code is:
View contentView = LayoutInflater.from(mContext).inflate(R.layout.test_view, this)" 

so what's wrong here ? it works in a normal build but failed in the test.

**Comment by thincal** [comment]
this issue is always present if using the jdk6, but will be gone when run test in the second time if using jdk7 or jdk8.

anyway, since that I still can't find a final solution, but it is fine when using jdk7/8 if I build the project first then run test.

Hope it will help other people if meet same issue.

**Comment by SNeugber** [comment]
What a timely coincidence. I've just come across the same error, but for me using a newer JDK didn't help (I upgraded from 7 to 8).

**Comment by SNeugber** [comment]
In case anyone else is stuck here:

**Comment by erd** [comment]
This should be fixed with the `RobolectricGradleTestRunner` support added in 3.0.

**Comment by skimarxall** [comment]
I am having problems with this still in the 3.0 version.

```
android.view.InflateException: XML file .\src\test\..\main\res\layout\search_activity.xml line #-1 (sorry, not yet implemented): Error inflating class fragment
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
```
And the search_activity has a fragment inside the layout that this fragment has a RecyclerView if I remove the recylcerview works, so I guess is because of that.

Gradle file:
```gradle
    testCompile('org.robolectric:robolectric:3.0') {
        exclude module: 'commons-logging'
        exclude module: 'httpclient'
    }
    testCompile 'org.robolectric:shadows-multidex:3.0'
    testCompile 'org.robolectric:shadows-support-v4:3.0'
```

Any solution?

**Comment by bes1002t** [comment]
http://stackoverflow.com/questions/18741485/caused-by-java-lang-unsupportedoperationexception-cant-convert-to-dimension

Look at your dimension values
