### ISSUE TITLE
getFragmentManager() - IllegalStateException: Recursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by StefMa** [robolectric/robolectric#1460]
Here my simple configuration:
NestedTestFragment
```
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootview = inflater.inflate(R.layout.fragment_nested_test, container, false);

        getFragmentManager().beginTransaction().add(R.id.nested_test_frame, new NestedTestFragment1()).commit();

        return rootview;
    }
```
NestedTestFragment1
```
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootview = inflater.inflate(R.layout.fragment_nested_test, container, false);
        return rootview;
    }

```
The Fragments are booth from ```android.app.Fragment``` NOT from support-lib

The Fragments are working fine in API 14+ 
But when I run a test I got the following error:
```

java.lang.IllegalStateException: Recursive entry to executePendingTransactions
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1407)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:34)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:3322)
	at android.view.ViewGroup.addView(ViewGroup.java:3298)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:896)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:48)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
	at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:210)
	at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:58)
	at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:53)
	at android.os.Handler.post(Handler.java)
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
	at android.app.BackStackRecord.commit(BackStackRecord.java:574)
	at org.robolectric.util.FragmentTestUtil.startVisibleFragment(FragmentTestUtil.java:36)
	at my.package.android.robolectric.NestedFragmentTest.setup(NestedFragmentTest.java:29)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

I can use ```getChildFragmentManager()``` and ```android.support.v4.Fragment``` then it works. But that isn't the right way, I think when Android can handle ```getFragmentManager()``` with Fragments should Robolectric this too...

**Comment by StefMa** [comment]
Forgot my testCase :-) 
That's a simple 
```
NestedFragment frag = new NestedFragment() ;
FragmentTestUtil.startVisibleFragment(frag)
```

**Comment by StefMa** [comment]
Fixed that issue by these lines of code:
```java
        NestedTestFragment fragment = new NestedTestFragment();
        Robolectric.pauseMainLooper();
        FragmentTestUtil.startVisibleFragment(fragment);
        Robolectric.getUiThreadScheduler().advanceToLastPostedRunnable();
```

**Comment by KenVanHoeylandt** [comment]
For Robolectric version 3.0, the code would be:
```
Robolectric.getBackgroundThreadScheduler().pause();
FragmentTestUtil.startVisibleFragment(fragment);
Robolectric.getBackgroundThreadScheduler().unpause();
```

**Comment by KioKrofovitch** [comment]
For Robolectric version 3.1, this worked for me:

```
ShadowLooper.pauseMainLooper();
SupportFragmentTestUtil.startVisibleFragment(myFragment);
Robolectric.getForegroundThreadScheduler().advanceToLastPostedRunnable();
```

**Comment by myronkwan** [comment]
Does anyone have an explanation for this solution?
