### ISSUE TITLE
NullPointerException at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:321)

### ISSUE THREAD

**Issue by rockerhieu** [robolectric/robolectric#1465]
I'm trying to upgrade to `3.0-SNAPSHOT` to see whether it support appcompat v21 or not. But most of the test are failed because of this:
```
java.lang.NullPointerException
    at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:321)
    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
    at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:717)
    at org.robolectric.shadows.ShadowContext.openOrCreateDatabase(ShadowContext.java:133)
    at org.robolectric.shadows.ShadowContextWrapper.openOrCreateDatabase(ShadowContextWrapper.java:385)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
```

**Comment by erd** [comment]
Could you re-test this against the most recent snapshot? There were commits on 1/12 that look to have fixed the problem.

**Comment by erd** [comment]
Please re-open if the most recent snapshot still has this problem.
