### ISSUE TITLE
V3_0_SNAPSHOT - ShadowLocaleData requires version specific shadow

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1468]
Looks like LocaleData.minusSign has changed from a char to String type.

Caused by: java.lang.NoSuchFieldError: minusSign
	at org.robolectric.shadows.ShadowLocaleData.setEnUsLocaleData(ShadowLocaleData.java:75)
	at org.robolectric.shadows.ShadowLocaleData.get(ShadowLocaleData.java:24)
	at libcore.icu.LocaleData.get(LocaleData.java)
	at libcore.icu.LocaleData.__staticInitializer__(LocaleData.java:40)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:177)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:40)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:98)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:13)
	at libcore.icu.LocaleData.<clinit>(LocaleData.java)
	at android.widget.NumberPicker$TwoDigitFormatter.getZeroDigit(NumberPicker.java:183)
	at android.widget.NumberPicker$TwoDigitFormatter.init(NumberPicker.java:168)
	at android.widget.NumberPicker$TwoDigitFormatter.__constructor__(NumberPicker.java:163)
	at android.widget.NumberPicker$TwoDigitFormatter.<init>(NumberPicker.java)
	at android.widget.NumberPicker.__staticInitializer__(NumberPicker.java:191)

**Comment by jongerrish** [comment]
The following PR fixes this issue by generating version specific shadows where necessary and building them against the corresponding version of the SDK https://github.com/robolectric/robolectric/pull/1470
