### ISSUE TITLE
V3 Snapshot: When running Config.emulateSdk == 18 fail to load API 21 class definition

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1471]
The code in question has a guard around the API 21 method calls as follows:

if (VERSION.SDK_INT >= VERSION_CODES.LOLLIPOP) {
  frameLayout.setOnApplyWindowInsetsListener(new OnApplyWindowInsetsListener() {
    ...
  }
}

However I think this is failing because we still require the import:

import android.view.View.OnApplyWindowInsetsListener;

Caused by: java.lang.ClassNotFoundException: android.view.View$OnApplyWindowInsetsListener
	at org.robolectric.internal.bytecode.AsmInstrumentingClassLoader.getByteCode(AsmInstrumentingClassLoader.java:164)
	at org.robolectric.internal.bytecode.AsmInstrumentingClassLoader.findClass(AsmInstrumentingClassLoader.java:121)
	at org.robolectric.internal.bytecode.AsmInstrumentingClassLoader.loadClass(AsmInstrumentingClassLoader.java:93)
	... 28 more

**Comment by erd** [comment]
Is this still an issue? I feel like we discussed this in person a few months back...

**Comment by erd** [comment]
The `Views$OnApplyWindowInsetsListener` failure is similar to #1633.
