### ISSUE TITLE
Issue shadowing YouTubePlayerSupportFragment

### ISSUE THREAD

**Issue by pivotal-nachos** [robolectric/robolectric#1527]
Hey all,

We are having an issue with [our fork of 2.4](https://github.com/pivotal-nachos/robolectric), that has very minimal changes.  The fork adds a few packages to the list of packages to instrument by the ASMInstrumentingClassLoader, most relevantly "com.google.android.youtube.".

We recently attempted to upgrade from the YouTube Player Api 1.0.0 to 1.2.1, and doing so caused a strange error during class loading.  Has anyone tried this before, or seen something like it?

[Here is a minimal project](https://github.com/pivotal-nachos/robolectric-youtube-player-error-reproduction) that has reproduction, although you have to install [our fork of robolectric](https://github.com/pivotal-nachos/robolectric) manually.

Here is the stacktrace we are seeing:

```
java.lang.NoClassDefFoundError: com/google/android/youtube/player/YouTubePlayerView
    at com.example.robolectric.DeckardActivity.playYoutube(DeckardActivity.java:32)
    at com.example.robolectric.DeckardActivity$1.run(DeckardActivity.java:26)
    at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
    at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
    at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
    at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
    at org.robolectric.util.ActivityController.create(ActivityController.java:111)
    at org.robolectric.util.ActivityController.create(ActivityController.java:122)
    at com.example.activity.DeckardActivityRobolectricTest.testSomething(DeckardActivityRobolectricTest.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: couldn't load com.google.android.youtube.player.YouTubePlayerView
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.findClass(AsmInstrumentingClassLoader.java:155)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.loadClass(AsmInstrumentingClassLoader.java:98)
    ... 56 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.Frame.a(Unknown Source)
    at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
    at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
    at org.objectweb.asm.tree.ClassNode.accept(Unknown Source)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.getInstrumentedBytes(AsmInstrumentingClassLoader.java:276)
    at org.robolectric.bytecode.AsmInstrumentingClassLoader.findClass(AsmInstrumentingClassLoader.java:147)
    ... 57 more
```

**Comment by jaredsburrows** [comment]
@pivotal-nachos Can you please try using Robolectric 3.0-rc3?

@erd They are using an old fork of Robolectric. Unless we have a test or they use the latest version, it is very difficult to reproduce this test.

**Comment by shadabunique** [comment]
Any progress with this issue ?

**Comment by utzcoz** [comment]
Current Robolectric doesn't maintain the shadow of `YouTubePlayerSupportFragment`, and please try the latest Robolectric, and feel free to reopen it if this issue still exists.
