### ISSUE TITLE
IllegalStateException when running tests that create Activities with Robolectric 2.4

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#1531]
After upgrading out build to use android-maven-plugin 4.1.0, about 200 of our tests started to fail with the following error that were working with the 3.7.0 version of the plugin.  I'm not sure if this is an Robolectric compatibility issue, or if it is something in our project that is causing the issue.  I'm going to pos the same thing on the Android Maven Plugin forums as well.

I've checked our themes and they are extending from the appropriate Theme.AppCompat descendent.

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:151)
	at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:138)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
	at com.altair.fusion.android.injection.InjectingFragmentActivity.onCreate(InjectingFragmentActivity.java:11)
	at com.altair.fusion.android.activities.FusionFragmentActivity.onCreate(FusionFragmentActivity.java:95)
	at com.altair.fusion.android.activities.student.AbstractStudentActivity.onCreate(AbstractStudentActivity.java:53)
	at com.altair.fusion.android.activities.student.StudentActivity.onCreate(StudentActivity.java:35)
	at android.app.Activity.performCreate(Activity.java:5133)
	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
	at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
	at com.altair.fusion.android.activities.student.StudentActivityTest.restNavigationDrawerButtonStateEnablesMyWeekButtonWhenIntentIsMyClasses(StudentActivityTest.java:562)

**Comment by jaredsburrows** [comment]
@kingargyle Upgrade to Robolectric 3.0 and update your status.

**Comment by kingargyle** [comment]
I'll have to wait until a stable release is out, as I'm sure some of the work arounds we did to get around issues like this will need to be addressed at the same time.

**Comment by jaredsburrows** [comment]
> I'll have to wait until a stable release is out

Do you mean Robolectric 3.0 release? Robolectric 3.0 rc2 has solved all my Robolectric 2.4 issues. Make a branch and quickly update your tests, not much has changed in the API that would break your tests.

**Comment by jaredsburrows** [comment]
@erd  There is no way to reproduce these tests and their issues started because of a newly introduced dependency. Also they are using Robolectric 2.4 instead of 3.0+, unless we can reproduce this, can we just close?
