### ISSUE TITLE
Robolectric 3.0 SNAPSHOT crashes using OpenJDK 1.7 on Ubuntu

### ISSUE THREAD

**Issue by argestes** [robolectric/robolectric#1541]
Tests crash with following stacktrace. Some of the stacktrace is omitted.

```
java.lang.NoClassDefFoundError: android/support/v4/view/OnApplyWindowInsetsListener
	at android.support.v7.app.ActionBarActivityDelegate.createDelegate(ActionBarActivityDelegate.java:51)
	at android.support.v7.app.ActionBarActivity.getDelegate(ActionBarActivity.java:557)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
	at roboguice.activity.RoboActionBarActivity.onCreate(RoboActionBarActivity.java:88)
...

Caused by: java.lang.ClassNotFoundException: android.support.v4.view.OnApplyWindowInsetsListener
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:166)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
	at android.support.v7.app.ActionBarActivityDelegate.$$robo$$ActionBarActivityDelegate_7c55_createDelegate(ActionBarActivityDelegate.java:51)
	at android.support.v7.app.ActionBarActivityDelegate.createDelegate(ActionBarActivityDelegate.java)
	at android.support.v7.app.ActionBarActivity.$$robo$$ActionBarActivity_eab0_getDelegate(ActionBarActivity.java:557)
	at android.support.v7.app.ActionBarActivity.getDelegate(ActionBarActivity.java)
	at android.support.v7.app.ActionBarActivity.$$robo$$ActionBarActivity_eab0_onCreate(ActionBarActivity.java:123)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java)
	at roboguice.activity.RoboActionBarActivity.onCreate(RoboActionBarActivity.java:88)
```

This crash doesn't happen when using Oracle JDK 1.7 or 1.8

**Comment by karekondjula** [comment]
After endless hours of trying to work it out, using Oracle JDK 1.8, once again I get an error:

java.lang.NoClassDefFoundError: android/support/v4/view/ViewPropertyAnimatorListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:151)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
	at android.support.v7.app.ActionBarActivityDelegate.createDelegate(ActionBarActivityDelegate.java:51)
	at android.support.v7.app.ActionBarActivity.getDelegate(ActionBarActivity.java:557)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
	at com.navayo.secfone.ui.MyAndroidClass.onCreate(PinEntryActivity.java:37)

**Comment by argestes** [comment]
I think this is invalid and somehow related with #1385

**Comment by erd** [comment]
I don't think this particular issue has anything to do with OpenJDK. Double check the dependencies of your app and make sure you don't have two versions of the `support-v4` library on the classpath.
