### ISSUE TITLE
RuntimeException on XmlFileBuilder$XmlResourceParserImpl.getAttributeResourceValue

### ISSUE THREAD

**Issue by jaydp17** [robolectric/robolectric#1546]
Hello, I just started using Robolectric, went through the [samples](https://github.com/robolectric/robolectric-samples) and created a simple test.

I'm using [MaterialDesignLibrary](https://github.com/navasmdc/MaterialDesignLibrary)'s Progress bar circular indeterminate.

Here's the error I get

``` java
layout/activity_recent_chatlist.xml line #-1 (sorry, not yet implemented): Error inflating class com.gc.materialdesign.views.ProgressBarCircularIndeterminate
    at android.view.LayoutInflater.createView(LayoutInflater.java:633)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
    at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
    at com.example.RecentChatListActivity_.setContentView(RecentChatListActivity_.java:38)
    at com.example.RecentChatListActivity.onCreate(RecentChatListActivity.java:88)
    at com.example.RecentChatListActivity_.onCreate(RecentChatListActivity_.java:29)
    at android.app.Activity.performCreate(Activity.java:5933)
    at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
    at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:114)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
    at org.robolectric.util.ActivityController.create(ActivityController.java:110)
    at org.robolectric.util.ActivityController.create(ActivityController.java:121)
    at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
    at org.robolectric.Robolectric.setupActivity(Robolectric.java:41)
    at com.example.RecentChatListActivityTest.showList(RecentChatListActivityTest.java:30)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:607)
    at android.view.LayoutInflater.createView(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createViewFromTag(LayoutInflater.java:743)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:806)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:809)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:365)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.support.v7.app.ActionBarActivityDelegateBase.$$robo$$ActionBarActivityDelegateBase_c4c6_setContentView(ActionBarActivityDelegateBase.java:228)
    at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java)
    at android.support.v7.app.ActionBarActivity.$$robo$$ActionBarActivity_eab0_setContentView(ActionBarActivity.java:102)
    at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java)
    at com.example.RecentChatListActivity_.setContentView(RecentChatListActivity_.java:38)
    at com.example.RecentChatListActivity.onCreate(RecentChatListActivity.java:88)
    at com.example.RecentChatListActivity_.onCreate(RecentChatListActivity_.java:29)
    at android.app.Activity.$$robo$$Activity_c57b_performCreate(Activity.java:5933)
    at android.app.Activity.performCreate(Activity.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
    at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:114)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
    at org.robolectric.util.ActivityController.create(ActivityController.java:110)
    at org.robolectric.util.ActivityController.create(ActivityController.java:121)
    at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
    at org.robolectric.Robolectric.setupActivity(Robolectric.java:41)
    at com.example.RecentChatListActivityTest.showList(RecentChatListActivityTest.java:30)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ... 1 more
Caused by: java.lang.RuntimeException: huh?
    at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getAttributeResourceValue(XmlFileBuilder.java:648)
    at com.gc.materialdesign.views.ProgressBarCircularIndeterminate.setAttributes(ProgressBarCircularIndeterminate.java:37)
    at com.gc.materialdesign.views.ProgressBarCircularIndeterminate.<init>(ProgressBarCircularIndeterminate.java:25)
    ... 75 more
```

[ProgressBarCircularIndeterminate.java:37](https://github.com/navasmdc/MaterialDesignLibrary/blob/master/MaterialDesign/src/com/gc/materialdesign/views/ProgressBarCircularIndeterminate.java#L37) is

``` java
int bacgroundColor = attrs.getAttributeResourceValue("http://schemas.android.com/apk/res/android","background",-1);
```

Here's the layout it's trying to inflate

``` xml
<com.gc.materialdesign.views.ProgressBarCircularIndeterminate
                    android:id="@+id/progress"
                    android:layout_width="64dp"
                    android:layout_centerInParent="true"
                    android:layout_height="64dp"
                    android:background="#1E88E5"/>
```

The only thing I do in my test is create the activity and get it.

**Comment by AdamMTGreenberg** [comment]
I have the same issue with custom fonts. My stacktrace, using 2.4, is the following:
```
android.view.InflateException: XML file ./application/src/production/res/layout/fragment_enrollment_landing_layout.xml line #-1 (sorry, not yet implemented): Error inflating class Button
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.markonelifestyle.vessyl.app.ui.fragments.ProductionBaseFragment.onCreateView(ProductionBaseFragment.java:70)
	at android.app.Fragment.performCreateView(Fragment.java:1695)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.app.BackStackRecord.run(BackStackRecord.java:682)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
	at com.markonelifestyle.vessyl.app.ui.activities.LoginActivityTest.testActivity(LoginActivityTest.java:25)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.RuntimeException: huh?
	at org.robolectric.res.builder.XmlFileBuilder$XmlResourceParserImpl.getAttributeResourceValue(XmlFileBuilder.java:646)
	at uk.co.chrisjenx.calligraphy.CalligraphyUtils.pullFontPathFromView(CalligraphyUtils.java:167)
	at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:151)
	at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:133)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:170)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.onCreateView(CalligraphyLayoutInflater.java:146)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
	... 41 more

```
It looks like Robolectric in general has trouble with things that cannot be previewed in the editor, etc. I am hopeful someone will come up with a solution as the code throwing the error
```java
public int getAttributeResourceValue(String namespace, String attribute, int defaultValue) {
      String attr = getAttribute(namespace, attribute);
      if (attr == null) {
        return defaultValue;
      }
      if (attr.startsWith("@")) {
        return getResourceId(attr.substring(1), packageName, null);
      }
      throw new RuntimeException("huh?");
    }
```
looks like it simply cannot resolve the asset

**Comment by AdamMTGreenberg** [comment]
I solved the issue after digging in and seeing that any custom resource without an "@" appended in front of it in XML is most likely going to fail in your tests. My solution was basically to create an `Application` class in my test project that extends the default Application class and use `@Config(application = ApplicationTestClass.class)` to run it. In the class there is a protected variable `isTest`, setting it true in the test Application class and wrapping the calls that bind the XML with `(ApplicationTestClass)getApplication().isTest()` should allow you to bypass the crashes

**Comment by anooshm** [comment]
@AdamMTGreenberg - Could you please explain how you wrapped the calls ? I am using calligraphy to use custom fonts.

            <Button
                fontPath="fonts/*******.ttf"

My tests are failing when setContentView is called in OnCreate. I don't wish to remove Calligraphy for the sake of running testcases.

Is there any workaround for this?

**Comment by AdamMTGreenberg** [comment]
I just put the call to init Calligraphy in a separate method in the
Application class, then override it in my test Application class to not
register it. The same thing can be done in a module for testing as well on
init.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
