### ISSUE TITLE
Can't run tests in parallel with Failsafe plugin

### ISSUE THREAD

**Issue by TomRK1089** [robolectric/robolectric#1552]
When executing tests in parallel with the Maven Failsafe plugin, my tests fail with the following exception:

`java.lang.RuntimeException: java.lang.RuntimeException: you should only be calling this from the main thread!
        at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: you should only be calling this from the main thread!
        at org.robolectric.shadows.ShadowChoreographer.resetThreadLoopers(ShadowChoreographer.java:44)
        at org.robolectric.RobolectricBase.reset(RobolectricBase.java:1804)
        at org.robolectric.Robolectric.reset(Robolectric.java:1372)
        at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:37)
        at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:207)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`
thrown from the RobolectricTestRunner. 

Is there any support for parallel test execution? Failsafe should be working nearly identically to the Surefire plugin in this regard -- has anyone had success using Surefire to parallelize tests run with the RobolectricTestRunner?

**Comment by jaredsburrows** [comment]
What is the status of this?
What version of Robolectric are you testing with?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
