### ISSUE TITLE
Support resource references (for drawables)

### ISSUE THREAD

**Issue by pingpongboss** [robolectric/robolectric#1554]
I am hitting this error when running a Robolectric test.

`java.lang.NullPointerException
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:322)
    at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:310)
    at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:92)
    at android.content.res.AssetManager.getResourceValue(AssetManager.java)
    at android.content.res.Resources.getValue(Resources.java:1114)
    at android.content.res.Resources.getDrawable(Resources.java:693)`

My res/values/drawables.xml file contains a resource alias

```
<resources>

    <item name="drawable_res_id" type="drawable">@drawable/another_res_id</item>

</resources>
```

And the code calls `Resources.getDrawable(R.drawable.drawable_res_id);`

It seems like the ShadowAssetManager is not able to parse the resource alias.

**Comment by erd** [comment]
Could you test against 3.0-SNAPSHOT? I believe this was fixed.

**Comment by jaredsburrows** [comment]
@pingpongboss  What is the status of this?

**Comment by jaredsburrows** [comment]
@pingpongboss @erd 
I just tested this, the all fail:

    @Test
    public void test_drawableResources0() {
        // used of activity
        Activity activity = buildActivity(Activity.class).create().start().visible().get();
        ResourcesCompat.getDrawable(activity.getResources(), R.drawable.drawable_res_id, null);
    }

    @Test
    public void test_drawableResources1() {
        // deprecated as of api 21
        RuntimeEnvironment.application.getResources().getDrawable(R.drawable.drawable_res_id);
    }

    @Test
    public void test_drawableResources2() {
        // api 21
        RuntimeEnvironment.application.getResources().getDrawable(R.drawable.drawable_res_id, null);
    }

    @Test
    public void test_drawableResources3() {
        // v4
        ContextCompat.getDrawable(RuntimeEnvironment.application, R.drawable.drawable_res_id);
    }

    @Test
    public void test_drawableResources4() {
        // v4
        ResourcesCompat.getDrawable(RuntimeEnvironment.application.getResources(), R.drawable.drawable_res_id, null);
    }

**Comment by jaredsburrows** [comment]
@pingpongboss Have you tried this again?

**Comment by AndroidGecko** [comment]
having same issue on 3.1 - snapshot

**Comment by OpilkiInside** [comment]
The issue still exists on latest 3.1-snapshot

Caused by: java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:359)
	at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:104)
	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
	at android.content.res.Resources.getValue(Resources.java:1229)
	at android.content.res.Resources.getDimension(Resources.java:576)

**Comment by keith30xi** [comment]
Is `PackageResourceLoader.loadEverything()` missing `new ValueResourceLoader(data, "/resources/item[@type='drawable']", "drawable", ResType.DRAWABLE),`?
