### ISSUE TITLE
com.viewpagerindicator

### ISSUE THREAD

**Issue by AnirudhLoya** [robolectric/robolectric#1602]
java.lang.IllegalArgumentException: Missing required <application/> element in .\src\main\..\..\build\intermediates\exploded-aar\com.viewpagerindicator\library\2.4.1\AndroidManifest.xml
	at org.robolectric.AndroidManifest.parseAndroidManifest(AndroidManifest.java:155)
	at org.robolectric.AndroidManifest.getPackageName(AndroidManifest.java:474)
	at org.robolectric.AndroidManifest.getResourcePath(AndroidManifest.java:517)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:522)
	at org.robolectric.AndroidManifest.getIncludedResourcePaths(AndroidManifest.java:524)
	at org.robolectric.RobolectricTestRunner.createAppResourceLoader(RobolectricTestRunner.java:635)
	at org.robolectric.RobolectricTestRunner.getAppResourceLoader(RobolectricTestRunner.java:627)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:67)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

**Comment by erd** [comment]
There isn't enough information to debug this issue.
