### ISSUE TITLE
NullPointerException at MetaData.init(MetaData.java:59) when processing  Google Play Services meta-data

### ISSUE THREAD

**Issue by paulpv** [robolectric/robolectric#1606]
My app uses Google Play Services, and I have the following meta-data in my AndroidManifest.xml:
```
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />
```
This follows the Google documented steps at:
http://developer.android.com/google/play-services/setup.html#Setup

When I test my app, Robolectric crashes with the following callstack:
```
com.pebblebee.pebblebee.util.UtilTest > testIsValidPassword STANDARD_ERROR
java.lang.NullPointerException
at org.robolectric.manifest.MetaData.init(MetaData.java:55)
at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:367)
at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:398)
at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:71)
at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:223)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
...
```

I instrumented the Robolectric code to print out the meta-data values as it is processing them:
https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/manifest/MetaData.java
```
37:  public void init(ResourceLoader resLoader, String packageName) {
38:    ResourceIndex resIndex = resLoader.getResourceIndex();
39:
40:    if (!initialised) {
41:      for (Map.Entry<String,VALUE_TYPE> entry : typeMap.entrySet()) {
42:        String value = valueMap.get(entry.getKey()).toString();
43:        System.out.println("MetaData: init: value=" + value);
44:        if (value.startsWith("@")) {
45:          ResName resName = ResName.qualifyResName(value.substring(1), packageName, null);
46:          System.out.println("MetaData: init: resName=" + resName);
47:          VALUE_TYPE entryValue = entry.getValue();
48:          System.out.println("MetaData: init: entryValue=" + entryValue);
49:          switch (entryValue) {
50:            case RESOURCE:
51:              // Was provided by resource attribute, store resource ID
52:              valueMap.put(entry.getKey(), resIndex.getResourceId(resName));
53:              break;
54:            case VALUE:
55:              // Was provided by value attribute, need to parse it
56:              TypedResource<?> typedRes = resLoader.getValue(resName, "");
57:              System.out.println("MetaData: init: typedRes=" + typedRes);
58:              // The typed resource's data is always a String, so need to parse the value.
59:              switch (typedRes.getResType()) {
60:                case BOOLEAN: case COLOR: case INTEGER: case FLOAT:
61:                  valueMap.put(entry.getKey(), parseValue(typedRes.getData().toString()));
62:                  break;
63:                default:
64:                  valueMap.put(entry.getKey(),typedRes.getData());
65:              }
66:              break;
67:          }
68:        } else if (entry.getValue() == VALUE_TYPE.VALUE) {
69:          // Raw value, so parse it in to the appropriate type and store it
70:          valueMap.put(entry.getKey(), parseValue(value));
71:        }
72:      }
73:      // Finished parsing, mark as initialised
74:      initialised = true;
75:    }
76:  }
```
I then get the following output:
```
com.pebblebee.pebblebee.util.UtilTest > testIsValidPassword STANDARD_OUT
    MetaData: init: value=@integer/google_play_services_version
    MetaData: init: resName=ResName{com.pebblebee.pebblebee:integer/google_play_services_version}
    MetaData: init: entryValue=VALUE
    MetaData: init: typedRes=null

com.pebblebee.pebblebee.util.UtilTest > testIsValidPassword STANDARD_ERROR
    java.lang.NullPointerException
    	at org.robolectric.manifest.MetaData.init(MetaData.java:59)
    	at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:369)
    	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:400)
    	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:71)
    	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
...
```

Do other people not have this issue when using Google Play Services?
What might I be doing wrong, and/or how to fix this?
Shouldn't typedRes be at least tested for null?

Thanks,
Pv

**Comment by paulpv** [comment]
FYI: An identical problem occurs on robolectric 2.4.

**Comment by erd** [comment]
How are you running your tests?

**Comment by RobertoArtiles** [comment]
Same issue here. In my case I run it in the Android Studio via recently introduced unit tests support.

**Comment by erd** [comment]
Consolidating this into #1399.
