### ISSUE TITLE
Using the new google play services aar makes tests fail

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1607]
Hello,

I just realized that a modular google play services is out and I thought I should give it a shot.
In my previous setup with maven I had the following dependencies:

           <dependency>
                <groupId>com.google.android.gms</groupId>
                <artifactId>google-play-services</artifactId>
                <version>22.0.0</version>
                <type>apklib</type>
            </dependency>
            <dependency>
                <groupId>com.google.android.gms</groupId>
                <artifactId>google-play-services</artifactId>
                <version>22.0.0</version>
                <type>jar</type>
            </dependency>

and everything was working fine. I got these artifacts from the android-sdk-deployer, existing in 
android-sdk\extras\google\google_play_services

Now I moved to 

    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services</artifactId>
      <version>6.5.87</version>
      <type>aar</type>
    </dependency>

for the whole google play services artifact, or to 

      <dependency>
            <groupId>com.google.android.gms</groupId>
            <artifactId>play-services-location</artifactId>
            <version>6.5.87</version>
            <type>aar</type>
       </dependency>

for the modular one that only includes the location, maps and base aar that I am using.

As soon as I made this change, even though everything works fine when I run the app, when I run the Map Activity (an activity the contains a map fragment ) related tests I get the following exception:

    android.view.InflateException: XML file .\res\layout\map_activity.xml line #-1 (sorry, not yet             implemented): Error inflating class fragment
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:267)
    	at android.app.Activity.setContentView(Activity.java:1895)
    	at com.follower.activity.map.MapActivity_.setContentView(MapActivity_.java:53)
    	at com.follower.activity.map.MapActivity_.onCreate(MapActivity_.java:40)
    	at android.app.Activity.performCreate(Activity.java:5133)
    	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
    	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
    	at     org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
    	at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
    	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
    	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
    	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
    	at com.follower.activity.map.MapActivityTest.setUpActivity(MapActivityTest.java:106)
    	at com.follower.activity.map.MapActivityTest.setUp(MapActivityTest.java:91)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
    Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f08000d
    	at android.content.res.Resources.getText(Resources.java:239)
    	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:363)
    	at android.content.res.Resources.getText(Resources.java)
    	at android.content.res.Resources.getString(Resources.java:325)
    	at com.google.android.gms.common.GooglePlayServicesUtil.b(Unknown Source)
    	at com.google.android.gms.common.GooglePlayServicesUtil.b(Unknown Source)
    	at com.google.android.gms.dynamic.a.b(Unknown Source)
    	at com.google.android.gms.dynamic.a.b(Unknown Source)
    	at com.google.android.gms.dynamic.a.a(Unknown Source)
    	at com.google.android.gms.dynamic.a.a(Unknown Source)
    	at com.google.android.gms.dynamic.a.onCreateView(Unknown Source)
    	at com.google.android.gms.dynamic.a.onCreateView(Unknown Source)
    	at com.google.android.gms.maps.MapFragment.onCreateView(Unknown Source)
    	at com.google.android.gms.maps.MapFragment.onCreateView(Unknown Source)
    	at android.app.Fragment.performCreateView(Fragment.java:1695)
    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:861)
    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
    	at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1137)
    	at android.app.Activity.onCreateView(Activity.java:4746)
    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:689)
    	... 39 more

Mind you that map_activity.xml is the layout of that activity:

and it looks like this 

    <?xml version="1.0" encoding="utf-8"?>

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                    android:layout_width="fill_parent"
                    android:layout_height="fill_parent"
                    android:orientation="vertical">

        <fragment android:id="@+id/map_activity__map_fragment"
                  android:name="com.google.android.gms.maps.MapFragment"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"/>

        <com.myapp.activity.map.view.BottomActionBarView_     android:id="@+id/map_activity__bottom_action_bar_view"
                                                             android:background="#CC333333"
                                                             android:clickable="true"
                                                             android:visibility="invisible"
                                                             android:layout_width="match_parent"
                                                             android:layout_height="wrap_content"
                                                             android:layout_alignParentBottom="true"
                                                             android:gravity="center"/>

    </RelativeLayout>

Is there anything that I am missing ?

**Comment by athkalia** [comment]
Found what the problem was. As added the new library I forgot to add it in the project.properties file so that robolectric could fetch it, as discussed here
http://robolectric.org/configuring/
