### ISSUE TITLE
Robolectric can't handle metadata with android:resource

### ISSUE THREAD

**Issue by gruszczy** [robolectric/robolectric#1609]
Application meta-data like this causes NPE:
		 <meta-data android:name="my.name"
		   android:resource="@xml/my_xml" /> 

Caused by: java.lang.NullPointerException
	at org.robolectric.res.builder.DefaultPackageManager.metaDataToBundle(DefaultPackageManager.java:689)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:462)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:71)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:223)
	... 24 more

**Comment by jaredsburrows** [comment]
Where are you specifying `android:resource="@xml/my_xml" ` at? In your `AndroidManifest.xml`?

**Comment by gruszczy** [comment]
I don't have a repro for this anymore :( I would close it now.
