### ISSUE TITLE
SQLiteDatabase not working on Windows with Lollipop

### ISSUE THREAD

**Issue by steveydee82** [robolectric/robolectric#1616]
Environment: Eclipse, Windows, Android-21 project. Roboelectric 2.4 (also tried 3.0-SNAPSHOT on 11/03/15)

Trying to create a SQLiteDatabase instance throws the following error:

java.lang.NullPointerException
    at android.database.sqlite.SQLiteGlobal.getDefaultJournalMode(SQLiteGlobal.java:74)
    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:287)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
    at com.genie_connect.tests.infrastructure.db.TestDaoProvider.<init>(TestDaoProvider.java:29)
    at com.genie_connect.tests.android.repo.BaseRepositoryTests.setupDb(BaseRepositoryTests.java:22)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.robolectric.RobolectricTestRunner.invokeBeforeClass(RobolectricTestRunner.java:259)
    at org.robolectric.RobolectricTestRunner.access$500(RobolectricTestRunner.java:50)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:212)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by erd** [comment]
No one who is a committer on robolectric uses Windows, so we really need PRs from the community here. It also doesn't help that Travis CI doesn't have windows workers to run our tests on.

**Comment by steveydee82** [comment]
The NPE is thrown because the function acesses Resources.getSystem(), which is null.

I'm guessing there's not much that can be done about that?

**Comment by steveydee82** [comment]
A bit more investigation reveals this is not a WIndows issue. I'm trying to create my SQLiteDatabase instance in a @BeforeClass method. Looking at the RoboElectric test runner, it only initialises resources after BeforeClass is invoked, so SQLite can't find the system resources and blows up.

I don't know enough about RE architecture to know whether this can safely be fixed so that I can instantiate my database in BeforeClass - but it would be great if I could as it would speed up my test run.

**Comment by kriegfrj** [comment]
I know that this is a bit old, but I did some work on this (see #1763) which means that connections are automatically cleaned up after each test. So if you're using in-memory databases, this will mean you have to set up your DB on each test.

I agree it would be good to be a bit more flexible so that expensive operations (like setting up a test db) can be done once and kept for several tests.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
