### ISSUE TITLE
Robolectric fails with AnnotationFormatError exception when using @Config annotation

### ISSUE THREAD

**Issue by vkislicins** [robolectric/robolectric#1620]
When using @Config annotation I can't run my tests from Android Studio (1.1 stable). Using Robolectric 3.0 SNAPSHOT. Here's the exception:

```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:747)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:263)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:117)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:70)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3271)
	at java.lang.Class.getAnnotation(Class.java:3219)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:199)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by jaredsburrows** [comment]
Works perfectly fine via the command line: `gradlew test`.

**Comment by marbarfa** [comment]
@vkislicins , does work without the @Config annotation?. It works just fine from the command line...

**Comment by vkislicins** [comment]
Yes running from command line worked fine, as did removing the Config annotation.

**Comment by jaredsburrows** [comment]
What Config were you using? I dont understand what your issue it.

**Comment by vkislicins** [comment]
I was setting a manifest and emulateSdk. Something like

@Config(manifest = "path/to/manifest/AndroidManifest.xml",
        resourceDir = "../main/res",
        emulateSdk = 18)

**Comment by jaredsburrows** [comment]
Why are you specifying `manifest` and `resourceDir`?

For 2.4:
     
     @RunWith(RobolectricTestRunner.class)
     @Config(emulateSdk = 18, reportSdk = 18)
      // You should not need this: @Config(emulateSdk = 18, reportSdk = 18, manifest = "src/main/AndroidManifest.xml")

For 3.0:

     @RunWith(RobolectricTestRunner.class) // or custom
     @Config(emulateSdk = 21, reportSdk = 21)

**Comment by vkislicins** [comment]
I'm using 3.0. I was specifying manifest as Robolectric couldn't find it and the config property was not getting picked up (https://github.com/robolectric/robolectric/issues/1621). Second problem was with app themes not being picked up - I think that's due to the ActionBarActivity.

In the end I removed the @Config and created a custom runner to solve those problems

**Comment by jaredsburrows** [comment]
@vkislicins  So you solved it?

When you are using API 22:

    @Config(emulateSdk = 21, reportSdk = 21)

Yes for 3.0 you should use a custom runner:

https://github.com/robolectric/robolectric/wiki/2.4-to-3.0-Upgrade-Guide-(Draft)

and see:

https://github.com/nenick/AndroidStudioAndRobolectric

**Comment by vkislicins** [comment]
Upgrade guide draft is useful thanks - wish I saw it sooner as I already discovered most of it with trial and error :)

I've upgraded my Android Studio earlier this week and @Config(emulateSdk = 21, reportSdk = 21) is not causing any issue anymore.

**Comment by jaredsburrows** [comment]
Yay!

**Comment by vkislicins** [comment]
Getting those again :( Nothing changed apart from maybe gradle pulled the new snapshot?

Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract 
```
java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:747)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:263)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:117)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:70)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3271)
	at java.lang.Class.getAnnotation(Class.java:3219)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:202)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```
However removing @Config does not help this time and the test is failing in custom runner:

```
ava.lang.NoClassDefFoundError: android/app/Activity
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2499)
	at java.lang.Class.getDeclaredFields(Class.java:1811)
	at org.junit.runners.model.TestClass.getSortedDeclaredFields(TestClass.java:77)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:70)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:76)
	at com.myapp.utils.CustomTestRunner.<init>(CustomTestRunner.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: android.app.Activity
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 65 more
```

**Comment by jaredsburrows** [comment]
@vkislicins That last exception seems like something on your side. Post the test.

**Comment by vkislicins** [comment]
This one fails with a similar error - java.lang.NoClassDefFoundError: android/content/Context
```
@RunWith(CustomTestRunner.class)
public class AppExampleTest extends MyTestFramework {
    @Test
    public void exampleTest_loadActivity() throws Exception {
        Activity activity = Robolectric.setupActivity(StartupActivity.class);
        assertTrue(activity.getTitle().toString().contains("Test"));
    }
}
```

**Comment by jaredsburrows** [comment]
Killing me with no details.

What is `MyTestFramework`? 

Also, you do not need to `Robolectric.setupActivity` start an entire `Activity` to test a `String`.

**Comment by vkislicins** [comment]
Sorry :) MyTestFramework is resetting my sdk after each test

```
public class MyTestFramework {

    @After
    public void tearDown() {
        SdkClient.reset();
    }
}
```
 SdkClient.reset() goes into my main sdk and sets an instance to null. That's pretty much it.

**Comment by vkislicins** [comment]
> Also, you do not need to Robolectric.setupActivity start an entire Activity to test a String.

I'm testing if the activity starts correctly rather than just a string.. Probably not the best way to test that?

**Comment by jaredsburrows** [comment]
I am never really see `setupActivity` used.

How many tests do you have that are affected?

Please see: http://stackoverflow.com/a/23480546/950427

`HomeScreenActivity homeActivity = Robolectric.buildActivity(HomeScreenActivity.class).create().start().visible().get();`

**Comment by vkislicins** [comment]
All of my tests are affected when running from Android Studio (17th March built). Works fine in command line..

Using buildActivity(StartupActivity.class).create().start().visible().get(); made no difference..

**Comment by vkislicins** [comment]
I think my Studio decided to start updating from Canary channel. Let me downgrade to stable and try again

**Comment by jaredsburrows** [comment]
Why not just run via command line? Basically simulate what your project would be doing on a CI server.

**Comment by vkislicins** [comment]
I am at the moment :) However it's good to have an option to run in debug.

Downgrading Studio didn't help

**Comment by jaredsburrows** [comment]
I believe running Robo tests in the IDE takes extra setup. I am really not sure. There is no real point for me to run debug on a test in Android Studio.

**Comment by grub-** [comment]
I confirm stumbled same issue today. After some freezing and killing gradle tasks in AS, before this all worked fine with 3.0-rc2+last AS

**Comment by bvellacott** [comment]
Hi I had the same problem - after I ran the tests once from the command line - everything was fine again

**Comment by mkurutin** [comment]
I was able to reproduce the issue inside my IDE:
```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
```
My tools combination:
- <code>com.android.tools.build:gradle:1.3.1</code>
- <code>org.robolectric:robolectric:3.0</code>
- IntelliJ 14.1.4

My test setup:
```
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class)
public class MainActivityTest {
...
}
```

There is a workaround though. Everything works if I downgrade my gradle plugin to: <code>com.android.tools.build:gradle:1.2.3</code>

**Comment by jaredsburrows** [comment]
@mkurutin Try what @bvellacott said.

**Comment by vpetrov** [comment]
For anyone stumbling on this page: I resolved this issue by removing the `.gradle` folder in my project and rebuilding the project.

I'm using:

* com.android.tools.build:gradle:1.5.0
* org.robolectric:robolectric:3.0
* Gradle 2.9
* Android Studio 1.5.1
* Oracle JDK 1.8.0_31-b13

The error was: **initializationError**

```
java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:597)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3513)
	at java.lang.Class.annotationData(Class.java:3502)
	at java.lang.Class.getAnnotations(Class.java:3438)
	at org.junit.runner.Description.createSuiteDescription(Description.java:124)
	at org.junit.internal.runners.ErrorReportingRunner.getDescription(ErrorReportingRunner.java:28)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.allTestsFiltered(JUnitTestClassExecuter.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:99)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by chrisjenx** [comment]
Deleting the `.gradle` folder worked for me too. Odd. Guessing some high level caching going on somewhere.

**Comment by Dimezis** [comment]
Same, deleting `.gradle` helped me

**Comment by ysyyork** [comment]
Is this issue solved just by deleting .gradle folder?

I'm still suffering from it even I delete .gradle folder. My code is like below:
```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class ProduceSyncUseCaseUnitTest {

    @Test
    public void a() {
        assertEquals(1, 1);
    }
}
```

My env is:
```
Android studio 3.0
Robolectric 3.8
gradle 3.5
API level 25. min 25, max 25
```

Not sure if I miss anything. In case you wanna double check the log, here it is:

```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:612)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:132)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:220)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by DuoBlood** [comment]
@ysyyork if deleting `.gradle` folder doesn't help try also `Invalidate caches and Restart`

**Comment by ysyyork** [comment]
I can make it work after I delete .gradle in android studio but with cmd line running ./gradlew test, it's totally same error. have been stucking on this for very long. anyone can help?

**Comment by starsep** [comment]
I had that issue while running tests from Android Studio.
Changing `Search for tests:` from `In whole project` to `In single module` fixed the issue
