### ISSUE TITLE
Cannot open SQLite connection, base error code: 14 - Works first time, but fails all subsequent times

### ISSUE THREAD

**Issue by simtse** [robolectric/robolectric#1622]
I was running my unit tests with Robolectric 2.4 and got my tests working from referring to the https://github.com/robolectric/robolectric/issues/569 issue and incorporated what @hvu did and closed my db connection and helper connection. This helped all my DB related unit tests pass and not fail for the reasons mentioned in https://github.com/robolectric/robolectric/issues/569.

However, because I am looking to use some Shadows in 3.0 SNAPSHOT, I decided to use Robolectric 3.0 and play services shadows with multi dexing (https://github.com/robolectric/robolectric/issues/1399#issuecomment-79119297). However, after a lot of battling, I realized that only adding Robolectric 3.0-SNAPSHOT would cause the same problem mentioned in #569 . The following is my stack trace

```
android.database.sqlite.SQLiteException: Cannot open SQLite connection, base error code: 14
    at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:53)
    at org.robolectric.shadows.ShadowSQLiteConnection.access$600(ShadowSQLiteConnection.java:30)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:443)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.open(ShadowSQLiteConnection.java:345)
    at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:58)
    at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
    at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:863)
    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:235)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
    at com.core.database.AndroidDatabaseWrapper.open(AndroidDatabaseWrapper.java:31)
        ...
Caused by: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
    at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1353)
    at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:258)
    at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:269)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$1.call(ShadowSQLiteConnection.java:352)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$1.call(ShadowSQLiteConnection.java:345)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:429)
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
```

Here is my gradle settings

```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        classpath 'org.robolectric:robolectric-gradle-plugin:0.14.+'
    }
}

repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

...

dependencies {
   ...
    // unit testing
    androidTestCompile fileTree(dir: 'libs/test', include: '*.jar')
    androidTestCompile('com.squareup:fest-android:1.0.+') {
        exclude group: 'com.android.support'
    }
    androidTestCompile 'com.google.dexmaker:dexmaker:1.+'

    androidTestCompile('junit:junit:4.11') {
        exclude module: 'hamcrest-core'
    }
    androidTestCompile 'org.hamcrest:hamcrest-library:1.3'
    androidTestCompile 'org.mockito:mockito-core:1.9.5'
    androidTestCompile 'org.robolectric:android-all:+'
    androidTestCompile('org.robolectric:robolectric:3.0-SNAPSHOT') {
        exclude module: 'classworlds'
        exclude module: 'commons-logging'
        exclude module: 'httpclient'
        exclude module: 'maven-artifact'
        exclude module: 'maven-artifact-manager'
        exclude module: 'maven-error-diagnostics'
        exclude module: 'maven-model'
        exclude module: 'maven-project'
        exclude module: 'maven-settings'
        exclude module: 'plexus-container-default'
        exclude module: 'plexus-interpolation'
        exclude module: 'plexus-utils'
        exclude module: 'wagon-file'
        exclude module: 'wagon-http-lightweight'
        exclude module: 'wagon-provider-api'
    }

}

```

But when I were to change my dependency of robolectric to just 2.4, then my tests run perfectly fine. Just for reference my Android Database Wrapper has the following snippets

```
public class AndroidDatabaseWrapper implements IDatabaseWrapper {
    private SQLiteDatabase mDb;
    private SQLiteOpenHelper mDBOpenHelper;
    @Override
    public IDatabaseWrapper open(Context context, String mDbPath, String code, int flags) {
        mDBOpenHelper = new SQLiteOpenHelper(context,
                mDbPath + ".db", null, 1) {
            @Override
            public void onCreate(SQLiteDatabase sqLiteDatabase) {
            }

            @Override
            public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i2) {
            }
        };


        mDb = mDBOpenHelper.getWritableDatabase();
        return this;
    }

// other code
...

    @Override
    public void close() {
        mDBOpenHelper.close();
    }
}
```

Can you confirm if you see the same thing on your side?

**Comment by polson** [comment]
I'm also seeing this in my project, with 3.0-SNAPSHOT

Normally I would close the DB after every test, but now that doesn't seem to work.

I'm not using play services shadows or multidex, just FYI.

**Comment by polson** [comment]
I was able to fix this by also creating a new SQLiteOpenHelper before each test [as described here](https://github.com/robolectric/robolectric/issues/569#issuecomment-53336780).  Originally I was just closing/opening the database after each test, which is no longer sufficient it seems.

**Comment by athkalia** [comment]
Just noticed this myself after upgrading to robo 3.0 rc2. Is there a recommended approach ?

**Comment by vkislicins** [comment]
Seeing a similar issue - my app attempts to get some data from the database when I create an activity. Used to work fine until I moved my SQL helper to a singleton model. Any suggestions? I can't create a new SQLiteOpenHelper as this is happening inside the app not the test.

**Comment by jaredsburrows** [comment]
@vkislicins  Didn't post a similar issue on StackOverflow?

**Comment by vkislicins** [comment]
@jaredsburrows yep and you commented there with a link to this issue here :)

http://stackoverflow.com/questions/30308776/robolectric-accessing-database-throws-an-error

fyi if someone needs a quick fix solution - there's one following the link above.

**Comment by kriegfrj** [comment]
I'm wondering if this is related to #1763?

**Comment by Malachiasz** [comment]
I see that with org.robolectric:robolectric:3.0-rc3

**Comment by gkraft4** [comment]
I'm seeing the same with org.robolectric:robolectric:3.0

> android.database.sqlite.SQLiteException: Cannot open SQLite connection, base error code: 14
> org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:56)

**Comment by jasonclarkjc** [comment]
This solution worked for me. chowning the dir to the user opening the db see here: [http://sqliteviewer.com/blog/know-manual-solution-of-sqlite-error-code-14.html](http://sqliteviewer.com/blog/know-manual-solution-of-sqlite-error-code-14.html)

**Comment by utzcoz** [comment]
@gkraft4 @Malachiasz @simtse does this problem exist on latest Robolectric 4.7.3? There are many improvement of SQLite supporting after Robolectric 3.x, and Robolectric 4.7 also added native SQLite supporting. This problem is too old, and related Robolectric version is also too old. I will close this problem, and feel free  to reopen this problem if you find this problem also exists in latest Robolectric.
