### ISSUE TITLE
NPE from org.robolectric.res.builder.DefaultPackageManager.compare

### ISSUE THREAD

**Issue by godares79** [robolectric/robolectric#1626]
Trace:
java.lang.RuntimeException: java.lang.NullPointerException
        at org.robolectric.RobolectricTestRunner.evaluate(RobolectricTestRunner.java:227)
        at junit.runners.ParentRunner.runLeaf(ParentRunner.java:273)
        at junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at junit.runners.ParentRunner.run(ParentRunner.java:240)
        at junit.runners.ParentRunner.schedule(ParentRunner.java:65)
        at junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
        at junit.runners.ParentRunner.access$000(ParentRunner.java:55)
        at junit.runners.ParentRunner.evaluate(ParentRunner.java:231)
        at org.robolectric.RobolectricTestRunner.evaluate(RobolectricTestRunner.java:167)
        at junit.runners.ParentRunner.run(ParentRunner.java:316)
        at junit.runners.Suite.runChild(Suite.java:127)
        at junit.runners.Suite.runChild(Suite.java:26)
        at junit.runners.ParentRunner.run(ParentRunner.java:240)
        at junit.runners.ParentRunner.schedule(ParentRunner.java:65)
        at junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
        at junit.runners.ParentRunner.access$000(ParentRunner.java:55)
        at junit.runners.ParentRunner.evaluate(ParentRunner.java:231)
        at junit.runners.ParentRunner.run(ParentRunner.java:316)
....
Caused by: java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1139)
        at org.robolectric.res.builder.DefaultPackageManager.compare(DefaultPackageManager.java:60)
        at org.robolectric.res.builder.DefaultPackageManager.compare(DefaultPackageManager.java:48)
        at java.util.TreeMap.put(TreeMap.java:551)
        at org.robolectric.res.builder.DefaultPackageManager.findOrCreateInfoList(DefaultPackageManager.java:522)
        at org.robolectric.res.builder.DefaultPackageManager.addResolveInfoForIntent(DefaultPackageManager.java:231)
        at org.robolectric.DefaultTestLifecycle.addManifestActivitiesToPackageManager(DefaultTestLifecycle.java:96)
        at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:70)
        at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:15)
        at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:97)
        at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
        at org.robolectric.RobolectricTestRunner.evaluate(RobolectricTestRunner.java:223)

This seems to be a very rare flake. DefaultPackageManager.compare is surrounded by null checks, so maybe there is a race condition that is nulling the intent action between the time of the check and the actual compare call.

**Comment by jongerrish** [comment]
Just saw the same error now. Agree it is flaky.

**Comment by lexs** [comment]
Also just saw this, should the code be rewritten to safeguard for race condition to at least alleviate for the symptom? That is just do `String action = i1.getAction()`.

**Comment by lexs** [comment]
I've started investigating this and I don't think Intent.setAction() is getting called clearing the action, the other alternative I can think of is that we are somehow skipping the shadow and calling getAction() directly on the Intent. However this is also odd because we do call the constructor of the real Intent, setting the action.

**Comment by lexs** [comment]
Saw this again today, can it be because somehow getAction() is being routed to a different object?

**Comment by sweetleon** [comment]
I'm also seeing this come up occasionally (about 1 in 50,000 tests) on `3.0-rc2`.

**Comment by lexs** [comment]
@sweetleon Make sure to update to rc3 (which has https://github.com/robolectric/robolectric/pull/1823) and report back if you see it with that "fix".

**Comment by jaredsburrows** [comment]
@sweetleon Really? 50,000? lol

@godares79 Can you show us the test?

**Comment by sweetleon** [comment]
@jaredsburrows Permit me to explain that 50,000 estimate: we have a suite of ~1,000 tests, and having run it ~1,000 times on circleci over that last month or so (yes, we commit a lot) we've seen it fail every 50 runs or so, hence ~50 x ~1,000 = ~50,000. The particular test that gets hit changes each time and there seems to be nothing about the test itself in the stack trace.

**Comment by sschuberth** [comment]
Confirmed that #1971 fixed this for us.

**Comment by jaredsburrows** [comment]
@sweetleon  Thanks for that. I'll also report back if I receive odd behavior.

@sschuberth Thank you. @godares79 Can you please update and confirm?

@erd We may be able to close.
