### ISSUE TITLE
Error inflating an custom view inherited from ViewPager

### ISSUE THREAD

**Issue by jiahaoliuliu** [robolectric/robolectric#1638]
Hi:
I am working on Robolectric 3.0 - Snapshot and I have a custom view which is inherited from the support version of ViewPager.

When I run a test of an activity which uses that custom view, it shows me inflateException because It cannot find the class ViewConfigurationCompatFroyo.

I am using support library v4 22.0.0 on Android Studio.

Here are some logs:

```
android.view.InflateException: XML file ../app/src/main/res/layout/activity_main.xml line #-1 (sorry, not yet implemented): Error inflating class com.jiahaoliuliu.extensions.JazzyViewPager
    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        ....
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:594)
        ....
Caused by: java.lang.NoClassDefFoundError: android/support/v4/view/ViewConfigurationCompatFroyo
    at android.support.v4.view.ViewConfigurationCompat$FroyoViewConfigurationVersionImpl.getScaledPagingTouchSlop(ViewConfigurationCompat.java:56)
    at android.support.v4.view.ViewConfigurationCompat.getScaledPagingTouchSlop(ViewConfigurationCompat.java:105)
    at android.support.v4.view.ViewPager.initViewPager(ViewPager.java:367)
    at android.support.v4.view.ViewPager.__constructor__(ViewPager.java:355)
    at android.support.v4.view.ViewPager.<init>(ViewPager.java)
        ....
Caused by: java.lang.ClassNotFoundException: android.support.v4.view.ViewConfigurationCompatFroyo
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:166)
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
    at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
    at android.support.v4.view.ViewConfigurationCompat$FroyoViewConfigurationVersionImpl.$$robo$$FroyoViewConfigurationVersionImpl_bcf8_getScaledPagingTouchSlop(ViewConfigurationCompat.java:56)
    at android.support.v4.view.ViewConfigurationCompat$FroyoViewConfigurationVersionImpl.getScaledPagingTouchSlop(ViewConfigurationCompat.java)
    at android.support.v4.view.ViewConfigurationCompat.$$robo$$ViewConfigurationCompat_b79c_getScaledPagingTouchSlop(ViewConfigurationCompat.java:105)
    at android.support.v4.view.ViewConfigurationCompat.getScaledPagingTouchSlop(ViewConfigurationCompat.java)
    at android.support.v4.view.ViewPager.$$robo$$ViewPager_da47_initViewPager(ViewPager.java:367)
    at android.support.v4.view.ViewPager.initViewPager(ViewPager.java)
    at android.support.v4.view.ViewPager.$$robo$$ViewPager_da47___constructor__(ViewPager.java:355)
    at android.support.v4.view.ViewPager.<init>(ViewPager.java)
        ....
```

**Comment by samygj** [comment]
Any updates?

**Comment by jongerrish** [comment]
Can you create a test case that shows the problem?

**Comment by erd** [comment]
I've tried, but am unable to reproduce the issue.

**Comment by samygj** [comment]
I'm currently using robolectric 2.4 and support-v4 21. When I run the unit tests I'm still getting:

android.view.InflateException: XML file ./res/layout/slidingmenumain.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
