### ISSUE TITLE
UnsupportedOperationException in ShadowAssetManager

### ISSUE THREAD

**Issue by pvtl-shane** [robolectric/robolectric#1645]
Using a third party library that inflates it's own layout:

java.lang.UnsupportedOperationException: ugh, this doesn't work still?
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:350)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:333)
	at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:93)
	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
	at android.content.res.Resources.getValue(Resources.java:1114)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
	at android.content.res.Resources.getLayout(Resources.java:934)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:395)

**Comment by erd** [comment]
This is very similar to #1554.
