### ISSUE TITLE
FileNotFoundException with <include layout=.../> tag

### ISSUE THREAD

**Issue by hidroh** [robolectric/robolectric#1651]
I'm using `robolectric` and `shadows-support-v4` 3.0-rc2. When trying to test an activity using `ActionBarDrawerToggle`, Robolectric failed to inflate the activity layout, which contains an `<include layout=../>` tag that I use to include my drawer layout:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@id/drawer_layout"
    android:layout_width="match_parent" android:layout_height="match_parent">
    <!-- The main content view -->
    <FrameLayout
        android:id="@id/content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
    <!-- The navigation drawer -->
    <include layout="@layout/drawer" />
</android.support.v4.widget.DrawerLayout>
```

The included layout:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@id/drawer"
    android:layout_gravity="left"
    android:background="?attr/themedDrawerBackgroundColor"
    android:scrollbars="none"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <fragment
        android:name="io.github.hidroh.materialistic.DrawerFragment"
        android:tag="io.github.hidroh.materialistic.DrawerFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</ScrollView>
```

Later I found out it has nothing to do with `DrawerLayout` or `ActionBarDrawerToggle`, but rather with `<include layout=.../>` tag. If I remove `<include layout=.../>` and replace it with the actual included layout, the exception is gone. I'm using `appcompat-v7` and `support-v4` 22.0.0, testing against SDK 21.

Below is the stacktrace:

```
java.lang.RuntimeException: java.io.FileNotFoundException:  (No such file or directory)
    at org.robolectric.res.XmlLoader.parse(XmlLoader.java:39)
    at org.robolectric.res.builder.XmlFileBuilder.getXmlResourceParser(XmlFileBuilder.java:61)
    at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2600)
    at android.content.res.Resources.getLayout(Resources.java:1049)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java:870)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
    at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:240)
    at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
    at io.github.hidroh.materialistic.BaseActivity.onCreate(BaseActivity.java:26)
    at io.github.hidroh.materialistic.BaseListActivity.onCreate(BaseListActivity.java:37)
    at android.app.Activity.performCreate(Activity.java:5933)
    at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
    at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at io.github.hidroh.materialistic.BaseListActivityTest.setUp(BaseListActivityTest.java:19)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException:  (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.robolectric.res.FileFsFile.getInputStream(FileFsFile.java:78)
    at org.robolectric.res.XmlLoader.parse(XmlLoader.java:32)
    at org.robolectric.res.builder.XmlFileBuilder.getXmlResourceParser(XmlFileBuilder.java:61)
    at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:478)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java)
    at android.content.res.Resources.$$robo$$Resources_fb43_loadXmlResourceParser(Resources.java:2600)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java)
    at android.content.res.Resources.$$robo$$Resources_fb43_getLayout(Resources.java:1049)
    at android.content.res.Resources.getLayout(Resources.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_parseInclude(LayoutInflater.java:870)
    at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_rInflate(LayoutInflater.java:802)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_inflate(LayoutInflater.java:365)
    at android.view.LayoutInflater.inflate(LayoutInflater.java)
    at android.support.v7.app.ActionBarActivityDelegateBase.$$robo$$ActionBarActivityDelegateBase_c4c6_setContentView(ActionBarActivityDelegateBase.java:240)
    at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java)
    at android.support.v7.app.ActionBarActivity.$$robo$$ActionBarActivity_eab0_setContentView(ActionBarActivity.java:102)
    at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java)
    at io.github.hidroh.materialistic.BaseActivity.onCreate(BaseActivity.java:26)
    at io.github.hidroh.materialistic.BaseListActivity.onCreate(BaseListActivity.java:37)
    at android.app.Activity.$$robo$$Activity_c57b_performCreate(Activity.java:5933)
    at android.app.Activity.performCreate(Activity.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
    at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at io.github.hidroh.materialistic.BaseListActivityTest.setUp(BaseListActivityTest.java:19)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    ... 7 more
```

**Comment by nenick** [comment]
> java.io.FileNotFoundException
Which file could not be found? And does this file exist somewhere?

Current I can only report that `<include layout=.../>` works for me.

**Comment by hidroh** [comment]
Tracing the stack trace does not give any useful hint, but my speculation is that it cannot find/cannot resolve the reference to `@layout/drawer`, which is the file I include in my layout. This file of course exists, just a normal layout file.

**Comment by nenick** [comment]
could you do a debug point 'at org.robolectric.res.XmlLoader.parse(XmlLoader.java:32)'  and get the path from xmlFile?

**Comment by hidroh** [comment]
At `android.content.res.Resources.loadXmlResourceParser(Resources.java)`:
```
this = {android.content.res.Resources@4571} "android.content.res.Resources@311ab05d"
mCachedXmlBlockIds = {int[4]@4626} 
mCachedXmlBlockIds.length = 4
```

At `org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)`:
```
this = {org.robolectric.shadows.ShadowResources@4566} 
file = {java.lang.String@4580} ""
id = 2130968604
assetCookie = 765317
type = {java.lang.String@2382} "layout"
packageName = {java.lang.String@4583} "io.github.hidroh.materialistic"
```

After that the file name is just empty, until exception is thrown.

**Comment by nenick** [comment]
Current I can only report that this feature work with robolectric 3.0 because we use this style for our actionbar and drawer and all tests on the fragments works fine.

An empty file name is wrong but no idea what is the root cause.

**Comment by nenick** [comment]
@hidroh your project materialistic use an old solution with androidTestCompile. Can you switch to the new android gradle plugin version 1.1.0 and use robolectric within testCompile? Also use the `RobolectricGradleTestRunner` at `@RunWith`and report if the error still exist?

**Comment by hidroh** [comment]
@nenick last time I tried there were some conflict dependencies with assertj-android that prevents me from switching to latest android gradle plugin. I'll try again when I have time and report back.

**Comment by nenick** [comment]
try that if you have still conflicts

    testCompile('com.squareup.assertj:assertj-android:1.0.1-SNAPSHOT') {
        exclude module: "support-annotations"
    }

**Comment by r9software** [comment]
I have the same Problem, and I'm include layout tag in the principal view for my activity, 
I'm using the last release of Ronolectric and 
@RunWith(RobolectricGradleTestRunner.class)
Activity mActivity = Robolectric.setupActivity(ActivationActivatingActivity.class);
the method is just adding the view to the activity nothing else.

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding resouce and layout-related issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
