### ISSUE TITLE
NullPointerException at ShadowAssetManager -> getThemeByInternalId

### ISSUE THREAD

**Issue by nolanlawson** [robolectric/robolectric#1662]
Hi, I'm using 3.0-SNAPSHOT with Gradle, and I'm trying to instantiate my activity using a simple:

``` java
    @Test
    public void testBasic() throws Exception {
        assertTrue(Robolectric.buildActivity(MyActivity.class).create() != null);
    }
```

But this is failing with the following stacktrace:

```
java.lang.NullPointerException
    at org.robolectric.shadows.ShadowAssetManager$OverlayedStyle.equals(ShadowAssetManager.java:299)
    at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:272)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.applyStyle(ShadowResources.java:465)
    at android.content.res.Resources$Theme.applyStyle(Resources.java)
    at android.view.ContextThemeWrapper.onApplyThemeResource(ContextThemeWrapper.java:128)
    at android.app.Activity.onApplyThemeResource(Activity.java:3661)
    at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
    at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
    at org.robolectric.shadows.ShadowActivity.setThemeFromManifest(ShadowActivity.java:81)
    at org.robolectric.shadows.CoreShadowsAdapter$1.setThemeFromManifest(CoreShadowsAdapter.java:37)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:58)
    ...
```

Seems the offending line of code is (sorry, can't find in the Github source):

``` java
  private synchronized Theme getThemeByInternalId(int internalThemeId) {
    return (Theme)this.themesById.get(Integer.valueOf(internalThemeId));
  }
```

Sorry for not having a reproducible test case; I will try to debug this, but I'm just now learning how to contribute to this project. And I dunno, if I'm lucky maybe someone will be able to immediately spot the problem? :)

**Comment by nolanlawson** [comment]
The application's theme is coming from an external AAR, so maybe that's what's causing this bug.

**Comment by nolanlawson** [comment]
I removed the app's theme in order to solve this problem. Couldn't find any other workaround. :(

**Comment by nolanlawson** [comment]
Here is [a reproducible test case](https://github.com/nolanlawson/demo-robolectric-1662). To run the test:

```
git clone https://github.com/nolanlawson/demo-robolectric-1662.git
cd demo-robolectric-1662
./gradlew test
```

**Comment by mheras** [comment]
Hi @erd, 

Do you have a release date for 3.1?
Or any workaround for this issue? I currently have all my activity tests failing :(

Thank you,
Martín

**Comment by xian** [comment]
Fixed for a while I think, please reopen if not!
