### ISSUE TITLE
android.os.Looper cannot be cast to org.robolectric.internal.ShadowedObject

### ISSUE THREAD

**Issue by DaimonPl** [robolectric/robolectric#1726]
Appeared today (so snapshot from 2015-04-23). All tests run with RobolectricGradleTestRunner are failing:

```
java.lang.RuntimeException: java.lang.ClassCastException: android.os.Looper cannot be cast to org.robolectric.internal.ShadowedObject
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:260)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:207)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassCastException: android.os.Looper cannot be cast to org.robolectric.internal.ShadowedObject
	at org.robolectric.internal.ShadowExtractor.extract(ShadowExtractor.java:5)
	at org.robolectric.Shadows.shadowOf(Shadows.java:904)
	at org.robolectric.shadows.ShadowLooper.resetThreadLoopers(ShadowLooper.java:58)
	at org.robolectric.Shadows.reset(Shadows.java:1355)
	at org.robolectric.Robolectric.reset(Robolectric.java:29)
	at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:39)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:249)
	... 26 more
```

**Comment by kriegfrj** [comment]
I ran into this issue (or at least a similar one) too. I think this is related to #1717. In my case I fixed it by pulling in the latest changes from master and running scripts/install-robolectric.sh again.

**Comment by lexs** [comment]
Most likely you have older snapshot of org.robolectric:robolectric which adds the interface. Check if reinstalling, like @kriegfrj said, helps.

**Comment by DaimonPl** [comment]
Snapshot was from maven directly. I'll verify it on Monday with newer snapshot

**Comment by DaimonPl** [comment]
Verification blocked by #1730

**Comment by DaimonPl** [comment]
Verified together with #1730
