### ISSUE TITLE
Not able to find config.sdk() in latest 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by nishantsoni** [robolectric/robolectric#1729]
My build.gradle has:
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
    testCompile('org.robolectric:robolectric:3.0-SNAPSHOT') 
    testCompile('org.robolectric:shadows-httpclient:3.0-SNAPSHOT')
```
It was working fine this afternoon but started throwing the exception in the evening and still not fixed.

```
java.lang.NoSuchMethodError: org.robolectric.annotation.Config.sdk()I
	at org.robolectric.RobolectricTestRunner.pickSdkVersion(RobolectricTestRunner.java:467)
	at org.robolectric.RobolectricTestRunner.getEnvironment(RobolectricTestRunner.java:306)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:206)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My robolectric-3.0-SNAPSHOT-sources.jar/RobolectricTestRunner.java has:
```
protected int pickReportedSdkVersion(Config config, AndroidManifest manifest) {
    if (config != null && config.sdk() > 0) {
      return config.sdk();

    } else if (manifest != null) {
      return manifest.getTargetSdkVersion();

    } else {
      return SdkConfig.FALLBACK_SDK_VERSION;
    }
  }
```
but robolectric-annotations-3.0-SNAPSHOT.jar/Config.class has:
```
        public int emulateSdk() {
            return this.emulateSdk;
        }
```
and not sdk() and that is why I am seeing above exception.
Is there any different repository for annotations? or the release of annotations jar was buggy?

**Comment by DaimonPl** [comment]
Had similar problems. In my case clearing maven repository cache worked

**Comment by nishantsoni** [comment]
For me, using 3.0-rc2 worked.

**Comment by dominicmarmionswrve** [comment]
Same issue here. Fix from nishantsoni to use 3.0-rc2 worked for me.

**Comment by hidroh** [comment]
It has been changed to `sdk` by 8c45d4a57fa380436885166f8e89b3e20d20290c on SNAPSHOT.

**Comment by erd** [comment]
Try refreshing your Maven / Gradle cache as @DaimonPl mentioned.
