### ISSUE TITLE
NoSuchMethodError: org.robolectric.annotation.Config.emulateSdk()I (3.0-SNAPSHOT)

### ISSUE THREAD

**Issue by DaimonPl** [robolectric/robolectric#1730]
Using newest snapshot from maven repository

```
java.lang.NoSuchMethodError: org.robolectric.annotation.Config.emulateSdk()I
	at org.robolectric.RobolectricTestRunner.pickSdkVersion(RobolectricTestRunner.java:467)
	at org.robolectric.RobolectricTestRunner.getEnvironment(RobolectricTestRunner.java:306)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:206)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by nenick** [comment]
this method was replaced. use 'sdk' instead of 'emulateSdk'
https://github.com/robolectric/robolectric/commit/8c45d4a57fa380436885166f8e89b3e20d20290c

**Comment by DaimonPl** [comment]
Thing is I'm not using sdk or emulateSdk at all and still getting this error for every single robolectric test

If code is already updated, maybe there's something wrong with maven snapshot repository (i.e. artifacts are not in sync)?

**Comment by DaimonPl** [comment]
Works after cleaning local maven repo (had to perform cleanup manually on fs)
