### ISSUE TITLE
ClassCastException: RelativeLayout cannot be cast to com.truepagerindicator.views.TabView on extrarnal view-library

### ISSUE THREAD

**Issue by ar-g** [robolectric/robolectric#1732]
Hi
I have lib-project where all src and tests and app which using it. And external view-library com.truepagerindicator. 

When in activity called: 

``` java
trueTabPageIndicator.setViewPager(viewPager);`
```

In this lib then execute code

``` java
LayoutInflater layoutInflater = (LayoutInflater)getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        final TabView tabView = (TabView)layoutInflater.inflate(R.layout.true_tab_view, null);
```

Then I getting stacktrace

```
java.lang.ClassCastException: android.widget.RelativeLayout cannot be cast to com.truepagerindicator.views.TabView
    at com.truepagerindicator.views.TrueTabPageIndicator.inflateAndInitTab(TrueTabPageIndicator.java:317)
    at com.truepagerindicator.views.TrueTabPageIndicator.createTab(TrueTabPageIndicator.java:289)
    at com.truepagerindicator.views.TrueTabPageIndicator.notifyDataSetChanged(TrueTabPageIndicator.java:392)
    at com.truepagerindicator.views.TrueTabPageIndicator.setViewPager(TrueTabPageIndicator.java:375)
    at com.evos.lib.view.impl.MainHomeActivity.setupViewPager(MainHomeActivity.java:201)
```

I also found that layout's ids different in tests and on device. I guess if I put this view-library into my project it will work but we don't need it.  Any suggestions or workarounds are welcome.

I use: `org.robolectric:robolectric:3.0-rc2`

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
