### ISSUE TITLE
Resources Not found for Project

### ISSUE THREAD

**Issue by Neristance** [robolectric/robolectric#1733]
Hi,

I just discovered today when i switched to 3.0-SNAPSHOT version that i cant load resources, to make this clear for example it does not load any string resource for me with my flavour. Im using the new GradleRobolectricTestRunner. I also tried to debug the setup and verified the Manifest, res etc. paths.
They are all there on my filesystem and correct. I debugged PackageResourceLoader it works but somehow the Data is not transferred back to OverlayResourceIndex in my case, so in the end when the code tries to find an resource by id it finds nothing because the Maps resourceIdToResName and resourceNameToId are empty.

Maybe some code is removed in the latest Snapshot Fri Apr 24 14:00:34 CDT 2015 i tried it on (27th of April 2015)

This is an test just trying to load a string
My Stacktrace:

android.content.res.Resources$NotFoundException: unknown resource 2131624127
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:335)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:68)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:270)
	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:361)
	at android.content.res.Resources.getText(Resources.java)
	at android.content.res.Resources.getString(Resources.java:360)
	at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:37)
	at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:77)
	at android.content.Context.getString(Context.java)
	at com.TestClass.testBasicString(TestClass.java:27)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:267)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:207)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Thanks for helping me :)

**Comment by nenick** [comment]
do you use different applicationId for your flavors?

**Comment by Neristance** [comment]
yes i do for each flavour its different

**Comment by nenick** [comment]
At https://github.com/robolectric/robolectric/issues/1623 you should find your solution.

**Comment by Neristance** [comment]
Hey thanks i give it a try and write some feedback if it works :+1:

**Comment by jaredsburrows** [comment]
@Neristance  What is the status of this? Can this be closed now?

**Comment by erd** [comment]
@Neristance If you use flavors with an `applicationId` that is different from your app's package name, you'll need to specify `@Config(packageName = "<your Java package name")` in your test so Robolectric can find your resources.

**Comment by jaredsburrows** [comment]
@erd  Thanks. I am trying to clean up a lot of these issues. It seems as if people have stopped trying and given up because most of very old and/or inactive.

**Comment by erd** [comment]
Thanks! I appreciate it!

**Comment by jaredsburrows** [comment]
@erd  How many owners are there for Robolectric? How do you become one? Or are you only accepting contributions?

**Comment by erd** [comment]
> How many owners are there for Robolectric? How do you become one? Or are you only accepting contributions?

Let's talk over e-mail: erich.douglass@gmail.com

**Comment by jaredsburrows** [comment]
@erd  Sounds good. I sent you an email.
