### ISSUE TITLE
Cannot indirectly reference library resource indirectly.

### ISSUE THREAD

**Issue by tcw48** [robolectric/robolectric#1737]
I am trying test an android library with the following set up. `com.android.tools.build:gradle:1.2.0, org.robolectric:robolectric:3.0-rc2, android studio 1.2-rc-3`
In the setup for my test I am making an indirect reference to the R file of another library. The test runs fine from within android studio but running from command line produces the following error.

    java.lang.NoClassDefFoundError: robolectricdemo/com/baselibrary/R$color
                at robolectricdemo.com.baselibrary.DemoStaticClass.getDemoResource(DemoStaticClass.java:12)
                at LibraryResourceTest.setUp(LibraryResourceTest.java:25)
        
                Caused by:
                java.lang.ClassNotFoundException: robolectricdemo.com.baselibrary.R$color
                    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
                    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
                    at java.security.AccessController.doPrivileged(Native Method)
                    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
                    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
                    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
                    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
                    at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:98)
                    ... 2 more

I have created a simplified version of my code at http://github.com/tcw48/robolectricDemo with the important snippets bellow.

**The test class lives in the library extendlibrary**

    RunWith(RobolectricGradleTestRunner.class)
    @Config(constants = BuildConfig.class)
    public class LibraryResourceTest {
        private int color;
    
        @Before
        public void setUp() {
            color = DemoStaticClass.getDemoResource(RuntimeEnvironment.application);
        }
    
        @Test
        public void testLibraryResource(){
            assertNotNull(color);
        }
    }
    
**This static class lives in the library baselibrary.**

    public class DemoStaticClass {
    
        public static int getDemoResource(Context context) {
            return context.getResources().getColor(R.color.robo_red);
        }
    }

I noticed in the build directory that an R file is only being generated in the package extendlibrary but there is no package for baselibrary. Manually creating the R file in a package called baselibrary causes the test to pass. Any ideas on what I could be doing wrong.

**Comment by ecgreb** [comment]
I am having a similar issue. We're building a library that depends on AppCompat. When I run the unit tests in Android Studio or on the command line I get the following error:
```
java.lang.NoClassDefFoundError: android/support/v7/appcompat/R$attr
    at android.support.v7.widget.SearchView.<init>(SearchView.java)
    at android.support.v7.widget.SearchView.<init>(SearchView.java)
    at com.mapzen.pelias.widget.PeliasSearchView.<init>(PeliasSearchView.java:49)
    at com.mapzen.pelias.widget.PeliasSearchViewTest.setUp(PeliasSearchViewTest.java:31)
```
As a workaround I created a Gradle task to copy the R.java file to the android.support.v7.appcompat package as an intermediate build step. Not pretty but it works.

https://github.com/mapzen/pelias-android-sdk/blob/chuck/pelias-search-view-widget/build.gradle#L20

**Comment by tcw48** [comment]
Yeah I though about doing something like that but realized I would have to do the following for any library I add. Do you know if there is a way to generalize the copy script so that we can extract the path from the libraries compiled.

**Comment by ecgreb** [comment]
It should be possible to have a task to iterate over each project in `build/generated/exploded-aar` and extract the package name then invoke the copy task for each but I haven't gotten that far yet.

I'm hoping this workaround is temporary and we can find a way to have Robolectric correctly resolve these resources without duplicating the R.java file for each library.

**Comment by arahlf** [comment]
Is there any update on this?

I think I'm running into the same issue, but I'm not positive.  I'm building a library that depends on another library (not the AppCompat library).  When I try and run my tests, they fail w/ NoClassDefFoundErrors regarding the dependent library's R file.

I can see the library exists down in build/intermediates/exploded-aar, although there's just an "R.txt", not an "R.java" file.  The link to your current workaround seems to be broken.  I'm not sure what to try at this point =\

**Comment by ecgreb** [comment]
Sorry about the broken link. Here is the relevant code. Basically the same hacky workaround you referenced above. Its not great but it works for now.

```groovy
task copyTask(type: Copy) {
  println "Copying com/mapzen/pelias/R.java to android/support/v7/appcompat/R.java"
  from 'build/generated/source/r/debug/com/mapzen/pelias'
  into 'build/generated/source/r/debug/android/support/v7/appcompat'
  include 'R.java'
  filter { line -> line.contains('package com.mapzen.pelias;') ? 'package android.support.v7.appcompat;' : line }
}
```

**Comment by arahlf** [comment]
When I applied that workaround, I ended up copying the R file from the actual library project (it's a sibling folder).  Looking closer at the link I had originally posted, and what you had used, it's actually copying your generated R file into the problem library's source package.

This must work because the R files already been merged, so even though the one your copying into that directory has all of AppCompat's resource IDs + all of yours, it at least fulfills the contract of AppCompat's R file -- is that correct?

**Comment by ecgreb** [comment]
Right. I am copying the fully merged R.java from our library project that depends on AppCompat into the AppCompat generated package. And in the linked workaround its copying the fully merged R.java into a test source folder but I'm guessing it has the same result.

**Comment by jonneymendoza** [comment]
Hi. i have tried the little hack/workaround of copying the R files directly from the build/generated folder  but it does not work because the varient.name for me anyway is incorrect.

i am expecting the variant.name to just incude the product flavour name ie production. But instead it names it productionDebug or productionRelease.

Gradle doesnt build my project in that way. it builds it like this  by default > build/gnerated/source/r/production/release and build/gnerated/source/r/production/debug .

The hack expect is to be build like the following.

build/gnerated/source/r/productionrRelease 


any suggestions?

**Comment by ecgreb** [comment]
I have not tried this with flavors or variants yet but can you not just update the paths in the copy task? Possibly copying from/to more than one location where your app/library expects them to be.

**Comment by pickeyboy** [comment]
I think it's not only with appcompat, I am facing problem with custom views as well. I am using custom styleable in my library and I get the same error. Below is the snippet 


CustomView constructor

 public CustomTextView(Context context, AttributeSet attrs)
 {
        super(context, attrs);
        TypedArray typedArray = context.obtainStyledAttributes(attrs, R.styleable.CustomTextView)
        mOutlineWidth = typedArray.getDimensionPixelSize(R.styleable.CustomTextView_outlineWidth, DEFAULT_OUTLINE_WIDTH);
.....
}

My Test case for the above view is 

    @Test
    public void testConstructor() throws Exception
    {
        Resources resources = RuntimeEnvironment.application.getResources();
        ResourceLoader resourceLoader = shadowOf(resources).getResourceLoader();

        AttributeSet attrs = new RoboAttributeSet(asList(
                new Attribute("android:attr/inflatedId", "@+id/include_id", ctx.getPackageName()),
                new Attribute("android:attr/layout", "@layout/media", ctx.getPackageName())
        ), resourceLoader);

        CustomTextView customTextView = new CustomTextView(RuntimeEnvironment.application, attrs);
        assertNotNull(mArcTextView);
    }


I get following error if I run this unit test case
 java.lang.NoClassDefFoundError: /com/library/customviewlibrary/R$styleable

I find that R.java file very well exists in below folder where I am using $> ./gradlew testDebug from command line.
app/build/generated/source/r/debug/com/library/customviewlibrary/R.java

Surprisingly when I run unit test from Android studio all tests passed without any issues. But I get error only when I run this test through gradle in command line. 

Any help/fix/workaround on this will really be appreciated.

**Comment by arahlf** [comment]
Have you tried the copyTask workaround mentioned above?

**Comment by pickeyboy** [comment]
@arahlf 
Yep I did it, still no success. I am not getting error with appcompat

My error is with my CustomView styleable
java.lang.NoClassDefFoundError: /com/library/customviewlibrary/R$styleable

Got any clue?

**Comment by arahlf** [comment]
I'm using the workaround for a similar scenario as yours (not using appcompat) and it works fine for me.  Basically you can use a copyTask to copy your generated R file into your test source folder, renaming the package so that it's mimicking the R file of your CustomViewLibrary, and it'll fix the runtime NoClassDefFoundErrors.  This works because your generated R file will have the merged identifiers from the CustomViewLibrary in it as well.  Does that make sense?

**Comment by pickeyboy** [comment]
you mean to say, I must copy R.java file from /build/generated/ folder to /test/ folder where my unit tests are sitting? if it is handy, may I see your copyText gradle script,

**Comment by arahlf** [comment]
You're missing the filter part to rename the package, as well as the part that ties the copyTask into the build process.  Although it looks like you're copying the R back into the same package for some reason, not sure I follow that.

I don't have access to the repo I used the workaround for right now, but it looked something like:

    afterEvaluate { project ->
        android.libraryVariants.each { variant ->
            tasks.getByName("assemble${variant.name.capitalize()}").dependsOn copyOtherLibraryRFile
        }
    }
     
    task copyOtherLibraryRFile(type: Copy) {
      from 'build/generated/source/r/debug/com/my/library'.replace("/", File.separator)
      into 'src/test/java/com/other/library'.replace("/", File.separator)
      include 'R.java'
      filter { line -> line.contains('package com.my.library;') ? 'package com.other.library;' : line }
    }

**Comment by jonneymendoza** [comment]
That doesn't work. I will post a proper workaround

**Comment by pickeyboy** [comment]
@jonneymendoza 
Thanks Jonneymendoza, I will wait for your solution.

**Comment by pickeyboy** [comment]
@arahlf 
Package name of my main source and unit test is same so I removed filter line. Ye but even after adding filter line it doesn't work for me :(

**Comment by arahlf** [comment]
@jonneymendoza Well it's working for me, and a handful of other people :P  Looking above, based on the problems you're running into with the build flavors, your scenario is slightly different / more complex.

@pickeyboy The whole idea of copying the library file is so that you end up creating a "fake" version of the problem library's R file, by copying + renaming the package of your app/library's R file (which has the all the R identifiers merged into it at that point).  Are you using build flavors at all?

**Comment by jonneymendoza** [comment]
Yes the default copy script posted here won't work on build flavours. Mine
does. I had to Google and school myself a bit on gradle scripts.  Not good
to just copy and paste stuff especially with no commenting on the script on
what exactly each line of code is doing etc.

We do need a more robust way of doing it where it can identify your src
build directories automatically

**Comment by pickeyboy** [comment]
@jonneymendoza 
Hey Jonney, then what is your solution for gradle with build flavor? I am experiencing similar problem and copy doesn't work through script.

**Comment by jonneymendoza** [comment]
Here is my solution.

add the srcDir into your source sets for each flavour like this:

 sourceSets {
  staging {
            res.srcDir 'build-config/staging/res'
            test.java.srcDirs += 'src/main/java'
           test.java.srcDirs += "build/generated/source/r/staging"
            test.java.srcDirs += "build/generated/source/buildConfig/staging"
        }
        production {
            res.srcDir 'build-config/production/res'
            test.java.srcDirs += 'src/main/java'
            test.java.srcDirs += "build/generated/source/r/production"
            test.java.srcDirs += "build/generated/source/buildConfig/production"
        }
}

And here is the task that copies the different varient u want to build and test

def package_namespace = "com.your.package"
    def package_namespace_path = package_namespace.replaceAll("\\.", "/")
    afterEvaluate { project ->
        android.libraryVariants.each { variant ->
            // workaround for missing R class for aar dependencies
            def copyTaskName = "copy${variant.name.capitalize()}AppCompat"
            task(copyTaskName, type:Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "build/generated/source/r/${variant.dirName}/$package_namespace_path" }
                into { "build/generated/source/r/${variant.dirName}/android/support/v7/appcompat" }
//                into { "src/test/java/android/support/v7/appcompat" }
                include 'R.java'
                filter { line -> line.contains("package ${package_namespace};") ? 'package android.support.v7.appcompat;' : line }
                outputs.upToDateWhen { false }
            }
            System.out.println("adding ${copyTaskName} build/generated/source/r/${variant.dirName}/$package_namespace_path ")
            println("basename =  ${variant.baseName}")
            println("directory name =  ${variant.dirName}")
            tasks.getByName("compile${variant.name.capitalize()}UnitTestJava") dependsOn copyTaskName
        }
    }

i did some modifications on it after understanding a bit on how gradle/ruby works. The key part in my script above is the varient.dirName as the previous script does not handle flavours at all.

this script finds the actual R class from the varient u are currently building and copies it to its relevant location. 

The source definition also HAS to be defined correctly. notice i specify the build/intermediate/ paths  for that too else it wont find your test code at all.

**Comment by imbeyondboredom** [comment]
I would like to argue that this is actually a bug and not an enhancement. Basically if you depend on library AARs (like appcompat) then you can't write unit tests. This is a pretty widespread problem.

I'll see if I can dig around and figure out how to fix but I do think the labelling for this issue is incorrect.

**Comment by jcogilvie** [comment]
Here's some code that works for arbitrary libraries by scanning exploded-aar.  It also does the same magic for /assets dirs.

```
afterEvaluate { project ->

    android.libraryVariants.each { variant ->
        def aars = new File(project.buildDir.absolutePath + "/intermediates/exploded-aar")
        def manifestFiles = new ArrayList<File>()

        // Iterate through the exploded-aars directory, finding the manifests
        aars.eachFileRecurse(FILES) {
            if (it.name.endsWith('AndroidManifest.xml') && !it.absolutePath.contains('aapt')) {
                manifestFiles.add(it)
            }
        }

        // TODO extract from our manifest?  Should be on the build variant
        def myPackageNamespace = ${INSERT YOUR PACKAGE NAMESPACE HERE, com.myapp.whatever}
        def myPackagePath = myPackageNamespace.replaceAll("\\.", "/")

        manifestFiles.each {
            def parsedManifestRoot = (new XmlParser()).parse(it.absolutePath)
            def targetPackageNamespace = parsedManifestRoot.@package
            def manifestDirectory = it.parent

            def targetPackageNamespacePath = targetPackageNamespace.replaceAll("\\.", "/")
            def copyRJavaTaskName = "copy${variant.name.capitalize()}" +
                    targetPackageNamespacePath.split("/").collect {
                        it.toString().capitalize()
                    }.join("")

            task(copyRJavaTaskName, type: Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "build/generated/source/r/${variant.name}/$myPackagePath" }
                into { "src/test/java/$targetPackageNamespacePath" }
                include 'R.java'
                filter { line -> line.contains("package ${myPackageNamespace};") ? "package ${targetPackageNamespace};" : line }
                outputs.upToDateWhen { false }
            }

            tasks.getByName("compile${variant.name.capitalize()}UnitTestJavaWithJavac") dependsOn copyRJavaTaskName

            def copyAssetsTaskName = "copy${variant.name.capitalize()}" +
                    targetPackageNamespacePath.split("/").collect {
                        it.toString().capitalize()
                    }.join("") + "Assets"

            task(copyAssetsTaskName, type: Copy) {
                dependsOn "process${variant.name.capitalize()}Resources"
                from { "${manifestDirectory}/assets" }
                into { "build/intermediates/bundles/${variant.name}/assets" }
                include '**/*'
                outputs.upToDateWhen { false }
            }

            tasks.getByName("test${variant.name.capitalize()}UnitTest") dependsOn copyAssetsTaskName

        }

    }
}
```

**Comment by MartinRajniak** [comment]
Have you actually tried this scenario without using Robolectric? I mean reference library resource in Android Unit Test but without Robolectric support? I have created a minimal test project to try it out and   I am seeing exactly same issues. So it might be that this one is not on Robolectric. You can check out more here: https://groups.google.com/d/msg/adt-dev/RacBvzBTq9M/5fEv9QD2BwAJ

**Comment by vlazzle** [comment]
Thanks Jonathan and Martin!

**Comment by jcogilvie** [comment]
I've had to update this slightly to deal with tests in subprojects.

```groovy
// After gradle's done compiling the code, it'll run this to add some more tasks for us.
    afterEvaluate { project ->

        // Debug and release get their own tasks
        android.libraryVariants.each { variant ->

            // TODO may be on the build variant
            def myManifestRoot = (new XmlParser()).parse("${project.projectDir}/src/main/AndroidManifest.xml")
            def myPackageNamespace = myManifestRoot.@package
            def myPackagePath = myPackageNamespace.replaceAll("\\.", "/")

            def processedPackages = new ArrayList<String>()

            // Task one of two that we're adding:  it depends on discovering manifest files
            // and on processing resources for this build variant.  It copies the merged R.java file
            // from our project's namespace (which contains the resource IDs included in our
            // dependencies) and drops it into each of our dependencies' namespaces.  This is to work
            // around limitations in robolectric.
            def copyRJavaTaskName = "copy${variant.name.capitalize()}RJavaForRobolectric"
            task(copyRJavaTaskName,
                    dependsOn: ["process${variant.name.capitalize()}Resources", "discoverManifestFiles"]) << {

                // For each manifest file we discovered earlier, open it up an pull out the package
                project.ext.manifestFiles.each {
                    def parsedManifestRoot = (new XmlParser()).parse(it.absolutePath)
                    def targetPackageNamespace = parsedManifestRoot.@package

                    // If it was already added, skip it
                    if (!processedPackages.contains(targetPackageNamespace)) {
                        processedPackages.add(targetPackageNamespace)
                    } else {
                        println "WARNING:  Found two versions of $targetPackageNamespace; this could mess" +
                                " with your assets and resources"
                        // For some reason there are two versions of this dependency
                        // so skip additional iterations
                        return
                    }

                    def targetPackageNamespacePath = targetPackageNamespace.replaceAll("\\.", "/")

                    // Copy R.java from our outputs into the namespace of each dependency
                    // (and change the package line in the file, correspondingly)
                    copy {
                        from "${project.buildDir}/generated/source/r/${variant.name}/$myPackagePath"
                        include 'R.java'
                        into "${project.projectDir}/src/test/java/$targetPackageNamespacePath"
                        filter { line -> line.contains("package ${myPackageNamespace};") ? "package ${targetPackageNamespace};" : line }
                    }
                }
            }
            // Insert this new task into the task tree:  compiling unit tests depends on it.
            tasks.getByName("compile${variant.name.capitalize()}UnitTestJavaWithJavac") dependsOn copyRJavaTaskName

            // Second task we're adding:  copy lib assets into the place where robolectric expects them.
            // It depends on processing this variant's resources and on discovering manifest files.
            def copyAssetsTaskName = "copy${variant.name.capitalize()}AssetsForRobolectric"
            task(copyAssetsTaskName,
                    dependsOn: ["process${variant.name.capitalize()}Resources", "discoverManifestFiles"]) << {

                // For each manifest file we discovered, find that project's assets folder and copy it
                // to the same merged destination dir
                project.ext.manifestFiles.each {
                    def manifestDirectory = it.parent

                    def src = "${manifestDirectory}/assets"
                    def dest = "${project.buildDir}/intermediates/bundles/${variant.name}/assets"

                    copy {
                        from src
                        include '**/*'
                        into dest
                    }
                }
            }
            // Insert this new task into the task tree:  executing unit tests depends on it.
            tasks.getByName("test${variant.name.capitalize()}UnitTest") dependsOn copyAssetsTaskName
        }
    }
```

**Comment by jonneymendoza** [comment]
Hi all. it appears my orginal solution no longer works on the latest android studio 

i get this error:

Task with name 'compileQaDebugUnitTestJava' not found in project ':lastminute'.
<a href="openFile:/Users/tresti/Projects/Android/android_hotel_module/lastminute/build.gradle">Open File</a>

this needs to be addressed properly without hacks

**Comment by nenick** [comment]
@jonneymendoza What did you change so thats no longer work?

It will be hard to fix this issue. In android library modules the R classes from the aar dependencies aren't generated / copied how it is done in application modules.

**Comment by jonneymendoza** [comment]
@nenick I simply updated Android studio to the latest version

**Comment by nenick** [comment]
Maybe the task test${variant.name.capitalize()}UnitTest is no longer executed? Does you run configuration use Make or Gradle-aware Make?

**Comment by Praveen-Android** [comment]
@jonneymendoza looks like with 1.3 and up, task names "testDebug" is now "testDebugUnitTest" and in your case "compileQaDebugUnitTestJava" would be "compileQaDebugUnitTestJavaWithJavac". Hope it works for you

**Comment by RyanNewsom** [comment]
FYI I saw this in one of our apps build.gradle, and I believe this resolves it.
```gradle
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

**Comment by slott** [comment]
Having a similar issue and I have the above in my build.gradle...
