### ISSUE TITLE
Nineoldandroids NullPointerException in AnimatorProxy with Robolectric

### ISSUE THREAD

**Issue by vkislicins** [robolectric/robolectric#1753]
Not really sure if that's even a Robolectric issue but maybe someone who knows a bit more how Robolectic is handling things inside its shadow classes can help out?

The view I'm testing has animation and it seems to go quite wrong when I test the view with Robolectric. I'm not really trying to test the animation - it just gets triggered automatically when I attempt to test my view. The animation is a simple slide away using Nineoldandroids for compatibility.

```
                    set.playTogether(
                            ObjectAnimator.ofFloat(viewOne, "y", 50, 150),
                            ObjectAnimator.ofFloat(viewOne, "alpha", 1, 0),
                            ObjectAnimator.ofFloat(viewTwo, "y", -100, 10),
                            ObjectAnimator.ofFloat(viewTwo, "alpha", 0, 1)
                    );
                    set.setDuration(300).start();
```

 All works fine outside of Robolectric, however my unit test is crashing with null pointer:

```
10:34:35.419 [DEBUG] [TestEventLogger]     java.lang.NullPointerException
10:34:35.419 [DEBUG] [TestEventLogger]      at com.nineoldandroids.view.animation.AnimatorProxy.applyTransformation(AnimatorProxy.java:316)
10:34:35.419 [DEBUG] [TestEventLogger]      at android.view.animation.Animation.getTransformation(Animation.java:870)
10:34:35.420 [DEBUG] [TestEventLogger]      at org.robolectric.shadows.ShadowView$2.run(ShadowView.java:492)
10:34:35.420 [DEBUG] [TestEventLogger]      at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:218)
10:34:35.420 [DEBUG] [TestEventLogger]      at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:73)
10:34:35.421 [DEBUG] [TestEventLogger]      at org.robolectric.shadows.ShadowChoreographer.postCallbackDelayed(ShadowChoreographer.java:44)
10:34:35.421 [DEBUG] [TestEventLogger]      at android.view.Choreographer.postCallbackDelayed(Choreographer.java)
10:34:35.427 [DEBUG] [TestEventLogger]      at org.robolectric.shadows.ShadowView.setAnimation(ShadowView.java:487)
10:34:35.429 [DEBUG] [TestEventLogger]      at android.view.View.setAnimation(View.java)
10:34:35.431 [DEBUG] [TestEventLogger]      at com.nineoldandroids.view.animation.AnimatorProxy.<init>(AnimatorProxy.java:66)
10:34:35.432 [DEBUG] [TestEventLogger]      at com.nineoldandroids.view.animation.AnimatorProxy.wrap(AnimatorProxy.java:38)
10:34:35.432 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.PreHoneycombCompat$14.get(PreHoneycombCompat.java:161)
10:34:35.432 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.PreHoneycombCompat$14.get(PreHoneycombCompat.java:153)
10:34:35.432 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:510)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:410)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:538)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:928)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:951)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:385)
10:34:35.433 [DEBUG] [TestEventLogger]      at com.nineoldandroids.animation.AnimatorSet.start(AnimatorSet.java:502)
```

If I add a check into my app code to only use Nineoldandroids for API <11 and by default use android native animation the test passes just fine. From the Nineoldandroids source I can see that it's null pointering on this line:

```
View view = mView.get();
```

where `mView = new WeakReference<View>(view);`

Is this a genuine issue or expected behaviour? Any suggestions how to work around this ideally from the test case and not my app code?

**Comment by erd** [comment]
We've tried to implement enough animation code so callbacks work correctly and it prevents NPEs. Despite this, animation support is still not great.

**Comment by kriegfrj** [comment]
I wonder if this might also be a manifestation of inline posts (#1770)?

**Comment by jaredsburrows** [comment]
@erd  @vkislicins  Please bare in mind that [NineOldAndroids](https://github.com/JakeWharton/NineOldAndroids) is deprecated.
