### ISSUE TITLE
SQLiteOpenHelperTest causing FileSystemException on Windows

### ISSUE THREAD

**Issue by kriegfrj** [robolectric/robolectric#1754]
`SQLiteOpenHelperTest` has never run well on Windows, however with a recent change on master, (looks like attempted cleanup code to remove the temp directory) - I have been running into the following:

      Caused by: java.nio.file.FileSystemException:
      C:\Users\Jeremy\AppData\Local\Temp\android-tmp-robolectric250258741663565975\databases\path:
      The process cannot access the file because it is being used by another process.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1123)
        at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:84)
        at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:81)
        at java.nio.file.Files.walkFileTree(Files.java:2667)
        at java.nio.file.Files.walkFileTree(Files.java:2739)
        at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:81)
        at org.robolectric.util.TempDirectory.destroyImpl(TempDirectory.java:70)
        ... 27 more

What seems to happen is that the tests run fine until it gets to the `SQLiteOpenHelperTest`, and thereafter all the tests fail with the above error. The SQLite stuff has never played nice under Windows - Windows is a a little bit more pedantic about removing files that are still in use, and I've always had errors about a process still having the database open in the SQLite-related tests. As I haven't been doing any testing with SQLite so far I've just been ignoring these errors, but now that it's causing other unrelated tests to fail too it gets a bit harder to ignore it.

I'm wondering if this is related to #1510 - if a static reference is held to the connection that persists between tests, then that would hold the file open (and locked) across tests, which would cause the above.

**Comment by kriegfrj** [comment]
I started having a look at this - it seems that it has something to do with the issue that #1748 was attempting to solve; however I had a look at the code and noticed that even after #1748 there are still a few unclosed `TestOpenHandler`s left lying around by individual tests that the global `tearDown()` doesn't clean up. I managed to fix the remaining unclosed `TestOpenHandler`s and this problem went away.

Before looking at repeating the fix with `SQLiteDatabaseTest`, I thought about the more generic problem - if any Robolectric databases are left opened in any test, it will cause all subsequent tests to fail. So perhaps a more scalable solution would be to fix it on the core/shadow side - rather than rely on every test to do the right thing and clean up after itself, Robolectric can keep track of the open database connections and close them all at `reset()`. #1510 would be part (maybe all?) of this solution.

I think of a legitimate case for keeping a database open between test runs, but if anyone knows of one it would be good to hear about it before I go to the effort of implementing the fix.

**Comment by erd** [comment]
> So perhaps a more scalable solution would be to fix it on the core/shadow side - rather than rely on every test to do the right thing and clean up after itself, Robolectric can keep track of the open database connections and close them all at reset()

This sounds like a reasonable approach.

**Comment by jongerrish** [comment]
Agreed!
