### ISSUE TITLE
java.lang.NoClassDefFoundError: org/robolectric/util/TempDirectory

### ISSUE THREAD

**Issue by Jivyx** [robolectric/robolectric#1755]
Hi, after automatically upgrade dependancies today (30/04), I got this error :
```
java.lang.NoClassDefFoundError: org/robolectric/util/TempDirectory
	at org.robolectric.shadows.ShadowEnvironment.reset(ShadowEnvironment.java:59)
	at org.robolectric.Shadows.reset(Shadows.java:1354)
	at org.robolectric.Robolectric.reset(Robolectric.java:20)
	at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:40)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:216)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.ClassNotFoundException: org.robolectric.util.TempDirectory
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:166)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
	... 21 more
```

Here is an exemple of a class : 
```
@RunWith(RobolectricTestRunner.class)
@Config(manifest = Config.NONE)
public class RegexEventTest {
   ...
}
```

**Comment by erd** [comment]
`org.robolectric.util.TempDirectory` was recently introduced. You probably need to force a snapshot update. Try `mvn --update-snapshots` or `gradle --refresh-dependencies`

**Comment by liangxianshen** [comment]
There will be a TempDirectory  NoClassDefFoundError

Android studio 3.0.1
robolectric-utils:3.4-rc2'
shadows-support-v4:3.4-rc2"
robolectric:3.6-alpha-1"
