### ISSUE TITLE
Robolectric doesn't recognize decimal based dp dimensions without a leading 0 

### ISSUE THREAD

**Issue by surge1** [robolectric/robolectric#1769]
I have a line divider view along the lines of 

```
               <View
                    android:id="@+id/event_type_divider"
                    android:layout_width="match_parent"
                    android:layout_height="@dimen/divider_height"
                    android:background="@color/dark_gray"
                    android:layout_marginLeft="@dimen/spacing_small"
                    android:layout_marginRight="@dimen/spacing_small"
                    style="@style/HorizontalDivider"
                    />
```

where  
```
    <dimen name="divider_height">.75dp</dimen>
```

running this will cause all tests for the activity containing it to fail. stack trace is as follows 
```
java.lang.RuntimeException: XML file ../app/build/intermediates/res/prod/debug/layout/activity_email.xml line #-1 (sorry, not yet implemented): You must supply a layout_height attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:606)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6423)
	at android.view.ViewGroup$MarginLayoutParams.__constructor__(ViewGroup.java:6591)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java)
	at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java)
	at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1083)
	at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:82)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:808)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
	at com.weddingwire.vendorclients.view.activity.EmailActivity.onCreate(EmailActivity.java:105)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:144)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:241)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:138)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:309)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at com.weddingwire.vendorclients.BaseActivityRobolectricTest.startActivity(BaseActivityRobolectricTest.java:56)
	at com.weddingwire.vendorclients.view.activity.EmailActivityTest.setupActivity(EmailActivityTest.java:71)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

however changing it to 1dp or 0.75dp will remove this problem and allow tests to pass. IDE is throwing no warnings on fractional DPs without a leading 0 so just wanted to make the issue known.

**Comment by erd** [comment]
Which version of Robolectric are you using?

**Comment by surge1** [comment]
robolectric:3.0-rc2

**Comment by ndtaylor** [comment]
Any progress on this issue?

**Comment by xian** [comment]
This is fixed in Robolectric 4.0's [binary resources mode](http://robolectric.org/migrating/#migrating-to-40).
