### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by pdiegmann** [robolectric/robolectric#1782]
Dear all,

we discovered some unexpected behavior running test with shadows on 3.0-SNAPSHOT (Wed May 06 2015 05:51:31 GMT+0200). 
Translating "Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird" means "The process cannot access the file because it is being used by another process".
We tried to clean all directories (Windows/TEMP as well as the project's directory itself).

Any additional ideas / workarounds?

Thank you very much,
Phil

The test we ran:
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,manifest = "src/main/AndroidManifest.xml",sdk = 19)
public class StartScreenActivityTest {
    private ShadowActivity startScreenShadow;
    private StartScreenActivity startScreenActivity;

    @Before
    public void setUp() {
        startScreenActivity = Robolectric.setupActivity(StartScreenActivity.class);
        startScreenShadow = shadowOf(startScreenActivity);
    }

    @Test
    public void checkRuntimeEnvironment() {
        assertThat(RuntimeEnvironment.application, notNullValue());
    }

    @Test
    public void checkNumbers() {
        assertThat(10, is(equalTo(9 + 2 - 1)));
    }

    @Test
    public void clickArrow() {
        View startButton = startScreenActivity.findViewById(R.id.startArrow);

        startButton.performClick();

        Intent startedIntent = startScreenShadow.getNextStartedActivity();
        assertThat(startedIntent.getComponent().getClassName(), equalTo(StartActivity.class.getName()));
    }
}
```
The error log:
```
java.lang.RuntimeException: java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Windows\TEMP\android-tmp-robolectric8808008674917068265\databases\tracemate-db: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

java.lang.RuntimeException: java.nio.file.FileSystemException: C:\Windows\TEMP\android-tmp-robolectric8808008674917068265\databases\tracemate-db: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at org.robolectric.util.TempDirectory.destroyImpl(TempDirectory.java:76)
	at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:50)
	at org.robolectric.shadows.ShadowEnvironment.reset(ShadowEnvironment.java:59)
	at org.robolectric.Shadows.reset(Shadows.java:1349)
	at org.robolectric.Robolectric.reset(Robolectric.java:22)
	at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:43)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:253)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: C:\Windows\TEMP\android-tmp-robolectric8808008674917068265\databases\tracemate-db: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:84)
	at org.robolectric.util.TempDirectory$2.visitFile(TempDirectory.java:81)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:81)
	at org.robolectric.util.TempDirectory.destroyImpl(TempDirectory.java:70)
	... 40 more
```

**Comment by lexs** [comment]
This sounds like you have a separate thread holding the db open after tests have finished. While this should be avoided I guess we could be more liberal when trying to clear the directory and simply throw it away if we can't clear it.
