### ISSUE TITLE
java.lang.ClassNotFoundException: org.robolectric.res.builder.XmlFileBuilder

### ISSUE THREAD

**Issue by solidi** [robolectric/robolectric#1785]
Hi,

Since late yesterday our tests started to fail via xml lookups with the following:

```
14:41:09.245 [DEBUG] [TestEventLogger] com.abc.a.test.DialogBoardActivityTest > pausesAndResumesActivity FAILED
14:41:09.246 [DEBUG] [TestEventLogger]     java.lang.NoClassDefFoundError: org/robolectric/res/builder/XmlFileBuilder
14:41:09.246 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)
14:41:09.246 [DEBUG] [TestEventLogger]         at android.content.res.Resources.loadXmlResourceParser(Resources.java)
14:41:09.246 [DEBUG] [TestEventLogger]         at android.content.res.Resources.loadXmlResourceParser(Resources.java:2600)
14:41:09.246 [DEBUG] [TestEventLogger]         at android.content.res.Resources.getLayout(Resources.java:1049)
14:41:09.246 [DEBUG] [TestEventLogger]         at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
14:41:09.246 [DEBUG] [TestEventLogger]         at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
14:41:09.246 [DEBUG] [TestEventLogger]         at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3489)
14:41:09.246 [DEBUG] [TestEventLogger]         at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3561)
14:41:09.246 [DEBUG] [TestEventLogger]         at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:367)
14:41:09.247 [DEBUG] [TestEventLogger]         at android.app.Activity.setContentView(Activity.java:2144)
14:41:09.247 [DEBUG] [TestEventLogger]         at com.abc.a.test.DialogBoardActivity.onCreate(DialogBoardActivity.java:78)
14:41:09.247 [DEBUG] [TestEventLogger]         at android.app.Activity.performCreate(Activity.java:5933)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.util.ActivityController.create(ActivityController.java:118)
14:41:09.247 [DEBUG] [TestEventLogger]         at org.robolectric.util.ActivityController.create(ActivityController.java:129)
14:41:09.247 [DEBUG] [TestEventLogger]         at com.abc.a.test.DialogBoardActivityTest.createWithIntent(DialogBoardActivityTest.java:46)
14:41:09.248 [DEBUG] [TestEventLogger]         at com.abc.a.test.DialogBoardActivityTest.pausesAndResumesActivity(DialogBoardActivityTest.java:60)
14:41:09.248 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
14:41:09.248 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
14:41:09.248 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
14:41:09.248 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
14:41:09.248 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
14:41:09.249 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
14:41:09.250 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
14:41:09.251 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
14:41:09.252 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
14:41:09.252 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
14:41:09.252 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:41:09.252 [DEBUG] [TestEventLogger]         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:41:09.252 [DEBUG] [TestEventLogger]         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
14:41:09.252 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
14:41:09.252 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
14:41:09.253 [DEBUG] [TestEventLogger]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
14:41:09.253 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:745)
14:41:09.253 [DEBUG] [TestEventLogger] 
14:41:09.253 [DEBUG] [TestEventLogger]         Caused by:
14:41:09.253 [DEBUG] [TestEventLogger]         java.lang.ClassNotFoundException: org.robolectric.res.builder.XmlFileBuilder
14:41:09.253 [DEBUG] [TestEventLogger]             at org.robolectric.internal.bytecode.InstrumentingClassLoader.getByteCode(InstrumentingClassLoader.java:168)
14:41:09.254 [DEBUG] [TestEventLogger]             at org.robolectric.internal.bytecode.InstrumentingClassLoader.findClass(InstrumentingClassLoader.java:123)
14:41:09.254 [DEBUG] [TestEventLogger]             at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:95)
14:41:09.254 [DEBUG] [TestEventLogger]             at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)
14:41:09.254 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:41:09.254 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14:41:09.254 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:41:09.255 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:606)
14:41:09.255 [DEBUG] [TestEventLogger]             at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
14:41:09.255 [DEBUG] [TestEventLogger]             at android.content.res.Resources.loadXmlResourceParser(Resources.java)
14:41:09.255 [DEBUG] [TestEventLogger]             at android.content.res.Resources.$$robo$$loadXmlResourceParser(Resources.java:2600)
14:41:09.255 [DEBUG] [TestEventLogger]             at android.content.res.Resources.loadXmlResourceParser(Resources.java)
14:41:09.255 [DEBUG] [TestEventLogger]             at android.content.res.Resources.$$robo$$getLayout(Resources.java:1049)
14:41:09.256 [DEBUG] [TestEventLogger]             at android.content.res.Resources.getLayout(Resources.java)
14:41:09.256 [DEBUG] [TestEventLogger]             at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:412)
14:41:09.256 [DEBUG] [TestEventLogger]             at android.view.LayoutInflater.inflate(LayoutInflater.java)
14:41:09.256 [DEBUG] [TestEventLogger]             at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:365)
14:41:09.256 [DEBUG] [TestEventLogger]             at android.view.LayoutInflater.inflate(LayoutInflater.java)
14:41:09.256 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.$$robo$$generateLayout(PhoneWindow.java:3489)
14:41:09.257 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java)
14:41:09.257 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.$$robo$$installDecor(PhoneWindow.java:3561)
14:41:09.257 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java)
14:41:09.257 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:367)
14:41:09.257 [DEBUG] [TestEventLogger]             at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
14:41:09.257 [DEBUG] [TestEventLogger]             at android.app.Activity.$$robo$$setContentView(Activity.java:2144)
14:41:09.258 [DEBUG] [TestEventLogger]             at android.app.Activity.setContentView(Activity.java)
14:41:09.258 [DEBUG] [TestEventLogger]             at com.abc.a.test.DialogBoardActivity.onCreate(DialogBoardActivity.java:78)
14:41:09.258 [DEBUG] [TestEventLogger]             at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
14:41:09.258 [DEBUG] [TestEventLogger]             at android.app.Activity.performCreate(Activity.java)
14:41:09.258 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:41:09.258 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14:41:09.258 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:41:09.259 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:606)
14:41:09.259 [DEBUG] [TestEventLogger]             at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
14:41:09.259 [DEBUG] [TestEventLogger]             at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
14:41:09.259 [DEBUG] [TestEventLogger]             at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
14:41:09.259 [DEBUG] [TestEventLogger]             at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
14:41:09.259 [DEBUG] [TestEventLogger]             at org.robolectric.util.ActivityController.create(ActivityController.java:118)
14:41:09.260 [DEBUG] [TestEventLogger]             at org.robolectric.util.ActivityController.create(ActivityController.java:129)
14:41:09.260 [DEBUG] [TestEventLogger]             at com.abc.a.test.DialogBoardActivityTest.createWithIntent(DialogBoardActivityTest.java:46)
14:41:09.260 [DEBUG] [TestEventLogger]             at com.abc.a.test.DialogBoardActivityTest.pausesAndResumesActivity(DialogBoardActivityTest.java:60)
14:41:09.260 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:41:09.260 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14:41:09.260 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:41:09.260 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:606)
14:41:09.260 [DEBUG] [TestEventLogger]             at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
14:41:09.261 [DEBUG] [TestEventLogger]             at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
14:41:09.262 [DEBUG] [TestEventLogger]             at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
14:41:09.263 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
14:41:09.263 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
14:41:09.263 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
14:41:09.263 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
14:41:09.263 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:41:09.263 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14:41:09.263 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:41:09.264 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:606)
14:41:09.264 [DEBUG] [TestEventLogger]             at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
14:41:09.264 [DEBUG] [TestEventLogger]             at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
14:41:09.264 [DEBUG] [TestEventLogger]             at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
14:41:09.264 [DEBUG] [TestEventLogger]             at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
14:41:09.264 [DEBUG] [TestEventLogger]             at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
14:41:09.264 [DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
14:41:09.264 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:41:09.265 [DEBUG] [TestEventLogger]             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
14:41:09.265 [DEBUG] [TestEventLogger]             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:41:09.265 [DEBUG] [TestEventLogger]             at java.lang.reflect.Method.invoke(Method.java:606)
14:41:09.265 [DEBUG] [TestEventLogger]             ... 7 more
```

currently using
robolectric-resources-3.0-20150506.035051-337.jar
shadows-core-3.0-20150506.035114-458.jar
robolectric-utils-3.0-20150506.035046-362.jar
robolectric-annotations-3.0-20150506.035041-367.jar

Can a reason be found on this?

**Comment by erd** [comment]
Are you using snapshots? Sometimes Maven / Gradle doesn't pull new versions of all of robolectric's dependencies. Try running `gradle --refresh-dependencies` or `mvn --update-snapshots`

**Comment by solidi** [comment]
Yep, that was the issue. We even tried as you suggested before filing this ticket (the --refresh-dependencies and removal of grade cache)... and still had the problem for a few hours until, magically, we got the update and all began to work okay. *shrugs*
