### ISSUE TITLE
Robolectric started failing just from today

### ISSUE THREAD

**Issue by pickeyboy** [robolectric/robolectric#1787]
I am using "org.robolectric:robolectric:3.0-SNAPSHOT".. It suddenly started failing with below errors.. 
all my test cases are failing .. Guys any update? 

    java.lang.NoClassDefFoundError: org/robolectric/res/builder/XmlFileBuilder
        at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:443)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2311)
        at android.content.res.Resources.getLayout(Resources.java:939)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:395)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2966)
        at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3029)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:286)

**Comment by ralphpina** [comment]
Same here, but for the support lib. I was using:

```
testCompile('org.robolectric:shadows-support-v4:3.0-SNAPSHOT') {
   changing true
}
```

And I was getting this:

```java
java.lang.NoClassDefFoundError: android/support/v4/app/NotificationManagerCompatEclair
	at android.support.v4.app.NotificationManagerCompat$ImplEclair.cancelNotification(NotificationManagerCompat.java:146)
	at android.support.v4.app.NotificationManagerCompat.cancel(NotificationManagerCompat.java:189)
	at android.support.v4.app.NotificationManagerCompat.cancel(NotificationManagerCompat.java:180)
	at com.cotap.android.notifications.NotificationHelper.cancelConversationNotification(NotificationHelper.java:205)
```

It went away when I reverted to 3.0-rc2:

```
testCompile('org.robolectric:shadows-support-v4:3.0-rc2') {
     changing true
}
```

**Comment by pickeyboy** [comment]
It seems SNAPSHOT version is currently broke.. I can't go back to RC2 some of changes may not work with RC2.. will wait until it is up .

**Comment by erd** [comment]
Maven / Gradle will occasionally not grab all the updated artifacts. Try running your tests on the command line with `gradle --refresh-dependencies` or `mvn --update-snapshots`.
