### ISSUE TITLE
Tests fail without touching actual test code

### ISSUE THREAD

**Issue by urandom** [robolectric/robolectric#1788]
I just migrated to robolectric-3.0-rc2, and it was mostly a success. One of my test files produces rather bizare failures though. Its reporting the following stack trace, though the stack itself doesn't actually go through any of my code. Is this a bug in robolectric itself?

org.sugr.gearshift.unit.core.TransmissionProfileTest > lastDownloadDirectory STANDARD_ERROR
   java.lang.NullPointerException
    	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
    	at android.os.Looper.getMainLooper(Looper.java)
    	at org.robolectric.shadows.ShadowLooper.getUiThreadScheduler(ShadowLooper.java:85)
    	at org.robolectric.shadows.ShadowSystemClock.now(ShadowSystemClock.java:20)
    	at org.robolectric.shadows.ShadowSystemClock.uptimeMillis(ShadowSystemClock.java:41)
    	at org.robolectric.shadows.ShadowSystemClock.elapsedRealtime(ShadowSystemClock.java:46)
    	at android.os.SystemClock.elapsedRealtime(SystemClock.java)
    	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:86)

**Comment by ramtej** [comment]
Same issue here..

**Comment by jaredsburrows** [comment]
Post the test code. How else can we help or even try to reproduce it?

**Comment by urandom** [comment]
https://github.com/urandom/gearshift/blob/master/gearshift/src/test/java/org/sugr/gearshift/unit/core/TransmissionProfileTest.java

**Comment by jaredsburrows** [comment]
Robolectric 3.0-rc3 is out now.

Why are you mocking `Context` when you can just use `RuntimeEnvironment.application`?

Can you narrow it down to which assetion in `lastDownloadDirectory` is failing?

**Comment by jongerrish** [comment]
+1 I recommend against mocking almost any android classes since Robolectric
wires up almost all android classes as you'd expect. There are some
exceptions, like listener interfaces etc.

**Comment by jaredsburrows** [comment]
@jongerrish Thanks for explaining. Robolectric covers a lot already and I tend to `mock` classes and interfaces for listener.

**Comment by erd** [comment]
Robolectric does not work correctly when you mix mocking and shadows. If you mock a class that Robolectric assumes will be real, you will get unexpected results. In general, you shouldn't mock classes that you don't own.
