### ISSUE TITLE
Problem when running tests that involve animations in Robolectric 2.4

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1790]
I have a couple of SweetAlert dialogs in my project (https://github.com/pedant/sweet-alert-dialog)
that run fine, but when I run them in robolectric I get this exception:

```
java.lang.RuntimeException:  Unknown animation name:  sweet:cn.pedant.SweetAlert.Rotate3dAnimation error:sweet:cn.pedant.SweetAlert.Rotate3dAnimation      
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
at com.myapp.activity.register.RegisterActivity.showNotConnectedToTheInternetDialog(RegisterActivity.java:213)
```

Can anyone tell me with a quick look if this looks like a robolectric issue not loading the animation properly, or whether I should start looking elsewhere? 

P.S I've already added the library in the project.properties

Thanks.

**Comment by jongerrish** [comment]
Animations are fairly broken in 2.4 and much improved in 3.0 when they run
real android code. I'd recommend upgrading.

**Comment by athkalia** [comment]
Thanks for the feedback, planning to as soon as final 3.0 is out, we don't do release candidates unfortunately ! :D

**Comment by anmolxicom** [comment]
This is crashing even in version 3.0 , What is the solution to this ?


ava.lang.RuntimeException: Unknown animation name: sweet:cn.pedant.SweetAlert.Rotate3dAnimation error:sweet:cn.pedant.SweetAlert.Rotate3dAnimation

	at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:77)
	at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:64)
	at cn.pedant.SweetAlert.OptAnimationLoader.createAnimationFromXml(OptAnimationLoader.java:41)
	at cn.pedant.SweetAlert.OptAnimationLoader.loadAnimation(OptAnimationLoader.java:22)
	at cn.pedant.SweetAlert.SweetAlertDialog.<init>(SweetAlertDialog.java:80)
	at com.montessorinotes.utils.CommonFunctions.getProgressAlert(CommonFunctions.java:514)
	at com.montessorinotes.core.BaseActivity.onCreate(BaseActivity.java:31)
	at com.montessorinotes.modules.dashboard.MainActivity.onCreate(MainActivity.java:103)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at montessorinotes.MainActivityTest.setup(MainActivityTest.java:40)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
