### ISSUE TITLE
RoboSharedPreferences issue in 3.0-rc2

### ISSUE THREAD

**Issue by athkalia** [robolectric/robolectric#1791]
Getting this exception in one of my tests after moving to robolectric 3.0-rc2

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
    at org.robolectric.fakes.RoboSharedPreferences.getLong(RoboSharedPreferences.java:60)
    at org.androidannotations.api.sharedpreferences.LongPrefField.getOr(LongPrefField.java:29)
    at org.androidannotations.api.sharedpreferences.LongPrefField.getOr(LongPrefField.java:20)
    at org.androidannotations.api.sharedpreferences.AbstractPrefField.get(AbstractPrefField.java:43)
    at com.follower.activity.settings.SettingsActivityTest.defaultAutomatedFollowSignalsIntervalValueIsCorrect(SettingsActivityTest.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

The exception occurs in this piece of code in android annotations inside the first catch statement..

```
@Override
    public Long getOr(Long defaultValue) {
        try {
            return sharedPreferences.getLong(key, defaultValue);
        } catch (ClassCastException e) {
            // The pref could be a String, if that is the case try this
            // recovery bit
            try {
                String value = sharedPreferences.getString(key, "" + defaultValue);
                return Long.parseLong(value);
            } catch (Exception e2) {
                // our recovery bit failed. The problem is elsewhere. Send the
                // original error
                throw e;
            }
        }
    }
```

Robolectric is asked to fetch the String (value is "60000")

```
    String value = sharedPreferences.getString(key, "" + defaultValue);
```

but returns a hex value (0xea60 instead of "60000") , which then can't be parsed via the Long.parseLong.

Same code when debugged in an application returns  the String "60000"

not quite sure why this is happening !

**Comment by xian** [comment]
[Robolectric 4.0](http://robolectric.org/blog/2018/10/25/robolectric-4-0/) fixes many longstanding issues; could you check to see if this remains a problem?

If so, please feel free to reopen this issue and include a link to a public git repo demonstrating the problem to help us diagnose. Thank you!
