### ISSUE TITLE
Animation NoSuchMethodError: org.robolectric.util.Scheduler.postDelayed(Runnable, Object)

### ISSUE THREAD

**Issue by ubelab** [robolectric/robolectric#1799]
After the recent commits my tests crash, probably when an animation in involved.

Robolectric version: 3.0-SNAPSHOT
Android Studio 1.2
emulateSDK = 21

Code:
```
slideUpPanel.post(new Runnable() {
            @Override
            public void run() {
                ObjectAnimator anim = ObjectAnimator.ofFloat(slideUpPanel, "translationY", 0f, slideUpPanel.getMeasuredHeight());
                anim.setDuration(100);
                anim.start();
            }
        });
```

Stacktrace:
```
java.lang.NoSuchMethodError: org.robolectric.util.Scheduler.postDelayed(Ljava/lang/Runnable;JLjava/lang/Object;)V
	at org.robolectric.shadows.ShadowChoreographer.postCallbackDelayed(ShadowChoreographer.java:44)
	at android.view.Choreographer.postCallbackDelayed(Choreographer.java)
	at android.view.Choreographer.postCallback(Choreographer.java:291)
	at android.animation.ValueAnimator$AnimationHandler.scheduleAnimation(ValueAnimator.java:687)
	at android.animation.ValueAnimator$AnimationHandler.start(ValueAnimator.java:607)
	at android.animation.ValueAnimator.start(ValueAnimator.java:964)
	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
	at android.animation.ObjectAnimator.start(ObjectAnimator.java:829)
	at com.mypackage.CommandActivity$1.run(CommandActivity.java:210)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:269)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:179)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:123)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:54)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:267)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:307)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.com.mypackage.CommandActivityUnitTest.setUp(CommandActivityUnitTest.java:55)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by erd** [comment]
Try running `gradle --refresh-dependencies` or `mvn --update-snapshots`. It sounds like you might have mismatched SNAPSHOT jars.

**Comment by ubelab** [comment]
This fix the problem. Thank you @erd .

**Comment by objcode** [comment]
@sweetleon and I have done this, as well as blown away both `~/.m2` and `~/.gradle` but it's still happening to us. Maybe it's because we installed Robolectric thru it's installation scripts (while trying to debug something else). Any other ideas?

**Comment by sweetleon** [comment]
Oops! Turned out that I'd upgraded only Robolectric's main jar to rc3 but left the Shadows at rc2. Upgrading the Shadows fixed it. (My fault entirely.)
