### ISSUE TITLE
Exception in thread "Thread-64" java.lang.RuntimeException: Unexpected call to execute, no pending responses are available.

### ISSUE THREAD

**Issue by Malachiasz** [robolectric/robolectric#1800]
I receive such an error as in title, when using DefaultHttpClient. The error doesn't occur always. For example when I run just one test in the class. Any Idea what is the cause?

Unexpected HTTP call POST https://login.mydomain.de HTTP/1.1
Exception in thread "Thread-64" java.lang.RuntimeException: Unexpected call to execute, no pending responses are available. See Robolectric.addPendingResponse(). Request was: POST https://uas2.uilogin.de
    at org.robolectric.tester.org.apache.http.FakeHttpLayer.emulateRequest(FakeHttpLayer.java:126)
    at org.robolectric.shadows.ShadowDefaultRequestDirector.execute(ShadowDefaultRequestDirector.java:168)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
    at com.MyProject.MyClass.login(Login.java:340) { return getHttpClient().execute(loginRequest); }

( Robolectric 3 )
    testCompile "org.robolectric:robolectric:3.0-SNAPSHOT"
    testCompile 'org.robolectric:shadows-support-v4:3.0-SNAPSHOT'
    testCompile 'org.robolectric:shadows-httpclient:3.0-SNAPSHOT'

**Comment by jongerrish** [comment]
Closing due to the age of the bug.

Note that apache http has been deprecated since M
