### ISSUE TITLE
AppCompatActivity view inflation error

### ISSUE THREAD

**Issue by tjohn** [robolectric/robolectric#1801]
Hey so when I am trying to inflate an AppCompatActivity I am getting a view inflation error. I am seeing the view in my generated sources and have stepped through the error a few times, but have not made any headway resolving it. I am under the impression that this should all be fixed in <https://github.com/robolectric/robolectric/issues/1446> and I am using 3.0-SNAPSHOT. 

It maybe something to do with my flavors and the fact that I add an `applicationIdSuffix` to my debug builds, but when I tried to confirm this in a separate app I couldn't reproduce this error. 

I also noticed `Caused by: java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getDrawable(Landroid/content/Context;I)Landroid/graphics/drawable/Drawable;` in the stacktrace. Do I need to do something with support-v4?

```java
android.view.InflateException: XML file build/intermediates/res/localhost/debug/layout/abc_screen_toolbar.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.v7.widget.Toolbar
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:296)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivity.onCreate(SignUpPhoneNumberActivity.java:43)
	at android.app.Activity.performCreate(Activity.java:5133)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivityTest.setUp(SignUpPhoneNumberActivityTest.java:63)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:353)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$ensureSubDecor(AppCompatDelegateImplV7.java:296)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatDelegateImplV7.$$robo$$setContentView(AppCompatDelegateImplV7.java:246)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java)
	at android.support.v7.app.AppCompatActivity.$$robo$$setContentView(AppCompatActivity.java:106)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivity.onCreate(SignUpPhoneNumberActivity.java:43)
	at android.app.Activity.$$robo$$performCreate(Activity.java:5133)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivityTest.setUp(SignUpPhoneNumberActivityTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 1 more
Caused by: java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getDrawable(Landroid/content/Context;I)Landroid/graphics/drawable/Drawable;
	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:165)
	at android.support.v7.internal.widget.TintManager.getDrawable(TintManager.java:158)
	at android.support.v7.internal.widget.TintTypedArray.getDrawable(TintTypedArray.java:62)
	at android.support.v7.widget.Toolbar.__constructor__(Toolbar.java:252)
	at android.support.v7.widget.Toolbar.<init>(Toolbar.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:296)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:246)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivity.onCreate(SignUpPhoneNumberActivity.java:43)
	at android.app.Activity.performCreate(Activity.java:5133)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.playdraft.draft.ui.SignUpPhoneNumberActivityTest.setUp(SignUpPhoneNumberActivityTest.java:63)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	... 1 more
```

**Comment by tjohn** [comment]
Ok so I am closing this issue. The problem for future people was I was targeting a newer version of appcompat v7. Specifically: com.android.support:appcompat-v7:22.0.0.

**Comment by tjohn** [comment]
more info on this, I was seeing this work from Android Studio but still failing from the command line. I don't have a reason yet, but it appears that there is some dependency issue that AS is hiding. By removing fest-android (which I should have done awhile ago) I solved this problem.
