### ISSUE TITLE
IllegalArgumentException: path must be convex

### ISSUE THREAD

**Issue by blairio** [robolectric/robolectric#1810]
When Config is set to emulateSdk 21 setting up an activity throws java.lang.IllegalArgumentException: path must be convex

When emulateSdk is 19 or 18 no exception is thrown

example: 
```java
    @Before
    public void setup() {
        ...
        activity = Robolectric.setupActivity(MyActivity.class);
    }
```

Emulating SDK 21 yields

```
java.lang.IllegalArgumentException: path must be convex
	at android.graphics.Outline.setConvexPath(Outline.java:216)
	at android.graphics.drawable.GradientDrawable.getOutline(GradientDrawable.java:1441)
	at android.graphics.drawable.RippleDrawable.getOutline(RippleDrawable.java:625)
	at android.graphics.drawable.LayerDrawable.getOutline(LayerDrawable.java:608)
	at android.graphics.drawable.InsetDrawable.getOutline(InsetDrawable.java:352)
	at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38)
	at android.view.View.rebuildOutline(View.java:11116)
	at android.view.View.onAttachedToWindow(View.java:12960)
	at android.widget.TextView.onAttachedToWindow(TextView.java:4961)
	at android.view.View.dispatchAttachedToWindow(View.java:13406)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1292)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:246)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:167)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:148)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:111)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:42)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:271)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:311)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
	at org.robolectric.util.ActivityController.visible(ActivityController.java:173)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
	at com.company.project.MyActivityTest.setup(MyActivityTest.java:42)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaredsburrows** [comment]
Is that that only code you had in your test?

**Comment by lexs** [comment]
This is likely due to Path being shadowed. It's problematic because Path is mostly native code. You might have some success by shadowing android.graphics.Outline.

**Comment by blairio** [comment]
For now my test runs against SDK 19 instead of 21. If it is useful I can try to make an isolated project that demonstrates the failure.

**Comment by Odunayo16** [comment]
Was this ever fixed?

**Comment by jaredsburrows** [comment]
> When Config is set to emulateSdk 21 setting up an activity throws java.lang.IllegalArgumentException: path must be convex

@blairio  Can you please use API 21 + Robolectric 3.0-rc3?

@Odunayo16 Are you seeing this? This issue would be closed and changes merged to master if it was fixed.

**Comment by Odunayo16** [comment]
I am using API 21 + Robolectric 3.0-rc3 and got it to work by shadowing android.graphics.Outline.

**Comment by blairio** [comment]
Still fails for me when I use Robolectric 3.0-rc3

```java
path must be convex
java.lang.IllegalArgumentException: path must be convex
	at android.graphics.Outline.setConvexPath(Outline.java:216)
	at android.graphics.drawable.GradientDrawable.getOutline(GradientDrawable.java:1441)
	at android.graphics.drawable.RippleDrawable.getOutline(RippleDrawable.java:625)
	at android.graphics.drawable.LayerDrawable.getOutline(LayerDrawable.java:608)
	at android.graphics.drawable.InsetDrawable.getOutline(InsetDrawable.java:352)
	at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38)
	at android.view.View.rebuildOutline(View.java:11116)
	at android.view.View.onAttachedToWindow(View.java:12960)
	at android.widget.TextView.onAttachedToWindow(TextView.java:4961)
	at android.view.View.dispatchAttachedToWindow(View.java:13406)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2714)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1292)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:29)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
...
```

**Comment by Odunayo16** [comment]
This seemed to work for me. Try making a custom Runner (Sorry for the formatting)
   <pre>public class CustomRobolectricRunner extends RobolectricGradleTestRunner {
    private static final int MAX_SDK_LEVEL = 21;
    private int[] sdk = {21};
    public CustomRobolectricRunner(Class<?> klass) throws InitializationError {
        super(klass);
    }
    @Override
    public Config getConfig(Method method) {
        Config config = super.getConfig(method);
		/*
		Fixing up the Config:
		* SDK can not be higher than 21
		* constants must point to a real BuildConfig class
		 */
        config = new Config.Implementation(sdk,
                config.manifest(),
                config.qualifiers(),
                config.packageName(),
                config.resourceDir(),
                config.assetDir(),
                config.shadows(),
                config.application(),
                config.libraries(),
                ensureBuildConfig(config.constants()));


        return config;
    }

    private Class<?> ensureBuildConfig(Class<?> constants) {
        if (constants == Void.class) return BuildConfig.class;
        return constants;
    }

    private int ensureSdkLevel(int sdkLevel) {
        if (sdkLevel > MAX_SDK_LEVEL) return MAX_SDK_LEVEL;
        if (sdkLevel <= 0) return MAX_SDK_LEVEL;
        return sdkLevel;
    }
}</pre>


I made a shadow of the Outline class and removed the code that was causing the error
<pre>@Implements(android.graphics.Outline.class)
public class OutlineShadow {

    @RealObject
    private android.graphics.Outline outline;

    public Path mPath;

    /** @hide */
    public Rect mRect;
    /** @hide */
    public float mRadius;
    /** @hide */
    public float mAlpha;

    /**
     * Sets the Constructs an Outline from a {@link android.graphics.Path#isConvex() convex path}.
     */
    @Implementation
    public void setConvexPath(Path convexPath) {
        if (mPath == null) mPath = new Path();
        mRect = null;
        mRadius = -1.0f;
        mPath.set(convexPath);
    }
}</pre>



Add this before your test
<pre>@RunWith(CustomRobolectricRunner.class)
@Config(constants = BuildConfig.class, shadows = OutlineShadow.class, sdk = 21)
public class YourTest {
}</pre>
