### ISSUE TITLE
java.lang.NullPointerException at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:295)

### ISSUE THREAD

**Issue by rockerhieu** [robolectric/robolectric#1826]
This issue happen randomly when running with Robolectric 3.0-RC2:

```
java.lang.NullPointerException
  at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:295)
  at java.util.ComparableTimSort.sort(ComparableTimSort.java:171)
  at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
  at java.util.Arrays.sort(Arrays.java:472)
  at java.util.Collections.sort(Collections.java:155)
  at org.robolectric.res.ResBunch.put(ResBunch.java:34)
  at org.robolectric.res.ValueResourceLoader.processNode(ValueResourceLoader.java:36)
  at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
  at org.robolectric.res.ValueResourceLoader.processResourceXml(ValueResourceLoader.java:19)
  at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:50)
  at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:47)
  at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:40)
  at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:30)
  at org.robolectric.res.PackageResourceLoader.loadEverything(PackageResourceLoader.java:32)
  at org.robolectric.res.PackageResourceLoader.doInitialize(PackageResourceLoader.java:19)
  at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
  at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
  at org.robolectric.res.PackageResourceLoader.getValue(PackageResourceLoader.java:5)
  at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
  at org.robolectric.shadows.ShadowAssetManager.resolveStyle(ShadowAssetManager.java:324)
  at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:267)
  at org.robolectric.shadows.ShadowResources$ShadowTheme.applyStyle(ShadowResources.java:465)
  at android.content.res.Resources$Theme.applyStyle(Resources.java)
  at android.app.ContextImpl.getTheme(ContextImpl.java:838)
  at android.content.ContextWrapper.getTheme(ContextWrapper.java:121)
  at android.content.Context.obtainStyledAttributes(Context.java:460)
  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
  at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
  at com.company.app.adapter.PhoneBookUserListAdapter.newView(PhoneBookUserListAdapter.java:87)
  at com.company.app.adapter.PhoneBookUserListAdapter.getView(PhoneBookUserListAdapter.java:97)
  at com.company.app.adapter.PhoneBookAdapterTest.testGetView(PhoneBookAdapterTest.java:53)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:235)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
  at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
  at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
  at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
  at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

Here is the configuration:

``` groovy
robolectric {
  include '**/*Test.class'
  exclude '**/espresso/**/*.class'

  maxHeapSize "3g"

  // configure the test JVM arguments
  jvmArgs '-XX:MaxPermSize=1024M', '-XX:-UseSplitVerifier'

  //  Specify max number of processes (default is 1)
  maxParallelForks = 1

  // Specify max number of test classes to execute in a test process
  // before restarting the process (default is unlimited)
  // forkEvery = 150

  // configure whether failing tests should fail the build
  ignoreFailures false

  // use afterTest to listen to the test execution results
  afterTest { descriptor, result ->
    println "Executing test for ${descriptor.name} with result: ${result.resultType}"
  }
}
```

**Comment by emakovsky** [comment]
The same issue in rc3

**Comment by pdegand** [comment]
:+1:

I have it every time with RC3

**Comment by ujikol** [comment]
Seem to have encountered the same issue with 3.0 release.

There is just an additional frame in the stack trace:
...
	at java.util.Collections.sort(Collections.java:155)
	at org.robolectric.res.ResBundle.put(ResBundle.java:32)
	at org.robolectric.res.ResBunch.put(ResBunch.java:12)
...

**Comment by shafty023** [comment]
I have having this same issue with 3.0 release. Any fix???

**Comment by shafty023** [comment]
This essentially blocks my ability to do any unit tests that require setting up an Activity. Is there anything we can help with debug-wise?

**Comment by kingargyle** [comment]
This seems to happen when a .withIntent() method is called when building the activity.  taking this out allows this to get buy without getting the exception.

**Comment by shafty023** [comment]
I didn't use .withIntent() and I am running into this issue.

    @Before
    public void setup() {
        try {
            RoboInstrumentation.newApplication(TestApplication.class, RuntimeEnvironment.application);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        mProvider = new TestProvider();
        mProvider.onCreate();
        ShadowContentResolver.registerProvider("com.test.provider", mProvider);
        mContext = Robolectric.setupActivity(MockActivity.class);
        mContentResolver = mContext.getContentResolver();
    }

And here is the MockActivity

    package com.test.activity;

    import android.app.Activity;

    public class MockActivity extends Activity {
        
    }

As you can see there is nothing in there. I have also tried full Activity implementations that extend Activity and ones that extend AppCompatActivity. Nothing is working and all throw the same exception 75% of the time.

**Comment by kingargyle** [comment]
I was mistaken on the withIntent, our issues started happening after we added Google Play Services and Google Analytics v4 to the app.  My current work around is when building the activity and it throws an exception, I try to build it again.

try {
    someActivity = Robolectric.build(......).create().get();
} catch (Exception ex) {
    someActivity = Robolectric.build(......).create().get();
}

This seems to fix it and causes robolectric to reset itself.  It is annoying that it has to be done this way.

**Comment by kingargyle** [comment]
I was finally able to work around this issue and get some consistency in my tests.   If you are using Google Analytics v4 and play services.  You should set the dryRun to true and appOptOut to true.  I still get the Nullpointer exception periodically but it isn't nearly as bad as it was before.

**Comment by jongerrish** [comment]
Robolectric 4.0 and binary resources has vastly improved resource handling. Please give that a try and reopen if its still an issue.
