### ISSUE TITLE
Robolectric setSearchableInfo on SearchView causes NullPointerException

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#1834]
**Originally asked here - closed by mistake:**
https://github.com/robolectric/robolectric/issues/1166

**And same person on StackOverflow:**
http://stackoverflow.com/questions/24332966/menuitemcompat-getactionviewitemid-returns-null-in-robolectric

**This refers back to my issue I posted as a comment here:**
https://github.com/robolectric/robolectric/issues/898#issuecomment-73380798

Now that we do have shadows for this, it is a `NullPointerException`.

**Code:**

    @Override
    public boolean onCreateOptionsMenu(final Menu menu) {
        this.getMenuInflater().inflate(R.menu.menu, menu);

        this.menuItem = menu.findItem(R.id.menu_search);

        final SearchManager searchManager = (SearchManager) this.getSystemService(Context.SEARCH_SERVICE);
        this.searchView = (SearchView) MenuItemCompat.getActionView(this.menuItem);
        this.searchView.setSearchableInfo(searchManager.getSearchableInfo(this.getComponentName())); // <-- NullPointerException
        this.searchView.setQueryHint(this.getString(R.string.search_sounds));
        this.searchView.setOnQueryTextListener(this.onQueryTextListener);
        this.searchView.setOnQueryTextFocusChangeListener(this.onFocusChangeListener);
        MenuItemCompat.setOnActionExpandListener(this.menuItem, this.onActionExpandListener);

        return super.onCreateOptionsMenu(menu);
    }

**Problem:**

    this.searchView.setSearchableInfo(searchManager.getSearchableInfo(this.getComponentName())); // <-- NullPointerException

**Error:**

    <package>.MainActivityTest > test FAILED
    java.lang.NullPointerException
        at <package>.MainActivity.onCreateOptionsMenu(MainActivity.java:266)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2820)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:277)
        at android.support.v7.internal.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:84)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImplBase.java:251)
        at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1089)
        at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1374)
        at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
        at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:131)
        at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
        at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:96)
        at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:246)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:167)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:148)
        at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:111)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:42)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:271)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:311)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:47)
        at org.robolectric.util.ActivityController.visible(ActivityController.java:173)
        at <package>.MainActivityTest.setUp(MainActivityTest.java:37)

**Temporary solution:**
https://github.com/robolectric/robolectric/issues/898#issuecomment-76224410

**Comment by jaredsburrows** [comment]
I was using Robolectric 3.0-rc2, this is no longer an issue in Robolectric 3.0-rc3.

@hidroh @gauravsak @sancho21

**Comment by hidroh** [comment]
Yes look like the issue is gone.
