### ISSUE TITLE
PowerMock fails with API 21, works in 18 and 19

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#1855]
Please read here: https://github.com/robolectric/robolectric/issues/1058#issuecomment-107236341.

It seems only not work with API 21. I have tested with APIs 18 and 19.

Thanks to, @WonderCsabo, In order to use `PowerMock + EasyMock` with `Robolectric`, you must do the following:

**Annotate your test:**

    @RunWith(RobolectricGradleTestRunner.class)
    @PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*" })
    @PrepareForTest({...)

**Use the `PowerMock` rule:**

    @Rule
    public PowerMockRule rule = new PowerMockRule();

**This works great with 18:**

    @Config(constants = BuildConfig.class, sdk = 18)

**But fails with 21:**

   @Config(constants = BuildConfig.class, sdk = 21)

**Error:**

    burrows.apps.math.data.DataFetcherTest > testGetEquationsNullData FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetVersionNullData FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetVersion FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

    burrows.apps.math.data.DataFetcherTest > testGetEquations FAILED
        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V

**Exception:**

        java.lang.NoSuchMethodError: java.lang.System.arraycopy([II[III)V
	at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1145)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
	at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at com.thoughtworks.xstream.io.xml.XppReader.pullNextEvent(XppReader.java:109)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.hasMoreChildren(AbstractPullReader.java:87)
	at com.thoughtworks.xstream.io.ReaderWrapper.hasMoreChildren(ReaderWrapper.java:32)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1052)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1036)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:912)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:903)
	at org.powermock.classloading.DeepCloner.clone(DeepCloner.java:54)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:89)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by WonderCsabo** [comment]
The problem is here that in API 21, the `KXmlParser` class uses an internal version of `System.arraycopy`, which is available in the android.jar, but not in the desktop Java. That is why that special method cannot be found. 

To make that work, you have to load the [standard version](http://mvnrepository.com/artifact/net.sf.kxml/kxml2/2.3.0) of `kxml` on the classpath, instead of the Android one. This is not easy but doable, however it could break other things which are expected from the Android implementation.

**Comment by eduplus** [comment]
I have the same experience and have been using sdk 19 because of this. It would be great to get it working on sdk 21.

**Comment by WonderCsabo** [comment]
Guys, do not expect the Robolectric team to fix this issue. PowerMock was never supported. I clearly commented what is the error. Lucky for you, i found a workaround: instead of using KXML which is modified in Android, depend on another XML parser implementation (XPP3).

Make sure to have these deps additional to the standard Robolectric + PowerMock deps:
```groovy
testCompile 'org.ogce:xpp3:1.1.6'
testCompile 'com.thoughtworks.xstream:xstream:1.4.2'
// testCompile "org.powermock:powermock-classloading-xstream:1.6.2" // remove this dep
```

Create the following class:
```java
package org.powermock.classloading;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.Xpp3Driver;

import org.powermock.classloading.spi.DeepClonerSPI;

public class DeepCloner implements DeepClonerSPI {
    private final XStream xStream;

    public DeepCloner(ClassLoader classLoader) {
        xStream = new XStream(null, null, new Xpp3Driver());
        xStream.omitField(ClassloaderExecutor.class, "classloader");
        xStream.setClassLoader(classLoader);
    }

    public <T> T clone(T objectToClone) {
        final String serialized = xStream.toXML(objectToClone);
        return (T) xStream.fromXML(serialized);
    }
}
```

And that's it. Now you can run the tests even with SDK 21.

**Comment by eduplus** [comment]
That workaround seems to fix the issue and we are now able to run with sdk = 21, thanks.

**Comment by erd** [comment]
Thanks @WonderCsabo! I've created a wiki page that documents your workaround here:

https://github.com/robolectric/robolectric/wiki/Using-Power-Mock

**Comment by WonderCsabo** [comment]
@erd i think we should add the "standard Robolectric + PowerMock deps" as well to that page, don't you think? Because those deps and usage with Robolectric is [not trivial](https://github.com/WonderCsabo/deckard-gradle/commit/d94d3399d0e4a483b7277f652f0bf5a8a12d3e41).

**Comment by jaredsburrows** [comment]
Sounds good. Im glad this got resolved.

**Comment by WonderCsabo** [comment]
@erd by the way, if anybody uses the xml pull parser with sdk 21, it will fail... I am not sure how you want to handle that.

**Comment by erd** [comment]
@WonderCsabo Feel free to edit that wiki page as much as necessary. I've never used PowerMock, so I was just going on your earlier comments.

**Comment by WonderCsabo** [comment]
@erd i updated the wiki page.

**Comment by WonderCsabo** [comment]
@erd i verified that #1905 indeed resolved this problems, so the workaround written here is no longer needed! Should we update the wiki?

**Comment by jaredsburrows** [comment]
@WonderCsabo Does Jacoco Test Reports work as well?

**Comment by WonderCsabo** [comment]
@jaredsburrows i never used JaCoco. Why do you think that is related?

**Comment by jaredsburrows** [comment]
@WonderCsabo It has been a while but when I first start this Gradle + Powermock issue by asking you about your example setup here: https://github.com/robolectric/robolectric/issues/1058#issuecomment-107236341.

I originally had 2 issues, getting Robolectric + PowerMock to work an then when I did get it to work, Jacoco Test Reports no longer worked with PowerMock. I believe something has changed in PowerMock.

So I posted my example and then we created this issue, which lead to the wiki being created which lead you to make this https://github.com/robolectric/robolectric/pull/1905 pull request.

**Comment by WonderCsabo** [comment]
@jaredsburrows i see, so PowerMock instrumentation killed the JaCoCo instrumentation, this is a known problem. I do not think that is related to Robolectric, try it in a pure Java project first.

**Comment by jaredsburrows** [comment]
@WonderCsabo Thanks for your fast replies!

**Comment by erd** [comment]
> Should we update the wiki?

Sure. Go for it.

**Comment by WonderCsabo** [comment]
Done, [here](https://github.com/robolectric/robolectric/wiki/Using-PowerMock).

**Comment by acherkashyn** [comment]
@WonderCsabo Is there a build/version that includes this fix?

**Comment by WonderCsabo** [comment]
Yeah, the CI automatically [deploys](https://github.com/robolectric/robolectric/blob/master/.travis.yml#L22) a snapshot after each commit to the `master` branch. They can be found in the Sonatype OSS snapshots [repository](https://oss.sonatype.org/content/repositories/snapshots) with version `3.0-SNAPSHOT`.

**Comment by acherkashyn** [comment]
Got it, thanks! Do you have a plan to create another 3.0-rc build sometime soon? I'll be using a snapshot for now, but it would be ideal to have a specific version to ensure consistent results.

**Comment by WonderCsabo** [comment]
@acherkashyn i am not a Robolectric developer. You should ask @erd for such things.

**Comment by erd** [comment]
Please don't use github issues to ask for updates. It makes it harder to read the issues and sort out the actual problem that needs to be solved (and I will either ignore the question or delete the post). Please follow up on the mailing list if you want information about the release.

**Comment by jaredsburrows** [comment]
@acherkashyn If you or anyone on this thread does not know already, please see: https://groups.google.com/forum/#!forum/robolectric.

**Comment by acherkashyn** [comment]
@jaredsburrows Already posted there, sorry for posting this question in inappropriate place originally.
