### ISSUE TITLE
Robolectric does not parse activity meta-data tag in manifest

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#1860]
Robolectric version: 2.4
Android minimum/target SDK version: 19

In my manifest I have this entry:

        <activity
                android:name=".FooActivity"
                android:parentActivityName=".FooParentActivity"
                android:label="@string/app_name"
                android:screenOrientation="portrait">
            <meta-data
                    android:name="android.support.PARENT_ACTIVITY"
                    android:value=".FooParentActivity"/>
        </activity>

Source code:

public class FooActivity {
...

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            NavUtils.navigateUpFromSameTask(this);
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}

Test code:

@Config(emulateSdk = 18, reportSdk = 18, manifest = "./src/main/AndroidManifest.xml")
@RunWith(RobolectricTestRunner.class)
public class FooActivityTest {

    @Test
    public void OnOptionsItemSelected_WithHomeItem_StartFooParentActivity() throws Exception {
        FooActivity activity = Robolectric.buildActivity(FooActivity.class).create().get();
        ShadowApplication shadowApplication = shadowOf(activity.getApplication());
        assumeThat(shadowApplication.peekNextStartedActivity(), nullValue());
        MenuItem item = new TestMenuItem(android.R.id.home);

        activity.onOptionsItemSelected(item);

        assertThat(shadowApplication.peekNextStartedActivity(), notNullValue());
        assertThat(shadowApplication.peekNextStartedActivity().getComponent().getClassName(), is(FooParentActivity.class.getSimpleName()));
    }
}

Result: 

java.lang.IllegalArgumentException: Activity FooActivity does not have a parent activity name specified. (Did you forget to add the android.support.PARENT_ACTIVITY <meta-data>  element in your manifest?)
	at android.support.v4.app.NavUtils.navigateUpFromSameTask(NavUtils.java:177)
	at com.example.FooActivity.onOptionsItemSelected(FooActivity.java:75)
	at com.example.FooActivityTest.OnOptionsItemSelected_WithHomeItem_StartFooParentActivity(FooActivityTest.java:60)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by erd** [comment]
Please see issue #1399.
