### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/net/ssl/DistinguishedNameParser

### ISSUE THREAD

**Issue by maksim88** [robolectric/robolectric#1864]
```
javax/net/ssl/DistinguishedNameParser
java.lang.NoClassDefFoundError: javax/net/ssl/DistinguishedNameParser
	at org.apache.http.conn.ssl.AbstractVerifier.getCNs(AbstractVerifier.java:205)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:112)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:95)
	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
	at org.robolectric.tester.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:419)
	at org.robolectric.shadows.ShadowDefaultRequestDirector.execute(ShadowDefaultRequestDirector.java:171)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
[...]

Caused by: java.lang.ClassNotFoundException: javax.net.ssl.DistinguishedNameParser
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.robolectric.internal.bytecode.InstrumentingClassLoader.loadClass(InstrumentingClassLoader.java:97)
	at org.apache.http.conn.ssl.AbstractVerifier.$$robo$$getCNs(AbstractVerifier.java:205)
	at org.apache.http.conn.ssl.AbstractVerifier.getCNs(AbstractVerifier.java)
	at org.apache.http.conn.ssl.AbstractVerifier.$$robo$$verify(AbstractVerifier.java:112)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java)
	at org.apache.http.conn.ssl.AbstractVerifier.$$robo$$verify(AbstractVerifier.java:95)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java)
	at org.apache.http.conn.ssl.SSLSocketFactory.$$robo$$createSocket(SSLSocketFactory.java:388)
	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.$$robo$$openConnection(DefaultClientConnectionOperator.java:165)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java)
	at org.apache.http.impl.conn.AbstractPoolEntry.$$robo$$open(AbstractPoolEntry.java:164)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.$$robo$$open(AbstractPooledConnAdapter.java:119)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java)
	at org.robolectric.tester.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:419)
	at org.robolectric.shadows.ShadowDefaultRequestDirector.execute(ShadowDefaultRequestDirector.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
	at org.apache.http.impl.client.AbstractHttpClient.$$robo$$execute(AbstractHttpClient.java:555)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java)
	at org.apache.http.impl.client.AbstractHttpClient.$$robo$$execute(AbstractHttpClient.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java)
[...]
```

Is a shadow to DistinguishedNameParser missing?

I am getting this error when using a HttpClient  with SSL.
(It only happens if testing agains API Level 21, API level 19 passes.)

Best

**Comment by erd** [comment]
> Is a shadow to DistinguishedNameParser missing?

No, it looks like `javax.net.ssl.DistinguishedNameParser` is not available in our android-all jar. We might have forgot to include a particular class, or it was added to the JDK in apache harmony.

**Comment by laminina** [comment]
I noticed also, that the android jar doesn't have the GL.class inside javax/microedition/khronos/opengles the last package is empty when taking a look at some of the android version for JellyBean, lollipop.

I'm getting same NoClassDefFoundError when running some unit tests. 
Should I create a separate Jira for this?

**Comment by erd** [comment]
> Should I create a separate Jira for this?

Yes, please. We have a whitelist of modules to include from AOSP that may not include OpenGL. Keep in mind that even if we do include those methods, any call into a GL class will most likely throw an error since the implementation will not work on a desktop (and I don't think we should attempt to shadow it).

**Comment by pdegand** [comment]
Any workaround for this one ?

**Comment by laminina** [comment]
Create and empy class GL with the same package and done!

**Comment by ecgreb** [comment]
@laminina that did the trick. Thanks for the tip.

**Comment by rsingh31** [comment]
@erd any workkaround for javax/net/ssl/DistinguishedNameParser error

**Comment by erd** [comment]
Don't use httpclient?

**Comment by jarrodmoldrich** [comment]
I've been using Robolectric for integration testing.  It's not it's primary function, I know, but it's worked well so far, until I tried testing with Firebase.  Internally it is using httpclient, which I can't change: http://mvnrepository.com/artifact/com.firebase/firebase-client-jvm/2.3.1

I googled around and found the source code for DistinguishedNameParser at: http://grepcode.com/file_/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-1/javax/net/ssl/DistinguishedNameParser.java

I pasted this file directly into the project and now it works fine.

**Comment by erd** [comment]
@jarrodmoldrich Interestingly enough, that link is to Robolectric's 5.0 android source.

**Comment by jarrodmoldrich** [comment]
@erd Ha!  Shows how much I was paying attention.  Adding the file does remove the exceptions I was seeing.

**Comment by erd** [comment]
I suspect that the OP was using an API version where we forgot to include the `DistinguishedNameParser` class in our android-all jar. It does look like it's included in 5.0.0_r2, so I suspect it will be included in all future versions of Robolectric. If you run into this issue on older versions, it sounds like you can grab that file from the link above and paste it into your test sources.

**Comment by ngbravo** [comment]
The reason this is failing is because we're attempting to load DistinguishedNameParser from the system class path, and it is not included in the JDK. The JDK includes a bunch of javax.net.ssl classes, but not this one. 

The decision whether to load through the InstrumentingClassloader or its parent (the system classpath) is made through the InstrumentationConfiguration and for demonstrated with this small test failing:

  ```
@Test
  public void shouldAcquireDistinguishedNameParser() {
    assertThat(config.shouldAcquire("javax.net.ssl.DistinguishedNameParser")).isTrue();
  }
```

Maybe this raises the question of whether we should revise the strategy for InstrumentationConfiguration.shouldAcquire(), what currently happens:

- Regex test for android/internal/R + android/R/stylable for explicit inclusion (included in android-all)
- Explicit exclusions for javax.* which causes this bug.
- Explicit exclusion for java.* which causes us to load the JVM version of say java.util.LinkedList rather than the version shipped in the android-all.jar

Is there any reason not to refactor to a strategy where by we always load a class if it is present in the android-all jar?

**Comment by erd** [comment]
> Is there any reason not to refactor to a strategy where by we always load a class if it is present in the android-all jar?

At the very least, you'd have to explicitly exclude classes in `java.lang` since those can only be loaded by the system class loader. As for the others, I can't think of a reason why you couldn't load most classes from the android-all jar. I suggest running the change through a real set of tests and see what happens.

**Comment by jongerrish** [comment]
boolean InstrumentationConfiguration.shouldAcquire(String name)

determines if the InstrumentatingClassloader should load a given class, further elaborating the logic described by Niko above:-

* DO load Test classes from org.robolectric.res + org.robolectric.manifest (No idea why these should be loaded by the InstrumentingClassloader)
* DO load android/internal/R/* classes (Makes sense as they're in the android-all jar)
* DO load android/R/stylable (Also makes sense as its in the android-all jar)
* DO NOT load any classes in the set of packagesToNotAquire 
* DO NOT load any classes in the set of classesToNotAquire
* DO NOT load any other *.R.* classes (Makes sense as they are probably user's R files.

// Doesn't always make sense... e.g: Hamcrest isn't going to be found in the jars we load in instrumenting classloader, but java, javax etc does get included in the android-all jar and we should probably use those versions rather than loading them from the system class path, i.e: the local users JDK, since we surely want the android versions which have higher fidelity to what is running on device.
packagesToNotAquire { 
          "java.",
          "javax.",
          "sun.",
          "com.sun.",
          "org.w3c.",
          "org.xml.",
          "org.junit",
          "org.hamcrest",
          "org.specs2",  // allows for android projects with mixed scala\java tests to be
          "scala.",      //  run with Maven Surefire (see the RoboSpecs project on github)
          "kotlin.",
          "com.almworks.sqlite4java" // Fix #958: SQLite native library must be loaded once.
}

// Makes sense not to acquire these since they're not going to be found in any of the jars we load acquired classes from:
      classesToNotAquire.addAll(stringify(
          TestLifecycle.class,
          ShadowWrangler.class,
          AndroidManifest.class,
          android.R.class,
          InstrumentingClassLoader.class,
          SdkEnvironment.class,
          SdkConfig.class,
          RobolectricTestRunner.class,
          RobolectricTestRunner.HelperTestRunner.class,
          ResourcePath.class,
          ResourceLoader.class,
          XmlBlock.class,
          ClassHandler.class,
          ClassHandler.Plan.class,
          ShadowInvalidator.class,
          RealObject.class,
          Implements.class,
          Implementation.class,
          Instrument.class,
          DoNotInstrument.class,
          Config.class,
          Transcript.class,
          DirectObjectMarker.class,
          DependencyJar.class,
          ParallelUniverseInterface.class,
          ShadowedObject.class,
          TempDirectory.class
      ));

android-all, shadows-core, json, tagsoup seem to be the jars where code can be directly loaded by the instrumenting classloader.

**Comment by jongerrish** [comment]
@erd - sounds good, we'll play with this tomorrow.

**Comment by karlicoss** [comment]
Related: https://github.com/robolectric/robolectric/issues/1932
