### ISSUE TITLE
org.robolectric.shadows.ShadowResourcesTest fails pre-21

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#1869]
It fails because the test makes assumptions about the wideness of the id type. Is there anything we can do about this?

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at org.robolectric.shadows.ShadowResourcesTest.getInternalId(ShadowResourcesTest.java:528)
    at org.robolectric.shadows.ShadowResourcesTest.getThemeValueShouldSupportDereferenceResource(ShadowResourcesTest.java:414)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:24)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by jaredsburrows** [comment]
@jongerrish Are you talking about https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowResourcesTest.java? I use similar tests for all my apps. 

Which was failing for you?

**Comment by jongerrish** [comment]
I switched all of the shadows tests to use the new MultiApiRobolectricTestRunner which runs tests once each against a set of sdk = { x, y, z } - this protects us when we support as new API version that we don't break the shadows functionality on previous versions of the api (to support 21, a some of the shadows broke on 18 my mistake}

I created a bunch of bugs to track tests that failed for shadows on lower api levels, some of these are broken, but some, like this test I think its just a case of being incompatible (long vs int as the native pointer in this case) you can see the failures yourself if you remove @Config(sdk = {
    Build.VERSION_CODES.LOLLIPOP }) so it will run against all api versions.

I think a better thing to do would be to have the tests run against each actual version of the shadows jar somehow. I think @erd told me this was tricky right now because of a limitation in maven but not sure.

**Comment by jaredsburrows** [comment]
Ah, nice `MultiApiRobolectricTestRunner` is being worked on! I did not notice the `3.1` label.

**Comment by xian** [comment]
Fixed a while ago.
