### ISSUE TITLE
Endless running test with spinner and complex layout since update rc2 to rc3

### ISSUE THREAD

**Issue by nenick** [robolectric/robolectric#1877]
I have layout with a spinner which is filled by a BaseAdapter implementation.

When I use a list item layout which has only one view component (TextView or RelativeLayout or ...) all works fine. 

```
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@android:id/text1"
        android:singleLine="true"
        android:layout_width="match_parent"
        android:layout_height="15dp"/>
```

When I use a layout with more than one view component then the run will never end.

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_height="wrap_content"
    android:layout_width="match_parent">

    <TextView xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@android:id/text1"
        android:singleLine="true"
        android:layout_width="match_parent"
        android:layout_height="15dp"/>

</LinearLayout>
```

With robolectric 3.0rc2 this tests works fine. Do you have an idea what happened?

**Comment by erd** [comment]
I can't think of anything that would have affected `BaseAdapter`. Do you have any idea where the test is spending it's time. Can you run it with the debugger and force a thread dump?

**Comment by nenick** [comment]
I don't think that this issue comes from base adapter. It could be the same base issue which I reported at https://github.com/robolectric/robolectric/issues/1587 because again it looks like endless requeuing task. 

```
"main" #1 prio=5 os_prio=0 tid=0x00000000029c6000 nid=0x1c6c runnable [0x00000000029b8000]
   java.lang.Thread.State: RUNNABLE
	at org.robolectric.util.Scheduler.post(Scheduler.java:72)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.shadows.ShadowView.post(ShadowView.java:406)
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at android.view.View.post(View.java)
	at android.widget.AdapterView$SelectionNotifier.$$robo$$run(AdapterView.java:862)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:269)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:179)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:143)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:243)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:85)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.post(Scheduler.java:72)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.shadows.ShadowView.post(ShadowView.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at android.view.View.post(View.java)
	at android.widget.AdapterView.$$robo$$selectionChanged(AdapterView.java:882)
	at android.widget.AdapterView.selectionChanged(AdapterView.java)
	at android.widget.AdapterView.$$robo$$checkSelectionChanged(AdapterView.java:1047)
	at android.widget.AdapterView.checkSelectionChanged(AdapterView.java)
	at android.widget.Spinner.$$robo$$layout(Spinner.java:586)
	at android.widget.Spinner.layout(Spinner.java)
	at android.widget.Spinner.$$robo$$onLayout(Spinner.java:527)
	at android.widget.Spinner.onLayout(Spinner.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.RelativeLayout.$$robo$$onLayout(RelativeLayout.java:1076)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.widget.ScrollView.$$robo$$onLayout(ScrollView.java:1502)
	at android.widget.ScrollView.onLayout(ScrollView.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.RelativeLayout.$$robo$$onLayout(RelativeLayout.java:1076)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.$$robo$$onLayout(ActionBarOverlayLayout.java:502)
	at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.LinearLayout.$$robo$$setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java)
	at android.widget.LinearLayout.$$robo$$layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java)
	at android.widget.LinearLayout.$$robo$$onLayout(LinearLayout.java:1466)
	at android.widget.LinearLayout.onLayout(LinearLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.widget.FrameLayout.$$robo$$layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java)
	at android.widget.FrameLayout.$$robo$$onLayout(FrameLayout.java:508)
	at android.widget.FrameLayout.onLayout(FrameLayout.java)
	at android.view.View.$$robo$$layout(View.java:15596)
	at android.view.View.layout(View.java)
	at android.view.ViewGroup.$$robo$$layout(ViewGroup.java:4966)
	at android.view.ViewGroup.layout(ViewGroup.java)
	at android.view.ViewRootImpl.$$robo$$performLayout(ViewRootImpl.java:2072)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java)
	at android.view.ViewRootImpl.$$robo$$performTraversals(ViewRootImpl.java:1829)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
	at android.view.ViewRootImpl.$$robo$$doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
	at android.view.ViewRootImpl$TraversalRunnable.$$robo$$run(ViewRootImpl.java:5779)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
	at android.os.Handler.$$robo$$handleCallback(Handler.java:739)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$dispatchMessage(Handler.java:95)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:29)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
	- locked <0x00000006c2772cf8> (a android.os.MessageQueue)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:269)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:179)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:123)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:54)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:267)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:307)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.visible(ActivityController.java:173)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
	at de.nenick.robolectricpages.RoboBasePage.startPage(RoboBasePage.java:21)
	at de.nenick.robolectric.RoboSupPage.startPage(RoboSupPage.java:19)
	at de.nenick.quacc.accounting.create.CreateAccountingFragmentSpec.shouldShowValueFromDatePicker(CreateAccountingFragmentSpec.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Variation of the thread dump
```
"main" #1 prio=5 os_prio=0 tid=0x00000000029c6000 nid=0x1c6c runnable [0x00000000029b8000]
   java.lang.Thread.State: RUNNABLE
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:173)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:143)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:243)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:85)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.util.Scheduler.post(Scheduler.java:72)
	- locked <0x00000006c2772cc0> (a org.robolectric.util.Scheduler)
	at org.robolectric.shadows.ShadowView.post(ShadowView.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at android.view.View.post(View.java)
```

**Comment by nenick** [comment]
The getView method from BaseAdapter is only called once with a complex layout. With a simple layout it get called for each item.

**Comment by nenick** [comment]
After testing some revision I found that the endless run start with https://github.com/robolectric/robolectric/commit/bd4f0499f89d473422087e6fd7f19acddea175bd

**Comment by nenick** [comment]
There was a merge. The commit https://github.com/robolectric/robolectric/commit/badb38566a181451ade9b478c98247986d0a5340 force this behavior

**Comment by kriegfrj** [comment]
I haven't been looking specifically into this issue, but when I saw it pop up it was the last straw which prompted me to raise #1879 as I had seen similar issues pop up that all seemed to come down to scheduling. The problem seems to be that it is trying to animate the initial selection of the Spinner's value, and there are problems with animations not completing as they should.

Possible fixes for your particular case:

1. Try changing the implementation of `Scheduler.unPause()` so that instead of `advanceToLastPostedRunnable()` it calls `advanceBy(0)`. I would be interested in hearing if this works - it might fix this problem but it might also break other tests that have come to rely on the incorrect behaviour, which is why I have not yet submitted a PR for it.
2. Not so much a fix as a workaround: pause the foreground scheduler before you try and inflate your layout. Ideally you shouldn't have to do this (this is what #1879 will aim to fix, but that will obviously take some time).

**Comment by kriegfrj** [comment]
Thanks for the feedback on #1891, @nenick. I'm sorry that it didn't fix this problem for you - your problem must be related to one of the other scheduling issues that I identified that affect animations (eg, the fact that the nano clock is different to the millis clock). I'm really sorry but you're going to have to wait a while for the fix - in the meantime, pausing the scheduler before inflating the view should help you get your test working.

Also, what will also help me in looking into this problem in more detail is if you could come up with a minimal test case to reproduce the issue that I can then use in my own testing. If you are in a position to do this it might help me to get things moving more quickly.

**Comment by nenick** [comment]
I have created a projet example which shows the issue. https://github.com/nenick/RobolectricEndless

This behaviour is a combination of "when get the adapter his values" and "someone is listening at item selection"

By writing this example I found a solution for me in changing the execution order of the MainActivityFragment onAfterViews method content. See the comments inside MainActivityFragment class.

**Comment by olivierg13** [comment]
Hello everyone,

We have a pretty big project where we ended up encountering this issue.

I forked @nenick Github project, updated it to one of the latest versions of Gradle (3.1) and Robolectric (4.1). It seems that it's still happening: https://github.com/olivierg13/RobolectricEndless

Could this issue be reopened and re-prioritized?

For anyone reading this and being miserable, a (dirty) workaround on latest Robolectric is:
`
val scheduler = shadowOf(Looper.getMainLooper()).scheduler
scheduler.pause()
[... Setup Activity using Robolectric, ActivityTestRule or ActivityScenario ...]
scheduler.unPause()
`

Thank you in advance.

Cheers,

Olivier

**Comment by jason1peng** [comment]
I'm having the same problem. My project is using Robolectric 4.3.
I can't use `@LooperMode(PAUSED)` because my test's base class is using ` Robolectric.flushBackgroundThreadScheduler();` which is not supported in PAUSE mode.

Pause and unpause looper can't solve my problem. 

But this could work
```
ShadowLooper.idleMainLooperConstantly(true);
```

**Comment by jongerrish** [comment]
What happens if you use paused mode and remove

Robolectric.flushBackgroundThreadScheduler();

You really don't want to use idleConstantly() either, these modes are
really broken, you're better off migrating to paused mode.

**Comment by jason1peng** [comment]
@jongerrish Agreed, especially `idleConstantly` already marked as deprecated. 

By removing Robolectric.flushBackgroundThreadScheduler(); & Robolectric.flushForegroundThreadScheduler();  test will pass.
