### ISSUE TITLE
ShadowSQLiteConnection$Connections.execute fails while testing sqlite operations in different test case

### ISSUE THREAD

**Issue by rsingh31** [robolectric/robolectric#1890]
java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 37. Current pointers for thread Thread[pool-1-thread-1,5,main] []
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:460)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:373)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:64)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)

**Comment by kriegfrj** [comment]
SQLiteDatabases are automatically cleaned up after every test (see #1510, #1763).

Perhaps we need a mechanism to keep them open between tests. This might be useful for cases where you need to set up a complex read-only database for use in many tests, as it might be inefficient to set it up several times.

**Comment by nenick** [comment]
@rsingh31 Most time the issue is that the own SQLiteOpenHelper is a singleton. Between tests all instances should be resettet or you will get strange side effects like this. For me it works to set the static variable null per reflection. Here an example

```
    @After
    public void finishComponentTesting() {
        // sInstance is the static variable name which holds the singleton instance
        resetSingleton(MySQLiteOpenHelper.class, "sInstance");
    }

    private void resetSingleton(Class clazz, String fieldName) {
        Field instance;
        try {
            instance = clazz.getDeclaredField(fieldName);
            instance.setAccessible(true);
            instance.set(null, null);
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }
```

**Comment by rsingh31** [comment]
@nenick,@kriegfrj Thanks for your reply , I'm using greenadao Sqlitedatabase for database management which does automatically manages connection and disconnection.

**Comment by rsingh31** [comment]
@kriegfrj @nenick  I have added demo project using greendao , which produces the same failure as above on running test cases . 
https://github.com/rsingh31/Robolectric-test-demo

**Comment by rsingh31** [comment]
@erd Can you please have a look in this issue.

**Comment by mickele** [comment]
Any news regarding this issue? I'm having the same problem but using DBFlow instead.

**Comment by kriegfrj** [comment]
I personally don't have the time to look at this at the moment.

How to handle this is more of a design issue. Robolectric testing has been designed on the assumption that no state is preserved between tests & you're always starting from scratch. Singletons & other static state maintained by your application and/or test can break that assumption. I guess there are two ways we can handle it:

* Insist that users of Robolectric reset static state in their own applications between tests (including any database singleton helpers). That is the solution that @nenick gave above.
* Be more flexible in allowing some state to be preserved between tests/less aggressive in clearing up static state between tests. Perhaps we could make it configurable at test runtime whether or not databases should be automatically closed, or perhaps we could be smart and do something like store the static state in weak references, which might allow it to be automatically cleaned up when required and conversely automatically retained if something is holding a static reference to them.

While I'm not working on this directly I have a similar question to deal with regarding threading and scheduling & preserving/resetting the associated static state; hopefully I can apply the same lessons to the DB cleanup code too.

**Comment by rsingh31** [comment]
sorry for no update ,@mickele  i resolved issue last week , actually m having static variables (greendao session object ) which needs to be set to null  after every test case , which can be done applying @nenick solution above.

**Comment by mickele** [comment]
Thanks for the answer guys. The mais reason I was trying out Robolectric was to speed up the tests and I thought I could save some ms re-using the connection between the tests, thanks for the clarification @kriegfrj.

I also tried @nenick suggestion before with no luck but after a night of sleep and some code digging I've managed to find who was holding the instances on DBFlow's side, if anyone ever need it:

```
@After
public void tearDown() throws Exception {
    Field field = FlowManager.class.getDeclaredField("mDatabaseHolder");
    field.setAccessible(true);
    field.set(null, null);
}
```

**Comment by StefMa** [comment]
@rsingh31 I'm using greendao too, but your solution comment dosn't help me.
Maybe you have some source code for me? :+1: :)

**Comment by rsingh31** [comment]
@StefMa if you are getting same error as i posted , then you need to set greendao session (which you get after calling newSession() method)object variable to null after every test case using solution above.
if you don't get it to work i will share  sample working demo!!!!!

**Comment by StefMa** [comment]
Yes, a demo would be great.
Here is some code of mine:
ApplicationSubClass:
```
    private DaoSession daoSession;

    public DaoSession getDaoSession() {
        if (this.daoSession == null) {
            MyOpenHelper helper = new MyOpenHelper(this, "my-db", null);
            DaoMaster daoMaster = new DaoMaster(helper.getWritableDatabase());
            this.daoSession = daoMaster.newSession();
        }
        return this.daoSession;
    }
```

When I say in test
```
    @After
    public void tearDown() throws Exception{
        Field instance;
        instance = ApplicationSubClass.class.getDeclaredField("daoSession");
        instance.setAccessible(true);
        instance.set(null, null);
    }
```
it posts the same error.

When I set the field "daoSession" to static *one* test, don't know why "one", passed. The rest failed again... :(

**Comment by glureau** [comment]
@mickele Thanks, you just saved my week-end!

**Comment by ConorGarry** [comment]
For anyone having this problem specifically with Ollie, there is a slight variation. Worked for me so hopefully helps someone else with the same issue -> [#1882 comment](https://github.com/robolectric/robolectric/issues/1882#issuecomment-120616728)

**Comment by DenisGL** [comment]
@mickele , thanks a lot for your solution.

**Comment by ubuntudroid** [comment]
For the sake of completeness: calling `OpenHelperManager.releaseHelper()` after every test and creating a new `SqliteOpenHelper` after every test via `OpenHelperManager.getHelper(...)` fixes the issue when using **ormlite**.

**Comment by benjosantony** [comment]
For ActiveAndroid , doing the following worked for me.
```
    @Before
    public void setUp() throws Exception {
        ActiveAndroid.initialize(RuntimeEnvironment.application);
    }

    @After
    public void tearDown() throws Exception {
        ActiveAndroid.dispose();
    }
```

**Comment by bayboraoren** [comment]
Everything's fine when I test it in **Android Studio**. But when I try **./gradlew test** Caused by: java.lang.IllegalStateException: Illegal connection pointer 1.....

**Comment by trevjonez** [comment]
For DBFlow 3 you can tear it down with `FlowManager.destroy()`

**Comment by svennu** [comment]
For me it worked if I just make sure to `.close` my DB connections either within the tests or more properly in `@After` annotated method if DB connection is an instance field created in `@Before` method.
