### ISSUE TITLE
IllegalStateException, using app:showAsAction="ifRoom|withText" in Android Library

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#1915]
`Android Library` containing the following in the `menu.xml`:

    <item
    android:id="@+id/menu_share"
    android:menuCategory="container"
    android:orderInCategory="1"
    android:title="@string/menu_share"
    app:actionProviderClass="android.support.v7.widget.ShareActionProvider"
    android:icon="@drawable/ic_share"
    app:showAsAction="ifRoom|withText" />

Then in the `Android App` test itself(using `build.gradle` to use the `Android Library` as a projecy dependency):

    @Test
    public void test_activity_create_start_onresume_visible() {
        MainActivity mainActivity = buildActivity(MainActivity.class).create().start().resume().visible().get();
        assertThat(mainActivity, not(nullValue()));
    }

This test is extremely trivial and just an example. All `Activity` based tests fail when the menu item in the Android Library is `app:showAsAction="ifRoom|withText"` instead of `app:showAsAction="never"`.

    <>.MainActivityLowAPITest > test_activity_create_start_onresume_visible FAILED
        java.lang.IllegalStateException: Observer android.support.v7.internal.widget.ActivityChooserView$1@7d23a5d7 is already registered.
            at android.database.Observable.registerObserver(Observable.java:49)
            at android.support.v7.internal.widget.ActivityChooserView.onAttachedToWindow(ActivityChooserView.java:416)
            at android.view.View.dispatchAttachedToWindow(View.java:11755)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2417)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2424)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1201)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
            at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:29)
            at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
            at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:230)
            at org.robolectric.util.Scheduler.postAtFrontOfQueue(Scheduler.java:98)
            at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:114)
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
            at android.os.Handler.sendMessageAtTime(Handler.java:473)
            at android.os.Handler.sendMessageDelayed(Handler.java:446)
            at android.os.Handler.postDelayed(Handler.java:331)
            at org.robolectric.shadows.ShadowChoreographer.postCallbackDelayed(ShadowChoreographer.java:47)
            at android.view.Choreographer.postCallbackDelayed(Choreographer.java)
            at android.view.Choreographer.postCallback(Choreographer.java:266)
            at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:974)
            at android.view.ViewRootImpl.requestChildFocus(ViewRootImpl.java:2548)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.ViewGroup.requestChildFocus(ViewGroup.java:584)
            at android.view.View.handleFocusGainInternal(View.java:4254)
            at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:558)
            at android.view.View.requestFocusNoSearch(View.java:6478)
            at android.view.View.requestFocus(View.java:6457)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2328)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2329)
            at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2373)
            at android.view.ViewGroup.requestFocus(ViewGroup.java:2332)
            at android.view.View.requestFocus(View.java:6424)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1775)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
            at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:29)
            at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
            at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:269)
            at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:179)
            at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
            at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:123)
            at org.robolectric.util.Scheduler.unPause(Scheduler.java:54)
            at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:267)
            at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:307)
            at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
            at org.robolectric.util.ActivityController.visible(ActivityController.java:173)
            at <>.MainActivityLowAPITest.test_activity_create_start_onresume_visible(MainActivityLowAPITest.java:24)

**Comment by jaredsburrows** [comment]
Using `Robolectric 3.0` + `compile 'com.android.support:design:23.1.1'`, I can no longer reproduce this.
