### ISSUE TITLE
NoSuchMethodException: android.app.Activity.attach(...)

### ISSUE THREAD

**Issue by tomrozb** [robolectric/robolectric#1921]
I'm getting `NoSuchMethodException` when using `@Config(sdk = 21)` with Robolectric 3 RC-3. This issue doesn't occur with SDK = 18. Any solutions for this issue?

```
java.lang.RuntimeException: java.lang.NoSuchMethodException: android.app.Activity.attach(android.content.Context, android.app.ActivityThread, android.app.Instrumentation, android.os.IBinder, int, android.app.Application, android.content.Intent, android.content.pm.ActivityInfo, java.lang.CharSequence, android.app.Activity, java.lang.String, android.app.Activity$NonConfigurationInstances, android.content.res.Configuration)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:205)
    at org.robolectric.internal.runtime.Api19RuntimeAdapter.callActivityAttach(Api19RuntimeAdapter.java:19)
    at org.robolectric.util.ActivityController.attach(ActivityController.java:56)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
```

**Comment by jaredsburrows** [comment]
Please see how to report issues here: https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues.

Can give us any code? How can we reproduce this?

**Comment by erd** [comment]
Are you setting the sdk version anywhere else? Robolectric thinks you are running API 19, and trying to call an older version of `attach`, which doesn't exist.

**Comment by tomrozb** [comment]
No, except the robolectric.properties file, but it's still set to 21.

I've no idea why this happens, that's why I haven't posted any code to reproduce. It's just Activity with Fragment inside, that's it.

**Comment by erd** [comment]
I should be able to reproduce this based on the information you provided.

**Comment by davidkravitz** [comment]
I'm having the same issue.

**Comment by jaredsburrows** [comment]
This is an old issue. @tomrozb Have you upgraded to 3.0 atleast?

**Comment by tomrozb** [comment]
@jaredsburrows yes I've upgraded to 3.0 but haven't seen this because I'm still using SDK 18.

**Comment by jaredsburrows** [comment]
@tomrozb Where is your code? Where is your test? All my apps have `Fragments` with `Activities` inside. I am using Robolectric 3.0, targeting API 21.

What do you mean you are still using API 18? Are you targeting API 18? You should always be targeting the latest API.

**Comment by xian** [comment]
No activity for over a year, please reopen if this is still an issue!
