### ISSUE TITLE
Robolectric 3 RC3 + RG 3 injection doesn't work when running tests via Android Studio

### ISSUE THREAD

**Issue by ahmednasir91** [robolectric/robolectric#1933]
I have updated the tests to Robolectric v3 rc-3 and using Roboguice v3 for DI. The injections work fine when running the tests via Gradle `testDebug` task but when running via Android Studio the injections throws NPE.

I have defined a custom module for injections in the test class, and override the default module using the following:

```
@Before
public void setUp() throws Exception {
    MockitoAnnotations.initMocks(this);

    ShadowLog.stream = System.out;
    Application application = RuntimeEnvironment.application;
    mContext = application;

    ShadowApplication shadowApplication = Shadows.shadowOf(RuntimeEnvironment.application);
    // To avoid null pointer exception when buildActivity is called.
    shadowApplication.declareActionUnbindable("com.google.android.gms.analytics.service.START");

    initMocks();

    Module module = getModule();

    if (module == null) {
        module = defaultModule();
    }

    RoboGuice.overrideApplicationInjector(application, module);
}
```

Following is the stack trace

```
java.lang.NullPointerException
    at com.ca.app.activity.ForgotPinActivity.init(ForgotPinActivity.java:58)
    at com.ca.app.activity.ForgotPinActivity.onCreate(ForgotPinActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:5243)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
    at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:305)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
    at org.robolectric.util.ActivityController.create(ActivityController.java:118)
    at org.robolectric.util.ActivityController.create(ActivityController.java:129)
    at com.ca.app.test.activity.ForgotPinActivityTest.setUp(ForgotPinActivityTest.java:67)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:149)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Any idea, what is the difference between running via gradle task vs Android Studio?

**Comment by erd** [comment]
Have you followed the setup guide (http://robolectric.org/getting-started)? Most notably, the part about setting your working directory to `$MODULE_DIR$`?

**Comment by ahmednasir91** [comment]
Yes I already configured that, check the screenshot below
<img width="747" alt="screen shot 2015-07-10 at 10 59 13 pm" src="https://cloud.githubusercontent.com/assets/1519532/8625309/6f9aa9f0-2757-11e5-9a3a-9f2848d00951.png">

**Comment by ahmednasir91** [comment]
Any reason of why this could be happening? What is the difference in running via command line vs Android Studio?

**Comment by erd** [comment]
There aren't any differences that I'm aware of.
