### ISSUE TITLE
Can't parse @null as a valid color value

### ISSUE THREAD

**Issue by cermakcz** [robolectric/robolectric#1935]
I have a styled button where one of the colors in the selector, let's say `@color/bg_button_disabled` resolves to `@null` (`<color name="bg_button_orange_disabled">@null</color>`). That's a valid value to make it transparent, but Robolectric disagrees and fails when the Activity's layout gets inflated.

I get this exception:

```
Caused by: android.content.res.Resources$NotFoundException: File build/intermediates/res/merged/vanilla/debug/drawable-v21/bg_button_orange.xml from drawable resource ID #0x7f02003b
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2428)
at android.content.res.Resources.loadDrawable(Resources.java:2330)
at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
at org.robolectric.internal.Shadow.directlyOn(Shadow.java:44)
at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:527)
at android.content.res.Resources.loadDrawable(Resources.java)
at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
at android.view.View.__constructor__(View.java:3730)
at android.view.View.<init>(View.java)
at android.widget.TextView.<init>(TextView.java)
at android.widget.Button.<init>(Button.java)
at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java)
at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:97)
at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:782)
at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:810)
at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:180)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
... 99 more
Caused by: java.lang.NumberFormatException: Color value '@null' must start with #
at org.robolectric.shadows.ResourceHelper.getColor(ResourceHelper.java:44)
at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:259)
at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:255)
at org.robolectric.shadows.Converter.convertAndFill(Converter.java:116)
at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
at org.robolectric.shadows.ShadowResources.obtainAttributes(ShadowResources.java:308)
at android.content.res.Resources.obtainAttributes(Resources.java)
at android.graphics.drawable.Drawable.obtainAttributes(Drawable.java:1277)
at android.graphics.drawable.GradientDrawable.inflateChildElements(GradientDrawable.java:1139)
at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:990)
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:185)
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:206)
at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:147)
at android.graphics.drawable.RippleDrawable.inflate(RippleDrawable.java:371)
at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
at android.content.res.Resources.loadDrawableForCookie(Resources.java:2418)
... 116 more
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
