### ISSUE TITLE
Nullpointer exception when running test against Android M

### ISSUE THREAD

**Issue by cooperkong** [robolectric/robolectric#1983]
Hi, this may sounds silly and perhaps won't be valid in the future, but is there a workaround available?
java.lang.NullPointerException
	at org.robolectric.manifest.AndroidManifest.initMetaData(AndroidManifest.java:367)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:398)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:71)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:420)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:223)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:167)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by erd** [comment]
We can't really do any work to support M until it hits AOSP. You can follow #1865 for updates.
