### ISSUE TITLE
NPE when Activity.onBackPressed() after replacing fragment with adding to backstack

### ISSUE THREAD

**Issue by AlexBonel** [robolectric/robolectric#1988]
I try to test proper navigation between fragments in activity through the following code:

```
@Test public void openFragmentClickReaction() {
    MyActivity activity = Robolectric.setupActivity(MyActivity.class);
    activity.findViewById(R.id.open_fragment).performClick();

    assertThat(activity.getCurrentFragment()).isInstanceOf(SecondFragment.class);
    activity.onBackPressed();
    assertThat(activity.getCurrentFragment()).isInstanceOf(FirstFragment.class);
  }
```

but got NPE just after invoked `activity.onBackPressed()` with the following stacktrace:

```
java.lang.NullPointerException
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1055)
    at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1233)
    at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:908)
    at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1551)
    at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:504)
    at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:176)
    at com.alexbonel.app.activity.MyActivityTest.openFragmentClickReaction(MyActivityTest.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)


Process finished with exit code 255
```

While running test with debugger I noticed that every line of code having breakpoint in `FragmentManagerImpl.moveToState()` somehow is invoked twice at the same time. Firstly I thought that there could be some another thread invoking this logic as well, but all of this code is executed on main thread

**Comment by JavierSP1209** [comment]
I have the same NPE, but when doing a simple replace using SupportFragmentManager on SDK=21

```
java.lang.NullPointerException
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
	at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManager.java:1235)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:697)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:130)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:95)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:269)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:179)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:160)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:143)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:243)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:85)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:116)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.sendMessage(Handler.java:507)
	at android.os.Message.sendToTarget(Message.java:416)
	at com.android.internal.app.AlertController$1.onClick(AlertController.java:134)
	at android.view.View.performClick(View.java:4756)
	at com.humana.vitalityapp.integration.ChallengesIntegrationTest.whenAUserIsOnTheChallengeList_andIsEnrolledInAChallengeThatIsInEnrollingPhase_userCanLeaveTeam(ChallengesIntegrationTest.java:412)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by utzcoz** [comment]
Hi @AlexBonel , @JavierSP1209 , this problem is too old with a very old Robolectric version. Please trying to use latest Robolectric and  feel free to reopen it if you find this problem still exists.
