### ISSUE TITLE
EntityUtils.toString SocketTimeoutException

### ISSUE THREAD

**Issue by chpasha** [robolectric/robolectric#1989]
EntityUtils.toString(entity) from httpclient causes SocketTimeoutException: socket closed when reading xml file from real http source containing base64 image. The same code works just fine on device / emulator. I don't know if solely the file represents the problem or the server response has some oddities. Maybe robolectric version of httpclient has some ridiculously small time-out? There is no visible delay between the call and exception, so it must be less than a second...or the problem lies elsewhere. 
Both 2.4 and 3.0 are affected. 
Stacktrace:
java.net.SocketException: Socket is closed
    at java.net.Socket.setSoTimeout(Socket.java:1101)
    at sun.security.ssl.SSLSocketImpl.setSoTimeout(SSLSocketImpl.java:2436)
    at org.apache.http.impl.io.SocketInputBuffer.isDataAvailable(SocketInputBuffer.java:87)
    at org.apache.http.impl.io.IdentityInputStream.available(IdentityInputStream.java:63)
    at java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:227)
    at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
    at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:159)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.Reader.read(Reader.java:140)
    at org.apache.http.util.EntityUtils.toString(EntityUtils.java:135)

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
