### ISSUE TITLE
android.util.Xml.parse - Not handled by Robolectric. UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mikedunbar** [robolectric/robolectric#1996]
Since this is part of the Android SDK, I'm assuming Robolectric should support mocking/shadowing it? Here is the stack trace I am getting:
```
java.lang.UnsatisfiedLinkError: org.apache.harmony.xml.ExpatParser.staticInitialize(Ljava/lang/String;)V
	at org.apache.harmony.xml.ExpatParser.staticInitialize(Native Method)
	at org.apache.harmony.xml.ExpatParser.<clinit>(ExpatParser.java:576)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:314)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
	at android.util.Xml.parse(Xml.java:84)
	at com.wsi.android.weather.utils.settings.MapSkinParser.parse(MapSkinParser.java:54)
	at com.wsi.android.weather.utils.settings.MapSkinSettings.<init>(MapSkinSettings.java:37)
	at com.wsi.android.framework.settings.ConfigurationManager.createSkinSettings(ConfigurationManager.java:118)
	at com.wsi.android.framework.settings.ConfigurationManager.createSkinSettingsFromXmlConfig(ConfigurationManager.java:170)
	at com.wsi.android.framework.settings.ConfigurationManager.initApplicationAndSkinSettings(ConfigurationManager.java:44)
	at com.wsi.android.weather.utils.InitializationGuardian.performAppInit(InitializationGuardian.java:87)
	at com.wsi.android.weather.utils.InitializationGuardian.attemptInit(InitializationGuardian.java:67)
	at com.wsi.android.weather.ui.MapApplication.onCreate(MapApplication.java:68)
	at com.weather.Weather.app.FlagshipApplication.onCreate(FlagshipApplication.java:164)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.
```

More detailed discussion on the Robolectric good group [here](https://groups.google.com/forum/#!topic/robolectric/9Dc8dDFY4gU)
A similar issue mentioning a workaround (using another XML parser) [here](https://github.com/robolectric/robolectric/issues/1002)

Thanks and hoping to be able to use this testing tool!

**Comment by erd** [comment]
`ExpatParser` is loading a native library when it throws that exception, and native libs are not currently supported by Robolectric.

**Comment by mikedunbar** [comment]
OK - so the best thing to do is to use a parser other than android.util.Xml?

**Comment by erd** [comment]
Either that or move the code somewhere it can be stubbed out in test.

**Comment by mikedunbar** [comment]
OK, thanks.

**Comment by erd** [comment]
See #1171.

**Comment by niushicha1** [comment]
这个问题，有人解决吗，请问
