### ISSUE TITLE
java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1 with GreenDAO

### ISSUE THREAD

**Issue by am5a03** [robolectric/robolectric#2010]
I've come across this issue with GreenDAO
I followed https://github.com/robolectric/robolectric/issues/1890 to reset all my sessions in ```@After```, but seems no luck at all. However, if I use plain SQL in Android, everything looks good.

I have tried to even reset my SQLiteDatabase in ```@After```, but then it will give me 'no such table' error in next test cases. I'm using robolectric 3.0

```
java.lang.RuntimeException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-22-thread-1,5,main] []
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:470)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:376)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:67)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:548)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
	at de.greenrobot.dao.query.DeleteQuery.executeDeleteWithoutDetachingEntities(DeleteQuery.java:72)
	at com.myapp.android.app.data.DatabaseController$GroupListDB.clearList(DatabaseController.java:1287)
	at com.myapp.android.app.task.GetGroupList.processData(GetGroupList.java:31)
	at com.myapp.android.app.task.ApiTask.run(ApiTask.java:115)
	at com.myapp.android.app.task.GetGroupListTest.test_GetGroupList_AfterDidGetGroupList(GetGroupListTest.java:58)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-22-thread-1,5,main] []
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:333)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:379)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:376)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:452)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:446)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kriegfrj** [comment]
If you are resetting the DB in an @After, you may also need to set it up again in a @Before. Give that a try.

**Comment by am5a03** [comment]
Thank you, that works! I'll close this issue.

**Comment by ray1984** [comment]
@am5a03 how do you reset your DB? what command?

**Comment by am5a03** [comment]
Hi @ray1984 

We have a class extending SQLiteOpenHelper, every time `@Before` we call the below function to reset our DB.

`dropAllTables()` and `createAllTables()` are simply a wrapper function that drops all tables and create all tables, they are purely SQL.
```
public void resetDB(){
        SQLiteDatabase db = getWritableDatabase();

        db.beginTransaction();

        try {
            dropAllTables(db);
            createAllTables(db);


            db.setTransactionSuccessful();
        } finally {
            db.endTransaction();
        }
    }
```
Example:
```
public void dropAllTables(SQLiteDatabase db){
        db.execSQL("DROP TABLE IF EXISTS " + DB.table.USERS);
        //other DROP TABLE SQLs...
}
```

**Comment by ray1984** [comment]
Well, I thought you use something special in GreenDao api
