### ISSUE TITLE
I try to use 3.1-SNAPSHOT

### ISSUE THREAD

**Issue by OleksandrKucherenko** [robolectric/robolectric#2013]
```
com.***.RegisterOrLoginTests,test_00_AppStartup
Downloading: org/robolectric/shadows-core/3.1-SNAPSHOT/shadows-core-3.1-20150709.004530-3-21.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
Unable to locate resource in repository

Unable to resolve artifact: Missing:
----------
1) org.robolectric:shadows-core:jar:21:3.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-20150709.004530-3 -Dclassifier=21 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-20150709.004530-3 -Dclassifier=21 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:21:3.1-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  sonatype (https://oss.sonatype.org/content/groups/public/)


	at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:268)
	at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:168)
	at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:40)
	at org.robolectric.internal.dependency.CachedDependencyResolver.getLocalArtifactUrls(CachedDependencyResolver.java:43)
	at org.robolectric.internal.InstrumentingClassLoaderFactory.getSdkEnvironment(InstrumentingClassLoaderFactory.java:39)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:187)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
----------
1) org.robolectric:shadows-core:jar:21:3.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-20150709.004530-3 -Dclassifier=21 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=shadows-core -Dversion=3.1-20150709.004530-3 -Dclassifier=21 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:21:3.1-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  sonatype (https://oss.sonatype.org/content/groups/public/)


	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:360)
	at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:263)
	... 23 more


Process finished with exit code 255

```

Let's take a look on web https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/shadows-core/3.1-SNAPSHOT/

```

Name	Last Modified	Size	Description
Parent Directory
maven-metadata.xml	Thu Jul 09 00:45:34 UTC 2015	1195	
maven-metadata.xml.md5	Thu Jul 09 00:45:34 UTC 2015	32	
maven-metadata.xml.sha1	Thu Jul 09 00:45:34 UTC 2015	40	
shadows-core-3.1-20150709.004530-3-javadoc.jar	Thu Jul 09 00:45:34 UTC 2015	1745551	
shadows-core-3.1-20150709.004530-3-javadoc.jar.md5	Thu Jul 09 00:45:34 UTC 2015	32	
shadows-core-3.1-20150709.004530-3-javadoc.jar.sha1	Thu Jul 09 00:45:34 UTC 2015	40	
shadows-core-3.1-20150709.004530-3-sources.jar	Thu Jul 09 00:45:33 UTC 2015	2349605	
shadows-core-3.1-20150709.004530-3-sources.jar.md5	Thu Jul 09 00:45:33 UTC 2015	32	
shadows-core-3.1-20150709.004530-3-sources.jar.sha1	Thu Jul 09 00:45:33 UTC 2015	40	
shadows-core-3.1-20150709.004530-3.jar	Thu Jul 09 00:45:31 UTC 2015	2658589	
shadows-core-3.1-20150709.004530-3.jar.md5	Thu Jul 09 00:45:32 UTC 2015	32	
shadows-core-3.1-20150709.004530-3.jar.sha1	Thu Jul 09 00:45:32 UTC 2015	40	
shadows-core-3.1-20150709.004530-3.pom	Thu Jul 09 00:45:32 UTC 2015	14523	
shadows-core-3.1-20150709.004530-3.pom.md5	Thu Jul 09 00:45:32 UTC 2015	32	
shadows-core-3.1-20150709.004530-3.pom.sha1	Thu Jul 09 00:45:32 UTC 2015	40	
```

expected:
shadows-core-3.1-20150709.004530-3-21.jar

```java
@Config(sdk = Build.VERSION_CODES.LOLLIPOP
    , manifest = "src/main/AndroidManifest.xml"
    , constants = BuildConfig.class
    , packageName = "com.***.component"
)
@RunWith(RobolectricGradleTestRunner.class)
```

How to solve?

**Comment by erd** [comment]
You may have to run `mvn --update-snapshots` if you're not seeing the most recent snapshot version. Also, please post these kinds of issues on the mailing list (robolectric@googlegroups.com).
