### ISSUE TITLE
Whitespace not trimmed when resources are parsed

### ISSUE THREAD

**Issue by OleksandrKucherenko** [robolectric/robolectric#2014]
Originally was: Robolectric cannot resolve the background selector? How to solve?

```
Caused by: java.lang.NumberFormatException: Color value '
      @drawable/tsview_action_bar_item_background_selector
    ' must start with #
	at org.robolectric.shadows.ResourceHelper.getColor(ResourceHelper.java:44)
	at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:259)
	at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:255)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:157)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.internal.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:437)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.$$robo$$obtainStyledAttributes(Context.java:472)
	at android.content.Context.obtainStyledAttributes(Context.java)
	at android.view.View.$$robo$$__constructor__(View.java:3677)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at android.widget.LinearLayout.<init>(LinearLayout.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:41)
	at android.view.LayoutInflater.$$robo$$onCreateView(LayoutInflater.java:682)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:741)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:482)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.widget.ActionBarView.$$robo$$__constructor__(ActionBarView.java:183)
	at com.android.internal.widget.ActionBarView.<init>(ActionBarView.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:365)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$generateLayout(PhoneWindow.java:3489)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$installDecor(PhoneWindow.java:3561)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java)
	at com.android.internal.policy.impl.PhoneWindow.$$robo$$setContentView(PhoneWindow.java:367)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java)
	at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:119)
	at com.actionbarsherlock.app.SherlockFragmentActivity.setContentView(SherlockFragmentActivity.java:262)
	at com.***.activities.MainActivity.onCreate(MainActivity.java:30)
	at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:122)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.tsview.robolectric.RobolectricTestHolder.fullLifecycle(RobolectricTestHolder.java:44)
	at com.tsview.robolectric.RobolectricTestHolder.fullLifecycle(RobolectricTestHolder.java:29)
	at com.***.RegisterOrLoginTests.test_00_AppStartup(RegisterOrLoginTests.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 1 more
```

Project structure:
```
app
 -- main
 -- flavor1
 -- test
3rd-party
 -- lib1
 -- lib...
 -- lib N
```

**Comment by OleksandrKucherenko** [comment]
I found the cause of the problem:
- anybody try to TRIM the line from white-spaces during the XML parsing?! 

mistake is in code (https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/res/Attribute.java):
```java
public boolean isResourceReference() {
    return value.startsWith("@") && !isNull();
}
```

value may contain white-space at the beginning!

**Comment by Amritpal363** [comment]
Good morning 🙏🌹 india punjabi city code 143604

![Image](https://github.com/user-attachments/assets/ef2dcdd2-ab2c-47f7-955c-f4a6d76cebfc)
