### ISSUE TITLE
Null content provider authority with support library v23

### ISSUE THREAD

**Issue by hidroh** [robolectric/robolectric#2020]
Just upgraded to Android support library 23.0.1 and get the following exception while running tests that passed with support library 22.2.1:

```
java.lang.RuntimeException: java.lang.SecurityException: The authority of the uri content://XXX/YYY does not match the one of the contentProvider: null
    at org.robolectric.util.SimpleFuture.run(SimpleFuture.java:61)
    at org.robolectric.shadows.support.v4.ShadowAsyncTaskLoader$2.run(ShadowAsyncTaskLoader.java:43)
    at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:230)
    at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:85)
    at org.robolectric.util.Scheduler.post(Scheduler.java:72)
    at org.robolectric.shadows.support.v4.ShadowAsyncTaskLoader.onForceLoad(ShadowAsyncTaskLoader.java:40)
    at android.support.v4.content.AsyncTaskLoader.onForceLoad(AsyncTaskLoader.java)
    at android.support.v4.content.Loader.forceLoad(Loader.java:329)
    at android.support.v4.content.CursorLoader.onStartLoading(CursorLoader.java:153)
    at android.support.v4.content.Loader.startLoading(Loader.java:272)
    at android.support.v4.app.LoaderManagerImpl$LoaderInfo.start(LoaderManager.java:273)
    at android.support.v4.app.LoaderManagerImpl.installLoader(LoaderManager.java:562)
    at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:549)
    at android.support.v4.app.LoaderManagerImpl.restartLoader(LoaderManager.java:697)
        ...
Caused by: java.lang.SecurityException: The authority of the uri content://XXX/YYY does not match the one of the contentProvider: null
    at android.content.ContentProvider.validateIncomingUri(ContentProvider.java:1795)
    at android.content.ContentProvider.access$000(ContentProvider.java:90)
    at android.content.ContentProvider$Transport.query(ContentProvider.java:202)
    at android.content.ContentResolver.query(ContentResolver.java:478)
    at android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:29)
    at android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
    at android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
    at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
    at android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
    at org.robolectric.shadows.support.v4.ShadowAsyncTaskLoader$BackgroundWorker.call(ShadowAsyncTaskLoader.java:50)
    at org.robolectric.util.SimpleFuture.run(SimpleFuture.java:56)
    ... 67 more
```

In support library v23 a new `ContentResolverCompat` has been added, which seems to be the one causing exception: https://developer.android.com/sdk/support_api_diff/23/changes/pkg_android.support.v4.content.html 

Using:
- Robolectric 3.0
- Compile & target SDK 23
- Test SDK 21
- Build tools version 23.3.0
- Android plugin version 1.3.1

**Comment by hidroh** [comment]
Created a shadow class to work around this for now:

```java
package android.support.v4.content;

import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;

import org.robolectric.annotation.Implementation;
import org.robolectric.annotation.Implements;
import org.robolectric.shadows.ShadowApplication;

import static org.robolectric.Shadows.shadowOf;

@Implements(value = ContentResolverCompatJellybean.class, inheritImplementationMethods = true)
public class ShadowContentResolverCompatJellybean {
    @Implementation
    public static Cursor query(ContentResolver resolver, Uri uri, String[] projection,
                               String selection, String[] selectionArgs, String sortOrder,
                               Object cancellationSignalObj) {
        return shadowOf(ShadowApplication.getInstance().getContentResolver())
                .query(uri, projection, selection, selectionArgs, sortOrder);
    }
}
```

**Comment by miketrewartha** [comment]
Thank you hidroh!

**Comment by priyamall** [comment]
I also Updated to support lib v23.0.1.Facing so many crashes.
My Crashlytics shows following info:

ContentResolverCompatJellybean.java line 29
android.support.v4.content.ContentResolverCompatJellybean.query

 Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()

What do i do to fix this ?Any suggestions please...

**Comment by utzcoz** [comment]
Android support library is too old, and many projects has already upgraded to use AndroidX library. Also this Robolectric version is too old, and latest Robolectric dropped the supporting for shadowing support library. If you have any issues about AndroidX library with latest Robolectric, please file a new issue. Thansk.
