### ISSUE TITLE
Deep-link no-index manifest tag causes NPE

### ISSUE THREAD

**Issue by tmelz** [robolectric/robolectric#2026]
The [deep-link](https://developers.google.com/app-indexing/android/app?hl=en) docs suggest adding a meta-data tag under `<application>` in `AndroidManifest.xml` to specify a no-index list:

``` xml
<meta-data android:name="search-engine" android:resource="@xml/noindex"/>
```

with the `noindex` file something like:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<search-engine xmlns:android="http://schemas.android.com/apk/res/android">
  <noindex uri="http://recipe-app.com/recipes/hidden_uri"/>
  <noindex uriPrefix="http://recipe-app.com/recipes/hidden_prefix"/>
  <noindex uri="recipe-app://hidden_path"/>
  <noindex uriPrefix="recipe-app://hidden_prefix"/>
</search-engine>
```

This produces the following exception when using Robolectric:

```
java.lang.NullPointerException
    at org.robolectric.res.builder.DefaultPackageManager.metaDataToBundle(DefaultPackageManager.java:701)
    at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:479)

java.lang.RuntimeException: java.lang.NullPointerException
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
```

It looks like `getValue()` returns `null` for this element.

I'm currently using a manifest-merger workaround:

``` xml
    <application>
        <meta-data android:name="search-engine" tools:node="remove"/>
    </application>
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
