### ISSUE TITLE
ShadowMap.<clinit> AbstractMethodError

### ISSUE THREAD

**Issue by legarspol** [robolectric/robolectric#2036]
Hi !

I have a problem here exclusively when compiling with Android studio:
 ```
java.lang.AbstractMethodError
	at org.robolectric.internal.bytecode.ShadowMap.<clinit>(ShadowMap.java:19)
	at org.robolectric.internal.bytecode.ShadowMap$Builder.build(ShadowMap.java:148)
	at org.robolectric.RobolectricTestRunner.createShadowMap(RobolectricTestRunner.java:509)
	at org.robolectric.RobolectricTestRunner.configureShadows(RobolectricTestRunner.java:408)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:210)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

I do not have the problem when launching tests with the cli.
Using Gradle 1.2.3.
Android studio 1.4 beta 3 
```
  testCompile 'junit:junit:4.12'
    testCompile 'org.hamcrest:hamcrest-core:1.1'
    testCompile 'org.hamcrest:hamcrest-library:1.1'
    testCompile 'org.hamcrest:hamcrest-integration:1.1'
    testCompile 'org.mockito:mockito-core:2.0.5-beta'
    testCompile('org.robolectric:robolectric:3.0') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
    testCompile('org.robolectric:shadows-support-v4:3.0') {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }
```
I actually need to compile with Android studio in order use the debugger and debug my tests.
Any help appreciated !
It seems that that dude have the same problem:
https://groups.google.com/forum/#!topic/robolectric/ApBbCF8UO9A

**Comment by sureshdraco** [comment]
I found the root cause in my case.
I had "robolectric:3.0" and "rc2" both versions in my project, each for different modules in same project. I changed them to point to same version and solved the issue.

**Comment by legarspol** [comment]
Thank you so much !
It solved my problem :-)
