### ISSUE TITLE
Shadowing ParcelFileDescriptor.createPipe

### ISSUE THREAD

**Issue by sunnygoyal** [robolectric/robolectric#2042]
Hi,

I am testing a code which uses ParcelFileDescriptor.createPipe. I am getting NullPointerException when making this call.
How do I work around this?

**Comment by jongerrish** [comment]
You will need to include more information, stack trace? Version of RE,
sample code.

**Comment by sunnygoyal** [comment]
```
java.lang.NullPointerException
	at android.os.ParcelFileDescriptor.createPipe(ParcelFileDescriptor.java:361)
	at com.mypackage.ParcelableResponse.writeToParcel(ClusteredCardsResponse.java:58)
```

Actual code

```
ParcelableResponse extends Response {

 writeToParcel(Parcel p, int flags) {
    final ParcelFileDescriptor[] fds;
    try {
      fds = ParcelFileDescriptor.createPipe();
    } catch (IOException e) {
      Log.e(TAG, "Failure building output pipe", e);
      return;
    }
    Thread thr = new Thread("ProcessStats pipe output") {
      public void run() {
        FileOutputStream fout = new ParcelFileDescriptor.AutoCloseOutputStream(fds[1]);
        try {
          super.writeToStream(fout);
          fout.close();
        } catch (IOException e) {
          Log.e(TAG, "Failure writing pipe", e);
        }
      }
    };
    thr.start();
    dest.writeFileDescriptor(fds[0].getFileDescriptor());
  }
}

```

I am testing the code to writeToParcel and readFromParcel

**Comment by benmargolin** [comment]
+1

**Comment by alanharder** [comment]
+1 I hit this today.

**Comment by levischmidt** [comment]
+1. Any chance anyone found a workaround for this?

NOTE: I also get a NoClassDefFoundError if I try to use createReliablePipe instead. 

java.lang.NoClassDefFoundError: java/lang/UnsafeByteSequence
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2703)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:260)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:54)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:118)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:18)
	at libcore.io.IoUtils.<clinit>(IoUtils.java)
	at android.os.ParcelFileDescriptor.createCommSocketPair(ParcelFileDescriptor.java:436)
	at android.os.ParcelFileDescriptor.createReliablePipe(ParcelFileDescriptor.java:381)

**Comment by jongerrish** [comment]
These calls hit native code and there are no shadow implementation for this yet.

Looking at the implementation for ParcelFileDescriptor I think you could probably just add a shadow implementation for 

public static FileDescriptor[] pipe() throws ErrnoException

to ShadowPosix to make both of these calls work.

If you send me a PR I'll merge that for you.
