### ISSUE TITLE
Nullpointer using RobolectricPackageManager

### ISSUE THREAD

**Issue by wiyarmir** [robolectric/robolectric#2058]
Robolectric 3.0 from Maven

Using RobolectricPackageManager to set up some fixtures for my test, then casting it to PackageManager and passing it to the method to test, I found that getInstalledPackages was returning null.

This is my set up:

``` java
@Before
public void setUp() throws Exception {
    RobolectricPackageManager roboPM = RuntimeEnvironment.getRobolectricPackageManager();
    roboPM.addPackage("com.example.mypackage");
    RuntimeEnvironment.setRobolectricPackageManager(roboPM);
}
```

And usage:

``` java
@Test
public void testGetInstalledApps() {
    RobolectricPackageManager roboPM = RuntimeEnvironment.getRobolectricPackageManager();

    HashMap<Integer, String> actual = DataUsageStats.getInstalledApps((PackageManager) roboPM);
    [...]
}
```

And the method being tested

``` java
@NonNull
static HashMap<Integer, String> getInstalledApps(PackageManager packageManager) {
    HashMap<Integer, String> appNames = new HashMap<>();

    for (ApplicationInfo app : packageManager.getInstalledApplications(0)) {
        appNames.put(app.uid, app.packageName);
    }

    return appNames;
}
```

Curious about how could that be, I debugged the test, and stepping in, found that at runtime it is going through the StubPackageManager implementation (which returns null as expected from it) even if the instance one level above is DefaultPackageManager.
![Imgur](http://i.imgur.com/jOxlxxs.png)
Any hints?

**Comment by MartinRajniak** [comment]
#1331 this was fixed once, probably it wasn't propagated to v3

**Comment by wiyarmir** [comment]
I saw that issue, but that's when there was no implementation, isn't it?
The implementation is there, and I can see it being instantiated when I
debug, but somehow the method call goes for the stub.

**Comment by jaredsburrows** [comment]
I do not see an issue here as I use these for my apps. Please see my answer to this issue here: https://github.com/robolectric/robolectric/issues/1982. This is an example of how to use the package manager.

@erd Can we can close this?

**Comment by wiyarmir** [comment]
@jaredsburrows I do use the package manager in that way, and what I report is that the class being tested instead of accessing the DefaultPackageManager implementation that Robolectric has, it's accessing the Stub. 

I even modified the code to look exactly like yours.

```
@Test
public void testGetInstalledApps() {
    RobolectricPackageManager roboPM = RuntimeEnvironment.getRobolectricPackageManager();
    PackageInfo pi = new PackageInfo();
    pi.packageName = "testGetPackageVersion";
    pi.versionName = "2.0";
    pi.applicationInfo = new ApplicationInfo();
    pi.applicationInfo.packageName = "testGetPackageVersion";
    pi.applicationInfo.name = "testGetPackageVersion";
    roboPM.addPackage(pi);

    NewShadowTrafficStats.setTotalRxBytes(1);
    NewShadowTrafficStats.setTotalTxBytes(1);

    PackageManager packageManager = (PackageManager) roboPM;

    HashMap<Integer, String> actual = DataUsageStats.getInstalledApps(packageManager); // NPE

    List<Integer> uidList = new ArrayList<>();
    for (ApplicationInfo pack : (packageManager).getInstalledApplications(0)) {
        uidList.add(pack.uid);
    }

    assertThat(actual).containsKeys((Integer[]) uidList.toArray());
}
```

And keeps crashing. Stacktrace:

```
java.lang.NullPointerException
	at frb.codilink.launcher.libs.stats.DataUsageStats.getInstalledApps(DataUsageStats.java:51)
	at frb.codilink.launcher.libs.stats.DataUsageStatsTest.testGetInstalledApps(DataUsageStatsTest.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jaredsburrows** [comment]
You are receiving an NPE, here `DataUsageStats.getInstalledApps(packageManager);` because you are not passing in the `RuntimeEnvironment.application` context. Is `DataUsageStats` your class?

**Comment by jaredsburrows** [comment]
@erd Can we close this? Why is this still open? This is not a support forum.

**Comment by jfarfel** [comment]
It's still open because getInstalledApplications(int) returns null, as there's no implementation for it in DefaultPackageManager. There's only an implementation for getInstalledPackages(int).

(fwiw, I'm not sure what exactly the difference in usefulness is between PackageManager's getInstalledApplications() and getInstalledPackages(), so I'm switching my app to use the latter to avoid this bug. :) )

**Comment by jongerrish** [comment]
Looks like we've implemented getInstalledApplications(int) - please test again with Robolectric 4.0 and reopen if its still an issue.
