### ISSUE TITLE
Resource array is not supported

### ISSUE THREAD

**Issue by prohan91** [robolectric/robolectric#2064]
I see following error when trying to access resource array:

``` java
Caused by: java.lang.RuntimeException: huh? ResName{com.xx.yy:array/custom_colors}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:106)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:55)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:460)
```

Resource array is defined as:

``` html
<resources>
    <array name="custom_colors">
        <item>@color/red</item>
        <item>@color/yellow</item>
    </array>
</resources>
```

**Comment by erd** [comment]
Which version of Robolectric are you using?

**Comment by prohan91** [comment]
I see this in v3.1

https://github.com/robolectric/robolectric/blob/master/robolectric-resources/src/main/java/org/robolectric/shadows/Converter.java
