### ISSUE TITLE
java.lang.NoSuchMethodError: org.robolectric.RuntimeEnvironment.getMasterScheduler()Lorg/robolectric/util/Scheduler;

### ISSUE THREAD

**Issue by emilianobonassi** [robolectric/robolectric#2083]
Yesterday working, today not.

Environment:
Roboelectric 3.1-SNAPSHOT
Android Studio 1.4
TargetSdk 22
Changes - Android Support Repository from 21 to 22

Complete info:
```
java.lang.NoSuchMethodError: org.robolectric.RuntimeEnvironment.getMasterScheduler()Lorg/robolectric/util/Scheduler;
	at org.robolectric.shadows.ShadowLooper.resetScheduler(ShadowLooper.java:315)
	at org.robolectric.shadows.ShadowLooper.__constructor__(ShadowLooper.java:77)
	at android.os.Looper.<init>(Looper.java)
	at android.os.Looper.prepare(Looper.java:78)
	at android.os.Looper.prepareMainLooper(Looper.java:88)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:101)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:443)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:247)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

What's happened?

**Comment by erd** [comment]
This happens when you don't have a complete set of SNAPSHOT jars. Try running `gradle --refresh-dependencies`. If that doesn't work, delete `~/.m2/repository/org/robolectric` and re-build.

If you keep having configuration issues, please post on robolectric@googlegroups.com for help.

**Comment by emilianobonassi** [comment]
@erd , thank you very much. I had tried to remove only the older jars but someone in maven went wrong. Now, after a complete cleanup it works again!
Good work!!
