### ISSUE TITLE
NullPointerException in RobolectricGradleTestRunner during initialization

### ISSUE THREAD

**Issue by cperry-gpsw** [robolectric/robolectric#2096]
This simple test fails to run

```java
@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 23)
public class ExampleRobolectricTest{

  @Test
  public void shouldInitialize() {
    assertThat(RuntimeEnvironment.application).isNotNull();
  }
}
```

I'm on 3.1-SNAPSHOT

Stack trace:

```
java.lang.NullPointerException
	at org.robolectric.RobolectricGradleTestRunner.<init>(RobolectricGradleTestRunner.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by cperry-gpsw** [comment]
Here's the relevant Robolectric code:

```java
public RobolectricGradleTestRunner(Class<?> klass) throws InitializationError {
    super(klass);
    final String locationPath = getClass().getProtectionDomain().getCodeSource().getLocation().getFile();
    FsFile currentLocation = FileFsFile.from(locationPath);
    buildFolder = FileFsFile.from(currentLocation.getPath());

    while (buildFolder.listFiles(FOR_RESOURCES).length == 0) {
      if (buildFolder.getParent() == null) {
        throw new IllegalStateException("Could not find resource path in " + currentLocation);
      } else {
        buildFolder = buildFolder.getParent();
      }
    }
  }
```

Looks like

```java
buildFolder.listFiles(FOR_RESOURCES)
```

is returning null causing the NPE.

The `buildFolder` is pointed at the robolectric jar for some reason.

**Comment by jaredsburrows** [comment]
Yes! I have been seeing this as well in the 3.1 snapshot.

**Comment by erd** [comment]
I suspect this has to do with #2021.

**Comment by cperry-gpsw** [comment]
@erd That was my suspicion as well. The Git history shows those changes occured between 3.0 and 3.1. Any idea why the buildFolder is pointing to the robolectric jar?

**Comment by erd** [comment]
Not off the top of my head. I'd have to step through it with a debugger.

**Comment by anujverma000** [comment]
Any Update on this? I am facing this issue.

**Comment by emce** [comment]
This is error I got for 3.1-SNAPSHOT:
```java.lang.NullPointerException
	at org.robolectric.RobolectricGradleTestRunner.<init>(RobolectricGradleTestRunner.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at com.intellij.junit4.JUnit46ClassesRequestBuilder.collectWrappedRunners(JUnit46ClassesRequestBuilder.java:90)
	at com.intellij.junit4.JUnit46ClassesRequestBuilder.getClassesRequest(JUnit46ClassesRequestBuilder.java:51)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:91)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
and for 3.0 I got:
```
java.lang.NullPointerException
	at org.robolectric.res.builder.DefaultPackageManager.metaDataToBundle(DefaultPackageManager.java:701)
	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:479)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:74)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by rogerhu** [comment]
Can we revert https://github.com/robolectric/robolectric/pull/2021 for now?  It is definitely breaking on 3.1-snapshot.

**Comment by jaredsburrows** [comment]
@rogerhu  +1

**Comment by cperry-gpsw** [comment]
@erd Any luck with this? I'm dying to compile against something later than api 21 but this bug is holding me back.

**Comment by ened** [comment]
Same issue here, `buildFolder` points at `/Users/sebastian/.gradle/caches/modules-2/files-2.1/org.robolectric/robolectric/3.1-SNAPSHOT/7e20e08acc0afc98834f3d6b1c05afb50407b274/robolectric-3.1-SNAPSHOT.jar`.

Using latest snapshot.

**Comment by rogerhu** [comment]
The snapshot just hasn't been updated in 2+ weeks since 10/29:

https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/3.1-SNAPSHOT/
https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/3.1-SNAPSHOT/maven-metadata.xml

**Comment by mag** [comment]
+1, the SNAPSHOT is broke; who knows how to rebuild? I used to, way back in the day, and could try to figure it out again unless somebody (@erd?) can just rip one off.

**Comment by erd** [comment]
There is probably something failing in the Travis build during the upload process. Even though the build is green, sometimes it fails building / uploading the snapshot. I suspect there's a javadoc doclet error somewhere. I don't have time to look at it, but if someone can track it down, I'm happy to merge any fixes needed.

**Comment by erd** [comment]
Here's the issue:

[ERROR] Exit code: 1 - /home/travis/build/robolectric/robolectric/robolectric-utils/src/main/java/org/robolectric/util/AccessibilityUtil.java:110: error: reference not found
[ERROR] * run ({@link ForRobolectricVersion.LATEST}.

**Comment by jaredsburrows** [comment]
@mag @erd What does the javadoc error have to do with the TestRunner failing to start? Is it possible to simply revert the changes?

**Comment by rogerhu** [comment]
Can someone merge? https://github.com/robolectric/robolectric/pull/2152

**Comment by jaredsburrows** [comment]
@rogerhu This fixes the runner?

**Comment by rogerhu** [comment]
That change has been reverted.  The Javadoc bug is preventing this merge to be updated in the snapshot repo.

**Comment by jaredsburrows** [comment]
@rogerhu Thanks for the update. I hope they merge your PR so I can start testing with `3.1` again.

**Comment by bblia** [comment]
@rogerhu +1

**Comment by jaredsburrows** [comment]
@rogerhu  +1

**Comment by rogerhu** [comment]
Snapshot build works now, many thanks.

**Comment by jaredsburrows** [comment]
@rogerhu @cperry-gpsw @erd We can close this now?

**Comment by rogerhu** [comment]
Yep thanks!

**Comment by mineshpatel1511** [comment]
Hi, 
I am trying to upgrade to roboelectric 3.0 and also added below tags to my test class. @RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class). I see the below stack trace. Has anyone resolved this issue?

java.lang.NullPointerException
    	at org.robolectric.res.builder.DefaultPackageManager.metaDataToBundle(DefaultPackageManager.java:701)
    	at org.robolectric.res.builder.DefaultPackageManager.addManifest(DefaultPackageManager.java:479)
    	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:74)
    	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
    	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
    	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by emce** [comment]
There is workaround - you have to add ignore to manifest node with resource - this is how it looks for me:
```xml
<meta-data
      android:name="com.parse.push.notification_icon"
      android:resource="@drawable/icon_notification"
      tools:ignore="ManifestResource"
      tools:node="remove"/>
```

**Comment by mineshpatel1511** [comment]
Thanks @emce for the reply. After adding this, I get these exceptions.

java.io.FileNotFoundException:. (Is a directory)
    at java.io.RandomAccessFile.open(Native Method)
    at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
    at android.support.multidex.ZipUtil.getZipCrc(ZipUtil.java:55)
    at android.support.multidex.MultiDexExtractor.getZipCrc(MultiDexExtractor.java:153)
    at android.support.multidex.MultiDexExtractor.load(MultiDexExtractor.java:87)
    at android.support.multidex.MultiDex.install(MultiDex.java:159)
    at com.MyApp.attachBaseContext(MyApp.java:84)
    at com.TestMyApp.attachBaseContext(TestMyApp.java:10)
    at android.app.Application.attach(Application.java:181)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:131)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

com.activity.DrawerActivityTest > itShouldPostEvent STANDARD_ERROR
    java.lang.RuntimeException: Multi dex installation failed (Is a directory)).
    at android.support.multidex.MultiDex.install(MultiDex.java:178)
    at com.MyApp.attachBaseContext(MyApp.java:84)
    at com.TestMyApp.attachBaseContext(MyApp.java:10)
    at android.app.Application.attach(Application.java:181)
    at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
    at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:131)
    at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
