### ISSUE TITLE
Broken resource loading near max method count

### ISSUE THREAD

**Issue by jcogilvie** [robolectric/robolectric#2099]
We have a similar issue to [this](http://stackoverflow.com/questions/27788825/no-resourceloader-found-runtimeexception-in-robolectric) one.  We are very close to the max method count (but not over yet... in the relevant branch, anyway) and our release build stopped passing tests.  [Edit:  I'm told by teammates that removing play services fixes it, but I haven't verified this myself.  Following up with them on this point has generated more uncertainty.]:  

```
Caused by: java.lang.RuntimeException: no ResourceLoader found for com.blackboard.android.bblearncollaborate
    at org.robolectric.res.RoutingResourceLoader.pickFor(RoutingResourceLoader.java:86)
    at org.robolectric.res.RoutingResourceLoader.pickFor(RoutingResourceLoader.java:75)
    at org.robolectric.res.RoutingResourceLoader.getDrawableNode(RoutingResourceLoader.java:46)
    at org.robolectric.shadows.ShadowAssetManager.openNonAsset(ShadowAssetManager.java:188)
    at android.content.res.AssetManager.openNonAsset(AssetManager.java)
    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2421)
    ... 75 more
```

Our debug build works fine; all tests pass.  Release fails with this error (as the root cause of a bunch of other exceptions).  Robo 3.0, API 21.  I can provide whatever additional info you need.

This particular test failure is on a sub-module build (android library) of our application.  Here is an excerpt from our top-level build.gradle.  The "subprojects" closure governs this project.  (There's some extra stuff about copying resources to work around another quirk that I included for completeness):

``` groovy
allprojects {
    ext {
        // ** Android stuff
        minSdkVersion = 15
        targetSdkVersion = 21
        compileSdkVersion = 21
        buildToolsVersion = "22.0.1"
        lintAbortOnError = false
        lintCheckReleaseBuilds = true
    }
}

subprojects {
    apply plugin: 'com.android.library'

    android {
        compileSdkVersion allprojects.ext.compileSdkVersion
        buildToolsVersion allprojects.ext.buildToolsVersion
        defaultConfig {
            minSdkVersion allprojects.ext.minSdkVersion
            targetSdkVersion allprojects.ext.targetSdkVersion
        }
        lintOptions {
            abortOnError allprojects.ext.lintAbortOnError
            checkReleaseBuilds allprojects.ext.lintCheckReleaseBuilds
        }
    }

       // After gradle's done compiling the code, it'll run this to add some more tasks for us.
    afterEvaluate { project ->

        // Debug and release get their own tasks
        android.libraryVariants.each { variant ->

            // TODO may be on the build variant
            def myManifestRoot = (new XmlParser()).parse("${project.projectDir}/src/main/AndroidManifest.xml")
            def myPackageNamespace = myManifestRoot.@package
            def myPackagePath = myPackageNamespace.replaceAll("\\.", "/")

            def processedPackages = new ArrayList<String>()

            // Task one of two that we're adding:  it depends on discovering manifest files
            // and on processing resources for this build variant.  It copies the merged R.java file
            // from our project's namespace (which contains the resource IDs included in our
            // dependencies) and drops it into each of our dependencies' namespaces.  This is to work
            // around limitations in robolectric.
            def copyRJavaTaskName = "copy${variant.name.capitalize()}RJavaForRobolectric"
            task(copyRJavaTaskName,
                    dependsOn: ["process${variant.name.capitalize()}Resources", "discoverManifestFiles"]) << {

                // For each manifest file we discovered earlier, open it up an pull out the package
                project.ext.manifestFiles.each {
                    def parsedManifestRoot = (new XmlParser()).parse(it.absolutePath)
                    def targetPackageNamespace = parsedManifestRoot.@package

                    // If it was already added, skip it
                    if (!processedPackages.contains(targetPackageNamespace)) {
                        processedPackages.add(targetPackageNamespace)
                    } else {
                        println "WARNING:  Found two versions of $targetPackageNamespace; this could mess" +
                                " with your assets and resources"
                        // For some reason there are two versions of this dependency
                        // so skip additional iterations
                        return
                    }

                    def targetPackageNamespacePath = targetPackageNamespace.replaceAll("\\.", "/")

                    // Copy R.java from our outputs into the namespace of each dependency
                    // (and change the package line in the file, correspondingly)
                    copy {
                        from "${project.buildDir}/generated/source/r/${variant.name}/$myPackagePath"
                        include 'R.java'
                        into "${project.projectDir}/src/test/java/$targetPackageNamespacePath"
                        filter { line -> line.contains("package ${myPackageNamespace};") ? "package ${targetPackageNamespace};" : line }
                    }
                }
            }
            // Insert this new task into the task tree:  compiling unit tests depends on it.
            tasks.getByName("compile${variant.name.capitalize()}UnitTestJavaWithJavac") dependsOn copyRJavaTaskName

            // Second task we're adding:  copy lib assets into the place where robolectric expects them.
            // It depends on processing this variant's resources and on discovering manifest files.
            def copyAssetsTaskName = "copy${variant.name.capitalize()}AssetsForRobolectric"
            task(copyAssetsTaskName,
                    dependsOn: ["process${variant.name.capitalize()}Resources", "discoverManifestFiles"]) << {

                // For each manifest file we discovered, find that project's assets folder and copy it
                // to the same merged destination dir
                project.ext.manifestFiles.each {
                    def manifestDirectory = it.parent

                    def src = "${manifestDirectory}/assets"
                    def dest = "build/intermediates/bundles/${variant.name}/assets"

                    copy {
                        from src
                        include '**/*'
                        into dest
                    }
                }
            }
            // Insert this new task into the task tree:  executing unit tests depends on it.
            tasks.getByName("test${variant.name.capitalize()}UnitTest") dependsOn copyAssetsTaskName
        }
    }

    // This task discovers the manifest files for the .aars that we depend on and
    // adds them to project.ext.manifestFiles for use in later tasks.
    task discoverManifestFiles(dependsOn: 'prepareDebugDependencies') << {

        def aars = new File(project.buildDir.absolutePath + "/intermediates/exploded-aar")
        def manifestFiles = new ArrayList<File>()

        // Iterate through the exploded-aars directory, finding the manifests
        aars.eachFileRecurse(FILES) {
            if (it.name.endsWith('AndroidManifest.xml') && !it.absolutePath.contains('aapt')) {
                manifestFiles.add(it)
            }
        }

        project.ext.manifestFiles = manifestFiles;
    }
}
```

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
