### ISSUE TITLE
huh?  ResName{com.myCompany:color/somecolor}

### ISSUE THREAD

**Issue by jcogilvie** [robolectric/robolectric#2102]
The resources are merged correctly--the intermediate resources folder contains values.xml which contains the color "dark_grey" at a specific ID, but that ID is not resolved to a color.  

Robolectric 3.0.  Library subproject within an app.  

```
Caused by: java.lang.RuntimeException: huh? ResName{com.blackboard.android.bblearncourses:color/dark_grey}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:101)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
    at org.robolectric.shadows.ShadowResources.obtainAttributes(ShadowResources.java:308)
    at android.content.res.Resources.obtainAttributes(Resources.java)
    at android.graphics.drawable.Drawable.obtainAttributes(Drawable.java:1277)
    at android.graphics.drawable.GradientDrawable.inflateChildElements(GradientDrawable.java:1139)
    at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:990)
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
    at android.content.res.Resources.loadDrawableForCookie(Resources.java:2418)
    ... 52 more
```

**Comment by jcogilvie** [comment]
I'm debugging, trying to figure out whether there's anything I can do about this.  

It looks like the namespace is set to "fixme!!!" here (also in a lot of other cases so maybe that's not a breaking issue?), and the count for this ResName in the bundle/hashmap thing in the resource loader is 0, whereas all the other entries in the map for things from my namespace have a count of 1.  

The format here is `reference|color` whereas the attributes that are internal to Android (@color/white, etc) seem to just be `color`.  

Still looking... not sure if that's helpful to you... if you can point me in a direction I can take a look and potentially put up a PR.

**Comment by erd** [comment]
The resource parsing / loading code has been a source of continued pain (look at the number of issues tagged with `resources`). I would really like to determine if we can rely on AOSP for more resource loading and start working on that.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
