### ISSUE TITLE
Whitespace in XML attribute values causes an exception; prevents tests from running

### ISSUE THREAD

**Issue by wongk** [robolectric/robolectric#2126]
The following attribute value: "\n            @color/account_setup_button_bar_background" causes the following exception in Converter#convertAndFill:

Caused by: java.lang.NumberFormatException: Color value '
            @color/account_setup_button_bar_background' must start with #
    at org.robolectric.shadows.ResourceHelper.getColor(ResourceHelper.java:44)
    at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:259)
    at org.robolectric.shadows.Converter$FromColor.fillTypedValue(Converter.java:255)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:157)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
...

Attribute values should be trimmed (with the exception of strings).

**Comment by jongerrish** [comment]
Resource handling has been vastly improved in Robolectric 4.0 an binary resource support. Please give that a try and reopen if its still an issue.
