### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Hesamedin** [robolectric/robolectric#2138]
Hi Guys,

I'm getting following logs when I run my test class.
```
java.util.ConcurrentModificationException
	at java.util.ArrayList.sort(ArrayList.java:1456)
	at java.util.Collections.sort(Collections.java:141)
	at org.robolectric.res.ResBundle.put(ResBundle.java:32)
	at org.robolectric.res.ResBunch.put(ResBunch.java:12)
	at org.robolectric.res.ValueResourceLoader.processNode(ValueResourceLoader.java:36)
	at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
	at org.robolectric.res.ValueResourceLoader.processResourceXml(ValueResourceLoader.java:19)
	at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:46)
	at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:47)
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:40)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:30)
	at org.robolectric.res.PackageResourceLoader.loadEverything(PackageResourceLoader.java:32)
	at org.robolectric.res.PackageResourceLoader.doInitialize(PackageResourceLoader.java:19)
	at org.robolectric.res.XResourceLoader.initialize(XResourceLoader.java:29)
	at org.robolectric.res.XResourceLoader.getValue(XResourceLoader.java:52)
	at org.robolectric.res.PackageResourceLoader.getValue(PackageResourceLoader.java:5)
	at org.robolectric.res.RoutingResourceLoader.getValue(RoutingResourceLoader.java:31)
	at org.robolectric.shadows.ShadowAssetManager.resolveStyle(ShadowAssetManager.java:343)
	at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:286)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.applyStyle(ShadowResources.java:461)
	at android.content.res.Resources$Theme.applyStyle(Resources.java)
	at android.app.ContextImpl.getTheme(ContextImpl.java:838)
	at android.content.ContextWrapper.getTheme(ContextWrapper.java:121)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:135)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:85)
	at org.robolectric.shadows.ShadowActivity.setThemeFromManifest(ShadowActivity.java:85)
	at org.robolectric.shadows.CoreShadowsAdapter$1.setThemeFromManifest(CoreShadowsAdapter.java:35)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:58)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ActivityController.create(ActivityController.java:118)
	at org.robolectric.util.ActivityController.create(ActivityController.java:129)
	at com.passenger.HitchWelcomeActivityTest.setUp(HitchWelcomeActivityTest.java:32)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)


Process finished with exit code 255
```

This is my test class:
```
package com.passenger;

import android.app.Activity;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.passenger.BuildConfig;
import com.passenger.R;

import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricGradleTestRunner;
import org.robolectric.annotation.Config;

import static org.hamcrest.CoreMatchers.equalTo;

@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21, packageName = "com.passenger")
public class HitchWelcomeActivityTest
{
    Activity activity;
    Button btnSignUp;
    TextView btnSkip;

    @Before
    public void setUp()
    {
        activity = Robolectric.buildActivity(HitchWelcomeActivity.class).create().get();

        btnSignUp = (Button) activity.findViewById(R.id.dialog_welcome_sign_up);
        btnSkip = (TextView) activity.findViewById(R.id.dialog_welcome_next_time);
    }

    @Test
    public void shouldNotBeNull() throws Exception
    {
        assertNotNull(activity);
    }

    @Test
    public void shouldHaveSignUp_SkipButtons() throws Exception {
        assertViewIsVisible(btnSignUp);
        assertViewIsVisible(btnSkip);
    }

    public static void assertViewIsVisible(View view) {
        assertNotNull(view);
        assertThat(view.getVisibility(), equalTo(View.VISIBLE));
    }
}
```

Any help would be appreciated, thanks.

**Comment by Hesamedin** [comment]
Okay, based on what I found, is related to my variants.

My test class under X_debug passes while X_release fails :(

**Comment by Hesamedin** [comment]
Seems, I've fixed the issue.
please have a look at http://stackoverflow.com/a/33663431/513413
