### ISSUE TITLE
InflateException with custom view

### ISSUE THREAD

**Issue by masterjefferson** [robolectric/robolectric#2155]
I'm using 3.0. Testing a class which does a layout inflation on a layout containing a custom view produces the following:

 
    android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/channel_lists_channel.xml line #-1 (sorry, not yet implemented): Error inflating class com.github.clans.fab.FloatingActionButton

	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultCandroid.view.InflateException: XML file build/intermediates/res/merged/debug/layout/channel_lists_channel.xml line #-1 (sorry, not yet implemented): Error inflating class com.github.clans.fab.FloatingActionButton

	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	... 1 more
    Caused by: android.content.res.Resources$NotFoundException: File build/intermediates/res/merged/debug/drawable/edit.xml from drawable resource ID #0x7f020048
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2428)
	at android.content.res.Resources.loadDrawable(Resources.java:2330)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.internal.Shadow.directlyOn(Shadow.java:44)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:527)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
	at android.widget.ImageView.__constructor__(ImageView.java:146)
	at android.widget.ImageView.<init>(ImageView.java)
	at android.widget.ImageButton.<init>(ImageButton.java)
	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:110)
	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:106)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
    Caused by: java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2418)
	... 38 more
    hannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	... 1 more
    Caused by: android.content.res.Resources$NotFoundException: File build/intermediates/res/merged/debug/drawable/edit.xml from drawable resource ID #0x7f020048
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2428)
	at android.content.res.Resources.loadDrawable(Resources.java:2330)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.internal.Shadow.directlyOn(Shadow.java:44)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:527)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
	at android.widget.ImageView.__constructor__(ImageView.java:146)
	at android.widget.ImageView.<init>(ImageView.java)
	at android.widget.ImageButton.<init>(ImageButton.java)
	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:110)
	at com.github.clans.fab.FloatingActionButton.<init>(FloatingActionButton.java:106)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactory.makeChannelView(DefaultChannelViewFactory.java:19)
	at beartooth.com.grizzly.ui.wrapper.view.legacy.DefaultChannelViewFactoryTest.shouldReturnExistingChannelView(DefaultChannelViewFactoryTest.java:48)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
    Caused by: java.lang.NumberFormatException: multiple points
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at android.util.PathParser.getFloats(PathParser.java:178)
	at android.util.PathParser.createNodesFromPathData(PathParser.java:59)
	at android.graphics.drawable.VectorDrawable$VFullPath.updateStateFromTypedArray(VectorDrawable.java:1439)
	at android.graphics.drawable.VectorDrawable$VFullPath.inflate(VectorDrawable.java:1421)
	at android.graphics.drawable.VectorDrawable.inflateInternal(VectorDrawable.java:542)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:458)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1095)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1017)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2418)
	... 38 more

It seems to be caused by using a vector drawable?

**Comment by masterjefferson** [comment]
Solved by implementing a custom shadow for `VectorDrawable`

**Comment by ksprash** [comment]
Can you please share the code for your custom shadow.

**Comment by DAlexIV** [comment]
@ksprash Here is how I made my shadow 
```java
/*
    Robolectic cant inflate LoadingView for some reason, so we shadow it
 */
@Implements(LoadingView.class)
public class LoadingViewStubShadow extends ShadowView {

    public void __constructor__(Context context) {
        // no-op
    }

    public void __constructor__(Context context, AttributeSet attrs) {
        // no-op
    }
}
```

Also you will need to load it into Robolectric (cause by default it can only shadow Android classes, not yours or the ones, which are in your libraries). The easiest way to do that is override createShadowMap in RobolectricTestRunner like below
```java
 @Override
    protected ShadowMap createShadowMap() {
        return new ShadowMap.Builder()
                .addShadowClass(LoadingView.class, LoadingViewStubShadow.class, true, true, true)
                .build();
    }
```

**Comment by caltseng** [comment]
Do we seriously have to create a new Shadow class for each of our custom views?

**Comment by DAlexIV** [comment]
@caltseng as far I can remember, this inflate exception happened only in couple of all custom views in app, so I guess that you will need to do this only for views that can't be properly inflated by robolectric

**Comment by caltseng** [comment]
It's choking on the style. I created a custom Shado class for the enclosing class, but since this is just an Android widget, I feel like this is a different issue. I've followed your pattern above and created a Shadow class for both ProgressBar (Android widget) and the custom view enclosing it, but this did not solve the problem. 

`Caused by: java.lang.RuntimeException: no value for android:attr/indeterminateProgressStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style ols.microsoft.com.shiftr:Theme_Shiftr (and parents) (forced)]`


```
    <ProgressBar
        android:id="@+id/blocking_progress_bar"
        style="?android:attr/indeterminateProgressStyle"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:indeterminate="true"
        android:interpolator="@android:interpolator/cycle" />
```

**Comment by DAlexIV** [comment]
@caltseng yup, it seems to be something wrong with robolectric and themes, still needs more research

**Comment by caltseng** [comment]
@DAlexIV http://stackoverflow.com/questions/6302867/robolectric-issue-with-progressbar

This seemed to work for style="?android:attr/indeterminateProgressStyle" to style="@android:style/Widget.ProgressBar.Small" made the error go away. Now I just need to make sure that it actually looks corect. I will need to find the correct attribute. 

Thanks for your help. The shadow class knowledge is very handy.

**Comment by DAlexIV** [comment]
@caltseng you are welcome! Unfortunately, testing w/ robolectric sometimes leads to non-trivial workarounds.

**Comment by xian** [comment]
Have you applied a style to the app or activity that declares a value for `android:attr/indeterminateProgressStyle`? Something like:

```java
setTheme(R.style.Widget_ActionBar);
```

@DAlexIV, you can also create a [`robolectric.properties` file](http://robolectric.org/configuring/) with a line like this:
```properties
shadows=com.whatever.LoadingViewStubShadow
```
