### ISSUE TITLE
 IBitmapDescriptorFactory is not initialized

### ISSUE THREAD

**Issue by agonist** [robolectric/robolectric#2159]
I try to run a Robolectric(3.0)  test which contains some related code to google map.

my dependencies : 

```
    testCompile 'org.robolectric:robolectric:3.0'
    testCompile "org.robolectric:shadows-play-services:3.0"
    testCompile "org.robolectric:shadows-multidex:3.0"
    testCompile 'org.robolectric:shadows-maps:3.0'
    testCompile "org.robolectric:shadows-support-v4:3.0"
```

The class I try to test contains : 

`BitmapDescriptorFactory.fromResource(R.drawable.ic_pin_start)`

on this line when I run the test I get : 

```
java.lang.NullPointerException: IBitmapDescriptorFactory is not initialized
    at com.google.android.gms.common.internal.zzx.zzb(Unknown Source)
    at com.google.android.gms.common.internal.zzx.zzb(Unknown Source)
    at com.google.android.gms.maps.model.BitmapDescriptorFactory.zzzt(Unknown Source)
    at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromResource(Unknown Source)
    at com.heetch.util.PreOrderSequencedFlow.initResources(PreOrderSequencedFlow.java:82)
    at com.heetch.util.PreOrderSequencedFlow.<init>(PreOrderSequencedFlow.java:66)
    at com.heetch.flow.preorder.PreOrderSequencesFlowTest.testPreorderFlow(PreOrderSequencesFlowTest.java:45)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

And before my test run I do :  

```
      MapsInitializer.initialize(HeetchApp.getInstance().getApplicationContext());
       ShadowGooglePlayServicesUtil.setIsGooglePlayServicesAvailable(ConnectionResult.SUCCESS);
```

This is where I'm stuck, I don't really know where to go with this.
How my `IBitmapDescriptorFactory` can be initialized ?

Thank's

**Comment by nrxus** [comment]
In case, you (or someone else) is still looking for an answer to this I'll post my findings here.

1. You are setting isGooglePlayServicesAvailable too late. MapsInitializer.initialize will try to initialize the map (and the BitmapDescriptorFactory) but first it checks that google play services is available. 

2. You should add ShadowGooglePlayServices to your config shadows, as described in the : [extending documentation](http://robolectric.org/extending/)
```
@Config(constants = BuildConfig.class,
        shadows = ShadowGooglePlayServicesUtil.class)
```

3. Even with the above "fixes", I still got a null pointer exception but further down the line. What I did instead, is I implemented my own BitmapDescriptorFactory: 

```
@Implements(BitmapDescriptorFactory.class)
    public static class ShadowBitmapDescriptorFactory {

        static int counter = 0;
        static BitmapDescriptor descriptor = new BitmapDescriptor(mock(zzd.class));

        public ShadowBitmapDescriptorFactory() {
        }

        public static void resetCounter() {
            counter = 0;
        }

        @Implementation
        public static BitmapDescriptor fromBitmap(Bitmap image) {
            counter++;
            return descriptor;
        }
    }
```

and then used it in my test class
```
@Config(constants = BuildConfig.class,
        shadows = BitmapDescriptorCacheTest.ShadowBitmapDescriptorFactory.class)
```

In my case, I was testing a caching class for BitmapDescriptorFactory so what I cared about the most was how many times was fromBitmap being called. Depending on what your application is using, you will have to implement different methods of the class. I wish robolectric had a shadow implementation for this class already but I could not find one.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
