### ISSUE TITLE
ShadowResources, OverlayedThemeValue

### ISSUE THREAD

**Issue by OleksandrKucherenko** [robolectric/robolectric#2163]
During executing the test capture interesting behavior/Exception: (Robolectric 3.0)

```
java.lang.NullPointerException
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:160)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:460)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
```

Reason of the exception is that in a application flavor specific style attribute is not defined. Android OS itself well survive that, but Robolectric is not.

So that raise two things:
- please modify ShadowResources.java line 160, and check that overlayed theme value is null
- please add some tracing into class, that will allow to dump into logs such kind of cases

Thanks

**Comment by steineron** [comment]
having similar issue with my fragment's test. following...

**Comment by jffiorillo** [comment]
Having similar issue inflating layout. following...

**Comment by arctouch-rafaelcamargo** [comment]
Having same issue, because i'm using `style="?android:attr/android:progressBarStyleSmall"`. Couldn't figure a solution yet.

**Comment by jongerrish** [comment]
Robolectric 4.0 and binary resource mode has significantly improved resource fidelity, please give that a try and reopen if there is still an issue.
