### ISSUE TITLE
Robolectric incompatible with support library 23.x.x

### ISSUE THREAD

**Issue by mpost** [robolectric/robolectric#2169]
Running any robolectric tests with the design support library 23.x.x, i get the following exception:

```java
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:310)
	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:279)
	at android.support.v7.app.AppCompatDelegateImplV7.initWindowDecorActionBar(AppCompatDelegateImplV7.java:172)
	at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:87)
	at android.support.v7.app.AppCompatDelegateImplV7.onPostResume(AppCompatDelegateImplV7.java:236)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:142)
	at android.app.Activity.performResume(Activity.java:6032)
	at org.robolectric.util.ReflectionHelpers$3.run(ReflectionHelpers.java:162)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:305)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:156)
	at org.robolectric.util.ComponentController$1.run(ComponentController.java:72)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
	at org.robolectric.util.ComponentController.invokeWhilePaused(ComponentController.java:69)
	at org.robolectric.util.ActivityController.resume(ActivityController.java:153)
   ...
```

A similar problem has been reported here https://github.com/robolectric/robolectric/issues/1976#issuecomment-153776024. I am running the tests for a library project and have properly specified the base theme to be `Theme.AppCompat`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.my.app">

    <application android:theme="@style/Theme.AppCompat">
    </application>

</manifest>
```

I have also tried to specify the theme directly in Activity.onCreate():

```java
setTheme( R.style.Theme_AppCompat );
```

None of the above helped to convince the support library, that it is running under the correct theme. The check that is performed by the support library in `android.support.v7.app.AppCompatDelegateImplV7.createSubDecor` is:

```java
    if (!a.hasValue(R.styleable.Theme_windowActionBar)) {
        a.recycle();
        throw new IllegalStateException(
                "You need to use a Theme.AppCompat theme (or descendant) with this activity.");
    }
```

Tests are run on robolectric 3.0 but i also get the same result on 3.1-SNAPSHOT. The app performs flawlessly when running on a regular device.

Any ideas on how to run robolectric tests when using the support library 23?

**Comment by mpost** [comment]
Apparently it was the missing R file of the design support library (packages as an .aar). A common problem when working with robolectric. I have added it in a gradle build step and now the resources are found as expected.

**Comment by emartynov** [comment]
How did you add it?

I have similar problem with next setup:
```public class AboutActivity extends BaseActivity {}```
```public abstract class BasActivity extends AppCompatActivity {}```

My test passes as soon as I do next changes
```public AboutActivity extends AppCompatActivity{}```
and move some code from ```BaseActivity``` to ```AboutActivity```.

**Comment by mpost** [comment]
@emartynov Similarly to here: https://github.com/robolectric/robolectric/issues/1737#issuecomment-121318761
