### ISSUE TITLE
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar

### ISSUE THREAD

**Issue by chdryra** [robolectric/robolectric#2171]
Trying to use Roboelectric for the first time have above issue. Doesn't like space character in "User 1" in path.

**Comment by jaredsburrows** [comment]
Could you give any more details?

**Comment by chdryra** [comment]
Hi thanks for replying. Here are some details - hope they help:
* Windows 7 64-bit.
* Android Studio 1.5
* Add the following to my Gradle script: testCompile 'org.robolectric:robolectric:3.0'
* This downloads Robolectric to C:\Users\User 1\.m2\repository\org\robolectric.
* Try running the following simple test:

    
    @RunWith(RobolectricTestRunner.class)
    public class RobolectricTest {

        @Test
        public void runTest() {
            assertThat(1, is(1));
        }
    }

* Get the following stack trace:
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
	at org.robolectric.res.Fs.fromJar(Fs.java:34)
	at org.robolectric.internal.SdkEnvironment.createSystemResourceLoader(SdkEnvironment.java:27)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceLoader(SdkEnvironment.java:40)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:239)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)

java.lang.RuntimeException: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:244)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
	at org.robolectric.res.Fs.fromJar(Fs.java:34)
	at org.robolectric.internal.SdkEnvironment.createSystemResourceLoader(SdkEnvironment.java:27)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceLoader(SdkEnvironment.java:40)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:239)
	... 18 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at java.net.URL.toURI(URL.java:938)
	at org.robolectric.res.Fs.fromJar(Fs.java:29)
	... 21 more

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.net.URISyntaxException: Illegal character in path at index 19: file:/C:/Users/User 1/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at java.net.URL.toURI(URL.java:938)
	at org.robolectric.res.Fs.fromJar(Fs.java:29)
	... 21 more

It seems that Robolectric doesn't like spaces in the file path. In windows this is hard to avoid I think so wondered if there was a solution as very keen on trying out Robolectric for my code base.

Thanks,
Riz

**Comment by jaredsburrows** [comment]
This is similar to https://github.com/robolectric/robolectric/issues/1363

**Comment by chdryra** [comment]
Yes but unfortunately that issue was deemed closed without a solution. I
was hoping for a solution.

**Comment by erd** [comment]
Have you tried 3.1-SNAPSHOT? I merged #2100 which attempted to fix the issue (I don't have a Windows machine to test on).

**Comment by chdryra** [comment]
Thanks for your reply. Is 3.1 SNAPSHOT something I can simply include in my gradle build or do I need to pull the code from a repo and compile?

**Comment by chdryra** [comment]
I've tried testCompile "org.robolectric:robolectric:3.1-SNAPSHOT" but get failed to resolve error...

**Comment by jaredsburrows** [comment]
@chdryra Are you still seeing this with `3.1.1`?

**Comment by chdryra** [comment]
No at some point it started working so I think the snapshot fixed it.
However I haven't run roboelectric tests in a while so would have to double
check.
