### ISSUE TITLE
ShadowAudioManager should implement registerMediaButtonEventReceiver

### ISSUE THREAD

**Issue by ened** [robolectric/robolectric#2173]
Right now, `MediaSession.setActive(boolean)` will fail with a NPE like this:

```
java.lang.NullPointerException
    at android.media.AudioManager.registerMediaButtonEventReceiver(AudioManager.java:2122)
    at android.support.v4.media.session.MediaSessionCompatApi18.registerMediaButtonEventReceiver(MediaSessionCompatApi18.java:57)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.update(MediaSessionCompat.java:1349)
    at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase.setActive(MediaSessionCompat.java:1212)
    at android.support.v4.media.session.MediaSessionCompat.setActive(MediaSessionCompat.java:297)
```

**Comment by utzcoz** [comment]
@ened Please try the latest Robolectric, and feel free to reopen this issue if it still exists and you still want to support this method. Thanks.
