### ISSUE TITLE
Instant Run gradle:2.0.0-alpha2 problem

### ISSUE THREAD

**Issue by sibeliusseraphini** [robolectric/robolectric#2180]
This problem - https://code.google.com/p/android/issues/detail?id=194996 is still happening on gradle 2 alpha2
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Could not find a class for package: com.example and class name: com.android.tools.fd.runtime.BootstrapApplication
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:61)
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:15)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:115)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:443)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:247)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: Could not find a class for package: com.example and class name: com.android.tools.fd.runtime.BootstrapApplication
	at org.robolectric.internal.ClassNameResolver.resolve(ClassNameResolver.java:25)
	at org.robolectric.DefaultTestLifecycle.createApplication(DefaultTestLifecycle.java:59)
	... 22 more
```

Is there any workaround?

**Comment by sibeliusseraphini** [comment]
The workaround that I've found is to disable Instant Run or change the buildvariant to release

**Comment by sibeliusseraphini** [comment]
Another workaround is to set

```
@Config(application = MyApplication.class)
```

**Comment by swolfand** [comment]
That worked great thanks
