### ISSUE TITLE
FileProvider.getUriForFile NullPointerException during tests

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#2199]
## Code:
```
public Uri method(final Activity activity, final File file) {
    return FileProvider.getUriForFile(activity,
                activity.getString(R.string.file_provider_authority),
                file);
}
```

## Test error (calls method above):
```
Test > test FAILED
    java.lang.NullPointerException
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:560)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:534)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:376)
        at <>.method(Util.java:79)
        at <>.onOptionsItemSelected(Fragment.java:292)
        at <>.method(Test.java:66)

1 failed
```

## File provider in AndroidManifest.xml:
```
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="@string/file_provider_authority"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/fileprovider_paths" />
        </provider>
```
## Paths in /xml:
```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <files-path
        name="files"
        path="." />
</paths>
```
Does Robolectric not look at the providers? The issue seems to be with `FileProvider.getUriForFile`.

**Comment by erd** [comment]
Robolectric does parse content providers from your manifest and make them available. There's probably some API used by `FileProvider.parsePathStrategy` that we don't support yet.

**Comment by JavierSP1209** [comment]
Hi! I had the same issue, what I did, was create a Shadow of the FileProvider and create a Uri, with the values I needed... It's not the best, but is a work around.

**Comment by jaredsburrows** [comment]
@JavierSP1209 Can you submit a PR of your Shadow?

**Comment by florian-kriener** [comment]
The problem is that `PackageManager#resolveContentProvider` always returns `null`.

**Comment by Werb** [comment]
@florian-kriener  why `PackageManager#resolveContentProvider` always returns null ?

**Comment by jaredsburrows** [comment]
@JavierSP1209 Submit PR?

**Comment by gmk57** [comment]
I had similar issue while [testing](https://github.com/gmk57/ya-photos/blob/09fc79f6ce556744d235fb12dbbd5a539fc3e55a/app/src/test/java/gmk57/yaphotos/ImageFileProviderRoboTest.java) logic in `query` method of [my FileProvider subclass](https://github.com/gmk57/ya-photos/blob/09fc79f6ce556744d235fb12dbbd5a539fc3e55a/app/src/main/java/gmk57/yaphotos/ImageFileProvider.java). Following [idea of **JavierSP1209**](https://github.com/robolectric/robolectric/issues/2199#issuecomment-208976402) and [documentation](http://robolectric.org/extending/), solved it by creating a [Shadow of FileProvider](https://github.com/gmk57/ya-photos/blob/09fc79f6ce556744d235fb12dbbd5a539fc3e55a/app/src/test/java/gmk57/yaphotos/ShadowFileProvider.java).

Essentially this means mocking calls to superclass methods with same name (something Mockito can't do, AFAIK). Not sure if this is intended use of Robolectric, but for my use case it worked fine. Hope this helps someone.

**Comment by MrHadiSatrio** [comment]
Thanks for the leads @JavierSP1209 and @gmk57. 👍🏽 

For those who are looking for a solution specifically related to `FileProvider#getUriForFile`, I want to share the code snippet below:

```kotlin
@RunWith(AndroidJUnit4::class)
@Config(shadows = [ShadowFileProvider::class])
class YourTestClass {

    @Test
    fun test() {
        // Test the flow which relies on FileProvider#getUriForFile here...
    }
}

@Suppress("UtilityClassWithPublicConstructor")
@Implements(FileProvider::class)
internal class ShadowFileProvider {

    companion object {

        @Suppress("UnusedParameter")
        @JvmStatic
        @Implementation
        fun getUriForFile(context: Context, authority: String, file: File): Uri {
            return Uri.parse("content://$authority/${file.name}")
        }
    }
}
```

**Comment by utzcoz** [comment]
@MrHadiSatrio Would you like to send a PR to support `FileProvider#getUriForFile`?
