### ISSUE TITLE
PowerMock broken with Robolectric 3.1+

### ISSUE THREAD

**Issue by karlicoss** [robolectric/robolectric#2208]
Turns out 3.0 worked fine, so it broke quite recently. I've created a simple demo project: https://github.com/karlicoss/RobolectricPowermock

It fails with the following exception:

```
com.thoughtworks.xstream.converters.ConversionException: Cannot convert type org.apache.tools.ant.Project to type org.apache.tools.ant.Project
---- Debugging information ----
class               : org.apache.tools.ant.Project$1
required-type       : org.apache.tools.ant.Project$1
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/this$1/outer-class/dependencyResolver/dependencyResolver/project/isLoggingMessage/outer-class
line number         : 198
class[1]            : org.apache.tools.ant.Project
class[2]            : org.robolectric.internal.dependency.MavenDependencyResolver
class[3]            : org.robolectric.internal.dependency.CachedDependencyResolver
class[4]            : org.robolectric.RobolectricGradleTestRunner
class[5]            : org.robolectric.RobolectricTestRunner$HelperTestRunner
class[6]            : org.robolectric.RobolectricTestRunner$HelperTestRunner$1
class[7]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[8]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available
-------------------------------
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:439)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:480)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:412)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1206)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1190)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1061)
    at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1052)
    at org.powermock.classloading.DeepCloner.clone(DeepCloner.java:54)
    at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:89)
    at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
    at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:49)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:255)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:185)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:151)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by karlicoss** [comment]
Ok so I think I bisected the commit responsible for this regression: c4d5d29fa4c054857708a13d90b16dbfa95ff4cb (PR https://github.com/robolectric/robolectric/pull/2039)

**Comment by karlicoss** [comment]
Apparently, this is somehow related https://github.com/robolectric/robolectric/issues/2153

**Comment by hzsweers** [comment]
@erd @jongerrish is anyone looking into this? Would be a dealbreaker for a lot of people considering how many static classes android has (Compat classes, BuildConfig, etc)

**Comment by jongerrish** [comment]
@hzsweers I think we should make Robolectric support PowerMock. For code outside the Android framework certainly. For code inside the Framework using PowerMock shouldn't be necessary if there is adequate shadow support. Can you give some examples of when you'd like to use PowerMock on the Android framework?

My feeling is that if possible refactor your own code to use DI and Mockito where possible. In cases where this is not possible use PowerMock. For Framework code, Robolectric shadows.

I don't know if anyone is working on this, I guess it needs someone to step up and volunteer ;-)

**Comment by karlicoss** [comment]
@jongerrish I tried fixing it, but apparently it didn't work. Although, there are couple questions about Robolectric internals in the PR comments https://github.com/robolectric/robolectric/pull/2213, so if you could elaborate on them, would be great, it might help me to figure out what exactly broke it.

Also, look at this test https://github.com/robolectric/robolectric/pull/2213/files#diff-ca1cf49ca80a766d69778b93b3d16db9R1. It doesn't try to invoke Powermock on Robolectric-instrumented classes, so it looks broken for all classes if your tests using Robolectric runner.

**Comment by karlicoss** [comment]
@hzsweers I guess I finally fixed that :D https://github.com/robolectric/robolectric/pull/2390
@jongerrish could you please take a look?

**Comment by marklapasa** [comment]
+1 Please fix

**Comment by marklapasa** [comment]
@jongerrish: "For code inside the Framework using PowerMock shouldn't be necessary if there is adequate shadow support."

I am trying to use PowerMock/Robolectric with java.security.KeyStore. There has been no support for KeyStore for a long time now.

**Comment by jongerrish** [comment]
Correct. You should not need to mock, regular Mockito or power mock
framework methods. If there is missing support for keystore we'd welcome a
pull request to add it :-)

**Comment by Russel-Zhang** [comment]
@marklapasa 
Have you tried to ingnore the "javax.crypto.* package"?
`@RunWith(RobolectricTestRunner.class)
@PowerMockIgnore({ "org.mockito.*", "org.robolectric.*", "android.*", "javax.crypto.*" })
@PrepareForTest(YourStatic.class)`

**Comment by dhirenmudgil** [comment]
Please fix. As i am using clover sdk and there is a static class to this which i need to mock.

**Comment by liupengking1** [comment]
+1 Please fix

**Comment by poldz123** [comment]
+1

**Comment by ending0421** [comment]
+1

**Comment by jamesneville** [comment]
+1 to fix this, please.

**Comment by CoderSpinoza** [comment]
+1 to fix this!

**Comment by YorkShen** [comment]
+1 to fix this, pls

**Comment by epool** [comment]
I still getting a similar error on `3.1.3`:
```
com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : Failed calling method
method              : org.apache.tools.ant.Project$AntRefTable.writeObject()
-------------------------------

	at com.thoughtworks.xstream.core.util.SerializationMembers.callWriteObject(SerializationMembers.java:151)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:257)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
...
```

**Comment by daniellAlgar** [comment]
Same here on `3.1.4`

    com.thoughtworks.xstream.converters.ConversionException: Cannot convert type org.apache.tools.ant.Project to type org.apache.tools.ant.Project
    ---- Debugging information ----
    class               : org.apache.tools.ant.Project$1
    required-type       : org.apache.tools.ant.Project$1
    converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
    path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/next/this$1/outer-class/dependencyResolver/dependencyResolver/project/isLoggingMessage/outer-class
    line number         : 331
    class[1]            : org.apache.tools.ant.Project
    class[2]            : org.robolectric.internal.dependency.MavenDependencyResolver
    class[3]            : org.robolectric.internal.dependency.CachedDependencyResolver
    class[4]            : org.robolectric.RobolectricTestRunner
    class[5]            : org.robolectric.RobolectricTestRunner$HelperTestRunner
    class[6]            : org.robolectric.RobolectricTestRunner$HelperTestRunner$1
    class[7]            : org.junit.internal.runners.statements.RunBefores
    class[8]            : org.powermock.modules.junit4.rule.PowerMockStatement
    class[9]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
    version             : not available
    -------------------------------

	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:439)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:263)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    ...

**Comment by bartoszwilk** [comment]
+1

**Comment by itanoss** [comment]
+1

**Comment by kmenager** [comment]
I've got the same issue with Realm and Unit test.
I just change the @PowerMockIgnore 
from
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
to 
@PowerMockIgnore({"org.mockito.*", "android.*"})

And now, I can run my Realm static test with powermock
Hope this help pending a new release.

**Comment by abhikmitra** [comment]
+!

**Comment by xian** [comment]
Deduping: https://github.com/robolectric/robolectric/issues/2677

**Comment by xian** [comment]
Example at https://github.com/robolectric/robolectric/tree/fix-powermock

**Comment by daidai513260** [comment]
I'm not sure if this issue get fixed, but I still got the same error message under org.robolectric:robolectric:3.2.2

**Comment by juanmendez** [comment]
I am seeing this error, and goes away if I use testCompile "org.robolectric:robolectric:3.0"

`@RunWith(RobolectricGradleTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@SuppressStaticInitializationFor("io.realm.internal.Util")
@PrepareForTest({Realm.class, RealmConfiguration.class, RealmQuery.class, RealmLog.class, RealmResults.class, RealmCore.class, RealmLog.class, RealmObject.class })
public class RobolecticTest{

    @Rule
    public PowerMockRule rule = new PowerMockRule();`

**Comment by benmarten** [comment]
Still running into this issue; Any insights?

**Comment by xian** [comment]
Fixed on master. We'll be rolling up a release very soon.

**Comment by sumanharman** [comment]
@xian Is the fix rolled out ?

**Comment by jongerrish** [comment]
Committed, but not released. We'll push out 3.3 this week.

On Feb 27, 2017 3:25 AM, "sumanharman" <notifications@github.com> wrote:

@xian <https://github.com/xian> Is the fix rolled out ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/2208#issuecomment-282694968>,
or mute the thread
