### ISSUE TITLE
java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)

### ISSUE THREAD

**Issue by DariusL** [robolectric/robolectric#2229]
I get this exception when I try to use the Facebook SDK in a Robolectric test. 

```
java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)

at com.facebook.GraphResponse.fromHttpConnection(GraphResponse.java:280)
at com.facebook.GraphRequest.executeConnectionAndWait(GraphRequest.java:1130)
at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1032)
at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:999)
at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:983)
at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:958)
at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:854)
... my code

Caused by: java.net.ProtocolException: cannot write to a URLConnection if doOutput=false - call setDoOutput(true)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1263)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1256)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1465)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
at com.facebook.GraphResponse.fromHttpConnection(GraphResponse.java:253)
```

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
