### ISSUE TITLE
android.text.PackedIntVector.getValue throwing java.lang.IndexOutOfBoundsException after ShadowMessageQueue dispatchMessage

### ISSUE THREAD

**Issue by NicoloParolini** [robolectric/robolectric#2286]
Hi, Using 3.1-SNAPSHOT, while running tests I get many failures on apparently unrelated tests, however they all narrow down to a ShadowMessageQueue executing a dispatchMessage. An example is below:

    java.lang.IndexOutOfBoundsException: 1, 0
        at android.text.PackedIntVector.getValue(PackedIntVector.java:71)
        at android.text.DynamicLayout.getLineStart(DynamicLayout.java:612)
        at android.text.Layout.getLineEnd(Layout.java:1208)
        at android.text.Layout.getParagraphAlignment(Layout.java:1559)
        at android.widget.TextView.bringPointIntoView(TextView.java:7280)
        at android.widget.TextView.onPreDraw(TextView.java:5228)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
        at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
        at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:113)
        at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:335)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:237)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:218)
        at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:201)
        at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:78)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:112)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:291)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:342)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
        at org.robolectric.util.ActivityController.visible(ActivityController.java:178)

This seems to be related to ShadowActivity as the tests I see failing are using it.

**Comment by jongerrish** [comment]
Is this on API 23? It's been fixed at head. Can dig up the commit when I
get to work.

**Comment by NicoloParolini** [comment]
I've rebuilt the shadows for 23 with the latest snapshot and indeed the problem has been fixed. Thank you.
