### ISSUE TITLE
ShadowBroadcastReceiver problem reproduced with full gist example

### ISSUE THREAD

**Issue by leviyehonatan** [robolectric/robolectric#2293]
I am trying to test this scenario with no luck, a picture worths more than a thousand words. this would be very nice to be able to test for me.

https://gist.github.com/leviyehonatan/bd8730df455b48e63eec

the reason the error arises is an assertion which is not necessary in the shadow class, it cannot be bypassed since i can not provide an alternative as the shadow is being used in ShadowApplication i believe.

will really appreciate any help to be able to write a complete test for my code

the exception is:

java.lang.IllegalStateException: Broadcast already finished
    at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
    at org.robolectric.shadows.ShadowBroadcastPendingResult.finish(ShadowBroadcastPendingResult.java:35)
    at android.content.BroadcastReceiver$PendingResult.finish(BroadcastReceiver.java)
    at org.robolectric.shadows.ShadowBroadcastReceiver.onReceive(ShadowBroadcastReceiver.java:40)
    at org.robolectric.shadows.ShadowApplication$6$1.run(ShadowApplication.java:550)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
    at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
    at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:105)
    at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:335)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:237)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:218)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:201)
    at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:308)
    at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
    at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
    at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
    at android.os.Handler.enqueueMessage(Handler.java:631)
    at android.os.Handler.sendMessageAtTime(Handler.java:600)
    at android.os.Handler.sendMessageDelayed(Handler.java:570)
    at android.os.Handler.post(Handler.java:326)
    at org.robolectric.shadows.ShadowApplication.postIntent(ShadowApplication.java:492)
    at org.robolectric.shadows.ShadowApplication.postToWrappers(ShadowApplication.java:504)
    at org.robolectric.shadows.ShadowApplication.sendBroadcastWithPermission(ShadowApplication.java:594)
    at org.robolectric.shadows.ShadowApplication.sendBroadcast(ShadowApplication.java:440)
    at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java)
    at com.test.TestBroadcast.test(TestBroadcast.java:24)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:553)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:258)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:154)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by leviyehonatan** [comment]
can i get a comment from one of the gurus?

**Comment by leviyehonatan** [comment]
have any one reviewed this?

**Comment by karlicoss** [comment]
@leviyehonatan for starters, which version of Robolectric do you use (did you try testing against snapshot)?

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
