### ISSUE TITLE
Headless support in robolectric. ShadowBitmapFactory is not constructed

### ISSUE THREAD

**Issue by ahtokca** [robolectric/robolectric#2295]
Does robolectric 3.0 works in headless env ?

java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

java.lang.UnsatisfiedLinkError: /data/jenkins/tools/hudson.model.JDK/AUTO_JDK_1_7/jre/lib/amd64/xawt/libmawt.so: libXtst.so.6: cannot open shared object file: No such file or directory
         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
         at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
         at java.lang.Runtime.load0(Runtime.java:795)
         at java.lang.System.load(System.java:1062)
         at java.lang.ClassLoader$NativeLibrary.load(Native Method)
         at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1872)
         at java.lang.Runtime.loadLibrary0(Runtime.java:849)
         at java.lang.System.loadLibrary(System.java:1088)
         at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
         at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
         at java.security.AccessController.doPrivileged(Native Method)
         at java.awt.Toolkit.loadLibraries(Toolkit.java:1653)
         at java.awt.Toolkit.<clinit>(Toolkit.java:1682)
         at sun.awt.AppContext$2.run(AppContext.java:274)
         at sun.awt.AppContext$2.run(AppContext.java:263)
         at java.security.AccessController.doPrivileged(Native Method)
         at sun.awt.AppContext.initMainAppContext(AppContext.java:263)
         at sun.awt.AppContext.access$400(AppContext.java:133)
         at sun.awt.AppContext$3.run(AppContext.java:318)
         at sun.awt.AppContext$3.run(AppContext.java:301)
         at java.security.AccessController.doPrivileged(Native Method)
         at sun.awt.AppContext.getAppContext(AppContext.java:300)
         at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:154)
         at javax.imageio.ImageIO.<clinit>(ImageIO.java:65)
         at org.robolectric.shadows.ShadowBitmapFactory.<clinit>(ShadowBitmapFactory.java:48)
         at org.robolectric.Shadows.reset(Shadows.java:1588)
         at org.robolectric.Robolectric.reset(Robolectric.java:22)
         at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:43)
         at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:233)
         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
         at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
         at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
         at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:606)
         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
         at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at java.lang.reflect.Method.invoke(Method.java:606)
         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
         at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
         at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
         at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
         at java.lang.Thread.run(Thread.java:745)

**Comment by jaredsburrows** [comment]
Robolectric does work in a head less environment. I run everything via command line. Also, this is 2016, please upgrade to JDK 1.8 :)

**Comment by ahtokca** [comment]
So it's not working on java 1.7...

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
