### ISSUE TITLE
MultipleArtifactsNotFoundException depending on 3.1-SNAPSHOT using Gradle

### ISSUE THREAD

**Issue by sjudd** [robolectric/robolectric#2321]
You can reproduce by

1. ``git clone https://github.com/bumptech/glide.git``
2. Update the [Robolectric version][1] to ``3.1-SNAPSHOT``
3. ./gradlew build

The primary error appears to be:

```
Unable to resolve artifact: Missing:
----------
1) org.robolectric:robolectric-resources:jar:3.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=robolectric-resources -Dversion=3.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=robolectric-resources -Dversion=3.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:18:3.1-SNAPSHOT
  	3) org.robolectric:robolectric-resources:jar:3.1-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.apache.maven:super-pom:pom:2.0

from the specified remote repositories:
  sonatype (https://oss.sonatype.org/content/groups/public/),
  central (http://repo1.maven.org/maven2)


	at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:268)
	at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:168)
	at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:52)
	at org.robolectric.internal.dependency.CachedDependencyResolver.getLocalArtifactUrls(CachedDependencyResolver.java:43)
	at org.robolectric.internal.InstrumentingClassLoaderFactory.getSdkEnvironment(InstrumentingClassLoaderFactory.java:42)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:187)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:154)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
----------
1) org.robolectric:robolectric-resources:jar:3.1-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.robolectric -DartifactId=robolectric-resources -Dversion=3.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=robolectric-resources -Dversion=3.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
  	1) org.apache.maven:super-pom:pom:2.0
  	2) org.robolectric:shadows-core:jar:18:3.1-SNAPSHOT
  	3) org.robolectric:robolectric-resources:jar:3.1-SNAPSHOT
```

[1]: https://github.com/bumptech/glide/blob/master/gradle.properties#L30

**Comment by dampcake** [comment]
It's not searching the snapshot repository. Need this:
```gradle
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
```

**Comment by NicoloParolini** [comment]
Same issue here

**Comment by sjudd** [comment]
Not able to reproduce, it was either transient or a configuration problem.

**Comment by NicoloParolini** [comment]
Additional info (problem still there)
if I use 3.0  testCompile('org.robolectric:robolectric:3.0') verything works as expected (API 23 unsupported exceptions is thrown).
if I use 3.1-SNAPSHOT testCompile('org.robolectric:robolectric:3.1-SNAPSHOT') the above exception is thrown when trying to run any test that makes use of shadows.
No other changes where made to any of the project files, which already include
maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        } 
as respository.
Cache has been cleaned by deleting .m2/repository/ and .gradle/caches/
Is there any additional step that should be made? As said, this was not happening until I cleaned out the maven cache.

**Comment by NicoloParolini** [comment]
After careful investigation, the problem appears to be related to threaded tests. To easily reproduce create a new project with a single activity and button (like the one described here: http://robolectric.org/writing-a-test/). Clear maven and gradle caches (~/.gradle/chaches and ~/m2/repository). Then duplicate the test (I made 30 of them) and run. It will crash ranting about artifacts not found, but the full stacktrace will tell that it was interrupted while reading a pom file.

This apparently happens only when building for API 23.

Might very well be a gradle issue, just replying here in case someone looks for this bug.

**Comment by NicoloParolini** [comment]
Bumping up as it still keeps happening, and it is not a Gradle bug.

**Comment by vpalivela** [comment]
@NicoloParolini I've had the same issue come up using API 23. I fixed it by setting proxy settings in the build.gradle

```java
afterEvaluate {
    project.tasks.withType(Test) {
        systemProperties.put('proxySet', true)
        systemProperties.put('proxyHost', 'someproxy.com')
        systemProperties.put('proxyPort', 80)
    }
}
```

Roboelectric test runner downloads shadow android jars at runtime and this doesn't use the gradle settings. Here is an article which describes an alternative if you still can't get it working or want a different approach: [http://codeblast.com/2015/05/13/using-robolectric-in-offline-mode/](http://codeblast.com/2015/05/13/using-robolectric-in-offline-mode/)

**Comment by ber4444** [comment]
Only way I could fix this is by disconnecting from our VPN just to run the robolectric test. Definitely the bug is that it fails to read from the global gradle setting where I configured the VPN.
