### ISSUE TITLE
Rebolectric 3.0 android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by beautifulSoup** [robolectric/robolectric#2322]
I'm using robolectric to do unittest in my android project. My APPLICATION_ID is different from PackageName. So I follow the advice of the issues in robolectric github to make it work. Here is what I do.  
First, I create a test runner 

```
public class CustomRobolectricRunner extends RobolectricGradleTestRunner {

public CustomRobolectricRunner(Class<?> klass) throws InitializationError {
    super(klass);
}

protected AndroidManifest getAppManifest(Config config) {
    AndroidManifest appManifest = super.getAppManifest(config);
    FsFile androidManifestFile = appManifest.getAndroidManifestFile();
    String packageName = config.packageName();
    if (androidManifestFile.exists()) {
        return appManifest;
    } else {
        String moduleRoot = getModuleRootPath(config);
        androidManifestFile = FileFsFile.from(moduleRoot, appManifest.getAndroidManifestFile().getPath().replace("bundles", "manifests/full"));
        FsFile resDirectory = FileFsFile.from(moduleRoot, appManifest.getResDirectory().getPath().replace("/res", "").replace("bundles", "res/merged"));
        FsFile assetsDirectory = FileFsFile.from(moduleRoot, appManifest.getAssetsDirectory().getPath().replace("/assets", "").replace("bundles", "assets"));
        return new AndroidManifest(androidManifestFile, resDirectory, assetsDirectory);
    }
}

private String getModuleRootPath(Config config) {
    String moduleRoot = config.constants().getResource("").toString().replace("file:", "");
    return moduleRoot.substring(0, moduleRoot.indexOf("/build"));
}
}
```

Secondly, I create a config file, in test/resources. I set the packageName to my real packageName.

```
packageName=cn.campusapp.campus
sdk=21
shadows=ui.robolectric.ShadowMultiDex
constants=cn.campusapp.campus.BuildConfig
application = ui.TestApplication
```

But when i run the test. it report error as 

```
android.content.res.Resources$NotFoundException: no such label cn.campusapp.forum:string/app_name
at org.robolectric.util.ActivityController.getActivityTitle(ActivityController.java:104)
at org.robolectric.util.ActivityController.attach(ActivityController.java:49)
at org.robolectric.util.ActivityController$1.run(ActivityController.java:121)
at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:304)
at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:45)
at org.robolectric.util.ActivityController.create(ActivityController.java:118)
at org.robolectric.util.ActivityController.create(ActivityController.java:129)
at org.robolectric.util.ActivityController.setup(ActivityController.java:210)
at org.robolectric.Robolectric.setupActivity(Robolectric.java:46)
at ui.VerifyActivityTest.testLogin(VerifyActivityTest.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:251)
at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Obviously, it's going to find the app_name string as the packageName-cn.campusapp.forum, which is my APPLICATION_ID. In other word, my config of packagename not work. I use the robolectric 3.0. Anybody can help me! Thanks. If i set the APPLICATION_ID the same as my PACKAGENAME. It works. But that's not good for me.

**Comment by jaredsburrows** [comment]
@beautifulSoup Use the latest Robolectric. You do not have to create your own to find your package id anymore.

**Comment by IgorGanapolsky** [comment]
@jaredsburrows In Android Studio 3.0 Beta3, using com.android.tools.build:gradle:2.2.3, I get this error:
> android.content.res.Resources$NotFoundException: Unable to find resource ID #0x0 in packages [android, org.robolectric.default]

**Comment by jongerrish** [comment]
It is not finding your resources directory.

You'll either need to use the new AGP 3.0 integration (use build tools
3.0+) or the existing integration which is ad-hoc and works on build tools
< 3.0 e.g: 2.3 that you are using...

http://robolectric.org/getting-started/

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
