### ISSUE TITLE
java.lang.IllegalStateException: "com.**.**:@attr/**" unexpected

### ISSUE THREAD

**Issue by alexwang3322** [robolectric/robolectric#2354]
java.lang.IllegalStateException: "com.**.**:@attr/**" unexpected
	at org.robolectric.res.Attribute.<init>(Attribute.java:90)
	at org.robolectric.res.StyleResourceLoader.processNode(StyleResourceLoader.java:32)
	at org.robolectric.res.XpathResourceXmlLoader.processResourceXml(XpathResourceXmlLoader.java:22)
	at org.robolectric.res.XmlLoader.processResourceXml(XmlLoader.java:46)
	at org.robolectric.res.DocumentLoader.loadResourceXmlFile(DocumentLoader.java:47)
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:40)

com.**.** is my package name.
attr/** is my project resource. 

I can't run unit test,because it throw a exception.In the class `org.robolectric.res.Attribute` executes the method `Attribute(..)` and `!resName.type.equals("attr")` equals true, and `resName.type` equals `@attr`.
So I am confusing this problem is a bug or I am not right with using robolectric at some point?
And same question show at [http://stackoverflow.com/questions/24999471/how-do-i-configure-roboattributeset-for-a-custom-view-in-robolectric](url).no one give a solve.

Hope give me a sovle or help.
Thanks a lot!

**Comment by marcoRS** [comment]
I'm getting a similar error on 3.3.2. Did you ever resolve this?
