### ISSUE TITLE
NullPointerException when accessing getString(int resId) while calling Service.onCreate()

### ISSUE THREAD

**Issue by NicoloParolini** [robolectric/robolectric#2358]
Given this Service:

```
package com.robolectrictest.robotest;

import android.app.Service;
import android.content.Intent;
import android.os.IBinder;

public class MyService extends Service {

    @Override
    public void onCreate() {
        super.onCreate();

        String appname = getString(R.string.app_name);
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}
```

and this test:

```
package com.robolectrictest.robotest;

import junit.framework.Assert;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;

    /**
     * To work on unit tests, switch the Test Artifact in the Build Variants view.
     */
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class ExampleUnitTest1 {
        @Test
        public void addition_isCorrect1_1() throws Exception {
            MyService service = new MyService();
            service.onCreate();
            Assert.assertTrue(true);
        }
    }
```

Test should succeed, but instead it fails with the following exception:

```
java.lang.NullPointerException
    at android.content.ContextWrapper.getResources(ContextWrapper.java:81)
    at android.content.Context.getString(Context.java:292)
    at com.robolectrictest.robotest.MyService.onCreate(MyService.java:13)
    at com.robolectrictest.robotest.ExampleUnitTest1.addition_isCorrect1_1(ExampleUnitTest1.java:19)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:553)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:258)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:154)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

```

Failure recorded with 3.1-SNAPSHOT from today 14th of March. succeeds on 3.0.

**Comment by jongerrish** [comment]
You need to attach() your service to the base context, using the
ServiceController. This is due to a big exposed in the service controller
from a recent PR I submitted that removes shadow code from ContextWrapper.

ActivityController calls attach() automatically for you in onCreate()
ServiceController doesn't. We should change that but in the meantime you
can call this manually.

**Comment by NicoloParolini** [comment]
Confirmed it works if manually attached. Thank you.

**Comment by jongerrish** [comment]
I think ServiceController now does the right thing
