### ISSUE TITLE
ShadowDefaultRequestDirector has null redirector

### ISSUE THREAD

**Issue by francisdb** [robolectric/robolectric#240]
the ShadowDefaultRequestDirector `__constructor__` is never called causing redirector to be null and execute to fail when using `Robolectric.getFakeHttpLayer().interceptHttpRequests(false);`

Not sure why this happens but my breakpoints in the  `__constructor__` are never reached

``` java
@Before
    public void setup() throws ClientProtocolException, IOException{
        Robolectric.getFakeHttpLayer().interceptHttpRequests(false);
        DefaultHttpClient client = new DefaultHttpClient();
        HttpResponse response = client.execute(new HttpGet("http://google.com"));
    }
```

this fails with 

```
java.lang.NullPointerException
    at com.xtremelabs.robolectric.shadows.ShadowDefaultRequestDirector.execute(ShadowDefaultRequestDirector.java:151)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
    at xxxxxxxntegrationTest.setup(xxxIntegrationTest.java:27)
```

**Comment by mwiesiolek** [comment]
Hi Guys,

if you are still facing with the issue then bellow you can find the solution:

The problem is that ShadowDefaultRequestDirectory has incorrectly defined types for the following three parameters in __\_\_constructor\_\___ method:

```java
HttpRequestRetryHandler retryHandler,
RedirectHandler redirectHandler,
AuthenticationHandler targetAuthHandler,
```

The types which are provided by Roboelectric are:

```java
org.apache.http.client.RedirectStrategy redirectHandler,
org.apache.http.client.AuthenticationStrategy targetAuthHandler,
org.apache.http.client.AuthenticationStrategy proxyAuthHandler,
```

Roboelectric cannot find the __\_\_constructor\_\___ method due to the other types that are provided. In result, the method is not invoked at all.

Below you can find the working solution:

Add the ShadowDefaultRequestDirectory class which the one below:

```java
@Implements(DefaultRequestDirector.class)
public class MyShadowDefaultRequestDirectory {

    @RealObject
    private DefaultRequestDirector realObject;

    private com.xtremelabs.robolectric.tester.org.apache.http.impl.client.DefaultRequestDirector redirector;

    public MyShadowDefaultRequestDirectory() {
        //roboelectric needs it
    }

    public void __constructor__(org.apache.commons.logging.Log log,
                                org.apache.http.protocol.HttpRequestExecutor requestExec,
                                org.apache.http.conn.ClientConnectionManager conman,
                                org.apache.http.ConnectionReuseStrategy reustrat,
                                org.apache.http.conn.ConnectionKeepAliveStrategy kastrat,
                                org.apache.http.conn.routing.HttpRoutePlanner rouplan,
                                org.apache.http.protocol.HttpProcessor httpProcessor,
                                org.apache.http.client.HttpRequestRetryHandler retryHandler,
                                org.apache.http.client.RedirectStrategy redirectHandler,
                                org.apache.http.client.AuthenticationStrategy targetAuthHandler,
                                org.apache.http.client.AuthenticationStrategy proxyAuthHandler,
                                org.apache.http.client.UserTokenHandler userTokenHandler,
                                org.apache.http.params.HttpParams params) {

        try {
            redirector = new com.xtremelabs.robolectric.tester.org.apache.http.impl.client.DefaultRequestDirector(
                    log,
                    requestExec,
                    conman,
                    reustrat,
                    kastrat,
                    rouplan,
                    httpProcessor,
                    retryHandler,
                    new DefaultRedirectHandler(),
                    new DefaultProxyAuthenticationHandler(),
                    new DefaultProxyAuthenticationHandler(),
                    userTokenHandler,
                    params
            );
        } catch (IllegalArgumentException ignored) {
            Robolectric.getFakeHttpLayer().interceptHttpRequests(true);
        }
    }

    @Implementation
    public HttpResponse execute(HttpHost httpHost, HttpRequest httpRequest, HttpContext httpContext) throws HttpException, IOException {
        Robolectric.getFakeHttpLayer().addRequestInfo(new HttpRequestInfo(httpRequest, httpHost, httpContext, redirector));
        HttpResponse response = redirector.execute(httpHost, httpRequest, httpContext);
        Robolectric.getFakeHttpLayer().addHttpResponse(response);
        return response;
    }
}
```

Afterwards set the following in your @Test method:

```java
Robolectric.bindShadowClass(MyShadowDefaultRequestDirectory.class);
Robolectric.getFakeHttpLayer().interceptHttpRequests(false);
```

Works fine for me, hope it will work for you guys as well.

**Comment by RyanNewsom** [comment]
I had this same issue in one of our apps. This dependency is the culprit: compile "org.apache.httpcomponents:httpmime:. If I add it back, Robolectric blows up w/ the stack @mikebridge posted. Luckily I am able to comment it out for tests, and uncomment it when I need to build the apk.
