### ISSUE TITLE
Transitive Drawable declaration can't inflate view

### ISSUE THREAD

**Issue by jbruchanov** [robolectric/robolectric#2404]
`button_transparent_background` is not a file, its just `<item name="button_transparent_background" type="drawable">@drawable/color_transparent</item>`

**Structure**
`View.background=@drawable/button_transparent_background`
-> **values/drawables.xml**

```
...
<item name="button_transparent_background" type="drawable">@drawable/color_transparent</item>
...
```

-> **values-v21/drawables.xml**

```
...
<item name="button_transparent_background" type="drawable">@drawable/button_ripple_mask_white_background</item>
...
```

```
@drawable/color_transparent
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
    <solid android:color="@android:color/transparent" />
</shape>
```

```
@drawable/button_ripple_mask_white_background
<?xml version="1.0" encoding="utf-8"?>
<ripple xmlns:android="http://schemas.android.com/apk/res/android"
        android:color="@color/blue_c5">
    <item>
        <shape>
            <solid android:color="@color/white_c1"/>
        </shape>
    </item>
</ripple>
```

```
Caused by: android.content.res.Resources$NotFoundException: can't find file for ResName{com.sample.app:drawable/button_transparent_background}
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:86)
    at org.robolectric.shadows.Converter.convertAndFill(Converter.java:44)
    at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:130)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:108)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:52)
    at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:310)
    at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:472)
    at android.view.View.__constructor__(View.java:3677)
    at android.view.View.<init>(View.java)
    at android.widget.ImageView.<init>(ImageView.java)
    at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:106)
    at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:972)
    at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1031)
    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:725)
    ... 68 more
```

**Comment by jongerrish** [comment]
It's likely this will just work now with binary resource mode....

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
