### ISSUE TITLE
Resources$NotFoundException on testReleaseUnitTest

### ISSUE THREAD

**Issue by jrarrieta** [robolectric/robolectric#2409]
I'm having my robolectric tests fail on command line (mac user) but specifically for my the release unit tests. They work successfully both on Android Studio 2.0 and in testDebugUnitTest on command line. I'm not sure why it wouldn't be able to find the resource ID in release. Does anyone have an idea? I am running robolectric 3.0 with gradle 2.0.0

> android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f03003e
	at org.robolectric.shadows.ShadowAssetManager.checkResName(ShadowAssetManager.java:803)
	at org.robolectric.shadows.ShadowAssetManager.resolveResName(ShadowAssetManager.java:798)
	at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:253)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java)
	at android.content.res.Resources.getLayout(Resources.java:1049)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:412)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at android.view.View.inflate(View.java:18415)
	at com.capitalone.msa.ui.transaction.detail.TransactionDetailRow.init(TransactionDetailRow.java:51)
	at com.capitalone.msa.ui.transaction.detail.TransactionDetailRow.<init>(TransactionDetailRow.java:36)
	at com.capitalone.msa.ui.paymentactivity.PaymentDetailRowTest.setUp(PaymentDetailRowTest.java:56)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:193)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:159)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Any ideas?

**Comment by jrarrieta** [comment]
When moving the failing Robolectric test class intoone specific package, it works. If I move it to its own package, it fails. It also fails when moving it to other packages in my module besides the one that works. This again only happens in testReleaseUnitTest
