### ISSUE TITLE
Error with Color Selector (3.0)

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#2416]
It appears that instead of using from Drawable robolectric is trying to load FromColor instead for a color selector we have.

Caused by: java.lang.RuntimeException: error converting 
      @drawable/button_default_not_rounded_inverse_text_color_selector
     using FromColor
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:159)
	at org.robolectric.shadows.Converter.convertAndFill(Converter.java:50)
	at org.robolectric.shadows.ShadowResources.createTypedArray(ShadowResources.java:232)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:209)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:485)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.widget.TextView.__constructor__(TextView.java:780)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.Button.<init>(Button.java)
	at com.abercrombie.abercrombie.ui.widget.LetterSpacingButton.<init>(LetterSpacingButton.java:27)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:916)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at com.abercrombie.abercrombie.ui.base.BaseFragmentDelegateImpl.onCreateView(BaseFragmentDelegateImpl.java:37)
	at com.abercrombie.abercrombie.ui.base.BaseFragment.onCreateView(BaseFragment.java:25)

The corresponding style that uses this looks like the following:
`  <style name="AFButton.NotRounded.Inverse" parent="android:Widget.Button">
    <item name="fontPath">@string/fontpath_button</item>
    <item name="android:background">@drawable/button_default_not_rounded_inverse</item>
    <item name="android:minHeight">@dimen/btn_height_small</item>
    <item name="android:textSize">@dimen/text_size_small</item>
    <item name="android:textAllCaps">true</item>
    <item name="android:textColor">
      @drawable/button_default_not_rounded_inverse_text_color_selector
    </item>
  </style>
`
The selector itself:

     <selector xmlns:android="http://schemas.android.com/apk/res/android">
         <item android:state_focused="true" android:state_pressed="false" android:color="@color/cream" />
         <item android:state_focused="true" android:state_pressed="true" android:color="@color/cream" />
         <item android:state_focused="false" android:state_pressed="true" android:color="@color/cream" />
         <item android:state_checked="true" android:color="@color/cream" />
         <item android:color="@color/dark_gray" />
     </selector>

The test is just using the SupportFragmentUtils.startFragment(...) method to start the fragment.

**Comment by kingargyle** [comment]
Figured this out.  It was because of a XML formatting issue in the drawable.  It had a CRLF combination that split the value into two ines for the android:textColor definition.   Making sure there was no extra whitespace made it work as expected.
