### ISSUE TITLE
ShadowGooglePlayServicesUtil is now ShadowGoogleApiAvailability?

### ISSUE THREAD

**Issue by jaredsburrows** [robolectric/robolectric#2436]
### Description

`ShadowGooglePlayServicesUtil` still exists but without `setIsGooglePlayServicesAvailable`.

Based on the unit test for `ShadowGoogleApiAvailability`, here https://github.com/robolectric/robolectric/blob/c5340e0ee03d614c54f292556d54520d02eb3d5f/robolectric-shadows/shadows-play-services/src/test/java/org/robolectric/shadows/gms/common/ShadowGoogleApiAvailabilityTest.java#L62.
### Steps to Reproduce

Put this in your `setUp()` of your test:

```
final ShadowGoogleApiAvailability shadowGoogleApiAvailability = Shadows.shadowOf(GoogleApiAvailability.getInstance());
final int expectedCode = ConnectionResult.SUCCESS;
shadowGoogleApiAvailability.setIsGooglePlayServicesAvailable(expectedCode);
```
#### Error Output:

```
    java.lang.ClassCastException: com.google.android.gms.common.GoogleApiAvailability cannot be cast to org.robolectric.internal.ShadowedObject
```
### Robolectric & Android Version

Robolectric: 3.1-rc1
Android: Any api level

**Comment by MarcqGuillaumeVO2** [comment]
Any solution ?

Reproduced with gms 8.4.0

**The full stack error**
```
java.lang.ClassCastException: com.google.android.gms.common.GoogleApiAvailability cannot be cast to org.robolectric.internal.ShadowedObject

	at org.robolectric.internal.ShadowExtractor.extract(ShadowExtractor.java:5)
	at org.robolectric.shadows.gms.Shadows.shadowOf(Shadows.java:37)
	at com.deveryware.saip.activity.RoboActivityTests.setUp(RoboActivityTests.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:193)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:159)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by jaredsburrows** [comment]
Use the latest release canidate.

**Comment by MarcqGuillaumeVO2** [comment]
I tried it with version 3.1-rc1 and 3.1--SNAPSHOT.

Same error :(

**Comment by jaredsburrows** [comment]
What does your code look like? I only get this when I do the shadowof it.

**Comment by MarcqGuillaumeVO2** [comment]
It was during the setup, the same code that you.

    ```
@Before
    public void setUp() {
        ShadowLog.stream = System.out;

        // Force success
        final ShadowGoogleApiAvailability shadowGoogleApiAvailability = Shadows.shadowOf(GoogleApiAvailability.getInstance());
        final int expectedCode = ConnectionResult.SUCCESS;
        shadowGoogleApiAvailability.setIsGooglePlayServicesAvailable(expectedCode);
    }
```

**Comment by jaredsburrows** [comment]
@MarcqGuillaumeVO2 Oh alright. I thought you had a new example.Yeah I have this issue. To get around it, I used reflection where I was checking for "success" and Robolectric no longer crashes when use GPS 8.4.0. So for now, I am not using `setIsGooglePlayServicesAvailable`.

**Comment by diegotori** [comment]
I wrote that code BTW. I could of sworn that it did pass unit testing very recently. Either way, I can take a look at it later this week to see what's actually happening.

**Comment by gkylafas** [comment]
@MarcqGuillaumeVO2 I had the same issue. I noticed that [the test for `ShadowGoogleApiAvailability`](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-play-services/src/test/java/org/robolectric/shadows/gms/common/ShadowGoogleApiAvailabilityTest.java#L27) explicitly declares it as a shadow class: 
`@Config(manifest = Config.NONE, shadows = {ShadowGoogleApiAvailability.class})`
I did the same and the problem was gone.

@diegotori Is the above true? Is there a way we could omit the above line (the "shadows=...." part)?

**Comment by diegotori** [comment]
I remember that they made changes to the way shadow classes were instrumented so that you now have to explicitly declare what shadow to use in your unit tests. This is how it has always worked for instance based classes such as this one.

**Comment by jaredsburrows** [comment]
@diegotori I believe you are right. Can @erd or @jongerrish confirm?

**Comment by jaredsburrows** [comment]
@diegotori Any updates?

**Comment by saantiaguilera** [comment]
Im having this same issue (and sometimes also https://github.com/robolectric/robolectric/issues/1399) are there any updates on this gms stuff?

**Comment by jaredsburrows** [comment]
@diegotori Any reason why this fails?

**Comment by diegotori** [comment]
You have to declare the shadow in your Config annotation before using it (that goes for all other shadows that your test will utilize):

`@Config(manifest = Config.NONE, shadows = {ShadowGoogleApiAvailability.class})`

That's how I am currently using it in one of my tests that requires it, and I can confirm with certainty that it works once it's declared in the config. As a matter of fact, I did the very same thing yesterday on a unit test that I had to modify when upgrading to 3.1.

**Comment by jaredsburrows** [comment]
@diegotori Ok awesome! Thanks!
