### ISSUE TITLE
Nullpointer when moving from 3.0 to 3.1-rc1

### ISSUE THREAD

**Issue by scottlahay** [robolectric/robolectric#2448]
### Description

3.1-rc1 seems to have an issue with getting resources. All tests ran fine using Roboblectric 3.0. Test started failing when I changed to 3.1-rc1. Going to look deeper but posting this in case somebody already knows the answer

java.lang.NullPointerException
	at android.content.ContextWrapper.getPackageName(ContextWrapper.java:133)
	at android.content.ComponentName.__constructor__(ComponentName.java:128)
	at android.content.ComponentName.<init>(ComponentName.java)
	at android.content.Intent.__constructor__(Intent.java:4449)
	at android.content.Intent.<init>(Intent.java)
	at com.blah.blah.activities.OfferDetailActivity.onRedeemOffer(OfferDetailActivity.java:154)
	at com.blah.blah.activities.OfferDetailActivityTest.usersThatClickTheButtonMoreThanOnceStillOnlySendOneRedeemMessageToTheServer(OfferDetailActivityTest.java:69)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:531)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:193)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:159)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

### Steps to Reproduce
In build.gradle i changed these two lines. 
targetSdkVersion 21 to targetSdkVersion 23
testCompile 'org.robolectric:robolectric:3.0'  to  testCompile 'org.robolectric:robolectric:3.1-rc1'

### Robolectric & Android Version
org.robolectric:robolectric:3.1-rc1
compileSdkVersion 23
buildToolsVersion "23.0.3"
 defaultConfig {
minSdkVersion 17
targetSdkVersion 23

**Comment by jongerrish** [comment]
We removed a bunch of shadow code in favor of using real Framework code. As such, it is required to have an attached base context for any component. You will need to create activities / services using

Robolectric.{build,setup}{Service,Activity}() etc

**Comment by scottlahay** [comment]
Cool, thanks
