### ISSUE TITLE
MultiApiTestRunner does not support run method

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#2501]
### Description

Cannot run individual test methods using MultiApiTestRunner

### Steps to Reproduce

1) Find a test the uses MultiApiTestRunner, e.g: ShadowLayoutInflaterTest
2) Ctrl+Shift+F10 in class body (test runs)
3) Ctrl+Shift+F10 in a method body fails:-

java.lang.Exception: No tests found matching Method testChoosesLayoutBasedOnSearchPath_choosesFirstFileFoundOnPath(org.robolectric.shadows.ShadowLayoutInflaterTest) from org.junit.internal.requests.ClassRequest@28ba21f3

	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:37)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:98)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

### Robolectric & Android Version

Head

**Comment by xian** [comment]
Fixed with c412861.
