### ISSUE TITLE
NoClassDefFoundError: org/apache/tools/ant/Project while executing Robolectric 3.1 tests

### ISSUE THREAD

**Issue by shriduttkothari** [robolectric/robolectric#2552]
java.lang.NoClassDefFoundError: org/apache/tools/ant/Project
	at org.robolectric.internal.dependency.MavenDependencyResolver.<init>(MavenDependencyResolver.java:15)
	at org.robolectric.internal.dependency.MavenDependencyResolver.<init>(MavenDependencyResolver.java:20)
	at org.robolectric.RobolectricTestRunner.getJarResolver(RobolectricTestRunner.java:105)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:189)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.Project
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

**Comment by shriduttkothari** [comment]
There are other user facing same issue using maven build system got it resolved after adding maven dependancy for anache-ant jar but as i am using eclipse to build tests after downloding apache-ant-1.8.2.jar from [http://www.java2s.com/Code/Jar/a/Downloadapacheant182jar.htm] the error got resolved.

i am also using following jars as a robolectric dependency in my project:
```
asm-5.0.1.jar
asm-commons-5.0.1.jar
asm-tree-5.0.1.jar
asm-util-5.0.1.jar
bcprov-jdk16-1.46.jar
commons-codec-1.3.jar
guava-19.0-rc2.jar
httpclient-4.0.3.jar
json-20160212.jar
maven-ant-tasks-2.1.3.jar
objenesis-2.4.jar
robolectric-3.1.jar
robolectric-annotations-3.1.jar
robolectric-resources-3.1.jar
robolectric-utils-3.1.jar
shadows-core-3.1.jar
sqlite4java-0.282.jar
vtd-xml-2.11.jar
```
