### ISSUE TITLE
ParameterizedRobolectricTestRunner in 3.1.1 gets "Stub!" error from XmlPullParserFactory.newInstance() via org.robolectric.ParameterizedRobolectricTestRunner$TestClassRunnerForParameters.methodBlock()

### ISSUE THREAD

**Issue by RobertREvans76** [robolectric/robolectric#2565]
### Description

I wish to run ParameterizedRobolectricTestRunner, to parameterized some existing Robolectric unit tests which Android 21 and robolectric v2.4. I ran into the issue #871 and #2016 - "non-native parameter data types are not correct in the unit test class c'tor" (my paraphrase). I upgraded to 3.1, and now encounter another problem: "java.lang.RuntimeException: Stub!" at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:13) (see attached details.

I am somewhat new to Android programming. I infer that the ParameterizedRobolectricTestRunner is using a utility library to parse an XML stream, and I do not have that library. I attach the libraries that are in my <project>/libs. Note 'xstream-1.4.9.jar'. According to the GIT page for xmlpull, there have have been no updates in several years. 

I have tried a number of approaches to address the problem, which I will not detail here.

Attachment 1: run time error
	"C:\Program Files\Java\jdk1.8.0_60\bin\java" -ea -Didea.launcher.port=7539 "-Didea.launcher.bin.path=D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.1\bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.1\lib\idea_rt.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.1\plugins\junit\lib\junit-rt.jar;D:\IDEA\ParameterizedRobolectric\out\production\ParameterizedRobolectric;D:\IDEA\ParameterizedRobolectric\lib\asm-5.1.jar;D:\IDEA\ParameterizedRobolectric\lib\ant-1.8.0.jar;D:\IDEA\ParameterizedRobolectric\lib\guava-19.0.jar;D:\IDEA\ParameterizedRobolectric\lib\icu4j-53.1.jar;D:\IDEA\ParameterizedRobolectric\lib\xstream-1.4.9.jar;D:\IDEA\ParameterizedRobolectric\lib\asm-tree-5.0.1.jar;D:\IDEA\ParameterizedRobolectric\lib\asm-util-5.0.1.jar;D:\IDEA\ParameterizedRobolectric\lib\asm-commons-5.1.jar;D:\IDEA\ParameterizedRobolectric\lib\bcprov-jdk16-1.46.jar;D:\IDEA\ParameterizedRobolectric\lib\robolectric-3.1.1.jar;D:\IDEA\ParameterizedRobolectric\lib\ant-launcher-1.8.0.jar;D:\IDEA\ParameterizedRobolectric\lib\sqlite4java-1.0.392.jar;D:\IDEA\ParameterizedRobolectric\lib\maven-ant-tasks-2.1.3.jar;D:\IDEA\ParameterizedRobolectric\lib\shadows-core-v23-3.1.1.jar;D:\IDEA\ParameterizedRobolectric\lib\robolectric-utils-3.1.1.jar;D:\IDEA\ParameterizedRobolectric\lib\robolectric-resources-3.1.1.jar;D:\IDEA\ParameterizedRobolectric\lib\robolectric-annotations-3.1.1.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.1\lib\junit-4.12.jar;D:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.1.1\lib\hamcrest-core-1.3.jar;D:\Android\android-sdk\platforms\android-21\android.jar;D:\Android\android-sdk\platforms\android-21\data\res" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 ContactServiceTest
	WARNING: No manifest file found at .\AndroidManifest.xml.Falling back to the Android OS resources only.
	To remove this warning, annotate your test class with @Config(manifest=Config.NONE).

	java.lang.RuntimeException: Stub!

		at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:13)
		at com.thoughtworks.xstream.io.xml.XppDriver.createParser(XppDriver.java:57)
		at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
		at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
		at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
		at org.robolectric.internal.DeepCloner.clone(DeepCloner.java:29)
		at org.robolectric.ParameterizedRobolectricTestRunner$TestClassRunnerForParameters.methodBlock(ParameterizedRobolectricTestRunner.java:109)
		at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
		at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runners.Suite.runChild(Suite.java:128)
		at org.junit.runners.Suite.runChild(Suite.java:27)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
		at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
		at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
		at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:497)
		at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

	Process finished with exit code -1

Attachment 2: libraries in <project>/lib
	
	ant-1.8.0.jar
	ant-launcher-1.8.0.jar
	asm-5.1.jar
	asm-commons-5.1.jar
	asm-tree-5.0.1.jar
	asm-util-5.0.1.jar
	bcprov-jdk16-1.46.jar
	guava-19.0.jar
	hamcrest-core-1.3.jar
	icu4j-53.1.jar
	junit-4.12.jar
	maven-ant-tasks-2.1.3.jar
	robolectric-3.1.1.jar
	robolectric-annotations-3.1.1.jar
	robolectric-resources-3.1.1.jar
	robolectric-utils-3.1.1.jar
	shadows-core-v23-3.1.1.jar
	sqlite4java-1.0.392.jar
	xstream-1.4.9.jar

### Steps to Reproduce
Use ParameterizedRobolectricTestRunner in version 3.1.1

### Robolectric & Android Version
Robolectric 3.1.1, Android 21
IntelliJ 2016.1.2, Windows 7

**Comment by jongerrish** [comment]
It is executing Android framework code before Robolectric's special classloader has been set up and thus executing code in the sdk android.jar which are just stubs.

I'm personally not familiar with ParameterizedRobolectricTestRunner so it might be best to direct questions to the authors or @WonderCSabo who added the cloning support that is failing for you.

What are your parameters? Are you declaring any static variables in your test?

**Comment by RobertREvans76** [comment]
Here is my java code. Based on your comment, could there be something wrong with my dependency ordering?

```
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.ParameterizedRobolectricTestRunner;
import org.robolectric.annotation.Config;

import java.util.Arrays;
import java.util.Collection;

@Config(sdk = 21)
@RunWith(ParameterizedRobolectricTestRunner.class)
public class ContactServiceTest {
    public enum Codes { AA, BB }

    @ParameterizedRobolectricTestRunner.Parameters
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]{
                {Codes.AA, "DEFAULT_ERROR_MSG"}
        });
    }

    private Codes errorCode;
    private String expectedErrorMsg;

    public ContactServiceTest(Codes errorCode, String errorMsg) {
        this.errorCode = errorCode;
        this.expectedErrorMsg = errorMsg;
    }

    @Test
    public void testRobolectricTestWithData() {
    }
}
```

**Comment by RobertREvans76** [comment]
This StackOverflow discussion has a workaround

http://stackoverflow.com/questions/15423833/robolectric-and-dagger-testing

**Comment by jongerrish** [comment]
Oh yeah, so the reason it is not loaded from the android-all*.jar is because of this line:-

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/bytecode/InstrumentationConfiguration.java#L138

This line makes it that the class in question is loaded from the system classloader, which is going to come from your android.jar I guess if you put the xml pull jar ahead of the android.jar on your classpath it would work.

Another dirty thing you could do is add android-all-6.0.0_r1-robolectric-0.jar to the classpath before android.jar.

I create an issue to track this: https://github.com/robolectric/robolectric/issues/2566

I'll close this as a duplicate
