### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by tudor-pop** [robolectric/robolectric#2579]
Hello! I'm really new to robolectric so I might be missing something but I can't get it running and I'm getting this

``` java
java.lang.NullPointerException
    at java.util.concurrent.LinkedBlockingDeque.putLast(LinkedBlockingDeque.java:390)
    at java.util.concurrent.LinkedBlockingDeque.put(LinkedBlockingDeque.java:649)
    at com.facebook.internal.AttributionIdentifiers$GoogleAdServiceConnection.onServiceConnected(AttributionIdentifiers.java:261)
    at org.robolectric.shadows.ShadowApplication$1.run(ShadowApplication.java:236)
    at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:335)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:237)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:218)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:201)
    at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:78)
    at org.robolectric.util.Scheduler.unPause(Scheduler.java:112)
    at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:291)
    at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:342)
    at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
    at org.robolectric.util.ActivityController.create(ActivityController.java:123)
    at org.robolectric.util.ActivityController.create(ActivityController.java:133)
    at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
    at org.robolectric.Robolectric.setupActivity(Robolectric.java:96)
    at com.marked.pixsee.main.MainActivityTest.testOnCreate(MainActivityTest.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:465)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
    at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

The test class looks like this

``` java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class,sdk = 23)
public class MainActivityTest {
    @Test
    public void testOnCreate() throws Exception {
        Activity activity = Robolectric.setupActivity(MainActivity.class);
    }
}
```

In gradle I use

``` gradle
testCompile "org.robolectric:robolectric:3.2-SNAPSHOT"
testCompile 'org.robolectric:shadows-play-services:3.2-SNAPSHOT'
```

I get the same error on 3.1 and 3.1.1 on android sdk 23

Any ideas how to fix it? I've been searching the web for 7 hours by now and could not find anything 
thank you !

**Comment by xian** [comment]
Looks like it's a problem with Facebook's sdk:

```
java.lang.NullPointerException
    at java.util.concurrent.LinkedBlockingDeque.putLast(LinkedBlockingDeque.java:390)
    at java.util.concurrent.LinkedBlockingDeque.put(LinkedBlockingDeque.java:649)
    at com.facebook.internal.AttributionIdentifiers$GoogleAdServiceConnection.onServiceConnected(AttributionIdentifiers.java:261)
    at org.robolectric.shadows.ShadowApplication$1.run(ShadowApplication.java:236)
```

Can you provide details from your `AndroidManifest.xml` and `MainActivity`?

**Comment by PopTudor** [comment]
@xian sorry for late answer and thank you for responding!
I get this error for every activity in the app. MainActivity is dumb also the Presenter is really light and not using any of Facebook's sdk features. However the sdk is initialised by extending Application
```java
public class Pixsee extends Application {
	private AppComponent appComponent;
	@Override
	public void onCreate() {
		super.onCreate();
		appComponent = DaggerAppComponent.builder().appModule(new AppModule(this)).build();
		OkHttpClient client = new OkHttpClient();
		client.interceptors().add(new com.squareup.okhttp.Interceptor() {
			@Override
			public Response intercept(Chain chain) throws IOException {
				Request request = chain.request();

				long t1 = System.nanoTime();
				Log.i("OKHttp",String.format("Sending request %s on %s%n%s", request.url(), chain.connection(), request.headers()));

				Response response = chain.proceed(request);

				long t2 = System.nanoTime();
				Log.i("OKHttp",String.format("Received response for %s in %.1fms%n%s",response.request().url(), (t2 - t1) / 1e6d, response.headers()));

				return response;
			}
		});
		ImagePipelineConfig config = OkHttpImagePipelineConfigFactory
				.newBuilder(this, client)
				.setDownsampleEnabled(true)
				.build();
		Fresco.initialize(this, config);
		FacebookSdk.sdkInitialize(getApplicationContext());
                AppEventsLogger.activateApp(this);
	}

	public AppComponent getAppComponent() {
		return appComponent;
	}
}
```
removing AppEventsLogger.activateApp(this); partially fixes the problem but then throws 
```java java.lang.NoClassDefFoundError: javax/microedition/khronos/opengles/GL`
The manifest is
```java
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.example.pixsee">

    <uses-permission android:name="android.permission.CAMERA"/>
    <!-- <uses-permission android:name="android.permission.RECORD_AUDIO"/> -->

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <!-- <uses-permission android:name="android.permission.READ_CONTACTS"/> -->

    <!-- Add this permission to allow opening network sockets. -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <!-- <uses-permission android:name="android.permission.USE_CREDENTIALS"/> -->
    <!-- <uses-permission android:name="android.permission.GET_ACCOUNTS"/> -->
    <!-- <uses-permission android:name="android.permission.READ_PROFILE"/> -->
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <uses-feature
        android:glEsVersion="0x00020000"
        android:required="true"/>
    <uses-feature android:name="android.hardware.camera"/>
    <application
        android:name=".Pixsee"
        android:allowBackup="true"
        android:backupAgent=".utility.TheBackupAgent"
        android:configChanges="orientation|keyboardHidden|screenSize|smallestScreenSize"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:restoreAnyVersion="true"
        android:theme="@style/AppTheme">
        <meta-data
            android:name="com.google.android.backup.api_key"
            android:value="some_backup_apikey"/>
        <meta-data
            android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version"/>
        <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>
        <meta-data
            android:name="com.google.android.gms.vision.DEPENDENCIES"
            android:value="face"/>

        <activity
            android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"/>
        <activity
            android:name=".entry.EntryActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <action android:name="package.FRIEND_REQUEST" />
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>

                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <!-- Accepts URIs "com.example.myapp://" -->
                <data android:scheme="com.marked.pixsee"/>
            </intent-filter>
        </activity>

        <!-- [START gcm_listener] -->
        <service android:name=".chat.GCMListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        <!-- [START instanceId_listener] -->
        <service android:name=".service.GCMInstanceIDListenerService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <!-- [END instanceId_listener] -->
        <service
            android:name=".service.LogInRegistrationIntentService"
            android:exported="false"/>


        <activity
            android:name=".authentification.AuthenticationActivity"
            android:screenOrientation="portrait"/>

        <meta-data
            android:name="io.fabric.ApiKey"
            android:value="some_apikey"/>

        <activity
            android:name=".fullscreenImage.ImageFullscreenActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:label="@string/title_activity_fullscreen"
            android:theme="@style/FullscreenTheme"/>
        <activity
            android:name=".chat.ChatActivity"
            android:label="FriendDetailActivity"
            android:screenOrientation="portrait"/>

        <provider
            android:name="com.facebook.FacebookContentProvider"
            android:authorities="some_authority"
            android:exported="true"/>

        <activity android:name=".main.MainActivity">
        </activity>
        <activity android:name=".friendsInvite.FriendsInviteActivity">
        </activity>
    </application>

</manifest>
`

**Comment by PopTudor** [comment]
fixed it with [NoClassDefFound](https://github.com/robolectric/robolectric/issues/1932#issuecomment-219796474) but only without ```AppEventsLogger.activateApp(this);```

**Comment by ijunes** [comment]
Any updates on this issue?

**Comment by ENDEMI0N** [comment]
try to use version 4.2.0 of Facebook SDK

**Comment by AndreSand** [comment]
Solution that worked for me. Add below code:
```
 if(!BaseActivity.isRoboUnitTest()) {
             AppEventsLogger.activateApp(this);
         }
```
It will disbable Facebook AppEventsLogger when running tests.

**Comment by SUPERCILEX** [comment]
For anyone experiencing this issue with `v4.19.0`, it took me soooo long to figure out, but Facebook is auto logging app events now so you need to disable automatic initialization of `AutoLogAppEvents`:
```xml
<meta-data
    android:name="com.facebook.sdk.AutoLogAppEventsEnabled"
    android:value="false"/>
```

**Comment by SUPERCILEX** [comment]
Okay, so I figured out why the `NullPointerException` occurs: https://github.com/robolectric/robolectric/issues/834 says Robolectirc returns null for `IBinder` and Facebook is using a `LinkedBlockingDeque` which does not support putting in null objects.

**Comment by jongerrish** [comment]
We're actually working on something related to this possibly at the moment,
which is generating dynamic proxies for service interfaces (so at least
they won't be null). If you can give is a simple test case (no external
code) I'll see if our change will solve this issue directly or can at least
be extended to solve it easily.

**Comment by SUPERCILEX** [comment]
@jongerrish Awesome!

**Comment by utzcoz** [comment]
@SUPERCILEX Looks like you have fixed this NPE problem on the facebook-android-sdk part. Feel free to reopen this issue if you think there are something that Robolectric needs do. Thanks.
