### ISSUE TITLE
Supporting CollapsingToolbarLayout

### ISSUE THREAD

**Issue by miquelbeltran** [robolectric/robolectric#2580]
### Description

I want to test a Fragment that contains a CollapsingToolbarLayout with Robolectric but I am facing the current issue when running startFragment.

`android.view.InflateException: XML file build/intermediates/res/merged/dev/layout/fragment_homefeed.xml line #-1 (sorry, not yet implemented): XML file build/intermediates/res/merged/dev/layout-v21/layout_homefeed_header.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.CollapsingToolbarLayout`

<details>
 <summary>Full stack trace</summary>
```
android.view.InflateException: XML file build/intermediates/res/merged/dev/layout/fragment_homefeed.xml line #-1 (sorry, not yet implemented): XML file build/intermediates/res/merged/dev/layout-v21/layout_homefeed_header.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.CollapsingToolbarLayout

	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at xxx.MyFragment.onCreateView(HomeFeedFragment.java:110)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:113)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1557)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:654)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:621)
	at org.robolectric.shadows.support.v4.SupportFragmentTestUtil.startFragment(SupportFragmentTestUtil.java:17)
	at xxx.MyFragmentTest.setUp(HomeFeedFragmentTest.java:23)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:265)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: android.view.InflateException: XML file build/intermediates/res/merged/dev/layout-v21/layout_homefeed_header.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.CollapsingToolbarLayout
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 45 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$parseInclude(LayoutInflater.java:971)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:831)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at xxx.MyFragment.onCreateView(HomeFeedFragment.java:110)
	at android.support.v4.app.Fragment.$$robo$$performCreateView(Fragment.java:2074)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1104)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$moveToState(FragmentManager.java:1286)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.BackStackRecord.$$robo$$run(BackStackRecord.java:758)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$execPendingActions(FragmentManager.java:1671)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl$1.$$robo$$run(FragmentManager.java:532)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java)
	at android.os.Handler.$$robo$$handleCallback(Handler.java:739)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.$$robo$$dispatchMessage(Handler.java:95)
	at android.os.Handler.dispatchMessage(Handler.java)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:113)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.$$robo$$enqueueMessage(Handler.java:631)
	at android.os.Handler.enqueueMessage(Handler.java)
	at android.os.Handler.$$robo$$sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageAtTime(Handler.java)
	at android.os.Handler.$$robo$$sendMessageDelayed(Handler.java:570)
	at android.os.Handler.sendMessageDelayed(Handler.java)
	at android.os.Handler.$$robo$$post(Handler.java:326)
	at android.os.Handler.post(Handler.java)
	at android.support.v4.app.FragmentManagerImpl.$$robo$$enqueueAction(FragmentManager.java:1557)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java)
	at android.support.v4.app.BackStackRecord.$$robo$$commitInternal(BackStackRecord.java:654)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java)
	at android.support.v4.app.BackStackRecord.$$robo$$commit(BackStackRecord.java:621)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java)
	at org.robolectric.shadows.support.v4.SupportFragmentTestUtil.startFragment(SupportFragmentTestUtil.java:17)
	at xxx.MyFragmentTest.setUp(HomeFeedFragmentTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:265)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0700e2
	at org.robolectric.shadows.ShadowAssetManager.checkResName(ShadowAssetManager.java:774)
	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:764)
	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:664)
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:103)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:52)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:270)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:265)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:520)
	at android.support.design.widget.CollapsingTextHelper.setCollapsedTextAppearance(CollapsingTextHelper.java:197)
	at android.support.design.widget.CollapsingToolbarLayout.__constructor__(CollapsingToolbarLayout.java:184)
	at android.support.design.widget.CollapsingToolbarLayout.<init>(CollapsingToolbarLayout.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at xxx.MyFragment.onCreateView(HomeFeedFragment.java:110)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:144)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:113)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:293)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:143)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:126)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.post(Handler.java:326)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1557)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:654)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:621)
	at org.robolectric.shadows.support.v4.SupportFragmentTestUtil.startFragment(SupportFragmentTestUtil.java:17)
	at xxx.MyFragmentTest.setUp(HomeFeedFragmentTest.java:23)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:265)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:191)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:56)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:157)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	... 1 more
```
</details>

Is there any way I can support CollapsingToolbarLayout with Robolectric?

I couldn't find a solution, neither on GitHub or StackOverflow.

### Steps to Reproduce

- Build a Fragment
- with a layout that contains the following hierarchy:

```
    <android.support.design.widget.CoordinatorLayout>
       <android.support.design.widget.AppBarLayout>
         <android.support.design.widget.CollapsingToolbarLayout>
```

The CollapsingToolbarLayout attributes:

```
    <android.support.design.widget.CollapsingToolbarLayout
        android:id="@+id/collapsing_toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:contentScrim="@android:color/white"
        app:layout_scrollFlags="scroll|exitUntilCollapsed">
```

- on test setup, run startFragment() with such fragment.

### Robolectric & Android Version

    compileSdkVersion 24
    buildToolsVersion "23.0.3"

    supportLibVersion = '24.1.0'
    robolectricLibVersion = '3.1'

Extract from my build.gradle

    testCompile("org.robolectric:robolectric:${robolectricLibVersion}") {
        exclude group: 'commons-logging', module: 'commons-logging'
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
        exclude group: 'com.android.support', module: 'cardview-v7'
        exclude group: 'com.android.support', module: 'design'
    }
    testCompile "org.robolectric:shadows-support-v4:${robolectricLibVersion}"

**Comment by jongerrish** [comment]
Caused by: android.content.res.Resources$NotFoundException: Unable to find
resource ID #0x7f0700e2

Robolectric can't find this resource, can you figure out which one it is.
Look in the R files.

What build system are you using ?

**Comment by miquelbeltran** [comment]
The ID number is not present in the R files.

I think this resource is not mine but from the Support Library?  The NotFoundException has this trace in it.

```
   at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
    at android.content.Context.obtainStyledAttributes(Context.java:520)
    at android.support.design.widget.CollapsingTextHelper.setCollapsedTextAppearance(CollapsingTextHelper.java:197)
```

Seems that it cannot find this defined CollapsedTextAppearance. I am not setting such attribute in the layout or code.

> What build system are you using ?

I am using Android Studio 2.1.2 on Mac OS.

**Comment by miquelbeltran** [comment]
I fixed the issue by creating my own Shadow for the CollapsingToolbarLayout.

https://gist.github.com/miquelbeltran/65c8f5327d71e6f1074180e0c18c7f53

Feel free to close the issue and/or use the provided Shadow to implement a proper solution.

**Comment by CCorrado** [comment]
+1 i have the same issue with roboelectric. 

Targeting API 24 (22 in the config for roboelectric test) running in Android Studio 2.2 preview 7. I have heirarchy the same as @miquelbeltran in most of the fragments I'm looking to test, so this definitely poses an issue. I'll check out implementing the shadow above and check back.
