### ISSUE TITLE
Dependency resolution freezes

### ISSUE THREAD

**Issue by Malinskiy** [robolectric/robolectric#2612]
### Description

Robolectric tests freeze in `MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:52)`

Maybe due to `java.net.SocketInputStream.socketRead0` bug or no timeout set on HttpUrlConnection in `LightweightHttpWagon`. On the same machine gradle's dependency resolution correctly handles such network conditions. Maybe we can reuse resolver from gradle?
### Steps to Reproduce
1. Use unreliable network connection
2. Execute tests or coverage report which depends on test task
3. Gradle task freezes
### Robolectric & Android Version

Robolectric version 3.1.2
#### ps

```
ID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                6909                6893                0                   08:52               ?                   00:00:05            /opt/jdk8/bin/java -Dorg.gradle.appname=gradle -classpath /opt/gradle-2.14.1/lib/gradle-launcher-2.14.1.jar org.gradle.launcher.GradleMain -PdisablePreDex disconnectedTest coverageReport
root                6954                6909                1                   08:52               ?                   00:01:30            /opt/jdk8/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Xmx8G -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /opt/gradle-2.14.1/lib/gradle-launcher-2.14.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 2.14.1
root                7253                6954                0                   08:53               ?                   00:00:10            /opt/jdk8/bin/java -Djava.awt.headless=true -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.7.2.201409121644.jar_bamkx1tjew75l4bszbzporv0s/jacocoagent.jar=destfile=build/jacoco/testRawUnitTest.exec,append=true,dumponexit=true,output=file,jmx=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /root/.gradle/caches/2.14.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
```
#### SIGQUIT response ("Test worker" 12 is the interesting part)

```
[11:13:56][docker] :data:testRawUnitTest
[11:13:56][docker] 2016-08-16 04:13:55
[11:13:56][docker] Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode):
[11:13:56][docker] 
[11:13:56][docker] "/0:0:0:0:0:0:0:1:34346 to /0:0:0:0:0:0:0:1:37223 workers Thread 3" #14 prio=5 os_prio=0 tid=0x00007fc690a11000 nid=0x169 runnable [0x00007fc668694000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker]  at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
[11:13:56][docker]  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
[11:13:56][docker]  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
[11:13:56][docker]  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
[11:13:56][docker]  - locked <0x00000007760a2e30> (a sun.nio.ch.Util$2)
[11:13:56][docker]  - locked <0x00000007760a2e40> (a java.util.Collections$UnmodifiableSet)
[11:13:56][docker]  - locked <0x00000007760a2de8> (a sun.nio.ch.EPollSelectorImpl)
[11:13:56][docker]  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
[11:13:56][docker]  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
[11:13:56][docker]  at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:165)
[11:13:56][docker]  at com.esotericsoftware.kryo.io.Input.fill(Input.java:139)
[11:13:56][docker]  at com.esotericsoftware.kryo.io.Input.require(Input.java:159)
[11:13:56][docker]  at com.esotericsoftware.kryo.io.Input.readByte(Input.java:255)
[11:13:56][docker]  at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:80)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:63)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
[11:13:56][docker]  at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:78)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:250)
[11:13:56][docker]  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[11:13:56][docker]  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:13:56][docker]  at java.lang.Thread.run(Thread.java:745)
[11:13:56][docker] 
[11:13:56][docker] "/0:0:0:0:0:0:0:1:34346 to /0:0:0:0:0:0:0:1:37223 workers Thread 2" #13 prio=5 os_prio=0 tid=0x00007fc690a13800 nid=0x168 waiting on condition [0x00007fc668795000]
[11:13:56][docker]    java.lang.Thread.State: WAITING (parking)
[11:13:56][docker]  at sun.misc.Unsafe.park(Native Method)
[11:13:56][docker]  - parking to wait for  <0x0000000776152e48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
[11:13:56][docker]  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[11:13:56][docker]  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.queue.EndPointQueue.take(EndPointQueue.java:48)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:293)
[11:13:56][docker]  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[11:13:56][docker]  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:13:56][docker]  at java.lang.Thread.run(Thread.java:745)
[11:13:56][docker] 
[11:13:56][docker] "Test worker" #12 prio=5 os_prio=0 tid=0x00007fc690a09800 nid=0x167 runnable [0x00007fc668893000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker]  at java.net.SocketInputStream.socketRead0(Native Method)
[11:13:56][docker]  at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[11:13:56][docker]  at java.net.SocketInputStream.read(SocketInputStream.java:170)
[11:13:56][docker]  at java.net.SocketInputStream.read(SocketInputStream.java:141)
[11:13:56][docker]  at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[11:13:56][docker]  at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[11:13:56][docker]  at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[11:13:56][docker]  - locked <0x0000000775244fa8> (a java.io.BufferedInputStream)
[11:13:56][docker]  at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
[11:13:56][docker]  at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
[11:13:56][docker]  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
[11:13:56][docker]  - locked <0x000000077523a398> (a sun.net.www.protocol.http.HttpURLConnection)
[11:13:56][docker]  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
[11:13:56][docker]  - locked <0x000000077523a398> (a sun.net.www.protocol.http.HttpURLConnection)
[11:13:56][docker]  at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
[11:13:56][docker]  at org.apache.maven.wagon.providers.http.LightweightHttpWagon.fillInputData(LightweightHttpWagon.java:115)
[11:13:56][docker]  at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
[11:13:56][docker]  at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
[11:13:56][docker]  at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
[11:13:56][docker]  at org.apache.maven.artifact.manager.DefaultWagonManager.getRemoteFile(DefaultWagonManager.java:546)
[11:13:56][docker]  at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:427)
[11:13:56][docker]  at org.apache.maven.artifact.manager.DefaultWagonManager.getArtifact(DefaultWagonManager.java:382)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:216)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
[11:13:56][docker]  at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
[11:13:56][docker]  at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultMavenProjectBuilder.java:251)
[11:13:56][docker]  at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedProject(MavenMetadataSource.java:163)
[11:13:56][docker]  at org.apache.maven.project.artifact.MavenMetadataSource.retrieveRelocatedArtifact(MavenMetadataSource.java:94)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:387)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtifactCollector.java:435)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtifactCollector.java:74)
[11:13:56][docker]  at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:316)
[11:13:56][docker]  at org.apache.maven.artifact.ant.DependenciesTask.doExecuteResolution(DependenciesTask.java:263)
[11:13:56][docker]  at org.apache.maven.artifact.ant.DependenciesTask.doExecute(DependenciesTask.java:168)
[11:13:56][docker]  at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
[11:13:56][docker]  at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:52)
[11:13:56][docker]  at org.robolectric.internal.dependency.CachedDependencyResolver.getLocalArtifactUrls(CachedDependencyResolver.java:43)
[11:13:56][docker]  at org.robolectric.internal.InstrumentingClassLoaderFactory.getSdkEnvironment(InstrumentingClassLoaderFactory.java:43)
[11:13:56][docker]  - locked <0x00000007761679f0> (a org.robolectric.internal.InstrumentingClassLoaderFactory)
[11:13:56][docker]  at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:173)
[11:13:56][docker]  at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
[11:13:56][docker]  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[11:13:56][docker]  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
[11:13:56][docker]  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
[11:13:56][docker]  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
[11:13:56][docker]  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
[11:13:56][docker]  at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
[11:13:56][docker]  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
[11:13:56][docker]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:13:56][docker]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:13:56][docker]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:13:56][docker]  at java.lang.reflect.Method.invoke(Method.java:498)
[11:13:56][docker]  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[11:13:56][docker]  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[11:13:56][docker]  at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
[11:13:56][docker]  at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
[11:13:56][docker]  at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
[11:13:56][docker]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:13:56][docker]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:13:56][docker]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:13:56][docker]  at java.lang.reflect.Method.invoke(Method.java:498)
[11:13:56][docker]  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
[11:13:56][docker]  at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[11:13:56][docker]  at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
[11:13:56][docker]  at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
[11:13:56][docker]  at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[11:13:56][docker]  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[11:13:56][docker]  at java.lang.Thread.run(Thread.java:745)
[11:13:56][docker] 
[11:13:56][docker] "Service Thread" #10 daemon prio=9 os_prio=0 tid=0x00007fc69035b000 nid=0x162 runnable [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "C1 CompilerThread3" #9 daemon prio=9 os_prio=0 tid=0x00007fc690340800 nid=0x161 waiting on condition [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "C2 CompilerThread2" #8 daemon prio=9 os_prio=0 tid=0x00007fc69033f000 nid=0x160 waiting on condition [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "C2 CompilerThread1" #7 daemon prio=9 os_prio=0 tid=0x00007fc690273800 nid=0x15f waiting on condition [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "C2 CompilerThread0" #6 daemon prio=9 os_prio=0 tid=0x00007fc69033d800 nid=0x15e waiting on condition [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007fc690238800 nid=0x15d waiting on condition [0x0000000000000000]
[11:13:56][docker]    java.lang.Thread.State: RUNNABLE
[11:13:56][docker] 
[11:13:56][docker] "Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fc6901d4800 nid=0x15c in Object.wait() [0x00007fc66a209000]
[11:13:56][docker]    java.lang.Thread.State: WAITING (on object monitor)
[11:13:56][docker]  at java.lang.Object.wait(Native Method)
[11:13:56][docker]  - waiting on <0x0000000776195158> (a java.lang.ref.ReferenceQueue$Lock)
[11:13:56][docker]  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
[11:13:56][docker]  - locked <0x0000000776195158> (a java.lang.ref.ReferenceQueue$Lock)
[11:13:56][docker]  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
[11:13:56][docker]  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
[11:13:56][docker] 
[11:13:56][docker] "Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fc6901cf800 nid=0x15b in Object.wait() [0x00007fc66a30a000]
[11:13:56][docker]    java.lang.Thread.State: WAITING (on object monitor)
[11:13:56][docker]  at java.lang.Object.wait(Native Method)
[11:13:56][docker]  - waiting on <0x0000000776195370> (a java.lang.ref.Reference$Lock)
[11:13:56][docker]  at java.lang.Object.wait(Object.java:502)
[11:13:56][docker]  at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
[11:13:56][docker]  - locked <0x0000000776195370> (a java.lang.ref.Reference$Lock)
[11:13:56][docker]  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
[11:13:56][docker] 
[11:13:56][docker] "main" #1 prio=5 os_prio=0 tid=0x00007fc69000b000 nid=0x151 waiting on condition [0x00007fc698bcd000]
[11:13:56][docker]    java.lang.Thread.State: WAITING (parking)
[11:13:56][docker]  at sun.misc.Unsafe.park(Native Method)
[11:13:56][docker]  - parking to wait for  <0x000000077612a9d0> (a java.util.concurrent.CountDownLatch$Sync)
[11:13:56][docker]  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[11:13:56][docker]  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
[11:13:56][docker]  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
[11:13:56][docker]  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
[11:13:56][docker]  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:70)
[11:13:56][docker]  at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:45)
[11:13:56][docker]  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:76)
[11:13:56][docker]  at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:34)
[11:13:56][docker]  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:85)
[11:13:56][docker]  at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:45)
[11:13:56][docker]  at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:61)
[11:13:56][docker]  at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:66)
[11:13:56][docker] 
[11:13:56][docker] "VM Thread" os_prio=0 tid=0x00007fc6901c8000 nid=0x15a runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007fc690020000 nid=0x152 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007fc690022000 nid=0x153 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007fc690023800 nid=0x154 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007fc690025800 nid=0x155 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007fc690027000 nid=0x156 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007fc690029000 nid=0x157 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007fc69002a800 nid=0x158 runnable 
[11:13:56][docker] 
[11:13:56][docker] "GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007fc69002c800 nid=0x159 runnable 
[11:13:56][docker] 
[11:13:56][docker] "VM Periodic Task Thread" os_prio=0 tid=0x00007fc69035d800 nid=0x163 waiting on condition 
[11:13:56][docker] 
[11:13:56][docker] JNI global references: 258
[11:13:56][docker] 
[11:13:56][docker] Heap
[11:13:56][docker]  PSYoungGen      total 70656K, used 62253K [0x0000000771b80000, 0x000000077a580000, 0x00000007c0000000)
[11:13:56][docker]   eden space 60928K, 93% used [0x0000000771b80000,0x0000000775320cd8,0x0000000775700000)
[11:13:56][docker]   from space 9728K, 54% used [0x0000000776080000,0x00000007765aaa98,0x0000000776a00000)
[11:13:56][docker]   to   space 9728K, 0% used [0x0000000775700000,0x0000000775700000,0x0000000776080000)
[11:13:56][docker]  ParOldGen       total 161280K, used 24K [0x00000006d5200000, 0x00000006def80000, 0x0000000771b80000)
[11:13:56][docker]   object space 161280K, 0% used [0x00000006d5200000,0x00000006d5206000,0x00000006def80000)
[11:13:56][docker]  Metaspace       used 17576K, capacity 17900K, committed 18048K, reserved 1064960K
[11:13:56][docker]   class space    used 1994K, capacity 2098K, committed 2176K, reserved 1048576K
[11:13:56][docker] 
```
#### Debug log from gradle

```
[16:19:42] :             [docker] 09:19:42.340 [DEBUG] [TestEventLogger] com.mobile.consumer.data.db.DbOpenHelperTest > testDatabaseMigrationToLatestVersion STANDARD_OUT
[16:19:42] :             [docker] 09:19:42.340 [DEBUG] [TestEventLogger]     [INFO] Unable to find resource 'org.ow2.asm:asm-tree:pom:5.0.1' in repository sonatype (https://oss.son$
[16:19:42] :             [docker] 09:19:42.340 [DEBUG] [TestEventLogger]
[16:19:42] :             [docker] 09:19:42.340 [DEBUG] [TestEventLogger] com.mobile.consumer.data.db.DbOpenHelperTest > testDatabaseMigrationToLatestVersion STANDARD_ERR$
[16:19:42] :             [docker] 09:19:42.340 [DEBUG] [TestEventLogger]     Downloading: org/ow2/asm/asm-tree/5.0.1/asm-tree-5.0.1.pom from repository central at http://repo1.mave$
[16:20:04] :             [docker] 09:20:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:20:04] :             [docker] 09:20:04.731 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:20:04] :             [docker] 09:20:04.732 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:20:04] :             [docker] 09:20:04.732 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:20:04] :             [docker] 09:20:04.733 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:21:04] :             [docker] 09:21:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:21:04] :             [docker] 09:21:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:21:04] :             [docker] 09:21:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:21:04] :             [docker] 09:21:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:21:04] :             [docker] 09:21:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:22:04] :             [docker] 09:22:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:22:04] :             [docker] 09:22:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:22:04] :             [docker] 09:22:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:22:04] :             [docker] 09:22:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:22:04] :             [docker] 09:22:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:23:04] :             [docker] 09:23:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:23:04] :             [docker] 09:23:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:23:04] :             [docker] 09:23:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:23:04] :             [docker] 09:23:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:23:04] :             [docker] 09:23:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:24:04] :             [docker] 09:24:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:24:04] :             [docker] 09:24:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:24:04] :             [docker] 09:24:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:24:04] :             [docker] 09:24:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:24:04] :             [docker] 09:24:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:25:04] :             [docker] 09:25:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:25:04] :             [docker] 09:25:04.730 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:25:04] :             [docker] 09:25:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:25:04] :             [docker] 09:25:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:25:04] :             [docker] 09:25:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:26:04] :             [docker] 09:26:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:26:04] :             [docker] 09:26:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:26:04] :             [docker] 09:26:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:26:04] :             [docker] 09:26:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:26:04] :             [docker] 09:26:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
[16:27:04] :             [docker] 09:27:04.729 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
[16:27:04] :             [docker] 09:27:04.729 [DEBUG] [org.gradle.launcher.daemon.server.health.DaemonStatus] GC rate: 0.0/s
[16:27:04] :             [docker] 09:27:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
[16:27:04] :             [docker] 09:27:04.730 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
[16:27:04] :             [docker] 09:27:04.731 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by rks4in** [comment]
how to download maven repository from docker run command

**Comment by utzcoz** [comment]
In unreliable or restricted network, the dependency downloading job will be failed. If you are in company's restricted network, for example docker or other virtualization environment, you can setup your company's maven mirror to sync Robolectric's dependencies and other dependencies from public maven repository; If you don't want to/can't setup a maven mirror, you can try to write some scripts to download all Robolectric's dependencies and cache them before running Robolectric tests, for example I have created a project: https://github.com/utzcoz/robolectric-android-all-fetcher to download all dependencies at local maven cache, and it will help me to speed up Robolectric unit tests; Also you can follow http://robolectric.org/blog/2017/03/01/hermetic-builds/ to use Gradle script to download all Robolectric dependencies' artifacts, and use downloaded artifacts as dependencies for your project with `robolectric.offline` mode(it also needs `robolectric.dependency.dir` property).
And it's problem is very old, and I will close this issue. Feel free to reopen it if you have other question or problem.
