### ISSUE TITLE
java.util.concurrent.ExecutionException in ShadowSQLiteConnection

### ISSUE THREAD

**Issue by tfKamran** [robolectric/robolectric#2679]
### Description

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-4-thread-1,5,main] []
    at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:469)
    at org.robolectric.shadows.ShadowSQLiteConnection.nativeResetStatementAndClearBindings(ShadowSQLiteConnection.java:298)
    at android.database.sqlite.SQLiteConnection.nativeResetStatementAndClearBindings(SQLiteConnection.java)
    at android.database.sqlite.SQLiteConnection.releasePreparedStatement(SQLiteConnection.java:915)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:519)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
    at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
```
### Steps to Reproduce

Write multiple tests in a single class, all of which query a common SQLiteDB.

Doesn't help even if you open and close the DB in `@Before` and `@After`.
### Reproducible on Robolectric & Android Version

Robolectric v3.0.0, v3.1.2
Android API v21, v22, v23

**Comment by lawrencebautista** [comment]
I am getting this too.. any ideas?
`java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 208. Current pointers for thread Thread[pool-1239-thread-1,5,main] []`

**Comment by satyaattili** [comment]
We are also getting same issues, getting java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 182. Current pointers for thread Thread[pool-53-thread-1,5,main] []

**Comment by caltseng** [comment]
I get the exact same issue. People have suggested the following, but I've verified that our teardown and setup correctly set up our databases. 

https://github.com/robolectric/robolectric/issues/1890

**Comment by jhz-zhangyun** [comment]
How do you solve it?

**Comment by utzcoz** [comment]
Please try the latest Robolectric with native SQLite mode, and feel free to reopen this issue if it still exists.
