### ISSUE TITLE
Robolectric cannot find font file

### ISSUE THREAD

**Issue by HanCheng** [robolectric/robolectric#2686]
### Description
I got error when running robolectric tests that says font files cannot be found. Basically I have xml files that use custom font file, the font file is saved in res folder, when I step up activity instance in Robolectric tests, and the activity is initialized, it will look for the font file in /build/intermediates/res/merged folder , but somehow the robolectric cannot find that font file. The followings are the stack trace.

`android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/fragment_users_list.xml line #-1 (sorry, not yet implemented): Error inflating class com. mycustom.common.views.RobotoTextView

// real issue here
Caused by: java.lang.RuntimeException: Font not found at [build/intermediates/bundles/debug/assets/Roboto-Light.ttf]
at org.robolectric.shadows.ShadowTypeface.createFromAsset(ShadowTypeface.java:73)
at android.graphics.Typeface.createFromAsset(Typeface.java)
at com.mycustom.utils.font.RobotoUtil.getRobotoTypeface(RobotoUtil.java:45)
at com.mycustom.common.views.RobotoTextView.setFontType(RobotoTextView.java:46)
at com.mycustom.common.views.RobotoTextView.<init>(RobotoTextView.java:33)
... 89 more`

It works before, but somehow, it shows this error.

### Robolectric & Android Version
Robolectric version 3.1.2

**Comment by HanCheng** [comment]
Since I also have espresso tests, if i move robolectric tests after espresso tests, robolectric tests will pass. Seems the espresso tests successfully copied the font file into cached file, so that when robolectric tests run, it can get the font file from cache. Still couldn't figure out a solid solution without swapping tests orders.

**Comment by HanCheng** [comment]
duplicate of #2647 . work around can be found in that issue.
