### ISSUE TITLE
android.content.res.Resources$NotFoundException thrown when enabling FastScroller

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#2693]
### Description
When enabling fast-scroll on a list-view (by calling `listView.setFastScrollEnabled(true)`), the unit-test will fail with a `Resources$NotFoundException`. Which is strange.
Moreover, it claims that the resource is of `style` type and not `Drawable`.

### Steps to Reproduce
See https://github.com/menny/deckard/tree/fast-scroll-issue

1.  Create a layout with `ListView`
2.  In the Activity's `onCreate` find that `ListView`
3.  Call `setFastScrollEnabled(true)` on that list-view.

boom: `android.content.res.Resources$NotFoundException: Resource "android:style/Widget_DeviceDefault_NumberPicker" (1150061)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x0 a=765256 r=0x1150061}`
### Robolectric & Android Version
Fails on Robolectric 3.1.4.
Works as expected on 3.1.2

**Comment by menny** [comment]
I used Robolectric official Deckard code to simulate this error.
The unit-test error is:
```
android.content.res.Resources$NotFoundException: Resource "android:style/Widget_DeviceDefault_NumberPicker" (1150061)  is not a Drawable (color or path): TypedValue{t=0x1/d=0x0 a=765256 r=0x1150061}
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2390)
	at android.content.res.Resources.loadDrawable(Resources.java:2330)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.internal.Shadow.directlyOn(Shadow.java:57)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:261)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
	at android.widget.FastScroller.setStyle(FastScroller.java:344)
	at android.widget.FastScroller.__constructor__(FastScroller.java:257)
	at android.widget.FastScroller.<init>(FastScroller.java)
	at android.widget.AbsListView.setFastScrollerEnabledUiThread(AbsListView.java:1274)
	at android.widget.AbsListView.setFastScrollEnabled(AbsListView.java:1258)
	at com.example.activity.DeckardActivity.onCreate(DeckardActivity.java:16)
	at android.app.Activity.performCreate(Activity.java:5933)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:195)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:126)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:356)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at org.robolectric.util.ActivityController.create(ActivityController.java:133)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:227)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:102)
	at com.example.activity.DeckardActivityTest.testSomething(DeckardActivityTest.java:19)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by menny** [comment]
Funny thing, if I change the app (by adding more resources), the ID will be different.

**Comment by hoisie** [comment]
Interestingly, this only fails with sdk = 21. It passes if sdk is set to 22 or 23.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
