### ISSUE TITLE
NullPointerException when running with RoboelectricTestRunner

### ISSUE THREAD

**Issue by benmarten** [robolectric/robolectric#2749]
### Description
I am using the library byte buddy, to do some byte code manipulation, which works great. Now I want to be able to unit test this as well. All our tests are already using Roboelectric.
Running in Android works well, on any Android Version 4 and up, but fails with Roboelectric.
I originally opened an issue with byte buddy, but the author says its most likely an issue within roboelectric: https://github.com/raphw/byte-buddy/issues/216
I would appreciate if someone could look into this and tell me if this can be made working with roboelectric.
```
java.lang.NullPointerException
	at dalvik.system.DexFile.__constructor__(DexFile.java:101)
	at dalvik.system.DexFile.<init>(DexFile.java)
	at dalvik.system.DexFile.loadDex(DexFile.java:151)
	at dalvik.system.DexPathList.loadDexFile(DexPathList.java:265)
	at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)
	at dalvik.system.DexPathList.__constructor__(DexPathList.java:109)
	at dalvik.system.DexPathList.<init>(DexPathList.java)
	at dalvik.system.BaseDexClassLoader.__constructor__(BaseDexClassLoader.java:48)
	at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java)
	at dalvik.system.DexClassLoader.<init>(DexClassLoader.java)
	at net.bytebuddy.android.AndroidClassLoadingStrategy$DexProcessor$ForSdkCompiler.makeClassLoader(AndroidClassLoadingStrategy.java:274)
	at net.bytebuddy.android.AndroidClassLoadingStrategy.load(AndroidClassLoadingStrategy.java:134)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:73)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:4525)
	at com.leanplum.recyclerviewadaptertest.AdapterSwitcher.swizzleRecyclerViewAdapter(AdapterSwitcher.java:39)
	at com.leanplum.recyclerviewadaptertest.AdapterSwitcherTest.testSwizzleRecyclerViewAdapter(AdapterSwitcherTest.java:32)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


Process finished with exit code 255
```

### Steps to Reproduce
`git clone https://github.com/benmarten/RecyclerViewAdapterTest/`
open in Android Studio and run test class: `AdapterSwitcherTest`

### Robolectric & Android Version
robolectric:3.1.4
android: 24.4.1_1
compileSdkVersion 25
buildToolsVersion "25.0.1"
java, bundled with android studio

**Comment by benmarten** [comment]
Is this project still active?

**Comment by jongerrish** [comment]
Yes, it's still active.

I've never used byte buddy but if you search for power mock / Mockito on
the issues list there are some similar issues due to byte code manipulation
/ class loader issues that prevents robolectric working well with these
libraries. We're close to a release that includes API 24/25 support and
resources fixes and these kind of issues will be our next priority so
probably in a minor release end of this year or early Jan.

**Comment by benmarten** [comment]
Is the new release out yet?

**Comment by xian** [comment]
This is still broken in 3.2.2 but we'll have a look at it before the next release.

**Comment by mohitagrawal** [comment]
Is this fixed as part of 3.3 SNAPSHOT?

**Comment by jongerrish** [comment]
Hopefully this has been fixed. Can someone verify it please? We're pushing
3.3 out today hopefully.

**Comment by benmarten** [comment]
So it seems 3.3 runs with our unit tests at least. But some tests fail with:

```
com.thoughtworks.xstream.converters.ConversionException: Cannot convert type com.sun.org.apache.xerces.internal.dom.DeferredElementImpl to type org.w3c.dom.Node
---- Debugging information ----
message             : Cannot convert type com.sun.org.apache.xerces.internal.dom.DeferredElementImpl to type org.w3c.dom.Node
class               : org.robolectric.manifest.AndroidManifest
required-type       : org.robolectric.manifest.AndroidManifest
converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
path                : /org.powermock.modules.junit4.rule.PowerMockStatement$1/outer-class/fNext/next/val$roboMethod/appManifest/applicationNode
line number         : 5978
class[1]            : org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod
class[2]            : org.robolectric.RobolectricTestRunner$HelperTestRunner$1
class[3]            : org.junit.internal.runners.statements.RunBefores
class[4]            : org.powermock.modules.junit4.rule.PowerMockStatement
class[5]            : org.powermock.modules.junit4.rule.PowerMockStatement$1
version             : not available
-------------------------------

	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:456)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:503)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:429)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:281)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:70)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1230)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1214)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1085)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1076)
	at org.powermock.classloading.DeepCloner.clone(DeepCloner.java:55)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:56)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:67)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:43)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Looks like the issue might be: http://stackoverflow.com/a/19097744/2302437
although I'm not finding any ref to that import in roboelectric.... Anyone has a clue?

**Comment by jongerrish** [comment]
These classes should be assignment compatible. Like I said, I think its a
classloader issue. If they are loaded from different classloaders then they
are not assignment compatible.

If you put a breakpoint at that line of code you can execute
com.sun.org.apache.xerces.internal.dom.DeferredElementImpl.class.getClassloader()
and org.w3c.dom.Node.class.getClassloader()

Let us know which classloaders have loaded each class.

**Comment by benmarten** [comment]
Ok, I'll check that. Another issue I'm seeing is:

java.lang.NoSuchMethodError: org.robolectric.Robolectric.buildActivity(Ljava/lang/Class;)Lorg/robolectric/util/ActivityController;

I don't understand how this can break in a minor release? Is roboelectric following semver?

**Comment by benmarten** [comment]
Both class loader vars are null for:
com.sun.org.apache.xerces.internal.dom.DeferredElementImpl.class.getClassloader()
and org.w3c.dom.Node.class.getClassloader()

![screen shot 2017-03-03 at 3 54 35 pm](https://cloud.githubusercontent.com/assets/5960238/23573312/e0fc425a-0029-11e7-95f9-fce02604812f.jpg)

**Comment by jongerrish** [comment]
Interesting:

Javadoc says that some implementations return null for the bootclass loader... but then if both classes were loaded this way they should be assignment compatible
http://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#getClassLoader%28%29

**Comment by jongerrish** [comment]
We do try not to make any breaking changes where possible, we're following a policy of deprecate and remove between versions. Are you sure you don't have an old version of the robolectric jar on the classpath?

**Comment by jongerrish** [comment]
@benmarten Can you post a really simple test case that reproduces the issue? We'll add take this and add this to our set of integration tests and make sure we keep it working.

**Comment by xian** [comment]
`3.3.1` will have a fix for the issue in https://github.com/robolectric/robolectric/issues/2749#issuecomment-284047529 (#2952). If that's masking another problem, please reopen this issue. Thanks!
