### ISSUE TITLE
java.lang.NoSuchFieldException: sSystem

### ISSUE THREAD

**Issue by craone** [robolectric/robolectric#2834]
### Description
Integrated robolectric error
```cmd
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchFieldException: sSystem

	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:332)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:199)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: sSystem
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:174)
	at org.robolectric.shadows.ShadowAssetManager.reset(ShadowAssetManager.java:780)
	at org.robolectric.Shadows.reset(Shadows.java:1644)
	at org.robolectric.Robolectric.reset(Robolectric.java:35)
	at org.robolectric.internal.ParallelUniverse.resetStaticState(ParallelUniverse.java:52)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:319)
	... 19 more
Caused by: java.lang.NoSuchFieldException: sSystem
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:172)
	... 24 more
```

### Steps to Reproduce
MainActivityTest
```java
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class MainActivityTest {
  @Test
  public void btnOpenWelcomingClick() throws Exception {
    MainActivity mainActivity = Robolectric.setupActivity(MainActivity.class);
    mainActivity.findViewById(R.id.btn_openWelcoming).performClick();

    Intent expectedIntent = new Intent(mainActivity, WelcomingActivity.class);
    ShadowActivity shadowActivity = Shadows.shadowOf(mainActivity);
    Intent actualIntent = shadowActivity.getNextStartedActivity();
    Assert.assertEquals(expectedIntent, actualIntent);
  }
```
MainActivity
```java
public class MainActivity extends AppCompatActivity implements View {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        final android.view.View button = findViewById(R.id.btn_openWelcoming);
        button.setOnClickListener(new android.view.View.OnClickListener() {
            @Override
            public void onClick(android.view.View v) {
                startActivity(new Intent(MainActivity.this, WelcomingActivity.class));
            }
        });
    }

    @Override
    public void showProgress() {

    }

    @Override
    public void hideProgress() {

    }

    @Override
    public void showError(String message) {

    }
}

```
### Robolectric & Android Version
```groovy
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    minSdkVersion 15
    targetSdkVersion 23
    testCompile 'org.robolectric:robolectric:3.2.1'
```

**Comment by craone** [comment]
it's ok,causing the dependencies to re-download at runtime.

**Comment by athkalia** [comment]
hey, I am getting this as well. Did you end up fixing it?
Cheers

**Comment by craone** [comment]
My reason is that the network speed is not good,Clear Robolectric Download drivers then re-download once just fine.

**Comment by BrantApps** [comment]
@athkalia - where did you get with this? Just started seeing it too!

**Comment by athkalia** [comment]
Nowhere unfortunately. Was only getting this for 1 test that existed in a specific variant test folder. After a refactor this test was no longer needed, so we removed it altogether

**Comment by paddykily** [comment]
A previously failed repository download could result in this issue. 

- Delete the existing roboelectric version in `/home/user/.m2/repository/org/robolectric/android-all`.
- Re-run your tests (roboelectric will be re-downloaded in the process).

**Comment by zhhp1121** [comment]
> A previously failed repository download could result in this issue.
> 
> * Delete the existing roboelectric version in `/home/user/.m2/repository/org/robolectric/android-all`.
> * Re-run your tests (roboelectric will be re-downloaded in the process).

thanks , it solved problem indeed.
