### ISSUE TITLE
Android.view.InflateException TextView with style set

### ISSUE THREAD

**Issue by mgoovaer** [robolectric/robolectric#2859]
### Description
Getting "android.view.InflateException" when trying to inflate xml that has a textview with the following style set:

```xml
 <TextView
        android:id="@+id/eBilling_payment_date_tv"
        style="@android:style/Widget.DeviceDefault.Light.Spinner"/>
```

Robolectric Error:
```
android.view.InflateException: XML file build/intermediates/res/merged/mock/debug/layout/activity_ebilling_payment.xml line #-1 (sorry, not yet implemented): Error inflating class TextView

	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.humana.myhumana.common.userinterface.ToolbarEnabledActivity.onCreate(ToolbarEnabledActivity.java:20)
	at com.humana.myhumana.ebilling.userinterface.EBillingPaymentActivity.onCreate(EBillingPaymentActivity.java:109)
	at android.app.Activity.performCreate(Activity.java:5133)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:128)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.create(ActivityController.java:125)
	at org.robolectric.util.ActivityController.create(ActivityController.java:135)
	at com.humana.myhumana.ebilling.userinterface.EBillingPaymentActivityTest.setup(EBillingPaymentActivityTest.java:113)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:339)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:199)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff in packages [android, com.humana.myhumana]
	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:868)
	at org.robolectric.shadows.ShadowAssetManager.buildTypedValue(ShadowAssetManager.java:734)
	at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:796)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:221)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:216)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:392)
	at uk.co.chrisjenx.calligraphy.CalligraphyUtils.pullFontPathFromTextAppearance(CalligraphyUtils.java:230)
	at uk.co.chrisjenx.calligraphy.CalligraphyFactory.resolveFontPath(CalligraphyFactory.java:197)
	at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreatedInternal(CalligraphyFactory.java:132)
	at uk.co.chrisjenx.calligraphy.CalligraphyFactory.onViewCreated(CalligraphyFactory.java:114)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$WrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:279)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
	... 42 more
```

### Steps to Reproduce
Robolectric.buildActivity(SomeActivity.class)
^have the layout set to a layout with the TextView defined above.

### Robolectric & Android Version
Robolectric 3.2.2, sdk=18

**Comment by xian** [comment]
It looks like this might be some interaction with the Calligraphy library. If you could provide a github repo with a failing test case we can investigate further. Feel free to reopen. Thanks!

**Comment by mgoovaer** [comment]
@xian you're right. thanks!

**Comment by caltseng** [comment]
@mgoovaer How did you resolve this issue?
