### ISSUE TITLE
FakeHttp.setDefaultHttpResponse causes java.lang.RuntimeException: Stub!

### ISSUE THREAD

**Issue by wongk** [robolectric/robolectric#2872]
### Description
Using FakeHttp.setDefaultHttpResponse causes the following exception:

```
java.lang.RuntimeException: Stub!
	at org.apache.http.params.AbstractHttpParams.__constructor__(AbstractHttpParams.java:37)
	at org.apache.http.params.AbstractHttpParams.<init>(AbstractHttpParams.java)
	at org.apache.http.params.BasicHttpParams.<init>(BasicHttpParams.java)
	at org.robolectric.shadows.httpclient.TestHttpResponse.<init>(TestHttpResponse.java:29)
	at org.robolectric.shadows.httpclient.FakeHttpLayer.setDefaultHttpResponse(FakeHttpLayer.java:95)
	at org.robolectric.shadows.httpclient.FakeHttp.setDefaultHttpResponse(FakeHttp.java:172)
	at com.boxer.exchange.eas.EasGalSearchTests.testGetRequestEntity_forEasAbove14(EasGalSearchTests.java:97)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:538)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:339)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:199)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

### Steps to Reproduce
Use the above method in a test.

### Robolectric & Android Version
Robolectric 3.2.2
Target SDK 25

**Comment by hoisie** [comment]
AndroidHttpClient was removed in SDK 23. Have you tried adding:

```
testCompile 'org.robolectric:shadows-httpclient:3.2.2'
```

To your build.gradle?

**Comment by wongk** [comment]
Yes. This was working just fine prior to updating Robolectric to 3.2.2. We were using 3.1.2.

**Comment by shafty023** [comment]
Bump? I'm having this issue as well.

**Comment by xian** [comment]
Having trouble reproducing this. Can you provide a git repo or pull request with a failing test? Thanks!

**Comment by wongk** [comment]
It turns out this was due to the inclusion of:

exclude group: 'commons-logging', module: 'commons-logging'
exclude group: 'org.apache.httpcomponents', module: 'httpclient'

In our 'testCompile('org.robolectric:shadows-httpclient:3.2.2') {' block. This was copied from other robolectric components.
