### ISSUE TITLE
getMainLooper NulPointerException

### ISSUE THREAD

**Issue by zhangyanru** [robolectric/robolectric#2876]
I meet problem:

```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.getMainLooper(ShadowLooper.java:70)
	at android.os.Looper.getMainLooper(Looper.java)
	at android.database.sqlite.SQLiteDatabase.isMainThread(SQLiteDatabase.java:391)
	at android.database.sqlite.SQLiteDatabase.getThreadDefaultConnectionFlags(SQLiteDatabase.java:381)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1253)
	at ....rawQuery(AnalyticsDB.java:136)
	...
```
 and I need help. Thanks.

**Comment by xian** [comment]
What version of Robolectric are you using? If it's not `3.3`, try that. Feel free to reopen otherwise. :-)

**Comment by GitHubMurt** [comment]
I'm getting that NPE in

```
  public ComponentController(T component) {
    myself = (C) this;
    this.component = component;
    shadowMainLooper = Shadow.extract(**_Looper.getMainLooper()_**);
  }
```

For
```
@RunWith(RobolectricTestRunner ::class)
@Ignore
open class MyRobolectric {

    @get:Rule
    val rule = PowerMockRule()

    lateinit var activity:MyActivity
    lateinit var context: Context

    @Before
    fun setupData(){
        activity = Robolectric.setupActivity(MyrActivity::class.java)
}}
```

I'm using 
    testImplementation "org.robolectric:robolectric:4.1"
        classpath 'com.android.tools.build:gradle:3.3.0'
AndroidStudio 3.3
