### ISSUE TITLE
fitsSystemWindow & Calling ActivityController.visible() results in java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ArtisticPsychology** [robolectric/robolectric#2898]
### Description

This problem occurs seemingly at the intersection of CoordinatorLayout, fitsSystemWindow, ViewPagers, and Fragments.  I'm getting the following exception when I have an activity with a ViewPager inside a CoordinatorLayout.  In the activity code, it sets a FragmentAdapter on the ViewPager and the corresponding fragment contains any View inside another layout.  Code is below the exception.

Because I can't call visible(), it means I'm unable to test more complex behavior between the Activity and fragments, along with UI elements that depend on being attached to the Window.

### Robolectric & Android Version

commit a15742afe9f4676b37e37be6db1fbea11a080bd0 & Lollipop

#### Exception
```
java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1631)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:704)
	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:776)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:165)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:126)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:355)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:257)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:238)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:221)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:211)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:79)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:113)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:313)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:364)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:34)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.addView(ViewGroup.java:3709)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:810)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
	at com.REDACTED.fragments.ContentFragment.onCreateView(ContentFragment.java:16)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:704)
	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:776)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5463)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2560)
	at android.view.View.measure(View.java:17430)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2001)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1166)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:165)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:126)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:355)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:257)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:238)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:221)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:211)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:79)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:113)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:313)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:364)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.util.ActivityController.visible(ActivityController.java:179)
	at com.REDACTED.NewTestActivityTest.testRobolectricVisible(NewTestActivityTest.java:56)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:538)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:339)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:240)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:65)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:55)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:231)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:199)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:316)
	7 REDACTED LINES
```

#### Test Code
```java
  @Test
  public void testRobolectricVisible() {
    testActivity = Robolectric.buildActivity(NewTestActivity.class)
        .create().start().resume().visible()
        .get();
    assertThat(true).isTrue();
  }
```

#### Activity Code
```java
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentManager;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import com.REDACTED.fragments.ContentFragment;

public class NewTestActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_new_test);
    setupPager();
  }

  private void setupPager() {
    // Set up the pager.
    FragmentAdapter pagerAdapter = new FragmentAdapter(getSupportFragmentManager());
    ViewPager pager = (ViewPager) findViewById(R.id.pager);

    pager.setAdapter(pagerAdapter);
  }

  public static class FragmentAdapter extends FragmentPagerAdapter {

    public FragmentAdapter(FragmentManager fm) {
      super(fm);
    }

    @Override
    public int getCount() {
      return 2;
    }

    @Override
    public Fragment getItem(int position) {
      return new ContentFragment();
    }
  }
}
```

#### Activity XML
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/coordinator_layout"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindows="true">
  
  <android.support.v4.view.ViewPager
    android:id="@+id/pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    
  </android.support.v4.view.ViewPager>
</android.support.design.widget.CoordinatorLayout>
```

#### Fragment Code
```java
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;


public class ContentFragment extends Fragment {
  @Override
  public View onCreateView(LayoutInflater inflater, ViewGroup container,
      Bundle savedInstanceState) {
    return inflater.inflate(R.layout.test_fragment, null /* parent */);
  }
}
```

#### Fragment XML
```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical">
  
  <!-- Seemingly, this can be any View -->
  <TextView
    android:id="@+id/inner_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:text="testesetest"/>

</LinearLayout>
```

#### Fragment contains only one View[group]

Delete the one of the two Views in the fragment xml above:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.RecyclerView
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/recycler"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:scrollbars="vertical" />
```
#### No fragment; Activity with Coordinator with Viewpager with Nested Views

Also omit the method setupPager() in the Activity.

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/coordinator_layout"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindow="true">

  <android.support.v4.view.ViewPager
    android:id="@+id/pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <LinearLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:orientation="vertical">

      <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical" />

    </LinearLayout>

    <!-- omitting duplicate LinearLayout/RecyclerView -->

  </android.support.v4.view.ViewPager>
</android.support.design.widget.CoordinatorLayout>
```

#### Put Fragment directly into Activity xml file

Again, omit setupPager() in the Activity.

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:id="@+id/coordinator_layout"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:fitsSystemWindows="true">

  <android.support.v4.view.ViewPager
    android:id="@+id/pager"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment android:name="com.REDACTED.fragments.ContentFragment"
      android:id="@+id/something_unique"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>

    <fragment android:name="com.REDACTED.fragments.ContentFragment"
      android:id="@+id/something_really_unique"
      android:layout_width="match_parent"
      android:layout_height="match_parent"/>

  </android.support.v4.view.ViewPager>
</android.support.design.widget.CoordinatorLayout>
```

---
Clearly, I tried to be exhaustive the first time around, but let me know if you need more details.

**Comment by jdvp** [comment]
I am also able to reproduce this defect (or at least something very similar) without coordinator layout in robolectric version 3.6.1 testing in API 26. 

If we only have the single view in each of the fragments in the view pager the error goes away (as mentioned above) but it isn't really realistic to have a fragment with a single view.

**Comment by jgomez-handy** [comment]
I've ran into something simlar, I've added my findings in #3698 
linking here to documentation.
