### ISSUE TITLE
NullPointerException when calling obtainStyledAttributes when testing build variants

### ISSUE THREAD

**Issue by mauricelam** [robolectric/robolectric#2904]
### Description
```
java.lang.NullPointerException
	at org.robolectric.res.ThemeStyleSet$OverlayedStyle.equals(ThemeStyleSet.java:67)
	at org.robolectric.res.ThemeStyleSet.apply(ThemeStyleSet.java:29)
	at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:479)
	at android.content.res.AssetManager.applyThemeStyle(AssetManager.java)
	at android.content.res.Resources$Theme.applyStyle(Resources.java:1323)
	at android.view.ContextThemeWrapper.onApplyThemeResource(ContextThemeWrapper.java:128)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:140)
	at android.view.ContextThemeWrapper.getTheme(ContextThemeWrapper.java:101)
	at android.content.Context.obtainStyledAttributes(Context.java:436)
```

It failed when I call `new ContextThemeWrapper(application, R.style.MyTheme).obtainStyledAttributes(...)`

### Steps to Reproduce
Create Android gradle project with two build variants. One depend on support-appcompat-v7 and the other do not.

One of the build variants have resources at
    `build/intermediates/res/merged/variant1/debug`
but `build/intermediates/res/merged/variant2/` does not exist.

I think this confused GradleManifestFactory and tried to look for resources in a directory that doesn't exist.

### Robolectric & Android Version
Robolectric 3.2. Android 7.0.0_r1

**Comment by passy** [comment]
My stacktrace looks a bit different. I'm calling `Context#getTheme()` which also ends up in `ThemeStyleSet#apply`.

Robolectric 3.3.0.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
