### ISSUE TITLE
System.arraycopy() NoSuchMethodError

### ISSUE THREAD

**Issue by niedzielski** [robolectric/robolectric#2954]
### Description
System.arraycopy() is not available when `Html.fromHtml(String, int, ImageGetter, TagHandler)` is invoked with a long String of HTML on API 24. However, a shorter String works fine and so does the deprecated `Html.fromHtml(String, ImageGetter, TagHandler)`.

```
java.lang.NoSuchMethodError: java.lang.System.arraycopy([CI[CII)V

	at org.ccil.cowan.tagsoup.HTMLScanner.save(HTMLScanner.java:679)
	at org.ccil.cowan.tagsoup.HTMLScanner.scan(HTMLScanner.java:616)
	at org.ccil.cowan.tagsoup.Parser.parse(Parser.java:450)
	at android.text.HtmlToSpannedConverter.convert(Html.java:758)
	at android.text.Html.fromHtml(Html.java:245)
	at com.niedzielski.android.robolectricarraycopybug.ArraycopyTest.testArraycopyLong(ArraycopyTest.java:36)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:487)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

### Steps to Reproduce
Please examine this repo for a simple repro case. Specifically [this line](https://github.com/niedzielski/robolectric-arraycopy-bug/commit/fc269a110b45f1eaaea1479547c3d9e54645be85#diff-ee9d9872eefffbe35172a531fffe2f04R37).

### Robolectric & Android Version
Robolectric v3.3 targeting API 24.

### See Also
- #1605

**Comment by xian** [comment]
Fixed by #2959.

**Comment by niedzielski** [comment]
:+1: @xian, works perfectly. Thank you!

**Comment by xian** [comment]
Thanks for the test cases @niedzielski!
