### ISSUE TITLE
 java.lang.annotation.AnnotationFormatError at Android Studio 2.3

### ISSUE THREAD

**Issue by wulaoh** [robolectric/robolectric#2955]
### Description
when upgrade Android Studio 2.3, run the before test case get below error:

```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:612)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:132)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:224)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:93)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Process finished with exit code 1
Empty test suite.

### Steps to Reproduce
1. Upgrade the Android Studio from 2.23 to 3.3, 
2. adjust the build grade to 2.3
3. adjust the grade to gradle-3.3-all.zip
4. clean project and rebuild project
5. run test case
### Robolectric & Android Version
Robolectric: 3.3
Android SDK: 23

**Comment by panzerfahrer** [comment]
Are there any insights or potential workarounds?

Could this be related to #1620

**Comment by wulaoh** [comment]
sorry, it's my mistake, delete this directory can fix it. thanks.

**Comment by jongerrish** [comment]
Sounds like a gradle bug. Try `rm -rf .gradle` as a workaround. Please reopen if not.
