### ISSUE TITLE
Can't find AndroidManifest with Gradle Plugin 2.3.0

### ISSUE THREAD

**Issue by Kaminiak** [robolectric/robolectric#2967]
### Description
Before update to the newest Android Studio 2.3 everything worked fine. After update, all my tests fail, because of missing Android Manifest. 

Stack trace: 
```
No such manifest file: build/intermediates/bundles/debug/AndroidManifest.xml

android.content.res.Resources$NotFoundException: String resource ID #0x7f080096

	at android.content.res.Resources.getText(Resources.java:274)
	at android.content.res.Resources.getString(Resources.java:360)
	at android.content.Context.getString(Context.java:376)
	at com.my.application.MyApplication.initCalligraphy(MyApplication.java:58)
	at com.my.application.MyApplication.onCreate(MyApplication.java:38)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:137)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:289)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
It crashes in my custom application class, in regular context.getString() call.

### Robolectric & Android Version
Robolectric: 3.3.1
Android Studio: 2.3
Gradle Plugin: 2.3.0
Gradle: 3.3
Android: 24

**Comment by Kaminiak** [comment]
Ok, I found the solution in: https://github.com/robolectric/robolectric/issues/2949
Need to remove all test configurations, and then set working directory to `$MODULE_DIR$` in Android JUnit configuration
