### ISSUE TITLE
GreenDao + Robolectric: Illegal connection pointer

### ISSUE THREAD

**Issue by bschnack** [robolectric/robolectric#3004]
### Description
When running tests, after two tests that use GreenDao, the tests will start to fail with "Illegal connection pointer." It always happens after the second test, regardless of order, whether they are all in one file, each test is in a separate file, etc.

Other posts mention clearing out Singletons but we do not use an singletons with GreenDao. mDaoSession is a variable that gets reset every time we create our service. The service is created and torn down for every test and we close the database at the end of every test.

### Steps to Reproduce
The class annotations on all of our tests are:
@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.M, constants = BuildConfig.class, assetDir = "../../main/assets")

During our tests, we are writing things to the database and all of that works fine across tests. The failure only happens when we call:

```
            Collection<AbstractDao<?, ?>> daos = mDaoSession.getAllDaos();
            try {
                for (AbstractDao dao : daos) {
                    dao.deleteAll();
                }
            } catch (SQLiteException e) {
                AppAssert.fail("Failed to clear database", e, AppAssert.ASSERT_LEVEL_NORMAL);
            }
```

with exception:

> java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 568. Current pointers for thread Thread[pool-10-thread-1,5,main] [1195]
> 
> 	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:604)
> 	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:523)
> 	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:91)
> 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
> 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
> 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
> 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
> 	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
> 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
> 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
> 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
> 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
> 	at org.greenrobot.greendao.database.StandardDatabase.execSQL(StandardDatabase.java:37)
> 	at org.greenrobot.greendao.AbstractDao.deleteAll(AbstractDao.java:616)

It is important to note that reading and writing to the database is all working fine

### Robolectric & Android Version
Relevant parts of build.gradle:
    compileSdkVersion 25
    buildToolsVersion '25.0.2'

    compile 'org.greenrobot:greendao:3.2.0'
    testCompile 'org.robolectric:robolectric:3.3.1'
    testCompile 'org.robolectric:shadows-support-v4:3.3.1'
    testCompile 'org.robolectric:shadows-multidex:3.3.1'
    testCompile 'org.robolectric:shadows-play-services:3.3.1'

**Comment by hoisie** [comment]
Do you have a small sample app that demonstrates this issue?

**Comment by mores** [comment]
I am seeing this same issue.
`    java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[Test worker,5,main] []
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:366)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getStatement(ShadowSQLiteConnection.java:375)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.executeStatementOperation(ShadowSQLiteConnection.java:704)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.resetStatementAndClearBindings(ShadowSQLiteConnection.java:686)
        at org.robolectric.shadows.ShadowSQLiteConnection.nativeResetStatementAndClearBindings(ShadowSQLiteConnection.java:297)
        at org.robolectric.shadows.ShadowSQLiteConnection.nativeResetStatementAndClearBindings(ShadowSQLiteConnection.java:292)
        at android.database.sqlite.SQLiteConnection.nativeResetStatementAndClearBindings(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.releasePreparedStatement(SQLiteConnection.java:908)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:520)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
        at android.database.sqlite.SQLiteDatabase.compileStatement(SQLiteDatabase.java:992)
        at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:155)
        at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91)
        at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:450)
        at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:310)
`

I will work on a sample app that reproduces this.

**Comment by mreid-projects** [comment]
I'm also getting the same error after migrating to androidx, @mores did you manage to fix the problem?

java.lang.IllegalStateException: Illegal connection pointer 5395. Current pointers for thread Thread[SDK 28 Main Thread,5,SDK 28] [5734]

	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:369)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:419)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:90)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1347)
	at com.elt.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.findJobsByTags(SqliteJobQueue.java:287)
	at com.elt.passsystem.domain.service.fileupload.PendingUploadService.removeUserNameFromOfflineUploadsSharedPreferences(PendingUploadService.java:81)
	at com.elt.path.android.jobqueue.persistentQueue.sqlite.FileSqliteJobQueue.delete(FileSqliteJobQueue.java:114)
	at com.elt.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove(SqliteJobQueue.java:187)
	at com.elt.path.android.jobqueue.JobQueueTestBase.testFindJobHolderById(JobQueueTestBase.java:487)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by slott** [comment]
This is interesting - I just got this out of the blue...

One of my tests fails with
Illegal connection pointer 1075. Current pointers for thread Thread[SDK 27 Main Thread,5,SDK 27] [

Its not the only DB test that I have - so it does feel a bit odd...

**Comment by slott** [comment]
just now tried the 4.4-snapshot and all was fine... 🤔

**Comment by utzcoz** [comment]
Anyone has this issue please try the latest Robolectric and enable native SQLiteMode to test it. And feel free to reopen this issue or report new issue if it still exists.
