### ISSUE TITLE
Fonts are not being found and thus tests are failing

### ISSUE THREAD

**Issue by bhavinmdesai** [robolectric/robolectric#3008]
### Description
When the test get executed on the mac build server it fails with following exception:

`com.rewardle.tabmerchantapp.EmailValidatorTest > testNullEmailAddress FAILED
java.lang.RuntimeException: Font not found at [build/intermediates/bundles/live/release/assets/font/font_helvetica_bold.ttf]
at org.robolectric.shadows.ShadowTypeface.createFromAsset(ShadowTypeface.java:77)
             at android.graphics.Typeface.createFromAsset(Typeface.java)
             at com.rewardle.tabmerchantapp.TabMerchantApplication.initializeFonts(TabMerchantApplication.java:975)
             at com.rewardle.tabmerchantapp.TabMerchantApplication.init(TabMerchantApplication.java:554)
             at com.rewardle.tabmerchantapp.TabMerchantApplication.onCreate(TabMerchantApplication.java:125)
             at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:137)
             at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:289)
             at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
             at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
             at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
             at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
             at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
             at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
             at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
             at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
             at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
             at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
             at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             at java.lang.reflect.Method.invoke(Method.java:498)
             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
             at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
             at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
             at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
             at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
             at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
             at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
             at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             at java.lang.reflect.Method.invoke(Method.java:498)
             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
             at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
             at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
             at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
             at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
             at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
             at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
             at java.lang.Thread.run(Thread.java:745)`
### Steps to Reproduce
Umm... Not sure
### Robolectric & Android Version

`testCompile 'org.robolectric:robolectric:3.2.2'`
`testCompile 'org.robolectric:shadows-multidex:3.2.2'`

`compileSdkVersion 25`
`buildToolsVersion "25.0.2"`
`classpath 'com.android.tools.build:gradle:2.3.0'`

**Comment by hidroh** [comment]
@bhavinmdesai see #2647 for discussion and some workaround.

**Comment by jongerrish** [comment]
I think this should be fixed in Robolectric 4.0 with binary resources. Please give that a try and reopen if its still an issue
