### ISSUE TITLE
ShadowAssetManager not retrieving styles correctly

### ISSUE THREAD

**Issue by saantiaguilera** [robolectric/robolectric#3018]
### Description

ShadowAssetManager doesnt retrieve the styles correctly (the theme contains all except 1 attribute, which when missing ends up throwing an exception upon inflating -> because a view uses it of course)

Stacktrace:
```
com.my.package.quotation.QuotationActivityTest > testQuoteIntentionDifferentSites FAILED
    android.view.InflateException: XML file build/intermediates/res/merged/debug/layout/quotation_activity.xml line #-1 (sorry, not yet implemented): Error inflating class com.my.package.ui.widgets.MySpinner
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.my.package.sdk.AbstractMyActivity.setupCustomLayout(AbstractMyActivity.java:825)
        at com.my.package.sdk.AbstractMyActivity.addCustomLayoutToAbstractOne(AbstractMyActivity.java:770)
        at com.my.package.sdk.AbstractMyActivity.setContentView(AbstractMyActivity.java:729)
        at com.my.package.quotation.QuotationActivity.onCreate(QuotationActivity.java:99)
        at android.app.Activity.performCreate(Activity.java:5933)
        at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:231)
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:128)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
        at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
        at org.robolectric.util.ActivityController.create(ActivityController.java:125)
        at com.my.package.testing.AbstractRobolectricTest.createActivity(AbstractRobolectricTest.java:197)
        at com.my.package.testing.AbstractRobolectricTest.startActivity(AbstractRobolectricTest.java:266)
        at com.my.package.testing.AbstractRobolectricTest.startActivity(AbstractRobolectricTest.java:293)
        at com.my.package.quotation.QuotationActivityTest.testQuoteIntentionDifferentSites(QuotationActivityTest.java:110)

        Caused by:
        java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createView(LayoutInflater.java)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
            at android.view.LayoutInflater$FactoryMerger.$$robo$$onCreateView(LayoutInflater.java:177)
            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:733)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:806)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:809)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:504)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
            at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:365)
            at android.view.LayoutInflater.inflate(LayoutInflater.java)
            at com.my.package.sdk.AbstractMyActivity.setupCustomLayout(AbstractMyActivity.java:825)
            at com.my.package.sdk.AbstractMyActivity.addCustomLayoutToAbstractOne(AbstractMyActivity.java:770)
            at com.my.package.sdk.AbstractMyActivity.setContentView(AbstractMyActivity.java:729)
            at com.my.package.quotation.QuotationActivity.onCreate(QuotationActivity.java:99)
            at android.app.Activity.$$robo$$performCreate(Activity.java:5933)
            at android.app.Activity.performCreate(Activity.java)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            ... 9 more

            Caused by:
            java.lang.RuntimeException: no value for com.my.package.quotation:attr/MySpinnerStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style com.my.package.quotation:Theme_MLTheme (and parents) (forced)]
                at org.robolectric.shadows.ShadowAssetManager.buildTypedValue(ShadowAssetManager.java:721)
                at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:796)
                at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:221)
                at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
                at android.content.Context.obtainStyledAttributes(Context.java:460)
                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                at com.my.package.ui.widgets.MySpinner.<init>(MySpinner.java:86)
                at com.my.package.ui.widgets.MySpinner.<init>(MySpinner.java:70)
                at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
                at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:177)
                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                at com.my.package.sdk.AbstractMyActivity.setupCustomLayout(AbstractMyActivity.java:825)
                at com.my.package.sdk.AbstractMyActivity.addCustomLayoutToAbstractOne(AbstractMyActivity.java:770)
                at com.my.package.sdk.AbstractMyActivity.setContentView(AbstractMyActivity.java:729)
                at com.my.package.quotation.QuotationActivity.onCreate(QuotationActivity.java:99)
                at android.app.Activity.performCreate(Activity.java:5933)
                ... 9 more
```

Some images that might be useful (See the spinner style missing in the theme):

![screen shot 2017-04-04 at 10 14 42 pm 1](https://cloud.githubusercontent.com/assets/9096015/24713054/ebe457e4-19fa-11e7-9de7-4bf555f9799c.png)
![image1](https://cloud.githubusercontent.com/assets/9096015/24713059/ee4040a2-19fa-11e7-9881-ff229686de02.png)

Needless to say, the theme is setted correctly since the context passed in the constructor has it attached just before inflating the custom view that will explode.

The theme is setted from the `<application>` tag in the manifest

### Steps to reproduce

If having from a library a
```
<declared-styleable name="something">
  <attr name="attritem" format="reference" />
</declared-styleable>
```

And a Theme in the library implementing the `attritem` attr, from an application consuming the library, when inflating custom views that use it (the custom view is in the library, the custom view inflates an xml which inside has a 
```xml
  <CustomView
    ...
    style="attr?attrItem >
      ...
```
they wont find it and will throw a 

```
java.lang.RuntimeException: no value for com.package.to.my.application/attritem in theme with applied styles: [Style android:Theme_something (and parents) (forced), Style com.package.to.my.application:ThemeTheLibraryImplementsWithAttrItem (and parents) (forced)]
```

### Robolectric & Android Version
Robolectric 3.3.2 / 3.2.2 / 3.1.4
Android: 25 / BT: 25.0.2 / SupportLib: 25.3.1

**Comment by saantiaguilera** [comment]
Found the culprit, I had tests running for api level X and had styles for X and the default.

The attribute was only in the default (my bad not setting it in both), android transparently fallbacks to the attribute from the defaults if not found in the specific api level style, while robolectric seems to not do it, hence its not found in the shadowsassetmanager.
