### ISSUE TITLE
Firebase callbacks when running with Robolectric are not Invoked

### ISSUE THREAD

**Issue by adizhol** [robolectric/robolectric#3032]
### Description
I tried to create an end-to-end test that reads and stores data in Firbase database, but I can't even get it to fetch existing data.
There are no errors or exceptions.

I'm new to Android programming, so I might be missing something.

### Steps to Reproduce
```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class DataLayerTest {
    MainActivity activity = Robolectric.setupActivity(MainActivity.class);

    @Before
    public void setup() {      
        activity = Robolectric.buildActivity(MainActivity.class).create().get();
    }

    FirebaseOptions options = new FirebaseOptions.Builder()
            .setApiKey("A...s")
            .setApplicationId("1:10...7c527e8")
            .setDatabaseUrl("https://myapp.firebaseio.com/")
            .build();
    FirebaseApp testApp = FirebaseApp.initializeApp(activity.getApplicationContext(), options, "test app");
    FirebaseDatabase testDatabase = FirebaseDatabase.getInstance(testApp);
    DatabaseReference firebaseReference = testDatabase.getReference();

@Test
    public void testExample() throws Exception{
       firebaseReference.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                for (DataSnapshot data : dataSnapshot.getChildren())
                {
                    System.out.println(dataSnapshot.getValue(String.class));
                }
            }
            @Override
            public void onCancelled(DatabaseError databaseError) {       }
        });
}
```

### Robolectric & Android Version
robolectric:3.3.2
firebase-database:10.0.1
android sdk 25

**Comment by b22n** [comment]
+1

**Comment by cutiko** [comment]
Hello

I'm getting the same problem, seems to be related with this https://github.com/robolectric/robolectric/issues/1171

```
Exception in thread "TubeSockReader-1" java.lang.UnsatisfiedLinkError: com.android.org.conscrypt.NativeCrypto.get_cipher_names(Ljava/lang/String;)[Ljava/lang/String;
	at com.android.org.conscrypt.NativeCrypto.get_cipher_names(Native Method)
	at com.android.org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:764)
	at com.android.org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:58)
	at com.android.org.conscrypt.Conscrypt.newPreferredSSLContextSpi(Conscrypt.java:111)
	at android.net.SSLCertificateSocketFactory.makeSocketFactory(SSLCertificateSocketFactory.java:221)
	at android.net.SSLCertificateSocketFactory.getDelegate(SSLCertificateSocketFactory.java:250)
	at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:539)
	at com.google.firebase.database.tubesock.WebSocket.createSocket(com.google.firebase:firebase-database@@16.0.5:318)
	at com.google.firebase.database.tubesock.WebSocket.runReader(com.google.firebase:firebase-database@@16.0.5:358)
	at com.google.firebase.database.tubesock.WebSocket.access$000(com.google.firebase:firebase-database@@16.0.5:47)
	at com.google.firebase.database.tubesock.WebSocket$2.run(com.google.firebase:firebase-database@@16.0.5:143)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "TubeSockReader-2" java.lang.NoClassDefFoundError: Could not initialize class com.android.org.conscrypt.NativeCrypto
	at com.android.org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:58)
	at com.android.org.conscrypt.Conscrypt.newPreferredSSLContextSpi(Conscrypt.java:111)
	at android.net.SSLCertificateSocketFactory.makeSocketFactory(SSLCertificateSocketFactory.java:221)
	at android.net.SSLCertificateSocketFactory.getDelegate(SSLCertificateSocketFactory.java:250)
	at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:539)
	at com.google.firebase.database.tubesock.WebSocket.createSocket(com.google.firebase:firebase-database@@16.0.5:318)
	at com.google.firebase.database.tubesock.WebSocket.runReader(com.google.firebase:firebase-database@@16.0.5:358)
	at com.google.firebase.database.tubesock.WebSocket.access$000(com.google.firebase:firebase-database@@16.0.5:47)
	at com.google.firebase.database.tubesock.WebSocket$2.run(com.google.firebase:firebase-database@@16.0.5:143)
	at java.lang.Thread.run(Thread.java:745)
```
For me this seems similar because:

 - `java.lang.UnsatisfiedLinkError`
 - `at com.google.firebase.database.tubesock.WebSocket.createSocket`

I'm guessing Firebase Database library is trying to call Conscrypt but can't find it

**Comment by slott** [comment]
Getting the same with all the latest libs as well...

**Comment by utzcoz** [comment]
Hi @cutiko , @adizhol , https://github.com/robolectric/robolectric/releases/tag/robolectric-4.9-alpha-1 Robolectric 4.9 alpha 1 was released today, and it brings ConscryptMode supporting. Could you try it and check whether this problem still exists?

**Comment by utzcoz** [comment]
> Hi @cutiko , @adizhol , https://github.com/robolectric/robolectric/releases/tag/robolectric-4.9-alpha-1 Robolectric 4.9 alpha 1 was released today, and it brings ConscryptMode supporting. Could you try it and check whether this problem still exists?

As this comment said, please try Robolectric 4.9 with `ConscryptMode`. Feel free to reopen this issue if it doesn't fix this issue for you.
