### ISSUE TITLE
Robolectric is completely broken with the Android Gradle plugin 2.4.0-alpha6

### ISSUE THREAD

**Issue by SUPERCILEX** [robolectric/robolectric#3039]
### Steps to Reproduce

```
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set static org.robolectric.internal.bytecode.ClassHandler field org.robolectric.internal.bytecode.RobolectricInternals.classHandler to org.robolectric.internal.bytecode.ShadowWrangler
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:174)
	at org.robolectric.internal.bytecode.Sandbox.configure(Sandbox.java:52)
	at org.robolectric.internal.SandboxTestRunner.configureShadows(SandboxTestRunner.java:169)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:181)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set static org.robolectric.internal.bytecode.ClassHandler field org.robolectric.internal.bytecode.RobolectricInternals.classHandler to org.robolectric.internal.bytecode.ShadowWrangler
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:159)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:172)
	... 40 more
Caused by: java.lang.IllegalArgumentException: Can not set static org.robolectric.internal.bytecode.ClassHandler field org.robolectric.internal.bytecode.RobolectricInternals.classHandler to org.robolectric.internal.bytecode.ShadowWrangler
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(UnsafeStaticObjectFieldAccessorImpl.java:79)
	at java.lang.reflect.Field.set(Field.java:764)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:157)
	... 41 more
```

### Robolectric & Android Version
Robolectric: `3.3.2`
Android: `25`

**Comment by SUPERCILEX** [comment]
Running it through Gradle on Windows BTW.

**Comment by SUPERCILEX** [comment]
Can confirm that it's also broken on Ubuntu

**Comment by SUPERCILEX** [comment]
@xian Any updates on this?

**Comment by samtstern** [comment]
Just ran into this as well.

**Comment by SUPERCILEX** [comment]
@samtstern Lol, feel my pain. 😄

**Comment by samtstern** [comment]
This went away when I removed these lines from my `RobolectricTestRunner`:

```java
    @Override
    public InstrumentationConfiguration createClassLoaderConfig(FrameworkMethod method) {
        InstrumentationConfiguration.Builder builder = InstrumentationConfiguration.newBuilder();

        builder.addInstrumentedClass(AuthHelper.class.getName());
        builder.addInstrumentedClass(FacebookProvider.class.getName());
        builder.addInstrumentedClass(GoogleProvider.class.getName());
        builder.addInstrumentedClass(LoginManager.class.getName());

        return builder.build();
    }
```

**Comment by SUPERCILEX** [comment]
@samtstern Oh interesting! Could you try using this in our `CustomRobolectricGradleTestRunner`?
```java
@Override
public InstrumentationConfiguration createClassLoaderConfig(Config config) {
    return InstrumentationConfiguration.newBuilder()
            .withConfig(config)
            .addInstrumentedClass(AuthHelper.class.getName())
            .addInstrumentedClass(FacebookProvider.class.getName())
            .addInstrumentedClass(GoogleProvider.class.getName())
            .addInstrumentedClass(LoginManager.class.getName())
            .build();
}
```

The super call includes a `withConfig`, that might be what we're missing.

**Comment by samtstern** [comment]
@SUPERCILEX  that method is gone in `3.4`.

**Comment by SUPERCILEX** [comment]
@samtstern Ok, turns out Robolectric keeps their docs up to date (yay! 😄) and we don't need our `CustomRobolectricGradleTestRunner` anymore. I just upgraded to Robolectric `3.4`, removed the `CustomRobolectricGradleTestRunner`, and now everything works magically! 😄 🎉 Do you want me to submit a PR or are you good?

**Comment by samtstern** [comment]
@SUPERCILEX yep seeing the same (with not needing the custom runner) but still having two test failures.  Almost there!

**Comment by SUPERCILEX** [comment]
@samtstern SGTM! Maybe try also removing these lines in our `auth.gradle`:
```groovy
// See https://github.com/robolectric/robolectric/issues/1932#issuecomment-219796474
testCompile 'org.khronos:opengl-api:gl1.1-android-2.1_r1'
```

The tests passed without an issue for me with or without those lines and I don't see why the environment would be messing with our tests. Good luck! 😄 

Going to close this issue since the solution was to remove our custom test runner.
