### ISSUE TITLE
java.lang.IllegalArgumentException: class com.android.app.R contains final fields

### ISSUE THREAD

**Issue by samjith** [robolectric/robolectric#3049]
### Description
Exception while testing android  app with Robolectric
java.lang.IllegalArgumentException: class com.android.app.R contains final fields, these will be inlined by the compiler and cannot be remapped.
	at org.robolectric.res.ResourceRemapper.remapRClass(ResourceRemapper.java:77)
	at org.robolectric.res.ResourceRemapper.remapRClass(ResourceRemapper.java:44)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:18)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

### Steps to Reproduce
I am testing a legacy app with resources distributed across 3 packages.
So I extended RobolectricTestRunner and modified resource path as below.

 ```
return new AndroidManifest(Fs.fileFromPath(manifestPath), Fs.fileFromPath(resDir), Fs.fileFromPath(assetsDir)) {
            @Override
            public List<ResourcePath> getIncludedResourcePaths() {
                List<ResourcePath> paths = super.getIncludedResourcePaths();
              
                paths.add(new ResourcePath(getRClass(),Fs.fileFromPath("../pkg1/res/"), getAssetsDirectory()));
                paths.add(new ResourcePath(getRClass(), Fs.fileFromPath("../pkg2/res/"), getAssetsDirectory()));
                paths.add(new ResourcePath(getRClass(), Fs.fileFromPath("../pkg2/res/"), getAssetsDirectory()));
                return paths;
            }
```

### Robolectric & Android Version
Robolectric : 3.3.2
sdk : 23

**Comment by samjith** [comment]
I don't see this exception if use robolectric 3.1.1 , with all other settings same.

**Comment by hazems** [comment]
I see this issue as well after upgrading to Robolectric 3.3.2.

**Comment by mauricelam** [comment]
I see this issue as well on Robolectric 3.3. The workaround I used was to replace `getRClass()` with `null`. I think that prevents Robolectric from remapping the resource IDs, which is only needed for Maven anyway.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
