### ISSUE TITLE
Tests fail, minimal codebase

### ISSUE THREAD

**Issue by milosmns** [robolectric/robolectric#3054]
### Description

Tests fail with Robolectric test runner in an Android library

### Steps to Reproduce, Robolectric & Android Version

Just run the linked test class; tests fail both from Studio and from the command line.
Library source is available in the repository. It's minimal, please check it out.

Activity setup: https://github.com/milosmns/silly-android/blob/master/sillyandroid/src/test/java/me/angrybyte/sillyandroid/parsable/AnnotationParserTest.java#L146
The activity class is just a few lines above the linked line.

**Error**:
```
android.content.res.Resources$NotFoundException: String resource ID #0x7f050000

	at android.content.res.Resources.getText(Resources.java:336)
	at android.content.res.Resources.getString(Resources.java:381)
	at android.content.Context.getString(Context.java:476)
	at org.robolectric.android.controller.ActivityController.getActivityTitle(ActivityController.java:127)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:75)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:34)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:93)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:89)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:97)
	at me.angrybyte.sillyandroid.parsable.AnnotationParserTest.setUp(AnnotationParserTest.java:146)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


android.content.res.Resources$NotFoundException: String resource ID #0x7f050000

	at android.content.res.Resources.getText(Resources.java:336)
	at android.content.res.Resources.getString(Resources.java:381)
	at android.content.Context.getString(Context.java:476)
	at org.robolectric.android.controller.ActivityController.getActivityTitle(ActivityController.java:127)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:75)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:34)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:93)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:89)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:97)
	at me.angrybyte.sillyandroid.parsable.AnnotationParserTest.setUp(AnnotationParserTest.java:146)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)


android.content.res.Resources$NotFoundException: String resource ID #0x7f050000

	at android.content.res.Resources.getText(Resources.java:336)
	at android.content.res.Resources.getString(Resources.java:381)
	at android.content.Context.getString(Context.java:476)
	at org.robolectric.android.controller.ActivityController.getActivityTitle(ActivityController.java:127)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:75)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:34)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:93)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:89)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:97)
	at me.angrybyte.sillyandroid.parsable.AnnotationParserTest.setUp(AnnotationParserTest.java:146)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Not sure what I am doing wrong.. I just need the activity instance, should be working out of the box.

**Comment by milosmns** [comment]
Btw I know that this was already reported, but nobody ever stated a clear solution, anywhere. 
So I was hoping that you can let me know what to do to fix this, and I can link a commit to this thread when it starts working again.

**Comment by hoisie** [comment]
Are you still having this issue? I get a 404 when clicking on that link to AnnotationParserTest.

**Comment by milosmns** [comment]
Yeah, that's because I abandoned the approach with testing the library. I
moved all of my tests to the app module and it works now.
Of course, this is not what I wanted and you can do a minimal test with
library+app to verify on your own, the Activity creation through
Robolectric fails cleanly.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
