### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/thrift/b

### ISSUE THREAD

**Issue by maonanyue** [robolectric/robolectric#3068]
### Description
run unit test failed!!!
stack message:
```
java.lang.NoClassDefFoundError: org/apache/thrift/b

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:319)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:20)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:35)
	at org.robolectric.shadows.ShadowApplication.registerBroadcastReceivers(ShadowApplication.java:138)
	at org.robolectric.shadows.ShadowApplication.bind(ShadowApplication.java:127)
	at org.robolectric.shadows.CoreShadowsAdapter.bind(CoreShadowsAdapter.java:71)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:107)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:289)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.thrift.b
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:161)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:108)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

Process finished with exit code 255
```

### Robolectric & Android Version
    build.gradle config:
```groovy
    testCompile "org.robolectric:robolectric:3.3"
    compileSdkVersion 25
    buildToolsVersion '25.0.2'
    minSdkVersion 18
    targetSdkVersion 23
```

**Comment by maonanyue** [comment]
help

**Comment by maonanyue** [comment]
I remove `@Config(constants = BuildConfig.class)` , and the exception is gone.

**Comment by jongerrish** [comment]
Not at my computer right now but I'm not sure where that class is coming
from. It looks like we're trying to register a receiver that you've defined
in your manifest and either it's that class or it has a reference to it.
The fact you removed constants = ... seems to back that up. Since you're
now not loading your manifest you're not registering the offending receiver.

**Comment by maonanyue** [comment]
@jongerrish thanks, you are right. I have third party receiver refer to `org.apache.thrift.b`.

**Comment by jongerrish** [comment]
Yeah, you could just make sure you have everything on your class path but
in the spirit of unit testing if you don't need the receiver for the
purposes of that test then best not to include it.

Glad you're good :-)

On May 10, 2017 9:19 PM, "weizongshang" <notifications@github.com> wrote:

@jongerrish <https://github.com/jongerrish> thanks, you are right. I have
third party receiver refer to org.apache.thrift.b.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/3068#issuecomment-300678260>,
or mute the thread

**Comment by maonanyue** [comment]
How can i configure test to exclude it when running unit test, but my application need it at other place.
And now i just update the third party library. @jongerrish

**Comment by hoisie** [comment]
Closing this as it does not seem to be an issue with the Robolectric framework -- it is likely an issue with your project's dependencies.
