### ISSUE TITLE
java.lang.IllegalArgumentException: class xxx.R contains final fields, these will be inlined by the compiler and cannot be remapped.

### ISSUE THREAD

**Issue by hazems** [robolectric/robolectric#3073]
### Description
After upgrading from Robolectric 3.0 to Robolectric 3.3.2, I found the following exception:
```
java.lang.IllegalArgumentException: class xxx.R contains final fields, these will be inlined by the compiler and cannot be remapped.
	at org.robolectric.res.ResourceRemapper.remapRClass(ResourceRemapper.java:77)
	at org.robolectric.res.ResourceRemapper.remapRClass(ResourceRemapper.java:44)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:18)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

```

### Steps to Reproduce
Note that this exception happens if I used getIncludedResourcePaths() of AndroidManifest class to include other project's resources as a resource dependency.

```
public class CustomRobolectricRunner extends RobolectricTestRunner {

    public CustomRobolectricRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected AndroidManifest getAppManifest(Config config) {
		// ...
		
        return new AndroidManifest(Fs.fileFromPath(manifestPath), Fs.fileFromPath(resDir),
                Fs.fileFromPath(assetsDir)) {

            @Override
            public List<ResourcePath> getIncludedResourcePaths() {
                List<ResourcePath> paths = super.getIncludedResourcePaths();
                
                ResourcePath resourcePath = new ResourcePath(getRClass(),
                        Fs.fileFromPath("../testProject/src/main/res"),
                        getAssetsDirectory());

                paths.add(resourcePath);

                return paths;
            }
        };
    }
	
	// ...
}
```

### Robolectric & Android Version
Robolectric 3.3.2 and Android targetSdkVersion 25.

**Comment by jongerrish** [comment]
It's not possible that one application depends on another applications R
class. You can only depend upon libraries. Libraries R files are generated
as non-final fields so that the compiler will not inline the values. The
final R class values are regenerated when the application is built. Is
there a library R class you can include instead?

**Comment by hazems** [comment]
@jongerrish Thanks for this response. As said, this scenario was working perfectly fine in Robolectric 3.0.0 which means that the following code was executing perfectly fine.

Does this behavior change? and if it is changed, what is the migration path for this code which loads resources from another project to execute Robolectric tests?

Thanks

```
public class CustomRobolectricRunner extends RobolectricTestRunner {

    public CustomRobolectricRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    @Override
    protected AndroidManifest getAppManifest(Config config) {
		
		// ...			
		return new AndroidManifest(Fs.fileFromPath(manifestPath), Fs.fileFromPath(resDir),
				Fs.fileFromPath(assetsDir)) {
			@Override
			public List<ResourcePath> getIncludedResourcePaths() {
				List<ResourcePath> paths = super.getIncludedResourcePaths();

				paths.add(new ResourcePath(getRClass(), getPackageName(),
						Fs.fileFromPath("../testProject/src/main/res"),
						getAssetsDirectory()));
				
				return paths;
			}
		};            
    }
	
	// ...
}
```

**Comment by jongerrish** [comment]
Yeah, the code changed to forbid this, if I understand correctly, you can't
depend on another applications resources within your own application in the
way you are talking. Your application can link in resources from other
libraries of course (these have R files with non-final fields because aapt
assigns the final R values when it builds your app).

There is of course
https://developer.android.com/reference/android/content/pm/PackageManager.html#getResourcesForApplication(java.lang.String)

which allows you to access resources from other applications, but you won't
have access to their R.class but you're talking about the former case
right? Where you're linking in another library with resources into your
application?

What build system are you using?

**Comment by hazems** [comment]
@jongerrish yes I'm talking about a former working test code (using Robolectric 3.0). So I have an android project (X) that depends on a common Java project (testProject) in order run correctly. Dependency here includes resources dependency, since there are android components in (testProject) which are used in project (X).

I'm using Gradle.

Thank you

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by FelixZhang00** [comment]
Could not set unknown property 'enableUnitTestBinaryResources' for object of type com.android.build.gradle.AppExtension.
