### ISSUE TITLE
buildIntentService - NoSuchMethodException on <init>

### ISSUE THREAD

**Issue by ben-xx** [robolectric/robolectric#3080]
### Description

Robolectric.buildIntentService throws a no constructor error, while Robolectric.buildService does not.

Known issue?

`java.lang.RuntimeException: java.lang.NoSuchMethodException: com.ik.myClass.SomeIntentService.<init>(java.lang.String)

	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:297)
	at org.robolectric.Robolectric.buildIntentService(Robolectric.java:78)
	at org.robolectric.Robolectric.buildIntentService(Robolectric.java:74)
	at com.ik.ticketwatcher.ExampleUnitTest.ticketWatcher_tests(ExampleUnitTest.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:498)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:245)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:171)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:137)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
Caused by: java.lang.NoSuchMethodException: com.ik.myClass.SomeIntentService.<init>(java.lang.String)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:283)
	... 27 more`

### Steps to Reproduce

`SomeIntentService svc = Robolectric.buildIntentService(SomeIntentService.class).create().get();`

### Robolectric & Android Version
3.1.4
Android compile SDK 24

**Comment by hoisie** [comment]
What constructors does `SomeIntentService` have? Does it have a zero-arg constructor, or just a one-arg constructor?

**Comment by ben-xx** [comment]
`SomeIntentService` had only a zero-arg constructor, nothing else:

`public SomeIntentService() {
        super("SomeIntentService");
    }`

Thanks, hoisie

**Comment by JavierSP1209** [comment]
In addition to this issue, if you have an inner class like:

```
 class MyTestServiceMock extends MyService {
    public MyTestServiceMock(String name) {
      super(name);
    }
```
You will have the same exception since is an InnerClass and the constructor found by reflection includes in addition to the `String` an additional parameter of type `MyService`

**Comment by JavierSP1209** [comment]
As a work around of the reported issue, make the extended Service class `static`

**Comment by alixwar** [comment]
I can reproduce this issue in Robolectric 3.4

**Comment by damienvaz** [comment]
Is that me or it hasn't been fixed yet ?
Had the same problem with robolectric version 3.8.

**Comment by alixwar** [comment]
It seems to be working for me on 4.2.1 at least. I could remove our workaround.
