### ISSUE TITLE
NPE in the call to ShadowConfiguration.setToDefaults

### ISSUE THREAD

**Issue by cesar1000** [robolectric/robolectric#3102]
After upgrading Robolectric from 3.2.2 to 3.3.2 we've starting seeing frequent crashes when running Robolectric tests, both in Mac developer laptops and in our Linux CI infra. The bug shows up occasionally and, when it does, every single test crashes with an NPE. All tests fail with the same callstack:

```
java.lang.NullPointerException
	at org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/2089684155.setToDefaults(Unknown Source)
	at org.robolectric.shadows.ShadowConfiguration.setToDefaults(ShadowConfiguration.java:48)
	at android.content.res.Configuration.setToDefaults(Configuration.java)
	at android.content.res.Configuration.__constructor__(Configuration.java:732)
	at android.content.res.Configuration.<init>(Configuration.java)
	at android.content.res.ResourcesImpl.__constructor__(ResourcesImpl.java:95)
	at android.content.res.ResourcesImpl.<init>(ResourcesImpl.java)
	at android.content.res.Resources.__constructor__(Resources.java:216)
	at android.content.res.Resources.<init>(Resources.java)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:86)
	at android.content.res.Resources.getSystem(Resources.java)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:80)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:315)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```
We are seeing this crash multiple times a day in our CI infra. Is there any information that we can collect in the case of a crash that would help figure out the problem?

**Comment by hoisie** [comment]
Have you tried upgrading to 3.4-RC2? ShadowConfiguration has been removed since the 3.3.2 release. Or have you tried overriding it with an empty shadow, e.g:

```java
/**
 * Remove Robolectric's shadow for for {@link android.content.res.Configuration}.
 */
@Implements(Configuration.class)
public class ShadowConfigurationRemover {
    // don't implement anything
}
```

**Comment by cesar1000** [comment]
I removed the shadow a few days ago and I haven't seen the issue since! Curious about the root cause but, for my purposes, the issue is fixed :)
