### ISSUE TITLE
Testing using a subclassed CursorAdapter results in NullPointerException

### ISSUE THREAD

**Issue by brarcher** [robolectric/robolectric#3111]
### Description
I'm attempting to write a unit test for an activity which uses a ListView populated by a subclassed CursorAdapter. Simply, the activity (source [here](https://github.com/brarcher/rental-calc/blob/51c8f400e38db795d7be726594c7f0857102d3f7/app/src/main/java/protect/rentalcalc/PropertiesListActivity.java#L62)) is doing the following:
```
    public void onResume()
    {
        super.onResume();
        final ListView propertyList = (ListView) findViewById(R.id.list);
        final Cursor properties = _db.getProperties();
        final PropertyCursorAdapter adapter = new PropertyCursorAdapter(this, properties);
        propertyList.setAdapter(adapter);
    }
```
When run on a phone the list items appear in the ListView as expected. However, when attempting to run within a test, running a test with a non-empty ListView always results in a NullPointerException. Here is an example test demonstrating this:
```
    @Before
    public void setUp()
    {
        db = new DBHelper(RuntimeEnvironment.application);
    }

    @Test
    public void clickOnPropertyLaunchesActivity()
    {
        // Create a property to show
        db.insertProperty(new Property());

        ActivityController controller = Robolectric.buildActivity(PropertiesListActivity.class).create();
        Activity activity = (Activity)controller.get();

        controller.start();
        controller.visible();

        // This next line results in a NullPointerException
        controller.resume();
} 
```
Debugging the code, my guess is that a shadow class is capturing some of the necessary calls, but not all of them, and as a result the subclassed CursorAdapter never produces a view when it should, and instead returns null. The following is the NullPointerException produced by the test:
```

java.lang.NullPointerException
	at android.widget.AbsListView.obtainView(AbsListView.java:2363)
	at android.widget.ListView.makeAndAddView(ListView.java:1876)
	at android.widget.ListView.fillDown(ListView.java:702)
	at android.widget.ListView.fillFromTop(ListView.java:763)
	at android.widget.ListView.layoutChildren(ListView.java:1685)
	at android.widget.AbsListView.onLayout(AbsListView.java:2148)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
	at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16636)
	at android.view.ViewGroup.layout(ViewGroup.java:5437)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2171)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:165)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:31)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:134)
	at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:355)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:257)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:238)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:221)
	at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:211)
	at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:79)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:113)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:313)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:364)
	at org.robolectric.shadows.CoreShadowsAdapter$2.runPaused(CoreShadowsAdapter.java:40)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:72)
	at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:171)
	at protect.rentalcalc.PropertiesListActivityTest.clickOnPropertyLaunchesActivity(PropertiesListActivityTest.java:67)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:488)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:209)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

### Steps to Reproduce
See description with example code and test which produces the failure.

### Robolectric & Android Version
Robolectric: 3.3.2
SDK used for tests: attempted SDK 25, 24, 23, and 22.
Android target SDK verison: 23

**Comment by hoisie** [comment]
@brarcher 

Can you try adding this shadow to your project (call it ShadowCursorAdapterRemover.java or something):

```java
/**
 * Remove Robolectric's shadow for for {@link android.widget.CursorAdapter}.
 */
@Implements(CursorAdapter.class)
public class ShadowCursorAdapterRemover extends ShadowBaseAdapter {
    // don't implement anything
}

```

Then in your tests(s), use 
```java
Config(shadows = ShadowCursorAdapterRemover.class)
```

Does that work for you?

**Comment by brarcher** [comment]
That does work. Thanks for the response!

So the issue was the shadow for the BaseAdapter not working as I expected. I'll certainly take this solution and run with it so I can write additional unit tests. However, as for the long-term expectation in this case, is it up to users of Robolectric to know when to remove certain shadows, or does the ShadowBaseAdapter need to be updated to work for the case where CursorAdapter is subclassed?

**Comment by hoisie** [comment]
In general it shouldn't be up to Robolectric users to remove shadows, but cases like this come up once in a while :/

`ShadowCursorAdapter` seems outdated. It's also confusing to use because you have to [manually add views](https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-core/src/main/java/org/robolectric/shadows/ShadowCursorAdapter.java#L65) to its internal list. Android's CursorAdapter.java is a pure Java and `ShadowCursorAdapter` appears to be a clone of it. I don't actually believe `CursorAdapter` needs to be shadowed.

**Comment by jongerrish** [comment]
Yeah, there is still a bunch of Shadow code left over from Robolectric 1.0
when we didn't use real Android code. It all needs to be removed really,
but it may break existing users who are depending on its behavior. Lets
@Deprecate it and remove it in Robolectric 3.5

**Comment by brarcher** [comment]
Yay! I appreciate the help, and planning on deprecating the ShadowCursorAdapter in Robolectric 3.5 to avoid future confusion.
