### ISSUE TITLE
Resources are not accessible with new android plugin (com.android.tools.build:gradle:3.0.0-alpha3)

### ISSUE THREAD

**Issue by paf001** [robolectric/robolectric#3169]
### Description
When trying to launch robolectric-based test with new Android Studio preview (3.0 canary), all tests fails when trying to access library / application resources.
After little research I found out the format of merged resources within build folder has changed (instead of  the same structure as the source has now there are files of form values_[some file name].arsc.flat in intermediates/res/merged directories)
Since the default robolectric configuration uses build folder as root for resolving resources, the resources loading silently fails. As the result, the resources are inaccessible from tests.

### Steps to Reproduce
- Create project with one application and one library module (with gradle-based build)
- Create resources in both library and application
- Create robolectric test for the application (in src/test directory). In the test, try access application or library resources via Resources.getValue()
- When the test is running, Instead of obtaining correct resource value android.content.res.Resources$NotFoundException exception is thrown.

See attached project:
[ResourceTestFail.zip](https://github.com/robolectric/robolectric/files/1060638/ResourceTestFail.zip)

### Robolectric & Android Version
com.android.tools.build:gradle:3.0.0-alpha3
org.robolectric:robolectric:3.2.1 (I tried it also on 3.3.2 and 3.4-rc2)

**Comment by paf001** [comment]
Probably related to https://issuetracker.google.com/issues/38039816

**Comment by jongerrish** [comment]
Yeah, aapt2 is enabled by default so intermediate merged Raw resources are
not available which Robolectric requires, we're working on a plan but for
now you can disable aapt2

**Comment by digitalbuddha** [comment]
Hi folks, I disabled aapt2 but am still seeing resource loading errors. Is there another workaround I could try?

**Comment by CCorrado** [comment]
Having the same issue on my project, running AS 3.0 Canary 4 gradle 3.0.0-alpha4 / gradle-4.0-rc-1.

Disabling aapt2 as a workaround would break libraries like dagger/butterknife that generate view binder classes etc (and for sure the unit tests depend on these libraries for binding views in fragments)

I was holding out a bit on my project to upgrade to AS 3.0 until API 26 hit production. I guess I could switch over to AS 2.3.3 and wait it out until 3.0 hits production :)

```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:450)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:288)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NullPointerException
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:35)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:140)
	... 32 more
```

**Comment by jongerrish** [comment]
AGP 3.0 includes changes made to better support unit tests (by including merged resources, assets + AndroidManifest.xml as first class citizens along with the Java code).

This can be enabled by adding the following configuration to your build.gradle files

android {
  ...
  testOptions {
    unitTests {
      includeAndroidResources = true
  }
}

With this integration enabled you'll also want to remove from your tests:-

@Config(constants = BuildConfig.class)

Using BuildConfig was always problematic as it relied on inferring the location of resources etc based on intermediate files produced by AGP which often changed and would break between versions. This new API is stable.

I know there have been other issues with AGP / aapt2 that may or may not be related but it would be great to get feedback on this new API. If you go ahead and try it, please let me know which exact versions of AGP 3.0 it works with and which you are still having problems with and I'll try and chase down the issues.

One problem we have is that we are not building Robolectric using AGP still, which means we're not fast to catch these issues, I'm sorry about that and its something we'll be looking at this quarter.

**Comment by vpratfr** [comment]
Some feedback to summarize how I got that working:

- Adding `android.enableAapt2=false` in my `gradle.properties` file
- Removing the `manifest` property from my `robolectric.properties` file
- Adding the `testOptions` block to my app's `build.gradle` file (see previous comment from @jongerrish)
- Removing the `applicationIdSuffix` property from my debug build types configuration

That last step has got me stuck for a bit of time. Resources cannot be found if we specify an applicationIdSuffix

```
    buildTypes {
        debug {
            // Commented due to problem with Robolectric
            // applicationIdSuffix '.debug'
```

Looking forward to getting back to a more standard build configuration but nothing too critical so far.

**Comment by jkasten2** [comment]
@vnayar Thanks, `android.enableAapt2=false` was the key for me. Also found this on Google blog post after the fact.
https://androidstudio.googleblog.com/2017/06/android-studio-30-canary-5-is-now.html


Also for those on `robolectric:3.4-rc5` you will get an error like this without it.
```Java
java.lang.NoSuchMethodError: android.content.res.Resources$NotFoundException.<init>(Ljava/lang/String;Ljava/lang/Exception;)V
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:72)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
```

Hopefully help someone searching based on stacktraces.

**Comment by jongerrish** [comment]
@jkasten2 - Created #3283 to track the constructor signature mismatch.

I think the underlying cause there is that the resource table does not have the resource specified in your manifest label. Whether this is because Robolectric is not finding any resources or because your library is missing that resource I'm not sure.

I've added details on the new AS/AGP3.0 integration here:-

http://robolectric.org/getting-started/

To be clear, you'll want Robolectric 3.4_rc5 (3.4 proper will be released tomorrow). With this new integration you shouldn't need to disable appt2, if that is not the case, please let me know and I'll report back to the AGP team.

For anyone still having problems with Robolectric + AGP 3.0 but not using the new integration, I'd be happy to accept pull requests to fix the paths in GradleManifestFactory but please also note that we won't be able to support this for long as when aapt2 and namespaced resources becomes standard there won't be any intermediate merged resources produced by AGP at all so I'd encourage everyone to start making migration plans.

**Comment by emarc-m** [comment]
@jkasten2 I tried out robolectric 3.4, it still requires disabling aapt2 so the android resources can be found. I have includeAndroidResources = true in my app's gradle but only disabling aapt2 works.

**Comment by laurencedawson** [comment]
@jongerrish I'm having the same issue as @emarc-m and only can resolve the issue by disabling aapt2.

**Comment by Kisty** [comment]
@jongerrish Thanks for updating the docs on the website, although I think there's a typo in 3.0 instructions as `compile` is removed from 3.0 where: 
`testCompile ...` --> `testImplementation ...`

**Comment by jongerrish** [comment]
Ah yeah, that was a warning, we should update that.

I'm at Burningman for the week so won't have connection, want to send a PR
to Brett Chabbot?

**Comment by ecorengia** [comment]
Just followed the instructions on getting-started guide, I had to remove applicationIdSuffix '.debug' to make it pass. I'm using AS 3.0 Beta 6 and dagger. No need to disable aapt2 in my case. Thanks!

**Comment by jongerrish** [comment]
No need to disable aapt2 since AS3.0 beta 1+

applicationId + applicationIdSuffix will be fixed in AS 3.0 beta 7 +
Robolectric 3.4.3

**Comment by juliooa** [comment]
Can confirm that including _includeAndroidResources=true_  and removing the suffix on the staging build fix the problem for me.

**Comment by Cherubyx** [comment]
I hope this helps out someone who is stuck.
1. I added the `testOptions` with `includeAndroidResources=true` to my app's gradle. Not modules or subproject, main app gradle file.
2. I **don't** have a default JUnit set to `$MODULE_DIR$` inside the configuration settings in `Defaults` > `Android JUnit`. Everything is blank like before.
3. I removed all indications of using the BuildConfig.class in my test files. 
`@Config(config=BuildConfig.class, application=TestApplication.class)` is now `@Config(application=TestApplication.class)`.
4. I did **NOT** comment out the applicationIdSuffix in my gradle file.

All my tests are running fine now.

**Comment by ankushg** [comment]
@Cherubyx did you have to disable `aapt2` and/or `newResourceProcessing`?

**Comment by Cherubyx** [comment]
@ankushg No for `aapt2` and I don't know what `newResourceProcessing` is.

**Comment by rodolfoizidoro** [comment]
I Remove @Config from my test and Its Works
