### ISSUE TITLE
Android Application's fileds nulll with PowerMockRule

### ISSUE THREAD

**Issue by apperside** [robolectric/robolectric#3215]
### Description
I am working to make Robolectric and Powermock work together, but I'm facing with some issues.

Given this classes

```
 public class MyClient {
    
        public boolean publicApi() {
            System.out.println("In publicApi");
            System.out.println("Application.self = " + BaseApplication.self());
            int result = 0;
            try {
                result = privateApi("hello", 1);
            } catch (Exception e) {
                Assert.fail();
            }
            System.out.println("result : " + result);
            return result == 20;
        }
    
        private int privateApi(String whatever, int num) throws Exception {
            System.out.println("In privateAPI");
            thirdPartyCall();
            int resp = 10;
            return resp;
        }
    
        private void thirdPartyCall() throws Exception {
            System.out.println("In thirdPartyCall");
            //Actual WS call which may be down while running the test cases
        }
    }
```

```
/**
     * Real application class
     */
    public class BaseApplication
        extends Application {
        protected static BaseApplication sSelf;
    
        @Override
        public void onCreate() {
            super.onCreate();
            System.out.println("filling Application.self");
            sSelf = this;
        }
    
        public static BaseApplication self() {
            return sSelf;
        }
    }

```

I tried these tests:

**# TEST 1 (using PowerMockRunner and PowerMockRunnerDelegate)**

```
@RunWith(PowerMockRunner.class)
    @PowerMockRunnerDelegate(RobolectricTestRunner.class)
    @PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
    @Config(manifest = Config.NONE, application = MyTestApplication.class)
    @PrepareForTest(MyClient.class)
    public class MyClientTest2 {
    
        @Test
        public void testPublicAPI() throws Exception {
            MyClient classUnderTest = PowerMockito.spy(new MyClient());
    
            PowerMockito.doReturn(20).when(classUnderTest, "privateApi", anyString(), anyInt());
    
            boolean result = classUnderTest.publicApi();
    
            Assert.assertTrue(result);
        }
    }
```

The output is 

```
filling Application.self
    In privateAPI
    In thirdPartyCall
    
    org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
    Invalid use of argument matchers!
    0 matchers expected, 2 recorded:
    -> at com.myapp.MyClientTest2.testPublicAPI(MyClientTest2.java:31)
    -> at com.myapp.MyClientTest2.testPublicAPI(MyClientTest2.java:31)
    
    This exception may occur if matchers are combined with raw values:
        //incorrect:
        someMethod(anyObject(), "raw String");
    When using matchers, all arguments have to be provided by matchers.
    For example:
        //correct:
        someMethod(anyObject(), eq("String by matcher"));
```

As you can see here the private method is executed when I call

    PowerMockito.doReturn(20).when(classUnderTest, "privateApi", anyString(), anyInt());

and the same call (line 31 is exactly that one) throws that exception

**# TEST 2 (using RobolectricTestRunner and PowerMockRule)**

```
@RunWith(RobolectricTestRunner.class)
    @PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
    @Config(manifest = Config.NONE, application = MyTestApplication.class)
    @PrepareForTest(MyClient.class)
    public class MyClientTest3 {
    
        @Rule
        public PowerMockRule rule = new PowerMockRule();
    
        @Test
        public void testPublicAPI() throws Exception {
            MyClient classUnderTest = PowerMockito.spy(new MyClient());
    
            PowerMockito.doReturn(20).when(classUnderTest, "privateApi", anyString(), anyInt());
    
            boolean result = classUnderTest.publicApi();
    
            Assert.assertTrue(result);
        }
    }
```
The output is 

```
filling Application.self
    In publicApi
    Application.self = null
    result : 20
```

Here the exception is gone, the private method is successfully mocked, but another problem comes in: MyTestApplication.self() returns null when accessed, even if the log `filling Application.self` indicates that the `sSelf` variable is valorized (I also checked it in the debugger)

This last solution seems to be the best one, but the problem it causes makes it impossible to use for me because I use Application.self() to access many dagger related stuff.

How should it be possible that the `sSelf` field is null at that point?

Many thanks for any help

### Robolectric & Android Version

org.robolectric:robolectric:3.3.2
org.robolectric:shadows-multidex:3.2.2

org.powermock:powermock-module-junit4:1.6.2"
org.powermock:powermock-module-junit4-rule:1.6.2"
org.powermock:powermock-api-mockito:1.6.2"
org.powermock:powermock-classloading-xstream:1.6.2"

**Comment by hazelguo** [comment]
Same!
