### ISSUE TITLE
Using @Config(manifest = Config.NONE) causes an NPE

### ISSUE THREAD

**Issue by cesar1000** [robolectric/robolectric#3220]
In Robolectric 3.3.2, annotating a class with @Config(manifest = Config.NONE) causes an NPE when parsing resources:

```
java.lang.RuntimeException: java.lang.RuntimeException: error parsing /Users/cpuerta/workspace/twitter-android/lib/twitter/features/legacy/build/intermediates/res/merged/debug/values/values.xml
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:155)
	at org.robolectric.res.ResourceTableFactory.newResourceTable(ResourceTableFactory.java:43)
	at org.robolectric.res.ResourceMerger.buildResourceTable(ResourceMerger.java:22)
	at org.robolectric.RobolectricTestRunner.getAppResourceTable(RobolectricTestRunner.java:472)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:313)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:203)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.twitter.test.runner.RunnerWrapper.run(RunnerWrapper.java:32)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: error parsing /Users/cpuerta/workspace/twitter-android/lib/twitter/features/legacy/build/intermediates/res/merged/debug/values/values.xml
	at org.robolectric.res.StaxDocumentLoader.loadResourceXmlFile(StaxDocumentLoader.java:32)
	at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:36)
	at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:26)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:140)
	... 42 more
Caused by: java.lang.NullPointerException
	at org.robolectric.res.ResName.computeHashCode(ResName.java:158)
	at org.robolectric.res.ResName.<init>(ResName.java:28)
	at org.robolectric.res.PackageResourceTable.addResource(PackageResourceTable.java:109)
	at org.robolectric.res.StaxArrayLoader.onEnd(StaxArrayLoader.java:48)
	at org.robolectric.res.StaxDocumentLoader.doParse(StaxDocumentLoader.java:66)
	at org.robolectric.res.StaxDocumentLoader.loadResourceXmlFile(StaxDocumentLoader.java:30)
	... 45 more
```

This is caused by a null package name, since the manifest was set to null.

**Comment by jongerrish** [comment]
Is this using the new build system api?

**Comment by cesar1000** [comment]
Yeah. It's caused by this in DefaultManifestFacfory, where the manifest is set to null explicitly if removed by the configuration:

```
  @Override
  public ManifestIdentifier identify(Config config) {
    FsFile manifestFile = Fs.fileFromPath(properties.getProperty("android_merged_manifest"));
    FsFile resourcesDir = Fs.fileFromPath(properties.getProperty("android_merged_resources"));
    FsFile assetsDir = Fs.fileFromPath(properties.getProperty("android_merged_assets"));
    String packageName = null;
    List<FsFile> libraryDirs = emptyList();


    String manifestConfig = config.manifest();
    if (Config.NONE.equals(manifestConfig)) {
      manifestFile = null;
```

I should've mentioned that, sorry!

**Comment by jongerrish** [comment]
So I'm actually in favor of just ignoring anything specified in @Config when the build api is used. It doesn't really make sense because none of these manifests or resources would be merged.

**Comment by jongerrish** [comment]
The PR above just ignores values set for @Config(manifest = Config.NONE) - I'd prefer to ignore all of the other values too, but we can discuss this later.

**Comment by cesar1000** [comment]
Yeah, makes sense.
