### ISSUE TITLE
Class not found exception android.app.Application

### ISSUE THREAD

**Issue by vpratfr** [robolectric/robolectric#3232]
### Description

Test suite was working yesterday (Android Studio canary 5). 

Today I am not able to launch any test. Just upgraded to Android Studio canary 6 in the meantime.

Tried cleaning, rebuild, resync gradle with no effect

### Robolectric & Android Version

Latest Robolectric, tried running on api 16 and 21.

```
java.lang.NoClassDefFoundError: android/app/Application

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:54)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:65)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:42)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: android.app.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
```

**Comment by vpratfr** [comment]
PS: Was working on Android Studio canary 5 yesterday

**Comment by vpratfr** [comment]
PPS: tried cleaning, rebuild, resync gradle with no effect

**Comment by jongerrish** [comment]
Any chance of a log? Error message etc?

**Comment by vpratfr** [comment]
I have copied it above

**Comment by vpratfr** [comment]
I have reverted to android studio 2.x latest and it all works properly.

**Comment by matejdro** [comment]
I have just experienced this issue and managed to fix it by deleting `.idea`, `.gradle` and `*.iml` files from my folder and let AS recreate project from gradle.

**Comment by xian** [comment]
Please reopen if you encounter this issue again. Thanks!

**Comment by johncazier** [comment]
I was able to fix it by just doing "Refresh Gradle project"

**Comment by danielesegato** [comment]
I believe the issue HAD NOT been solved by "Refresh Gradle project", it is just a matter of the user having to set up tests run configuration again after reloading the project.

This happens if you set "Search for tests: `Whole Project`" in the target Android JUnit configuration.
It works if you use `in Single Module` or `Across module dependencies`.

This would be very useful (and I find it very annoying) for multi-module repositories that not necessarily depends on each other. What I usually do is create an empty project depending on everything else to run all tests from there.

I think this issue should be re-open and targeted (probably not by robolectric though).
And should probably be "Whole Projects (android apps or libraries)" so that it can only run for Android modules (which makes sense being an Android JUnit configuration.
