### ISSUE TITLE
CertPathValidatorException on OpenJDK 8 131

### ISSUE THREAD

**Issue by rlac** [robolectric/robolectric#3288]
### Description

After updating the OpenJDK release packaged by Ubuntu to the current version (1.8.0_131-8u131-b11-2ubuntu1.16.04.2-b11) our tests that performed secure network operations began failing with the exception:

~~~~
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Algorithm constraints check failed on signature algorithm: SHA256WithRSAEncryption
~~~~

We were able to resolve this when we forced a newer version of Bouncy Castle than included with Robolectric as follows:

~~~~
testCompile 'org.bouncycastle:bcprov-jdk15on:1.57'
testCompile dependencies.create('org.robolectric:robolectric:3.1.2') {
    exclude group: 'org.bouncycastle'
}
testCompile dependencies.create('org.robolectric:robolectric-shadows:3.1') {
    exclude group: 'org.bouncycastle'
}
~~~~

(Note we also tried Robolectric 3.4 RC5 - the same exception occurred)

### Steps to Reproduce
Using OpenJDK 8 131 on Ubuntu (1.8.0_131-8u131-b11-2ubuntu1.16.04.2-b11), run a test that communicates with a HTTPS server.

### Robolectric & Android Version
Robolectric versions 3.1.2, 3.4 RC5

**Comment by Blackhex** [comment]
Same here with today updated Ubuntu 17.04 and Robolectric 3.4. @rlac Thank you very much for sharing the workaround.

**Comment by rmasarovic** [comment]
Same here Ubuntu 17.04, Robolectric 3.4.2, Jdk1.8.0_152

**Comment by ericfabreu** [comment]
The same thing happens when using any version of Android Studio 3.0 on Windows 10. All tests run fine on Android Studio 2.3 but fail with the exception above when using the AS3.0 preview

**Comment by TuFei-CN** [comment]
@ericfabreu I also met when using Robolectric3.4 to test  on Android Studio 3.0, Windows 10.But it's no problem on Android Studio 2.3.3.All tests run fine as you said. You can try that on AS3.0 preview.It's work for me.
```
testImplementation 'org.robolectric:robolectric:3.4'
testImplementation 'org.bouncycastle:bcprov-jdk15on:1.57'
```

**Comment by ericfabreu** [comment]
@TuFei-CN That seems to work here too, but I managed to "fix" the problem a few days ago by forcing Android Studio 3.0 to use the Java version that comes with Android Studio 2.3.3. 

As a reference, Android Studio 2.3.3 uses Java 1.8.0_112 while AS 3.0 uses 1.8.0_152. I also tried running the tests with Oracle's Java 1.8.0_144 but the tests failed with the same exception

**Comment by TuFei-CN** [comment]
@ericfabreu Yeah,you are right.AS 2.3.3 uses Java 1.8.0_112 while AS 3.0 uses 1.8.0_152.When I tried to test with Java 1.8.0_131,the tests also ran well.Thank you for your sharing.

**Comment by calvarez-ov** [comment]
The #3458 PR actually seems to introduce a regression for us, when our tests use volley to connect to wiremock.

Broken configuration:
oracle jdks tested: 
* 1.8.0_121
* 1.8.0_131
* 1.8.0_141
* 1.8.0_144
* 1.8.0_151
```
testCompile 'org.robolectric:robolectric:3.5'
```
Exception trying to connect to the wiremock server: 
```
15:21:55.897 [DEBUG] [TestEventLogger]     com.android.volley.NoConnectionError: javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key
15:21:55.899 [DEBUG] [TestEventLogger]          at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:151)
15:21:55.900 [DEBUG] [TestEventLogger]          at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)
15:21:55.900 [DEBUG] [TestEventLogger]     Caused by: javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
15:21:55.900 [DEBUG] [TestEventLogger]          at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
15:21:55.901 [DEBUG] [TestEventLogger]          at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
15:21:55.901 [DEBUG] [TestEventLogger]          at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
15:21:55.901 [DEBUG] [TestEventLogger]          at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
15:21:55.901 [DEBUG] [TestEventLogger]          at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
15:21:55.901 [DEBUG] [TestEventLogger]          at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
15:21:55.901 [DEBUG] [TestEventLogger]          at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:110)
15:21:55.901 [DEBUG] [TestEventLogger]          at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:96)
15:21:55.901 [DEBUG] [TestEventLogger]          ... 1 more
15:21:55.901 [DEBUG] [TestEventLogger]     Caused by: java.security.ProviderException: Could not derive key
15:21:55.901 [DEBUG] [TestEventLogger]          at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:133)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163)
15:21:55.902 [DEBUG] [TestEventLogger]          at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:102)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1061)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
15:21:55.902 [DEBUG] [TestEventLogger]          at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
15:21:55.902 [DEBUG] [TestEventLogger]          ... 10 more
15:21:55.903 [DEBUG] [TestEventLogger]     Caused by: java.security.InvalidAlgorithmParameterException
15:21:55.903 [DEBUG] [TestEventLogger]          at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)
15:21:55.903 [DEBUG] [TestEventLogger]          at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130)
15:21:55.903 [DEBUG] [TestEventLogger]          ... 20 more
```

Configurations which work:
Using the jdk installed on Ubuntu (openjdk 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
```
testCompile 'org.robolectric:robolectric:3.5'
```

Or, using the oracle jdks with the older bouncycastle:
```
    testCompile "org.bouncycastle:bcprov-jdk16:1.46"
    testCompile ('org.robolectric:robolectric:3.5') {
        exclude group: 'org.bouncycastle'
    }
```

Maybe this is a bug with wiremock, or with volley, and not necessarily Robolectric.

**Comment by eliasbagley** [comment]
@calvarez-ov I'm getting the same `java.security.ProviderException: Could not derive key` error after updating.

**Comment by hameno** [comment]
We have the same problem with 3.5

**Comment by victorlaerte** [comment]
@hameno update to 3.5.1 and be happy

**Comment by AchrafAmil** [comment]
Thank you @rlac , works marvelously well!

I faced this problem once I had to move one of my tests from standard JVM to Robolectric runner.

**Comment by thanghs6714-seta** [comment]
anyone fixed it

**Comment by thanghs6714-seta** [comment]
@jrodbx
Update bouncycastle to latest (1.58) #3458
Thanks. It worked for me
