### ISSUE TITLE
No internet permissions granted

### ISSUE THREAD

**Issue by lukaskris** [robolectric/robolectric#3307]
### Description
No internet permission granted

### Error 

java.lang.IllegalStateException: No internet permissions granted for the app, please add <uses-permission android:name="android.permission.INTERNET" /> to your AndroidManifest.xml.

	at com.facebook.accountkit.internal.Validate.checkInternetPermissionAndThrow(Validate.java:47)
	at com.facebook.accountkit.internal.Initializer.initialize(Initializer.java:92)
	at com.facebook.accountkit.internal.AccountKitController.initialize(AccountKitController.java:592)
	at com.facebook.accountkit.AccountKit.initialize(AccountKit.java:127)
	at com.renseki.app.conecworld.Conecworld.onCreate(Conecworld.java:39)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:144)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

### Robolectric & Android Version
Robolectric 3.4
android studio 2.3
already setup configuration $MODULE_DIR$
and <uses permission ....> in manifest
i stuck in this error

**Comment by utzcoz** [comment]
@lukaskris Please try the latest Robolectric 4.9.2. And please attach a minimal reproducable app when reopening this issue if you found this issue still exists.
