### ISSUE TITLE
FactoryConfigurationError

### ISSUE THREAD

**Issue by DFreds** [robolectric/robolectric#3318]
### Description

The first test I write gives this error on running it.

```
javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created

	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:370)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:313)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:227)
	at javax.xml.stream.XMLInputFactory.newFactory(XMLInputFactory.java:205)
	at org.robolectric.res.StaxDocumentLoader.<init>(StaxDocumentLoader.java:20)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:113)
	at org.robolectric.res.ResourceTableFactory.newFrameworkResourceTable(ResourceTableFactory.java:24)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceTable(SdkEnvironment.java:23)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:290)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:367)
	... 28 more
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Provider com.ctc.wstx.stax.WstxInputFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.stream.FactoryFinder$1.run(FactoryFinder.java:353)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:341)
	... 28 more


javax.xml.stream.FactoryConfigurationError: Provider for class javax.xml.stream.XMLInputFactory cannot be created

	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:370)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:313)
	at javax.xml.stream.FactoryFinder.find(FactoryFinder.java:227)
	at javax.xml.stream.XMLInputFactory.newFactory(XMLInputFactory.java:205)
	at org.robolectric.res.StaxDocumentLoader.<init>(StaxDocumentLoader.java:20)
	at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:113)
	at org.robolectric.res.ResourceTableFactory.newFrameworkResourceTable(ResourceTableFactory.java:24)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceTable(SdkEnvironment.java:23)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:290)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.stream.XMLInputFactory cannot be created
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:367)
	... 28 more
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Provider com.ctc.wstx.stax.WstxInputFactory not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at javax.xml.stream.FactoryFinder$1.run(FactoryFinder.java:353)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.xml.stream.FactoryFinder.findServiceProvider(FactoryFinder.java:341)
	... 28 more
```

### Steps to Reproduce
Here is my Kotlin code:

```
class MyActivity : BaseActivity() {

    override fun createFragment(): Fragment {
        return MyFragment()
    }

    override fun onBackPressed() {
        val drawer = findViewById(R.id.drawer_layout) as DrawerLayout
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START)
        } else {
            super.onBackPressed()
        }
    }
}
```

```
@RunWith(RobolectricTestRunner::class)
@Config(constants = BuildConfig::class)
class MyActivityTest {

    private lateinit var activity: MyActivity

    @Before
    fun setUp() {
        activity = Robolectric.setupActivity(MyActivity::class.java)
    }

    @Test
    fun createFragment() {
        assertTrue(true)
    }

}
```

### Robolectric & Android Version
Robolectric version 3.4.2
Android Studio version 2.3.3

**Comment by DFreds** [comment]
Quick note. This only occurs on versions 3.3.2 and greater. Version 3.3.1 works for me.

**Comment by markiantorno** [comment]
Yeah...please fix this.

**Comment by avajor** [comment]
Still happening in 3.6.1 for me.

Does anyone know how to avoid this?

**Comment by leesandy** [comment]
Of course thank you

**Comment by mik9** [comment]
The issue is old but I think I got same exception with https://github.com/JavaMoney/jsr354-ri library (v1.4.5): `java.util.ServiceConfigurationError: org.javamoney.moneta.spi.MonetaryConfigProvider: org.javamoney.moneta.spi.DefaultConfigProvider not a subtype` if I used it inside `@RunWith(RobolectricTestRunner)` test.
(the simplest code is `Money.of(123, "USD")`)
