### ISSUE TITLE
ShadowViewAnimator not needed

### ISSUE THREAD

**Issue by romkal** [robolectric/robolectric#3319]
### Description
It seems that ShadowViewAnimator doesn't do anything that would be actually needed, but messes up classes like ViewSwitcher because they use different methods for switching views that reach to package protected mWhichChild field directly.

### Steps to Reproduce
TextSwitcher s = new TextSwitcher(context);
s.addView(new TextView(context), 0, null);
s.addView(new TextView(context), 1, null);
s.setText("Boo");
assertThat((TextView) s.getCurrentView()).getText().toString()).isEqualTo("Boo")

This should pass, but fails.

**Comment by MGaetan89** [comment]
This is still valid with Robolectric 4.14.1. The provided test above results in:
```
Cannot read field "width" because "source" is null
java.lang.NullPointerException: Cannot read field "width" because "source" is null
	at android.view.ViewGroup$LayoutParams.__constructor__(ViewGroup.java:6403)
	at android.view.ViewGroup$LayoutParams.<init>(ViewGroup.java:6402)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6685)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:770)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:697)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:3889)
	at android.view.ViewGroup.addView(ViewGroup.java:3733)
```
