### ISSUE TITLE
Unable to find resource ID if the applicationId in build.gradle different with the package attribute in the AndroidManifest.xml.

### ISSUE THREAD

**Issue by x2361** [robolectric/robolectric#3323]
### Description
Unable to find resource ID if the applicationId in build.gradle different with the package attribute in the AndroidManifest.xml.

android.content.res.Resources$NotFoundException: Unable to find resource ID #0x0 in packages [android, my.app.id]
	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:864)
	at org.robolectric.shadows.ShadowAssetManager.resolveResourceValue(ShadowAssetManager.java:672)
	at org.robolectric.shadows.ShadowAssetManager.resolve(ShadowAssetManager.java:632)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:626)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:226)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:331)
	at android.content.res.Resources.getString(Resources.java:381)
	at android.content.Context.getString(Context.java:476)
	at org.robolectric.shadows.ShadowActivity.getActivityTitle(ShadowActivity.java:100)
	at org.robolectric.shadows.ShadowActivity.callAttach(ShadowActivity.java:110)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:56)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:25)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:98)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:94)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:102)
	at com.daydayup.ddreport.FistRobolectricTest.test(FistRobolectricTest.java:33)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.mockito.internal.junit.JUnitRule$1.evaluateSafely(JUnitRule.java:63)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:43)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
### Robolectric & Android Version

classpath 'com.android.tools.build:gradle:3.0.0-beta1'

testCompile 'org.robolectric:robolectric:3.4.2'

**Comment by jongerrish** [comment]
I this an issue in AS3.0 alpha 9?

**Comment by wuzhen0808** [comment]
Not in AS, just run with Android Gradle Plugin 3.0.0-beta1(3.0.0-alpha9 is also the same i guess).
Run test in command line(like:gradlew test). And the exception information is come from the test report: <myproject>\build\reports\tests\testDebugUnitTest\index.html

**Comment by bagza** [comment]
+ 1
Android Gradle Plugin 3.0.0-beta2

**Comment by leocabral** [comment]
please, follow these steps to make sure you have all set to run the tests

1. include this into your module build gradle file 
```
android {
 testOptions.unitTests.includeAndroidResources true
}
```
2. add `android.enableAapt2=false` into gradle.properties..

3. and make sure to use the latest AGP plugin version

i guess it should all be fine now...

also check these links below 
https://issuetracker.google.com/issues/64107525
https://issuetracker.google.com/issues/63721209

😀

**Comment by MinkiPan** [comment]
this is still a problem, tried all options like "testOptions.unitTests.includeAndroidResources true"
if the package name in manifest differs from application id, the resource cannot be found, I need to specify the package explicitly in @Config(constants = BuildConfig::class packageName = "manifestpackagename")
using Android Gradle Plugin 3.0.0-beta3

**Comment by jongerrish** [comment]
This is an issue with AGP, follow along here:-

https://issuetracker.google.com/65398093

**Comment by IgorGanapolsky** [comment]
@leocabral `testOptions.unitTests.includeAndroidResources true` doesn't do anything

**Comment by jongerrish** [comment]
@IgorGanapolsky You need AGP 3.0 for the new build system API.

**Comment by jongerrish** [comment]
For this particular issue, I've added support in Robolectric to read the custom package passed from the build system: https://github.com/robolectric/robolectric/pull/3383

We'll cherry pick this into the 3.4 branch and make a release. The fix from AGP side should be in the next version of AS.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by nicusorflorin** [comment]
this is still happenning @jongerrish
