### ISSUE TITLE
VectorDrawableCompat 26.0.0 fails on fillType="evenOdd"

### ISSUE THREAD

**Issue by nborodikhin** [robolectric/robolectric#3354]
### Description
During construction of a vector drawable containing `fillType="evenOdd"` attribute, `VectorDrawableCompat` crashes with `NumberFormatException` parsing the attribute:

```
java.lang.NumberFormatException: For input string: "evenOdd"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:128)
	at android.content.res.TypedArray.getInt(TypedArray.java:322)
	at android.support.v4.content.res.TypedArrayUtils.getNamedInt(TypedArrayUtils.java:105)
	at android.support.graphics.drawable.VectorDrawableCompat$VFullPath.updateStateFromTypedArray(VectorDrawableCompat.java:1779)
	at android.support.graphics.drawable.VectorDrawableCompat$VFullPath.inflate(VectorDrawableCompat.java:1718)
	at android.support.graphics.drawable.VectorDrawableCompat.inflateInternal(VectorDrawableCompat.java:743)
	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:627)
	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:586)
	at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:568)
```

[VectorDrawableCompat.java](https://github.com/android/platform_frameworks_support/blob/oreo-r6-release/graphics/drawable/static/src/android/support/graphics/drawable/VectorDrawableCompat.java):
```java
  1720	        private void updateStateFromTypedArray(TypedArray a, XmlPullParser parser) {
  ...                    ...
  1777	            mFillRule = TypedArrayUtils.getNamedInt(a, parser, "fillType",
  1778	                    AndroidResources.STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE,
  1779	                    mFillRule);
  1780	        }
```

### Steps to Reproduce
inflate such a vector drawable:
```
  VectorDrawableCompat.create(resources, R.drawable.square, null);
```

square.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="30dp"
        android:height="30dp"
        android:viewportWidth="30"
        android:viewportHeight="30">

    <path
        android:fillColor="#ffffff"
        android:fillType="evenOdd"
        android:pathData="M10 10, 10 20, 20 20, 20, 10" />
</vector>
```

### Robolectric & Android Version
* Robolectric 3.4, 3.4.2
* suport library 26.0.0 (prior versions did not have `fillType` support
* sdk<24.  On sdk >= 24, support library delegates to the platform implementation, which works fine

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
