### ISSUE TITLE
Robolectric 3.4.2 does not work with Android 8 and support-library 26

### ISSUE THREAD

**Issue by mpost** [robolectric/robolectric#3357]
### Description

The attached project does not run its only test when using the 26 support library. The test is not able to create an activity:

```java
@RunWith(RobolectricTestRunner.class)
public class MainActivity_Test {

  @Test
  public void robolectricTest() {
    MainActivity activity = Robolectric.buildActivity(MainActivity.class).setup().get();

    assertNotNull(activity);
  }

}
```

The tests throws the exception:

```java
com.eclipsesource.robolectric.robolectictest.MainActivity_Test > robolectricTest FAILED
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f060052 in packages [android, org.robolectric.default]
        at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:864)
        at org.robolectric.shadows.ShadowAssetManager.resolveResourceValue(ShadowAssetManager.java:672)
        at org.robolectric.shadows.ShadowAssetManager.resolve(ShadowAssetManager.java:632)
        at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:626)
        at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:255)
        at android.content.res.AssetManager.getResourceValue(AssetManager.java)
        at android.content.res.Resources.getValue(Resources.java:1009)
        at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
        at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
        at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
        at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:131)
        at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
        at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
        at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
        at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
        at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
        at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
        at com.eclipsesource.robolectric.robolectictest.MainActivity.onCreate(MainActivity.java:10)
```

### Steps to Reproduce

run `./gradlew check` in the attached project to see the error.

[robolectric-test.zip](https://github.com/robolectric/robolectric/files/1252166/robolectric-test.zip)

### Robolectric & Android Version

robolectric 3.4.2
android 26

**Comment by jongerrish** [comment]
What version of Android studio / Gradle Plugin are you using?

What package name is specified in your manifest and what package is your R
class generated in?

**Comment by mpost** [comment]
You can extract all information from the attached project. It is Android
plugin and Android studio 3 beta 3. Gradle 4.1.

**Comment by jongerrish** [comment]
Unfortunately I'm on vacation till next week so I can't do that... Hoping
Brett can take a look....

**Comment by omar25h** [comment]
@mpost it seems that `includeAndroidResources = true` is missing in your module gradle file. Try adding this code snippet
```
android {
    buildTypes { 
        // ...
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}
```

**Comment by mpost** [comment]
@omar25h Thanks for the reminder. This helps for the attached project. :)

It is still not running in my actual application where it is still failing (resources are included there). I'll close the issue and continue to investigate.
