### ISSUE TITLE
Testing JobIntentService in Robolectric

### ISSUE THREAD

**Issue by ngoctranfire** [robolectric/robolectric#3358]
### Description
Currently, when I try to test JobIntentService, it goes through the following steps:
it calls `MyJobIntentService#onCreate()`, which needs then eventually calls
`context.getPackageName`, which then throws a NPE. How should I test JobIntentService.class using Robolectric.
### Steps to Reproduce
 Right now, I'm just making the service by doing the following:
```
MyJobIntentService jobIntentService = new MyJobIntentService();
jobIntentService.onCreate();
```
That onCreate() call leads to a NPE, because it does the following:
```java.lang.NullPointerException
	at android.content.ContextWrapper.getPackageName(ContextWrapper.java:127)
	at android.content.ComponentName.__constructor__(ComponentName.java:75)
	at android.content.ComponentName.<init>(ComponentName.java)
	at android.support.v4.app.JobIntentService.onCreate(MyJobIntentService.java:427)```

### Robolectric & Android Version
Robolectric 3.4.2
AndroidVersion: 26.0.1

**Comment by ngoctranfire** [comment]
Nvm. We can close this. I can easily just do
Robolectric.setupService(MyJobIntentService.class);
