### ISSUE TITLE
android.content.res.Resources$NotFoundException: Unable to find resource ID

### ISSUE THREAD

**Issue by IgorGanapolsky** [robolectric/robolectric#3374]
[TestServiceApplication.zip](https://github.com/robolectric/robolectric/files/1271462/TestServiceApplication.zip)
### Description
Linked from issue https://github.com/robolectric/robolectric/issues/3047#issuecomment-326621289

I am unable to run my unit test.  it is complaining about a missing resouceID:

### Steps to Reproduce
1) Run the unit test in the attached project
2) Observe the error:
> android.content.res.Resources$NotFoundException: Unable to find resource ID #0x0 in packages [android, com.example.igorganapolsky.testserviceapplication]

	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:864)
	at org.robolectric.shadows.ShadowAssetManager.resolveResourceValue(ShadowAssetManager.java:672)
	at org.robolectric.shadows.ShadowAssetManager.resolve(ShadowAssetManager.java:632)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:626)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:226)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:334)
	at android.content.Context.getText(Context.java:543)

### Robolectric & Android Version
org.robolectric:robolectric:3.4.2
buildToolsVersion "26.0.1"

**Comment by IgorGanapolsky** [comment]
Actually, I see the issue is with using `context.getResources().getIdentifier`.
When I use `context.getString()` instead, it works.

**Comment by jongerrish** [comment]
How are you calling getIdentifier() ?

You'll need to call with the apps package name, i.e:

context.getResources().getIdentifier("name", "type", context.getPackageName());

**Comment by IgorGanapolsky** [comment]
Yes, I use `context.getPackageName()`

**Comment by jongerrish** [comment]
What build system + version are you using?

**Comment by IgorGanapolsky** [comment]
com.android.tools.build:gradle:3.0.0-beta4
org.robolectric:robolectric:3.4.2

I decided that I need to break dependencies in my code to make it more testable.  I am no longer calling the code which uses `context.getResources().getIdentifier()`.  That way my tests are truly nimble.

**Comment by autonomousapps** [comment]
I got this same issue calling `context.getResources().getStringArray()`. This was working fine before I updated to the Android Gradle Plugin v3.0.0.

**Comment by NodensN** [comment]
same issue with `.getApplicationContext()` after I updated to the Android Gradle Plugin v3.0.0.

**Comment by bengui** [comment]
Same issue here using ```context.getResources().getString(stringId)``` after updating to Android Gradle Plugin v3.0.0. Is there a workaround for this ?

**Comment by lognaturel** [comment]
I believe the problem I'm getting running debug unit tests from gradle is related, would love some ideas on what changes might be necessary to work with the new versions.

com.android.tools.build:gradle:3.0.1
org.robolectric.robolectric:3.5.1
build tools 26.0.2
gradle 4.1

```
android.content.res.Resources$NotFoundException: org.odk.collect.android:integer/google_play_services_version
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:72)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:220)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:108)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:35)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:62)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
```

**Comment by said120276** [comment]
Hi ;
same issue with :
.setBackground(ContextCompat.getDrawable(cntx,  R.drawable.drbl)) ;
I do not use robolectric in my application and I get the same problem after the update:
 the Android Studio 
 the build tool '26.0.2' 
gradle plugin 3.0.0


Caused by android.content.res.Resources$NotFoundException
--
  | android.content.res.Resources.getValue (Resources.java:2598)
  | android.content.res.Resources.getDrawable (Resources.java:2041)
  | android.content.res.Resources.getDrawable (Resources.java:2027)
  | android.content.Context.getDrawable (Context.java:464)
  | android.support.v4.content.ContextCompat.getDrawable (ContextCompat.java:351)
  | com.semsemcode.ty.AppLockservice.onStartCommand (AppLockservice.java:518)
  | android.app.ActivityThread.handleServiceArgs (ActivityThread.java:4132)
