### ISSUE TITLE
java.lang.NoClassDefFoundError: org/robolectric/internal/ShadowExtractor

### ISSUE THREAD

**Issue by fmanno** [robolectric/robolectric#3381]
### Description
Trying to use 

> org.robolectric.shadows.gms.common.ShadowGoogleApiAvailability

 in a test results in this error when trying to get the shadow of GoogleApiAvailability instance.

```
java.lang.NoClassDefFoundError: org/robolectric/internal/ShadowExtractor

	at org.robolectric.shadows.gms.Shadows.shadowOf(Shadows.java:37)
	at com.dambi.geofence.RoboTestFail.setUp(RoboTestFail.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: org.robolectric.internal.ShadowExtractor
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:103)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more
```
If I look at at `org.robolectric.shadows.gms.Shadows.shadowOf(Shadows.java:37)` by clicking on `Shadows.java:37`
It brings me to a seemingly autogenerated file where I can see:

```
    public static ShadowGoogleApiAvailability shadowOf(GoogleApiAvailability actual) {
        return (ShadowGoogleApiAvailability)ShadowExtractor.extract(actual);
    }
```
But what I don't understand is how is this getting here. Apparently ShadowExtractor has been deprecated [here](https://github.com/robolectric/robolectric/pull/3174)

I've deleted the contents of my .gradle folder and ran "cleanGradleBuildCache" and "clean" tasks. Is there something I'm missing or is this a bug?

### Steps to Reproduce
Test to reproduce this:

```
import com.google.android.gms.common.ConnectionResult;
import com.google.android.gms.common.GoogleApiAvailability;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import org.robolectric.shadows.gms.common.ShadowGoogleApiAvailability;
import static org.robolectric.shadows.gms.Shadows.shadowOf;

@RunWith(RobolectricTestRunner.class)
@Config(shadows = {ShadowGoogleApiAvailability.class})
public class RoboTestFail {

    @Before public void setUp() throws Exception {
        final ShadowGoogleApiAvailability shadowGoogleApiAvailability
                = shadowOf(GoogleApiAvailability.getInstance());
        final int expectedCode = ConnectionResult.SUCCESS;
        shadowGoogleApiAvailability.setIsGooglePlayServicesAvailable(expectedCode);
        MainActivity activity = Robolectric.setupActivity(MainActivity.class);
        GoogleApiAvailability.getInstance().makeGooglePlayServicesAvailable(activity);
    }
    @Test public void dummy_test() {
        System.out.println("Dummy test");
    }
}
```

### Robolectric & Android Version
Targeting Android SDK 26 and
```
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.robolectric:robolectric:3.4.2'
    testImplementation 'org.robolectric:shadows-play-services:3.4-rc2'
    testImplementation 'org.robolectric:shadows-maps:3.4-rc2'
    testImplementation 'org.robolectric:shadows-support-v4:3.4-rc2'
```

**Comment by fmanno** [comment]
If I change the code adding:
`import org.robolectric.shadow.api.Shadow;`

and then:
```
        final ShadowGoogleApiAvailability shadowGoogleApiAvailability
                = Shadow.extract(GoogleApiAvailability.getInstance());
```
The test works as expected. Still I don't understand why this isn't the behaviour with the other import

**Comment by praveeng145** [comment]
@fmanno thanks a bunch. Just worked like that!

**Comment by jongerrish** [comment]
Hopefully you shouldn't need ShadowGoogleApiAvailability since you can now pass an instance of that class around and provide your own fake / mock for it.
