### ISSUE TITLE
Calling AccessibilityNodeInfo.CollectionInfo.obtain() throws exception about unmocked method

### ISSUE THREAD

**Issue by pnovapps** [robolectric/robolectric#3384]
### Description

trying to obtain AccessibilityNodeInfo.CollectionInfo throws exception about unmocked method

java.lang.RuntimeException: Method obtain in android.view.accessibility.AccessibilityNodeInfo$CollectionInfo not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.view.accessibility.AccessibilityNodeInfo$CollectionInfo.obtain(AccessibilityNodeInfo.java)
	at com.vigilantapps.testaccessibilitynodeinfo.ExampleUnitTest.testScan(ExampleUnitTest.java:31)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

### Steps to Reproduce

        AccessibilityNodeInfo.CollectionInfo collectionInfo = AccessibilityNodeInfo.CollectionInfo.obtain(12, 0, false);

### Robolectric & Android Version

roboelectric 3.4.2

**Comment by MGaetan89** [comment]
Hey @pnovapps,

I know this is an old issue, but I've added a unit test for your use case in #10152.
The test is passing, so this is probably working as expected in the latest Robolectric release.
I'm going to close this once the PR is merged. Feel free to reopen if there's more to do in the scope of this issue.
