### ISSUE TITLE
java.lang.RuntimeException: java.io.FileNotFoundException: <app dir> is a directory) 	at org.robolectric.res.Fs$JarFs.<init>(Fs.java:93)

### ISSUE THREAD

**Issue by bonnyfone** [robolectric/robolectric#3411]
### Description
Running tests using Robolectric **3.4.2** through CI (Jenkins) hosted on **AWS (Linux)** is causing the exception below. On older Robolectric versions (<= 3.3.2) everything works without exceptions.

```
java.lang.RuntimeException: java.io.FileNotFoundException: <absolut_path_to_android_project>/app (Is a directory)
	at org.robolectric.res.Fs$JarFs.<init>(Fs.java:93)
	at org.robolectric.res.Fs.fromJar(Fs.java:28)
	at org.robolectric.internal.SdkEnvironment.createRuntimeSdkResourcePath(SdkEnvironment.java:31)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceTable(SdkEnvironment.java:22)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:290)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: <absolut_path_to_android_project>/app (Is a directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:130)
	at org.robolectric.res.Fs$JarFs.<init>(Fs.java:91)
	... 43 more
```

### Steps to Reproduce
Run a tests using Robolectric 3.4.2 on a machine hosted on AWS (Linux).

### Robolectric & Android Version
- Robolectric 3.4.2
- Android target sdk 26
- Android min sdk 21

**Comment by audriusKV** [comment]
Does anyone know reason or workaround for this?

**Comment by tadfisher** [comment]
Here's a weird log:

```
    DEBUG: Loading classes from: file:/mnt/tmp/jenkins-worker/JENKINS_HOME/workspace/_Mobile-Android_jenkinsfile-BY43CSRUK5FQRTHXTIPSMMHTZ2FAIKRHSA74GFEDG5R3C2GTHIYQ/Mobile-Android/?/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-0/android-all-4.1.2_r1-robolectric-0.jar
```

Probably has something to do with how MavenDependencyResolver is building its local artifact URL.

**Comment by neworld** [comment]
I found one problem. If your path contains `?`, everything works fine except:

https://github.com/robolectric/robolectric/blob/master/resources/src/main/java/org/robolectric/res/Fs.java#L34

`url.getPath()` truncates after `?`:

```
new URL("file://home/neworld/?/robolectric").getPath() == "/home/neworld"
```

However, I am not sure, this is a real problem or symptom. Maybe some other code should ensure no `?` comes here.

**Comment by neworld** [comment]
### Working workaround

- You need setup `user.home` for unit tests
- Also, you may need clear robolectric cache from `/tmp` or other directories

Example:
```
android {
    testOptions {
        unitTests.all {
            systemProperty 'user.home', System.getenv('WORKSPACE') ?: System.getenv('HOME')
        }
    }
}
```

In my CI, `WORKSPACE` is working directory for build and it is fine to put `.m2` there. `HOME` dir is for local builds
