### ISSUE TITLE
FileAlreadyExistsException thrown from ShadowEnvironment.getExternalStoragePublicDirectory

### ISSUE THREAD

**Issue by sjballance** [robolectric/robolectric#3418]
Exception is thrown when test is running:

```
java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: /tmp/robolectric-Method_testStopAndStart548604011417905593/external-cache
	at org.robolectric.util.TempDirectory.create(TempDirectory.java:39)
	at org.robolectric.shadows.ShadowEnvironment.getExternalStorageDirectory(ShadowEnvironment.java:62)
	at android.os.Environment.getExternalStorageDirectory(Environment.java)
	at android.provider.MediaStore$Audio$Media.getContentUriForPath(MediaStore.java:1402)
        ...
```

(MediaStore.Audio.Media.getContentUriForPath is called from my app code.)

Only reproduces intermittently - each time I run all of my unit tests, one or two normally fail with this exception.

I saw this in Robolectric 3.3.2 but looking at the code, I don't think this has been fixed. Looks like a regression of issue #1749.

Tests were running on a CentOS 7 machine.

**Comment by mhozza** [comment]
+1 this is happening when I'm calling File.createNewFile on existing file - should return false, instead throws this RuntimeException.

**Comment by twobitlabs** [comment]
I'm seeing this same error on Robolectric 3.8. If I run test classes individually, they pass. If I run all tests in one go, I invariably see this failure on certain classes, and it's not consistently the same ones. It seems like Robolectric is stepping on its own toes, attempting to create temp directories that have already been created (and were perhaps not properly cleaned up?).
