### ISSUE TITLE
Unable to Run test case class file , 

### ISSUE THREAD

**Issue by vikassminq** [robolectric/robolectric#3441]
### Description
Follow the Getting setup process . 
http://robolectric.org/getting-started/

java.lang.VerifyError: Expecting a stackmap frame at branch target 75
Exception Details:
  Location:
    com/razorpay/RzpTokenReceiver.onReceive(Landroid/content/Context;Landroid/content/Intent;)V @17: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2bb8 0011 1202 01b9 0016 0300 594d b800
    0x0000010: 109a 003a 2a04 b600 1259 4e12 01b6 000e
    0x0000020: 593a 04c7 000c bb00 0b59 b700 143a 04bb
    0x0000030: 000a 592c 2bb6 000d b700 134c 1904 2bb6
    0x0000040: 0015 572d 1201 1904 b600 0fb1          

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:320)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:36)
	at org.robolectric.shadows.ShadowApplication.registerBroadcastReceivers(ShadowApplication.java:134)
	at org.robolectric.shadows.ShadowApplication.bind(ShadowApplication.java:123)
	at org.robolectric.shadows.CoreShadowsAdapter.bind(CoreShadowsAdapter.java:49)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:119)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

### Steps to Reproduce
http://robolectric.org/getting-started/

### Robolectric & Android Version
Robolectric : org.robolectric:robolectric:3.4.2
Android : Android Studio 2.3.3.

**Comment by Kisty** [comment]
What does your `app/build.gradle` file look like? Knowing this would help.

**Comment by utzcoz** [comment]
Please try latest Robolectric 4.9 to check whether this issue still exists. Feel free to reopen this issue if you find this issue still exists, and attach a minimal reproducable app for later investigation. Thanks.
