### ISSUE TITLE
java.lang.ClassCastException: MyClass cannot be cast to org.robolectric.internal.bytecode.ShadowedObject

### ISSUE THREAD

**Issue by vudzkostek** [robolectric/robolectric#3463]
### Description
When I run single unit test from Android Studio (3.0 RC2) everything is ok.
When I try to run all tests from terminal:
`./gradlew -Dorg.gradle.daemon=false --console=plain -Pandroid.test.maxParallelForks=4 ModuleName:testDevDebug`
Almost all tests fail because of exception in title.
Everything started after updating gradle plugin to 3.0.0-beta7

I have custom ShadowProvider:
```java
public class MyShadows implements ShadowProvider {
    private static final HashMap<String, String> SHADOW_MAP = new HashMap<>();

    static {
        SHADOW_MAP.put("com.package.MyClass", "com.package.ShadowMyClass");
    }

    public static ShadowMyClass shadowOf(MyClass address) {
        return shadowOf_(address);
    }

    @Override
    public void reset() {
        // nop
    }

    @Override
    public String[] getProvidedPackageNames() {
        return new String[] {
                "com.package",
        };
    }

    @Override
    public java.util.Map<String, String> getShadowMap() {
        return SHADOW_MAP;
    }

    @SuppressWarnings("unchecked")
    private static <T> T shadowOf_(Object object) {
        return (T) Shadow.extract(object);
    }
}
```
(I can see it in org.robolectric.internal.ShadowProvider generated file and usage is confirmed by stack trace below)

```java
java.lang.ClassCastException: com.package.MyClass cannot be cast to org.robolectric.internal.bytecode.ShadowedObject
	at org.robolectric.internal.bytecode.ShadowImpl.extract(ShadowImpl.java:17)
	at org.robolectric.shadow.api.Shadow.extract(Shadow.java:26)
	at com.package.MyShadows.shadowOf_(MyShadows.java:100)
	at com.package.MyShadows.shadowOf(MyShadows.java:78)
	at com.package.Caller1.reset(Caller1.java:581)
	at com.package.TestLifecycle.beforeTest(TestLifecycle.java:29)
	at com.package.CustomRobolectricTestRunner$TestLifecycle.beforeTest(CustomRobolectricTestRunner.java:152)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:294)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:222)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

MyClass is a final class. It's provided by dependency (my own library in local maven repo)

### Steps to Reproduce
`./gradlew -Dorg.gradle.daemon=false --console=plain -Pandroid.test.maxParallelForks=4 ModuleName:testDevDebug`

### Robolectric & Android Version
robolectric 3.4.2
targetSdkVersion = 25
compileSdkVersion = 26
buildToolsVersion = '26.0.2'

### Link to a public git repo demonstrating the problem:
https://github.com/vudzkostek/ShadowsFailure

**Comment by xian** [comment]
@vudzkostek, are you using the annotation processor to generate `MyShadows`?

Could you provide a git repo demonstrating the problem? Thanks!

**Comment by vudzkostek** [comment]
MyShadows is not generated, it was created manually to provide shadows for final classes from internal sdk. Unfortunately I cannot publish git repo as it company's project. But I will create new project and try to reproduce this issue, then publish it

**Comment by vudzkostek** [comment]
@xian I created simple project that fails for same reason regardless of running in Android Studio or through gradlew
https://github.com/vudzkostek/ShadowsFailure

**Comment by vudzkostek** [comment]
I solved it by adding `@Config(shadows = {ShadowMyClass.class})` to each test file
