### ISSUE TITLE
After delete .gradle dir,aways happen this :Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()

### ISSUE THREAD

**Issue by wuseal** [robolectric/robolectric#3470]
I delete the .gradle dir, why also aways error with this .No one time sccucess
```
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:612)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:224)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:93)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
OMG,AnyWay to find the reason? 

AndroidStudio 2.3.3
Android Gradle Plugin:2.3.3
KotlinVersion:1.1.51
Robolectric Version: 3.4.2
TestCode like this
```
@Config(constants = BuildConfig::class)
@RunWith(RobolectricTestRunner::class)
class FileUtilsTest {

    @Test
    fun testEnter() {
        assert(ENTER=="/r/n")
    }


}
```
Iam sorry,some private reason,can't not upload the project

**Comment by wuseal** [comment]
Thanks for God, I find the reason 
With debugging the run time steps,I find that 💯 
First ,The  error stack trace is caused by another error `Can not find class (android.app.Application)`
Then.I found that my mockable android jar has problem because of the task `mockableAndroidJar`
Last. After resolve the mock android jar problem , the error was fixed ,
I close this issue ,make a log to help anyone would need this answer

**Comment by jhz-zhangyun** [comment]
Hello I have encountered the same problem how can this solve it?

**Comment by jhz-zhangyun** [comment]
![32](https://user-images.githubusercontent.com/20765461/32318558-973db106-bff2-11e7-934e-2d21baffa9b6.png)

**Comment by wuseal** [comment]
删除.gradle文件夹试过了没

**Comment by jhz-zhangyun** [comment]
删了试了的，没办法解决，困扰两天了，555

**Comment by jhz-zhangyun** [comment]
compileSdkVersion 26就行，19不支持

**Comment by wuseal** [comment]
解决了就好

**Comment by ysyyork** [comment]
@wuseal you are genius my friend! 你是天才！thanks!
