### ISSUE TITLE
 java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()

### ISSUE THREAD

**Issue by jhz-zhangyun** [robolectric/robolectric#3503]
"C:\Program Files\Android\android-studio2.3\android-studio\jre\bin\java" -Didea.launcher.port=7532 "-Didea.launcher.bin.path=C:\Program Files\Android\android-studio2.3\android-studio\bin" -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Android\android-studio2.3\android-studio\lib\idea_rt.jar;C:\Program Files\Android\android-studio2.3\android-studio\plugins\junit\lib\junit-rt.jar;C:\Users\zhangyun\AppData\Local\Android\sdk\platforms\android-19\data\res;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\build\intermediates\classes\test\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\build\intermediates\classes\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\TalkingDataAnalytics.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\nineoldandroids-2.4.0.jar;C:\Users\zhangyun\.android\build-cache\e1c8cf4c8abe50dfb5274cf5cac98d79531c683f\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\e1c8cf4c8abe50dfb5274cf5cac98d79531c683f\output\res;C:\Users\zhangyun\.android\build-cache\e1c8cf4c8abe50dfb5274cf5cac98d79531c683f\output\jars\libs\aliyun-android-sdk.0.1.0.jar;C:\Users\zhangyun\.android\build-cache\86afcc108c1d83e1c58846878034e6e19f774c78\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\86afcc108c1d83e1c58846878034e6e19f774c78\output\res;C:\Users\zhangyun\.android\build-cache\46de1ad63fc42d7cc76930f74ba25df2fca3e041\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\46de1ad63fc42d7cc76930f74ba25df2fca3e041\output\res;C:\Users\zhangyun\.android\build-cache\46de1ad63fc42d7cc76930f74ba25df2fca3e041\output\jars\libs\okhttp-2.5.0.jar;C:\Users\zhangyun\.android\build-cache\46de1ad63fc42d7cc76930f74ba25df2fca3e041\output\jars\libs\okio-1.6.0.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\xUtils-2.6.14.jar;C:\Users\zhangyun\.android\build-cache\a2b37846ef4458c7251efd2d97181992f0590f5c\output\res;C:\Users\zhangyun\.android\build-cache\a2b37846ef4458c7251efd2d97181992f0590f5c\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\a2b37846ef4458c7251efd2d97181992f0590f5c\output\jars\libs\internal_impl-23.1.1.jar;C:\Users\zhangyun\.android\build-cache\21f549cea2152df78c73de6af345f8fd662c223e\output\res;C:\Users\zhangyun\.android\build-cache\21f549cea2152df78c73de6af345f8fd662c223e\output\jars\classes.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\qtsdk.jar;C:\Users\zhangyun\.android\build-cache\075e08cbcff922d132f25a5cfe7247b9d5d093a4\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\075e08cbcff922d132f25a5cfe7247b9d5d093a4\output\res;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\hcicloud-3.9.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\hcicloud_player-3.9.jar;C:\Users\zhangyun\AppData\Local\Android\sdk\extras\android\m2repository\com\android\support\support-annotations\23.1.1\support-annotations-23.1.1.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\Msc.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\Sunflower.jar;C:\Users\zhangyun\.android\build-cache\70403a3611bc8d152e87fd017ddd3c1694f19905\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\70403a3611bc8d152e87fd017ddd3c1694f19905\output\res;C:\Users\zhangyun\.android\build-cache\074ec8f84a16a0c62cc7e222a94076ebfd8b6baa\output\jars\classes.jar;C:\Users\zhangyun\.android\build-cache\074ec8f84a16a0c62cc7e222a94076ebfd8b6baa\output\res;C:\Users\zhangyun\.android\build-cache\074ec8f84a16a0c62cc7e222a94076ebfd8b6baa\output\jars\libs\pinyin4j-2.5.0.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\libs\kwmusic-autosdk-v1.5 .jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\testlibrary\build\intermediates\classes\test\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\testlibrary\build\intermediates\classes\debug;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\backport-util-concurrent\backport-util-concurrent\3.1\682f7ac17fed79e92f8e87d8455192b63376347b\backport-util-concurrent-3.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-profile\2.2.1\3950071587027e5086e9c395574a60650c432738\maven-profile-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\nekohtml\xercesMinimal\1.9.6.2\d1c5e063683a0e6f77cd5f051a9d4af48346fa6\xercesMinimal-1.9.6.2.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-settings\2.2.1\2236ffe71fa5f78ce42b0f5fc22c54ed45f14294\maven-settings-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-library\1.3\4785a3c21320980282f9f33d0d1264a69040538f\hamcrest-library-1.3.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\5.0.1\7b7147a390a93a14d2edfdcf3f7b0e87a0939c3e\asm-commons-5.0.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.google.android.apps.common.testing.accessibility.framework\accessibility-test-framework\2.1\c2d6267c3ad0435ddf9e27a94a0e0af4ca3fdfbb\accessibility-test-framework-2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-lightweight\1.0-beta-6\b3815078570c3b1f0667e123d59717c6b726c6c2\wagon-http-lightweight-1.0-beta-6.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\nekohtml\nekohtml\1.9.6.2\2d960be7b62ae6622dbbbe49ab4ffdc609f85c80\nekohtml-1.9.6.2.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\5.0.1\2fd56467a018aafe6ec6a73ccba520be4a7e1565\asm-5.0.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-repository-metadata\2.2.1\98f0c07fcf1eeb213bef8d9316a9935184084b06\maven-repository-metadata-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\20.0\89507701249388e1ed5ddcf8c41f4ce1be7831ef\guava-20.0.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\utils\3.5.1\f6bcebdffea801c80ab2dc2b933c7562bfc111b0\utils-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.mockito\mockito-core\1.9.5\c3264abeea62c4d2f367e21484fbb40c7e256393\mockito-core-1.9.5.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model\2.2.1\c0a1c17436ec3ff5a56207c031d82277b4250a29\maven-model-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\xmlpull\xmlpull\1.1.3.1\2b8e230d2ab644e4ecaa94db7cdedbc40c805dfa\xmlpull-1.1.3.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\1.0\9b473564e792c2bdf1449da1f0b1b5bff9805704\objenesis-1.0.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.ibm.icu\icu4j\53.1\786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f\icu4j-53.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\robolectric\3.5.1\82490ab19a371ff2d8514dc51386aac9979b9230\robolectric-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\5.0.1\1b1e6e9d869acd704056d0a4223071a511c619e6\asm-tree-5.0.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.almworks.sqlite4java\sqlite4java\0.282\745a7e2f35fdbe6336922e0d492c979dbbfa74fb\sqlite4java-0.282.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-project\2.2.1\8239e98c16f641d55a4ad0e0bab0aee3aff8933f\maven-project-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-container-default\1.0-alpha-9-stable-1\94aea3010e250a334d9dab7f591114cd6c767458\plexus-container-default-1.0-alpha-9-stable-1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\classworlds\classworlds\1.1-alpha-2\5adf2e681c57d7f48038b602f3ca2254ee82d47\classworlds-1.1-alpha-2.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interpolation\1.11\ad9dddff6043194904ad1d2c00ff1d003c3915f7\plexus-interpolation-1.11.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact-manager\2.2.1\ec355b913c34d37080810f98e3f51abecbe1572b\maven-artifact-manager-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.52\88a941faf9819d371e3174b5ed56a3f3f7d73269\bcprov-jdk15on-1.52.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-ant-tasks\2.1.3\b09be554228d66d208e5fef5266844aacf443abc\maven-ant-tasks-2.1.3.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant\1.8.0\7b456ca6b93900f96e58cc8371f03d90a9c1c8d1\ant-1.8.0.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant-launcher\1.8.0\8b53ba16fa62fb1034da8f1de200ddc407c8381\ant-launcher-1.8.0.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\xpp3\xpp3_min\1.1.4c\19d4e90b43059058f6e056f794f0ea4030d60b86\xpp3_min-1.1.4c.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-error-diagnostics\2.2.1\e81bb342d7d172f23d108dc8fa979a1facdcde8e\maven-error-diagnostics-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-file\1.0-beta-6\6c53633505460caf49d2660de1e24744d915afb9\wagon-file-1.0-beta-6.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.thoughtworks.xstream\xstream\1.4.8\520d90f30f36a0d6ba2dc929d980831631ad6a92\xstream-1.4.8.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-provider-api\1.0-beta-6\3f952e0282ae77ae59851d96bb18015e520b6208\wagon-provider-api-1.0-beta-6.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\junit\3.5.1\12dc524d1d136b3f79c9763d432f75af928adaf\junit-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-shared\1.0-beta-6\ccd70d7e0d8c085e648a83f072da06ca9a53be94\wagon-http-shared-1.0-beta-6.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\annotations\3.5.1\8e81f810d673c213caa72613837b74414e1eab2f\annotations-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\2.2.1\23600f790d4dab2cb965419eaa982e3e84c428f8\maven-artifact-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.jmockit\jmockit\1.32\f1be438604783c59cdf80584acee551fff031fd1\jmockit-1.32.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\shadows-framework\3.5.1\424ed8da8f49ae1a5576eacd1fa72b6c2c36076b\shadows-framework-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\resources\3.5.1\880a3514d9a21ae44bee5eadabbe6162d73c067\resources-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-utils\1.5.15\c689598ce1eb94c304817877ed15911099972526\plexus-utils-1.5.15.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-plugin-registry\2.2.1\72a24b7775649af78f3986b5aa7eb354b9674cfd\maven-plugin-registry-2.2.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\2.6.1\d9521f2aecb909835746b7a5facf612af5e890e8\protobuf-java-2.6.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\sandbox\3.5.1\acfbba0143e3f5ad50722af0c70eb186e605a07d\sandbox-3.5.1.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\zhangyun\.gradle\caches\modules-2\files-2.1\org.robolectric\shadowapi\3.5.1\2f96f59961a888cbcd366fc10358e64161d71ac1\shadowapi-3.5.1.jar;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\build\intermediates\sourceFolderJavaResources\test\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\testlibrary\build\intermediates\sourceFolderJavaResources\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\client-android-robot-speech\build\intermediates\sourceFolderJavaResources\debug;C:\Users\zhangyun\AndroidStudioProjects\Speech_WorkSpace\build\generated\mockable-android-19.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 cn.efrobot.speech.SpeechEventTest
Exception in thread "main" java.lang.annotation.AnnotationFormatError: Invalid default: public abstract java.lang.Class org.robolectric.annotation.Config.application()
	at java.lang.reflect.Method.getDefaultValue(Method.java:612)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:132)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:224)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:93)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by jhz-zhangyun** [comment]
compileSdkVersion 26
