### ISSUE TITLE
Robolectric 3.5.1: RuntimeException when parsing notification_template_header.xml

### ISSUE THREAD

**Issue by cesar1000** [robolectric/robolectric#3518]
Parsing [notification_template_header.xml](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/res/layout/notification_template_header.xml), which happens when inflating a notification, throws the following exception:

```
android.view.InflateException: XML file jar:/Users/cpuerta/.m2/repository/org/robolectric/android-all/8.0.0_r4-robolectric-0/android-all-8.0.0_r4-robolectric-0.jar!/res/layout/notification_template_material_big_text.xml line #-1 (sorry, not yet implemented): no value for android:attr/notificationHeaderStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style com.twitter.android:Theme_AppCompat (and parents) (forced)]
Caused by: java.lang.RuntimeException: no value for android:attr/notificationHeaderStyle in theme with applied styles: [Style android:Theme_DeviceDefault (and parents) (forced), Style com.twitter.android:Theme_AppCompat (and parents) (forced)]
	at org.robolectric.shadows.ShadowAssetManager.buildTypedValue(ShadowAssetManager.java:774)
	at org.robolectric.shadows.ShadowAssetManager.attrsToTypedArray(ShadowAssetManager.java:849)
	at org.robolectric.shadows.ShadowResourcesImpl$ShadowThemeImpl.obtainStyledAttributes(ShadowResourcesImpl.java:217)
	at android.content.res.ResourcesImpl$ThemeImpl.obtainStyledAttributes(ResourcesImpl.java)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java:1521)
	at android.content.Context.obtainStyledAttributes(Context.java:679)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:756)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.widget.RemoteViews.inflateView(RemoteViews.java:3278)
	at android.widget.RemoteViews.apply(RemoteViews.java:3255)
	at android.widget.RemoteViews.apply(RemoteViews.java:3248)
```

This is in Robolectric 3.5.1 with Android 26.

It seems like resolving style="?attr/notificationHeaderStyle" will no apply the theme first (android:theme="@style/Theme.Material.Notification") so that theme definitions won't be available.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
