### ISSUE TITLE
NPE after upgrading to AS & AGP to 3.0.0

### ISSUE THREAD

**Issue by tito0224** [robolectric/robolectric#3535]
### Description
After upgrading to AS 3.0 and the new Android gradle plugin all my unit tests fail with the below stack trace:

```
java.lang.NullPointerException
	at android.content.ContextWrapper.getResources(ContextWrapper.java:86)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:149)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:220)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:108)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:35)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:62)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I have followed all the instructions on http://robolectric.org/getting-started/ but does not seem to work any more. Am I missing something?

I removed all  `@Config(constants = BuildConfig.class)` annotations. I was using Robolectric 3.2.2 before upgrading to 3.5.1 during this process.

**Comment by jaredsburrows** [comment]
I am seeing this with Android Gradle Plugin 2.3.3 and Robolectric 3.6.1.

**Comment by hidroh** [comment]
@jaredsburrows do you have multi-flavor setup in your project? We have 1 with flavors and 1 without flavors, only the one with flavors failed with the above NPE, so I suspect it may be due to multi-flavor setup, and the fact that Robolectric resources loading has now been changed to use framework implementation.

**Comment by hidroh** [comment]
Adding `constants=<package>.BuildConfig` to robolectric.properties resolves this. In our setup we have 2-dimensional flavors so probably it's causing issue for Robolectric resources loading.

**Comment by jaredsburrows** [comment]
@hidroh No. The project only has `buildtypes`. I will try the `robolectric.properties` fix later.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
