### ISSUE TITLE
Error:java.lang.ClassNotFoundException: Class android.content.pm.IPackageStatsObserver not found

### ISSUE THREAD

**Issue by jhz-zhangyun** [robolectric/robolectric#3537]
### 
![37](https://user-images.githubusercontent.com/20765461/32878089-808fa5de-cadf-11e7-9a73-8177b680de74.png)

**Comment by ramack** [comment]
I see a similar issue with roboelectric 3.5.1, AndroidStudio 3.0.1:
```
Exception in thread "main" java.lang.TypeNotPresentException: Type android.content.pm.IPackageStatsObserver not present
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:54)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
        at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:399)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
Caused by: java.lang.ClassNotFoundException: Class android.content.pm.IPackageStatsObserver not found
        at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)

```

**Comment by jongerrish** [comment]
What version of Android do you build against?

On Dec 12, 2017 1:44 PM, "Raphael Mack" <notifications@github.com> wrote:

I see a similar issue with roboelectric 3.5.1, AndroidStudio 3.0.1:

Exception in thread "main" java.lang.TypeNotPresentException: Type
android.content.pm.IPackageStatsObserver not present
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:85)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:54)
        at sun.invoke.util.BytecodeDescriptor.parseMethod(BytecodeDescriptor.java:41)
        at java.lang.invoke.MethodType.fromMethodDescriptorString(MethodType.java:1067)
        at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:399)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown
Source)
        at org.objectweb.asm.MethodVisitor.visitInvokeDynamicInsn(Unknown
Source)
        at org.objectweb.asm.ClassReader.a(Unknown Source)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:401)
        at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
        at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
        at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)
Caused by: java.lang.ClassNotFoundException: Class
android.content.pm.IPackageStatsObserver not found
        at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.invoke.util.BytecodeDescriptor.parseSig(BytecodeDescriptor.java:83)


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robolectric/robolectric/issues/3537#issuecomment-351204673>,
or mute the thread

**Comment by ramack** [comment]
I used 
  compileSdkVersion 25
  buildToolsVersion '25.0.3'

But also changed to 26

**Comment by jongerrish** [comment]
https://github.com/robolectric/robolectric/pull/3593 should fix this

**Comment by jongerrish** [comment]
This will be available in 3.6 coming in the next week hopefully

**Comment by ramack** [comment]
But with API level 25 it should in theory work, right?
Anyhow thanks for the fix. Looking forward to the release.

**Comment by jongerrish** [comment]
Is the class in the android.jar (stubs jar from SDK)? I think the problem
is with the desugar tool that seems to be running on unit tests. (I'm not
sure why as this code never gets deployed on a device). This class is not
provided to the desugar tool.

Hopefully we'll get the new release out this week or next.

**Comment by MarcoMauricio** [comment]
Seeing something similar with 
```
Android Studio 3.1.1
Build #AI-173.4697961, built on April 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
``` 
compileSdkVersion 27
android{
    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 27
       ... }
... }
dependencies {
    androidTestImplementation 'junit:junit:4.12'
    androidTestImplementation 'org.robolectric:robolectric:3.8'
    ...
}
```

Logs: 
```Exception in thread "main" java.lang.IllegalStateException: Couldn't desugar invokedynamic for org/robolectric/shadows/ShadowApplicationPackageManager.run using java/lang/invoke/LambdaMetafactory.metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (6) with arguments [()V, org/robolectric/shadows/ShadowApplicationPackageManager.lambda$getPackageSizeInfo$0(Ljava/lang/Object;Landroid/content/pm/PackageStats;)V (6), ()V]
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:474)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1623)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)
Caused by: java.lang.IllegalAccessException: no such method: org.robolectric.shadows.ShadowApplicationPackageManager.lambda$getPackageSizeInfo$0(Object,PackageStats)void/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:867)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toMethodHandle(LambdaDesugaring.java:665)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.toJvmMetatype(LambdaDesugaring.java:647)
	at com.google.devtools.build.android.desugar.LambdaDesugaring$InvokedynamicRewriter.visitInvokeDynamicInsn(LambdaDesugaring.java:408)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: android/content/pm/PackageParser$IntentInfo
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	... 13 more
Caused by: java.lang.ClassNotFoundException: Class android.content.pm.PackageParser$IntentInfo not found
	at com.google.devtools.build.android.desugar.HeaderClassLoader.findClass(HeaderClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more```

**Comment by jongerrish** [comment]
Marco,

I don't think you want a dependency on Robolectric in your androidTest
source root, these are for instrumentation tests that run on a device.

Robolectric tests should live in the regular tests source root.

**Comment by MarcoMauricio** [comment]
You're right, I was using it in regular tests and it was working fine. I switched back androidTest and started having problem and I completely forgot that instrumentation test deal with the problem I was trying to solve.

I removed the comment to not cause confusion.
