### ISSUE TITLE
java.lang.NullPointerException at org.robolectric.shadows.ShadowViewConfiguration.setup(ShadowViewConfiguration.java:74)

### ISSUE THREAD

**Issue by AlienAsRoger** [robolectric/robolectric#3543]
### Description
```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowViewConfiguration.setup(ShadowViewConfiguration.java:74)
	at org.robolectric.shadows.ShadowViewConfiguration.get(ShadowViewConfiguration.java:91)
	at android.view.ViewConfiguration.get(ViewConfiguration.java)
	at android.view.View.__constructor__(View.java:4026)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.FrameLayout.<init>(FrameLayout.java)
```
### Robolectric & Android Version
```
robolectric  = '3.5.1' 
buildToolsVersion = '26.0.2'
gradleVersion = 'com.android.tools.build:gradle:3.0.0'
```

**Comment by PavelGP** [comment]
Try read this issue https://github.com/robolectric/robolectric/issues/3157
So try to disable aapt2. Works for me.

**Comment by jongerrish** [comment]
I imagine this is fixed.

Please reopen if its still an issue on Robolectric 4.0+
