### ISSUE TITLE
Change request/bug: Glide 4.4.0 not handling error "You cannot start a load for a destroyed activity"

### ISSUE THREAD

**Issue by lam-amsiq** [robolectric/robolectric#3577]
We recently migrated from Picasso to Glide and now we run into crashes related to Glide trying to load images on a destroyed activity. It would be a better experience if Glide could handle this issue for us as Picasso did.

Check:
```
if (context instanceof Activity && ((Activity) context).isDestroyed())  return;
```

Stack:
```
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:302)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:127)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:112)
       at com.bumptech.glide.Glide.with(Glide.java:638)
       at com.app.devUtilities.ImageLoader.setIcon(ImageLoader.java:206)
       at com.app.views.Notification.BottomNotification.init(BottomNotification.java:72)
       at com.app.views.Notification.BottomNotification_.onViewChanged(BottomNotification_.java:119)
       at org.androidannotations.api.view.OnViewChangedNotifier.notifyViewChanged(OnViewChangedNotifier.java:41)
       at com.app.views.Notification.BottomNotification_.onFinishInflate(BottomNotification_.java:66)
       at com.app.views.Notification.BottomNotification_.build(BottomNotification_.java:51)
       at com.app.activities.forgotpassword.ForgotPasswordActivity.sendEmailFailed(ForgotPasswordActivity.java:280)
       at com.app.controllers.ForgotPasswordController$1.onFailure(ForgotPasswordController.java:58)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$2.run(ExecutorCallAdapterFactory.java:79)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
[Fabric](http://crashes.to/s/a3dc5f60aa6)

**Comment by helpdesskApplication** [comment]
We are also facing same issues, fabric has noted 80% crashes with the error.
Fatal Exception: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
       at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:302)
       at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:127)
       at com.bumptech.glide.Glide.with(Glide.java:661)
       at com.android.helpdessk.helpdesk.activities.HomeScreenActivity$32$2.run(HomeScreenActivity.java:2521)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
