### ISSUE TITLE
ShadowHandler don't process Runnables in expected Thread

### ISSUE THREAD

**Issue by Ponyets** [robolectric/robolectric#361]
I new a Handler in mainthread(and I have tried assign Looper.getMainLooper() as the handler's param), and post a `Runnable` in another thread. it seems that the `Runnable` run in the thread which post it. I'm wondering how can I use ShadowHandler to test communication between threads

Exception in thread "Thread-3" junit.framework.AssertionFailedError: expected:<Thread[main,5,main]> but was:<Thread[Thread-3,5,main]>
    at junit.framework.Assert.fail(Assert.java:50)
    at junit.framework.Assert.failNotEquals(Assert.java:287)
    at junit.framework.Assert.assertEquals(Assert.java:67)
    at junit.framework.Assert.assertEquals(Assert.java:74)
    at com.sankuai.meituan.model.message.TestContentObserver$HandlerCheckObserver.onChanged(TestContentObserver.java:58)
    at com.sankuai.meituan.model.message.ContentObserver$1.run(ContentObserver.java:32)
    at com.xtremelabs.robolectric.util.Scheduler.postDelayed(Scheduler.java:35)
    at com.xtremelabs.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:116)
    at com.xtremelabs.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:50)
    at com.xtremelabs.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:45)
    at android.os.Handler.post(Handler.java)

**Comment by mdoufei** [comment]
@Test
    public void shouldExecuteRunnable() throws Exception {

        final CountDownLatch signal = new CountDownLatch(1);

        //not run.
        final boolean[] result = {false};
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                result[0] = true;
                signal.countDown();
            }
        };
        HandlerThread handlerThread = new HandlerThread("HandlerThread");
        handlerThread.start();
        Handler handler = new Handler(handlerThread.getLooper());
        handler.post(runnable);


        //work
//        Completable.fromAction(()->{
//            result[0] = true;
//            signal.countDown();
//        }).subscribeOn(Schedulers.io()).subscribe(()->{},Throwable::printStackTrace);

        signal.await(2,TimeUnit.SECONDS);
        Assert.assertTrue(result[0]);
    }

**Comment by yuhui2016github** [comment]
@mdoufei

**Comment by yuhui2016github** [comment]
@mdoufei 
add shadowOf(mHandler.getLooper()).getScheduler().advanceToNextPostedRunnable(); after hander.post(runnable)

but I found that the runnable would be run on mainThread rather than on HandlerThread, that is different from runing on real device
