### ISSUE TITLE
java.lang.VerifyError: org/robolectric/android/fakes/RoboInstrumentation

### ISSUE THREAD

**Issue by jrodbx** [robolectric/robolectric#3613]
### Description
After upgrading from Robolectric 3.5.1 to 3.6, tests start to fail with the following error:
```
java.lang.VerifyError: org/robolectric/android/fakes/RoboInstrumentation
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:109)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:328)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:241)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

### Robolectric & Android Version
Robolectric 3.6
Android Compile SDK Level: 26
Android Target SDK Level: 26

**Comment by jrodbx** [comment]
Examining more closely, one of the failed tests displays a slightly different, yet more useful error message:
```
java.lang.VerifyError: class org.robolectric.android.fakes.RoboInstrumentation overrides final method specifyDexMakerCacheProperty.()V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:172)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:133)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:132)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:109)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:328)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:241)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
```

That clue points to https://github.com/robolectric/robolectric/commit/14d291498cc9ab4a2a12d65578461a775af8bd40#diff-6ebe788bd250cba3e629fd563751be27, which changed RoboInstrumentation to extend from MonitoringInstrumentation.  

MonitoringInstrumentation#specifyDexMakerCacheProperty was a final method in `com.android.support.test:runner` until version `1.0.2-alpha1` when it was extracted to `com.android.support.test:monitor` and set to non-final.

Solution: upgrade to Espresso 3.0.2-alpha1 and `com.android.support.test:runner:1.0.2-alpha1`.
