### ISSUE TITLE
Robolectric 3.6 & Android Gradle Plugin 3.0.1 causes android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by ze1os** [robolectric/robolectric#3618]
### Description
After updating to 3.6 and android plugin for gradle 3.0.1 i got the following exception:
```
android.content.res.Resources$NotFoundException: File /home/hacker/Projects/4.3/mobile-cadisAPP-rio/rio/build/intermediates/merged-not-compiled-resources/debug/drawable/abc_vector_test.xml from drawable resource ID #0x7f09005e

	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:59)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:56)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:268)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.Resources.getDrawable(Resources.java:806)
	at android.content.Context.getDrawable(Context.java:458)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:128)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:200)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
	at kam.android.rio.base.presentation.activity.BaseActivityView.onCreate(BaseActivityView.java:97)
	at android.app.Activity.performCreate(Activity.java:6251)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:74)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:364)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:71)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:81)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:168)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:106)
	at kam.android.rio.infrastructure.presentation.login.AppModeSelectionViewTest.testUnregisterDevice(AppModeSelectionViewTest.java:139)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:535)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:249)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: org.xmlpull.v1.XmlPullParserException: XML file /home/hacker/Projects/4.3/mobile-cadisAPP-rio/rio/build/intermediates/merged-not-compiled-resources/debug/drawable/abc_vector_test.xml line #-1 (sorry, not yet implemented)<vector> tag requires viewportWidth > 0
	at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:606)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:567)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)
	... 57 more
```

### Steps to Reproduce
Test
```
@RunWith(RobolectricTestRunner.class)
@Config(sdk = 24)
public class AppModeSelectionViewTest
{
  ...
  StartupActivity startupActivity = Robolectric.setupActivity(StartupActivity.class);`
  ...
}
```

Activity
```
public class StartupActivity extends AppCompatActivity {
  ...
}

```
build.gradle
```
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```
### Robolectric & Android Version
robolectric  = '3.6' 
gradleVersion = 'com.android.tools.build:gradle:3.0.1'
androidMinSdkVersion = 17
androidTargetSdkVersion = 22
androidCompileSdkVersion = 26
com.android.support:appcompat-v7:26.0.2

**Comment by MasterEmit** [comment]
Is there any idea for a temporarily workaround? We are struggling with the same problem.

**Comment by shafty023** [comment]
I'm having the same issue as well

**Comment by rezazarchi** [comment]
same issue

**Comment by Pietervdv** [comment]
I have the same issue with #3872 and I am using different "newer" versions

**Comment by AtlasRider** [comment]
Also having this issue

**Comment by fargus9** [comment]
+1

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
