### ISSUE TITLE
java.lang.NullPointerException 	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)

### ISSUE THREAD

**Issue by zhiyi20101** [robolectric/robolectric#3635]
### Description
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)
### Steps to Reproduce
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)
### Robolectric & Android Version
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)
### Link to a public git repo demonstrating the problem:
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowAssetManager.buildAttributes(ShadowAssetManager.java:654)

**Comment by jongerrish** [comment]
You'll need to provide more information if you want us to investigate. A reproducable test case would be a great start :-)
