### ISSUE TITLE
Resources$NotFoundException

### ISSUE THREAD

**Issue by dmitrikudrenko** [robolectric/robolectric#3657]
### Description
Activity:

    public class MvpAppCompatActivity extends AppCompatActivity {
        private MvpDelegate<? extends MvpAppCompatActivity> mMvpDelegate;

        @Override
        protected void onCreate(final Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            getMvpDelegate().onCreate(savedInstanceState);
        }

        /**
         * @return The {@link MvpDelegate} being used by this Activity.
         */
        public MvpDelegate getMvpDelegate() {
            if (mMvpDelegate == null) {
                mMvpDelegate = new MvpDelegate<>(this);
            }
            return mMvpDelegate;
        }
    }

Test:

    @RunWith(RobolectricTestRunner.class)
    @Config(constants = BuildConfig.class, sdk = 26)
    public class MvpAppCompatActivityTest {
        private ActivityController< MvpAppCompatActivity > activityController;
        private MvpDelegate mvpDelegate;

        @Before
        public void setUp() throws Exception {
            activityController = Robolectric.buildActivity(MvpAppCompatActivity.class);
            mvpDelegate = spy(activityController.get().getMvpDelegate());
        }

        @Test
        public void shouldOnCreateCalled() throws Exception {
            final Bundle bundle = mock(Bundle.class);
            activityController.create(bundle);
            verify(mvpDelegate).onCreate(bundle);
        }
    }

### Robolectric & Android Version
'org.robolectric:robolectric:3.6.1'
androidCompileSdkVersion = 26

### Error
    android.content.res.Resources$NotFoundException: Resource ID #0x7f090053

	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:195)
	at android.content.res.Resources.getValue(Resources.java:1315)
	at android.support.v7.widget.AppCompatDrawableManager.createDrawableIfNeeded(AppCompatDrawableManager.java:234)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:755)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:193)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:87)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:128)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java)
	at android.support.v7.app.AppCompatDelegateImplN.<init>(AppCompatDelegateImplN.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:198)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
	at io.github.dmitrikudrenko.mdrxl.mvp.MvpAppCompatActivity.onCreate(MvpAppCompatActivity.java:12)
	at android.app.Activity.performCreate(Activity.java:6975)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:74)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:364)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:71)
	at io.github.dmitrikudrenko.mdrxl.mvp.MvpAppCompatActivityTest.shouldOnCreateCalled(MvpAppCompatActivityTest.java:31)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:535)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:249)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

**Comment by dmitrikudrenko** [comment]
Just add ```testOptions.unitTests.includeAndroidResources = true``` in ```build.gradle```
