### ISSUE TITLE
Linkage Error between GoogleApiAvailability and ShadowGoogleApiAvailability

### ISSUE THREAD

**Issue by praveeng145** [robolectric/robolectric#3670]
### Description
Am seeing this error when running the following test case to validate the availability of PlayServices.
From the error message I sense that GoogleApiAvailability class is coming from different versions of play services. How can I fix this?

```
    @Test
    @Config(manifest = Config.NONE, shadows = {ShadowGoogleApiAvailability.class, ShadowGoogleAuthUtil.class})
    public void testGoogleApiAvailability() {
        final ShadowGoogleApiAvailability shadowGoogleApiAvailability
                = Shadows.shadowOf(GoogleApiAvailability.getInstance());
        final int expectedCode = ConnectionResult.SUCCESS;
        shadowGoogleApiAvailability.setIsGooglePlayServicesAvailable(expectedCode);
    }
```

Error : 

> java.lang.LinkageError: loader constraint violation: when resolving method "org.robolectric.shadows.gms.Shadows.shadowOf(Lcom/google/android/gms/common/GoogleApiAvailability;)Lorg/robolectric/shadows/gms/common/ShadowGoogleApiAvailability;" the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class, com/org/StaticTest, and the class loader (instance of org/robolectric/internal/bytecode/SandboxClassLoader) for the method's defining class, org/robolectric/shadows/gms/Shadows, have different Class objects for the type com/google/android/gms/common/GoogleApiAvailability used in the signature

	at com.org.StaticTest.test1(StaticTest.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1873)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:773)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:638)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:57)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:146)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:139)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:130)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:139)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)

### Steps to Reproduce
Run the above test cases.

### Robolectric & Android Version

> 
implementation 'com.google.android.gms:play-services-ads:9.2.1'
testImplementation 'org.robolectric:robolectric:3.4.2'
testImplementation "com.google.android.gms:play-services-auth:9.2.1"
testImplementation "org.robolectric:shadows-play-services:3.4-rc2"

Running in Android Studio 3.0 Canary

**Comment by ber4444** [comment]
I got this as well after adding powermockito, perhaps that's what's messing with it.

**Comment by jongerrish** [comment]
We're not actively supporting Google Play Services shadows, I'd recommend instead creating your own fake (subclass GoogleApiAvailability).
