### ISSUE TITLE
Robolectric can not work！please help me！

### ISSUE THREAD

**Issue by sony9997** [robolectric/robolectric#3674]
### Description
**I set up the environment according to the instructions of the official website, but I always get the exception, but I always get the exception:**

Exception in thread "main" java.lang.NoClassDefFoundError: android/app/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.annotation.Config.<clinit>(Config.java:36)
	at org.robolectric.annotation.Config$Builder.<init>(Config.java:401)
	at org.robolectric.RobolectricTestRunner.buildGlobalConfig(RobolectricTestRunner.java:459)
	at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:441)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:244)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: android.app.Application
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more

my JUnit java:
@RunWith(RobolectricTestRunner.class)
public class ExampleUnitTest {
    @Test
    public void addition_isCorrect() throws Exception {
        Integer a=2;
        Integer b=2;
        assertTrue(a==b);
    }
}
### Robolectric & Android Version
Robolectric:3.6.1
grade:4.4.1
java:1.8
android sdk:26
android studio:3.0.1
buildToolsVersion:26.0.2
support library version : '26.0.0-alpha1'

**Comment by samuelHolvi** [comment]
This same thing started to happen to me in a project. Cleaning it from Android Studio didn't help. I then did run tests from the console with `./gradlew test` and everything went well. Afterwards, running tests directly in Android Studio started to work again.

**Comment by sony9997** [comment]
@samuelHolvi Thank you for your reply, but it's not work for me. Can you see the contents of your gradlew file?

**Comment by ysyyork** [comment]
not work for me neither

**Comment by xian** [comment]
Things have changed pretty significantly with the release of Robolectric 4.0; can you give it a try again and reopen this issue if the problem remains? Thanks!

**Comment by sevar83** [comment]
Just came to work this morning, got coffee, hit "Run all unit tests" and voila...
