### ISSUE TITLE
robolectric add poewermock can not use  android.text.TextUtils

### ISSUE THREAD

**Issue by shaomaicheng** [robolectric/robolectric#3697]
my code is:
```java
@RunWith(RobolectricTestRunner.class)
@Config(manifest = Config.NONE, constants = BuildConfig.class)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
```

add powermock rule

```java
 @Rule
    public PowerMockRule rule = new PowerMockRule();
```

in @Test method , add code:
```java
TextUtils.isEmpty("Hello,World")
```

but throw a Exception
```
java.lang.IllegalStateException: Failed to transform class with name android.text.TextUtils. Reason: cannot find android.text.MeasuredText

	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:296)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:204)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:89)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:79)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

so how can I solve this ?

**Comment by dmeng** [comment]
@shaomaicheng 

1) What versions of Robolectric and PowerMock are you using?
2) Which PowerMock libraries are you using? Wondering how much of https://github.com/robolectric/robolectric/issues/1058 might apply to you.
