### ISSUE TITLE
Bulk SQLite Insert throws exception

### ISSUE THREAD

**Issue by xXxXxXxXxXam** [robolectric/robolectric#3716]
### Description

Bulk inserts in SQLite throw an exception `Cannot prepare statement, base error code: 1` in RoboElectric. 

For example a statement like the following will trigger it:

```
// SqliteDatabase db;
db.execSQL("INSERT INTO some_table (field) VALUES (?), (?), (?)", args);
```

This issue is also reported by someone else on StackOverflow here https://stackoverflow.com/questions/47109606/bulk-insert-in-sqlite-not-support-by-robolectric

### Steps to Reproduce

Any insert where there are multiple values will throw this.

### Robolectric & Android Version

The two versions I tried were `3.3.2` and `3.6.1`

**Comment by xXxXxXxXxXam** [comment]
Multi row insert statements were added in sqlite 3.7.11 https://sqlite.org/changes.html#version_3_7_11

According to this, Android got 3.7.11 in Jellybean https://stackoverflow.com/a/4377116/445348

**Comment by xXxXxXxXxXam** [comment]
Ah looks like Roboelectric uses 3.7.10... soooo close.  Is there a way to tell it what version to use or to use a higher version?  I tried using the `sdk` config, that doesn't seem to make a difference.

**Comment by shmakova** [comment]
I have the same problem, is there any solution to test bulk inserts?

**Comment by WildOrangutan** [comment]
Same issue still persists in 4.2 robolectric version

**Comment by WildOrangutan** [comment]
Same issue still persists in 4.2 robolectric version
<details>
<summary>Stacktrace</summary>

```
android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: 1

	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getSqliteException(ShadowSQLiteConnection.java:761)`
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:731)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:720)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:417)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:89)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1769)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1698)
	at com.my.app.database.DatabaseHelperTest.upgradeTest(DatabaseHelperTest.java:23)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[2] prepare() insert into Log values(1,'2',3,4,5),(2,'3',4,5,6) [near ",": syntax error]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:199)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:726)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:720)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:417)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:89)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.$$robo$$android_database_sqlite_SQLiteSession$prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java)
	at android.database.sqlite.SQLiteProgram.$$robo$$android_database_sqlite_SQLiteProgram$__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$executeSql(SQLiteDatabase.java:1769)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$execSQL(SQLiteDatabase.java:1698)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java)
	at com.my.app.database.DatabaseHelperTest.upgradeTest(DatabaseHelperTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 10 more
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[2] prepare() insert into Log values(1,'2',3,4,5),(2,'3',4,5,6) [near ",": syntax error]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1436)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:580)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:635)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:622)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:420)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:417)
	... 4 more
```

</details>

**Comment by guness** [comment]
We can close this one because a solution has been merged: https://github.com/robolectric/robolectric/pull/5216

**Comment by hoisie** [comment]
Thanks @guness
