### ISSUE TITLE
Firebase and FirebaseAnalytics initialization exception

### ISSUE THREAD

**Issue by daniellojewski** [robolectric/robolectric#3722]
### Description
I'm new to unit testing and Robolectric so this is probably the cause of all my problem but still I need your help. 
My test class looks line this:
```
@RunWith(RobolectricTestRunner.class)
@Config(sdk = { 16, 17, 18, 19, 21, 22, 23, 24, 25})
//ALL_SDKS
public class ViewTest {
    MainActivity view;

    @Before
    public void setup() {
        Robolectric.getBackgroundThreadScheduler().pause();
        Robolectric.getForegroundThreadScheduler().pause();

        view = Robolectric.setupActivity(MainActivity.class);

        Robolectric.getBackgroundThreadScheduler().unPause();
        Robolectric.getForegroundThreadScheduler().unPause();
    }

    @Test
    public void test() {
        view.hideContent();
        assertThat(view.binding.activityContent.getVisibility(), is(View.GONE));
    }
}
```
When I ran the test at first I had similar problem to the one described [here](https://stackoverflow.com/questions/38713427/firebase-roboelectric-java-lang-illegalstateexception-firebaseapp-with-name?rq=1) and after using responses provided in that SO post I move forward to following error:
```
java.lang.BootstrapMethodError: call site initialization exception

	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at android.app.job.JobScheduler.<init>(JobScheduler.java)
	at android.app.JobSchedulerImpl.<init>(JobSchedulerImpl.java)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:339)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:29)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:202)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:659)
	at com.google.android.gms.internal.zzcjg.zzzq(Unknown Source)
	at com.google.android.gms.internal.zzcjg.zzjD(Unknown Source)
	at com.google.android.gms.internal.zzchj.initialize(Unknown Source)
	at com.google.android.gms.internal.zzcgl.<init>(Unknown Source)
	at com.google.android.gms.internal.zzcgl.zzbj(Unknown Source)
	at com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
	at com.example.android.App.setupFirebaseServices(App.java:124)
	at com.example.android.App.onCreate(App.java:73)
	at org.robolectric.android.internal.ParallelUniverse.lambda$setUpApplicationState$0(ParallelUniverse.java:173)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:172)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:328)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:241)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.NoClassDefFoundError: android/app/job/JobWorkItem
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodInternal(ShadowWrangler.java:249)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:215)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:149)
	at org.robolectric.internal.bytecode.RobolectricInternals.findShadowMethod(RobolectricInternals.java:39)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bindCallSite(InvokeDynamicSupport.java:120)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bootstrap(InvokeDynamicSupport.java:62)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:294)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at android.app.job.JobScheduler.<init>(JobScheduler.java)
	at android.app.JobSchedulerImpl.<init>(JobSchedulerImpl.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:339)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:29)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:202)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.$$robo$$getSystemService(ContextWrapper.java:659)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java)
	at com.google.android.gms.internal.zzcjg.zzzq(Unknown Source)
	at com.google.android.gms.internal.zzcjg.zzjD(Unknown Source)
	at com.google.android.gms.internal.zzchj.initialize(Unknown Source)
	at com.google.android.gms.internal.zzcgl.<init>(Unknown Source)
	at com.google.android.gms.internal.zzcgl.zzbj(Unknown Source)
	at com.google.firebase.analytics.FirebaseAnalytics.getInstance(Unknown Source)
	at com.example.android.App.setupFirebaseServices(App.java:124)
	at com.example.android.App.onCreate(App.java:73)
	at org.robolectric.android.internal.ParallelUniverse.lambda$setUpApplicationState$0(ParallelUniverse.java:173)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:172)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:328)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:241)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:123)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:77)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more
Caused by: java.lang.ClassNotFoundException: android.app.job.JobWorkItem
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:195)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:140)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:133)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:132)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 59 more
```
Method mentioned inside stacktrace looks like this:
```
private void setupFirebaseServices() {
        if (FirebaseApp.getApps(this).isEmpty()) {
            FirebaseApp.initializeApp(this);
        }
        mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);

        String[] topicsToSubscribe = getResources().getStringArray(R.array.topics_to_subscribe);
        for (String aTopicsToSubscribe : topicsToSubscribe) {
            FirebaseMessaging.getInstance().subscribeToTopic(aTopicsToSubscribe);
        }
    }
```

Problem occurs only for sdk grater than 23. For 23 and below everything is fine.
Well when I comment `mFirebaseAnalytics = FirebaseAnalytics.getInstance(this);` inside my `setupFirebaseServices` then for all sdks test provided above is done without failure.
Am I missing something? Please ask me questions if something is unclear or some specific info will be helpful

### Steps to Reproduce
In App onCreate use **FirebaseAnalytics.getInstance()**
Run test

### Robolectric & Android Version

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.google.firebase:firebase-plugins:1.1.5'
        classpath 'me.tatarka:gradle-retrolambda:3.6.1'
    }
```

```
compileSdkVersion 25
buildToolsVersion '26.0.2'
```

```
compile 'com.google.firebase:firebase-crash:11.0.4'
compile 'com.google.firebase:firebase-core:11.0.4'
compile 'com.google.firebase:firebase-config:11.0.4'
compile 'com.google.firebase:firebase-messaging:11.0.4'
compile 'com.google.firebase:firebase-perf:11.0.4'
compile 'com.google.android.gms:play-services-analytics:11.0.4'
```
I'm aware that this gms and firebase dependencies aren't the newest but can change it for production atm, but I've tried to upgrade it just to test if that would help and I'm affraid that's not the case.

```
testImplementation 'junit:junit:4.12'
testImplementation "org.robolectric:robolectric:3.6.1"
```

**Comment by bitfield66** [comment]
@daniellojewski have you found any solution for this?

**Comment by daniellojewski** [comment]
Unfortunately no, tests for this project were abandoned long time ago so I forgotten about it.

**Comment by utzcoz** [comment]
@daniellojewski @bitfield66 Please try the latest Robolectric 4.9. I remember Firebase Android SDK also uses Robolectric for its many modules' local tests. Feel free to reopen this issue if it still exists with latest Robolectric 4.9.
