### ISSUE TITLE
java.lang.LinkageError: loader constraint violation for Context

### ISSUE THREAD

**Issue by renukavam** [robolectric/robolectric#3738]
Using Power Mock with Robolectric gives linkage error for Context.
the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class and its superclass 
loader (instance of org/robolectric/internal/bytecode/SandboxClassLoader), 
have different Class objects for the type android/content/Context used in the signature

### Configured test class as follow
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 25)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest({static.class})
public class SampleActivityTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    SampleActivity activity;
    @Mock
    Context context;
    @Mock
    DbHelper dbHelper;

    @Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        PowerMockito.mockStatic(AdExpressDbHelper.class);
        Mockito.when(DbHelper.getInstance(context)).thenReturn(dbHelper);
        activity = Robolectric.buildActivity(SampleActivity.class).create().resume().get();
    }

while running this code getting error (Landroid/content/Context;Landroid/content/Intent;)V" 
the class loader (instance of org/powermock/core/classloader/MockClassLoader) of the current class, 
com/SampleActivity$2, and its superclass 
loader (instance of org/robolectric/internal/bytecode/SandboxClassLoader), 
have different Class objects for the type android/content/Context used in the signature

Following dependency are used :

             testCompile "org.robolectric:robolectric:3.6.1"
              testCompile 'org.robolectric:shadows-support-v4:3.0'
              testCompile "org.mockito:mockito-core:1.10.19"
               testCompile "org.powermock:powermock-module-junit4:1.6.6"
               testCompile "org.powermock:powermock-module-junit4-rule:1.6.6"
               testCompile "org.powermock:powermock-api-mockito:1.6.6"
               testCompile "org.powermock:powermock-classloading-xstream:1.6.6"

**Comment by forlayo** [comment]
I am having the same issue, my details are:

Code of test
```
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PowerMockIgnore;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.rule.PowerMockRule;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.RuntimeEnvironment;
import org.robolectric.annotation.Config;

import java.util.ArrayList;
import java.util.List;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;


@RunWith(RobolectricTestRunner.class)
@PowerMockIgnore({ "org.powermock.*", "org.mockito.*", "org.robolectric.*", "android.*", "androidx.*" })
@PrepareForTest({ScreenSaverDreamsService.class, DeviceChecker.class, Permissions.class})
public class ScreenSaverTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Test
    public void screensaver_empty_returns_error(){

        Context context = RuntimeEnvironment.systemContext; // This line produces the exception.

        ScreenSaver screenSaver = new ScreenSaver(context);
        ICmdResult callback = mock(ICmdResult.class);
        ScreenSaverCmd sampleCmd = getSampleScreenSaverCmd(context, callback, true, true);
        screenSaver.process(sampleCmd);

        verify(callback, times(1)).OnResult(false, sampleCmd);

    }
}
```

Exception I am getting
```
[Robolectric] 
<removed>.ScreenSaverTest.screensaver_empty_returns_error: sdk=22; resources=BINARY

java.lang.LinkageError: loader constraint violation: when resolving field "systemContext" the class loader (instance of org/powermock/core/classloader/javassist/JavassistMockClassLoader) of the referring class, org/robolectric/RuntimeEnvironment, and the class loader (instance of org/robolectric/internal/AndroidSandbox$SdkSandboxClassLoader) for the field's resolved type, android/content/Context, have different Class objects for that type

	at <removed>.ScreenSaverTest.screensaver_empty_returns_error(ScreenSaverTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1854)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:816)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:681)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:76)
	at org.powermock.classloading.AbstractClassloaderExecutor.invokeWithClassLoader(AbstractClassloaderExecutor.java:64)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:56)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:33)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:40)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Modules I'm using
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:2.24.5'
    testImplementation 'org.robolectric:robolectric:4.2'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.0'
    testImplementation 'org.powermock:powermock-module-junit4-rule:2.0.0'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.0'
    testImplementation 'org.powermock:powermock-classloading-xstream:2.0.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
