### ISSUE TITLE
java.lang.VerifyError when running all tests in module in Android Studio

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#3756]
### Description
A unit test fails under certain conditions:
- When only same test class is running: Passes
- When only classes in same package are running: Passes
- When all tests in module are running: Fails (see error below)

### Steps to Reproduce
My test looks like this:

```
@Config(sdk = Build.VERSION_CODES.LOLLIPOP)
@RunWith(RobolectricTestRunner.class)
public class MainActivityTest {
    private ActivityController<MainActivity> activityController;

    private Context context;

    @Before
    public void setUp() throws Exception {
        activityController = Robolectric.buildActivity(MainActivity.class);
        context = RuntimeEnvironment.application;
    }

    @Test
    public void OnRegistrationFailedIntent_AfterOnCreate_DoesNotSaveToPreferences() throws Exception {
        final MainActivity activity = activityController.create().get();
        final SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(context);
        boolean serviceEnabled = preferences.getBoolean(AmandineSharedPreferences.PREF_SERVICES_BOOLEAN_ENABLE, false);
        assumeThat(serviceEnabled, is(false));
        final BroadcastReceiver receiver = MainActivity.CallFromTestsOnly.getBroadcastReceiver(activity);
        final DialogFragment dialogFragment = new DialogFragment();
        activity.getSupportFragmentManager().beginTransaction().add(dialogFragment, ProgressBarDialog.TAG).commit();

        receiver.onReceive(context, new RegistrationFailedIntent("error", 500));

        serviceEnabled = preferences.getBoolean(AmandineSharedPreferences.PREF_SERVICES_BOOLEAN_ENABLE, false);
        assertThat(serviceEnabled, is(false));
    }
}

```

I get the following stacktrace: 

```
java.lang.VerifyError: Inconsistent stackmap frames at branch target 557
Exception Details:
  Location:
    android/view/animation/AnimationUtils.$$robo$$createInterpolatorFromXml(Landroid/content/res/Resources;Landroid/content/res/Resources$Theme;Lorg/xmlpull/v1/XmlPullParser;)Landroid/view/animation/Interpolator; @557: aload_3
  Reason:
    Type 'android/view/animation/LinearInterpolator' (current frame, locals[4]) is not assignable to 'android/view/animation/BaseInterpolator' (stack map, locals[4])
  Current Frame:
    bci: @153
    flags: { }
    locals: { 'android/content/res/Resources', 'android/content/res/Resources$Theme', 'org/xmlpull/v1/XmlPullParser', 'java/lang/Object', 'android/view/animation/LinearInterpolator', integer, integer, 'android/util/AttributeSet', 'java/lang/String' }
    stack: { }
  Stackmap Frame:
    bci: @557
    flags: { }
    locals: { 'android/content/res/Resources', 'android/content/res/Resources$Theme', 'org/xmlpull/v1/XmlPullParser', 'java/lang/Object', 'android/view/animation/BaseInterpolator', integer, integer, 'android/util/AttributeSet', 'java/lang/String' }
    stack: { }
  Bytecode:
    0x0000000: 121a b800 204e 2d11 0144 b800 2401 3a04
    0x0000010: 2d11 0148 b800 242c b900 8301 0036 062d
    0x0000020: 1101 4bb8 0024 2cb9 0086 0100 5936 0506
    0x0000030: a000 0e2c b900 8301 0015 06a4 01fc 1505
    0x0000040: 049f 01f6 2d11 014d b800 2415 0505 9f00
    0x0000050: 0d2d 1101 4eb8 0024 a7ff c72d 1101 51b8
    0x0000060: 0024 2cb8 0078 3a07 2d11 0153 b800 242c
    0x0000070: b900 8901 003a 082d 1101 55b8 0024 1908
    0x0000080: 1301 0db6 0091 9900 162d 1101 56b8 0024
    0x0000090: bb01 0f59 b701 103a 04a7 0194 2d11 0157
    0x00000a0: b800 2419 0813 0112 b600 9199 001a 2d11
    0x00000b0: 0158 b800 24bb 00f4 592a 2b19 07b7 0115
    0x00000c0: 3a04 a701 6b2d 1101 59b8 0024 1908 1301
    0x00000d0: 17b6 0091 9900 1a2d 1101 5ab8 0024 bb00
    0x00000e0: e059 2a2b 1907 b701 183a 04a7 0142 2d11
    0x00000f0: 015b b800 2419 0813 011a b600 9199 0016
    0x0000100: 2d11 015c b800 24bb 011c 59b7 011d 3a04
    0x0000110: a701 1d2d 1101 5db8 0024 1908 1301 1fb6
    0x0000120: 0091 9900 1a2d 1101 5eb8 0024 bb01 2159
    0x0000130: 2a2b 1907 b701 223a 04a7 00f4 2d11 015f
    0x0000140: b800 2419 0813 0124 b600 9199 001a 2d11
    0x0000150: 0160 b800 24bb 0126 592a 2b19 07b7 0127
    0x0000160: 3a04 a700 cb2d 1101 61b8 0024 1908 1301
    0x0000170: 29b6 0091 9900 1a2d 1101 62b8 0024 bb01
    0x0000180: 2b59 2a2b 1907 b701 2c3a 04a7 00a2 2d11
    0x0000190: 0163 b800 2419 0813 012e b600 9199 001a
    0x00001a0: 2d11 0164 b800 24bb 0130 592a 2b19 07b7
    0x00001b0: 0131 3a04 a700 792d 1101 65b8 0024 1908
    0x00001c0: 1301 33b6 0091 9900 162d 1101 66b8 0024
    0x00001d0: bb01 3559 b701 363a 04a7 0054 2d11 0167
    0x00001e0: b800 2419 0813 0138 b600 9199 001a 2d11
    0x00001f0: 0168 b800 24bb 013a 592a 2b19 07b7 013b
    0x0000200: 3a04 a700 2b2d 1101 6ab8 0024 bb00 ac59
    0x0000210: bb00 4959 b700 4c13 013d b600 522c b900
    0x0000220: 8901 00b6 0052 b600 5cb7 00af bf2d 1101
    0x0000230: 6db8 0024 a7fd eb2d 1101 6fb8 0024 1904
    0x0000240: b0                                     
  Stackmap Table:
    full_frame(@31,{Object[#11],Object[#14],Object[#127],Object[#4],Object[#321],Top,Integer},{})
    full_frame(@62,{Object[#11],Object[#14],Object[#127],Object[#4],Object[#321],Integer,Integer},{})
    same_frame(@91)
    append_frame(@156,Object[#191],Object[#141])
    same_frame(@197)
    same_frame(@238)
    same_frame(@275)
    same_frame(@316)
    same_frame(@357)
    same_frame(@398)
    same_frame(@439)
    same_frame(@476)
    same_frame(@517)
    same_frame(@557)
    chop_frame(@567,2)


	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:540)
	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
	at android.support.design.widget.BaseTransientBottomBar.animateViewOut(BaseTransientBottomBar.java:590)
	at android.support.design.widget.BaseTransientBottomBar.hideView(BaseTransientBottomBar.java:614)
	at android.support.design.widget.BaseTransientBottomBar$1.handleMessage(BaseTransientBottomBar.java:188)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at org.robolectric.shadows.ShadowMessageQueue.dispatchMessage(ShadowMessageQueue.java:164)
	at org.robolectric.shadows.ShadowMessageQueue.access$100(ShadowMessageQueue.java:30)
	at org.robolectric.shadows.ShadowMessageQueue$1.run(ShadowMessageQueue.java:138)
	at org.robolectric.util.Scheduler.runOrQueueRunnable(Scheduler.java:319)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:156)
	at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:145)
	at org.robolectric.shadows.ShadowMessageQueue.enqueueMessage(ShadowMessageQueue.java:145)
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java)
	at android.os.Handler.enqueueMessage(Handler.java:631)
	at android.os.Handler.sendMessageAtTime(Handler.java:600)
	at android.os.Handler.sendMessageDelayed(Handler.java:570)
	at android.os.Handler.sendMessage(Handler.java:507)
	at android.support.design.widget.BaseTransientBottomBar$3.dismiss(BaseTransientBottomBar.java:399)
	at android.support.design.widget.SnackbarManager.cancelSnackbarLocked(SnackbarManager.java:205)
	at android.support.design.widget.SnackbarManager.show(SnackbarManager.java:89)
	at android.support.design.widget.BaseTransientBottomBar.show(BaseTransientBottomBar.java:323)
	at com.assaabloy.stg.amandine.android.app.MainActivity$1.handle(MainActivity.java:58)
	at com.assaabloy.stg.amandine.android.app.services.ServiceRegistrationReceiver.onReceive(ServiceRegistrationReceiver.java:74)
	at com.assaabloy.stg.amandine.android.app.MainActivityTest.OnRegistrationFailedIntent_AfterOnCreate_DoesNotSaveToPreferences(MainActivityTest.java:54)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:568)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```
### Robolectric & Android Version
Android Studio 3.0.1
Robolectric 3.7 (also reproducible in 3.6.1)
Android (compileSdk/targetSdk): 27

**Comment by leesandy** [comment]
Thank you so much

Vào 13 thg 2, 2018 6:41 CH, "Alix" <notifications@github.com> đã viết:

**Comment by hoisie** [comment]
Has this issue been resolved? Can this test run under 4.4?

**Comment by MGaetan89** [comment]
@alixwar did you have a chance to test again with Robolectric 4.14.1 (the latest version as of today)? Do you still have this issue?

**Comment by alixwar** [comment]
@MGaetan89 I'm not working on the same codebase as originally reported but I can confirm that running all tests in a module using Robolectric 4.14.1 works as expected for me now
