### ISSUE TITLE
java.lang.NoSuchMethodError: org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.doNotInstrumentPackage

### ISSUE THREAD

**Issue by abhi-gadewar** [robolectric/robolectric#3795]
### Description
java.lang.NoSuchMethodError: org.robolectric.internal.bytecode.InstrumentationConfiguration$Builder.doNotInstrumentPackage(Ljava/lang/String;)Lorg/robolectric/internal/bytecode/InstrumentationConfiguration$Builder;
	at org.robolectric.internal.AndroidConfigurer.configure(AndroidConfigurer.java:94)
	at org.robolectric.RobolectricTestRunner.createClassLoaderConfig(RobolectricTestRunner.java:219)
	at org.robolectric.RobolectricTestRunner.createClassLoaderConfig(RobolectricTestRunner.java:229)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:305)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:72)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:176)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:109)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:36)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:63)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

### Robolectric & Android Version
My dependencies 

testImplmentation 'org.robolectric:robolectric:3.7.1',
testImplmentation 'org.robolectric:junit:3.7.1',
testImplmentation 'org.robolectric:robolectric-junit:3.4-rc2',
testImplmentation 'org.robolectric:shadows-support-v4:3.4-rc2',
testImplmentation 'org.robolectric:shadows-multidex:3.7.1',
testImplmentation 'org.robolectric:robolectric-utils:3.4-rc2'

**Comment by jongerrish** [comment]
You'll need to use consistent versions of all Robolectric dependencies. You
have a variety of versions there.

**Comment by abhi-gadewar** [comment]
@jongerrish  Latest version for robolectric-junit,shadows-support, robolectric-utils is 3.7.1. Refer https://mvnrepository.com/artifact/org.robolectric

**Comment by abhi-gadewar** [comment]
@jongerrish  After making versions same it worked. Thanks for help.
