### ISSUE TITLE
Shadows class appears on stacktrace

### ISSUE THREAD

**Issue by nguyentruongtho** [robolectric/robolectric#3796]
We are using robolectric 3.7.1, and getting this crash. I tried to trace the crash and it is weird that `Shadows.reset()` is called, even though there is no `Shadows` class from this version.

Any idea?

```
java.lang.NullPointerException
    at org.robolectric.shadows.ShadowLooper.resetThreadLoopers(ShadowLooper.java:62)
    at org.robolectric.Shadows.reset(Shadows.java:1758)
    at org.robolectric.RobolectricTestRunner.resetStaticState(RobolectricTestRunner.java:362)
    at org.robolectric.RobolectricTestRunner.lambda$beforeTest$0(RobolectricTestRunner.java:327)
    at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
    at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:326)
    at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:250)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at com.facebook.buck.testrunner.DelegateRunnerWithTimeout.lambda$runWithBuckManagedTimeout$0(DelegateRunnerWithTimeout.java:116)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by nguyentruongtho** [comment]
It happens randomly after upgrading to robolectric 3.7.1. We have never seen that before the upgrade.

**Comment by xian** [comment]
@brettchabot maybe related to the looper race you found?

**Comment by nguyentruongtho** [comment]
any idea on this? I don't understand why `Shadows` class appears in the stacktrace even it is not in source code anymore.

**Comment by nguyentruongtho** [comment]
apparently this is facebook buck issue, they are still using shadows-core 3.3.2

**Comment by nguyentruongtho** [comment]
above wasn't correct, `Shadows` class is actually generated during building new version of robolectric.

**Comment by jongerrish** [comment]
We've removed the call to the resetter before tests (rest will now happen
only after tests) after 3.8 coming soon. Not sure the root cause of your
issue, but it won't happen anymore (at least before the test run.

**Comment by nguyentruongtho** [comment]
nice, thanks for the headup and looking forward to the new version.

**Comment by nguyentruongtho** [comment]
Still seeing similar stacktrace in v3.8:

```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLooper.quitUnchecked(ShadowLooper.java:127)
	at org.robolectric.shadows.ShadowLooper.quit(ShadowLooper.java:115)
	at android.os.Looper.quit(Looper.java)
	at org.robolectric.shadows.ShadowLooper.resetThreadLoopers(ShadowLooper.java:57)
	at org.robolectric.Shadows.reset(Shadows.java:1798)
	at org.robolectric.RobolectricTestRunner.resetStaticState(RobolectricTestRunner.java:364)
	at org.robolectric.RobolectricTestRunner.lambda$afterTest$0(RobolectricTestRunner.java:357)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.RobolectricTestRunner.afterTest(RobolectricTestRunner.java:356)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.facebook.buck.testrunner.DelegateRunnerWithTimeout.lambda$runWithBuckManagedTimeout$0(DelegateRunnerWithTimeout.java:116)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by utzcoz** [comment]
@nguyentruongtho Please try the latest Robolectric, and feel free to reopen this issue if it still exists. Thanks.
