### ISSUE TITLE
Robolectric fails to inflate ConstraintLayout: NumberFormatException

### ISSUE THREAD

**Issue by softcrafter** [robolectric/robolectric#3825]
### Description
I have a class that extends ConstraintLayout:
```java
public class CustomView extends ConstraintLayout {
...
```
In the constructor of the CustomView I am doing this:
```java
View rootView = inflate(getContext(), R.layout.custom_view, this);
```

XML looks like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent">
...
```
### Steps to Reproduce
With the above setup I am trying to run the following code in a test class:
```java
@RunWith(RobolectricTestRunner.class)
@Config(manifest = "src/main/AndroidManifest.xml")
public class CustomViewTest {

    private CustomView mCustomView;

    @Before
    public void setUp() throws Exception {
        ActivityController<Activity> activityController = Robolectric.buildActivity(Activity.class).create();
        mCustomView = new CustomView(activityController.get());
```

Fails with the following exception:
```
java.lang.NumberFormatException: For input string: "parent"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:123)
	at android.content.res.TypedArray.getInt(TypedArray.java:254)
	at android.support.constraint.ConstraintLayout$LayoutParams.__constructor__(ConstraintLayout.java:1706)
	at android.support.constraint.ConstraintLayout$LayoutParams.<init>(ConstraintLayout.java)
	at android.support.constraint.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:1223)
	at android.support.constraint.ConstraintLayout.generateLayoutParams(ConstraintLayout.java:383)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at android.view.View.inflate(View.java:16119)
```
The stack trace is pointing to the line from the constructor:
```java
View rootView = inflate(getContext(), R.layout.custom_view, this);
```
### Robolectric & Android Version
```
    testCompile 'org.robolectric:robolectric:3.7.1'
    buildToolsVersion '25.0.2'
    compileSdkVersion 25
    minSdkVersion 17
    targetSdkVersion 25
```
I am using ```Activity.class``` because I am developing a library with a custom view and I want to test it without having to add activities just for testing.
Am I doing something wrong ?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

You also no longer need to specify @Config(constants = ..., manifest = ...)

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
