### ISSUE TITLE
NullPointerException after upgrading to gradle 4.1

### ISSUE THREAD

**Issue by bigmouth** [robolectric/robolectric#3826]
All robolectric tests in my project are failing with NPE after upgrading gradle to version 4.1

I wrote a minimal test to reproduce the issue:
    
    @Config(constants = BuildConfig.class)

    @RunWith(RobolectricTestRunner.class)

    public class WelcomeActivityTest {
        private WelcomeActivity activity;

        @Before
        public void setup() {
            activity = Robolectric.setupActivity(WelcomeActivity.class);
        }

        @Test
        public void test() {
            
        }
    }

Robolectric version is 3.7.1

Everything was working fine with gradle 3.3 and android studio gradle plugin 2.3.1

The error message is 

    java.lang.NullPointerException
	at org.robolectric.res.ThemeStyleSet$OverlayedStyle.equals(ThemeStyleSet.java:67)
	at org.robolectric.res.ThemeStyleSet.apply(ThemeStyleSet.java:29)
	at org.robolectric.shadows.ShadowAssetManager.applyThemeStyle(ShadowAssetManager.java:729)
	at android.content.res.AssetManager.applyThemeStyle(AssetManager.java)
	at android.content.res.ResourcesImpl$ThemeImpl.applyStyle(ResourcesImpl.java:1258)
	at android.content.res.Resources$Theme.applyStyle(Resources.java:1405)
	at android.view.ContextThemeWrapper.onApplyThemeResource(ContextThemeWrapper.java:186)
	at android.app.Activity.onApplyThemeResource(Activity.java:4277)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:198)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:140)
	at android.app.Activity.setTheme(Activity.java:4269)
	at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:90)
	at org.robolectric.shadows.ShadowActivity.callAttach(ShadowActivity.java:216)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:41)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:25)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:84)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:80)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:88)
    ...

**Comment by npike** [comment]
Seeing the same thing - any luck?

**Comment by jongerrish** [comment]
For Robolectric tests you shouldn't need returnDefaultValues, that's only when using mockable jar.

The problem for @bigmouth is that he/she is configuring for AGP2.3 (Using constants = BuildConfig.class) this is deprecated and we strongly recommend upgrading to AGP3.0+ because we have proper resource integration there, instructions here: http://robolectric.org/getting-started/

The problem pre AGP3.0 was that Robolectric needed special code to try and find the merged resource directory and the problem for us was that was always changing between releases (its not public API). If you really can't upgrade from AGP2.3 for whatever reason, I would suggest putting a breakpoint in GradleManifestFactory and trying to find where the merged resources are now output and then modifying that class. We'll happily take pull requests to update it, but we're not actively supporting it anymore.
