### ISSUE TITLE
Running tests on other thread does not properly switch Main Looper to new thread

### ISSUE THREAD

**Issue by matejdro** [robolectric/robolectric#3829]
### Description

When Robolectric test is run on another thread (for example due to JUnit's timeout feature), `Looper.getMainLooper()` will stay on current thread. This causes issues with libraries that check and throw exception if any code is run on non-main thread (for example `LiveData.setValue()` from android architecture components breaks).

### Steps to Reproduce

Run this test, it fails:

```java
@RunWith(RobolectricTestRunner::class)
class LooperTest {
    @Test(timeout = 100L)
    fun mainLooperMatchesTimeout() {
        assertSame(Thread.currentThread(), Looper.getMainLooper().thread)
    }
}
```

### Robolectric & Android Version

Robolectric 3.8

**Comment by Pavneet-Sing** [comment]
Have you tried InstantTaskExecutorRule ?

@Rule
public TestRule rule = new InstantTaskExecutorRule();

**Comment by matejdro** [comment]
This does not have anything to do with architecture components.

**Comment by Pavneet-Sing** [comment]
Yeah, that's the blocker, robolectric suppose to mimic everything but I have seen some failures with live data and room execution issues due to threads. Would have to see more improvement in framework.

**Comment by ganadist** [comment]
Android Looper on Robolectric is initialized on Sandbox thread.
https://github.com/robolectric/robolectric/blob/robolectric-4.4/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L226-L233

But method runner thread is created while evaluate it if there is timeout annotation.
https://github.com/robolectric/robolectric/blob/robolectric-4.4/junit/src/main/java/org/robolectric/internal/SandboxTestRunner.java#L263
https://github.com/junit-team/junit4/blob/main/src/main/java/org/junit/runners/BlockJUnit4ClassRunner.java#L316-L322
https://github.com/junit-team/junit4/blob/main/src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java#L124-L128

**Comment by ganadist** [comment]
It seems it is a feature(?).
https://github.com/robolectric/robolectric/pull/4559/files#diff-cc1e70e6e497648b6b2f23210b085080e50c1d60e1005f5b87315bd14885629aR317-R320

**Comment by mcumings** [comment]
When combined with Kotlin coroutines, this issue causes deadlock when test code directly or indirectly attempts to use `Dispatchers.Main`, as the main thread is blocked (not suspended) in `FailOnTimeout.getResult`.

**Comment by kschults** [comment]
As a workaround, you can inject your dispatcher instead of directly using `Dispatchers.Main`. In your test, inject an instance of `TestCoroutineDispatcher` instead.

**Comment by Diarrhio** [comment]
This issue bit us hard and took me a number of days to sort through, particularly in the situation of Kotlin coroutines and using `Dispatchers.Main`. The solution was to use @kschults suggestion and create a dispatcher in the unit tests and set that to be the dispatcher to use in the main code base being tested.

In unit tests:
```
// Create dispatcher. In our case we needed a single threaded dispatcher and couldn't use `TestCoroutineDispatcher` as suggested above
  val mainDispatcher = Executors.newFixedThreadPool(1) { runnable ->
    Thread(runnable).apply {
      name = "UnitTestingUIThread"
    }
  }.asCoroutineDispatcher()
```

That `mainDispatcher` then get injected/passed into the main code base to be used instead of `Dispatchers.Main` everywhere that we were. e.g.:

```
// This
launch(injectedMainDispatcher) {}

// instead of this
launch(Dispatchers.Main) {}
```

**Comment by fknives** [comment]
👋  I run into a similar issue today, I might be just using something wrong, any kind of response is appreciated and sorry if it's not related in the end.

is `org.junit.rules.Timeout` incompatibile with Robolectric  and should only @Test(timeout=500) be used? and that is expected?

I try to use Timeout cause I share tests between androidTest and Robolectric tests and it worked there.

As I understand according to the file linked by  @ganadist this shouldn't happen ([comment](https://github.com/robolectric/robolectric/issues/3829#issuecomment-758350361)):
```java
/**
 * For tests with a timeout, we need to wrap the test method execution (but not befores or
 * afters) in a {@link TimeLimitedStatement}. We can't use JUnit's built-in
 * {@link FailOnTimeout} statement because it causes the test to be run on a new thread, but
 * tests should be run on the sandbox's main thread in all cases.
 */
```
 
The important parts from my test look like this:
```kotlin
@RunWith(AndroidJUnit4::class)
class CrashBecauseOfTimeOut {

    @JvmField
    @Rule
    val globalTimeout: Timeout = Timeout.seconds(60)

    @Before
    fun setup() {
        Intents.init()
    }

    @After
    fun tearDown() {
        Intents.release()
    }

    @Test
    fun example() { // irrelevant what's inside
    }
}
```

This test crashes with:
```
main looper can only be controlled from main thread
java.lang.UnsupportedOperationException: main looper can only be controlled from main thread
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:370)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:92)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.runOnMainSync(RoboMonitoringInstrumentation.java:125)
	at androidx.test.espresso.intent.Intents.internalRelease(Intents.java:336)
	at androidx.test.espresso.intent.Intents.release(Intents.java:142)
	at org.fnives.android.timeout.issue.report.CrashBecauseOfTimeOut.tearDown(CrashBecauseOfTimeOut.kt:26)
```

Created a small repository to be able to reproduce: https://github.com/fknives/robolectric-issue-sample--3829

**Comment by hoisie** [comment]
I vaguely recall that `@Timeout` spawns a new thread that runs the test method. In essence it changes a test method to run in a background thread. This is not compatible with Robolectric's scheduler, which requires idling the main looper to be performed from the test thread that is set up in Robolectric.

I unfortunately do not know any workarounds other than constructing a custom timeout rule that does the waiting on a separate thread and interrupts the main/test thread if it times out.

**Comment by hoisie** [comment]
Looks like this is how Robolectric implements timeouts (I think with `@Test(timeout = ...)`)

https://github.com/robolectric/robolectric/blob/master/junit/src/main/java/org/robolectric/internal/TimeLimitedStatement.java

You may be able to extract that logic into a rule?

**Comment by fknives** [comment]
@hoisie Thanks you @hoisie for the fast response. That explanation makes sense, will try with a Custom Rule, thank you. 👍

**Comment by fknives** [comment]
Looks like I was able to convert that snippet into a TestRule and it seems to be working in the sample project and also in my original project. Thank you again. The file: [SharedTimeOut.kt](https://github.com/fknives/robolectric-issue-sample--3829/blob/develop/app/src/sharedTest/java/org/fnives/android/timout/issue/report/fix/SharedTimeOut.kt)

**Comment by fknives** [comment]
If you think it is worth to do, I'm happy too. I will have time  probably during the weekend.
