### ISSUE TITLE
Long test method names cause "SQLiteCantOpenDatabaseException Cannot open SQLite connection"

### ISSUE THREAD

**Issue by jakob-grabner** [robolectric/robolectric#3838]
### Description
Long method names (around 120 characters) cause a `android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open SQLite connection`. 
After some debugging, I found out that the method name of the current test is part of the path to the temporary database file. In my case :
`C:\Users\USERNAE\AppData\Local\Temp\robolectric-Method_some_very_very_very_very_very_very_very_very_very_long_method_name7090764217589220180\com.example-dataDir\databases\db_name`

I guess robolectric runs into some path length limitations on windows.

### Steps to Reproduce
- Use a windows machine
- Create robolectric test that opens a db file
- Use a very long method name (around 120 characters) for the test method

### Robolectric & Android Version
- org.robolectric:robolectric:3.8
- Android sdk 26

### Full stacktrace

    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open SQLite connection

        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getSqliteException(ShadowSQLiteConnection.java:746)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:730)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:719)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.open(ShadowSQLiteConnection.java:390)
        at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:71)
        at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:723)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:299)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at com.runtastic.android.common.contentProvider.BaseContentProvider.delete(BaseContentProvider.java:144)
        at org.robolectric.shadows.ShadowContentResolver.delete(ShadowContentResolver.java:369)
        at android.content.ContentResolver.delete(ContentResolver.java)
        at com.example.utils.DatabaseUtilsKt.clearDatabase(DatabaseUtils.kt:18)
        at com.example.test.DatabaseIntegrationTest.baseDataBaseSetUp(DatabaseIntegrationTest.kt:34)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at com.runtastic.android.testutil.rules.Rx2SchedulersOverrideRule$apply$1.evaluate(Rx2SchedulersOverrideRule.kt:27)
        at com.runtastic.android.testutil.rules.RxSchedulersOverrideRule$apply$1.evaluate(RxSchedulersOverrideRule.kt:26)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
        at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
        at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:83)
        at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:74)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:65)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:142)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:725)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:719)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections.open(ShadowSQLiteConnection.java:390)
        at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:71)
        at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.$$robo$$open(SQLiteConnection.java:209)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.$$robo$$open(SQLiteConnection.java:193)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$openInner(SQLiteDatabase.java:808)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$open(SQLiteDatabase.java:793)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$openDatabase(SQLiteDatabase.java:696)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
        at android.app.ContextImpl.$$robo$$openOrCreateDatabase(ContextImpl.java:723)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java)
        at android.content.ContextWrapper.$$robo$$openOrCreateDatabase(ContextWrapper.java:299)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java)
        at android.database.sqlite.SQLiteOpenHelper.$$robo$$getDatabaseLocked(SQLiteOpenHelper.java:254)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
        at android.database.sqlite.SQLiteOpenHelper.$$robo$$getWritableDatabase(SQLiteOpenHelper.java:194)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java)
        at com.example.contentProvider.BaseContentProvider.delete(BaseContentProvider.java:144)
        at org.robolectric.shadows.ShadowContentResolver.delete(ShadowContentResolver.java:369)
        at android.content.ContentResolver.delete(ContentResolver.java)
        at com.example.utils.DatabaseUtilsKt.clearDatabase(DatabaseUtils.kt:18)
        at com.example.test.DatabaseIntegrationTest.baseDataBaseSetUp(DatabaseIntegrationTest.kt:34)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        ... 41 more
    Caused by: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
        at com.almworks.sqlite4java.SQLiteConnection.open0(SQLiteConnection.java:1353)
        at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:258)
        at com.almworks.sqlite4java.SQLiteConnection.open(SQLiteConnection.java:269)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections$1.call(ShadowSQLiteConnection.java:397)
        at org.robolectric.shadows.ShadowSQLiteConnection$Connections$1.call(ShadowSQLiteConnection.java:390)
        at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
        at java.util.concurrent.FutureTask.run(FutureTask.java)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ionutbarau** [comment]
Any workaround for this issue?

**Comment by ionutbarau** [comment]
I have managed to solve it by extending the Application class for tests and overriding the getDataDir() and getDatabasePath() methods. I have created a folder inside src/test/res for robolectric to use when running tests. Because the method names are big and Roblectric is creating a test folder in temp directory, the path is to big. With this fix you should be able to keep the method names as you like

**Comment by utzcoz** [comment]
@ionutbarau @jakob-grabner What about trying Robolectric's native mode for SQLite. The legacy mode with sqlite4java has been deprecated.
