### ISSUE TITLE
NoSuchMethodError when using latest shadows-support-v4 package

### ISSUE THREAD

**Issue by JPDMetaswitch** [robolectric/robolectric#3844]
### Description
When using shadows-support-v4 latest (3.4-rc2) with robolectric v3.8.0, I hit:

```
java.lang.NoSuchMethodError: org.robolectric.Robolectric.getShadowsAdapter()Lorg/robolectric/ShadowsAdapter;

at org.robolectric.shadows.support.v4.SupportFragmentController.<init>(SupportFragmentController.java:28)
at org.robolectric.shadows.support.v4.SupportFragmentController.<init> SupportFragmentController.java:24)
at org.robolectric.shadows.support.v4.SupportFragmentController.of(SupportFragmentController.java:38)
```

This is caused by the following line:
`    super(Robolectric.getShadowsAdapter(), fragment, intent);`

In the repository this has been fixed to say:
`    super(fragment, intent);`

But this has not made it into a release. Would it be possible to get a new release of the shadows-support-v4 package to fix this issue?

### Steps to Reproduce
Call SupportFragmentController.of(Fragment) on any fragment, while using latest robolectric and shadows-support-v4 packages.

### Robolectric & Android Version
robolectric 3.8.0
shadows-support-v4 3.4-rc2

### Link to a public git repo demonstrating the problem:
-

**Comment by JPDMetaswitch** [comment]
Thanks. This has fixed the issue.
