### ISSUE TITLE
android.content.res.Resources$NotFoundException: null

### ISSUE THREAD

**Issue by 17050097616** [robolectric/robolectric#3851]
Drawable com.echase.cashier:drawable/abc_vector_test with resource ID #0x7f080058
android.content.res.Resources$NotFoundException: null
Caused by: android.content.res.Resources$NotFoundException: File E:\workSpace\Cashier\app\build\intermediates\merged-not-compiled-resources\debug\drawable\abc_vector_test.xml from drawable resource ID #0x7f080058

	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:726)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:59)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:57)
	at org.robolectric.shadows.ShadowResourcesImpl.loadDrawable(ShadowResourcesImpl.java:218)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
	at android.content.res.Resources.getDrawable(Resources.java:771)
	at android.content.Context.getDrawable(Context.java:525)
	at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:131)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java)
	at android.support.v7.app.AppCompatDelegateImplN.<init>(AppCompatDelegateImplN.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
	at com.echase.cashier.base.BaseActivity.onCreate(BaseActivity.java:50)
	at com.echase.cashier.ui.activity.FlowWaterActivity.onCreate(FlowWaterActivity.java:74)
	at android.app.Activity.performCreate(Activity.java:6679)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:232)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:73)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:366)
	at org.robolectric.shadows.CoreShadowsAdapter$1.runPaused(CoreShadowsAdapter.java:27)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:70)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:80)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:172)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:102)
	at com.echase.cashier.FlowWaterActivityTest.testPrint(FlowWaterActivityTest.java:30)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:497)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:228)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:110)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:64)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.xmlpull.v1.XmlPullParserException: XML file E:\workSpace\Cashier\app\build\intermediates\merged-not-compiled-resources\debug\drawable\abc_vector_test.xml line #-1 (sorry, not yet implemented)<vector> tag requires viewportWidth > 0
	at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:637)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:595)
	at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1224)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1197)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
	... 58 more

Disconnected from the target VM, address: '127.0.0.1:56381', transport: 'socket'

Process finished with exit code -1

as3.0.1 gradle4.4

root  build.gradle:

classpath 'com.android.tools.build:gradle:3.1.0'
ext {
    compileSdkVersion = 25
    buildToolsVersion = '27.0.3'
    minSdkVersion = 16
    targetSdkVersion = compileSdkVersion

}

app build.gradle:

testOptions {
        unitTests {
            includeAndroidResources = true
        }
}

dependencies:
testImplementation "org.robolectric:robolectric:3.8"

javaCode:

@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class FlowWaterActivityTest {

    @Test
    public void test() throws Exception {
        FlowWaterDetailFragment fragment = new FlowWaterDetailFragment();
        FlowWaterActivity activity = Robolectric.setupActivity(FlowWaterActivity.class);
	}
}

**Comment by Pietervdv** [comment]
Same issue for me. #3872

**Comment by hemannkim** [comment]
Anyone solved this PROBLEM?

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
