### ISSUE TITLE
Getting Resource NotFound error after upgrading to 3.8

### ISSUE THREAD

**Issue by repl-krishna-g** [robolectric/robolectric#3857]
### Description
Getting 
android.content.res.Resources$NotFoundException: String resource ID #0x7f0e047e

	at android.content.res.Resources.getText(Resources.java:274)
	at android.content.res.Resources.getString(Resources.java:360)
	at android.content.res.Resources.getString(Resources.java:388)
	at android.content.Context.getString(Context.java:389)

Test used to work perfectly fine in robolectric 3.5.1

**Comment by charlag** [comment]
Same here.
The problem seems to be in `TypedResource#isRefernce()`. It thinks that all strings which start with @ are links (`return !s.isEmpty() && s.charAt(0) == '@';`). We have it escaped like

`<string name="status_username_format">\@%s</string>`

but it seems to ignore this.

Thanks for your work!
