### ISSUE TITLE
<vector> tag requires viewportWidth > 0

### ISSUE THREAD

**Issue by Pietervdv** [robolectric/robolectric#3872]
### Description
After upgrade from SDK 24 to 27 tests fail with <vector> tag requires viewportWidth > 0 on app/build/intermediates/merged-not-compiled-resources/debug/drawable/abc_vector_test.xml

### Steps to Reproduce
Run simple smoke test using: Robolectric.buildActivity(mActivityClass)
                .create().start().postCreate(null).resume().postResume().visible()
                .pause().stop().destroy();

### Robolectric & Android Version
Robo= 3.8
AS = 3.0.1
compileSdkVersion = 27
buildToolsVersion = '27.0.3'
support libs = 27.1.1

### Stacktrace
```
android.content.res.Resources$NotFoundException: File /app/build/intermediates/merged-not-compiled-resources/debug/drawable/abc_vector_test.xml from drawable resource ID #0x7f080058

	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2640)
	at android.content.res.Resources.loadDrawable(Resources.java:2540)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:59)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:56)
	at org.robolectric.shadows.ShadowResources.loadDrawable(ShadowResources.java:268)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.Resources.getDrawable(Resources.java:806)
	at android.content.Context.getDrawable(Context.java:458)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:358)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:186)
	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:85)
	at android.support.v7.app.AppCompatDelegateImplBase.__constructor__(AppCompatDelegateImplBase.java:128)
	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java)
	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java)
	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:200)
	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:183)
	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:70)
	at com.example.view.BaseActivity.onCreate(BaseActivity.java:46)
	at com.example.view.authentication.AuthenticationActivity.onCreate(AuthenticationActivity.java:25)
	at android.app.Activity.performCreate(Activity.java:6251)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at com.example.core.BaseActivityTest.lifecycleSmokeTest(BaseActivityTest.java:27)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.xmlpull.v1.XmlPullParserException: XML file /app/build/intermediates/merged-not-compiled-resources/debug/drawable/abc_vector_test.xml line #-1 (sorry, not yet implemented)<vector> tag requires viewportWidth > 0
	at android.graphics.drawable.VectorDrawable.updateStateFromTypedArray(VectorDrawable.java:606)
	at android.graphics.drawable.VectorDrawable.inflate(VectorDrawable.java:567)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)
	... 60 more
```

**Comment by Narayane** [comment]
@Pietervdv Same problem for me...

This [workaround](https://github.com/robolectric/robolectric/issues/2315#issuecomment-356634933) moves the problem to ```android.view.InflateException: XML file pathtomyappbarlayout.xml line #-1 (sorry, not yet implemented): Error inflating class android.support.design.widget.AppBarLayout```

Someone here?

**Comment by Pietervdv** [comment]
@Narayane I eventually upgraded to Roblectric 4.0 alpha builds which let me build and run tests again.
I gave up on this issue once that started working.

**Comment by jongerrish** [comment]
Good idea.

If you use the new binary resource support then resource handling is much
much closer to the Android platform behaviour. We're going to remove raw
resource support in 4.1 -4.2 time frame
