### ISSUE TITLE
Null pointer exception in Broadcast receiver that declare in Manifest

### ISSUE THREAD

**Issue by ChauNTM** [robolectric/robolectric#3908]
Description:
My application uses Dagger2 and I got an error when I run a test with robolectric (I declared LocaleChangedReceiver in Manifest as broadcast receiver):
java.lang.NullPointerException
	at com.portfolio.platform.receiver.LocaleChangedReceiver.<init>(LocaleChangedReceiver.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:342)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:21)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:35)
	at org.robolectric.android.internal.ParallelUniverse.registerBroadcastReceivers(ParallelUniverse.java:388)
	at org.robolectric.android.internal.ParallelUniverse.createApplication(ParallelUniverse.java:258)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:168)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

My code is below:
```@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk = 21, application = TestPortfolioApp.class)
@PrepareForTest({TokenAuthenticator.class, TestPortfolioApp.class, ProviderManager.class, PortfolioApp.class})
@PowerMockIgnore({"okhttp3.*"})
public class TokenAuthenticatorTest {

    @Mock
    TestPortfolioApp mApplication;

    @Mock
    ApplicationComponent mApplicationComponent;

@Before
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        mApplicationComponent = Mockito.mock(ApplicationComponent.class);
        mApplication = (TestPortfolioApp) RuntimeEnvironment.application;
        Mockito.when(mApplication.getApplicationComponent()).thenReturn(mApplicationComponent);
    }
}```

```public class TestPortfolioApp extends PortfolioApp {

    ApplicationComponent mApplicationComponent;
    private static TestPortfolioApp instance;

    @Override public void onCreate() {
        super.onCreate();
        instance = this;
        mApplicationComponent = DaggerApplicationComponent.builder()
                .applicationModule(new ApplicationModule(this))
                .build();
        mApplicationComponent.inject(this);
    }

    public static TestPortfolioApp getInstance() {
        return instance;
    }

    @Override
    public ApplicationComponent getApplicationComponent() {
        return mApplicationComponent;
    }
}```
And I init dagger in LocaleChangedReceiver as below:
```public class LocaleChangedReceiver extends BroadcastReceiver {
    private static final String TAG = LocaleChangedReceiver.class.getSimpleName();

    @Inject
    WidgetRepository mWidgetRepository;

    @Inject
    ExploreRepository mExplorationRepository;

    @Inject
    MicroAppGalleryRepository mMicroAppGalleryRepository;


    public LocaleChangedReceiver() {
        PortfolioApp.getInstance().getApplicationComponent().inject(this);
    }
}```
I'm using robolectric 3.8 with junit 4.12, and my target android sdk version is 27.

**Comment by DataGraham** [comment]
The cause is that broadcast receivers are registered here: https://github.com/robolectric/robolectric/blob/2e5a05d3cfe313dd602bbfcfca721a06fccec076/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java#L259

But Application.onCreate() is not called until later: https://github.com/robolectric/robolectric/blob/2e5a05d3cfe313dd602bbfcfca721a06fccec076/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java#L270

These need to be done in the opposite order.

**Comment by utzcoz** [comment]
Looks like this issue still exists because current Robolectric still uses this order to initialize receivers and application. @DataGraham could you help to send a PR for it?

**Comment by carstenhag** [comment]
Stumbled across this issue while trying to update the Emarsys SDK: https://github.com/emartech/android-emarsys-sdk/commit/5b27a08b525314e8834c407369f22b7df499ca48
