### ISSUE TITLE
java.lang.ClassNotFoundException: com.android.internal.graphics.drawable.AnimationScaleListDrawable

### ISSUE THREAD

**Issue by fargus9** [robolectric/robolectric#3939]
### Description

A progress bar is failing to inflate, it looks like because an internal class can't be found.

`Caused by: android.view.InflateException: XML file <path>/build/intermediates/merged-not-compiled-resources/debug/layout/<layout>.xml line #-1 (sorry, not yet implemented): Error inflating class android.widget.ProgressBar
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at com.android.internal.policy.PhoneLayoutInflater.$$robo$$onCreateView(PhoneLayoutInflater.java:58)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v7.app.AppCompatDelegateImplV9.$$robo$$setContentView(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatActivity.$$robo$$setContentView(AppCompatActivity.java:139)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at <Activity>.onCreate(<snip>)
	at android.app.Activity.$$robo$$performCreate(Activity.java:6975)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at com.crowdcompass.util.CameraHandlerTest.testOpenCamera(CameraHandlerTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: android.content.res.Resources$NotFoundException: null
Caused by: android.content.res.Resources$NotFoundException: File jar:file: <path>/.m2/repository/org/robolectric/android-all/8.0.0_r4-robolectric-r1/android-all-8.0.0_r4-robolectric-r1.jar!/raw-res/res/drawable/progress_medium_material.xml from drawable resource ID #0x108091c
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:769)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:600)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:59)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:56)
	at org.robolectric.shadows.ShadowResourcesImpl.loadDrawable(ShadowResourcesImpl.java:189)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
	at android.content.res.Resources.loadDrawable(Resources.java:885)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:953)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
	at android.widget.ProgressBar.__constructor__(ProgressBar.java:281)
	at android.widget.ProgressBar.<init>(ProgressBar.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
	at <Activity>.onCreate(<snip>)
	at android.app.Activity.performCreate(Activity.java:6975)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at com.crowdcompass.util.CameraHandlerTest.testOpenCamera(CameraHandlerTest.java:58)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: android.view.InflateException: Class not found com.android.internal.graphics.drawable.AnimationScaleListDrawable
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:220)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:139)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1295)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1254)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:758)
	... 58 more
Caused by: java.lang.ClassNotFoundException: com.android.internal.graphics.drawable.AnimationScaleListDrawable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at android.graphics.drawable.DrawableInflater.$$robo$$inflateFromClass(DrawableInflater.java:201)
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java)
	at android.graphics.drawable.DrawableInflater.$$robo$$inflateFromXmlForDensity(DrawableInflater.java:139)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java)
	at android.graphics.drawable.Drawable.$$robo$$createFromXmlInnerForDensity(Drawable.java:1295)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java)
	at android.graphics.drawable.Drawable.$$robo$$createFromXmlForDensity(Drawable.java:1254)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java)
	at android.content.res.ResourcesImpl.$$robo$$loadDrawableForCookie(ResourcesImpl.java:758)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
	at android.content.res.ResourcesImpl.$$robo$$loadDrawable(ResourcesImpl.java:600)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:59)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:56)
	at org.robolectric.shadows.ShadowResourcesImpl.loadDrawable(ShadowResourcesImpl.java:189)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
	at android.content.res.Resources.$$robo$$loadDrawable(Resources.java:885)
	at android.content.res.Resources.loadDrawable(Resources.java)
	at android.content.res.TypedArray.$$robo$$getDrawableForDensity(TypedArray.java:953)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java)
	at android.content.res.TypedArray.$$robo$$getDrawable(TypedArray.java:928)
	at android.content.res.TypedArray.getDrawable(TypedArray.java)
	at android.widget.ProgressBar.$$robo$$__constructor__(ProgressBar.java:281)
	at android.widget.ProgressBar.<init>(ProgressBar.java)
	at android.widget.ProgressBar.<init>(ProgressBar.java)
	at android.widget.ProgressBar.<init>(ProgressBar.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at com.android.internal.policy.PhoneLayoutInflater.$$robo$$onCreateView(PhoneLayoutInflater.java:58)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.support.v7.app.AppCompatDelegateImplV9.$$robo$$setContentView(AppCompatDelegateImplV9.java:287)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java)
	at android.support.v7.app.AppCompatActivity.$$robo$$setContentView(AppCompatActivity.java:139)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at <Activity>.onCreate(<snip>)
	at android.app.Activity.$$robo$$performCreate(Activity.java:6975)
	at android.app.Activity.performCreate(Activity.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:62)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:359)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:59)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:69)
	at com.crowdcompass.util.CameraHandlerTest.testOpenCamera(CameraHandlerTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 1 more

Process finished with exit code 255
`

### Steps to Reproduce

Try to start a visible activity referencing the layout with a progress bar.

### Robolectric & Android Version

Robolectric 3.8
Android compile/target 26

### Link to a public git repo demonstrating the problem:

N/A though I can make something if needs be.

**Comment by AtlasRider** [comment]
I am also having this issue

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
