### ISSUE TITLE
Not able to perform the Realm unit test

### ISSUE THREAD

**Issue by asbadve** [robolectric/robolectric#3943]
### Description
Not able to run a unit test for realm database

stack trace

        java.lang.UnsatisfiedLinkError: Can't load library: /tmp/robolectric-
       Method_shouldBeAbleToGetDefaultInstance6619303088695095726/com.ajinkyabadve.mywatchlist-
       dataDir/app_lib/librealm-jni.so.5.1.0

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1827)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.getkeepsafe.relinker.SystemLibraryLoader.loadPath(SystemLibraryLoader.java:29)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:198)
	at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
	at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
	at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:60)
	at io.realm.Realm.init(Realm.java:258)
	at com.ajinkyabadve.mywatchlist.MyWatchListApp.onCreate(MyWatchListApp.java:68)
	at org.robolectric.android.internal.ParallelUniverse.lambda$setUpApplicationState$0(ParallelUniverse.java:208)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:207)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

I am using 

.
    testImplementation 'org.robolectric:robolectric:3.8'
    testImplementation 'org.robolectric:shadows-support-v4:3.0'
    testImplementation "com.android.support.test:rules:1.0.2"

    testImplementation 'org.powermock:powermock-api-mockito2:1.7.0RC2'
    testImplementation 'org.powermock:powermock-module-junit4:1.7.0'
    testImplementation 'org.powermock:powermock-core:1.7.0'
    testImplementation 'org.powermock:powermock-module-junit4-rule:1.7.0'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-inline:2.8.9'

    Android studio 3.1.2

**Comment by herrbert74** [comment]
I'm happy to report that realm-kotlin started to work with Robolectric as of 1.10.0-SNAPSHOT.
I reported it through their ticketing system, and the latests snapshot started to work with my in-memory Realm tests.
Not sure what exactly the fix was, as no ticket is associated with it on Github. It will be released probably in a few days or weeks, if you do not want to use the snapshot version. They also promised to update documentation on it. Maybe they meant this ticket:
https://github.com/realm/realm-kotlin/issues/949
Also the change log:
https://github.com/realm/realm-kotlin/blob/main/CHANGELOG.md

**Comment by herrbert74** [comment]
I realise this ticket is about mocking Realm, which should not involve Robolectric, is it? I have no problem mocking realm-kotlin with MockK, so this should probably be closed.

**Comment by utzcoz** [comment]
Duplicated to https://github.com/robolectric/robolectric/issues/1389.

**Comment by utzcoz** [comment]
> I realise this ticket is about mocking Realm, which should not involve Robolectric, is it? I have no problem mocking realm-kotlin with MockK, so this should probably be closed.

IMO, the best approach to support Realm is to support the low-level APIs of Realm using. Anyway, shadowing/mocking Realm high-level APIs with other tools is also a great method. IIRC, Realm doesn't use SQLite as the backend for database operations, and it's not easy to fake Realm's internal implementation from Robolectric part.

**Comment by herrbert74** [comment]
Just to be clear, this is not a duplication of #1389. We need both. We need to mock Realm for unit tests, which should not need Robolectric. We need support for Realm-Robolectric support for integration tests, which is now provided by Realm, at least for realm-kotlin, so #1389 can be closed.

**Comment by utzcoz** [comment]
@herrbert74 If realm-kotlin can be used to run tests with Robolectric + Realm, and it can be a solution for this issue. And IMO, https://github.com/robolectric/robolectric/issues/1389 is a more common issue to track Realm's supporting in Robolectric environment including mock and possible fake.
