### ISSUE TITLE
Resources$NotFoundException on Android Navigation setGraph

### ISSUE THREAD

**Issue by jocmp** [robolectric/robolectric#3953]
### Description
My robolectric test throws a Resources$NotFoundExecption on the new Androidx [Navigation Library](https://developer.android.com/topic/libraries/architecture/adding-components). The navigation XML is present and working on device, and I have `unitTests.includeAndroidResources = true` in my app's build.gradle. Note that other tests can discover string resources.

### Steps to Reproduce
Call [NavDeepLinkBuilder](https://developer.android.com/reference/kotlin/androidx/navigation/NavDeepLinkBuilder) with a navigation graph in `src/main/res/navigation/my_navigation.xml`
```
val context = RuntimeEnvironment.application.applicationContext
NavDeepLinkBuilder(context)
            .setDestination(R.id.exitScreen)
            .setComponentName(MyActivity::class.java)
            .setGraph(R.navigation.my_navigation)
            .createPendingIntent()
```

Stack trace
```
android.content.res.Resources$NotFoundException: com.mywebsite:navigation/my_navigation
	at org.robolectric.shadows.ShadowAssetManager.loadXmlResourceParser(ShadowAssetManager.java:493)
	at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:213)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java)
	at android.content.res.Resources.getXml(Resources.java:1192)
	at androidx.navigation.NavInflater.inflate(NavInflater.java:109)
	at androidx.navigation.NavDeepLinkBuilder.setGraph(NavDeepLinkBuilder.java:125)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

### Robolectric & Android Version
Robolectric 3.8 and Robolectric 4.0-alpha-3
Android compileSdkVersion 28, Robolectric Config sdk=27

**Comment by DDihanov** [comment]
+1

**Comment by fbattet** [comment]
I have a similar problem.
My robolectric test throws a android.view.InflateException on the new Android Navigation Component. 
I think robolectric doesn't recognise the "app:navGraph" attribute in the fragment layout.

### Layout
 ```
<?xml version="1.0" encoding="utf-8"?>

<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/fragmentContainer"
    android:name="androidx.navigation.fragment.NavHostFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:defaultNavHost="true"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    app:navGraph="@navigation/navigation_graph"
    tools:showIn="@layout/app_bar_drawer" />
```

### Test
```
@RunWith(RobolectricTestRunner::class)
class TypeTriFragmentTest {

    @Test
    fun name() {
        val fragment = TypeTriFragment()
        setupFragment(fragment, DrawerActivity::class.java)
    }
}
```

### Stack trace
```
 [Robolectric] ...TypeTriFragmentTest.name: sdk=28; resources=legacy

android.view.InflateException: XML file C:\...\Retrofit\app\build\intermediates\merged-not-compiled-resources\debug\layout\activity_drawer.xml line #-1 (sorry, not yet implemented): XML file C:\...\Retrofit\app\build\intermediates\merged-not-compiled-resources\debug\layout\content_drawer.xml line #-1 (sorry, not yet implemented): Error inflating class fragment

Caused by: android.view.InflateException: XML file C:\...\Retrofit\app\build\intermediates\merged-not-compiled-resources\debug\layout\content_drawer.xml line #-1 (sorry, not yet implemented): Error inflating class fragment
Caused by: android.content.res.Resources$NotFoundException: com.test.retrofit:navigation/navigation_graph
	at org.robolectric.shadows.ShadowLegacyAssetManager.loadXmlResourceParser(ShadowLegacyAssetManager.java:563)
	at org.robolectric.shadows.ShadowResources.loadXmlResourceParser(ShadowResources.java:225)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java)
	at android.content.res.Resources.getXml(Resources.java:1206)
	at androidx.navigation.NavInflater.inflate(NavInflater.java:109)
	at androidx.navigation.NavController.setGraph(NavController.java:419)
	at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:221)
	at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1684)
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1930)
	at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3745)
	at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
	at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:405)
	at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:387)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:995)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:859)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.test.retrofit.presentation.DrawerActivity.onCreate(DrawerActivity.kt:23)
	at android.app.Activity.performCreate(Activity.java:7131)
	at android.app.Activity.performCreate(Activity.java:7122)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:252)
	at org.robolectric.android.controller.ActivityController$1.run(ActivityController.java:61)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:58)
	at org.robolectric.shadows.support.v4.SupportFragmentController$1.run(SupportFragmentController.java:110)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:362)
	at org.robolectric.shadows.support.v4.SupportFragmentController.create(SupportFragmentController.java:105)
	at org.robolectric.shadows.support.v4.SupportFragmentController.create(SupportFragmentController.java:126)
	at org.robolectric.shadows.support.v4.SupportFragmentController.create(SupportFragmentController.java:131)
	at org.robolectric.shadows.support.v4.SupportFragmentController.setupFragment(SupportFragmentController.java:60)
	at com.test.retrofit.presentation.apim.TypeTriFragmentTest.name(TypeTriFragmentTest.kt:16)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:606)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```



### Robolectric & Android Version
 
Robolectric 4.0-alpha-3
Android compileSdkVersion 28

**Comment by Galaxer** [comment]
I'm having the same issue as @fbattet

**Comment by jongerrish** [comment]
Its likely this will just work in binary resource mode.....

We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code and an overhaul of our PackageManager support.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.

**Comment by R4md4c** [comment]
@jongerrish I'm still experiencing this issue, with robolectric 4.1, and AGP 3.3, even after adding` enableUnitTestBinaryResources` (in gradle.properties) and `includeAndroidResources`.

I've created a project that should help you. 

The test case is in `RobolectricBugTest`, once you run it will crash with a similar stacktrace as above. 

[RobolectricNavGraphTest.zip](https://github.com/robolectric/robolectric/files/2764636/RobolectricNavGraphTest.zip)

**Comment by jongerrish** [comment]
Is it because you are using an application context and that doesn't have a
theme set?

**Comment by R4md4c** [comment]
I don't think so, because usually I invoke  `PendingIntent`s from notifications, and the context in these situations are usually without a theme set. 
When running the same PendingIntent through a real instrumented notification, it opens the desired activity normally.

**Comment by R4md4c** [comment]
@jongerrish Correction, You're right, I tried testing with `Robolectric.buildActivity(Activity::class.java).get()` and the test passes. So it is a theme thing then. 
But shouldn't it passes even when the context doesn't have a theme set.

**Comment by jongerrish** [comment]
No, that's actual real Android behavior, funny as you'd expect setting
theme on the application element in the manifest to set the theme on the
application class but it doesn't.

**Comment by daniloleemes** [comment]
Any updates on this?
I'm using 

- Android Studio 3.4.2
- Robolectric 4.3
- AndroidX
- Gradle Kotlin DSL

I'm setting the navigation graph programmatically and when I run the tests I get this message:
`android.content.res.Resources$NotFoundException: com.bestseller.android:navigation/nav_graph`

**Comment by jongerrish** [comment]
In your test log output what resources mode is being used? Should say
something like SDK=xx Resources=binary

**Comment by vasticles** [comment]
> @jongerrish Correction, You're right, I tried testing with `Robolectric.buildActivity(Activity::class.java).get()` and the test passes. So it is a theme thing then.
> But shouldn't it pass even when the context doesn't have a theme set?

Thanks for this. I spent a day on a similar issue. It looks like using `ActivityScenarioRule` is not quite the same as `Robolectric.buildActivity()`
