### ISSUE TITLE
ZipException: invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by heitorcolangelo** [robolectric/robolectric#3957]
### Description
Just updated to version 3.8 and started to get this exception from Roboletric.
```
java.lang.RuntimeException: java.util.zip.ZipException: invalid CEN header (bad signature)

	at org.robolectric.res.Fs$JarFs.<init>(Fs.java:96)
	at org.robolectric.res.Fs.fromJar(Fs.java:27)
	at org.robolectric.internal.SdkEnvironment.createRuntimeSdkResourcePath(SdkEnvironment.java:31)
	at org.robolectric.internal.SdkEnvironment.getSystemResourceTable(SdkEnvironment.java:22)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:332)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```
### Steps to Reproduce

Update to version 3.8 and run the tests that are using `RobolectricTestRunner`

### Robolectric & Android Version

Robolectric version 3.8

Android 
```groovy
compileSdkVersion = 27
minSdkVersion = 21
targetSdkVersion = 27
buildToolsVersion = "27.0.3"

'com.android.tools.build:gradle:3.1.3'

```
Gradle version 4.4

### Link to a public git repo demonstrating the problem:

Don't have it

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and feel free to reopen this issue if it still exists. Thanks.
