### ISSUE TITLE
Robolectric not working with Androidx: ClassNotFoundException

### ISSUE THREAD

**Issue by cklar** [robolectric/robolectric#3981]
### Description
As soon as I want to run this test with latest robolectric version 4.0-alpha-4-SNAPSHOT it fails with a ClassNotFoundException. 

```
@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.O_MR1, packageName = "com.example", application = TestApplication.class, shadows = {ShadowMultiDex.class})
public class SimpleTest {

    @Test
    public void name() {
        Assert.assertTrue(true);
    }
}
```

Stacktrace: 
```
java.lang.NoClassDefFoundError: android/support/v4/content/WakefulBroadcastReceiver

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:134)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:34)
	at org.robolectric.android.internal.ParallelUniverse.registerBroadcastReceivers(ParallelUniverse.java:433)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:223)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:380)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
Caused by: java.lang.ClassNotFoundException: android.support.v4.content.WakefulBroadcastReceiver
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:118)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
```

### Robolectric & Android Version
Robolectric version: 4.0-alpha-4-SNAPSHOT
AndroidX: rc01
Compile-/TargetSdk: 28

Note: Because of some libraries I still have some dependencies to support libs. The issue is also reproducable with robolectric 3.8

**Comment by naturalwarren** [comment]
Any updates here? I'm running into this as well.

**Comment by tomrozb** [comment]
Same here

**Comment by andrisama** [comment]
I am running this issue when i was updating my project to use AndroidX and Robolectric 4.0. I found that one of the library i've used declared a BroadcastReceiver on Manifest that's extending legacy `WakefulBroadcastReceiver`. A workaround that's working for my project is as follows:

1. Create empty `TestManifest.xml` on test resources folder
1. Declare @Config(manifest = "TestManifest.xml") on test class

I don't need to do above workaround if i run it from terminal tho, seems only happens when i run it from Android Studio

**Comment by slott** [comment]
I'm having similar issues

`java.lang.NoClassDefFoundError: retrofit2/converter/simplexml/SimpleXmlConverterFactory`

and the class in question _is_ implemented

implementation "com.squareup.retrofit2:converter-simplexml:${retrofitConverterSimplexml}"

Should be mentioned that the tests run fine from the command line and only fail within Android Studio.

**Comment by xian** [comment]
Do you have [these properties](https://stackoverflow.com/questions/51680671/what-is-jetifier) set in your `gradle.properties`?
```properties
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by olerich** [comment]
I have had set both of the properties in `gradle.properties` - it's failing in Android Studio, working from command line.

**Comment by jay81979** [comment]
I had the same issue. File -> Invalidate Cache and Restart worked for me in Android Studio.

**Comment by olerich** [comment]
Invalidating Cache works for me, I feel so stupid for not trying that. \
Thanks a lot!

**Comment by xian** [comment]
Thanks for the fix @jay81979!

**Comment by volsahin** [comment]
Same issue here with Robolectric : 4.0.2 and AndroidX
useAndroidX and enableJetifier flags are true in gradle.properties
Invalidate Cache and Restart not working for me.

**Comment by DummyCo** [comment]
Same here, `java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse`
```
org.robolectric:robolectric:4.1
androidx.fragment:fragment-testing:1.1.0-alpha03
```
Invalidating and clean builds are not resolving issue as for me,

**Comment by volsahin** [comment]
Hi @DummyCo is your Android Studio up to date? I got rid of with updating it

**Comment by mircze** [comment]
I have same problem like @DummyCo using AS 3.3, gradle is set to 3.3 also. Have same library version and have exactly same error.

**Comment by pimtegelaar** [comment]
Same issue here  Robolectric 4.1, AS 3.3 clean and invalidate cache did not help.
Getting `java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse`

**Comment by pimtegelaar** [comment]
Ok for the `java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse` issue in Android studio I was using classpath file as path shortening option. With the  JAR manifest option it works!

**Comment by muthuraj57** [comment]
Any update on this? Having same issue. I'm using Robolectric 4.3

**Comment by droid-it** [comment]
> Ok for the `java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse` issue in Android studio I was using classpath file as path shortening option. With the JAR manifest option it works!

Can you please elaborate on this? What exactly did you do to solve this issue?

**Comment by mochadwi** [comment]
> > Ok for the `java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse` issue in Android studio I was using classpath file as path shortening option. With the JAR manifest option it works!
> 
> Can you please elaborate on this? What exactly did you do to solve this issue?

+1 @pimtegelaar

**Comment by aditmodhvadia** [comment]
I found a fix online. Put your test file in src/test instead of src/androidTest.
I also have these set in gradle.properties
android.enableJetifier=true
android.useAndroidX=true

It worked for me.

But I got another error:
[Robolectric] WARN: Android SDK 10000 requires Java 9 (have Java 8). Tests won't be run on SDK 10000 unless explicitly requested.

I'm working on fixing this. I will update my result here.

**Comment by aditmodhvadia** [comment]
And this fixed the issue mentioned in the comment above.
Annotate your test class with this
@Config(sdk = Build.VERSION_CODES.O_MR1)

**Comment by sebastianharder** [comment]
`java.lang.ClassNotFoundException: org.robolectric.android.internal.ParallelUniverse` happens to me when I try running tests with an older Robolectric version (4.1) with JDK17 in Android Studio. Selecting a JDK11 as Gradle JDK resolves this.
