### ISSUE TITLE
Reflection error: IllegalAccessException at setting public field 

### ISSUE THREAD

**Issue by AlexTrotsenko** [robolectric/robolectric#3994]
### Description
I am developing extension (V8 debugger) using [Stetho](https://github.com/facebook/stetho). When I run test, which invokes Stetho's class where reflection is using - unexpected exception is thrown. 
Message says it can't access a member of class with modifiers **"public"**, which sounds odd.

Kotlin call:
````.Java
        val resultValues = runtime.getProperties(peerMock, JSONObject(mapOf("ownProperties" to true, "objectId" to 2)))
````

Exception:
```
java.lang.IllegalArgumentException: java.lang.IllegalAccessException: Class com.facebook.stetho.json.ObjectMapper can not access a member of class com.facebook.stetho.inspector.protocol.module.Runtime$GetPropertiesRequest with modifiers "public"

	at com.facebook.stetho.json.ObjectMapper.convertValue(ObjectMapper.java:89)
	at com.facebook.stetho.inspector.protocol.module.Runtime$Session.getProperties(Runtime.java:293)
         ...
Caused by: java.lang.IllegalAccessException: Class com.facebook.stetho.json.ObjectMapper can not access a member of class com.facebook.stetho.inspector.protocol.module.Runtime$GetPropertiesRequest with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.set(Field.java:761)
	at com.facebook.stetho.json.ObjectMapper._convertFromJSONObject(ObjectMapper.java:114)
	at com.facebook.stetho.json.ObjectMapper.convertValue(ObjectMapper.java:79)
	... 33 more
```

### Steps to Reproduce
Call `field.set(instance, setValue);` like it's done in [Stetho](https://github.com/AlexTrotsenko/stetho/blob/118d516510ef11e633927af919300bb67be6f6c4/stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java#L114)

### Robolectric & Android Version
- Android api 28
- Robolectric `4.0-alpha3` as well as Robolectric `3.8` (`@Config(sdk = [Build.VERSION_CODES.O_MR1])`)

### Link to a public git repo demonstrating the problem:
https://github.com/AlexTrotsenko/stetho/blob/118d516510ef11e633927af919300bb67be6f6c4/stetho/src/main/java/com/facebook/stetho/json/ObjectMapper.java#L114

P.S. Error message looks similar to https://github.com/robolectric/robolectric/issues/3987 but if I am not sure if it's the same issue though.

**Comment by utzcoz** [comment]
@AlexTrotsenko From the stacktrace, it is not Robolectric's problem, and it's related to your `ObjectMapper.java`. Looks like it is a JDK restriction.
