### ISSUE TITLE
Support v53 (Java 9) class files

### ISSUE THREAD

**Issue by 15characterlimi** [robolectric/robolectric#3999]
### Description

The release notes for Robolectric 3.6 say that "Java 9 is now supported [issue #3459].", but that seems to be incorrect or at least misleading. I think it supports *running* under the "java" command from OpenJDK 9, but only for v52 .class files. It doesn't support v53 .class files, as produced by OpenJDK 9's "javac" command.

I think there are at least two problems:

1.) Reading v53 class files needs ASM version 6+. robolectric was mostly updated to ASM 6 a couple of weeks ago in https://github.com/robolectric/robolectric/commit/b380af09d748771858c43d1ce62f5835296e64a3 for Robolectric 4.0, but at least one reference to ASM 5 remains in [1] and two places in the source refer to Opcodes.ASM4 (should probably use Opcodes.ASM6).

2.) ShadowGenerator generates the field __robo_data__ is generated with flags Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL in [2] , but since the changes for OpenJDK bug [3] (which were backported to earlier versions of Java), linkResolver.cpp no longer allows updates of final fields from $$robo$init (only from <init> and <clinit>). I tried changing the field to be generated nonfinal [4], but that breaks SandboxClassLoaderTest which asserts that it is final  "so Mockito doesn't try to @InjectMocks on it" [5], and links to https://github.com/robolectric/robolectric/issues/2442

[1] https://github.com/robolectric/robolectric/blob/master/buildSrc/build.gradle#L12

[2] https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/internal/bytecode/ShadowDecorator.java#L23

[3] https://bugs.openjdk.java.net/browse/JDK-8157181

[4] https://github.com/15characterlimi/robolectric/commits/robolectric-3.6.x

[5] https://github.com/robolectric/robolectric/blob/master/sandbox/src/test/java/org/robolectric/SandboxClassLoaderTest.java#L161

Here's the stacktrace that I've observed when running Robolectric on v53 class files:

java.lang.IllegalAccessError: Update to non-static final field dalvik.system.VMRuntime.__robo_data__ attempted from a different method ($$robo$init) than the initializer method <init> 
    at dalvik.system.VMRuntime.$$robo$init(VMRuntime.java)
    at dalvik.system.VMRuntime.<init>(VMRuntime.java)
    at dalvik.system.VMRuntime.__staticInitializer__(VMRuntime.java:37)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
    at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:280)

### Steps to Reproduce

I expect that all relevant OpenJDK 9 compatibility problems should be observable through:

Point PATH to OpenJDK 9, eg. the Android Open Source Project's prebuilts/jdk/jdk9/linux-x86/bin
./gradlew build

When I run these steps locally, I run into a different problem first (see below), but I expect that that problem only hides the other problems behind it.

If you work at Google, you can find reproduction steps for the above 1.-2) internally under bug 115709535.

Here's what I get when I run "./gradlew build" in an enviornment where java -version is OpenJDK  9+181:

Execution failed for task ':aggregateTestReports'.
> 77

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':aggregateTestReports'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:596)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 77
        at org.gradle.api.internal.tasks.testing.junit.result.TestResultSerializer.readMethodResult(TestResultSerializer.java:143)
        at org.gradle.api.internal.tasks.testing.junit.result.TestResultSerializer.readClassResult(TestResultSerializer.java:133)
        at org.gradle.api.internal.tasks.testing.junit.result.TestResultSerializer.readResults(TestResultSerializer.java:120)
        at org.gradle.api.internal.tasks.testing.junit.result.TestResultSerializer.read(TestResultSerializer.java:104)
        at org.gradle.api.internal.tasks.testing.junit.result.BinaryResultBackedTestResultsProvider.visitClasses(BinaryResultBackedTestResultsProvider.java:82)
        at org.gradle.api.internal.tasks.testing.junit.result.AggregateTestResultsProvider.visitClasses(AggregateTestResultsProvider.java:51)
        at org.gradle.api.internal.tasks.testing.report.DefaultTestReport.loadModelFromProvider(DefaultTestReport.java:64)
        at org.gradle.api.internal.tasks.testing.report.DefaultTestReport.generateReport(DefaultTestReport.java:57)
        at org.gradle.api.tasks.testing.TestReport.generateReport(TestReport.java:137)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 32 more

### Robolectric & Android Version

Head, ie. https://github.com/robolectric/robolectric/commit/6a86d7f5486ce5d9c7a9124410791a5ada14ebcc

My local.properties has sdk.dir pointing to an Android SDK directory with android-23, -25, -26, -27 and -28 present.

### Link to a public git repo demonstrating the problem:

https://github.com/robolectric/robolectric   :-p

**Comment by 15characterlimi** [comment]
Should be fixed by https://github.com/15characterlimi/robolectric/commit/72e4373f4922d72efbf08fc43d2b4c22509e35d5

I've proposed that fix upstream, if it gets accepted and merged here then I'll close this issue.

**Comment by xian** [comment]
I think this can be closed now, yes? Please reopen if not.
