### ISSUE TITLE
Robolectric 4 (beta): RuntimeExceptions

### ISSUE THREAD

**Issue by nikoskyr** [robolectric/robolectric#4015]
Hello,

### Description
While I was trying to integrate Robolectric 4 into my project I came across this error:

```
java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.content.res.Configuration.getLocales(Configuration.java)
	at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
	at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
	at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:106)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:372)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

It seems very strange because with the same configuration in Robolectric 3.6 this specific unit test passes.

### Robolectric & Android Version
Robolectric 4 - alpha & beta 1 
Android Studio 3.2
Gradle plugin 4.10

Could you please check it?

Thanks in advance!!!

**Comment by xian** [comment]
Hey @nikoskyr, could you include the test code that causes this problem?

**Comment by xian** [comment]
Also, which SDK is this running on? Robolectric should tell you on stdout.

**Comment by nikoskyr** [comment]
Hello @xian,

Thanks for the prompt reply.

In the build.gradle I have the following setup:
```
testOptions {
        unitTests {
            //returnDefaultValues = true
            includeAndroidResources = true
        }

testImplementation 'androidx.test:rules:1.1.0-alpha4'
testImplementation 'androidx.test:runner:1.1.0-alpha4'
testImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
testImplementation "org.robolectric:robolectric:4.0-beta-1"
//testImplementation "org.robolectric:robolectric:3.6.1"
```

And the test code respectively:
```
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import androidx.test.rule.ActivityTestRule;
import androidx.test.runner.AndroidJUnit4;

import static org.junit.Assert.assertNotNull;

@RunWith(AndroidJUnit4.class)
public class MyActivityTest {


    private MyActivityTest activity;

    @Rule
    public ActivityTestRule<MyActivity> mActivityRule = new ActivityTestRule<>(MyActivity.class);

    @Before
    public void setUp() throws Exception {
    }

    @Test
    public void shouldNotBeNull() throws Exception {
        assertNotNull( activity );
    }
}
```
Also, the SDK that is running on is 27
[Robolectric] MyActivityTest.shouldNotBeNull: sdk=27; resources=legacy

**Comment by nikoskyr** [comment]
Hello,

I made a few changes in the compiledSdk (27->28) and I added the following code, taken from my Espresso tests, in the before test and it worked.

```
@Before
    public void setUp() throws Exception {
        activity = mActivityRule.getActivity();
    }
```
However, when I changed the compiledSdk back to 27, I came across the aforementioned issue.

**Comment by xian** [comment]
@nikoskyr -- sorry, I'm still unable to reproduce this here. If you're still seeing the problem with 4.0, could you create a git repo with a minimal project that displays this problem and reopen this issue? Thanks!

**Comment by nikoskyr** [comment]
@xian The problem was only reproducible with the compiledSdk=27. 
However, we have updated our app to 28 so this issue is resolved.

Thank you for the support and your time!!

**Comment by ScottPierce** [comment]
We are seeing this intermittently on our jenkins environment as well.

**Comment by wongk** [comment]
I just saw this in our build environment w/ 4.0.1.

`java.lang.RuntimeException: java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.content.res.Configuration.getLocales(Configuration.java)
	at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
	at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
	at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:106)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)`
