### ISSUE TITLE
4.0 migration tool not working on simple sample project (also the doc needs clarification)

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#4052]
### Description
I've created a sample project to test out the [automatic migration](http://robolectric.org/automated-migration/)

The documentation doesn't specify if the gradle config should go on the **root** `build.gradle` or the **app** `build.gradle`.  But either way, the tool doesn't work as expected:
* If the config is added to the root gradle file, the manual tasks fail because the root gradle file doesn't have java compilation tasks `Task 'compileDebugUnitTestJava' not found in root project`
* If the config is added to the app gradle file, the manual task ends in error, indicating the deprecated code, but not modifying it as the documentation says it would.

### Steps to Reproduce
A sample app is here: https://github.com/libon/RobolectricMigration
This is just a bare bones newly created app from Android Studio, with:
* androidTests removed
* one simple robolectric test which uses a deprecated api: `ShadowApplication.getInstance().getNextStartedActivity();`
* the gradle config for the migration tool added to the root build.gradle
* a `README.md` with the details of the issues with the tool.

To reproduce it, just follow the steps in the automatic migration guide to try to automatically migrate the test which uses deprecated code.  Specifically the following were tried:
* Adding the tool config to the root build.gradle:
  - Running:
 ```ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :compileDebugUnitTestJava```
      * result: `Task 'compileDebugUnitTestJava' not found in root project`
  - Running: 
```ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :app:compileDebugUnitTestJava```
      * result: successful completion, but no warnings or corrections for the deprecated code.
* Moving the tool config to the app build.gradle:
  - Running `ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :app:compileDebugUnitTestJava`
      * result: build errors but no corrections of deprecated code:
```
ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :app:compileDebugUnitTestJava

> Task :app:compileDebugJavaWithJavac
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/androidx/versionedparcelable/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/example/com/robolectricmigration/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/coreutils/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/asynclayoutinflater/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/v7/viewpager/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/v7/appcompat/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/compat/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/drawerlayout/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/interpolator/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/coreui/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/documentfile/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/print/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/localbroadcastmanager/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/cursoradapter/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/swiperefreshlayout/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/fragment/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/loader/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/customview/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/slidingpanelayout/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/graphics/drawable/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/support/coordinatorlayout/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/arch/core/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/arch/lifecycle/viewmodel/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/arch/lifecycle/livedata/core/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/arch/lifecycle/livedata/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/not_namespaced_r_class_sources/debug/processDebugResources/r/android/arch/lifecycle/R.java, please check the refactored code and recompile.
Refactoring changes were successfully applied to file:///Users/calvarez/dev/projects/RobolectricMigration/app/build/generated/source/buildConfig/debug/example/com/robolectricmigration/BuildConfig.java, please check the refactored code and recompile.

> Task :app:compileDebugUnitTestJavaWithJavac FAILED
/Users/calvarez/dev/projects/RobolectricMigration/app/src/test/java/example/com/robolectricmigration/ExampleUnitTest.java:13: warning: [DeprecatedMethods] Robolectric shadows shouldn't be stored to variables or fields.
public class ExampleUnitTest {
       ^
    (see http://errorprone.info/bugpattern/DeprecatedMethods)
  Did you mean 'Intent nextActivity = shadowOf(RuntimeEnvironment.application).getNextStartedActivity();'?
1 warning
An exception has occurred in the compiler ((version info not available)). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: unexpected type: (android.app.Application)org.robolectric.shadows.ShadowApplication
        at com.sun.tools.javac.tree.TreeMaker.Type(TreeMaker.java:787)
        at com.sun.tools.javac.comp.TransTypes.cast(TransTypes.java:121)
        at com.sun.tools.javac.comp.TransTypes.coerce(TransTypes.java:148)
        at com.sun.tools.javac.comp.TransTypes.retype(TransTypes.java:186)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:728)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1628)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:532)
        at com.sun.tools.javac.comp.TransTypes.visitSelect(TransTypes.java:883)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2104)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:532)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:706)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1628)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:532)
        at com.sun.tools.javac.comp.TransTypes.visitVarDef(TransTypes.java:588)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:950)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:167)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1014)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:532)
        at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:567)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:866)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:139)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:994)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:553)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:532)
        at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:1018)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1545)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1418)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
        at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at org.gradle.api.internal.tasks.compile.IncrementalAnnotationProcessingCompileTask.call(IncrementalAnnotationProcessingCompileTask.java:73)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:37)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerRunnable.run(AbstractDaemonCompiler.java:87)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:36)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:46)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:30)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugUnitTestJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### Robolectric & Android Version
Robolectric 3.8
### Link to a public git repo demonstrating the problem:
https://github.com/libon/RobolectricMigration

**Comment by xian** [comment]
@calvarez-ov — awesome bug report. :-) You're right, the config snippet should go in `app/build.gradle` or wherever your code lives. I'll fix the docs and figure out what's up with the failure. Thanks!

**Comment by m00head** [comment]
This may not fix the issue, but just thought I would point it out anyway.

Step 1 of the [Automated Migration](http://robolectric.org/automated-migration/) docs says:
> Make sure you’re using a recent version of Gradle (**4.10 or newer**).

But the linked git repo is using Gradle 4.6:
https://github.com/libon/RobolectricMigration/blob/c7fb1573a31c9b80fffe320025d3c873857d5601/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by calvarez-ov** [comment]
@m00head thanks for the heads-up about the gradle version. I've updated it to 4.10.2, and it appears to have the same issues.

**Comment by xian** [comment]
@calvarez-ov, I've fixed a few issues with the migrator which will be in the 4.0.1 release, coming soon. If you'd like to give it a try now, you can use this line in your dependencies:

```groovy
errorprone "org.robolectric:errorprone:4.0.1-rc1"
```

Let me know if you see more issues! Thanks again!

**Comment by calvarez-ov** [comment]
@xian Indeed the migration tool works, cool 👍 I see that it modified by `ExampleUnitTest.java`

But I think the doc needs one more minor change.
In step 3, instead of:
```
ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :compileDebugUnitTestJava
ROBOLECTRIC_MIGRATION=ShadowUsageCheck ./gradlew clean :compileDebugUnitTestJava
```

it should be:
```
ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :app:compileDebugUnitTestJava
ROBOLECTRIC_MIGRATION=ShadowUsageCheck ./gradlew clean :app:compileDebugUnitTestJava
```

**Comment by cooldude77** [comment]
Need Help!! 
How do you run this from android studio ?
```
ROBOLECTRIC_MIGRATION=DeprecatedMethods ./gradlew clean :app:compileDebugUnitTestJava
ROBOLECTRIC_MIGRATION=ShadowUsageCheck ./gradlew clean :app:compileDebugUnitTestJava 
```
Thanks :)
