### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x7f090005

### ISSUE THREAD

**Issue by rameshmkll** [robolectric/robolectric#4082]
I am using Robolectric dependency  testImplementation "org.robolectric:robolectric:4.0.1"
        
and i have added 

android {
    compileSdkVersion 28
    testOptions.unitTests.includeAndroidResources = true
}
in Build.gradle file

and added android.enableUnitTestBinaryResources=true in grdle.properties

and updated my gradle plugin to  classpath 'com.android.tools.build:gradle:3.2.1'  as per the latest Robolectric plugin documentation from http://robolectric.org/migrating/#migrating-to-40.
But i am still getting the above error.

**Comment by jongerrish** [comment]
Are you using aapt2 or aapt?

**Comment by fbarthelery** [comment]
I have the same issue when trying to load an xml preferences resources. 
it loads fine without `android.enableUnitTestBinaryResources=true`

**Comment by fbarthelery** [comment]
I'm using aaptv2 (I think it's enabled by default on AGP 3.4-rcXX) 

Simple settings Fragment in an activity
```
    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
    public static class SettingsFragment extends PreferenceFragmentCompat {
        @Override
        public void onCreatePreferences(Bundle savedInstanceState, String rootKey) {
            // this fails with the ResourcesNotFoundException, the failing id is the one R.xml.pref_general
            addPreferencesFromResource(R.xml.pref_general); 
       }
    }
```

pref_general is in `src/main/res/xml` no qualifiers and it contains an empty `PreferenceScreen`

I actually run the test using `AndroidJunit4` runner after reading https://medium.com/androiddevelopers/write-once-run-everywhere-tests-on-android-88adb2ba20c5 so I didn't specify any runtime version.

I'll try to make a sample test case later this week.

**Comment by jongerrish** [comment]
@fbarthelery - What is your test runtime environment + resource mode?

You can see something like this in your logs:-

E.[Robolectric] com.foo.TestClass.testName: sdk=19; resources=binary

**Comment by fbarthelery** [comment]
sdk=28, resources=binary

**Comment by rameshmkll** [comment]
I wrote a simple test case for null checking

@RunWith(RobolectricTestRunner.class)
public class LoginActivityTest {
    Activity activity;
    Button login;
    TextInputLayout email,password;


    @Before
    public void setUp() {
         activity = Robolectric.setupActivity(LoginActivity.class);
         login=activity.findViewById(R.id.btnLogin);
         email=activity.findViewById(R.id.tip_username_mobile);
         password=activity.findViewById(R.id.tip_password);
    }

    @Test
    public void shouldNotBeNull()
    {
        assertNotNull(activity);
        assertNotNull(login);
        assertNotNull(email);
        assertNotNull(password);
    }
}

Error Log

[Robolectric] com.delivmeds.LoginActivityTest.loginFailure: sdk=28; resources=legacy
[Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40


android.content.res.Resources$NotFoundException: Resource ID #0x7f090005

	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)
	at android.content.res.Resources.getValue(Resources.java:1331)
	at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:337)
	at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:207)



I have made changes as given in here  http://robolectric.org/migrating/#migrating-to-40


I did not add android.enableUnitTestBinaryResources=true in grdale.properties.

If i add android.enableUnitTestBinaryResources=true in grdale.properties.

while running test cases i am getting below error

Illegal character in opaque part at index 11: jar:file:D:\projects\myproject-android\app\build\intermediates\apk_for_local_test\qaDebugUnitTest\packageQaDebugUnitTestForUnitTest\apk-for-local-test.ap_

**Comment by jongerrish** [comment]
@rameshmkll I think you are running into https://github.com/robolectric/robolectric/issues/3955

**Comment by rameshmkll** [comment]
Is this issue caused by not setting 
android.enableUnitTestBinaryResources=true in grdale.properties in windows.

But in #3995 there was no solution given.

What should we do to run our test cases.
Can you help us to resolve this issue.

**Comment by jongerrish** [comment]
Yep, we'll have a fix in 4.0.2 for binary resources on windows.

**Comment by xian** [comment]
Could you point us at a public git repo with a simple project that exhibits the problem you mentioned at the top (the `Resources$NotFoundException`) if you're still seeing that error?

**Comment by rameshmkll** [comment]
My Test cases are running successfully after i have removed
"android.enableUnitTestBinaryResources=true" from gradle.properties in Android studio 3.3 beta 3.
