### ISSUE TITLE
Fake ServiceInfo doesn't contain processName, causing LeakCanary failure

### ISSUE THREAD

**Issue by Egorand** [robolectric/robolectric#4090]
### Description
Unit tests ran with `RobolectricTestRunner` fail with the following exception:
```java
java.lang.NullPointerException
	at com.squareup.leakcanary.internal.LeakCanaryInternals.isInServiceProcess(LeakCanaryInternals.java:114)
	at com.squareup.leakcanary.LeakCanary.isInAnalyzerProcess(LeakCanary.java:182)
	at com.squareup.cash.CashApp.onCreate(CashApp.java:45)
        ...
```

The stack trace points to the following code in [LeakCanary](https://github.com/square/leakcanary) codebase:
```java
ComponentName component = new ComponentName(context, serviceClass);
ServiceInfo serviceInfo;
try {
  serviceInfo = packageManager.getServiceInfo(component, 0);
} catch (PackageManager.NameNotFoundException ignored) {
  // Service is disabled.
  return false;
}

// this line causes the crash
if (serviceInfo.processName.equals(mainProcess)) {
```

Debugging shows that the value of `processName` is null.

### Robolectric & Android Version
Robolectric: 4.0.1
Android: compileSdk = 28, targetSdk = 28, minSdk = 21

**Comment by Egorand** [comment]
Happy to provide more info or create a project that reproduces the issue if needed.
