### ISSUE TITLE
Tests run successfully when ran from IDE, but fail when ran by a task

### ISSUE THREAD

**Issue by stankinzl** [robolectric/robolectric#4254]
### Description

Hello, I ran into this odd problem. We are trying to use Robolectric 4.0.2 for our instrumented testing. We use Espresso. When I run this test:

<img width="636" alt="screenshot 2018-12-02 at 14 02 45" src="https://user-images.githubusercontent.com/22709850/49340651-fa240200-f63a-11e8-8eea-a6e10fe1f412.png">
(The same test using Kakao library, for better understanding. Results are the same)
<img width="501" alt="screenshot 2018-12-02 at 14 03 57" src="https://user-images.githubusercontent.com/22709850/49340671-40796100-f63b-11e8-93bb-8f70b751b095.png">

It is successful when running from IDE (both the same result.) - it shows the green successful symbols after running for each test.

![screenshot 2018-12-02 at 14 31 46](https://user-images.githubusercontent.com/22709850/49341013-7ae4fd00-f63f-11e8-9d88-fb75dc78e863.png)

But when they are executed by task tDUT (./gradlew clean tDUT) taskDebugUnitTests (runs all the tests in the project.) This is the output:

<img width="782" alt="screenshot 2018-12-02 at 14 13 05" src="https://user-images.githubusercontent.com/22709850/49340769-70753400-f63c-11e8-9184-79e4fa20ec90.png">

And when you see the stack trace:

```
<init>java.lang.VerifyError: Stack map does not match the one at exception handler 176
Exception Details:
  Location:
    androidx/test/espresso/core/internal/deps/guava/util/concurrent/InterruptibleTask.run()V @176: astore
  Reason:
    Type 'java/lang/Object' (current frame, locals[4]) is not assignable to null (stack map, locals[4])
  Current Frame:
    bci: @80
    flags: { }
    locals: { 'androidx/test/espresso/core/internal/deps/guava/util/concurrent/InterruptibleTask', '[Z', 'java/lang/Thread', integer, 'java/lang/Object', null }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @176
    flags: { }
    locals: { 'androidx/test/espresso/core/internal/deps/guava/util/concurrent/InterruptibleTask', '[Z', 'java/lang/Thread', integer, null, null }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: b800 804c b800 1d4d 2b04 0454 2a01 2cb6
    0x0000010: 0021 9a00 082b 0504 54b1 2ab6 0025 9a00
    0x0000020: 0b04 2b06 0454 a700 0803 2b07 0454 3e01
    0x0000030: 3a04 013a 052b 0804 541d 9a00 0b2b 1006
    0x0000040: 0454 a700 132b 1007 0454 2ab6 0029 3a04
    0x0000050: 2b10 0804 542a 2cb2 002d b600 2199 000b
    0x0000060: 2b10 0904 54a7 002a 2b10 0a04 542a b600
    0x0000070: 30b2 0032 a500 0b2b 100b 0454 a700 132b
    0x0000080: 100c 0454 b800 352b 100d 0454 a7ff e11d
    0x0000090: 9a00 0b2b 100e 0454 a700 e02b 100f 0454
    0x00000a0: 2a19 0419 05b6 0039 2b10 1004 54a7 00cb
    0x00000b0: 3a06 1906 3a05 2b10 1104 542a 2cb2 002d
    0x00000c0: b600 2199 000b 2b10 1204 54a7 002a 2b10
    0x00000d0: 1304 542a b600 30b2 0032 a500 0b2b 1014
    0x00000e0: 0454 a700 132b 1015 0454 b800 352b 1016
    0x00000f0: 0454 a7ff e11d 9a00 0b2b 1017 0454 a700
    0x0000100: 7a2b 1018 0454 2a19 0419 05b6 0039 2b10
    0x0000110: 1904 54a7 0065 3a07 2a2c b200 2db6 0021
    0x0000120: 9900 0b2b 101a 0454 a700 2a2b 101b 0454
    0x0000130: 2ab6 0030 b200 32a5 000b 2b10 1c04 54a7
    0x0000140: 0013 2b10 1d04 54b8 0035 2b10 1e04 54a7
    0x0000150: ffe1 1d9a 000b 2b10 1f04 54a7 0015 2b10
    0x0000160: 2004 542a 1904 1905 b600 392b 1021 0454
    0x0000170: 1907 2b10 2204 54bf 2b10 2304 54b1     
  Exception Handler Table:
    bci [53, 85] => handler: 176
    bci [53, 85] => handler: 278
    bci [176, 187] => handler: 278
    bci [278, 280] => handler: 278
  Stackmap Table:
    append_frame(@26,Object[#130],Object[#25])
    same_frame(@41)
    same_locals_1_stack_item_frame(@46,Integer)
    append_frame(@69,Integer,Null,Null)
    full_frame(@85,{Object[#2],Object[#130],Object[#25],Integer,Object[#43],Null},{})
    same_frame(@104)
    same_frame(@109)
    same_frame(@127)
    same_frame(@143)
    same_frame(@155)
    full_frame(@176,{Object[#2],Object[#130],Object[#25],Integer,Null,Null},{Object[#23]})
    full_frame(@206,{Object[#2],Object[#130],Object[#25],Integer,Null,Object[#23],Object[#23]},{})
    same_frame(@211)
    same_frame(@229)
    same_frame(@245)
    same_frame(@257)
    full_frame(@278,{Object[#2],Object[#130],Object[#25],Integer,Null,Null},{Object[#23]})
    append_frame(@299,Top,Object[#23])
    same_frame(@304)
    same_frame(@322)
    same_frame(@338)
    same_frame(@350)
    same_frame(@368)
    full_frame(@376,{Object[#2],Object[#130],Object[#25],Integer,Object[#43],Object[#23]},{})

	at androidx.test.espresso.core.internal.deps.guava.util.concurrent.TrustedListenableFutureTask.<init>(TrustedListenableFutureTask.java:67)
	at androidx.test.espresso.core.internal.deps.guava.util.concurrent.TrustedListenableFutureTask.create(TrustedListenableFutureTask.java:41)
	at androidx.test.espresso.core.internal.deps.guava.util.concurrent.AbstractListeningExecutorService.newTaskFor(AbstractListeningExecutorService.java:51)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:133)
	at androidx.test.espresso.core.internal.deps.guava.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:289)
	at com.████.mobile.testingandroid.helpers.TestMatchers.iSee(TestMatchers.kt:101)
	at com.████.mobile.titan.slot.view.ChangeDeliverySlotActivityTestNew$checkToolbarDisplaysExpectedTitle$1.invoke(ChangeDeliverySlotActivityTestNew.kt:46)
	at com.████.mobile.titan.slot.view.ChangeDeliverySlotActivityTestNew$checkToolbarDisplaysExpectedTitle$1.invoke(ChangeDeliverySlotActivityTestNew.kt:13)
	at com.████.mobile.testingandroid.BDDEspressoTest.Given(BDDEspressoTest.kt:6)
	at com.████.mobile.titan.slot.view.ChangeDeliverySlotActivityTestNew.checkToolbarDisplaysExpectedTitle(ChangeDeliverySlotActivityTestNew.kt:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:600)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:527)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

It is problematic for us because this task is tied with our Jenkins CI, which is integrated into our GitHub project and we can't merge branches into our develop branch if any tests are unsuccessful.

### Robolectric & Android Version

Robolectric 4.0.2
Gradle Plugin Version 3.2.1
Android Studio Version 3.2

**Comment by 69** [comment]
weird flex but ok

**Comment by mageRabbitStudios** [comment]
Our senior engineer managed to fix it somehow. I'll ask him and let you know how he did it soon.

**Comment by xian** [comment]
Love to hear if he has further info!

**Comment by satur9nine** [comment]
I'm see the exact same problem...

**Comment by alipov** [comment]
Just had the exact same issue: tests ran from Android Studio succeeded, while tests ran from terminal failed with `java.lang.VerifyError`.
I've documented my issue [here](https://stackoverflow.com/q/61520264/1233652), but TLDR is that in my case it was caused by JDK version mismatch.

**Comment by utzcoz** [comment]
@stankinzl @satur9nine Please try the latest Robolectric release, and feel free to reopen this issue if it still exists.
