### ISSUE TITLE
No package ID found - Resources$NotFoundException String not found

### ISSUE THREAD

**Issue by CookedApps** [robolectric/robolectric#4278]
### Description
Hello. I constructed a simple JUnit test which tries to get a string from strings.xml (just to see if Robolectric works for my project) like this:

```java
@RunWith(RobolectricTestRunner.class)
public class RoboStringTest {
    @Test
    public void getStringFromResources() {
        Context context = RuntimeEnvironment.systemContext;
        String actual = context.getString(R.string.error);
        assertEquals("Error", actual);
    }
}
```

But it throws an exception:
```
No package ID 7f found for ID 0x7f0e005d.

android.content.res.Resources$NotFoundException: String resource ID #0x7f0e005d

	at android.content.res.Resources.getText(Resources.java:348)
	at android.content.res.Resources.getString(Resources.java:441)
	at android.content.Context.getString(Context.java:578)
	at com.cookedapps.android.dronescout.RoboStringTest.getStringFromResources(RoboStringTest.java:21)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:600)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

I read every Github issue or Stackoverflow question regarding this problem but all provided solutions did not work for me. 

Disabling AAPT2 with `android.enableAapt2=false` resulted in the same exception but i think this should not be a problem with Robolectric 4.

What I find interesting is the message **`"No package ID 7f found for ID 0x7f0e005d."`**. This stays the same for ever string I try to get. I don't understand this message. Does it mean that strings.xml could not be found?

### Steps to Reproduce

- Added `testOptions.unitTests.includeAndroidResources = true` to my `build.gradle`
- Added `android.enableUnitTestBinaryResources=true` to my `gradle.properties`
- Checked my JUnit Run Config (I am on Linux), Working dir is set to `$MODULE_DIR$`

### Robolectric & Android Version
Robolectric: 4.0.2
Robolectric-Multidex: 4.0.2
Sdk: 28
BuildTools: 28.0.3
Gradle: 3.2.1
AS: 3.2.1

**Comment by jongerrish** [comment]
You shouldn't need to android.enableAapt2=false and all your config looks correct.

Did you put the test under "tests" folder, not "androidTest"?

7F is the application package ID in the resource space where

PPTTTTEEEE

P = package
T = type
E = entry

So it looks like there are no application resources.

Can you put a break point in DefaultManifestFactory.identify() https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/DefaultManifestFactory.java#L22

And let us know the values of all the properties that are being read, especially "android_resource_apk" - this is the path to the resources.ap_ file that contains your applications resources that gradle (AGP) passes to Robolectric. If there is a value there, can you check and see if the file exists?

**Comment by RanaJakka** [comment]
Use this 
testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

**Comment by Barryrowe** [comment]
I am running into this same issue during an upgrade to Android Studio 3.4 Canary 9.

- Our tests are under the "test" directory and not "androidTest"
- Tests were passing with the following environment:
     - Android Studio 3.3 beta 4
     - AGP 3.3.0-beta04
     - gradle 4.10
     - `android.testOptions.unitTests.includeAndroidResources = true` in `build.gradle`
     - Robolectric version 4.0-alpha-3

While attempting to update to the latest Android Studio, I ran into this issue: https://github.com/robolectric/robolectric/issues/3333 and found robolectric 4.1 is available. This seemed to resolve #3333, and all but 4 tests pass again. However, these 4 tests expect to validate color and drawable resources are applied, and fail to find them.

Environment After upgrading:
     - Android Studio 3.4 Canary 9
     - AGP 3.4.0-alpha09
     - gradle 5.1 (required for AGP 3.4)
     - `android.testOptions.unitTests.includeAndroidResources = true` in `build.gradle`
     - Robolectric version 4.1

I have set a debugger in the class you mentioned above `DefaultManifestFactory.java` and there are paths in the properties, and the files do exist. 

```
properties = {Properties@897}  size = 5
 0 = {Hashtable$Entry@911} "android_sdk_home" -> "/Users/barry.rowe/devtools/Android/sdk/platforms/android-28"
 1 = {Hashtable$Entry@912} "android_merged_assets" -> "/Users/barry.rowe/projects/TS-Android/mobile/build/intermediates/merged_assets/tsIte/out"
 2 = {Hashtable$Entry@913} "android_custom_package" -> "com.ts.android"
 3 = {Hashtable$Entry@914} "android_merged_manifest" -> "/Users/barry.rowe/projects/TS-Android/mobile/build/intermediates/merged_manifests/tsIte/AndroidManifest.xml"
 4 = {Hashtable$Entry@915} "android_resource_apk" -> "/Users/barry.rowe/projects/TS-Android/mobile/build/intermediates/apk_for_local_test/tsIteUnitTest/packageTsIteUnitTestForUnitTest/apk-for-local-test.ap_"
```
Stepping through the execution the resourceMode also gets set to Binary.

**Comment by Alton09** [comment]
I am seeing this issue with the following environment:
- Android Studio 3.3
- gradle 5.1.1
- Robolectric 4.2
- setting `android.testOptions.unitTests.includeAndroidResources = true` did not work

This issue does not occur for developers in my team who are using MacOS. Once I downgraded to Robolectric 4.1 the issue was resolved.

**Comment by buntupana** [comment]
> @jongerrish Thanks for your quick response.
> 
> I put the test under "test" folder, not "androidTest". I guess that is correct (?).
> 
> Debugging gave me these properties:
> 
> ```
>  "android_sdk_home" -> "/home/user/Android/Sdk/platforms/android-28"
>  "android_merged_assets" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out"
>  "android_custom_package" -> "com.cookedapps.android.myapp"
>  "android_merged_manifest" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml"
>  "android_resource_apk" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_"
> ```
> 
> They are from the current DefaultManifestFactory, not the passed config. I hope that is what you wanted.
> 
> And yes the file under "android_resource_apk" did exist when I debugged the test.
> 
> **In addition to that** I constructed a test which tries to save a key to SharedPreferences.
> This results in: `java.lang.RuntimeException: No data directory found for package android`
> Is it correct that it just says package "android" and not my actual package name?

I have the same problem with SharedPreferences

- Robolectric 4.2
- gradle 4.10.1

**Comment by shaurya947** [comment]
Any updates on this? Essentially unable to write view tests using Robolectric, something that I enjoyed doing in an old project with older versions of everything. 😢

**Comment by shinwan2** [comment]
> > @jongerrish Thanks for your quick response.
> > I put the test under "test" folder, not "androidTest". I guess that is correct (?).
> > Debugging gave me these properties:
> > ```
> >  "android_sdk_home" -> "/home/user/Android/Sdk/platforms/android-28"
> >  "android_merged_assets" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/merged_assets/debug/mergeDebugAssets/out"
> >  "android_custom_package" -> "com.cookedapps.android.myapp"
> >  "android_merged_manifest" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml"
> >  "android_resource_apk" -> "/home/user/AndroidStudioProjects/myapp-android/app/build/intermediates/apk_for_local_test/debugUnitTest/packageDebugUnitTestForUnitTest/apk-for-local-test.ap_"
> > ```
> > 
> > 
> > They are from the current DefaultManifestFactory, not the passed config. I hope that is what you wanted.
> > And yes the file under "android_resource_apk" did exist when I debugged the test.
> > **In addition to that** I constructed a test which tries to save a key to SharedPreferences.
> > This results in: `java.lang.RuntimeException: No data directory found for package android`
> > Is it correct that it just says package "android" and not my actual package name?
> 
> I have the same problem with SharedPreferences
> 
> * Android Studio 3.3.2
> * Robolectric 4.2
> * gradle 4.10.1

I ran into the same issue when testing `SharedPreferences`
- Android Studio 3.4.1
- Robolectric 4.3

```
java.lang.RuntimeException: No data directory found for package android

at android.app.ContextImpl.getDataDir(ContextImpl.java:2204)
at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:517)
at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:714)
at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:368)
```

Specifying `sdk` with value 21 or 23 in the `@Config` annotation solved this for me.
```kotlin
@RunWith(AndroidJUnit4::class)
@Config(sdk = [21], …)
class MyPreferencesTest {
    …
```

**Comment by cooldude77** [comment]
Trying to do operations on files( create/update/deletes) throw up the same error

**Comment by cooldude77** [comment]
Have you tried adding
`testImplementation 'androidx.test:core:1.0.0'` to the build gradle and then using 
`ApplicationProvider.getApplicationContext();` to get context. I was able to perform file operations with this

**Comment by JohnZhang1000** [comment]
Any updates on this? I have a project, it used pacakge_res.apk for Custom theme,  when I use robolectric to test activity,It shows No package ID 02 found for ID 0x02060009. whitch acturly is the ID of the theme resouce. and I have no idea how to add apk Resources for Unit Test. 

Android Studio 4.1.1
Robolectric 4.7.3
sdk 30
and uesd testOption
testOptions {
        unitTests {
            includeAndroidResources = true
            returnDefaultValues  = true
        }
    }
aaptOptions {
     additionalParameters '-I',   ../../../package_res.apk', '--auto-add-overlay'
}

**Comment by sbeach** [comment]
My team is experiencing flaky tests that seem related to this issue. We're seeing a number of our tests fail with varying Robolectric interactions, but they always contain this stacktrace in the build console logs:
```shell
java.lang.RuntimeException at ShadowPackageParser.java:70
    Caused by: android.content.pm.PackageParser$PackageParserException at PackageParser.java:1243
        Caused by: java.lang.NullPointerException at CppAssetManager2.java:687
```
When run from Android Studio, we _sometimes_ get a more detailed stacktrace:
```shell
android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /<source>/build/intermediates/apk_for_local_test/<flavor>UnitTest/apk-for-local-test.ap_
java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /<source>/build/intermediates/apk_for_local_test/<flavor>UnitTest/apk-for-local-test.ap_
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:70)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:404)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:376)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:376)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:273)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:245)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:242)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:72)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:210)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:331)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /<source>/build/intermediates/apk_for_local_test/<flavor>UnitTest/apk-for-local-test.ap_
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1243)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1189)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1093)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1102)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:48)
	... 18 more
Caused by: java.lang.NullPointerException
	at org.robolectric.res.android.CppAssetManager2.FindEntry(CppAssetManager2.java:687)
	at org.robolectric.res.android.CppAssetManager2.GetResource(CppAssetManager2.java:849)
	at org.robolectric.res.android.CppAssetManager2.ResolveReference(CppAssetManager2.java:907)
	at org.robolectric.res.android.AttributeResolution10.RetrieveAttributes(AttributeResolution10.java:493)
	at org.robolectric.shadows.ShadowArscAssetManager10.nativeRetrieveAttributes(ShadowArscAssetManager10.java:1591)
	at android.content.res.AssetManager.nativeRetrieveAttributes(AssetManager.java)
	at android.content.res.AssetManager.retrieveAttributes(AssetManager.java:1188)
	at android.content.res.Resources.obtainAttributes(Resources.java:2120)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowResources$ResourcesReflector$$Reflector6.obtainAttributes(Unknown Source)
	at org.robolectric.shadows.ShadowResources.obtainAttributes(ShadowResources.java:98)
	at android.content.res.Resources.obtainAttributes(Resources.java)
	at android.content.pm.PackageParser.parseActivity(PackageParser.java:4288)
	at android.content.pm.PackageParser.parseBaseApplication(PackageParser.java:3765)
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2021)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1912)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1227)
	... 22 more
```

When I found this thread, I put a breakpoint in `DefaultManifestFactory` as suggested; the `.ap_` file **did** exist, at least for that particular test.
We have so far been unable to isolate any setting or code change that addresses this. It has primarily been a problem since we upgraded our target SDK to 33, but was present before that, albeit at a far lesser frequency.
Build details:

- Android Studio Stable (Dolphin | 2021.3.1 Patch 1)
- Android Gradle Plugin 7.3.1
- Gradle 7.4
- Robolectric 4.9.1
- compileSdkVersion 33
- minSdkVersion 26
- targetSdkVersion 33
- data binding
- view binding
- prolific use of Dagger (version 2.44)

```groovy
testOptions {
  unitTests {
    includeAndroidResources = true
  }
  unitTests.all {
    jvmArgs '-noverify', '-XX:MaxMetaspaceSize=1024m', '-Xmx1024m', '-Xms512m'
    systemProperty 'robolectric.logging.enabled', 'true'
    maxHeapSize = "1024m"
    minHeapSize = "512m"
  }
}
```

**Comment by yuvalgnessin-qz** [comment]
I am experiencing the same issue as @sbeach on my project. Tests fail intermittently on CI with the same stacktrace as the one @sbeach shared, and locally tests pass but I see errors like this in the logs:

```
No package ID 7f found for ID 0x7f140503.
```
