### ISSUE TITLE
I am getting this error for every time when in trying to run the test.

### ISSUE THREAD

**Issue by RanaJakka** [robolectric/robolectric#4292]
```
java.lang.IllegalArgumentException
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:77)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:63)
	at org.objectweb.asm.tree.ClassNode.visitAnnotation(ClassNode.java:208)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.robolectric.internal.bytecode.ClassInstrumentor.analyzeClass(ClassInstrumentor.java:63)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$maybeInstrumentClass$1(SandboxClassLoader.java:121)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:120)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:111)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:110)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.RobolectricTestRunner.getHooksInterface(RobolectricTestRunner.java:550)
	at org.robolectric.RobolectricTestRunner.configureSandbox(RobolectricTestRunner.java:233)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:230)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by xian** [comment]
Java version? Robolectric version?

**Comment by RanaJakka** [comment]
@xian 
Robolectric Version   4.0.2
java version "1.8.0_191"

**Comment by xian** [comment]
I suspect you're running into the download race condition bug #2346, which is fixed in Robolectric 4.1, due out this week. You may also want to try clearing your maven cache:
```bash
rm -rf ~/.m2/repository/org/robolectric/android-all
```

**Comment by calvarez-ov** [comment]
Just started running into this issue after adding a new dependency to my project: 
```gradle
implementation "com.braintreepayments.api:three-d-secure:$braintreeVersion"
```

It happens when running tests from Android Studio, but not from running tests from the command line.

Excluding the asm dependency makes the tests pass on Android Studio:
```gradle
    implementation ("com.braintreepayments.api:three-d-secure:3.3.0") {
        exclude module: 'asm'
    }
```

robolectric version: 4.3

Will update here with more info as I investigate.

**Comment by jongerrish** [comment]
I think this is different versions of ASM, here's the source

https://github.com/consulo/objectweb-asm/blob/master/asm/src/main/java/org/objectweb/asm/AnnotationVisitor.java#L70
