### ISSUE TITLE
kotlin/rooms/coroutines: BootstrapMethodError: IllegalAccessError

### ISSUE THREAD

**Issue by personshelldon** [robolectric/robolectric#4340]
### Description
Hello! I have a problem with testing my logic if it is written in `kotlin` and with `companion object`.
Project has many modules and some of them are written on `kotlin`, but the main module is written on `java`, that's why all main tests also on `java`. But when I try to start any tests there is an error:
```
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class android.support.v17.leanback.widget.LeanbackInitializer$Companion

	at android.support.v17.leanback.widget.LeanbackInitializer$Companion.<init>(LeanbackInitializer.kt)
	at android.support.v17.leanback.widget.LeanbackInitializer.__staticInitializer__(LeanbackInitializer.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:314)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
	at android.support.v17.leanback.widget.LeanbackInitializer.<clinit>(LeanbackInitializer.kt)
	at com.infomir.magicfiles.app.ProvidesModule.provideLeanbackInitializer(ProvidesModule.java:46)
	at com.infomir.magicfiles.app.ProvidesModule_ProvideLeanbackInitializerFactory.proxyProvideLeanbackInitializer(ProvidesModule_ProvideLeanbackInitializerFactory.java:31)
	at com.infomir.magicfiles.app.ProvidesModule_ProvideLeanbackInitializerFactory.provideInstance(ProvidesModule_ProvideLeanbackInitializerFactory.java:22)
	at com.infomir.magicfiles.app.ProvidesModule_ProvideLeanbackInitializerFactory.get(ProvidesModule_ProvideLeanbackInitializerFactory.java:18)
	at com.infomir.magicfiles.app.ProvidesModule_ProvideLeanbackInitializerFactory.get(ProvidesModule_ProvideLeanbackInitializerFactory.java:8)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.infomir.magicfiles.app.Initialization_Factory.provideInstance(Initialization_Factory.java:29)
	at com.infomir.magicfiles.app.Initialization_Factory.get(Initialization_Factory.java:23)
	at com.infomir.magicfiles.app.Initialization_Factory.get(Initialization_Factory.java:9)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at com.infomir.magicfiles.app.DaggerAppComponent.injectApp(DaggerAppComponent.java:432)
	at com.infomir.magicfiles.app.DaggerAppComponent.inject(DaggerAppComponent.java:415)
	at com.infomir.magicfiles.app.DaggerAppComponent.inject(DaggerAppComponent.java:104)
	at dagger.android.DaggerApplication.injectIfNecessary(DaggerApplication.java:78)
	at dagger.android.DaggerApplication.onCreate(DaggerApplication.java:53)
	at com.infomir.magicfiles.app.App.onCreate(App.java:53)
	at org.robolectric.android.internal.ParallelUniverse.lambda$setUpApplicationState$0(ParallelUniverse.java:260)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:260)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitForkedStarter.main(JUnitForkedStarter.java:41)
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class android.support.v17.leanback.widget.LeanbackInitializer$Companion
	... 45 more
```

`LeanbackInitializer` is my class in this case, but it was written on `kotlin` and with `companion object` in it. I decompiled it to `java` and see the next code in the `LeanbackInitializer` class:
```
@Metadata(
      mv = {1, 1, 13},
      bv = {1, 0, 3},
      k = 1,
      d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0000\n\u0002\u0010\u000b\n\u0000\b\u0086\u0003\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002R\u000e\u0010\u0003\u001a\u00020\u0004X\u0082T¢\u0006\u0002\n\u0000R\u000e\u0010\u0005\u001a\u00020\u0006X\u0082\u000e¢\u0006\u0002\n\u0000¨\u0006\u0007"},
      d2 = {"Landroid/support/v17/leanback/widget/LeanbackInitializer$Companion;", "", "()V", "LIBRARY_NAME", "", "sLibraryLoaded", "", "security_mag425ResourcesDebug"}
   )
   public static final class Companion {
      private Companion() {
      }

      // $FF: synthetic method
      public Companion(DefaultConstructorMarker $constructor_marker) {
         this();
      }
   }
```
As You can see, there is a `DefaultConstructorMarker ` class in `Companion` constructor, but it is private in kotlin and can not be used directly (it is generated by `kotlin` framework). How I can avoid this problem without much code change? Thanks in advance.
### Steps to Reproduce

1. Create any code on `kotlin` with any `comapnion object` with `init` block
2. Write any tests that uses this object in `java`
3. The error occures

### Robolectric & Android Version

Robolectric version: 4.0.2
Android Version: 28 (9.0)

**Comment by personshelldon** [comment]
I found the problem. In my case it was this block in gradle:
```
testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
```
After I removed it - everething works fine.

**Comment by roccadev** [comment]
I encountered the same problem but the solution (better call it a workaround) proposed in the above comment doesn't change anything for me. In my case it's androidx.room.CoroutinesRoom$Companion.<init> that throws the exception.
It happens with Roboelectric 4.0.2, 4.1 and 4.2-alpha-2. The latter prints a slightly different stacktrace but it's the same exception:
```
java.lang.ExceptionInInitializerError
	at com.app.model.room.MyDao_Impl.insertIgnoreConflict(ChatDao_Impl.java:190)
	at com.app.RoboElectricTest$room$1.invokeSuspend(RoboElectricTest.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.app.RoboElectricTest.room(RoboElectricTest.kt:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:81)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:154)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at androidx.room.CoroutinesRoom.<clinit>(CoroutinesRoom.kt)
	... 27 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	... 29 more
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.room.CoroutinesRoom$Companion
	at androidx.room.CoroutinesRoom$Companion.<init>(CoroutinesRoom.kt)
	at androidx.room.CoroutinesRoom.__staticInitializer__(CoroutinesRoom.kt)
	... 35 more
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.room.CoroutinesRoom$Companion
	... 37 more
```

**Comment by xian** [comment]
I created the following project which seems to work fine:
```kotlin
@RunWith(RobolectricTestRunner::class)
class ExampleUnitTest {
    @Test
    fun testMainActivity() {
        Robolectric.setupActivity(MainActivity::class.java)
    }
}

class MainActivity : AppCompatActivity() {
    companion object {
        val foo = "foo"

        init { println("initialized!") }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        println(foo)
    }
}
```

Am I missing something? Can you point me at a git repo that exhibits the problem?

**Comment by johnfrey99** [comment]
> I encountered the same problem but the solution (better call it a workaround) proposed in the above comment doesn't change anything for me. In my case it's androidx.room.CoroutinesRoom$Companion. that throws the exception.
> It happens with Roboelectric 4.0.2, 4.1 and 4.2-alpha-2. The latter prints a slightly different stacktrace but it's the same exception:
> 
> ```
> java.lang.ExceptionInInitializerError
> 	at com.app.model.room.MyDao_Impl.insertIgnoreConflict(ChatDao_Impl.java:190)
> 	at com.app.RoboElectricTest$room$1.invokeSuspend(RoboElectricTest.kt:43)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
> 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
> 	at com.app.RoboElectricTest.room(RoboElectricTest.kt:39)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
> 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:81)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> 	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:154)
> 	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
> 	at androidx.room.CoroutinesRoom.<clinit>(CoroutinesRoom.kt)
> 	... 27 more
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
> 	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
> 	... 29 more
> Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.room.CoroutinesRoom$Companion
> 	at androidx.room.CoroutinesRoom$Companion.<init>(CoroutinesRoom.kt)
> 	at androidx.room.CoroutinesRoom.__staticInitializer__(CoroutinesRoom.kt)
> 	... 35 more
> Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.room.CoroutinesRoom$Companion
> 	... 37 more
> ```

I''m having the same exact issue. Seems to be with using the new coroutine support with room. 

https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5

**Comment by xian** [comment]
A git repo with a project demonstrating the problem would be super helpful.

**Comment by roccadev** [comment]
Reproducing it is as simple as adding a suspend function in a Dao, which is supported in Room 2.1.0-alpha04.
Here's a repo. Just run ExampleUnitTest to check the error.
https://github.com/roccadev/RoboelectricRoomError

**Comment by xian** [comment]
Likely related: https://youtrack.jetbrains.com/issue/KT-20869

**Comment by mattmckeon** [comment]
> I encountered the same problem but the solution (better call it a workaround) proposed in the above comment doesn't change anything for me. In my case it's androidx.room.CoroutinesRoom$Companion. that throws the exception.

Here's this issue in Room's issuetracker: https://issuetracker.google.com/issues/124781244

It does seem like an issue with Robolectric though.

**Comment by virco** [comment]
Looks like there is at least one more `@RestrictTo` annotation in Room Coroutines that we need to watch out for, I'm not sure how to find a complete list other than searching through the source.

The annotated class is `androidx.room.TransactionElement`
annotated with `@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)`

This one was found in RoomDatabase.kt looks like they are extension functions from
`androidx.room:room-ktx:2.1.0-alpha06`

Error Log:
```
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	... 34 more
Caused by: java.lang.IllegalAccessError: failed to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.room.TransactionElement$Key (kotlin.jvm.internal.DefaultConstructorMarker is in unnamed module of loader 'app'; androidx.room.TransactionElement$Key is in unnamed module of loader org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader @3d5c822d)
	at androidx.room.TransactionElement$Key.<init>(RoomDatabase.kt)
	at androidx.room.TransactionElement.__staticInitializer__(RoomDatabase.kt)
	... 40 more
```

**Comment by BenTilbrook** [comment]
I'm getting the same issue with Robolectric `4.5-alpha-1` with the AndroidX DataStore lib:

```
java.lang.ExceptionInInitializerError
	at androidx.datastore.DataStoreFactory.create(DataStoreFactory.kt:64)
	at androidx.datastore.DataStoreFactoryKt.createDataStore(DataStoreFactory.kt:91)
	at androidx.datastore.DataStoreFactoryKt.createDataStore$default(DataStoreFactory.kt:89)
	...
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:166)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at androidx.datastore.DataMigrationInitializer.<clinit>(DataMigrationInitializer.kt)
	at androidx.datastore.DataStoreFactory.$$robo$$androidx_datastore_DataStoreFactory$create(DataStoreFactory.kt:64)
	at androidx.datastore.DataStoreFactory.create(DataStoreFactory.kt)
	at androidx.datastore.DataStoreFactoryKt.$$robo$$androidx_datastore_DataStoreFactoryKt$createDataStore(DataStoreFactory.kt:91)
	at androidx.datastore.DataStoreFactoryKt.createDataStore(DataStoreFactory.kt)
	at androidx.datastore.DataStoreFactoryKt.createDataStore$default(DataStoreFactory.kt:89)
	...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:163)
	... 24 more
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.datastore.DataMigrationInitializer$Companion
	at androidx.datastore.DataMigrationInitializer$Companion.<init>(DataMigrationInitializer.kt)
	at androidx.datastore.DataMigrationInitializer.__staticInitializer__(DataMigrationInitializer.kt)
	... 30 more
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.datastore.DataMigrationInitializer$Companion
	... 32 more
```

**Comment by hoisie** [comment]
BenTilbrook@ can you put up a small Android project on Github that demonstrates the issue?

**Comment by BenTilbrook** [comment]
Sure. Here's one:

https://github.com/BenTilbrook/RoboIllegalAccessBug

**Comment by BenTilbrook** [comment]
@hoisie Is there any way I can exclude the `androidx.datastore` package from instrumentation somehow? Is there an escape hatch for this kind of thing? It's currently blocking our use of DataStore entirely.

**Comment by hoisie** [comment]
I believe you are looking for https://github.com/robolectric/robolectric/blob/master/sandbox/src/main/java/org/robolectric/JarInstrumentor.java. There is also https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java, but I believe that is for Android framework jars.

**Comment by BenTilbrook** [comment]
Thank you. Do you have any pointers on how to get started with these? I've spent some time already attempting to configure exclusions by providing a custom test runner, without success.

**Comment by hoisie** [comment]
Looks like similar exclusions for other androidx classes are here (e.g. androidx.room):

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java#L123

As far as I know it's not possible to customize these.

**Comment by hoisie** [comment]
Looks like this line may do the trick:

```diff
diff --git a/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java b/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java
index baef26285..85db1c66e 100644
--- a/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java
+++ b/robolectric/src/main/java/org/robolectric/internal/AndroidConfigurer.java
@@ -126,6 +126,7 @@ public class AndroidConfigurer {
     builder.doNotInstrumentPackage("androidx.lifecycle");
     builder.doNotInstrumentPackage("androidx.paging");
     builder.doNotInstrumentPackage("androidx.work");
+    builder.doNotInstrumentPackage("androidx.datastore");

     // exclude Compose libraries from instrumentation. These are written in Kotlin and
     // fail on any usage due to DefaultConstructorMarker being inaccessible.
```

You want to add that and send a PR? We want more people to get familiar with the PR process :)

**Comment by BenTilbrook** [comment]
Submitted #5987

**Comment by hoisie** [comment]
For future reference it looks like you can also override RobolectricTestRunner to add some additional logic to AndroidConfigurer:

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L157-L165
