### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.robolectric.internal.bytecode.RobolectricInternals

### ISSUE THREAD

**Issue by Ebirux** [robolectric/robolectric#4484]
### Description
```java
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.robolectric.internal.bytecode.RobolectricInternals

	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:23)
	at org.robolectric.internal.bytecode.Sandbox.configure(Sandbox.java:50)
	at org.robolectric.internal.SandboxTestRunner.configureShadows(SandboxTestRunner.java:205)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:223)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
Caused by: java.lang.ClassNotFoundException: org.robolectric.internal.bytecode.RobolectricInternals
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:154)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:114)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:107)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:21)`
```

Anyone familiar with the above stacktrace?

### Steps to Reproduce
Just running unit tests. This repo is old and currently trying to upgrade it

### Robolectric & Android Version
Robo: 3.8
Android: 28

**Comment by xian** [comment]
That's a new one for me. If you can point me at a repo that demonstrates the problem I can try to diagnose, give me a git url and reopen this issue. Thanks!

**Comment by PrzemekMaterna** [comment]
Same here. Active repo, after upgrade to Android Studio 3.3 (only change I made in project before fail) tests stopped work (I guess it was the reason). I downgrade to Android Studio 3.2 - didn't help. Still the same error. Any solution?

**Comment by dhabensky** [comment]
Same here.
Android studio 3.4 beta 2
Tested on Robolectric 3.7 and 3.8
Works fine on Robolectric 4.2
