### ISSUE TITLE
org.junit.runners.model.InitializationError

### ISSUE THREAD

**Issue by GorkemKarayel** [robolectric/robolectric#4533]
when I add gradle Robolectric version 4.1 ; I get the following error.
  
java.lang.RuntimeException: org.junit.runners.model.InitializationError

	at org.robolectric.RobolectricTestRunner.getHelperTestRunner(RobolectricTestRunner.java:423)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:237)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.junit.runners.model.InitializationError
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:418)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.<init>(SandboxTestRunner.java:313)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.<init>(RobolectricTestRunner.java:581)
	at org.robolectric.RobolectricTestRunner.getHelperTestRunner(RobolectricTestRunner.java:421)
	... 15 more

My simple test code ; 

@RunWith(RobolectricTestRunner::class)
class SplashTest {

    @Test
    fun addition_isCorrect() {
        val activity = Robolectric.setupActivity(SplashActivity::class.java)
        activity.tv_example.performClick()
        assertThat(activity.tv_example.text).isEqualTo("Click")
    }
}                                                                                                                                                                  

### Robolectric & Android Version

    implementation files('libs/dagger-compiler-2.18.jar')
    testCompile 'com.google.truth:truth:0.42'
    // Robelectric
    testİmplementation 'org.robolectric:robolectric:4.1'

   ext.kotlin_version = '1.3.11'
   gradle_version = 4_10.1
   Android Studio = 3.3

  and of course I added;
  android.enableUnitTestBinaryResources=true

     testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

**Comment by xian** [comment]
Is there any more to the stack trace or error messages than that? Or can you point me at a git repo that shows the problem?

**Comment by GorkemKarayel** [comment]
@xian thank you for answer but unfortunately I can't share repos url because company private code. :( however , when I open new projects running smoothly for local UnitTest or Integration Test. 

I think check all; 
https://user-images.githubusercontent.com/17555866/51586429-3f073f00-1eee-11e9-8dfa-f34b5313b2f4.png

**Comment by GorkemKarayel** [comment]
thank you for information. I've prepared a simple class to show you the example. 

@RunWith(RobolectricTestRunner::class)
```
class SplashTest {
  lateinit  var activity : SplashActivity
    @Before
    public  fun setUp(){
        activity = Robolectric.setupActivity(SplashActivity::class.java)
    }@Test
    public fun testActivityNotNull(){
        assertThat(activity).isNotNull()
    }
}
```
when I put the breakpoint to ParentRunner.java:418; return 2 errors ; 
`
Method $$robo$$android_example_apps_customerapp_ui_SplashTest$setUp() should be public
Method $$robo$$android_example_apps_customerapp_ui_SplashTest$testActivityNotNull() should be public`

**Comment by xian** [comment]
Maybe `SplashTest` needs to be public?

**Comment by johnchangviki** [comment]
I also run into this issue.

> testImplementation 'junit:junit:4.12'
> testImplementation "org.robolectric:robolectric:$robolectricVersion"
> testImplementation 'com.google.truth:truth:1.0'

I have no idea because there is happened on one module but other is okay.

**Comment by johnchangviki** [comment]
I got the reason and workaround from https://github.com/robolectric/robolectric/issues/3208
