### ISSUE TITLE
Couldn't create lock file ?/.robolectric-download-lock

### ISSUE THREAD

**Issue by neworld** [robolectric/robolectric#4534]
### Description

This error happens only on CI with multiple SDK target and the following settings:
docker image: openjdk:8u181-jdk-slim
HOME: /tmp/home
Robolectric: 4.1
default SDK: 28

StackTrace:
```
java.lang.IllegalStateException: Couldn't create lock file ?/.robolectric-download-lock
	at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:96)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:72)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:39)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrl(MavenDependencyResolver.java:104)
	at org.robolectric.internal.dependency.CachedDependencyResolver.getLocalArtifactUrl(CachedDependencyResolver.java:44)
	at org.robolectric.internal.dependency.DependencyResolver.getLocalArtifactUrls(DependencyResolver.java:9)
	at org.robolectric.internal.SandboxFactory.getSdkEnvironment(SandboxFactory.java:38)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:338)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:65)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:225)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: ?/.robolectric-download-lock (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:89)
	... 46 more
```

### Steps to Reproduce

Create docker image, with following docker file:
```
FROM openjdk:8u181-jdk-slim

ENV ANDROID_HOME=/opt/android-sdk
ENV NPM_DIR /.npm
ENV ANDROID_DIR /.android
ENV HOME /tmp/home

RUN apt-get update \
    && apt-get install --yes bash wget git unzip curl

RUN mkdir $NPM_DIR && chmod 777 $NPM_DIR \
    && mkdir $ANDROID_DIR && chmod 777 $ANDROID_DIR \
    && mkdir $HOME && chmod 777 $HOME

#Releases https://dl.google.com/android/repository/repository2-1.xml
RUN SDK_BUILD="4333796" SDK_CHECKSUM="8c7c28554a32318461802c1291d76fccfafde054" \
    && wget -q https://dl.google.com/android/repository/sdk-tools-linux-"$SDK_BUILD".zip \
    && echo "$SDK_CHECKSUM *sdk-tools-linux-$SDK_BUILD.zip" | sha1sum -c - \
    && mkdir /opt || true \
    && unzip -qq sdk-tools-linux-"$SDK_BUILD".zip -d /opt/android-sdk \
    && rm sdk-tools-linux-"$SDK_BUILD".zip \
    && yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses \
    && yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3" \
    && chmod -R 777 $ANDROID_HOME
```
You must run with non-root user, like:
```
docker build -t android:latest .
docker run -it --rm -w /opt/build -u=`id -u`:`id -g` -v `pwd`:/opt/build:rw android:latest bash
./gradlew build
```

There is good you will get a failure without any additional tests. 

Have a test:
```
@RunWith(RobolectricTestRunner::class)
class LockFailsTest {
  @Test 
  fun alwaysSuccess() {
     //do nothing
  }

  @Test
  @Config(sdk = [Config.OLDEST_SDK, Config.NEWEST_SDK, Config.TARGET_SDK])
  fun alwaysFails() {
     //do nothing
  }
}
```

`TARGET_SDK` never fails, but the other two fails always. I don't know how internals is working, but to me it seems like target is running on main runner, but other SDK is running on the child. And child do not have proper `System.getProperty("user.home") == "?"`

**Comment by neworld** [comment]
For example file path of lock file:
```
File: ?/.robolectric-download-lock
File absolute: /var/lib/jenkins/workspace/android_PR-11943-HKKNYPHTELUL4KS7XRCAAEFGLRDPE2JPCWPS6243OKQT4JIF7OMA/application/?/.robolectric-download-lock
```

While home directory is /tmp/home and other tests points to `/tmp/home/.robolectric-download-lock`

**Comment by xian** [comment]
Is that a literal question mark, or are you replacing the actual path?

Your `System.getProperty("user.home")` needs to point at an existing, writable directory.

**Comment by neworld** [comment]
what question mark is literally path coming from `System.getProperty("user.home")`, and it happens only for tests running inside docker and with different SDK. 

```
@RunWith(RobolectricTestRunner::class)
class LockFailsTest {
  @Test 
  fun alwaysSuccess() {
     System.getProperty("user.home") == "/tmp/home"
  }

  @Test
  @Config(sdk = [Config.OLDEST_SDK, Config.NEWEST_SDK, Config.TARGET_SDK])
  fun alwaysFails() {
     System.getProperty("user.home") == "?" or sometimes "/tmp/home"
  }
}
```

**Comment by neworld** [comment]
BTW, I have stable reproduction only in CI. I could put any `System.out` in that test and print any info which helps you. Let me know if you need something

**Comment by xian** [comment]
Sounds like you're running into this: https://stackoverflow.com/questions/1503284/java-system-getpropertyuser-home-returns

Please reopen if that doesn't help. :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by neworld** [comment]
Strange, but suggested solution actually works. If somebody else gets the same issue, there is a fix:
```
    testOptions {
        unitTests.all {
            systemProperty 'user.home', System.getenv('HOME')
        }
    }
```
