### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by YoursBoss** [robolectric/robolectric#4567]
using testImplementation 'org.robolectric:robolectric:4.2-alpha-1' and report err:

java.lang.IllegalArgumentException: URI is not hierarchical

	at sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:122)
	at sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:92)
	at java.nio.file.Paths.get(Paths.java:138)
	at org.robolectric.util.Util.pathFrom(Util.java:98)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:120)
	at org.robolectric.internal.SandboxFactory.getSdkEnvironment(SandboxFactory.java:52)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:299)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:66)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:201)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:81)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

**Comment by christopherfrieler** [comment]
Just ran into the same issue after updating robolectric to 4.2.

After some analysis with the debugger I found out, that a URL object loaded from a local file-system cache contained a URL of the form "file:C:\some\path", i.e. it was missing the triple slash between scheme and path. Hence the URL could not be converted into a URI (original exception as described above).

Deleting the file on my machine solved the problem for me. It was located in C:\Users\<me>\AppData\Local\Temp\robolectric-2.

**Comment by sevar83** [comment]
Just upgraded from 4.1 to 4.2 and got this.

**Comment by alixwar** [comment]
I also ran into this after upgrading from 4.1 to 4.2 (seen on Windows only)

```
java.lang.IllegalArgumentException: URI is not hierarchical

	at sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:122)
	at sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:92)
	at java.nio.file.Paths.get(Paths.java:138)
	at org.robolectric.util.Util.pathFrom(Util.java:98)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:120)
	at org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader.<init>(AndroidSandbox.java:97)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.resolveDependencies(Injector.java:284)
	at org.robolectric.util.inject.Injector.inject(Injector.java:237)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:85)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:552)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:535)
	at com.sun.proxy.$Proxy11.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:53)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:62)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:219)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ParaskP7** [comment]
Same for me ☹

Deleting the file mentioned above solved the problem: `C:\Users\<me>\AppData\Local\Temp\robolectric-2.` 😊

**Comment by xian** [comment]
This should be fixed in 4.2.1: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.2.1

Please reopen if not. Thanks!

**Comment by vladad** [comment]
I updated version from 4.1 to 4.2.1 and I have this error during continuous integration build.
Maybe it is because mentioned Temp folder is shared with other builds with older Robolectric versions?

**Comment by xian** [comment]
Does it work when you delete the temp file? `C:\Users\<me>\AppData\Local\Temp\robolectric-2`

**Comment by vladad** [comment]
Yes, but only temporary. Until next build with previous Robolectric version.

I had to downgrade to 4.1.

**Comment by DanFTRX** [comment]
I am getting this on upgrading from 4.1 to 4.3
