### ISSUE TITLE
CNFE on 4.2-alpha-2

### ISSUE THREAD

**Issue by edenman** [robolectric/robolectric#4593]
### Stacktrace
```
org.robolectric.util.inject.InjectionException: org.robolectric.internal.SandboxFactory: failed to inject Key<class org.robolectric.plugins.SdkCollection> param

	at org.robolectric.util.inject.Injector.inject(Injector.java:258)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:206)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:458)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:198)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:189)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:106)
...
Caused by: org.robolectric.util.inject.InjectionException: org.robolectric.plugins.SdkCollection: failed to inject Key<interface org.robolectric.pluginapi.SdkProvider> param
...
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.robolectric.plugins.CachedMavenDependencyResolver
	at org.robolectric.util.ReflectionHelpers.loadClass(ReflectionHelpers.java:344)
	at org.robolectric.LegacyDependencyResolver.<init>(LegacyDependencyResolver.java:56)
```

### Robolectric & Android Version
Robolectric 4.2-alpha-2
Kotlin 1.3.11
androidx.test 1.1.0
AGP 3.5.0-alpha03, AS 3.5 Canary 3
jdk 1.8.0_201

### Link to a public git repo demonstrating the problem:
Let me know if this is necessary and I'll try to make one.

**Comment by edenman** [comment]
Yeah we're not doing anything crazy, normal Gradle dependency listing:

```
  testImplementation "junit:junit:$junit_version"
  testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
  testImplementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
  testImplementation "com.nhaarman:mockito-kotlin:1.6.0"
  testImplementation "org.robolectric:robolectric:$robolectric_version"
  testImplementation "net.wuerl.kotlin:assertj-core-kotlin:$assertj_version"
  testImplementation "androidx.test:core:$androidx_test_version"
```

with these versions:
```
  ext.androidx_test_version = '1.1.0'
  ext.assertj_version = '0.2.1'
  ext.kotlin_version = '1.3.11'
  ext.junit_version = '4.12'
  ext.robolectric_version = '4.1'
```

**Comment by edenman** [comment]
(obviously robolectric was 4.2-alpha-2, i rolled back to 4.1)

**Comment by edenman** [comment]
Oh, super fun: these tests pass on the command line, fail in AS.

**Comment by xian** [comment]
Ah, ok, I bet that's because I declared it as an `implementation` dependency instead of `api`, and the gradle/AS module setup stuff is kinda janky. New build coming soon. :-)

**Comment by xian** [comment]
@edenman — https://issuetracker.corp.google.com/issues/123899777

Maybe stick with 3.4 for now? :-)

**Comment by kingargyle** [comment]
@xian unfortunately the link above is an internal issue tracker... any similar issue on the external tracker?

**Comment by edenman** [comment]
@kingargyle in this case you can just remove the “.corp” (dunno if that always works)

**Comment by kingargyle** [comment]
For others, https://issuetracker.google.com/issues/123899777
