### ISSUE TITLE
Robolectric fails with "Illegal char <:> at index 2" on Windows

### ISSUE THREAD

**Issue by hungvietnguyen** [robolectric/robolectric#4603]
(Originally reported at https://issuetracker.google.com/120098460.) 

When running our Android Gradle plugin tests on Windows, we found that Robolectric 4.1 failed with the following stack trace:

```
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/gavra/android-tests/runUnitTese3f8a969a37ef6500582f805697c00bf999d9ee2/unitTestingAndroidResources/build/intermediates/sourceFolderJavaResources/test/debug/../../../../../robolectric-libs/android-all-7.0.0_r1-robolectric-r1.jar
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.robolectric.res.android.CppAssetManager.getFileModDate(CppAssetManager.java:1755)
	at org.robolectric.res.android.CppAssetManager.access$000(CppAssetManager.java:38)
	at org.robolectric.res.android.CppAssetManager$SharedZip.get(CppAssetManager.java:1507)
	at org.robolectric.res.android.CppAssetManager$SharedZip.get(CppAssetManager.java:1502)
	at org.robolectric.res.android.CppAssetManager$ZipSet.getZipResourceTable(CppAssetManager.java:1680)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable_measured(CppAssetManager.java:618)
	at org.robolectric.res.android.CppAssetManager.lambda$appendPathToResTable$0(CppAssetManager.java:572)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable(CppAssetManager.java:570)
	at org.robolectric.res.android.CppAssetManager.lambda$getResTable$1(CppAssetManager.java:711)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:72)
	at org.robolectric.res.android.CppAssetManager.getResTable(CppAssetManager.java:704)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:812)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:808)
	at org.robolectric.shadows.ShadowArscAssetManager.getStringBlockCount(ShadowArscAssetManager.java:1314)
	at android.content.res.AssetManager.getStringBlockCount(AssetManager.java)
	at android.content.res.AssetManager.makeStringBlocks(AssetManager.java:291)
	at android.content.res.AssetManager.ensureSystemAssets(AssetManager.java:109)
	at android.content.res.AssetManager.__constructor__(AssetManager.java:101)
	at android.content.res.AssetManager.<init>(AssetManager.java)
	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1309)
```

This appears to be an issue in Robolectric: The SDK jar path should contain `\` instead of `/`. I've traced the incorrect path to this line: https://github.com/robolectric/robolectric/blob/d7c10e6ae373334b1b37f5b8539ee11585dbf072/robolectric/src/main/java/org/robolectric/android/internal/AndroidEnvironment.java#L103

### Additional Request
Because Robolectric seems to fail on basic cases on Windows (see also https://github.com/robolectric/robolectric/issues/3955), it would be great if Robolectric was tested on Windows.

**Comment by xian** [comment]
@hungvietnguyen — can you point me at the AGP test that's failing?

**Comment by hungvietnguyen** [comment]
It's UnitTestingAndroidResourcesTest: https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/integration-test/application/src/test/java/com/android/build/gradle/integration/testing/unit/UnitTestingAndroidResourcesTest.java#143

Note that we currently have to disable that test on Windows.

**Comment by xian** [comment]
Not convinced this is fixed, I'll repro tomorrow.

**Comment by xian** [comment]
Hey @hungvietnguyen — could you try changing the Robolectric version to `4.2-beta-1` and check if it still fails? https://cs.corp.google.com/android/tools/base/build-system/integration-test/test-projects/unitTestingAndroidResources/build.gradle?l=49

**Comment by AmrAfifiy** [comment]
Hey @xian, I'm Amr from the AGP team. I've upgraded our robolectric version to 4.2-rc1 and the test is now failing on linux. Here is the exception:

```
java.lang.IllegalArgumentException: Path is not a file: ./android-all-7.0.0_r1-robolectric-r1.jar
	at org.robolectric.internal.dependency.LocalDependencyResolver.validateFile(LocalDependencyResolver.java:42)
	at org.robolectric.internal.dependency.LocalDependencyResolver.getLocalArtifactUrl(LocalDependencyResolver.java:30)
	at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:86)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:119)
	at org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader.<init>(AndroidSandbox.java:97)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.resolveDependencies(Injector.java:284)
	at org.robolectric.util.inject.Injector.inject(Injector.java:237)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:85)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:552)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:535)
	at com.sun.proxy.$Proxy16.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:53)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:62)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:219)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by smaugho** [comment]
Having some issue here `Illegal character in opaque part at index 2: C:\Users\`

**Comment by xian** [comment]
@smaugho — is that using 4.2 or 4.2.1-rc1?

```groovy
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/orgrobolectric-1198"
    }
    ...
}

dependencies {
    testImplementation "org.robolectric:robolectric:4.2.1-rc1"
}
```

**Comment by xian** [comment]
Confirmed fixed in 4.2.1 (release forthcoming).

**Comment by xian** [comment]
4.2.1 is released: https://github.com/robolectric/robolectric/releases/tag/robolectric-4.2.1

**Comment by devlee-team** [comment]
Still happens with version 4.2.1

```
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:packageFullHelpDebugUnitTestForUnitTest'.
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Illegal character in opaque part at index 11: jar:file:C:\Users\User\AndroidStudioProjects\project-android\app\build\interme
diates\apk_for_local_test\fullTheyDebugUnitTest\packageFullImprisonDebugUnitTestForUnitTest\apk-for-local-test.ap_
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.967 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:packageFullMeDebugUnitTestForUnitTest'.
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.jav
a:51)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter
.java:54)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExec
uter.java:44)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
14:16:31.968 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.j
ava:62)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecut
or.java:336)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecut
or.java:328)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
14:16:31.969 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: Illegal character in opaque part at index 11: jar:file:C:\Users\User\AndroidStudi
oProjects\project-android\app\build\intermediates\apk_for_local_test\fullInDebugUnitTest\packageFullTheDebugUnitTestForUnitTest\apk-for-local-test.ap_
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.android.build.gradle.internal.tasks.PackageForUnitTest.generateApkForUnitTest(PackageForUnitTest.java:58)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
14:16:31.970 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:788)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:755)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecut
or.java:336)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecut
or.java:328)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 30 more
14:16:31.971 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 11: jar:file:C:\Users\User\AndroidStudioProjec
ts\project-android\app\build\intermediates\apk_for_local_test\fullBasementDebugUnitTest\packageFullHelpDebugUnitTestForUnitTest\apk-for-local-test.ap_
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 44 more
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
14:16:31.972 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 17s

```
