### ISSUE TITLE
Robolectric 4.2 breaks SQLite tests

### ISSUE THREAD

**Issue by sum-elier** [robolectric/robolectric#4639]
### Description
After upgrading to Robolectric 4.2 from 4.1 I am unable to run my test over the database. One of the test tables contains an unique constraint over 2 columns. I keep getting the following error in between tests, where before there was none:

```
Caused by: com.almworks.sqlite4java.SQLiteException: [19] DB[39] step() [INSERT INTO my_table(start,middle,end) VALUES (?,?,?)]DB[39][C] [columns middle, start are not unique]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection$BaseController.throwResult(SQLiteConnection.java:1562)
	at com.almworks.sqlite4java.SQLiteStatement.stepResult(SQLiteStatement.java:1231)
	at com.almworks.sqlite4java.SQLiteStatement.step(SQLiteStatement.java:302)
	at com.almworks.sqlite4java.SQLiteStatement.stepThrough(SQLiteStatement.java:316)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$20.call(ShadowSQLiteConnection.java:670)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$20.call(ShadowSQLiteConnection.java:667)
	... 4 more
```

### Steps to Reproduce
Unsure. Each test is using `writableDatabase.insertOrThrow` to insert some initial test data used in the test.

It seems as the database isn't reset after each invocation of a test method such that old data isn't deleted.
### Robolectric & Android Version
Robolectic version: 4.2
Android SDK version: 28
Java 1.6

### Link to a public git repo demonstrating the problem:
N/A

**Comment by xian** [comment]
@fjna — can you give a little more background info: how is the database schema being created? is there code that explicitly deletes rows or drops tables in between tests?

Or, even better, could you provide a stripped down git repo that exhibits the problem?

**Comment by fjna** [comment]
Alright, I'll see if I can create a stripped down git repo for that
