### ISSUE TITLE
[Migration]Robolectric 4.0.2 test fail with ClassCastException

### ISSUE THREAD

**Issue by arjunkchr** [robolectric/robolectric#4646]
### Description
Running the test cases causes and exception:

    java.lang.ClassCastException: java.lang.Object cannot be cast to org.robolectric.shadows.ShadowLooper

	at org.robolectric.shadows.ShadowLooper.shadowOf(ShadowLooper.java:372)
	at org.robolectric.shadows.ShadowLooper.getShadowMainLooper(ShadowLooper.java:144)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:119)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

Any hints into what might be going wrong?

### Steps to Reproduce

1. Migrate from robolectric 3.4.2 to 4.0.2
2. Change API Level to 28.
3. Removing constants field from `@Config` since it is no longer available.
4. Change `addShadowClass` to `addShadowClasses`
5. After doing the changes manually, ran the migration script http://robolectric.org/automated-migration/ and no additional changes were seen.
6. The project is still not migrated to AndroidX

### Robolectric & Android Version
4.0.2

**Comment by xian** [comment]
Hey @arjunkchr — sounds like you have some local custom shadows? It's difficult to diagnose the issue without some info about those. Can you can include a git repo showing your customizations, or better yet, see if you can remove the custom shadows?

**Comment by arjunkchr** [comment]
Hi @xian : Does robolectric 4+ versions not support shadows? Our project includes other submodules, which has couple of native dependencies(like wrapper for Openssl) and that is the reason we created shadow classes for those. The same shadow classes work on robolectric 3.4.2 version. Thoughts?

**Comment by xian** [comment]
Robolectric 4 still supports custom shadows, it's just hard to diagnose what's going on without knowing what your local customizations are. It sounds like `ShadowLooper` isn't being registered for some reason (so `Looper`'s shadow is just an instance of `Object`, which can't be cast to `ShadowLooper`).

Do any of your custom shadows involve `Looper`?

**Comment by utzcoz** [comment]
Please try the latest Robolectric, and reopen this issue if this problem still exists. Thanks.
