### ISSUE TITLE
use setDataSource(FileDescriptor fd, long offset, long length) get error

### ISSUE THREAD

**Issue by iamupgirl** [robolectric/robolectric#4673]
error log

java.lang.IllegalArgumentException: Don't know what to do with dataSource org.robolectric.shadows.util.DataSource@44d79510 - either add an exception with addException() or media info with addMediaInfo()

	at org.robolectric.shadows.ShadowMediaPlayer.doSetDataSource(ShadowMediaPlayer.java:620)
	at org.robolectric.shadows.ShadowMediaPlayer.setDataSource(ShadowMediaPlayer.java:604)
	at org.robolectric.shadows.ShadowMediaPlayer.setDataSource(ShadowMediaPlayer.java:644)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java)

code content

my asserts folder have a .mp3 file,used code to get the file make sound,my code as follows:
public void startBell(String fileName){
		try {
			if (mp == null) {
				mp = new MediaPlayer();
			}
			if (!StringUtils.isEquals(this.fileName, fileName)) {
				mp.reset();
				AssetManager am = mContext.getAssets();
				AssetFileDescriptor afd = am.openFd(fileName);
				mp.setDataSource(afd.getFileDescriptor(),afd.getStartOffset(), afd.getLength());
				this.fileName = fileName;
				mp.prepare();
			}

		} catch (IOException e) {
			e.printStackTrace();
		}
		mp.start();
	}
Robolectric & Android Version

robolectric:3.8
Android Studio:3.0.1
sdk:1.8

**Comment by dmeng** [comment]
That is documented behavior in Robolectric 3.8

From the [doc](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html):

> **Note**: One gotcha with this shadow is that you need to either configure an exception or a ShadowMediaPlayer.MediaInfo instance for that data source (using [addException(DataSource, IOException) ](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#addException-org.robolectric.shadows.util.DataSource-java.io.IOException-) or [addMediaInfo(DataSource, MediaInfo)](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#addMediaInfo-org.robolectric.shadows.util.DataSource-org.robolectric.shadows.ShadowMediaPlayer.MediaInfo-) respectively) before calling [setDataSource(org.robolectric.shadows.util.DataSource)](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#setDataSource-org.robolectric.shadows.util.DataSource-), otherwise you’ll get an IllegalArgumentException.

Or are you requesting that Robolectric change the documented behavior in a future version?

**Comment by iamupgirl** [comment]
> That is documented behavior in Robolectric 3.8
> 
> From the [doc](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html):
> 
> > **Note**: One gotcha with this shadow is that you need to either configure an exception or a ShadowMediaPlayer.MediaInfo instance for that data source (using [addException(DataSource, IOException) ](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#addException-org.robolectric.shadows.util.DataSource-java.io.IOException-) or [addMediaInfo(DataSource, MediaInfo)](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#addMediaInfo-org.robolectric.shadows.util.DataSource-org.robolectric.shadows.ShadowMediaPlayer.MediaInfo-) respectively) before calling [setDataSource(org.robolectric.shadows.util.DataSource)](http://robolectric.org/javadoc/3.8/org/robolectric/shadows/ShadowMediaPlayer.html#setDataSource-org.robolectric.shadows.util.DataSource-), otherwise you’ll get an IllegalArgumentException.
> 
> Or are you requesting that Robolectric change the documented behavior in a future version?

MediaPlayer have not MediaInfo,how can I addException or addMediaInfo.

**Comment by dmeng** [comment]
@iamupgirl See the link in the earlier comment; addMediaInfo is a method inside ShadowMediaPlayer, not MediaPlayer

**Comment by bjenning04** [comment]
In case anyone else runs into this issue for dynamically loaded `DataSource`s (so have no access to it a unit test runtime) and don't care about the media info used in the actual test, the solution is to replace the default `MediaInfoProvider` with a custom one. Something like this.
```
ShadowMediaPlayer.setMediaInfoProvider(dataSource -> new ShadowMediaPlayer.MediaInfo(1, 0));
```
