### ISSUE TITLE
I am getting this error for every test run

### ISSUE THREAD

**Issue by vudzkostek** [robolectric/robolectric#4689]
### Description
It seems like it was failing in org.objectweb.asm.AnnotationVisitor constructor when checking ASM version. AnnotationNode created instance with Opcodes.ASM7 but AnnotationVisitor constructor  javadoc says it can only work with Opcodes#ASM4 and Opcodes#ASM5.

### Steps to Reproduce
Just run any unit test

### Robolectric & Android Version
minSdkVersion = 21
targetSdkVersion = 27
compileSdkVersion = 28
buildToolsVersion = '28.0.3'
robolectric   : '4.2'
shadows       : '3.4-rc2'
mockito       : '2.23.0'

compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}

Test dependencies:
testCore       : 'androidx.test:core:1.0.0',
fragmentTesting: 'androidx.fragment:fragment-testing:1.1.0-alpha02',
robolectric    : [
       robolectric        : "org.robolectric:robolectric:${deps.versions.robolectric}",
       shadowsHttpClient  : "org.robolectric:shadows-httpclient:${deps.versions.robolectric}",
       shadowsMultidex    : "org.robolectric:shadows-multidex:${deps.versions.robolectric}",
       shadowsPlayServices: "org.robolectric:shadows-play-services:${deps.versions.shadows}",
]

# STACKTRACE

java.lang.IllegalArgumentException
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.AnnotationVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:77)
	at org.objectweb.asm.tree.AnnotationNode.<init>(AnnotationNode.java:63)
	at org.objectweb.asm.tree.ClassNode.visitAnnotation(ClassNode.java:208)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.robolectric.internal.bytecode.ClassInstrumentor.analyzeClass(ClassInstrumentor.java:63)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$maybeInstrumentClass$1(SandboxClassLoader.java:122)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:121)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:112)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:111)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:41)
	at org.robolectric.internal.AndroidSandbox.<init>(AndroidSandbox.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:85)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:552)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:535)
	at com.sun.proxy.$Proxy9.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:53)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:62)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:219)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by vudzkostek** [comment]
Ok it seems that we had forced asm version in our dependency tree
