### ISSUE TITLE
NullPointerException in DefaultManifestFactory

### ISSUE THREAD

**Issue by janvr-at-q16** [robolectric/robolectric#4690]
### Description
When I run a test wit the following setup code, I get a NullPointerException

@RunWith(RobolectricTestRunner.class)
public class UserQuestionMapperTests {
    @BeforeClass
    public static void BeforeAll() {
        Configuration configuration = new Configuration.Builder(RuntimeEnvironment.application.getApplicationContext())
                .addModelClass(UserQuestion.class)
                .setDatabaseName(null)
                .create();

        ActiveAndroid.initialize(configuration);
    }

        ActiveAndroid.initialize(configuration);
}

I have the following in build.gradle

    testOptions {
        execution 'ANDROID_TEST_ORCHESTRATOR'
        unitTests {
            includeAndroidResources true
        }
    }

And the following in gradle.properties
android.enableUnitTestBinaryResources=true
android.enableAapt2=false

The stack trace is the following:
java.lang.NullPointerException
	at org.robolectric.internal.DefaultManifestFactory.getFsFileFromPath(DefaultManifestFactory.java:65)
	at org.robolectric.internal.DefaultManifestFactory.identify(DefaultManifestFactory.java:24)
	at org.robolectric.RobolectricTestRunner.getAppManifest(RobolectricTestRunner.java:431)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:255)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.filter(ParentRunner.java:379)
	at org.junit.runner.manipulation.Filter.apply(Filter.java:97)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:37)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70) 

When I debugged the code, I noticed that the "android_merged_resources" is not included in the list of properties:
https://github.com/robolectric/robolectric/blob/robolectric-3.7.x/robolectric/src/main/java/org/robolectric/internal/DefaultManifestFactory.java#L24

### Robolectric & Android Version
Using Roboelectic version 3.8, Android SDK 26

Any ideas what I might be doing wrong?

**Comment by jongerrish** [comment]
I don't think binary resources works with Robolectric 3.8, can you try with 4.2?

**Comment by janvr-at-q16** [comment]
Well, here's the thing. I first started out with the latest version. I noticed that RuntimeEnvironment.application.getApplicationContext() was deprecated and returned a null reference. 

Reading through the docs, I came across a page that mentioned using AndroidX in order to get to a fake context. Unfortunately, I'm not able to use AndroidX that because the app uses an earlier version of the Android SDK (and we're not able to upgrade that easily) for which AndroidX is not compatible. That's the reason why I downgraded to version 3.8 of Roboelectric.

I'm pretty new to Android development, and I would love to use Roboelectric for setting up automated tests (which are severely lacking in this app). Do you have any recommendations or a path that I could follow? Thanks in advance.

**Comment by asgarddesigns** [comment]
It looks to be due to the `com.android.tools.build:gradle` update. I faced the same issue and had to revert to `3.3.2` from `3.4.0-beta5`

**Comment by lprent** [comment]
It appears to be in gradle plugin 3.4.0 in android studio. After I upgraded to that I got the same error (see below). When I set the project to use gradle plugin 3.3.2 (using File > Project Structure > Project), the error disappeared on the specific I was using.

`java.lang.NullPointerException
	at org.robolectric.internal.DefaultManifestFactory.getFsFileFromPath(DefaultManifestFactory.java:65)
	at org.robolectric.internal.DefaultManifestFactory.identify(DefaultManifestFactory.java:24)
	at org.robolectric.RobolectricTestRunner.getAppManifest(RobolectricTestRunner.java:431)
	at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:255)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
	at com.intellij.junit4.JUnit4IdeaTestRunner.getDescription(JUnit4IdeaTestRunner.java:78)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
`

**Comment by jongerrish** [comment]
Try the latest version of Robolectric, I know there were some problems with
earlier versions especially on Windows for the integration with AGP.

**Comment by antonkazakov** [comment]
Hey guys, have the same issue with Robolectric 3.8 and build tools 3.5.1. For internal reasons we cannot switch to Robolectrics 4.3. Looks like explicitly adding `android.enableUnitTestBinaryResources=false` to gradle.properties file fixes this issue.

**Comment by HughIngram** [comment]
I am having this issue after upgrading android studio & build tools from 3.5.3 to 3.6.1

**Comment by ByunghooLim** [comment]
@HughIngram 
Hi. 
Did you solved this issue?
I'm also in trouble on build tools from 3.5.3 to 3.6.2

**Comment by HughIngram** [comment]
@ByunghooLim no, I had to ignore robolectric tests in the affected project module for now. Currently we are using Robolectric 3.8, so if we upgrade to 4.3 in the future hopefully this will fix it.
