### ISSUE TITLE
RuntimeException:  Method ___ not mocked

### ISSUE THREAD

**Issue by jahorton** [robolectric/robolectric#4740]
### Description
This is likely related to #4015, though we're using Robolectric 4.2 rather than 4.0.  An interesting wrinkle - this is only occurring on **one** of our development machines, despite our best efforts to duplicate our environmental setup to match that of unaffected machines.  In case it matters, this began occurring when updating from 3.8 to 4.2.  The specific PR is linked at the bottom; we're an open-source project.

Despite our best efforts to ensure an identical development environment, all test cases are failing on a single development machine.  There are no reported errors on the other machines, and the failure/success happens both in Android Studio and in command-line gradle builds.  First, a brief summary of the error logs for the affected machine:

```
[Robolectric] com.tavultesoft.kmea.packages.PackageProcessorTest.test_load_GFF_KMP_keyboards: sdk=28; resources=BINARY
java.lang.RuntimeException: Method clear in android.util.SparseArray not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.util.SparseArray.clear(SparseArray.java)
	at org.robolectric.shadows.ShadowAccessibilityNodeInfo.resetObtainedInstances(ShadowAccessibilityNodeInfo.java:280)
	at org.robolectric.Shadows.reset(Shadows.java:2058)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:333)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:329)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

java.lang.RuntimeException: Method getLocales in android.content.res.Configuration not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.content.res.Configuration.getLocales(Configuration.java)
	at org.robolectric.android.DeviceConfig.getLocale(DeviceConfig.java:397)
	at org.robolectric.android.DeviceConfig.applyRules(DeviceConfig.java:244)
	at org.robolectric.android.Bootstrap.applyQualifiers(Bootstrap.java:50)
	at org.robolectric.android.internal.AndroidEnvironment.setUpApplicationState(AndroidEnvironment.java:135)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:298)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Literally every test fails, producing one of the two (or possibly both) `RuntimeException`s listed above, each time with an identical call stack to the respective log above.  While the latter generated error matches that of #4015, the call stack differs.

### Steps to Reproduce

Unknown.

### Robolectric & Android Version

SDK:  28
Robolectric version: 4.2
Android Studio:  3.3.2

### Other environmental data

`android.testOptions.unitTests.includeAndroidResources = true`

gradle.properties:

```
android.enableJetifier=true
android.useAndroidX=true
android.enableUnitTestBinaryResources=true
```

All of the following are confirmed to be identical between the unaffected machines and the single affected one.

Windows 10 (latest update as of March 11, 2019)

Android SDK, for version 9.0
* Android SDK Platform 28, Revision 6
* Sources for Android 28, Revision 1
* Google APIs Intel x86 Atom System Image, Revision 8
* Google Play Intel x86 Atom System Image, Revision 8

Java version (for command-line builds): 1.8.0_201
Java version (Android Studio): "Use embedded JDK (recommended)"
* Studio's JRE is 1.8.0_152, according to its About dialog.

I've wiped and redownloaded both the Gradle cache and the SDK once each in case of a corrupted download.  All licenses accepted, etc.  I also reset Android Studio's settings on the affected machine before readjusting the points above to match those from an unaffected machine.

### Link to a public git repo demonstrating the problem:

I apologize for being unable to determine any sort of reproduction steps for the issue; I haven't gotten Robolectric to work for any tests so far with 4.2 on the affected machine.  As a result, I'll link the repo being utilized when this issue arose, though it's _definitely_ not a minimal reproduction:

https://github.com/keymanapp/keyman/ (see /android/KMEA subdirectory for the specific project)

In case it's helpful in any way, the following PR is when things broke on the affected development machine:  https://github.com/keymanapp/keyman/pull/1654/files

**Comment by jongerrish** [comment]
SparseArray.clear() was added in API level 1 so it should _always_ be loaded in the Robolectric Sandbox. The error we are seeing suggests that somehow the class was loaded from the system classloader since its executing the class definition from the mockable jar stubs.

**Comment by palrahul** [comment]
@jahorton ran into similar issue , was able to resolve it by deleting my local maven repository for robolectric. Have a feeling that somehow it got corrupted, I do remember that I was on a really spotty network connection when I saw it happen first, so maybe theres some correlation there.

**Comment by yongce** [comment]
Ran into the same issue. I fixed it by deleting the whole folder at ~/.m2/repository/org/robolectric/android-all/9-robolectric-4913185-2 .

**Comment by tangxiangpi** [comment]
me too, all thing is fine in win10 and mac machines, but failed on a win10 server machine , just the same as you ,what is the problem ?

**Comment by vidhithakrar** [comment]
I tried what @yongce mentioned above. But it did not solve the problem.

**Comment by vidhithakrar** [comment]
So in my case, due to slow network over VPN, was getting Checksum verification error and the whole android-all-9-robolectric-4913185-2.jar was not getting downloaded. 

After downloading the full jar separately, this problem got solved.

**Comment by rohit-337** [comment]
A previously failed repository download could result in this issue.
	•	Delete the existing roboelectric version in /home/user/.m2/repository/org/robolectric/android all.
	•	Re-run your tests (robolectric will be re-downloaded in the process).

**Comment by supermavericks** [comment]
rm -rf .m2/repository/org/robolectric.
I done it  then successful.
