### ISSUE TITLE
robolectric:processor release artifact's sdks.txt points to files in builder's home dir

### ISSUE THREAD

**Issue by xian** [robolectric/robolectric#4801]
Oops.

SDK refs should be calculated locally when the processor is used, not distributed with the processor.

**Comment by xian** [comment]
```java
java.lang.RuntimeException: java.lang.RuntimeException: failed to open SDK 0 at /usr/local/google/home/christianw/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-r1/android-all-4.1.2_r1-robolectric-r1.jar
    at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
    at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
    at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
    at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:113)
    at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:107)
    at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:67)
    at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:116)
    at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:123)
    at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
    at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
    at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.lang.RuntimeException: failed to open SDK 0 at /usr/local/google/home/christianw/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-r1/android-all-4.1.2_r1-robolectric-r1.jar
    at org.robolectric.annotation.processing.validator.SdkStore$Sdk.ensureJar(SdkStore.java:266)
    at org.robolectric.annotation.processing.validator.SdkStore$Sdk.<init>(SdkStore.java:127)
    at org.robolectric.annotation.processing.validator.SdkStore.loadFromSdksFile(SdkStore.java:93)
    at org.robolectric.annotation.processing.validator.SdkStore.loadSdksOnce(SdkStore.java:76)
    at org.robolectric.annotation.processing.validator.SdkStore.sdksMatching(SdkStore.java:46)
    at org.robolectric.annotation.processing.validator.ImplementsValidator.verifySdkMethod(ImplementsValidator.java:244)
    at org.robolectric.annotation.processing.validator.ImplementsValidator.validateShadowMethods(ImplementsValidator.java:217)
    at org.robolectric.annotation.processing.validator.ImplementsValidator.visitType(ImplementsValidator.java:158)
    at org.robolectric.annotation.processing.validator.Validator$1.visitType(Validator.java:41)
    at org.robolectric.annotation.processing.validator.Validator$1.visitType(Validator.java:32)
    at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:1432)
    at java.compiler@10.0.1/javax.lang.model.util.AbstractElementVisitor6.visit(AbstractElementVisitor6.java:92)
    at org.robolectric.annotation.processing.validator.Validator.visit(Validator.java:109)
    at org.robolectric.annotation.processing.RobolectricProcessor.process(RobolectricProcessor.java:92)
    at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
    at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
    at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
    at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
    at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
    at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
    at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
    at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
    at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
    ... 10 more
Caused by: java.nio.file.NoSuchFileException: /usr/local/google/home/christianw/.m2/repository/org/robolectric/android-all/4.1.2_r1-robolectric-r1/android-all-4.1.2_r1-robolectric-r1.jar
    at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
    at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
    at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
    at java.base/java.nio.file.Files.readAttributes(Unknown Source)
    at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
    at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile$CleanableResource.get(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
    at java.base/java.util.jar.JarFile.<init>(Unknown Source)
    at java.base/java.util.jar.JarFile.<init>(Unknown Source)
    at java.base/java.util.jar.JarFile.<init>(Unknown Source)
    at org.robolectric.annotation.processing.validator.SdkStore$Sdk.ensureJar(SdkStore.java:262)
    ... 32 more
INFO: Elapsed time: 22.057s, Critical Path: 21.17s
INFO: 3 processes: 3 local.
FAILED: Build did NOT complete successfully
```

**Comment by xian** [comment]
As a workaround, pass `-Aorg.robolectric.annotation.processing.sdkCheckMode=OFF` as a `javac` option.
