### ISSUE TITLE
When using robolectric-deps.properties, if the paths are incorrect Robolectric will not tell you that

### ISSUE THREAD

**Issue by menny** [robolectric/robolectric#4805]
### Description
I tried to setup Bazel to run Robolectric tests but kept getting failures due to `java.lang.NullPointerException: could not find build.prop` while robolectric was setting up:
```
1) testParcelableMarshallAndUnmarshallReturnsEqualObject(com.spotify.mobile.android.util.ParcelableUtilTest)
java.lang.ExceptionInInitializerError
    at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:105)
    at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
    at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:89)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
    at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:112)
    at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:153)
    at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:84)
Caused by: java.lang.NullPointerException: could not find build.prop
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:906)
    at org.robolectric.shadows.ShadowSystemProperties.loadProperties(ShadowSystemProperties.java:80)
    at org.robolectric.shadows.ShadowSystemProperties.getProperty(ShadowSystemProperties.java:71)
    at org.robolectric.shadows.ShadowSystemProperties.native_get_int(ShadowSystemProperties.java:30)
    at android.os.SystemProperties.native_get_int(SystemProperties.java)
    at android.os.SystemProperties.getInt(SystemProperties.java:133)
    at android.util.DisplayMetrics.getDeviceDensity(DisplayMetrics.java:376)
    at android.util.DisplayMetrics.__staticInitializer__(DisplayMetrics.java:175)
    at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:314)
    at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:56)
    at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
    at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:20)
    at android.util.DisplayMetrics.<clinit>(DisplayMetrics.java)
    ... 18 more
```

### Steps to Reproduce
Use `robolectric-offline` method, but make sure the paths in `robolectric-deps.properties` are incorrect.

I would also ask that the check will only be done when trying to load the required SDK jar, and not verify all paths exist before. That's because we provide just the required `android-all-XXX.jar` as dependency to the Bazel test target.

### Robolectric & Android Version
3.8-4.2

**Comment by jin** [comment]
> I would also ask that the check will only be done when trying to load the required SDK jar, and not verify all paths exist before. That's because we provide just the required android-all-XXX.jar as dependency to the Bazel test target.

I think this is a good idea. We do the props file generation from within android_local_test and feed that into Robolectric, instead of requiring the generated prop file as an input. This way, we can drop the dependency on https://github.com/robolectric/roboelectric-bazel altogether.
