### ISSUE TITLE
org.objectweb.asm.MethodVisitor – IllegalArgumentException

### ISSUE THREAD

**Issue by enginegl** [robolectric/robolectric#4916]
### Description
After global tooling update (com.android.tools.build:gradle:3.3.2->3.4.0 and gradle 4.10.2->5.1.1) my unit tests are crashing because of weird crash:

<img width="884" alt="stacktrace" src="https://user-images.githubusercontent.com/3976062/56507990-ba977d00-652b-11e9-8ab2-ce3d32d56dbe.png">

Even empty tests are failing:
<img width="941" alt="Screenshot" src="https://user-images.githubusercontent.com/3976062/56507918-8f149280-652b-11e9-9ffb-f9bb61a31c80.png">

I tried to clear the cache
`rm -rf ~/.m2/repository/org/robolectric/android-all`
but it doesn't work for me.
### Environment
Multi-module project.
Target SDK 28

sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8

Android Studio 3.4 (Stable)
com.android.tools.build:gradle 3.4.0
Kotlin 1.3.30
Robolectric 4.2.1

./gradlew -v output: 

Gradle 5.1.1
Kotlin DSL: 1.1.1
Kotlin: 1.3.11
Groovy:  2.5.4
Ant: Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM: 1.8.0_112 (Oracle Corporation 25.112-b16)
OS: Mac OS X 10.14.4 x86_64

**Comment by enginegl** [comment]
Full stacktrace:

> java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.objectweb.asm.commons.JSRInlinerAdapter.<init>(JSRInlinerAdapter.java:129)
	at org.objectweb.asm.commons.JSRInlinerAdapter.<init>(JSRInlinerAdapter.java:101)
	at org.robolectric.internal.bytecode.ClassInstrumentor$1.visitMethod(ClassInstrumentor.java:58)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.robolectric.internal.bytecode.ClassInstrumentor.analyzeClass(ClassInstrumentor.java:63)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$maybeInstrumentClass$1(SandboxClassLoader.java:122)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:121)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:112)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:111)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:41)
	at org.robolectric.internal.AndroidSandbox.<init>(AndroidSandbox.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:239)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:221)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:486)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:213)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:197)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:85)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:552)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:535)
	at com.sun.proxy.$Proxy14.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:53)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:263)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:62)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:219)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by adazh** [comment]
Could you check what version of ASM you have on your classpath and report back?

**Comment by enginegl** [comment]
@adazh it's 7.0

**Comment by enginegl** [comment]
I can see that this is robolectric's dependency from my project dependency tree

**Comment by adazh** [comment]
Cool, thanks! Might need to repro this locally, but one more question: have you ever got this working on Android Studio 3.4? Did you update your AS recently?

**Comment by enginegl** [comment]
Yes, but if I'll roll back my repo back to previous Gradle/Gradle plugin versions, Robolectric's tests are working again on AS 3.4. So there's a problem with Gradle versions that I've specified in my first message.

**Comment by enginegl** [comment]
I found the cause of this problem. I have another dependency that contains ASM classes with version less than 7.0 and it packaged as .jar. Seems like something changed with classpaths resolution in new gradle tools.

**Comment by jongerrish** [comment]
Mind posting your solution as an FYI to others that encounter the same issue?

**Comment by enginegl** [comment]
@jongerrish it's obvious, you just need to remove this classes from another library. Or update it's dependencies.
If you're using Android studio just press Cmd+O twice, type class name and look for results - it will show everything that you have.
