### ISSUE TITLE
ApplicationProvider.getApplicationContext().getPackageManager().getPackageArchiveInfo(ApplicationProvider.getApplicationContext().getPackageName(), 0) returns null on Android Gradle 3.4.0

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#4921]
### Description
A method now returns null when it returned a value on Android Gradle 3.3.2

### Steps to Reproduce
100% reproducible on Android Gradle 3.4.0. 0% reproducible on Android Gradle 3.3.2.
Note: There is no test manifest. Only the app manifest.
```
@Config(sdk = Build.VERSION_CODES.LOLLIPOP)
@RunWith(AndroidJUnit4.class)
public class FooTest {

    private Context context;

    @Before
    public void setUp() {
        context = ApplicationProvider.getApplicationContext();    }

    @Test
    public void TestFails() throws PackageManager.NameNotFoundException {
        assertThat(context.getPackageManager().getPackageInfo(context.getPackageName(), 0).versionName, notNullValue());
    }

}

```
### Robolectric Version
Robolectric 4.2.1

**Comment by cooltey** [comment]
Seeing the same issue when upgraded to Android Gradle 3.4.0

**Comment by Malachiasz** [comment]
The problem is because gradle plugin 3.4.0 changes package name returned by context.getPackageName() adds .test. According to the documentation it should happen in instrumented tests. Now it happens in unit tests as well:

> By default, the build tools apply an application ID to your instrumentation test APK using the application ID for the given build variant, appended with .test. For example, a test APK for the com.example.myapp.free build variant has the application ID com.example.myapp.free.test.
https://developer.android.com/studio/build/application-id

It seems to be a bug of gradle plugin and I don't know how to fix it, because setting testApplicationId the same as app id is not allowed.

perhaps it has to do with changes mentioned in Known issues:
https://developer.android.com/studio/releases/gradle-plugin

**Comment by nicolas71640** [comment]
Is somebody had found a solution for this issue ?

**Comment by Malachiasz** [comment]
As far as I know there is no workaround. What is the Android Gradle version you are using? Can you confirm the issue was not fixed there yet?

**Comment by nicolas71640** [comment]
Yes, I can confirm, The issue still exists. 
I'm using gradle 3.5.2.

**Comment by Malachiasz** [comment]
Google has answered that adding ".test" is a new feature and not a bug. So it has to be fixed by users or Robolectic would have to remove it.

**Comment by alixwar** [comment]
Still an issue in AGP 4.1.2 / Gradle 6.8 / Robolectric 4.5.1

**Comment by utzcoz** [comment]
> Google has answered that adding ".test" is a new feature and not a bug. So it has to be fixed by users or Robolectic would have to remove it.

IMO, I don't think Robolectric needs to remove `.test` from package name. Maybe developers add extra logic to resolve package name? Does AGP add `.test` for Emulator tests or not?

**Comment by dylan-chong** [comment]
what solution have people found?
defining an explicit testNamespace as the google issue does not make the problem go away

**Comment by MGaetan89** [comment]
Hey @dylan-chong,

I've copied/pasted the code snippet provided in the original comment in [`ShadowPackageManagerTest`](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowPackageManagerTest.java), and it passes successfully.

Could you try using the latest version of Robolectric (currently 4.14.1)? If that doesn't work, would you mind opening a new issue with a simple reproducible example?

**Comment by dylan-chong** [comment]
this

```
    testImplementation 'org.robolectric:robolectric:4.14.1'
```

doesnt compile with java 17 as bouncy castle requires java 21 https://github.com/bcgit/bc-java?tab=readme-ov-file#building-overview

```
Execution failed for task ':compileDebugUnitTestJavaWithJavac'.
> Could not resolve all files for configuration ':debugUnitTestCompileClasspath'.
   > Failed to transform bcprov-jdk18on-1.78.1.jar (org.bouncycastle:bcprov-jdk18on:1.78.1) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/dylanchong/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.78.1/39e9e45359e20998eb79c1828751f94a818d25f8/bcprov-jdk18on-1.78.1.jar.
         > Failed to transform '/Users/dylanchong/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk18on/1.78.1/39e9e45359e20998eb79c1828751f94a818d25f8/bcprov-jdk18on-1.78.1.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 65. (Run with --stacktrace for more details.)
```

i had to add

```
android.jetifier.ignorelist=bcprov
```

to `gradle.properties` and now it compiles

---

i still get the same error in my test though

```
Cannot load from object array because "android.os.Build$VERSION.ALL_CODENAMES" is null
java.lang.NullPointerException: Cannot load from object array because "android.os.Build$VERSION.ALL_CODENAMES" is null
	at android.os.Build$VERSION.__staticInitializer__(Build.java:339)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.robolectric.shadows.ShadowBuild$_VERSION_$$Reflector19.__staticInitializer__(Unknown Source)
	at org.robolectric.shadows.ShadowBuild.reset(ShadowBuild.java:274)
	at org.robolectric.Shadows.reset(Shadows.java:2749)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:579)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:326)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:82)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:324)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:298)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

ive been assuming that this error is related but please let me know if you think this is not the case

**Comment by dylan-chong** [comment]
AH! Found the issue - this legacy code i was editing has some static Mockito mock that was not getting closed after the test.


Sorry for the bother!
