### ISSUE TITLE
Robolectric flaky test "Shutdown in progress"

### ISSUE THREAD

**Issue by SauliusTheBlack** [robolectric/robolectric#4941]
### Description
During testing, both on my local machine, and on our build pipeline, I sometimes get failed builds due to the following stacktrace:
```
[Robolectric] tests.integration.TourQueryHandlerTest.testLinkedEmployeeAccompanyingNurse: sdk=25; resources=legacy
[Robolectric] NOTICE: legacy resources mode is deprecated; see http://robolectric.org/migrating/#migrating-to-40

java.lang.IllegalStateException: Shutdown in progress

    at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
    at java.lang.Runtime.addShutdownHook(Runtime.java:211)
    at org.robolectric.util.TempDirectory.<init>(TempDirectory.java:23)
    at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:90)
    at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:377)
    at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:252)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
    at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

The tests usually aren't anything big.

My test classes have several tests in the same file, and I've noticed that robolectric restarts after every test.

It's not always the same test that fails

### Steps to Reproduce
Since these tests are flaky, I have no way te reliably reproduce

### Robolectric & Android Version
Robolectric: 4.0.1
Android:
    minSdkVersion 23
    targetSdkVersion 25
    compileSdkVersion 25
    buildToolsVersion "28.0.3"

**Comment by philbrown-mdt** [comment]
This occurs even for tests that are not flaky. Tested on Robolectric 4.3/Android 28. I get the following stacktrace:

````
Shutdown in progress
java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at org.robolectric.util.TempDirectory.<init>(TempDirectory.java:29)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:132)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by philbrown-mdt** [comment]
It's caused by this code in [TempDirectory.java](https://github.com/robolectric/robolectric/blob/02d3a8f18fb9df7d05554f2882e73ff0ba60f5af/utils/src/main/java/org/robolectric/util/TempDirectory.java#L29):

````java
Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
        @Override public void run() {
            destroy();
          }
    }));
````

The shutdown is already in progress, so you can't add a new shutdown hook.

**Comment by eggman87** [comment]
Seeing this as well, seems to consistently happen when I run a full test suite and the runner gets to kotlin tests.

**Comment by harshmittal29** [comment]
I am getting this error after I introduced new tests using FragmentScenario

> [Robolectric] com.example.test: sdk=28; resources=BINARY
> 
> 
> 
> java.lang.IllegalStateException: Shutdown in progress
> 
> 	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
> 	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
> 	at org.robolectric.util.TempDirectory.<init>(TempDirectory.java:29)
> 	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:132)
> 	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
> 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
> 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by ampeixoto** [comment]
I am also having this issue, either in v4.2.1 or v4.3. 
Is there any know solution for this?

**Comment by philbrown-mdt** [comment]
@ampeixoto I worked around it by leaving the tests that failed for this as instrumentation tests. I think this one pretty much needs to be fixed as a PR against Robolectric.

**Comment by hoisie** [comment]
Can someone send a PR to fix this issue? Seems like catching the IllegalStateException and doing nothing is the simplest approach.

**Comment by alsutton** [comment]
The "Shutdown in progress" is a valid error condition; The hook is needed to ensure that robolectric cleans up its temporary files, and if your tests are starting when the JVM is shutting down you're probably in a bad situation anyway, so catching the exception and doing nothing will only mask the fact that a set of tests are starting when the JVM thinks it should be shutting down.

**Comment by MGaetan89** [comment]
#6126 fixes/mitigates this issue. It has been released with Robolectric 4.5.
I'm closing this ticket, but feel free to reopen if more work is needed.
