### ISSUE TITLE
ShadowSQLiteConnection: - java.lang.IllegalStateException: Illegal connection pointer 1

### ISSUE THREAD

**Issue by jongerrish** [robolectric/robolectric#4947]
When creating transactions with Room getting the following error logged to console. Tests still pass so its just noise, but should be fixed.

[Robolectric] com.example.android.architecture.blueprints.todoapp.tasks.TasksFragmentTest.markTaskAsActive: sdk=28; resources=BINARY
Exception in thread "pool-1-thread-1" java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-1-thread-1,5,SDK 28] []
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:369)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:419)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:90)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:549)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:460)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransaction(FrameworkSQLiteDatabase.java:69)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:330)
	at com.example.android.architecture.blueprints.todoapp.data.source.local.TasksDao_Impl.insertTask(TasksDao_Impl.java:136)
	at com.example.android.architecture.blueprints.todoapp.data.source.local.TasksLocalDataSource$saveTask$2.run(TasksLocalDataSource.kt:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jameswald** [comment]
I'm seeing this when using SQLiteOpenHelper as well. The first transaction works fine but the second transaction fails with this exception when SQLiteDatabase.beginTransaction() is called.

**Comment by AstralStorm** [comment]
Seeing the same issue in code where Helper is queried from AsyncTasks where MasterScheduler is UNPAUSED but is fine when it's CONSTANT_IDLE. Code calling it seems correct and is inside a ContentProvider, likewise synchronization inside Connections seems ok. Something else might be amiss.

(Tested in 4.0.2 and 4.2.1.)

**Comment by AstralStorm** [comment]
Actually the close is just not done, because ContentProviders are not being destroyed across tests as they should be - in Android, they're killed alongside process.

**Comment by AstralStorm** [comment]
Instead, ContentProvider.shutdown is being called by Robolectric which is not guaranteed to be implemented. (But should be!)

**Comment by marijalukaroska1** [comment]
Is there any progress on this issue.

I tried closing the database in @After method although in some tests I still get the same exception, but the pointer is some other number and not 1, like it was.

**Comment by jameswald** [comment]
In my case the problem was caused by instantiating SQLiteOpenHelper as a singleton which was shared across multiple calls to ContentProvider.onCreate(). I removed this optimization for Robolectric tests and always create a new SQLiteOpenHelper instance ContentProvider.onCreate() to avoid this issue.

**Comment by marijalukaroska1** [comment]
I will try that, but the weird thing is that the test started failing after I migrated from robolectric 3.0-rc2 to robolectric 4.3

**Comment by blinkmacalahan** [comment]
I too experienced this issue using a `Singleton` for my `SQLiteOpenHelper`. I was able to work around the issue by using mocks that made my singleton return an object that was created in @Before and then closed and nulled in @After (essentially making it not a singleton).

**Comment by hoisie** [comment]
@jongerrish could this be test pollution caused by threading? Such as a thread executing some logic in a SQLite database after the tests ends?

**Comment by kingargyle** [comment]
Recently experienced this with 4.5.1... same tests run fine with 4.3.   During the Application startup, we have an custom analytics that gets initialized on a background thread.  The code here may indeed be executed after the test itself has finished.  For the tests I'm working on they aren't testing the analytics portion, so I turned them off as a work around, but it still shouldn't cause the test to fail normally.

**Comment by utzcoz** [comment]
@DevDema What's your running platform? If it is not Windows, what about trying SQLiteMode.NATIVE to validate this problem again? It brings a native SQLite implementation for Robolectric. Hi @hoisie , do think native SQLite can resolve this problem?

**Comment by hoisie** [comment]
I believe this is only a problem with legacy SQLite, not native SQLite.

**Comment by asteele0** [comment]
I'm also experiencing this issue, just to bump it.
