### ISSUE TITLE
Tests pass when android.enableUnitTestBinaryResources=false but not when true

### ISSUE THREAD

**Issue by wintersandroid** [robolectric/robolectric#4961]
### Description
In our large project I have been going through the ardious task of updating to android studio 3.4
To do so I have had to update to robolectric 4.3-alpha-(3)

All tests that use robolectric and start something UI related will fail with an exception when the activity (for example) is started - failures are in loading the android resources. This I have verified by slowly commenting out one of the activities being tested until it worked.

By setting android.enableUnitTestBinaryResources=false to false, all the tests pass.

Exception example, 
`
[Robolectric] com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.successfulEditedProject: sdk=28; resources=BINARY
2019-05-01T22:31:44,167Z 10:31+1200 UTIL INFO Setting brand to 'TEST'... 

android.view.InflateException: Binary XML file line #13: Binary XML file line #13: Error inflating class android.widget.Toolbar

Caused by: android.view.InflateException: Binary XML file line #13: Error inflating class android.widget.Toolbar
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at com.android.internal.policy.PhoneLayoutInflater.$$robo$$com_android_internal_policy_PhoneLayoutInflater$onCreateView(PhoneLayoutInflater.java:58)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at com.trimble.ctct.darkcity.common.ui.ActionBarUtils.addToolBar(ActionBarUtils.java:125)
	at com.trimble.ctct.darkcity.ui.BaseRuntimeActivity.setContentView(BaseRuntimeActivity.java:210)
	at com.trimble.ctct.darkcity.ui.ProjectAddEditActivity.onCreate(ProjectAddEditActivity.java:116)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7127)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnCreate(Instrumentation.java:1271)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:680)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:322)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.setUpActivity(ProjectAddEditActivityTest.java:114)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.setUpActivityToEditMode(ProjectAddEditActivityTest.java:96)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.successfulEditedProject(ProjectAddEditActivityTest.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f040000 a=-1}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:946)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
	at android.view.View.__constructor__(View.java:5010)
	at android.view.View.<init>(View.java)
	at android.view.ViewGroup.<init>(ViewGroup.java)
	at android.widget.Toolbar.<init>(Toolbar.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at com.trimble.ctct.darkcity.common.ui.ActionBarUtils.addToolBar(ActionBarUtils.java:125)
	at com.trimble.ctct.darkcity.ui.BaseRuntimeActivity.setContentView(BaseRuntimeActivity.java:210)
	at com.trimble.ctct.darkcity.ui.ProjectAddEditActivity.onCreate(ProjectAddEditActivity.java:116)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:680)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:322)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.setUpActivity(ProjectAddEditActivityTest.java:114)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.setUpActivityToEditMode(ProjectAddEditActivityTest.java:96)
	at com.trimble.ctct.darkcity.ui.views.ProjectAddEditActivityTest.successfulEditedProject(ProjectAddEditActivityTest.java:195)
	... 11 more
`

### Steps to Reproduce

In our project, setting android.enableUnitTestBinaryResources=true or omitting it
### Robolectric & Android Version
cfgRobolectricVersion = '4.3-alpha-3'
    cfgCompileSdkVersion = 28 // Android recommends compiling with the latest stable version
    cfgTargetSdkVersion = 28 // The target platform must be a recent API to be accepted by Google Play
    cfgMinSdkVersion = 23 // The oldest platform we support 
    cfgJUnitVersion = '4.12'
    cfgAndroidXTestVersion = '1.2.0-alpha05'

### Link to a public git repo demonstrating the problem:
Private Commercial Project.

**Comment by dmeng** [comment]
@wintersandroid If you cannot link to the specific project that you're working on, can you at least recreate the issue using a much smaller project that doesn't have any of the private proprietary stuff? Right now as far as we know, it could be any number of things going on.

**Comment by jongerrish** [comment]
I suspect you are running into an issue where you were inadvertently
leaning on a bug in Robolectric that has now been fixed with binary
resources.

Previously with legacy xml resource implementation, if you attempt to look
up an attribute that doesn't exist in your context's theme, Robolectric
would silently ignore it. However, with binary resources, just like real
Android, that results in a runtime error.

What you need to do is set the correct theme on your context.

You can reverse lookup the attribute by its ID: 0x7f040000 by sticking a
breakpoint in your code and calling
context.getResources().getResourceName(0x7f040000)

then, look through your code (or dependent libraries) and find a theme that
defines that attribute (probably your main app theme is always a good bet)

It looks like your context is your ProjectAddEditActivity so this needs to
have its theme defined, either in <activity theme="..."> or the fallback if
not defined there is <application theme="...">

Check that these have the correct theme that defines the attribute it is
trying to resolve.

You can also verify this in the debugger by inspecting something like
context.getPackageManager().getApplicationInfo().activity_info

**Comment by wintersandroid** [comment]
Looks like it was our overly complicated (not my choice) themes that were the problem along with too many hands in the pool (found some tests using basic android themes).

Thanks for the tip.
