### ISSUE TITLE
java.lang.NoSuchMethodError  java.nio.ByteBuffer.position(I)

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#4990]
### Description

When running robolectric 4.3 Beta 1 with Java 8 and not targeting Android Q, I'm getting the following stack trace on about 71 tests.

java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

	at org.robolectric.res.android.ResourceTypes$FutureWriter.<init>(ResourceTypes.java:1573)
	at org.robolectric.res.android.ResourceTypes$ShortWriter.<init>(ResourceTypes.java:1596)
	at org.robolectric.res.android.ResourceTypes$ResChunk_header.write(ResourceTypes.java:124)
	at org.robolectric.res.android.ResourceTypes$ResXMLTree_header.write(ResourceTypes.java:673)
	at org.robolectric.android.AttributeSetBuilderImpl.build(AttributeSetBuilderImpl.java:357)
	at com.abercrombie.abercrombie.util.TestUtil.createAttributeSet(TestUtil.java:61)
	at com.abercrombie.abercrombie.ui.pdp.PriceViewTest.testCreateWithContextAndAttributeSetAndDefaultStyleAndDefaultStyleRes(PriceViewTest.kt:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Steps to Reproduce
Run tests with java 8.

### Robolectric & Android Version

4.3 Beta 1

**Comment by jongerrish** [comment]
Huh.... Looks like this is probably another spot where we need to apply:

[robolectric/robolectric] Upcast call to <ByteBuffer>
ByteBuffer.position(int) to <Buffer> Buffer.position(int) for Java 8
compatibility. (#4894)

**Comment by mattswitch** [comment]
I'm still getting this in 4.3 when trying to construct a `Time` object:
```java
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.skip(ShadowMemoryMappedFile.java:101)
	at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.readByteArray(ShadowMemoryMappedFile.java:111)
	at libcore.util.ZoneInfoDB$TzData.readHeader(ZoneInfoDB.java:135)
	at libcore.util.ZoneInfoDB$TzData.loadData(ZoneInfoDB.java:117)
	at libcore.util.ZoneInfoDB$TzData.__constructor__(ZoneInfoDB.java:95)
	at libcore.util.ZoneInfoDB$TzData.<init>(ZoneInfoDB.java)
	at libcore.util.ZoneInfoDB.__staticInitializer__(ZoneInfoDB.java:43)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at libcore.util.ZoneInfoDB.<clinit>(ZoneInfoDB.java)
	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1080)
	at android.text.format.Time$TimeCalculator.__constructor__(Time.java:1040)
	at android.text.format.Time$TimeCalculator.<init>(Time.java)
	at android.text.format.Time.initialize(Time.java:204)
	at android.text.format.Time.__constructor__(Time.java:180)
	at android.text.format.Time.<init>(Time.java)
```

**Comment by jongerrish** [comment]
@mattswitch I think https://github.com/robolectric/robolectric/pull/5075 should fix the issue.
