### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.google.android.gms.common.GooglePlayServicesUtil

### ISSUE THREAD

**Issue by PascalLzx** [robolectric/robolectric#5022]
### Description
I migrated my project to AndroidX and now with Robolectric 4.2.1, I get the following exceptions when running unit tests:

`java.lang.NoClassDefFoundError: Could not initialize class com.google.android.gms.common.GooglePlayServicesUtil

	at com.google.android.gms.maps.internal.zzbz.zza(Unknown Source)
	at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment$zzb.zzd(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment$zzb.createDelegate(Unknown Source)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source)
	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onInflate(Unknown Source)
	at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
	at androidx.fragment.app.Fragment.onInflate(Fragment.java:1384)
	at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3744)
	at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:186)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at com.deveryware.notico.mapsnew.DeverywareMapFragment.onCreateView(DeverywareMapFragment.java:148)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
	at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at com.deveryware.notico.widget.DeverywareActivity.onStart(DeverywareActivity.java:158)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnStart(MonitoringInstrumentation.java:686)
	at android.app.Activity.performStart(Activity.java:7029)
	at org.robolectric.util.ReflectionHelpers$6.run(ReflectionHelpers.java:247)
	at org.robolectric.util.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:399)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:241)
	at org.robolectric.android.controller.ComponentController$1.run(ComponentController.java:53)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:396)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
	at org.robolectric.android.controller.ActivityController.start(ActivityController.java:126)
	at com.deveryware.notico.myUnitTests.ui.map.MapFragmentTests.launchGeographicRestrictionEditionActivity(MapFragmentTests.java:51)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`
But I can use GooglePlayServicesUtil in my project ...

### Robolectric & Android Version
Gradle 5.1.1
minSdkVersion 22
targetSdkVersion 28
testImplementation 'org.robolectric:robolectric:4.2.1'
testImplementation 'org.robolectric:shadows-framework:4.2.1'
testImplementation 'org.robolectric:shadows-playservices:4.2.1'

**Comment by slott** [comment]
If you create your own class in your test scope matching Googles class you can get around this. Example:

package com.google.android.gms.common;

import android.content.Context;

public class GooglePlayServicesUtil {

	public static int isGooglePlayServicesAvailable(Context context) {
		return 0;
	}

	public static int isGooglePlayServicesAvailable(Context var0, int var1) {
		return 0;
	}

}

**Comment by DennisPlaysTennis** [comment]
I've replaced all my deprecated GooglePlayServicesUtil calls with GoogleApiAvailability, but still getting `java.lang.NoClassDefFoundError: Could not initialize class com.google.android.gms.common.GooglePlayServicesUtil` when running unit tests.

**Comment by joshuapinter** [comment]
Not sure if it's related but I was getting a similar error after upgrading to AndroidX and the fix was to upgrade my `com.google.android.gms:play-services` dependencies from `11.8` to `17.0`. Hopefully that helps others.
