### ISSUE TITLE
Robolectric 4.3 - NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by NickButcher1** [robolectric/robolectric#5077]
### Description
This looks similiar to https://github.com/robolectric/robolectric/issues/4990 which claims to be fixed in Robolectric 4.3.

Some tests fail like this.

java.lang.ExceptionInInitializerError
    at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1111)
    at android.text.format.Time$TimeCalculator.__constructor__(Time.java:1071)
    at android.text.format.Time$TimeCalculator.<init>(Time.java)
    at android.text.format.Time.initialize(Time.java:208)
    at android.text.format.Time.__constructor__(Time.java:184)
    at android.text.format.Time.<init>(Time.java)
    at com.myapp.MainActivity$1.onServiceConnected(MainActivity.java:234)
    at org.robolectric.shadows.ShadowInstrumentation.lambda$bindService$0(ShadowInstrumentation.java:514)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
    at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
    at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
    at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
    at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
    at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
    at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
    at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
    at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:150)
    at com.myapp.ActivityTest.testFeatureVariations(ActivityTest.kt:94)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
    at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
    at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:154)
    at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
    at libcore.util.ZoneInfoDB.<clinit>(ZoneInfoDB.java)
    at android.text.format.Time$TimeCalculator.$$robo$$android_text_format_Time_TimeCalculator$lookupZoneInfo(Time.java:1111)
    at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java)
    at android.text.format.Time$TimeCalculator.$$robo$$android_text_format_Time_TimeCalculator$__constructor__(Time.java:1071)
    at android.text.format.Time$TimeCalculator.<init>(Time.java)
    at android.text.format.Time.$$robo$$android_text_format_Time$initialize(Time.java:208)
    at android.text.format.Time.initialize(Time.java)
    at android.text.format.Time.$$robo$$android_text_format_Time$__constructor__(Time.java:184)
    at android.text.format.Time.<init>(Time.java)
    at com.myapp.main.ui.MainActivity$1.onServiceConnected(MainActivity.java:234)
    at org.robolectric.shadows.ShadowInstrumentation.lambda$bindService$0(ShadowInstrumentation.java:514)
    at android.os.Handler.$$robo$$android_os_Handler$handleCallback(Handler.java:789)
    at android.os.Handler.handleCallback(Handler.java)
    at android.os.Handler.$$robo$$android_os_Handler$dispatchMessage(Handler.java:98)
    at android.os.Handler.dispatchMessage(Handler.java)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
    at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
    at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
    at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
    at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
    at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
    at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
    at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
    at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:150)
    at com.myapp.RatingActivityTest.testFeatureVariations(RatingActivityTest.kt:94)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    ... 15 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
    at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
    ... 57 more
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
    at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.skip(ShadowMemoryMappedFile.java:101)
    at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.readByteArray(ShadowMemoryMappedFile.java:111)
    at libcore.util.ZoneInfoDB$TzData.readHeader(ZoneInfoDB.java:203)
    at libcore.util.ZoneInfoDB$TzData.loadData(ZoneInfoDB.java:182)
    at libcore.util.ZoneInfoDB$TzData.loadTzDataWithFallback(ZoneInfoDB.java:112)
    at libcore.util.ZoneInfoDB.__staticInitializer__(ZoneInfoDB.java:45)
    at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
    at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
    at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
    at libcore.util.ZoneInfoDB.<clinit>(ZoneInfoDB.java)
    at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1111)
    at android.text.format.Time$TimeCalculator.__constructor__(Time.java:1071)
    at android.text.format.Time$TimeCalculator.<init>(Time.java)
    at android.text.format.Time.initialize(Time.java:208)
    at android.text.format.Time.__constructor__(Time.java:184)
    at android.text.format.Time.<init>(Time.java)
    at com.myapp.MainActivity$1.onServiceConnected(MainActivity.java:234)
    at org.robolectric.shadows.ShadowInstrumentation.lambda$bindService$0(ShadowInstrumentation.java:514)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.dispatchMessage(ShadowLegacyMessageQueue.java:157)
    at org.robolectric.shadows.ShadowLegacyMessageQueue.access$200(ShadowLegacyMessageQueue.java:42)
    at org.robolectric.shadows.ShadowLegacyMessageQueue$1.run(ShadowLegacyMessageQueue.java:135)
    at org.robolectric.util.Scheduler$ScheduledRunnable.run(Scheduler.java:407)
    at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:279)
    at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:261)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:244)
    at org.robolectric.util.Scheduler.advanceBy(Scheduler.java:234)
    at org.robolectric.util.Scheduler.setIdleState(Scheduler.java:89)
    at org.robolectric.util.Scheduler.unPause(Scheduler.java:124)
    at org.robolectric.shadows.ShadowLegacyLooper.unPause(ShadowLegacyLooper.java:267)
    at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:324)
    at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
    at org.robolectric.android.controller.ActivityController.resume(ActivityController.java:150)
    ... 15 more

### Steps to Reproduce
All my tests pass with Robolectric 4.2.1.  After changing Robolectric version to 4.3 some tests fail with the above stack.

### Robolectric & Android Version
AGP 3.4.1.  
Robolectric 4.3.
Fails on both my Windows 10 laptop and Linux CI.

### Link to a public git repo demonstrating the problem:
Sorry, can't really share my code.

**Comment by jongerrish** [comment]
I think https://github.com/robolectric/robolectric/pull/5075 should fix the issue.
