### ISSUE TITLE
Impossible to shadow ProcessLifecycleOwner (which maintains state across tests)

### ISSUE THREAD

**Issue by calvarez-ov** [robolectric/robolectric#5080]
### Description

`androidx.lifecycle.ProcessLifecycleOwner` maintains static state across tests. As with any class that maintains static state, this causes issues when multiple tests are run.

Prior to robolectric 4.3, we had a hacky workaround for this that used reflection to reset `ProcessLifecycleOwner.sInstance` to a new `ProcessLifecycleOwner()` instance for each test.  This no longer works in robolectric 4.3 : we get an `IllegalAccessException` attempting to instantiate a new `ProcessLifecycleOwner` instance via reflection.

I tried another approach: to use a shadow for `ProcessLifecycleOwner`.  My shadow is never called. I think it may be because of this commit:

https://github.com/robolectric/robolectric/pull/4883/files
```
 // exclude arch libraries from instrumentation. These are just android libs and no one
 // should need to shadow them
```

This architecture component is a singleton, maintains static state across state, and can't be reset, either with reflection or a shadow.  How can we make sure we have a fresh state for each test?

### Steps to Reproduce
I'll try to make a sample project.

### Robolectric & Android Version
Robolectric 4.3

### Link to a public git repo demonstrating the problem:
Maybe tomorrow...

**Comment by jongerrish** [comment]
Hey @calvarez-ov - Mind opening an issue on the Google Tracker - There should be a testing story for ProcessLifecycleOwner - copy me on it and I can see what I can do to make it testable.

In the meantime, what's causing the IAE? We can see if we can re-enable the workaround.

**Comment by calvarez-ov** [comment]
I've updated the description with the IAE. I'll start working on a sample project now...

**Comment by calvarez-ov** [comment]
I've added a [sample project](https://github.com/libon/ProcessLifecycleOwnerPersistedState) with all the details in the `README.md`.

Can you take a look at it and see which parts of it would be relevant for a bug report on the Google tracker?

**Comment by jongerrish** [comment]
I suspect it's because it's final?

If you use Robolectric's Reflection helpers, that should handle the final
modifier for you too.

As for what to include in the bug for the support library, something like:-

ProcessLifecycleOwer is not testable.

It can only be invoked once per VM as it holds static state and cannot be
reinitialized or torn down. It should be reentrant so that it can be unit
tested.

**Comment by calvarez-ov** [comment]
Indeed `ReflectionHelpers` solved my "Problem 3" and so I'm no longer blocked.

I'll still create an issue on the google tracker as soon as I get a chance though.

Thanks!

**Comment by jongerrish** [comment]
Glad to hear that.

Yeah, please do Carmen, all of the androidx architecture components should
be designed for testability in mind, its totally unreasonable to expect
devs to have to apply hacks to make this work as you have had to do. If you
create an issue, please loop me in and I'll push as hard as I can from my
end to get it resolved.

**Comment by calvarez-ov** [comment]
Here's the issue in the google tracker: https://issuetracker.google.com/issues/134473339

**Comment by calvarez-ov** [comment]
Unfortunately,  using `ReflectionHelpers` doesn't work on recent versions of java.

If my java home is java 8, it works.
If it's java 15.0.1, I get an `IllegalAccessException` again:
```
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final androidx.lifecycle.ProcessLifecycleOwner field androidx.lifecycle.ProcessLifecycleOwner.sInstance to androidx.lifecycle.ProcessLifecycleOwner
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:215)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:228)
	... 21 more
Caused by: java.lang.IllegalAccessException: Can not set static final androidx.lifecycle.ProcessLifecycleOwner field androidx.lifecycle.ProcessLifecycleOwner.sInstance to androidx.lifecycle.ProcessLifecycleOwner
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
	at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
	at java.base/java.lang.reflect.Field.set(Field.java:793)
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:213)
	... 22 more
```

**Comment by utzcoz** [comment]
Hi @calvarez-ov, from [#4776](https://github.com/robolectric/robolectric/issues/4776), it is fixed from `roboletric 4.4`, could you try `4.5.1` to check whether this problem is fixed by it?

**Comment by calvarez-ov** [comment]
I'm using robolectric 4.5.1.

It looks like #4776 was fixed by no longer setting a static final field via reflection, but by using a shadow instead: https://github.com/robolectric/robolectric/issues/4776#issuecomment-668106112

Unfortunately, since the `ProcessLifecycleOwner` can't be shadowed, the only way to not preserve its state across tests is to set a static final field.

I think the inability to set a static final field in newer java versions may be a java limitation unfortunately: https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12

The only ways I see to deal with this are:
* Google fixes their [issue](https://issuetracker.google.com/issues/134473339). Unfortunately it's been open for two years and hasn't moved since
* Robolectric allows shadowing `ProcessLifecycleOwner`
* Users of robolectric keep using java 8 until one of the previous points is unblocked

**Comment by hoisie** [comment]
> Google fixes their issue. Unfortunately it's been open for two years and hasn't moved since

I can try to ping that Google issue. Not sure what's going on there. The AndroidX folks are pretty open to issues like this.

> Robolectric allows shadowing ProcessLifecycleOwner

Robolectric doesn't prevent you from shadowing anything :) You can create custom shadows for anything you'd like.. Robolectric just tries to provide default instrumentation config that tries to only shadow what is necessary. You can use `@Config(instrumentedPackages={"androidx.lifecycle"})` or have a subclass of RobolectricTestRunner that overrides `createClassLoaderConfig` to tell Robolectric to instrument androidx.lifecycle.

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/RobolectricTestRunner.java#L157

**Comment by calvarez-ov** [comment]
Thanks for the new info!  I'll give the shadow another try.  I previously ran into a problem:

> I tried another approach: to use a shadow for ProcessLifecycleOwner. My shadow is never called. I think it may be because of this commit:
> 
> https://github.com/robolectric/robolectric/pull/4883/files
> 
>  // exclude arch libraries from instrumentation. These are just android libs and no one
>  // should need to shadow them

But I'll take a closer look with what you've just said.  Thanks!

**Comment by hoisie** [comment]
Ah yeah, it's not too intuitive, but in order to have a custom shadow for things, the class to be instrumented by Robolectric. So if the class you want to custom-shadow is not instrumented by default for Robolectric, you have to provide new instrumentation configuration.

Maybe we should have an error message (or at least a warning) if you try to use a custom shadow and the underlying class is not instrumented by Robolectric.

**Comment by calvarez-ov** [comment]
Looks like adding the following isn't enough:

```kt
 @Config(shadows = [MyShadowProcessLifecycleOwner::class],instrumentedPackages=["androidx.lifecycle"])
```

Because the built-in package exclusion seems to take priority:

In `InstrumentationConfiguration.java`:

```java
  public boolean shouldInstrument(ClassDetails classDetails) {
    return !classDetails.isInterface()
        && !classDetails.isAnnotation()
        && !classesToNotInstrument.contains(classDetails.getName())
        && !isInPackagesToNotInstrument(classDetails.getName()). // <---- quits here, before evaluating `isInInstrumentedPackage`
        && !classMatchesExclusionRegex(classDetails.getName())
        && !classDetails.hasAnnotation(DoNotInstrument.class)
        && (isInInstrumentedPackage(classDetails.getName())
            || instrumentedClasses.contains(classDetails.getName())
            || classDetails.hasAnnotation(Instrument.class));
  }
```

**Comment by hoisie** [comment]
Ugh that's annoying. This should be possible in 4.6 because we removed all Androidx instrumentation directives in AndroidConfigurer.

I'll try to push out an alpha today or tomorrow.

Also maybe that logic needs to be updated to be more flexible.

**Comment by calvarez-ov** [comment]
An update on our side: We've done some refactoring/rework in our app code to no longer use the `ProcessLifecycleOwner` apis. This allows us to avoid this problem in tests, and upgrade our development environments to Java 15!  (Not Java 16 yet as that introduces new unrelated issues 😅 )

**Comment by hoisie** [comment]
Robolectric 4.6 alpha 1 is released which should fix this issue. That
stopped shadowing AndroidX explicitly.
