### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by biothunder** [robolectric/robolectric#5103]
### Description
Use Robolectric 4.3 still have problem with android.text.format.DateUtils

java.lang.ExceptionInInitializerError
	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1110)
	at android.text.format.Time$TimeCalculator.__constructor__(Time.java:1070)
	at android.text.format.Time$TimeCalculator.<init>(Time.java)
	at android.text.format.Time.initialize(Time.java:208)
	at android.text.format.Time.__constructor__(Time.java:184)
	at android.text.format.Time.<init>(Time.java)
	at android.text.format.DateUtils.isToday(DateUtils.java:502)
	at com.hyena.qwic2.extension.DateKt.isNotToday(Date.kt:29)
	at com.hyena.qwic2.manager.DailyTripHistoryManager.updateTodayDailyTripHistory(DailyTripHistoryManager.kt:89)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest$updateTodayDailyTripHistory$1.invokeSuspend(DailyTripHistoryManagerTest.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest.updateTodayDailyTripHistory(DailyTripHistoryManagerTest.kt:88)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:154)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at libcore.util.ZoneInfoDB.<clinit>(ZoneInfoDB.java)
	at android.text.format.Time$TimeCalculator.$$robo$$android_text_format_Time_TimeCalculator$lookupZoneInfo(Time.java:1110)
	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java)
	at android.text.format.Time$TimeCalculator.$$robo$$android_text_format_Time_TimeCalculator$__constructor__(Time.java:1070)
	at android.text.format.Time$TimeCalculator.<init>(Time.java)
	at android.text.format.Time.$$robo$$android_text_format_Time$initialize(Time.java:208)
	at android.text.format.Time.initialize(Time.java)
	at android.text.format.Time.$$robo$$android_text_format_Time$__constructor__(Time.java:184)
	at android.text.format.Time.<init>(Time.java)
	at android.text.format.DateUtils.$$robo$$android_text_format_DateUtils$isToday(DateUtils.java:502)
	at android.text.format.DateUtils.isToday(DateUtils.java)
	at com.hyena.qwic2.extension.DateKt.isNotToday(Date.kt:29)
	at com.hyena.qwic2.manager.DailyTripHistoryManager.updateTodayDailyTripHistory(DailyTripHistoryManager.kt:89)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest$updateTodayDailyTripHistory$1.invokeSuspend(DailyTripHistoryManagerTest.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest.updateTodayDailyTripHistory(DailyTripHistoryManagerTest.kt:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	... 41 more
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.skip(ShadowMemoryMappedFile.java:101)
	at org.robolectric.shadows.ShadowMemoryMappedFile$RoboBufferIterator.readByteArray(ShadowMemoryMappedFile.java:111)
	at libcore.util.ZoneInfoDB$TzData.readHeader(ZoneInfoDB.java:206)
	at libcore.util.ZoneInfoDB$TzData.loadData(ZoneInfoDB.java:185)
	at libcore.util.ZoneInfoDB$TzData.loadTzDataWithFallback(ZoneInfoDB.java:115)
	at libcore.util.ZoneInfoDB.__staticInitializer__(ZoneInfoDB.java:46)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at libcore.util.ZoneInfoDB.<clinit>(ZoneInfoDB.java)
	at android.text.format.Time$TimeCalculator.lookupZoneInfo(Time.java:1110)
	at android.text.format.Time$TimeCalculator.__constructor__(Time.java:1070)
	at android.text.format.Time$TimeCalculator.<init>(Time.java)
	at android.text.format.Time.initialize(Time.java:208)
	at android.text.format.Time.__constructor__(Time.java:184)
	at android.text.format.Time.<init>(Time.java)
	at android.text.format.DateUtils.isToday(DateUtils.java:502)
	at com.hyena.qwic2.extension.DateKt.isNotToday(Date.kt:29)
	at com.hyena.qwic2.manager.DailyTripHistoryManager.updateTodayDailyTripHistory(DailyTripHistoryManager.kt:89)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest$updateTodayDailyTripHistory$1.invokeSuspend(DailyTripHistoryManagerTest.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:233)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:76)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:53)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:35)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.hyena.qwic2.manager.DailyTripHistoryManagerTest.updateTodayDailyTripHistory(DailyTripHistoryManagerTest.kt:88)
	... 13 more

### Steps to Reproduce
call android.text.format.DateUtils.isToday() function

### Robolectric & Android Version
Robolectric 4.3

**Comment by YogeshByndoor** [comment]
Even i am facing the same issue.

**Comment by YogeshByndoor** [comment]
@biothunder : Any updates on this. Even i am facing the same issue.

**Comment by YogeshByndoor** [comment]
This works in 4.2.1
