### ISSUE TITLE
ViewInteraction.perform(RecyclerViewActions.actionOnItemAtPosition(idx, click())) doesn't start new activity

### ISSUE THREAD

**Issue by gabo602** [robolectric/robolectric#5127]
### Description
```
onView(withId(R.id.recyclerview_messages)).check(matches(isDisplayed())).perform(RecyclerViewActions.actionOnItemAtPosition(idx, click()));
```

does not start new activity when run as instrumentedTest with robolectric.
No error, just when checking in next step

`onView(withId(R.id.relativelayout_messages_detail)).check(matches(isDisplayed()))`

I get

```
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: with id: my.project.app.test:id/relativelayout_messages_detail
at java.lang.Thread.getStackTrace(Thread.java:1559)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at my.project.app.BaseActivityTest.checkAndGetView(BaseActivityTest.java:72)
	at my.project.app.FirstActivityTest.testMessageReadCount(FirstActivityTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

When I run test as androidTest on device with Espresso, test runs fine and activity is started.

CardView onClickListener:
`activity.startActivity(new Intent(activity, SecondActivity.class).putExtra(PARAM_ID, paramId));`

FirstActivity is started with:
 ```
@Rule
public ActivityScenarioRule<FirstActivity> activityRule = new ActivityScenarioRule<>(FirstActivity.class);
```

### Robolectric & Android Version
Robolectric: 4.3
Espresso: 3.2.0
androidx.test: 1.2.0
Android SDK: 24
Java: 8

**Comment by mageRabbitStudios** [comment]
Isn't it better to test views in isolation using Robolectric, only asserting that navigate gets called when using Navigation Component, rather than doing end-to-end tests with Robolectric? Those can be done under androidTest

**Comment by gabo602** [comment]
I'm sorry I respond so late. In the end, I did it the way you described, but was hoping that I can use robolectric for end-to-end tests, too.

**Comment by calvarez-ov** [comment]
Looks like the same as #5104 (which was closed for the same reason).
