### ISSUE TITLE
Failed Robolectric 4 unit tests when testing using Nougat or above sdk config

### ISSUE THREAD

**Issue by ruairimcguigan** [robolectric/robolectric#5141]
### Description

`java.lang.RuntimeException: No data directory found for package android

	at android.app.ContextImpl.getDataDir(ContextImpl.java:1973)
	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:475)
	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:655)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:487)
	at com.ctrlgroup.blackwell.locale.LocaleManager.getSharedPreferences(LocaleManager.kt:184)
	at com.ctrlgroup.blackwell.locale.LocaleManager.setAppLocale(LocaleManager.kt:38)
	at com.ctrlgroup.blackwell.locale.LocaleManager.isPreferredLocale(LocaleManager.kt:123)
	at com.ctrlgroup.blackwell.locale.LocaleManagerTest.setPreferredLocale(), when api Nougat or above, and study supports first user preference, setAppLocale to this, and return true(LocaleManagerTest.kt:236)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

### Steps to Reproduce
Works fine for < api 25. Once @Config(sdk = [N]) or higher is set I get above error.

### Robolectric & Android Version
"org.robolectric:robolectric:4.2"

**Comment by hoisie** [comment]
Is this still an issue with 4.4? Seems like this should work now given it is under test (https://github.com/robolectric/robolectric/pull/3612)
