### ISSUE TITLE
Robolectric does not fail if an invalid icon is posted

### ISSUE THREAD

**Issue by jpd236** [robolectric/robolectric#5162]
On a real Android device running Android M or earlier, attempting to show a notification with a vector drawable small icon that uses unsupported XML elements (like gradients) in Android M will subsequently crash the app with a stack trace like:

android.app.RemoteServiceException: Bad notification posted from package [package name]: Couldn't create icon: StatusBarIcon(icon=Icon(typ=RESOURCE pkg=[package name] id=[resource id]) visible user=0 )
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2019)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

I believe this is because the exception comes from SystemUI when actually attempting to show the notification and then gets reported back to the application that initially showed it, though I'm not certain.

Ideally, Robolectric would match the symptom here and validate the icon, crashing if it cannot be shown for the active SDK level. I believe this could be checked by calling Context#getDrawable on the provided icon.

**Comment by hoisie** [comment]
Sounds good to me, up for sending a PR to fix it?

**Comment by jpd236** [comment]
I prepared an internal CL for this (cl/331254884) but run into some failures in existing internal code due to test code that passes invalid resource IDs for the icon. I think the next step is to verify that completely invalid IDs would crash on a real device as well; if so, we should fix those tests (which would take a little time to see through). If not, then I think we'd need to find a way to distinguish between invalid resources and missing resources, or else just accept that Robolectric is stricter than the platform in a reasonable way.

**Comment by jpd236** [comment]
From testing on a real device:

- If you set the small icon to 0 or leave it unset, and target SDK > LOLLIPOP_MR1, it will crash: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/NotificationManager.java#601

- If you set the small icon to a non-zero resource, it does not crash (at least on this device), but silently fails to show the notification.

I'm not sure how to test what would happen on this device w/ an unsupported vector attribute, since it supports all vector attributes that I'm aware of.

The first validation (making sure small icon is non-zero) seems likely to cause many tests to fail since I imagine there could be many unit tests which trigger notifications but never call setSmallIcon (as opposed to calling it with an invalid value). Any guidance from the Robolectric perspective on the best way to introduce that kind of check?

I also worry that this behavior might have changed from platform release to platform release, and I'm not sure if we'd want to try and match historical behavior as well. My hope is we could just be simple and strict here, but I'm not sure how much we value keeping reasonable existing tests working.
