### ISSUE TITLE
ShadowParcelFileDescriptor.createPipe FileAlreadyExistsException

### ISSUE THREAD

**Issue by roshcagra** [robolectric/robolectric#5194]
Example stacktrace:
java.nio.file.FileAlreadyExistsException: 
        at org.robolectric.util.TempDirectory.create(TempDirectory.java:51)
        at org.robolectric.shadows.ShadowParcelFileDescriptor.createPipe(ShadowParcelFileDescriptor.java:79)
        at android.os.ParcelFileDescriptor.createPipe(ParcelFileDescriptor.java)

Offending line:
https://github.com/robolectric/robolectric/blob/4c7db6dc1ab4962275253726443fb7d107e89eff/shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcelFileDescriptor.java#L79

Looks like it should use TempDirectory.createIfNotExists()?

**Comment by hoisie** [comment]
Has this been fixed?
