### ISSUE TITLE
Custom shadow w/ static synchronized field ignored

### ISSUE THREAD

**Issue by nuKs** [robolectric/robolectric#5225]
### Description

Hello,

I am trying to write a simple custom shadow with Robolectric 4.3 for SQLCypher. The shadowed method is never called. I suspect the shadow class not to be registered at all.

Not sure what I am doing wrong. I didn't find any related issue anywhere. Here are a few hypothesis I have.

1.
Maybe I just simply misunderstand the Robolectric 4 API.

2.
I dont want to mock SQLCypher as it's a transitive dependency. However, I've put the intermediary library module inside my own code for now such as the debugging is made easier. Therefore the SQLCypher method call is temporarily located inside my own code. May be it's related

3.
Maybe Robolectric doesn't support synchronized field ?

```java
// Not working with RobolectricTestRunner.class either - not sure which one to use though.
@RunWith(AndroidJUnit4.class)
@Config(sdk = Build.VERSION_CODES.O_MR1, application = TestApplication.class, shadows = { SQLiteClosableShadow.class, SQLiteDatabaseShadow.class })
public class TestJoinStudy {
    ...
}
```

```java
@Implements(SQLiteDatabase.class)
public class SQLiteDatabaseShadow extends SQLiteClosableShadow {

    @Implementation
    // Not working with public visibility as well, but I suppose Robolectric rely on Reflection instead of inheritance anyway ?
    protected static synchronized void loadLibs (Context context) {
        // Do nothing...
    }
    ....
}

@Implements(SQLiteClosable.class)
public class SQLiteClosableShadow {

}
```

The error is the following, obviously showing the methods are not overriden.

```
java.lang.UnsatisfiedLinkError: no sqlcipher in java.library.path

	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:223)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:240)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:219)
	at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:212)
	at com.aware.utils.DatabaseHelper.<init>(DatabaseHelper.java:66)
```

**Comment by nuKs** [comment]
Found out !

I needed to specify the instrumented package on which to inject the shadows as well. 
Would be nice to precise this in the user guide.

```java
@RunWith(AndroidJUnit4.class)
@Config(sdk = Build.VERSION_CODES.O_MR1, application = TestApplication.class, shadows = { SQLiteClosableShadow.class, SQLiteDatabaseShadow.class }, instrumentedPackages = { "net.sqlcipher.database" })
public class TestJoinStudy {
    ...
}
```
