### ISSUE TITLE
Absent Code attribute in method that is not native after migrated to Robolectric 4.0.2 with androidX

### ISSUE THREAD

**Issue by karan2vel** [robolectric/robolectric#5246]
After migrated my android project to androidx and roboelectric to 4.0.2 classes having annotation

> @RunWith(RobolectricTestRunner.class)

failed to execute with the below error. When tried to debug the test case it is not even coming to the the 

> @Before

 function and the stacktrace is just failed with showing the error message as **initializationError** and with the top message of below error.
Using : Andorid API 28 (P)
Gradle version : 3.3.1
Gradle Wrapper Version : 4.10.1

> java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file android/app/Application
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>     at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     at java.lang.ClassLoader.defineClass1(Native Method)
>     at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
>     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
>     at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
>     at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>     at org.robolectric.annotation.Config.<clinit>(Config.java:40)
>     at org.robolectric.annotation.Config$Builder.<init>(Config.java:377)
>     at org.robolectric.RobolectricTestRunner.buildGlobalConfig(RobolectricTestRunner.java:538)
>     at org.robolectric.RobolectricTestRunner.getConfig(RobolectricTestRunner.java:520)
>     at org.robolectric.RobolectricTestRunner.getChildren(RobolectricTestRunner.java:284)
>     at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:426)
>     at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:351)
>     at org.junit.runners.ParentRunner.run(ParentRunner.java:359)
>     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
>     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
>     at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
>     at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
>     at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
>     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
>     at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
>     at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
>     at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
>     at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
>     at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
>     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
>     at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
>     at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
>     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
>     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
>     at java.lang.Thread.run(Thread.java:748)

**Comment by karan2vel** [comment]
For a detailed information please visit [here](https://stackoverflow.com/questions/57784581/robolectric-fails-with-androidx-absent-code-attribute-in-method-that-is-not-na).

**Comment by karan2vel** [comment]
I beleive the error happens in this place from the config file of robolectric.

```
/**
    The {@link android.app.Application} class to use in the test, this takes precedence over any application
    specified in the AndroidManifest.xml.
   
   @return The {@link android.app.Application} class to use in the test.
   */
  Class<? extends Application> application() default DefaultApplication.class;  // DEFAULT_APPLICATION
```

**Comment by karan2vel** [comment]
I understood the issue is mainly because of I am using the modified android.jar file in platforms folder.
I have raised a issue with the hidden api project team [here](https://github.com/anggrayudi/android-hidden-api/issues/62). Also if some have any workaround for this issue please let me know and I need with hidden api's android jar because I am writing a system application.

Thank you.

**Comment by JomyPaul01** [comment]
I faced similar error in robolectric 4.6.1 version. it was resolved for me by changing the JRE refer to version 11 in edit configuration of junit test
