### ISSUE TITLE
Creating FireBaseVisionImage from byteArray[] - 

### ISSUE THREAD

**Issue by PriyaJaichandran** [robolectric/robolectric#5308]
When try to create FirebaseVisionImage using a byteArray got and error ,

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: android.os.SystemClock.elapsedRealtime()J
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1006)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
/*CODE SNIPPET */
private void imageFromBuffer(byte[] byteArray, int rotation) {
        // [START set_metadata]
        FirebaseVisionImageMetadata metadata = new FirebaseVisionImageMetadata.Builder()
                .setWidth(480)   // 480x360 is typically sufficient for
                .setHeight(360)  // image recognition
                .setFormat(FirebaseVisionImageMetadata.IMAGE_FORMAT_YV12)
                .setRotation(rotation)
                .build();
        // [END set_metadata]
        // [START image_from_buffer]
        //FirebaseVisionImage image = FirebaseVisionImage.fromByteArray(byteArray, metadata);
        FirebaseVisionImage myImage = FirebaseVisionImage.fromByteArray(new byte[]{},
                new FirebaseVisionImageMetadata.Builder().build());
        //labelImagesCloud(image);
        Task<List<FirebaseVisionImageLabel>> result = labeler.processImage(myImage);
        // [END image_from_buffer]
    }

**Comment by dmeng** [comment]
Was this meant to be filed against a Firebase repo? Robolectric doesn't touch FirebaseVisionImage.
