### ISSUE TITLE
Espresso test in Robolectric is not working

### ISSUE THREAD

**Issue by varunam** [robolectric/robolectric#5334]
### Hi Team,
I am trying to run a simple espresso test under test package with robolectric dependency added but it's failing with below exception.

`androidx.test.espresso.NoMatchingRootException: Matcher '(has window layout params and (((is dialog and with decor view has window focus) or is subwindow of current activity) and is focusable))' did not match any of the following roots: []
at java.lang.Thread.getStackTrace(Thread.java:1559)
	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:96)
	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
	at androidx.test.espresso.ViewInteraction.check(ViewInteraction.java:306)
	at com.example.robolectricsample.MainActivityTest.testButtonText(MainActivityTest.kt:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

### Steps to Reproduce
1. Add test class under test package.
2. Write a sample espresso test.
3. Run it.
Below is the code

`
@RunWith(RobolectricTestRunner::class)
class MainActivityTest {

    private lateinit var activity: Activity

    @Before
    fun setUp() {
        activity = Robolectric.buildActivity(MainActivity::class.java).create().resume().get()
    }

@Test
    fun testButtonText() {
        Logger.info("test started")
        onView(withId(R.id.sample_button_id)).check(matches(isDisplayed()))
        Logger.info("test ended")
    }
}`

### Robolectric & Android Version
Robolectric - v3.4
Target SDK - 28

**Comment by neiljaywarner** [comment]
@varunam Maybe try using ActivityTestRule, that has worked for me, and even the ext package AndroidTestRunner. you also have to fiddle around with build.gradle awhile but the instructions on developer site are decent.

see https://github.com/neiljaywarner/LocalUiTest/blob/master/app/src/test/java/com/example/localuitest/MainActivityTest.kt

**Comment by utzcoz** [comment]
Please try latest Robolectric, and I think it can work with Espresso because Robolectric also has some tests with Espresso. Feel free to reopen this issue or file a new issue if you encounter problem when using Robolectric with Espresso.
