### ISSUE TITLE
android.view.InflateException: Binary XML file line #27

### ISSUE THREAD

**Issue by 4mr0m3r0** [robolectric/robolectric#5348]
### Description
When I run the unit test

android.view.InflateException: Binary XML file line #27: Binary XML file line #27: Error inflating class androidx.appcompat.widget.ActionBarContainer

Caused by: android.view.InflateException: Binary XML file line #27: Error inflating class androidx.appcompat.widget.ActionBarContainer
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$createSubDecor(AppCompatDelegateImpl.java:607)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$ensureSubDecor(AppCompatDelegateImpl.java:518)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$setContentView(AppCompatDelegateImpl.java:466)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatActivity.$$robo$$androidx_appcompat_app_AppCompatActivity$setContentView(AppCompatActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$setContentView(DataBindingUtil.java:284)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.setupBinding(DisplayMoviesActivity.kt:55)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.onCreate(DisplayMoviesActivity.kt:49)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7127)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnCreate(Instrumentation.java:1271)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:102)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:396)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:102)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:107)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:39)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:184)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivityTest.<init>(DisplayMoviesActivityTest.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.createTest(RobolectricTestRunner.java:534)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:322)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ExceptionInInitializerError
	at androidx.appcompat.widget.ActionBarContainer.__constructor__(ActionBarContainer.java:62)
	at androidx.appcompat.widget.ActionBarContainer.<init>(ActionBarContainer.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:607)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.setupBinding(DisplayMoviesActivity.kt:55)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.onCreate(DisplayMoviesActivity.kt:49)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:102)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:396)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:102)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:107)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:39)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:184)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivityTest.<init>(DisplayMoviesActivityTest.kt:23)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:154)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at androidx.core.view.ViewCompat.<clinit>(ViewCompat.java)
	at androidx.appcompat.widget.ActionBarContainer.$$robo$$androidx_appcompat_widget_ActionBarContainer$__constructor__(ActionBarContainer.java:62)
	at androidx.appcompat.widget.ActionBarContainer.<init>(ActionBarContainer.java)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createView(LayoutInflater.java:647)
	at android.view.LayoutInflater.createView(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:790)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at android.view.LayoutInflater.$$robo$$android_view_LayoutInflater$inflate(LayoutInflater.java:374)
	at android.view.LayoutInflater.inflate(LayoutInflater.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$createSubDecor(AppCompatDelegateImpl.java:607)
	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$ensureSubDecor(AppCompatDelegateImpl.java:518)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatDelegateImpl.$$robo$$androidx_appcompat_app_AppCompatDelegateImpl$setContentView(AppCompatDelegateImpl.java:466)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java)
	at androidx.appcompat.app.AppCompatActivity.$$robo$$androidx_appcompat_app_AppCompatActivity$setContentView(AppCompatActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$setContentView(DataBindingUtil.java:303)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at androidx.databinding.DataBindingUtil.$$robo$$androidx_databinding_DataBindingUtil$setContentView(DataBindingUtil.java:284)
	at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.setupBinding(DisplayMoviesActivity.kt:55)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivity.onCreate(DisplayMoviesActivity.kt:49)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:7127)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnCreate(Instrumentation.java:1271)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:674)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:102)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:396)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:102)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:107)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:39)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:207)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:184)
	at com.tzion.openmoviesdatabase.movie.displayMovies.DisplayMoviesActivityTest.<init>(DisplayMoviesActivityTest.kt:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	... 12 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:151)
	... 69 more
Caused by: java.lang.NoSuchFieldError: accessibility_custom_action_0
	at androidx.core.view.ViewCompat.__staticInitializer__(ViewCompat.java:1191)
	... 75 more

### Steps to Reproduce
Inside DisplayMoviesActivityTest run "when activity launch, then display search image" test.

### Robolectric & Android Version
4.2, also with 4.3.1. androidBuildToolsVersion: 28.0.3, androidCompileSdkVersion: 28

### Link to a public git repo demonstrating the problem:
https://github.com/4mr0m3r0/movies-mvi-sample/blob/master/smartphone-ui/src/test/java/com/tzion/openmoviesdatabase/movie/displayMovies/DisplayMoviesActivityTest.kt

**Comment by Plastix** [comment]
I have the same exact issue with some of my Robolectric tests. Robolectric complains about not being able to inflate AndroidX's RecyclerView class as well as some my own custom views.

I tried with Robolectric 3.8-4.3.1 running with SDK 27 using Android Gradle Plugin 3.3.2 and Gradle 4.10

**Comment by goldy1992** [comment]
I had a similar issue throwing an InflateException:

```
android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class TextView

Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class TextView
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)
	at android.widget.TextView.readTextAppearance(TextView.java:3548)
	at android.widget.TextView.__constructor__(TextView.java:924)
	at android.widget.TextView.<init>(TextView.java)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.github.goldy1992.mp3player.client.activities.SplashScreenEntryActivity.onCreate(SplashScreenEntryActivity.kt:60)
	at com.github.goldy1992.mp3player.client.activities.SplashScreenEntryActivityInjectorTestImpl.onCreate(SplashScreenEntryActivityInjectorTestImpl.kt:11)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:198)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
	at org.robolectric.android.fakes.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:61)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:34)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:231)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:190)
	at com.github.goldy1992.mp3player.client.activities.SplashScreenEntryActivityTest.setup(SplashScreenEntryActivityTest.kt:33)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This was for my splash screen.
**The problem** was I had defined different themes for my app, which I didn't need to set for my Splash screen because it was always the same.

**The solution for me** was to add
```
        val settings = applicationContext.getSharedPreferences(Constants.THEME, Context.MODE_PRIVATE)
        setTheme(settings.getInt(Constants.THEME, R.style.AppTheme_Blue))
```
to my `onCreate` and my tests ran as expected

**Comment by gmazzo** [comment]
Is there any update on this issue? For us, it seems that it's not picking the `android:theme` value from the manifest and you need to set it manually with a custom `setTheme`

**Comment by luloe** [comment]
You need to set the theme manually every time you start a new activity.

In onCreate:

setTheme(R.style.YourTheme);

**Comment by JohnZhang1000** [comment]
I also got a similar issue throwing an InflateException:

**Comment by JohnZhang1000** [comment]
I got a similar issue throwing an InflateException in xml place where I used Costumed Toolbar.
My situation is I do unit test for a project, but it's activity uesd a Costumed Toolbar, and theCostubmed Toolbar was in a jar package, and it's constructor and method was Throwing Stub Exception.
so when I onCreat the view ,the InflateException happend. any solution can dealwith this?

I Know the Costum Toolbar is Empty,so I try to make a shadow Toolbar for it. but don't Know how to make it .

**Comment by utzcoz** [comment]
@JohnZhang1000 you can follow http://robolectric.org/extending/ to create shadow class for your custom Toolbar. IMO, it's enough to learn how to write custom shadow class.

**Comment by utzcoz** [comment]
Hi @4mr0m3r0 @goldy1992 @gmazzo could you retest it on latest 4.7.3 with `includeAndroidResource=true`? I remember Robolectric will not instrument androidx source code, and `includeAndroidResource=true` can help to integrate all your resources, and both of them maybe helpful to fix this problem.

**Comment by JohnZhang1000** [comment]
> 

thank you very much for your advice@utzcoz. cause the custom view have five overload constructor ,I have no idea How to make the constructor in my shadow.and it contains a super() method , whitch means it need a real parents class.  I will try it.

**Comment by mposch-Z** [comment]
Tried setTheme in the onCreate of the activity I'm trying to fake using Robo, still seeing the same error.  My issue occurs when inflating a snackbar: Binary XML file line #26 in com.X.Y:layout/design_layout_snackbar_include: Binary XML file line #26 in com.X.Y:layout/design_layout_snackbar_include: Error inflating class <unknown>****

Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 6: TypedValue{t=0x2/d=0x101009b a=1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
	
Also, when creating the snackbar in the class under test I'm doing the following hoping to resolve the error, again, with no success:
snackbar =  Snackbar.make(context, view, context.getResources().getString(R.string.internet_down), Snackbar.LENGTH_INDEFINITE).setTextColor(new ColorStateList(states,colors));

Is the issue b/c my snackbar is totally created programmatically and not in a layout/xml file somewhere?
