### ISSUE TITLE
SandboxTestRunner$HelperTestRunner is not public

### ISSUE THREAD

**Issue by philbrown-mdt** [robolectric/robolectric#5368]
### Description

There is an error thrown by the test runner when using certain runner configurations. For example, when using `@Runwith(Enclosed.class)`, this error sometimes occurs:

```
How did getFields return a field we couldn't access?
java.lang.RuntimeException: How did getFields return a field we couldn't access?
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:235)
	at org.junit.runners.BlockJUnit4ClassRunner.getTestRules(BlockJUnit4ClassRunner.java:413)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:353)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:318)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.methodBlock(RobolectricTestRunner.java:541)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:248)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessException: Class org.junit.runners.model.FrameworkField can not access a member of class com.example.application.MyTest$BaseTest with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.get(Field.java:390)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	... 11 more
```

### Steps to Reproduce

Create an test in android written in java, and place in the androidTest directory. Specify the test runner as `@RunWith(Enclosed.class)`. Create three inner classes. One is abstract and serves as a base class. This contains public fields like rules. Add a field `public String foo`. The other classes are test classes. These should extend BaseTest and reference the field foo in there setup methods. Annotate these for to `@RunWith(AndroidJunit4.class)`. Your file will look something like this:

````java
@RunWith(Enclosed.class)
public class MyTest {
    public static abstract class BaseTest {
        public String foo;
    }
    @RunWith(AndroidJUnit4.class)
    public static class MyFirstTest extends BaseTest {
        @Before
        public void setUp() {
            foo = "Hello";
        }
    }
    @RunWith(AndroidJUnit4.class)
    public static class MySecondTest extends BaseTest {
        @Before
        public void setUp() {
            foo = "Hi";
        }
    }
}
````

Next, convert the androidTest sourceSets to test sourceSets and add the robolectric dependency:

````groovy
android.sourceSets.test.java.srcDir android.sourceSets.androidTest.java.srcDirs[0]
android.dependencies {
    testImplementation 'org.robolectric:robolectric:4.3'
}
````

Now run the test MyTest. 

### Robolectric & Android Version

Robolectric 4.3
Android compile sdk 28

-----

I believe this may be an issue with the protected status of the test runner, as described at https://github.com/junit-team/junit4/issues/1576#issuecomment-444420776

**Comment by utzcoz** [comment]
@philbrown-mdt Could you try latest Robolectric 4.9? `RobolectricTestRunner$HelperTestRunner` is public now, and I tried it with junit4's `Enclosed.class` + your mentioned example successfully.

**Comment by utzcoz** [comment]
Closed by https://github.com/robolectric/robolectric/pull/7873. @philbrown-mdt If you find other `Enclosed` scenarios that Robolectric can't work with, feel free to reopen this issue. Thanks.
