### ISSUE TITLE
popBackStackImmediate is crashing for androidx-fragment 1.1.0

### ISSUE THREAD

**Issue by neworld** [robolectric/robolectric#5370]
### Description

```
java.lang.IllegalStateException: Fragment host has been destroyed
	at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1664)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1721)
	at androidx.fragment.app.FragmentManagerImpl.dispatchDestroy(FragmentManagerImpl.java:2643)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2825)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1028)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:496)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManagerImpl.java:310)
	at androidx.fragment.app.FragmentManagerImpl.popBackStackImmediate(FragmentManagerImpl.java:264)
	at com.vinted.androidx_fragment_110.MainActivityTest.checkWithCustomManagement(MainActivityTest.kt:46)
```

This crash happens, because `FragmentManagerImpl.dispatchDestroy()`  happens two times. One time was triggered due to popped fragment out, another time due to finished animation. Breakpoint in this method reveals this behavior.

In the Android device, it is working. So I suppose this one is a Robolectric issue. Some `androidx-fragment` are working:
- 1.0.0 - works
- 1.1.0 - Crash: java.lang.IllegalStateException: Fragment host has been destroyed
- 1.2.0-xxxx - Crash: NPE

### Steps to Reproduce

```
git clone git@github.com:neworld/androidx_fragment_110.git
cd androidx_fragment_110
./gradlew testDebug
```

Also, it will fail from Android Studio as well. `app` has exactly the same implementation, but it is not crashing

### Robolectric & Android Version

Robolectric: 4.3.1
Android compile: 29
Android target: 28-29
JVM: 11

### Link to a public git repo demonstrating the problem:

https://github.com/neworld/androidx_fragment_110

**Comment by utzcoz** [comment]
@neworld Could you try it with latest Robolectric? If this issue still exists, feel free to reopen this issue. Thanks.
