### ISSUE TITLE
Robolectric isn't compatible with dynamic-features modules

### ISSUE THREAD

**Issue by vmadalin** [robolectric/robolectric#5383]
### Description

Running robolectric test on `dynamic-feature` throws the following exception. The same test but under `android-library` works correctly.

``` 
java.lang.RuntimeException: java.lang.UnsupportedOperationException: libraries not supported yet

	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:69)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:314)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:284)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:282)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:178)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: libraries not supported yet
	at org.robolectric.res.android.ResTable.parsePackage(ResTable.java:1014)
	at org.robolectric.res.android.ResTable.addInternal(ResTable.java:330)
	at org.robolectric.res.android.ResTable.add(ResTable.java:165)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable_measured(CppAssetManager.java:674)
	at org.robolectric.res.android.CppAssetManager.lambda$appendPathToResTable$0(CppAssetManager.java:577)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.res.android.CppAssetManager.appendPathToResTable(CppAssetManager.java:575)
	at org.robolectric.res.android.CppAssetManager.lambda$getResTable$1(CppAssetManager.java:716)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.res.android.CppAssetManager.getResTable(CppAssetManager.java:709)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:817)
	at org.robolectric.res.android.CppAssetManager.getResources(CppAssetManager.java:813)
	at org.robolectric.shadows.ShadowArscAssetManager.getStringBlockCount(ShadowArscAssetManager.java:1323)
	at android.content.res.AssetManager.getStringBlockCount(AssetManager.java)
	at android.content.res.AssetManager.makeStringBlocks(AssetManager.java:257)
	at android.content.res.AssetManager.addAssetPath(AssetManager.java:615)
	at android.content.pm.PackageParser.loadApkIntoAssetManager(PackageParser.java:840)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:857)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:822)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:742)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
```

### Steps to Reproduce

1). Into an existing project create a new module as `dynamic-feature`
2). Create a test class and add annotation `@RunWith(RobolectricTestRunner::class)` 
3). Run test

### Robolectric & Android Version

Robolectric: 4.4-SNAPSHOT
Android: 3.6 beta 4

### Link to a public git repo demonstrating the problem:

https://github.com/VMadalin/kotlin-sample-app add the following test on any feature (an dynamic-feature) module:

```java
class CharactersFavoriteFragmentTest : TestRobolectric() {

    @Test
    fun test() {  }
}
```

The same test on [core](https://github.com/VMadalin/kotlin-sample-app/blob/master/core/src/test/kotlin/com/vmadalin/core/database/charactersfavorite/CharacterFavoriteDaoTest.kt) (an android.library module) works correctly.

**Comment by VMadalin** [comment]
Exist another issue reated with `dynamic-feature` but with a different message here: https://github.com/robolectric/robolectric/issues/5105 (https://issuetracker.google.com/issues/123441249)

**Comment by utzcoz** [comment]
Hi @vmadalin , thanks for reporting this problem. Robolectric doesn't work correctly with dynamic-features. And there is a related issue https://github.com/robolectric/robolectric/issues/5597 with more discussion. If you have any question about it, you can post at https://github.com/robolectric/robolectric/issues/5597.
