### ISSUE TITLE
how to Shadow NtpTrustedTime (Android Pie)

### ISSUE THREAD

**Issue by triedwithlove** [robolectric/robolectric#5392]
### Description
I am using NtpTrustedTome in a class to check the validity of a token.
Before the unittest written to test the class, I created  

**@Implements(ShadowSystemClock.class)
public class CustomSystemClock {

    public static long 	currentTimeMillis() {
        return 19000;
    }
}**

Here is the beginning of my Test class
**@Config(shadows={CustomSystemClock.class})
public class MyCustomParserTest {...}**

The test failed with the following message 
java.lang.NullPointerException
	at android.util.NtpTrustedTime.getInstance(NtpTrustedTime.java:64)

### Steps to Reproduce
mMockContext = mock(Context.class);
is the context I will be using 

create a class in AOSP using the NtpTrustedTime to compare time with the one returned by currentTimeMillis

### Robolectric & Android Version
robolectric v4.0,2
gradle-5.4.1-bin
android Pie (sdk 28)

### Link to a public git repo demonstrating the problem:
confidential project

Actually I am looking for a way to shadow that Class cause **ShadowSystemClock** is actually shadowing **android.os.SystemClock.class** not **android.util.NtpTrustedTime**
Thank you

**Comment by triedwithlove** [comment]
I added the following in the build.gradle file
**testImplementation "androidx.test:core:1.0.0"**

The context has been updated to 
**mMockContext = ApplicationProvider.getApplicationContext();**

 and the new error now is 
**java.lang.NoSuchMethodError: java.net.InetAddress.getByNameOnNet(Ljava/lang/String;I)Ljava/net/InetAddress;**

	at android.net.Network.getByName(Network.java:140)
	at android.net.SntpClient.requestTime(SntpClient.java:93)
	at android.util.NtpTrustedTime.forceRefresh(NtpTrustedTime.java:117)
	at android.util.NtpTrustedTime.forceRefresh(NtpTrustedTime.java:92)

Hope someone could help me on this

**Comment by triedwithlove** [comment]
**Created this file**
@Implements(NtpTrustedTime.class)
public class CustomNtpTrustedTime {
    public void forceRefresh() {}
    .....
}

**Added into the build.gradle file**
testImplementation files("../../common_lib/robolectric/v3/runtime/android-all-4.4_r1-robolectric-1.jar")

**Updated the beguining of the Class**
@config(shadows={CustomNtpTrustedTime.class})
public class MyCustomParserTest {...}

this solved My issue
