### ISSUE TITLE
java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets in robolectric

### ISSUE THREAD

**Issue by AndrewGong2016** [robolectric/robolectric#5396]
### Steps to Reproduce
build.gradle:
    testOptions {
        unitTests.includeAndroidResources = true
    }

### Robolectric & Android Version
    testImplementation 'org.robolectric:robolectric:4.3.1';
    Android Q;
    compileSdkVersion 29;
targetSdkVersion 29;
### Link to a public git repo demonstrating the problem:

```
D:\IDEandroidstudio\jdk-9+181_windows-x64_ri\java-se-9-ri\jdk-9\bin\java.exe -ea -Didea.test.cyclic.buffer.size=1048576 -javaagent:D:\IDEandroidstudio\lib\idea_rt.jar=4088:D:\IDEandroidstudio\bin -Dfile.encoding=UTF-8 -classpath D:\IDEandroidstudio\lib\idea_rt.jar;D:\IDEandroidstudio\plugins\junit\lib\junit-rt.jar;D:\IDEandroidstudio\plugins\junit\lib\junit5-rt.jar;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\intermediates\javac\debugUnitTest\classes;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\intermediates\javac\debug\classes;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\intermediates\unit_test_config_directory\debugUnitTest\out;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\generated\res\resValues\debug;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\junit\junit\4.12\2973d150c0dc1fefe998f834810d68f278ea58ec\junit-4.12.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-library\1.3\4785a3c21320980282f9f33d0d1264a69040538f\hamcrest-library-1.3.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\javax.inject\javax.inject\1\6975da39a7040257bd51d21a231b76c915872d38\javax.inject-1.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\6736845452a1b4a43dd9123048998c64\monitor-1.2.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\robolectric\4.3.1\b7374ec0a3695a741ca984b9eaaa80632fb4a7f0\robolectric-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\shadows-framework\4.3.1\da048a93951f4d9e46519749c53b0f868dfdf425\shadows-framework-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.android.apps.common.testing.accessibility.framework\accessibility-test-framework\2.1\c2d6267c3ad0435ddf9e27a94a0e0af4ca3fdfbb\accessibility-test-framework-2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.mockito\mockito-core\1.10.19\e8546f5bef4e061d8dd73895b4e8f40e3fe6effe\mockito-core-1.10.19.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\junit\4.3.1\4f04c077a385c47801946ffa080a6beb19ba9ee\junit-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\resources\4.3.1\ccc69608304ec4c36e8b26d7fe7f48d7bec1dd0b\resources-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\sandbox\4.3.1\4b1b82b661ebc747a6e4ddcfdbfc939e9cd24886\sandbox-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\plugins-maven-dependency-resolver\4.3.1\8b9d224707c0eff28ec39e9d7b33774c7b128d25\plugins-maven-dependency-resolver-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\utils\4.3.1\ae572384d7fc49713ef3fc2061a81b45aefe9eb7\utils-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\pluginapi\4.3.1\48807e74eba780ea0261de605c021195f511f990\pluginapi-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\shadowapi\4.3.1\a93e55b36c418aa3afc17c26eac82590a3bfb63e\shadowapi-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\annotations\4.3.1\5ba2cdb5be608a05ae01e27c8d3675a86b34b4f3\annotations-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-ant-tasks\2.1.3\b09be554228d66d208e5fef5266844aacf443abc\maven-ant-tasks-2.1.3.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant\1.8.0\7b456ca6b93900f96e58cc8371f03d90a9c1c8d1\ant-1.8.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.ant\ant-launcher\1.8.0\8b53ba16fa62fb1034da8f1de200ddc407c8381\ant-launcher-1.8.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-project\2.2.1\8239e98c16f641d55a4ad0e0bab0aee3aff8933f\maven-project-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact-manager\2.2.1\ec355b913c34d37080810f98e3f51abecbe1572b\maven-artifact-manager-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-error-diagnostics\2.2.1\e81bb342d7d172f23d108dc8fa979a1facdcde8e\maven-error-diagnostics-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-settings\2.2.1\2236ffe71fa5f78ce42b0f5fc22c54ed45f14294\maven-settings-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-profile\2.2.1\3950071587027e5086e9c395574a60650c432738\maven-profile-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-plugin-registry\2.2.1\72a24b7775649af78f3986b5aa7eb354b9674cfd\maven-plugin-registry-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-container-default\1.0-alpha-9-stable-1\94aea3010e250a334d9dab7f591114cd6c767458\plexus-container-default-1.0-alpha-9-stable-1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\classworlds\classworlds\1.1-alpha-2\5adf2e681c57d7f48038b602f3ca2254ee82d47\classworlds-1.1-alpha-2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\2.2.1\23600f790d4dab2cb965419eaa982e3e84c428f8\maven-artifact-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model\2.2.1\c0a1c17436ec3ff5a56207c031d82277b4250a29\maven-model-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-file\1.0-beta-6\6c53633505460caf49d2660de1e24744d915afb9\wagon-file-1.0-beta-6.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-lightweight\1.0-beta-6\b3815078570c3b1f0667e123d59717c6b726c6c2\wagon-http-lightweight-1.0-beta-6.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-http-shared\1.0-beta-6\ccd70d7e0d8c085e648a83f072da06ca9a53be94\wagon-http-shared-1.0-beta-6.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-provider-api\1.0-beta-6\3f952e0282ae77ae59851d96bb18015e520b6208\wagon-provider-api-1.0-beta-6.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-repository-metadata\2.2.1\98f0c07fcf1eeb213bef8d9316a9935184084b06\maven-repository-metadata-2.2.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-utils\1.5.15\c689598ce1eb94c304817877ed15911099972526\plexus-utils-1.5.15.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interpolation\1.11\ad9dddff6043194904ad1d2c00ff1d003c3915f7\plexus-interpolation-1.11.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\backport-util-concurrent\backport-util-concurrent\3.1\682f7ac17fed79e92f8e87d8455192b63376347b\backport-util-concurrent-3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\nekohtml\xercesMinimal\1.9.6.2\d1c5e063683a0e6f77cd5f051a9d4af48346fa6\xercesMinimal-1.9.6.2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\nekohtml\nekohtml\1.9.6.2\2d960be7b62ae6622dbbbe49ab4ffdc609f85c80\nekohtml-1.9.6.2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.robolectric\utils-reflector\4.3.1\2e8444b02656d03df82334c6f2b062a3da46f0bc\utils-reflector-4.3.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\7.0\478006d07b7c561ae3a92ddc1829bca81ae0cdd1\asm-commons-7.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-util\7.0\18d4d07010c24405129a6dbb0e92057f8779fb9d\asm-util-7.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\7.0\4b310d20d6f1c6b7197a75f1b5d69f169bc8ac1f\asm-analysis-7.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\7.0\29bc62dcb85573af6e62e5b2d735ef65966c4180\asm-tree-7.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\7.0\d74d4ba0dee443f68fb2dcb7fcdb945a2cd89912\asm-7.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.auto.service\auto-service\1.0-rc4\44954d465f3b9065388bbd2fc08a3eb8fd07917c\auto-service-1.0-rc4.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.auto\auto-common\0.8\c6f7af0e57b9d69d81b05434ef9f3c5610d498c4\auto-common-0.8.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\27.0.1-jre\bd41a290787b5301e63929676d792c507bbc00ae\guava-27.0.1-jre.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.guava\failureaccess\1.0.1\1dcf1de382a0bf95a3d8b0849546c88bac1292c9\failureaccess-1.0.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\b421526c5f297295adef1c886e5246c39d4ac629\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\3.0.2\25ea2e8b0c338a877313bd4672d3fe056ea78f0d\jsr305-3.0.2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-qual\2.5.2\cea74543d5904a30861a61b4643a5f2bb372efc4\checker-qual-2.5.2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.errorprone\error_prone_annotations\2.2.0\88e3c593e9b3586e1c6177f89267da6fc6986f0c\error_prone_annotations-2.2.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.j2objc\j2objc-annotations\1.1\ed28ded51a8b1c6b112568def5f4b455e6809019\j2objc-annotations-1.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.codehaus.mojo\animal-sniffer-annotations\1.17\f97ce6decaea32b36101e37979f8b647f00681fb\animal-sniffer-annotations-1.17.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\javax.annotation\javax.annotation-api\1.3.2\934c04d3cfef185a8008e7bf34331b79730a9d43\javax.annotation-api-1.3.2.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.almworks.sqlite4java\sqlite4java\0.282\745a7e2f35fdbe6336922e0d492c979dbbfa74fb\sqlite4java-0.282.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.ibm.icu\icu4j\53.1\786d9055d4ca8c1aab4a7d4ac8283f973fd7e41f\icu4j-53.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\2.6.1\d9521f2aecb909835746b7a5facf612af5e890e8\protobuf-java-2.6.1.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.52\88a941faf9819d371e3174b5ed56a3f3f7d73269\bcprov-jdk15on-1.52.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\124b421a2210e371a1481a830acf3677\core-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\124b421a2210e371a1481a830acf3677\core-1.0.0\res;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\androidx.collection\collection\1.1.0\1f27220b47669781457de0d600849a5de0e89909\collection-1.1.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\androidx.lifecycle\lifecycle-common\2.1.0\c67e7807d9cd6c329b9d0218b2ec4e505dd340b7\lifecycle-common-2.1.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\androidx.arch.core\core-common\2.1.0\b3152fc64428c9354344bd89848ecddc09b6f07e\core-common-2.1.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\androidx.annotation\annotation\1.1.0\e3a6fb2f40e3a3842e6b7472628ba4ce416ea4c8\annotation-1.1.0.jar;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\androidx.constraintlayout\constraintlayout-solver\1.1.3\54abe9ffb22cc9019b0b6fcc10f185cc4e67b34e\constraintlayout-solver-1.1.3.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\f5bdf8930f5b0dade80802408310dda6\appcompat-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\f5bdf8930f5b0dade80802408310dda6\appcompat-1.1.0\res;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\df9a84c4655b7cf6fd3ecff2821fd9d3\fragment-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\a44642c3bddc1cd9ae77529ce5394be3\appcompat-resources-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\a44642c3bddc1cd9ae77529ce5394be3\appcompat-resources-1.1.0\res;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\3d66247cb3e229dc7753f5f4d3b35b4b\drawerlayout-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\7ae8c1d65b7331eeb350edf91287a16c\viewpager-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\de3b4aff63e255359d6d83ac6fbdaff5\loader-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\b96b3435fb358bdd7f04f1152639314c\activity-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\bf0848ee243e36dc13961016c6f63543\vectordrawable-animated-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\9572194aa98bde0ee13f87e0985824cf\vectordrawable-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\2dfde23a071269bfc073d57af77f7873\customview-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\7f6c41cc2a14c0fbaa8d0166c17dc544\core-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\7f6c41cc2a14c0fbaa8d0166c17dc544\core-1.1.0\res;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\fb37b7f790edcc9d7fe6d3e5314b8c56\cursoradapter-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\9a29ee90fd211f611caccd9d338a3e44\versionedparcelable-1.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\55566c395264c409f125230efea7fd76\lifecycle-viewmodel-2.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\1bd2f6a321d0549948d7f1edb5f036d6\lifecycle-runtime-2.1.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\f031147607d3aeb238f176a00d5e308c\savedstate-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\e7284bace20bec096294b5474e153fbf\lifecycle-livedata-2.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\c073c929da6ad4e112abaac7d3212747\lifecycle-livedata-core-2.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\2d1f640c1b4beb33089ff5c91bbd7f31\interpolator-1.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\e72949b043b8df7a6068dab5e7cd21f2\core-runtime-2.0.0\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\c1763829f79bc3811543d2bb9a22b866\constraintlayout-1.1.3\jars\classes.jar;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\c1763829f79bc3811543d2bb9a22b866\constraintlayout-1.1.3\res;C:\Users\andrew.gong\.gradle\caches\modules-2\files-2.1\org.objenesis\objenesis\2.1\87c0ea803b69252868d09308b4618f766f135a96\objenesis-2.1.jar;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\intermediates\sourceFolderJavaResources\test\debug;D:\AndroidProjects\GitRepo\SparseArrayTest\app\build\intermediates\sourceFolderJavaResources\debug;C:\Users\andrew.gong\.gradle\caches\transforms-2\files-2.1\991e4d7aa867133a630a728bf0e563cd\android.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 com.android.sparsearraytest.MainActivityTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.robolectric.util.ReflectionHelpers$6 (file:/C:/Users/andrew.gong/.gradle/caches/modules-2/files-2.1/org.robolectric/shadowapi/4.3.1/a93e55b36c418aa3afc17c26eac82590a3bfb63e/shadowapi-4.3.1.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.robolectric.util.ReflectionHelpers$6
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Robolectric] com.android.sparsearraytest.MainActivityTest.testActivity: sdk=29; resources=BINARY

java.lang.NoClassDefFoundError: [Landroid/content/res/ApkAssets;

	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3139)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3164)
	at java.base/java.lang.Class.getMethods(Class.java:1861)
	at org.robolectric.util.reflector.ReflectorClassWriter.write(ReflectorClassWriter.java:96)
	at org.robolectric.util.reflector.Reflector.getBytecode(Reflector.java:151)
	at org.robolectric.util.reflector.Reflector.createReflectorClass(Reflector.java:105)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:64)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:48)
	at org.robolectric.shadows.ShadowArscAssetManager10.reset(ShadowArscAssetManager10.java:236)
	at org.robolectric.Shadows.reset(Shadows.java:2133)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:486)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:334)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:332)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:261)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: android.content.res.ApkAssets
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:164)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:119)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:112)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:111)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 21 more


Process finished with exit code -1
```

**Comment by AndrewGong2016** [comment]
I have solve the issue by delete ‘.m2' directory and download them when run my unit case.
It seems maven lost  android.content.res.ApkAssets in my local repository, and I download android-all-10-robolectric-5803371 from https://www.mvnjar.com/org.robolectric/android-all/10-robolectric-5803371/detail.html ,and  replace the whole android-all-10-robolectric-5803371.jar in local repository

**Comment by hoisie** [comment]
Seems like this has been resolved, closing. If it is still ongoing let me know and I'll reopen.
