### ISSUE TITLE
Parcel.obtain not working on newer API levels

### ISSUE THREAD

**Issue by henrikpersson** [robolectric/robolectric#5421]
### Description
For some reason `mReadWriteHelper` seem to stay uninitialised. Any ideas?

### Steps to Reproduce
```
@RunWith(RobolectricTestRunner.class)
public class TestParcel {

    @Test
    @Config(sdk = 22)
    public void testOld() {
        Parcel parcel = Parcel.obtain();
        parcel.writeString("foo");
    }

    @Test
    @Config(sdk = 27)
    public void testNew() {
        Parcel parcel = Parcel.obtain();
        parcel.writeString("foo");
    }
}
```

`testNew` fails with: 

```
[Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
[Robolectric] com.example.TestParcel.testNew: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28



java.lang.NullPointerException
	at android.os.Parcel.writeString(Parcel.java:704)
	at com.example.auto.TestParcel.testNew(TestParcel.java:23)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


[Robolectric] com.example.TestParcel.testOld: sdk=22; resources=BINARY
```

### Robolectric & Android Version
Robolectric 4.3.1

**Comment by hoisie** [comment]
Can you try this in Robolectric 4.4?

**Comment by hoisie** [comment]
I was not able to repro this (either in 4.3.1 or later), so I am going to assume it's either been fixed or it is a transitive issue. Feel free to reopen if this issue persists.
