### ISSUE TITLE
NPE buildActivity/setupActivity

### ISSUE THREAD

**Issue by Mxiim** [robolectric/robolectric#5438]
### Description
I am having issue with Roboelectric after I upgraded a project to androidX. Was able to reproduce with minimal code (https://github.com/Mxiim/AndroidExample).

Specific line of code that fails is:
`
FragmentActivity activity = Robolectric.buildActivity(FragmentActivity.class).create().get();
`
I also tried
`
FragmentActivity activity = Robolectric.setupActivity(FragmentActivity.class);
`
but getting same error (see Stacktrace below). 

Gradle 5.4.1 (tried with 6 and 4.4)
Android build gradle 3.5.3 (tried 3.2.1)
Roboelectric version 3.7.1 (tried with 3.8.0 and 4.3)
Tried adding includeAndroidResources=true and returnDefaultValues=true in testOptions (build.gradle)

### Stacktrace:
java.lang.NullPointerException
  at org.robolectric.internal.bytecode.ShadowImpl.extract(ShadowImpl.java:17)
  at org.robolectric.shadow.api.Shadow.extract(Shadow.java:25)
  at org.robolectric.Shadows.shadowOf(Shadows.java:1272)
  at org.robolectric.android.controller.ComponentController.<init>(ComponentController.java:30)
  at org.robolectric.android.controller.ComponentController.<init>(ComponentController.java:22)
  at org.robolectric.android.controller.ActivityController.<init>(ActivityController.java:33)
  at org.robolectric.android.controller.ActivityController.of(ActivityController.java:25)
  at org.robolectric.Robolectric.buildActivity(Robolectric.java:84)
  at org.robolectric.Robolectric.buildActivity(Robolectric.java:80)
  at org.robolectric.Robolectric.setupActivity(Robolectric.java:88)
  at com.example.testapp.ClientSwagTest.setup(ClientSwagTest.java:25)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
  at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
  at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
### Steps to Reproduce
See link to repo, using android studio to run the tests
### Link to a public git repo demonstrating the problem:
https://github.com/Mxiim/AndroidExample

I also tried changing roboelectric to 4.3, android gradle to 3.2.1 and @RunWith(RobolectricTestRunner.class) --- in that case the error I am getting is 'Robolectric doesn't support legacy mode after P'.

I wonder if anyone knows a possible solution or even a hack that does not involve changing much of the code, because it is also used by another build system which does not use gradle at all. 
However, I appreciate all solutions that can help fix it.
I think in general, it is some issue with gradle-android because the tests work when we use the other build system.

**Comment by utzcoz** [comment]
@Mxiim could you help to re-test it with latest Robolectric 4.7.3 and AndroidX Test/Espresso?

**Comment by utzcoz** [comment]
> @Mxiim could you help to re-test it with latest Robolectric 4.7.3 and AndroidX Test/Espresso?

Please re-test it with latest Robolectric, and feel free to reopen this issue if this issue still exists. Thanks.
