### ISSUE TITLE
Firebase initialization fails with Robolectric

### ISSUE THREAD

**Issue by leventepal** [robolectric/robolectric#5454]
Edit: Downgraded to 4.2.1 now it's working.

### Description
Can't run tests with Robolectric, I'm getting the following exception:
`java.lang.IllegalStateException: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect`

### Steps to Reproduce
Just simply write a unit test having firebase then run the tests

### Robolectric & Android Version
Robolectric 4.3.1 & Android SDK 28

**Test class**:
`
    @RunWith(RobolectricTestRunner::class)
    @Config(sdk = [Build.VERSION_CODES.P])
    class SimpleUnitTest {

    @Test
    fun testMe() {

    }
`

**Application class**:
`    
    class App: MultiDexApplication  {

    override fun onCreate() {
        super.onCreate()

        FirebaseApp.initializeApp(this)
        // ....
}
`

**Full stacktrace**:
`
"C:\Program Files\Android\Android Studio\jre\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=5144576 "-javaagent:C:\Program Files\Android\Android Studio\lib\idea_rt.jar=56081:C:\Program Files\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\manman\AppData\Local\Temp\classpath993112459.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 com.myapp.SimpleUnitTest 
[Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
[Robolectric] com.myapp.SimpleUnitTest.testMe: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28

java.lang.IllegalStateException: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect

	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:265)
	at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:334)
	at com.google.firebase.internal.DataCollectionConfigStorage.readAutoDataCollectionEnabled(com.google.firebase:firebase-common@@19.3.0:74)
	at com.google.firebase.internal.DataCollectionConfigStorage.<init>(com.google.firebase:firebase-common@@19.3.0:49)
	at com.google.firebase.FirebaseApp.lambda$new$0(com.google.firebase:firebase-common@@19.3.0:426)
	at com.google.firebase.FirebaseApp$$Lambda$1.get(com.google.firebase:firebase-common@@19.3.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.FirebaseApp.isDataCollectionDefaultEnabled(com.google.firebase:firebase-common@@19.3.0:375)
	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(com.google.android.gms:play-services-measurement-api@@17.2.1:17)
	at com.google.firebase.analytics.connector.internal.zzb.create(com.google.android.gms:play-services-measurement-api@@17.2.1:6)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(com.google.firebase:firebase-components@@16.0.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.myapp.MyApp.onCreate(App.kt:30)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:60)
	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
	at org.robolectric.shadows.ShadowLinux.stat(ShadowLinux.java:30)
	at libcore.io.Linux.stat(Linux.java)
	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
	at android.system.Os.stat(Os.java:565)
	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:147)
	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:58)
	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
	at org.robolectric.shadows.ShadowLinux.stat(ShadowLinux.java:30)
	at libcore.io.Linux.stat(Linux.java)
	at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$stat(BlockGuardOs.java:328)
	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java)
	at android.system.Os.$$robo$$android_system_Os$stat(Os.java:565)
	at android.system.Os.stat(Os.java)
	at android.app.SharedPreferencesImpl.$$robo$$android_app_SharedPreferencesImpl$loadFromDisk(SharedPreferencesImpl.java:147)
	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java)
	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
	at android.app.SharedPreferencesImpl$1.$$robo$$android_app_SharedPreferencesImpl_1$run(SharedPreferencesImpl.java:122)
	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java)

Process finished with exit code -1
`

**Comment by drizzd** [comment]
See also #5186.

**Comment by expilu** [comment]
I have this bug too.
For now I've fixed it by downgrading Robolectric to 4.2 [as mentioned](https://github.com/robolectric/robolectric/issues/5186#issuecomment-544930108_) in #5186

**Comment by Kisty** [comment]
Wouldn't a shadow artifact for Firebase fix this? Just ran in to this migrating from Fabric Crashlytics to Firebase Crashlytics

**Comment by hoisie** [comment]
This has been fixed in #5186, update to at least 4.5-alpha-1
