### ISSUE TITLE
State is retained across tests.

### ISSUE THREAD

**Issue by ww2lin** [robolectric/robolectric#5484]
### Description
When WorkManager is set up to be lazily loaded and running roboelectric tests. It looks like Application is recreated but the WorkManager state is still retained.

### Steps to Reproduce
1. Remove eagerly loading of WorkManager(https://developer.android.com/topic/libraries/architecture/workmanager/advanced/custom-configuration) inside manifest.
        <provider
            android:name="androidx.work.impl.WorkManagerInitializer"
            android:authorities="${applicationId}.workmanager-init"
            android:exported="false"
            tools:node="remove" /> 

2. Have WorkManager call initialize inside Application#onCreate(see below).
3. Any test file contains at least two tests.
4. Run the test on the test file, the first test will pass while the sequential test will complain about WorkManager is already initialized. 

### Link to a public git repo demonstrating the problem:
// Inside Application.java
    public void onCreate() {
        super.onCreate();
        sInstance = this;

            final Configuration workManagerConfig = new Configuration.Builder()
                .setMinimumLoggingLevel(Log.INFO)
                .build();

            WorkManager.initialize(
                new CredentialProtectedStorageContextWrapper(this), workManagerConfig);
    }

### Robolectric & Android Version
Robolectric: 4.3.1
Android Q

Logs:
java.lang.IllegalStateException: WorkManager is already initialized.  Did you try to initialize it manually without disabling WorkManagerInitializer? See WorkManager#initialize(Context, Configuration) or the class level Javadoc for more information.
	at androidx.work.impl.WorkManagerImpl.initialize(WorkManagerImpl.java:173)
	at androidx.work.WorkManager.initialize(WorkManager.java:207)
	at com.android.euicc.EuiccApplication.onCreate(EuiccApplication.java:88)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:270)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:270)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:168)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:298)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:251)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hoisie** [comment]
Have you looked at this issue:

https://github.com/robolectric/robolectric/issues/4788

Seems like others have found a way to use WorkManager in Robolectric tests.
