### ISSUE TITLE
Robolectric's BluetoothAdapter gives null pointer on method calls

### ISSUE THREAD

**Issue by brianreinhold** [robolectric/robolectric#5501]
### Description
Calling BluetoothAdapter.getDefaultAdapter().getBluetoothLeScanner() does this
`java.lang.NullPointerException
	at android.bluetooth.BluetoothAdapter.getLeState(BluetoothAdapter.java:950)
	at android.bluetooth.BluetoothAdapter.getLeAccess(BluetoothAdapter.java:960)
	at android.bluetooth.BluetoothAdapter.getBluetoothLeScanner(BluetoothAdapter.java:721)
	at com.pcha.androidbtmanager.BtScannerTests.showRobolecricFailsBluetoothAdapter(BtScannerTests.java:49)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
### Steps to Reproduce

Run this test (sorry the formatting of the code is always corrupted. Don't know why. I have tried various combinations and after 15 minutes I gave up. I guess this web app cannot handle code.)

`    @RunWith(AndroidJUnit4.class)
    //@RunWith(RobolectricTestRunner.class)  // makes no difference which runner I use
    @Config(sdk = Build.VERSION_CODES.P)
    public class BtScannerTests
    {
        private BluetoothAdapter bluetoothAdapter;
        //private final Context context = RuntimeEnvironment.systemContext;
    
        @Before
        public void setUp() throws Exception
        {
    
            bluetoothAdapter = Shadow.newInstanceOf(BluetoothAdapter.class);
    
            // Makes no difference
            shadowOf(bluetoothAdapter).setState(BluetoothAdapter.STATE_ON);
            shadowOf(bluetoothAdapter).setEnabled(true);
        }
    
        @Test
        public void showRobolecricFailsBluetoothAdapter()
        {
            bluetoothAdapter.getBluetoothLeScanner();
        }
    
    }
`
### Robolectric & Android Version
Robolectric 4.3.1  Android 28

**Comment by hoisie** [comment]
Use [BluetoothAdapter.getDefaultAdapter()](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#getDefaultAdapter()), not `Shadow.newInstanceOf(BluetoothAdapter.class)`. When you do `Shadow.newInstanceOf(BluetoothAdapter.class)`, you are creating an empty instance with no member variables initialized, which will result in NPEs most of the time. I am looking into feasibility of dropping `Shadow.newInstanceOf` APIs by default.
