### ISSUE TITLE
java.lang.NullPointerException with  java.base/java.io.File.length when having extended File class in test.

### ISSUE THREAD

**Issue by Malachiasz** [robolectric/robolectric#5522]
### Description
It's a regression error. Doesn't happen with Robolectric 4.3.1, but is observed with the latest 4.4-SNAPSHOT version. I have a class extending File class. Whenever it appears in Robolectric test, even as a mock it crashes.

### Robolectric & Android Version
Oracle JDK 11
Android Compile SKD 29
build tools 29.0.3
Gradle 6.2.2
Robolectric 4.4-SNAPSHOT

```
java.lang.NullPointerException
	at java.base/java.io.File.isInvalid(File.java:186)
	at java.base/java.io.File.length(File.java:983)
	at com.mydomain.network.UploadTransferTest.testTotalFileSizeWithZeroLengthFile(UploadTransferTest.java:306)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:544)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The class which causes crash:

```
public class UploadFile extends File {

    private final String displayedName;
    private final CDashResult cDashResult;

    public UploadFile(@NonNull File file, @NonNull String virtualName, @NonNull CDashResult cDashResult) {
        super(file.getAbsolutePath());
        this.displayedName = virtualName;
        this.cDashResult = cDashResult;
    }

    @NonNull
    public String getDisplayedName() {
        return displayedName;
    }

    @NonNull
    public CDashResult getcDashResult() {
        return cDashResult;
    }
}

```

**Comment by ZacSweers** [comment]
We've observed this as well, but worked around it by just using `TemporaryFolder` more. Pretty much ever case was really better off using that anyway

**Comment by andersu** [comment]
Same issue. Mocking a `File` in a Robolectric test. Works with 4.3.1, but NullPointerException with `4.4-beta-1`.
