### ISSUE TITLE
Robolectric fails on Windows when includeAndroidResources=true

### ISSUE THREAD

**Issue by Bradleycorn** [robolectric/robolectric#5528]
### Description
When using Robolectric 4.3.1 (or 4.3) on Windows and the build.gradle has `includeAndroidResources=true`, Robolectric tests fail with an error message. 

### Steps to Reproduce
**Using a Windows machine**, setup an android project using Android Studio 3.6.1 and configure it to use robolectric for tests according to the "Getting Started" page on the Robolectric web site. Specifically, be sure to 
include the following in your `build.gradle`:

```
android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

Now, build some tests using Robolectric and run them. They fail, and the error output is:
```
[Robolectric] com.myapp.mycomponent.remove: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28

java.lang.IllegalStateException: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
```

Put the EXACT SAME project on a mac, and the tests run fine.

### Robolectric & Android Version
Robolectric: 4.3 (or 4.3.1)
Android Studio: 3.6.1

**Comment by xian** [comment]
Is there any further info/stacktrace in the test report?

**Comment by Bradleycorn** [comment]
@xian here's the full output with stack trace:

```
Downloading from maven 
[Robolectric] com.app.MyApp.data.store.JwtTokenStoreTest.remove: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28



java.lang.IllegalStateException: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect

	at android.app.SharedPreferencesImpl.awaitLoadedLocked(SharedPreferencesImpl.java:265)
	at android.app.SharedPreferencesImpl.contains(SharedPreferencesImpl.java:334)
	at com.google.firebase.internal.DataCollectionConfigStorage.readAutoDataCollectionEnabled(com.google.firebase:firebase-common@@19.3.0:74)
	at com.google.firebase.internal.DataCollectionConfigStorage.<init>(com.google.firebase:firebase-common@@19.3.0:49)
	at com.google.firebase.FirebaseApp.lambda$new$0(com.google.firebase:firebase-common@@19.3.0:426)
	at com.google.firebase.FirebaseApp$$Lambda$1.get(com.google.firebase:firebase-common@@19.3.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.FirebaseApp.isDataCollectionDefaultEnabled(com.google.firebase:firebase-common@@19.3.0:375)
	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.getInstance(com.google.android.gms:play-services-measurement-api@@17.2.2:17)
	at com.google.firebase.analytics.connector.internal.zzc.create(com.google.android.gms:play-services-measurement-api@@17.2.2:6)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(com.google.firebase:firebase-components@@16.0.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
	at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
	at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
	at com.google.firebase.abt.component.AbtRegistrar.lambda$getComponents$0(com.google.firebase:firebase-abt@@19.0.0:45)
	at com.google.firebase.abt.component.AbtRegistrar$$Lambda$1.create(com.google.firebase:firebase-abt@@19.0.0)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(com.google.firebase:firebase-components@@16.0.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
	at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
	at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
	at com.google.firebase.remoteconfig.RemoteConfigRegistrar.lambda$getComponents$0(com.google.firebase:firebase-config@@19.0.4:55)
	at com.google.firebase.remoteconfig.RemoteConfigRegistrar$$Lambda$1.create(com.google.firebase:firebase-config@@19.0.4)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(com.google.firebase:firebase-components@@16.0.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:27)
	at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-components@@16.0.0:35)
	at com.google.firebase.components.RestrictedComponentContainer.get(com.google.firebase:firebase-components@@16.0.0:83)
	at com.google.firebase.perf.zza.create(com.google.firebase:firebase-perf@@19.0.5:4)
	at com.google.firebase.components.ComponentRuntime.lambda$new$0(com.google.firebase:firebase-components@@16.0.0:69)
	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(com.google.firebase:firebase-components@@16.0.0)
	at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-components@@16.0.0:53)
	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-components@@16.0.0:158)
	at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@19.3.0:563)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:304)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:268)
	at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:253)
	at com.my.app.MyApp.onCreate(MyApp.kt:99)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:276)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:276)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:169)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:301)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:243)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:60)
	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
	at org.robolectric.shadows.ShadowLinux.stat(ShadowLinux.java:30)
	at libcore.io.Linux.stat(Linux.java)
	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
	at android.system.Os.stat(Os.java:565)
	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:147)
	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:428)
	at java.io.File.getCanonicalPath(File.java:618)
	at org.robolectric.shadows.OsConstantsValues.canonicalize(OsConstantsValues.java:58)
	at org.robolectric.shadows.OsConstantsValues.getMode(OsConstantsValues.java:50)
	at org.robolectric.shadows.ShadowLinux.stat(ShadowLinux.java:30)
	at libcore.io.Linux.stat(Linux.java)
	at libcore.io.BlockGuardOs.$$robo$$libcore_io_BlockGuardOs$stat(BlockGuardOs.java:328)
	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java)
	at android.system.Os.$$robo$$android_system_Os$stat(Os.java:565)
	at android.system.Os.stat(Os.java)
	at android.app.SharedPreferencesImpl.$$robo$$android_app_SharedPreferencesImpl$loadFromDisk(SharedPreferencesImpl.java:147)
	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java)
	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
	at android.app.SharedPreferencesImpl$1.$$robo$$android_app_SharedPreferencesImpl_1$run(SharedPreferencesImpl.java:122)
	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java)

```

**Comment by hameno** [comment]
Same problem here, even on 4.4-SNAPSHOT not working

**Comment by hoisie** [comment]
Fixed in https://github.com/robolectric/robolectric/pull/5897
