### ISSUE TITLE
Memory Leak In CppAssetManager2

### ISSUE THREAD

**Issue by abed-quayo** [robolectric/robolectric#5530]
### Description
I am trying to iterate a test case 1000+ times, the memory is being consumed gradually every time a new instance of **ActivityScenario** is created.

Heap dump:
![Untitled](https://user-images.githubusercontent.com/57088178/76774406-8d3f6780-67ac-11ea-815e-5d7ec1e91a5a.png)
![Untitled1](https://user-images.githubusercontent.com/57088178/76774408-8e709480-67ac-11ea-8f64-cca13c389eca.png)
![Untitled2](https://user-images.githubusercontent.com/57088178/76774409-8f092b00-67ac-11ea-9f5b-d6a4decb39af.png)

The issue class is CppAssetManager2, it's noticeable that the Theme-related objects are retained regardless of the activity state.
### Steps to Reproduce
```
        ActivityScenario<Activity> scenario;
        for(int i = 0; i < n; i++) {
            scenario = ActivityScenario.launch(intent);
            scenario.onActivity(new ActivityScenario.ActivityAction<Activity>() {
                @Override
                public void perform(Activity activity) {
                    test(activity);
                    activity.finish();
                    scenario.close();
                }
            });
        }
```
### Tried:
```
unitTests.all {
    jvmArgs '-Xmx512m'
}
```

### Robolectric & Android Version
Robolectric 4.3
Android 28

Thanks for your time.

**Comment by pedrovgs** [comment]
I've found the exact same scenario with Robolectric 4.3 and Android 28 using the JDK 8. Is there any update or any workaround we can use? I'm not using the activity scenario but the intent's test rule but looking at visual VM I've found similar data.

**Comment by pedrovgs** [comment]
I'm attaching two screenshots and a heap dump so you can review the details.

This is the base scenario with 4gb max heap size:

![Screenshot 2020-05-04 at 15 36 21](https://user-images.githubusercontent.com/4030704/80971576-47eafe00-8e1d-11ea-875a-247365a2cf4c.png)

If the heap size is configured with 1gb you can see how you'll end up blowing the process because there is no more memory available.

![Screenshot 2020-05-04 at 14 34 21](https://user-images.githubusercontent.com/4030704/80971668-651fcc80-8e1d-11ea-9ca6-fd93e2f475bf.png)


This is the heap dump: https://drive.google.com/open?id=1BneGabbNkZ6hf8qYhR59gHzjocjWCASt


**As a workaround, I've noticed if you downgrade the SDK used by to API 21 the scenario improves a lot. So in case you need it, I'd recommend you change the SDK used.**

**Comment by hoisie** [comment]
Does the memory get reclaimed after the test is over?

**Comment by hoisie** [comment]
FTR this seems to be where theme objects are created.

```
	at org.robolectric.shadows.ShadowArscAssetManager10.nativeThemeCreate(ShadowArscAssetManager10.java:1492)
	at android.content.res.AssetManager.nativeThemeCreate(AssetManager.java)
	at android.content.res.AssetManager.createTheme(AssetManager.java:1116)
	at android.content.res.ResourcesImpl$ThemeImpl.__constructor__(ResourcesImpl.java:1347)
	at android.content.res.ResourcesImpl$ThemeImpl.<init>(ResourcesImpl.java)
	at android.content.res.ResourcesImpl.newThemeImpl(ResourcesImpl.java:1317)
	at android.content.res.Resources.newTheme(Resources.java:1884)
	at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:210)
	at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:147)
	at android.app.Activity.setTheme(Activity.java:4948)
	at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:144)
	at org.robolectric.shadows.ShadowActivity.callAttach(ShadowActivity.java:133)
	at org.robolectric.android.controller.ActivityController.attach(ActivityController.java:88)
	at org.robolectric.android.controller.ActivityController.of(ActivityController.java:57)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:89)
	at org.robolectric.android.fakes.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:65)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:40)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:226)
	at com.google.android.robobugs.MainActivityTest.testMultipleActivities(MainActivityTest.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:57)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:59)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by hoisie** [comment]
I looked into this a bit and could not find a quick fix. Seems like a tricky use case to support. There is a  [ShadowArscAssetManager10.nativeThemeDestroy](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowArscAssetManager10.java#L1495-L1500), but that does not seem to be called too often. It seems like that gets called from the ThemeImpl finalizer (http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/content/res/ResourcesImpl.java#1288). However, I don't quite understand the lifecycle of Resources in Robolectric, so I'm not sure what should be responsible for cleaning up the resources of a destroyed activity. I believe in real Android that is partially handled by ActivityManagerService and WindowManagerService, which are not run in Robolectric.

Instead of creating/destroying 1000 activities in a single test, a workaround could be using something like a https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/ParameterizedRobolectricTestRunner.java. In between tests all resetters are run, which should hopefully clear up memory.

**Comment by realdadfish** [comment]
Memory is not cleared up between different test executions, unfortunately. I suspect that the static `Registries.NATIVE_THEME9_REGISTRY` accumulates memory in between tests for the same JVM. The only way to counteract this is to use Gradle's `forkEvery` test setting to keep the JVM not alive for too long, which unfortunately slows down the tests tremendously.

**Comment by hoisie** [comment]
I've been thinking about this on and off and here are some quick ideas:
1) Entries are added to Registries.NATIVE_THEME9_REGISTRY in [AssetManager.nativeThemeCreate](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowArscAssetManager10.java#L1495-L1499)
2) AssetManager.nativeThemeCreate ultimately gets called when Resources.newTheme is called. https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/res/Resources.java;l=1960-1974?q=frameworks%2Fbase%2Fcore%2Fjava%2Fandroid%2Fcontent%2Fres%2FResources.java&ss=android
3) Resources.newTheme gets called whenever an Activity is initialized, either an Android activity or an AndroidX one https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/ContextThemeWrapper.java;l=210?q=newTheme&ss=android
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/ContextThemeWrapper.java;l=210?q=newTheme&ss=android
4) When the ThemeImpl get finalized (GC'd), they are released from the asset manager: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/res/ResourcesImpl.java;l=1365-1369;bpv=1;bpt=1?q=themeimpl&ss=android

I think you're right that Registries.NATIVE_THEME9_REGISTRY is preventing them from being GC'd. However, if Activities are leaking, they also won't be GC'd. 

Maybe we should also have some additional logic that either clears all registries in between tests. I'm not sure if those objects are designed to persist across tests.

**Comment by realdadfish** [comment]
@hoisie Thanks for the detailed lookup - yes, the missing finalizer call might be the culprit. The question is now - how would one effectively release an Activity to enforce that call, other than what @abed-quayo already did above, meaning calling `close()` on the `ActivityScenario`, which effectively calls into Robolectrics `LocalActivityInvoker.finishActivity()`?

In my heap dump I saw that quite a few `androidx.fragment.app.testing.FragmentScenario$EmptyFragmentActivity` were retained, so I checked their paths2gc. To me this looks as if `android.provider.DeviceConfig` holds upon a Handler thread that has an internal reference to the activity, originating from a call to `addOnPropertiesChangedListener` (https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/provider/DeviceConfig.java;l=671;bpv=0;bpt=1)

<img width="1158" src="https://user-images.githubusercontent.com/208234/97423841-24a69480-1910-11eb-8011-c4629754e3f1.png">

All registered `onPropertiesChangedListener` of `DeviceConfig` seem to point at different instances of `android.view.textclassifier.TextClassificationManager$SettingsObserver`:

<img width="1021"  src="https://user-images.githubusercontent.com/208234/97425430-69cbc600-1912-11eb-88e3-0f77c2e7aadd.png">

This static inner class seems to be present only up until Android 10 (https://cs.android.com/android/platform/superproject/+/android-10.0.0_r30:frameworks/base/core/java/android/view/textclassifier/TextClassificationManager.java;l=296;bpv=0;bpt=0) and was apparently removed in Android 11. 

Guess I'll retest with Robolectric 4.5-alpha01 (that seems to support Android 11) and bump my project to SDK 30 to see if this error persists.

**Comment by hoisie** [comment]
Good sleuthing!

This is how DeviceConfig.addOnPropertiesChangedListener gets called. Does this only occur when AutoCompleteTextView is used?

You could add a `@Resetter` to ShadowDeviceConfig that clears the listeners?

```
	at android.provider.DeviceConfig.addOnPropertiesChangedListener(DeviceConfig.java)
	at android.view.textclassifier.TextClassificationManager$SettingsObserver.__constructor__(TextClassificationManager.java:309)
	at android.view.textclassifier.TextClassificationManager$SettingsObserver.<init>(TextClassificationManager.java)
	at android.view.textclassifier.TextClassificationManager.__constructor__(TextClassificationManager.java:77)
	at android.view.textclassifier.TextClassificationManager.<init>(TextClassificationManager.java)
	at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:310)
	at android.app.SystemServiceRegistry$12.createService(SystemServiceRegistry.java:307)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1390)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1306)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1805)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:290)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:41)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:51)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:76)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:752)
	at android.content.Context.getSystemService(Context.java:3452)
	at android.view.textclassifier.TextClassificationManager.getSettings(TextClassificationManager.java:287)
	at android.widget.SelectionActionModeHelper.getTextClassificationSettings(SelectionActionModeHelper.java:221)
	at android.widget.SelectionActionModeHelper.__constructor__(SelectionActionModeHelper.java:99)
	at android.widget.SelectionActionModeHelper.<init>(SelectionActionModeHelper.java)
	at android.widget.Editor.getSelectionActionModeHelper(Editor.java:2184)
	at android.widget.Editor.sendOnTextChanged(Editor.java:1376)
	at android.widget.TextView.sendOnTextChanged(TextView.java:10539)
	at android.widget.TextView.setText(TextView.java:6272)
	at android.widget.TextView.setText(TextView.java:6097)
	at android.widget.EditText.setText(EditText.java:122)
	at android.widget.TextView.__constructor__(TextView.java:1616)
	at android.widget.TextView.<init>(TextView.java)
	at android.widget.EditText.<init>(EditText.java)
	at android.widget.AutoCompleteTextView.<init>(AutoCompleteTextView.java)
	at org.robolectric.shadows.ShadowAutoCompleteTextViewTest.shouldInvokeFilter(ShadowAutoCompleteTextViewTest.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:57)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:59)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by hoisie** [comment]
Want to send a PR to add a resetter to ShadowDeviceConfig?

```java
  @Resetter
  public static void reset() {
    Map singleListeners = ReflectionHelpers.getStaticField(DeviceConfig.class, "sSingleListeners");
    singleListeners.clear();

    Map listeners = ReflectionHelpers.getStaticField(DeviceConfig.class, "sListeners");
    listeners.clear();

    Map nameSpaces = ReflectionHelpers.getStaticField(DeviceConfig.class, "sNamespaces");
    nameSpaces.clear();

    // any other fields that have to be cleared
  }
```

You could also run:
```java
    Registries.NATIVE_THEME9_REGISTRY.clear();
```

at the end of each test.

I am trying to figure out if it's possible to switch to use weak references in Registries.

**Comment by realdadfish** [comment]
I'll try the resetter variant later today. Calling clear() on the registry after each test did not work, I got then NPRs from the same registry because expected themes were missing in subsequent tests (which _should_ not actually happen given what we know now, but I didn't investigated further). I'll paste a stack trace of that here later as well. 

Am 28. Oktober 2020 23:20:01 MEZ schrieb Michael Hoisie <notifications@github.com>:
>Want to send a PR to add a resetter to ShadowDeviceConfig?
>
>```java
>  @Resetter
>  public static void reset() {
>Map singleListeners =
>ReflectionHelpers.getStaticField(DeviceConfig.class,
>"sSingleListeners");
>    singleListeners.clear();
>
>Map listeners = ReflectionHelpers.getStaticField(DeviceConfig.class,
>"sListeners");
>    listeners.clear();
>
>Map nameSpaces = ReflectionHelpers.getStaticField(DeviceConfig.class,
>"sNamespaces");
>    nameSpaces.clear();
>
>    // any other fields that have to be cleared
>  }
>```
>
>You could also run:
>```java
>    Registries.NATIVE_THEME9_REGISTRY.clear();
>```
>
>at the end of each test.
>
>I am trying to figure out if it's possible to switch to use weak
>references in Registries.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/robolectric/robolectric/issues/5530#issuecomment-718241565

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by hoisie** [comment]
Yeah I don't think it's safe to clear the registries either. I think the artifacts from binary resources get stored there once and get reused. I think the best option is to ensure that the registries are not preventing GC from happening and that activities don't leak across tests.

**Comment by realdadfish** [comment]
For reference, this is the exception I get when I clear the registry:

```
 java.lang.NullPointerException: Could not find object with nativeId: 11. Currently registered ids: []
        at org.robolectric.res.android.NativeObjRegistry.getNativeObject(NativeObjRegistry.java:141)
        at org.robolectric.shadows.ShadowArscAssetManager9.nativeThemeGetAttributeValue(ShadowArscAssetManager9.java:1560)
        at android.content.res.AssetManager.nativeThemeGetAttributeValue(AssetManager.java)
        at android.content.res.AssetManager.getThemeValue(AssetManager.java:644)
        at android.content.res.ResourcesImpl$ThemeImpl.resolveAttribute(ResourcesImpl.java:1366)
        at android.content.res.Resources$Theme.resolveAttribute(Resources.java:1578)
        at androidx.test.espresso.matcher.ViewMatchers$IsDisplayingAtLeastMatcher.getScreenWithoutStatusBarActionBar(ViewMatchers.java:16)
        at androidx.test.espresso.matcher.ViewMatchers$IsDisplayingAtLeastMatcher.matchesSafely(ViewMatchers.java:25)
        at androidx.test.espresso.matcher.ViewMatchers$IsDisplayingAtLeastMatcher.matchesSafely(ViewMatchers.java:36)
        at org.hamcrest.TypeSafeMatcher.matches(TypeSafeMatcher.java:65)
        at androidx.test.espresso.action.ScrollToAction.perform(ScrollToAction.java:19)
        at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:16)
        at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:65)
        at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:15)
        at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
        at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:305)
        at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:270)
        at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:87)
        at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:15)
        at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:99)
        at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:43)
        at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:94)
```

**Comment by realdadfish** [comment]
Some more observations:

* The leak only occurs on targetSdk=29, incidentally the version `ShadowDeviceConfig` was introduced
* With the proposed `@Resetter` code the leak on targetSdk=29 seems to be gone, test execution uses even less memory than on targetSdk=28 (around 400MB on my MBP)

I'll create a PR later on.

**Comment by hoisie** [comment]
Another leak that occurs while tests are running -- activities don't clean themselves up from WindowManager objects:

```
Paths from "GC Roots" to "MainActivity"

+----------------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------+
|                                                                  Name                                                                  |  Retained Size  |  Shallow Size  |
+----------------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------+
|  +---com.google.android.robobugs.MainActivity                                                                                          |          8,016  |           336  |
|    |                                                                                                                                   |                 |                |
|    +---[0] of java.lang.Object[8]                                                                                                      |             48  |            48  |
|    | |                                                                                                                                 |                 |                |
|    | +---mValues of android.util.SparseArray                                                                                           |            128  |            32  |
|    |   |                                                                                                                               |                 |                |
|    |   +---mKeyedTags of com.android.internal.policy.DecorView                                                                         |          3,440  |           928  |
|    |     |                                                                                                                             |                 |                |
|    |     +---[48] of java.lang.Object[549]                                                                                             |          2,216  |         2,216  |
|    |       |                                                                                                                           |                 |                |
|    |       +---elementData of java.util.ArrayList size = 438                                                                           |          2,240  |            24  |
|    |         |                                                                                                                         |                 |                |
|    |         +---mViews of android.view.WindowManagerGlobal                                                                            |          6,832  |            40  |
|    |           |                                                                                                                       |                 |                |
|    |           +---mGlobal of android.view.WindowManagerImpl                                                                           |             56  |            32  |
|    |             |                                                                                                                     |                 |                |
|    |             +---mWindowManager of com.android.internal.policy.PhoneWindow                                                         |         14,856  |           384  |
|    |               |                                                                                                                   |                 |                |
|    |               +---mWindow of android.support.v7.app.AppCompatDelegateImpl [Stack Local]                                           |            744  |           160  |
|    |                 |                                                                                                                 |                 |                |
|    |                 +---<local variable> of java.lang.Thread [JNI Local, Thread, Stack Local] "SDK 29 Main Thread" tid=15 [RUNNABLE]  |         13,232  |           120  |
|    |                                                                                                                                   |                 |                |
|    +---mContext of android.widget.LinearLayout                                                                                         |          1,736  |           728  |
|    | |                                                                                                                                 |                 |                |
|    | +---mContentRoot of com.android.internal.policy.DecorView                                                                         |          3,440  |           928  |
|    |   |                                                                                                                               |                 |                |
|    |   +---[48] of java.lang.Object[549]                                                                                               |          2,216  |         2,216  |
|    |     |                                                                                                                             |                 |                |
|    |     +---elementData of java.util.ArrayList size = 438                                                                             |          2,240  |            24  |
|    |       |                                                                                                                           |                 |                |
|    |       +---mViews of android.view.WindowManagerGlobal                                                                              |          6,832  |            40  |
|    |         |                                                                                                                         |                 |                |
|    |         +---mGlobal of android.view.WindowManagerImpl                                                                             |             56  |            32  |
|    |           |                                                                                                                       |                 |                |
|    |           +---mWindowManager of com.android.internal.policy.PhoneWindow                                                           |         14,856  |           384  |
|    |             |                                                                                                                     |                 |                |
|    |             +---mWindow of android.support.v7.app.AppCompatDelegateImpl [Stack Local]                                             |            744  |           160  |
|    |               |                                                                                                                   |                 |                |
|    |               +---<local variable> of java.lang.Thread [JNI Local, Thread, Stack Local] "SDK 29 Main Thread" tid=15 [RUNNABLE]    |         13,232  |           120  |
|    |                                                                                                                                   |                 |                |
|    +---mContext of com.android.internal.policy.PhoneWindow                                                                             |         14,856  |           384  |
|      |                                                                                                                                 |                 |                |
|      +---mWindow of com.android.internal.policy.DecorView                                                                              |          3,440  |           928  |
|        |                                                                                                                               |                 |                |
|        +---[48] of java.lang.Object[549]                                                                                               |          2,216  |         2,216  |
|          |                                                                                                                             |                 |                |
|          +---elementData of java.util.ArrayList size = 438                                                                             |          2,240  |            24  |
|            |                                                                                                                           |                 |                |
|            +---mViews of android.view.WindowManagerGlobal                                                                              |          6,832  |            40  |
|              |                                                                                                                         |                 |                |
|              +---mGlobal of android.view.WindowManagerImpl                                                                             |             56  |            32  |
|                |                                                                                                                       |                 |                |
|                +---mWindowManager of com.android.internal.policy.PhoneWindow                                                           |         14,856  |           384  |
|                  |                                                                                                                     |                 |                |
|                  +---mWindow of android.support.v7.app.AppCompatDelegateImpl [Stack Local]                                             |            744  |           160  |
|                    |                                                                                                                   |                 |                |
|                    +---<local variable> of java.lang.Thread [JNI Local, Thread, Stack Local] "SDK 29 Main Thread" tid=15 [RUNNABLE]    |         13,232  |           120  |
+----------------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------+

```

**Comment by realdadfish** [comment]
Awesome, thank you for fixing this!

**Comment by realdadfish** [comment]
A proposal: would it be a good idea to have some kind of regression test that, like above, quickly starts and stops many activities and checks the timing on that, so in case a new leak is introduced through a new SDK version this test would fail, because GC times would go through the roof again for the test?

**Comment by hoisie** [comment]
I added a test that creates/destroys 1000 activities in a single test. It will probably OOM if there's a leak in the activity cycle.

**Comment by vn01971** [comment]
I'm still getting an OOM error using the following robolectric dependencies
```gradle
    def robolectric_version = "4.5.1"
    testImplementation "org.robolectric:robolectric:$robolectric_version"
    testImplementation "org.robolectric:shadows-httpclient:$robolectric_version"
```

and `targetSdkVersion 29`

![Screen Shot 2021-03-02 at 10 06 46 AM](https://user-images.githubusercontent.com/60491415/109686337-cb61a280-7b47-11eb-8633-269cc1a05898.png)

Any other information I can provide to determine if this is the same issue?

**Comment by hoisie** [comment]
Sure, it would be great if you can provide sample code or a sample app that
repros the issue.

It looks like something is preventing activities from being collected. Can
you do shortest roots to GC on the activity objects? Could also be your app
or test code that is preventing it from being collected.

**Comment by vn01971** [comment]
@hoisie My tests make heavy use of `FragmentScenario`s and it looks like the OOM error doesn't occur (or at least doesn't occur as often) when I move the fragment to the destroyed state after each test. Do you know if you're expected to move it to the destroyed state for test cleanup? Note that `MyCustomFragment` is a complex fragment in my app, so potentially it could have a memory leak (though I haven't seen any from LeakCanary)

### Without moving to destroyed state
```kotlin
    @Test
    // This test does result in OOM error
    fun launchMyCustomFragment_DontMoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<MyCustomFragment>(null, R.style.MyTheme)
        }
    }
```
![Screen Shot 2021-03-03 at 3 23 16 PM](https://user-images.githubusercontent.com/60491415/110033404-f3473680-7cfe-11eb-98ac-6c0b89a452cd.png)

### With moving to destroyed state
```kotlin
    @Test
    // This test doesn't result in OOM error
    fun launchMyCustomFragment_MoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<MyCustomFragment>(null, R.style.MyTheme)
            scenario.moveToState(Lifecycle.State.DESTROYED)
        }
    }
```
![Screen Shot 2021-03-03 at 3 23 05 PM](https://user-images.githubusercontent.com/60491415/110033430-fc380800-7cfe-11eb-98d0-55957a97c8f1.png)


It _seemed_ like it was a memory leak in my code since the following test didn't result in an OOM error (note that `EmptyFragment` is a fragment I made with just a textview):
```kotlin
    @Test
    // This test doesn't result in OOM error
    fun launchEmptyFragment_MoveToDestroyed(){
        for (i in 0 until 1000) {
            val scenario = launchFragmentInContainer<EmptyFragment>(null, R.style.MyTheme)
        }
    }
```

However, that `launchEmptyFragment_MoveToDestroyed` test does result in an OOM error if I change the loop iterations to 10,000. Futhermore, the following test also results in an OOM error, which makes me concerned that moving to the destroyed state isn't the solution:
```kotlin
    @Test
    // This test does result in an OOM error
    fun launchEmpty_MoveToDestroyed(){
        for (i in 0 until 10000) {
            val scenario = launchFragmentInContainer<EmptyFragment>(null, R.style.MyTheme)
            scenario.moveToState(Lifecycle.State.DESTROYED)
        }
    }
```

I'm very new to VisualVM, so could you explain how you knew that something is preventing activities from being collected? Also, could you explain or refer me to the docs on how to find the shortest roots to GC?
I assume it's the `FragmentScenario$EmptyFragmentActivity` that you're referring to? It does look like a lot of those are sticking around (this image is from the last example test above).
<img width="1099" alt="Screen Shot 2021-03-04 at 3 45 44 PM" src="https://user-images.githubusercontent.com/60491415/110035082-d14eb380-7d00-11eb-8b56-334a8800fef8.png">

<img width="1577" alt="Screen Shot 2021-03-04 at 3 51 34 PM" src="https://user-images.githubusercontent.com/60491415/110035655-900ad380-7d01-11eb-977a-675fae9e7a0d.png">

**Comment by vn01971** [comment]
My issue might be related to https://github.com/android/android-test/issues/457

**Comment by hoisie** [comment]
@vn01971 can you file a new issue? If there is a new leak the root cause would be different than the other in this issue, and I don't want one issue to be used for all memory leaks.

**Comment by ajeihala** [comment]
Hello. This seems to be still an issue in Robolectric version `4.5.1` (`targetSdkVersion: 28`).

This test acquires gigabytes of ram very quickly: 
``` 
@Test
fun test() {
    val applicationContext = ApplicationProvider.getApplicationContext<Context>()
    while (true) {
        val scenario = ActivityScenario.launch<TestActivity>(
            Intent(applicationContext, TestActivity::class.java)
        )
        scenario.close() // same with scenario.use {  }
    }
}
```
(Test activity is empty `class TestActivity : AppCompatActivity()`)

<img width="1630" alt="Screenshot 2021-03-17 at 00 04 53" src="https://user-images.githubusercontent.com/3758340/111391533-15ed2e00-86b5-11eb-8516-50f9b5a43c9b.png">

Could anyone confirm it works correctly and memory is not leaked?
