### ISSUE TITLE
MaterialShapeDrawable four arg constructor: NoSuchMethodError

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#5564]
When I test a `MaterialDialog` using Google's Material Design Library 1.2.0-alpha05 (the latest), I receive the following crash:

```
java.lang.NoSuchMethodError: com.google.android.material.shape.MaterialShapeDrawable.<init>(Landroid/content/Context;Landroid/util/AttributeSet;II)V
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:121)
    at com.google.android.material.dialog.MaterialAlertDialogBuilder.<init>(MaterialAlertDialogBuilder.java:103)
    at our.code.onCreate(OurFragment.kt:112)
    at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
    at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
    at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
    at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
    at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
    at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
    at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
    at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
    at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:312)
    at androidx.fragment.app.testing.FragmentScenario$1.perform(FragmentScenario.java:291)
    at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:551)
    at androidx.test.core.app.ActivityScenario$$Lambda$4.run(Unknown Source)
    at androidx.test.core.app.ActivityScenario.onActivity(ActivityScenario.java:561)
    at androidx.fragment.app.testing.FragmentScenario.internalLaunch(FragmentScenario.java:290)
    at androidx.fragment.app.testing.FragmentScenario.launchInContainer(FragmentScenario.java:272)
```

For whatever reason the call in `MaterialAlertDialog.Builder`

```kotlin
    MaterialShapeDrawable materialShapeDrawable =
        new MaterialShapeDrawable(context, null, DEF_STYLE_ATTR, DEF_STYLE_RES);
```

doesn't find the four-argument constructor of `MaterialShapeDrawable`, which is existant:

```kotlin
  public MaterialShapeDrawable(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @AttrRes int defStyleAttr,
      @StyleRes int defStyleRes) {
    this(ShapeAppearanceModel.builder(context, attrs, defStyleAttr, defStyleRes).build());
  }
```

(Source: https://github.com/material-components/material-components-android/blob/841fae9258e4f70288dd43288939747acebeb960/lib/java/com/google/android/material/shape/MaterialShapeDrawable.java#L177)

What's going on here?

This is Robolectric 4.3.1

**Comment by hoisie** [comment]
Is this still happening? Is it possible that multiple MaterialShapeDrawable are on the classpath?

**Comment by realdadfish** [comment]
Haven't seen this in a while. Will close this for now. Thanks for taking care!
