### ISSUE TITLE
[2.0-rc3] Intermittent NPE when setting adapter on ListView

### ISSUE THREAD

**Issue by sdhull** [robolectric/robolectric#557]
Getting this like 1 out of every 10ish runs.

Code:

``` java
    @Override
    public void success(RemoteRoute route){
        mAdapter.setRoute(route);

        mListView.setAdapter(mAdapter);  // this is the line it explodes on
```

Test:

``` java
    @Test
    public void success__setsAdapterOnListview(){
        activity.success(route);
        assertThat(mListView).hasAdapter(activity.mAdapter);
        assertThat(mListView.getCount()).isEqualTo(2);
    }
```

Stacktrace:

``` java
java.lang.NullPointerException
    at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6399)
    at android.widget.AbsListView.obtainView(AbsListView.java:2251)
    at android.widget.ListView.measureHeightOfChildren(ListView.java:1244)
    at android.widget.ListView.onMeasure(ListView.java:1156)
    at android.view.View.measure(View.java:15172)
    at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
    at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
    at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    at android.view.View.measure(View.java:15172)
    at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1850)
    at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1102)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1275)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4214)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
    at android.view.Choreographer.doCallbacks(Choreographer.java:555)
    at android.view.Choreographer.doFrame(Choreographer.java:525)
    at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:657)
    at org.robolectric.shadows.ShadowHandler.routeMessage(ShadowHandler.java:120)
    at org.robolectric.shadows.ShadowHandler.access$100(ShadowHandler.java:25)
    at org.robolectric.shadows.ShadowHandler$1.run(ShadowHandler.java:109)
    at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
    at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:198)
    at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
    at org.robolectric.shadows.ShadowHandler.sendMessageDelayed(ShadowHandler.java:104)
    at org.robolectric.shadows.ShadowHandler.sendMessageAtTime(ShadowHandler.java:155)
    at android.os.Handler.sendMessageAtTime(Handler.java)
    at android.view.Choreographer.scheduleFrameLocked(Choreographer.java:479)
    at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
    at org.robolectric.shadows.ShadowChoreographer.scheduleFrameLocked(ShadowChoreographer.java:45)
    at android.view.Choreographer.scheduleFrameLocked(Choreographer.java)
    at android.view.Choreographer.postCallbackDelayedInternal(Choreographer.java:309)
    at android.view.Choreographer.postCallbackDelayed(Choreographer.java:292)
    at android.view.Choreographer.postCallback(Choreographer.java:266)
    at android.view.ViewRootImpl.scheduleTraversals(ViewRootImpl.java:974)
    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:837)
    at android.view.View.requestLayout(View.java:15129)
    at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:164)
    at android.view.View.requestLayout(View.java)
    at org.robolectric.tester.android.view.RoboWindow$1.requestLayout(RoboWindow.java:221)
    at android.view.View.requestLayout(View.java:15129)
    at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:164)
    at android.view.View.requestLayout(View.java)
    at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:292)
    at android.view.View.requestLayout(View.java:15129)
    at org.robolectric.shadows.ShadowView.requestLayout(ShadowView.java:164)
    at android.view.View.requestLayout(View.java)
    at android.widget.AbsListView.requestLayout(AbsListView.java:1932)
    at android.widget.ListView.onFocusChanged(ListView.java:3407)
    at android.view.View.handleFocusGainInternal(View.java:4257)
    at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:558)
    at android.view.View.requestFocusNoSearch(View.java:6478)
    at android.view.View.requestFocus(View.java:6457)
    at android.view.ViewGroup.requestFocus(ViewGroup.java:2328)
    at android.view.View.requestFocus(View.java:6424)
    at android.view.View.requestFocus(View.java:6403)
    at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:2579)
    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:604)
    at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:604)
    at android.view.View.setFlags(View.java:8290)
    at android.view.View.setFocusableInTouchMode(View.java:5586)
    at android.widget.AdapterView.checkFocus(AdapterView.java:717)
    at android.widget.ListView.setAdapter(ListView.java:461)
    at com.mycompany.myapp.ui.routes.RouteOverviewActivity.success(RouteOverviewActivity.java:51)
    at com.mycompany.myapp.ui.routes.RouteOverviewActivityTest.success__setsAdapterOnListview(RouteOverviewActivityTest.java:95)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:246)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:181)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by qsjh898** [comment]
I am working with Robolecric3.2.1 and still getting this NPE while run listView.setAdapter().
After some extra test, I find it happen when ListView.setAdapter() is firstly called after ActivityController.visible().
