### ISSUE TITLE
Dynamic Feature Activity test

### ISSUE THREAD

**Issue by adamstyrc** [robolectric/robolectric#5597]
### Description
I've added new module to my Android project which is not a library:
`apply plugin: 'com.android.library'`
but a dynamic feature that I want to uninstall at some time from my App Bundle
`apply plugin: 'com.android.dynamic-feature'`

After work on UI done I wanted to write a Robolectric/AndroidX test to check my Activity behavior.

When I tried to run Activity with **_launchActivity()_ ** I get 

> java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.robolectric.default/com.goincharge.app.onboarding.ui.AppOnboardingActivity } -- see https://github.com/robolectric/robolectric/pull/4736 for details
> 
> 	at org.robolectric.android.fakes.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:48)
> 	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:34)
> 	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:231)
> 	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:190)
> 	at com.goincharge.app.onboarding.ui.AppOnboardingActivityTest.aa(AppOnboardingActivityTest.kt:43)

and when I tried with old:
**_Robolectric.setupActivity(AppOnboardingActivity::class.java)_**

I got 
android.content.res.Resources$NotFoundException: Resource ID #0x7f08005f

> 	at org.robolectric.shadows.ShadowLegacyAssetManager.getResName(ShadowLegacyAssetManager.java:1283)
> 	at org.robolectric.shadows.ShadowLegacyAssetManager.resolveResourceValue(ShadowLegacyAssetManager.java:1066)
> 	at org.robolectric.shadows.ShadowLegacyAssetManager.resolve(ShadowLegacyAssetManager.java:1026)
> 	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1020)
> 	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceValue(ShadowLegacyAssetManager.java:319)
> 	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
> 	at android.content.res.Resources.getValue(Resources.java:1009)
> 	at androidx.appcompat.widget.ResourceManagerInternal.loadDrawableFromDelegates(ResourceManagerInternal.java:252)
> 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:139)
> 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
> 	at androidx.appcompat.widget.ResourceManagerInternal.checkVectorDrawableSetup(ResourceManagerInternal.java:504)
> 	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:137)
> 	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:411)
> 	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:86)
> 	at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:647)
> 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:623)
> 	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:350)
> 	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:105)

### Steps to Reproduce

Create Activity in the new Dynamic Feature module and just setup a test. My AndroidManifest.xml 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dist="http://schemas.android.com/apk/distribution"
    package="com.goincharge.app.onboarding">

    <dist:module
        dist:instant="false"
        dist:title="@string/feature_app_onboarding">
        <dist:delivery>
            <dist:install-time />
        </dist:delivery>

        <dist:fusing dist:include="true" />
    </dist:module>

    <application>
        <activity
            android:name=".ui.AppOnboardingActivity"
            android:screenOrientation="portrait">
...
        </activity>
    </application>

</manifest>

### Robolectric & Android Version
Robolectric **4.3.1**
### Link to a public git repo demonstrating the problem:
Project not public

**Comment by hoisie** [comment]
Switch to binary resources and try again. Add this to app/build.gradle inside the `android` block:
```
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```

**Comment by ganadist** [comment]
When set `includeAndroidResources = true`, robolectric shows another error.

Tested with AGP 4.2, Robolectric 4.6.1, Java 11, and targetSdkVersion is 29 or 30


```
    W/PackageParser: Failed to parse feature1/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
     java.lang.NullPointerException
    	at org.robolectric.res.android.LoadedArsc$LoadedPackage.Load(LoadedArsc.java:728)
    	at org.robolectric.res.android.LoadedArsc.LoadTable(LoadedArsc.java:911)
    	at org.robolectric.res.android.LoadedArsc.Load(LoadedArsc.java:957)
    	at org.robolectric.res.android.CppApkAssets.LoadImpl_measured(CppApkAssets.java:266)
    	at org.robolectric.res.android.CppApkAssets.lambda$LoadImpl$0(CppApkAssets.java:205)
    	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    	at org.robolectric.res.android.CppApkAssets.LoadImpl(CppApkAssets.java:202)
    	at org.robolectric.res.android.CppApkAssets.Load(CppApkAssets.java:117)
    	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:264)
    	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:285)
    	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
    	at android.content.res.ApkAssets.__constructor__(ApkAssets.java:291)
    	at android.content.res.ApkAssets.<init>(ApkAssets.java)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:140)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:343)
    	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:56)
    	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:61)
    	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:225)
    	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:152)
    	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:222)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:127)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at org.robolectric.util.ReflectionHelpers.callStaticMethod(ReflectionHelpers.java:343)
    	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:56)
    	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:61)
    	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$0(ShadowArscApkAssets9.java:164)
    	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:152)
    	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:162)
    	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
    	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1442)
    	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1415)
    	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:932)
    	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1140)
    	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1054)
    	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1063)
    	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
    	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:326)
    	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:296)
    	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:294)
    	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:195)
    	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
    	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
    	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:269)
    	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by ganadist** [comment]
Also, when set `includeAndroidResources = false`, robolectric will shows this error since 4.6.x (It was okay until 4.5.x)

```
Caused by: java.lang.NullPointerException: (No message provided)
        at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1019)	
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceValue(ShadowLegacyAssetManager.java:319)	
	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:212)	
	at android.content.res.Resources.getBoolean(Resources.java:1068)	
	at android.database.sqlite.SQLiteGlobal.isCompatibilityWalSupported(SQLiteGlobal.java:89)	
	at android.database.sqlite.SQLiteDatabase.__constructor__(SQLiteDatabase.java:298)	
	at android.database.sqlite.SQLiteDatabase.<init>(SQLiteDatabase.java)	
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:738)	
	at android.database.sqlite.SQLiteDatabase.createInMemory(SQLiteDatabase.java:920)	
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:350)	
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)	
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)	
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)	
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)	
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)	
	at androidx.room.RoomDatabase.query(RoomDatabase.java:442)	
	at androidx.room.util.DBUtil.query(DBUtil.java:83)	
```

**Comment by utzcoz** [comment]
Hi @ganadist , could you help to provide a sample app that can reproduce it? Thanks.

**Comment by ganadist** [comment]
Here is a sample app for test

```
$ git clone https://github.com/ganadist/VersionCodeDemo

$ cd VersionCodeDemo


#### robolectric 4.5.1 or 4.6.1 / includeAndroidResources = true / sdk is 30
$ git checkout origin/dynamic_feature_robolectric
$ ./gradlew :dynamicfeature1:testDevelopDebugUnitTest

// got error at org.robolectric.res.android.LoadedArsc$LoadedPackage.Load(LoadedArsc.java:728)

#### robolectric 4.5.1 or 4.6.1 / includeAndroidResources = false / sdk is 28
$ git checkout HEAD~1
$ ./gradlew :dynamicfeature1:testDevelopDebugUnitTest

// passed


#### robolectric 4.6.1
$ git checkout origin/dynamic_feature_robolectric_461
$ ./gradlew :dynamicfeature1:testDevelopDebugUnitTest

// got error at  org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1019)	

#### robolectric 4.5.1
$ git checkout HEAD~1
$ ./gradlew :dynamicfeature1:testDevelopDebugUnitTest

// passed

```

**Comment by utzcoz** [comment]
After simple debug, I found that `entry_begin` is null at https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/LoadedArsc.java#L723-L724 . I will take a look to check the reason. And again @ganadist , thanks your sample app, it helps a lot.

**Comment by hoisie** [comment]
Awesome, thanks for the example. Seems like this is an edge case in the ARSC unpacking logic. You can get the ARSC file by unzipping the ap_ file generated by the Gradle build. The file format is not well documented (I think it's mainly documented in the package manager source code), but it is relatively simple. I can look for more docs about the ARSC format.

**Comment by utzcoz** [comment]
The `asResTable_lib_entry` returns null because header size is less than `ResTable_lib_entry.SIZEOF` at https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/resources/src/main/java/org/robolectric/res/android/Chunk.java#L114-L120

The log says header size is 12, and it is less than `ResTable_lib_entry.SIZEOF`. I also added log before https://cs.android.com/android/platform/superproject/+/master:frameworks/base/libs/androidfw/LoadedArsc.cpp;l=612?q=LoadedArsc.cpp, to check the real header size that AOSP read from above mentioned sample app, it is also 12.

Added log:

```
        if (child_chunk.data_size() / sizeof(ResTable_lib_entry) < dtohl(lib->count)) {
          LOG(ERROR) << "RES_TABLE_LIBRARY_TYPE too small to hold entries.";
          return {};
        }
        LOG(ERROR) << "header " << child_chunk.header_size();

        loaded_package->dynamic_package_map_.reserve(dtohl(lib->count));
```
Printed log:

```
07-12 00:06:21.306   540   586 E system_server: header 12
```

Look like Robolectric's `Chunk#asResTable_lib_entry` and its related buffer parsing are not correctly.

**Comment by utzcoz** [comment]
I have modified `Chunk#asResTable_lib_entry` with following dirty code:

```java
    if (header_size() > 0) {
      ResTable_lib_entry lib_entry = new ResTable_lib_entry(device_chunk_.myBuf(), device_chunk_.myOffset() + header_size());
      return lib_entry;
    }
```

And make sure `LoadedArsc#Load`'s foreach for `RES_TABLE_LIBRARY_TYPE` with correct increment step:
```java
entry_iter.myOffset() != entry_begin.myOffset() + dtohl(lib.count) * ResTable_lib_entry.SIZEOF
```

Also need to add try-catch for new iterator entry (Actually it needs a checking for `ByteBuffer`'s end position to ensure the new offset doesn't exceed allowed position):

```java
              try {
                entry_iter = new ResTable_lib_entry(entry_iter.myBuf(), entry_iter.myOffset() + ResTable_lib_entry.SIZEOF);
              } catch (Exception e) {
                System.err.println("failed to create new entry " + e.getMessage());
                break;
              }
```

With above patches, the NPE disappears with `includeAndroidResources = true` and sdk 30. But `PackageParser` throws the below error:

```
Caused by: android.content.pm.PackageParser$PackageParserException: /home/dev/workspace/VersionCodeDemo/dynamicfeature1/build/intermediates/apk_for_local_test/developDebugUnitTest/apk-for-local-test.ap_ (at Binary XML file line #2): Expected base APK, but found split dynamicfeature1
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1191)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1150)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1054)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1063)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
```

In a sense, the above modification is reasonable for me, so I will look at the new `PackageParser` exception before imporving modification for Robolectric's `ARSC` parser.

**Comment by ganadist** [comment]
It seems `ShadowPackageParser` should parse with `parseClusterPackage` ( https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PackageParser.java;l=1037-1064?q=parsePackage&ss=android) (directory must contain base apk and split(dynamic feature) apk ), 

But base apk is located on `app/build/intermediates/apk_for_local_test/developDebugUnitTest/apk-for-local-test.ap_` and can be built with `:app:testDevelopDebugUnitTest` task

**Comment by ganadist** [comment]
I tried to modify robolectric as https://github.com/robolectric/robolectric/issues/5597#issuecomment-877836058 , also modify to use package directory instead file.

https://github.com/ganadist/robolectric/commit/2e48cc3d77cc773f2a119a596cf3051372cf684c#diff-16f874a8ce1fd6aa0c4faba55475bad44949ee2087391001f2a2d209a8dab559R47-R48

Also, I copied base.apk from app module, manually
```
cp -f app/build/intermediates/apk_for_local_test/developDebugUnitTest/apk-for-local-test.ap_ \ 
   dynamicfeature1/build/intermediates/apk_for_local_test/developDebugUnitTest/base.apk
```

Then, it seems PackageParser loaded apk, but I got another error while load resources.

https://scans.gradle.com/s/kt2yqkfvrho5k/tests/:dynamicfeature1:testDevelopDebugUnitTest/com.example.dynamicfeature1.ActivityTest/test_Activity?expanded-stacktrace=WyIwLTEiXQ&top-execution=1

**Comment by utzcoz** [comment]
That's cool. I need more time to learn what AGP and frameworks do for dynamic feature apks.

**Comment by utzcoz** [comment]
No folks take this issue at GSoC 2022, so I will take this issue again to continue related work at next few weekends. cc @ganadist ..

**Comment by utzcoz** [comment]
FYI @ganadist, I cherry-picked your previous commit and pushed it to https://github.com/robolectric/robolectric/pull/7336 for next continuous work to support dynamic feature.

**Comment by cainiaoxiaomin** [comment]
Is there a solution to this problem?
i also meet this problem
only use robolectric 4.5.1 and includeAndroidResources = false  can work
but because  includeAndroidResources = false, setcontentview in activity can not work

**Comment by sbeach** [comment]
My team is not using dynamic modules, but wanted to comment we are experiencing a similar test failure with `ShadowPackageParser`. Since we use static modules, I added my details to a different issue: https://github.com/robolectric/robolectric/issues/4278#issuecomment-1367605817.
I hope the extra information is helpful in debugging both issues.

**Comment by saran-epifi** [comment]
@utzcoz Hey thanks for your attention to this issue. I see that you have a PR with the fix. Do you have any timeline in mind by when we will be able to see this fix get released.

**Comment by utzcoz** [comment]
@saran-epifi Sorry for pending/delaying. I think I will come back to this issue at next month after I resolved some pending PRs about Kotlin conversion for some modules' test code.

**Comment by clickrapha** [comment]
Hi @utzcoz, any update about this issue?

**Comment by ksachin7** [comment]
@utzcoz @hoisie I am interested in working on this Issue as my GSOC Project, should I propose my initial solutions for this here in this discussion or through mail ?

**Comment by Pramath02** [comment]
@utzcoz I am interested in working on this issue.
