### ISSUE TITLE
NoClassDefFound: TelephonyManager$CellInfoCallback with Robolectric 4.4-SNAPSHOT

### ISSUE THREAD

**Issue by kingargyle** [robolectric/robolectric#5637]
### Description

When running a test that uses EasyDeviceInfo with Robolectric 4.4-SNAPSHOT, the following stack trace is thrown and test fails:

java.lang.NoClassDefFoundError: android/telephony/TelephonyManager$CellInfoCallback

	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:304)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:273)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:250)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:146)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.app.SystemServiceRegistry$33.createService(SystemServiceRegistry.java:413)
	at android.app.SystemServiceRegistry$33.createService(SystemServiceRegistry.java:410)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:768)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:721)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1365)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:41)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:51)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:74)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:627)
	at github.nisrulz.easydeviceinfo.base.EasyDeviceMod.<init>(EasyDeviceMod.java:54)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClient.<init>(EmbyAPIClient.kt:69)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClient.<init>(EmbyAPIClient.kt:30)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClientTest.setUp(EmbyAPIClientTest.kt:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:544)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyManager$CellInfoCallback
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:189)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:133)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:119)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:304)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:273)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:250)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:146)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.app.SystemServiceRegistry$33.$$robo$$android_app_SystemServiceRegistry_33$createService(SystemServiceRegistry.java:413)
	at android.app.SystemServiceRegistry$33.createService(SystemServiceRegistry.java)
	at android.app.SystemServiceRegistry$33.createService(SystemServiceRegistry.java:410)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.$$robo$$android_app_SystemServiceRegistry_CachedServiceFetcher$getService(SystemServiceRegistry.java:768)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java)
	at android.app.SystemServiceRegistry.$$robo$$android_app_SystemServiceRegistry$getSystemService(SystemServiceRegistry.java:721)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java)
	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSystemService(ContextImpl.java:1365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:283)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:41)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:51)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:74)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.$$robo$$android_content_ContextWrapper$getSystemService(ContextWrapper.java:627)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java)
	at github.nisrulz.easydeviceinfo.base.EasyDeviceMod.<init>(EasyDeviceMod.java:54)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClient.<init>(EmbyAPIClient.kt:69)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClient.<init>(EmbyAPIClient.kt:30)
	at us.nineworlds.serenity.emby.server.api.EmbyAPIClientTest.setUp(EmbyAPIClientTest.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 11 more

### Steps to Reproduce

See the tests in the emby-lib, and run them as part of build.  The setup uses the project EasyDeviceInfo to obtain information about the device it is running on.   Test works fine with Robolectric 4.3.1, fails with 4.4-SNAPSHOT.   No other changes.

### Robolectric & Android Version

4.4-SNAPSHOT 
sdk 28

### Link to a public git repo demonstrating the problem:

https://github.com/NineWorlds/serenity-android/tree/robo44

You may not be able to run this particular test as it requires a local emby media server to be setup.  Stack Trace and the same code should give you what you need.  If you need any other information let me know.

**Comment by kingargyle** [comment]
Like #5636 this needs to have the compile version set to 29, otherwise compilation will fail with the above issue.
