### ISSUE TITLE
Unknown font id: 0 (textFontWeight)

### ISSUE THREAD

**Issue by tonyshkurenko** [robolectric/robolectric#5749]
### Description

Crashes, when using `textFontWeight` property with built-in font.

### Steps to Reproduce

`includeAndroidResources = true`

Create a xml, with `android:textFontWeight="400"` and `android:textFontWeight="500"`

Latest stacktrace:

```
Caused by: java.lang.RuntimeException: Unknown font id: 0
	at org.robolectric.shadows.ShadowTypeface.findById(ShadowTypeface.java:181)
	at org.robolectric.shadows.ShadowTypeface.__constructor__(ShadowTypeface.java:50)
	at android.graphics.Typeface.<init>(Typeface.java)
	at android.graphics.Typeface.createWeightStyle(Typeface.java:800)
	at android.graphics.Typeface.create(Typeface.java:779)
	at android.widget.TextView.resolveStyleAndSetTypeface(TextView.java:2035)
	at android.widget.TextView.setTypefaceFromAttrs(TextView.java:2008)
	at android.widget.TextView.applyTextAppearance(TextView.java:3640)
	at android.widget.TextView.__constructor__(TextView.java:1498)
	at android.widget.TextView.<init>(TextView.java)
	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
```

### Robolectric & Android Version

Robolectric 4.3.1, Android: compileSdkVersion 29, build tools 29.0.3, robolectric runs tests on 28

### Link to a public git repo demonstrating the problem:

Absent :(

**Comment by tonyshkurenko** [comment]
For those, who encounters this too, I've written small hack around it and it helped:

```
val fontsField = ShadowTypeface::class.java.getDeclaredField("FONTS")
fontsField.isAccessible = true
@Suppress("UNCHECKED_CAST")
val map: MutableMap<Long, ShadowTypeface.FontDesc> =
        fontsField.get(null) as MutableMap<Long, ShadowTypeface.FontDesc>
map[0L] = ShadowTypeface.FontDesc("sans-serif", 0)
```

**Comment by hoisie** [comment]
I believe this was fixed in #5616, which is after 4.3.1.

You could try 4.4-alpha-1, or declare a custom ShadowTypeface that includes that fix.

**Comment by tonyshkurenko** [comment]
Yeah, looks like it should be fixed.

**Comment by hoisie** [comment]
4.4 is now released which should contain a fix, closing this.
