### ISSUE TITLE
ShadowMediaRouter method addBluetoothRoute() causes NPE

### ISSUE THREAD

**Issue by PawelS96** [robolectric/robolectric#5779]
### Description

Trying to call addBluetoothRoute() on a ShadowMediaRouter instance will throw a NullPointerException

```
java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:259)
	at org.robolectric.shadows.ShadowMediaRouter.callUpdateAudioRoutes(ShadowMediaRouter.java:86)
	at org.robolectric.shadows.ShadowMediaRouter.updateBluetoothAudioRoute(ShadowMediaRouter.java:69)
	at org.robolectric.shadows.ShadowMediaRouter.addBluetoothRoute(ShadowMediaRouter.java:31)
```

### Steps to Reproduce

` ShadowMediaRouter().addBluetoothRoute()`

or

```
val mr: MediaRouter = Shadow.newInstanceOf(MediaRouter::class.java)
Shadow.extract<ShadowMediaRouter>(mr).addBluetoothRoute()
```

### Robolectric & Android Version

Robolectric: 4.3, 4.3.1
compile & target: 29

**Comment by hoisie** [comment]
Would you be up for fixing this and submitting a PR?

**Comment by hoisie** [comment]
Actually, you need to do:
```java
MediaRouter mediaRouter = (MediaRouter) context.getSystemService(Context.MEDIA_ROUTER_SERVICE);
shadowOf(mediaRouter).addBluetoothRoute();
```

**Comment by hoisie** [comment]
Closing this, please switch to using `context.getSystemService(Context.MEDIA_ROUTER_SERVICE)`.
