### ISSUE TITLE
java.lang.ClassCastException with Kotlin 1.4 suspend fun interface

### ISSUE THREAD

**Issue by colinrtwhite** [robolectric/robolectric#5793]
### Description

Robolectric fails to instantiate instances of a Kotlin 1.4 `fun interface` when its method is a `suspend fun`.

It's possible to work around this issue by declaring the instance without using lambda syntax.

### Steps to Reproduce

Run `ExampleUnitTest.reproduce` in this [reproduction sample](https://github.com/robolectric/robolectric/files/4978827/MyApplication.zip). It will fail with the following error:

```kotlin
java.lang.ClassCastException: com.example.myapplication.ExampleUnitTest$reproduce$test$1 cannot be cast to com.example.myapplication.ExampleUnitTest$Interface
	at com.example.myapplication.ExampleUnitTest.reproduce(ExampleUnitTest.kt:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Robolectric & Android Version

Tested with both 4.3.1 and 4.4-alph02.

### Link to a public git repo demonstrating the problem:

[Reproduction project](https://github.com/robolectric/robolectric/files/4978827/MyApplication.zip).

**Comment by colinrtwhite** [comment]
Hmm this seems to be unrelated to Robolectric. Sorry for the noise!
