### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.robolectric.util.reflector.UnsafeAccess

### ISSUE THREAD

**Issue by alxrsngrtn** [robolectric/robolectric#5804]
### Description
Android JUnit4 test runner fails with reflection error in Robolectric. Here's the full trace: 
```
JUnit4 Test Runner
.WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.robolectric.util.ReflectionHelpers$6 (file:/private/var/tmp/_bazel_alxrsngrtn/6664c0354a75327234089c8b040ba855/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/maven/v1/https/jcenter.bintray.com/org/robolectric/shadowapi/4.4-alpha-2/shadowapi-4.4-alpha-2.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.robolectric.util.ReflectionHelpers$6
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Robolectric] arcs.showcase.typevariables.VariableTest.shop_redactsSku: sdk=28; resources=BINARY
E
Time: 1.17
There was 1 failure:
1) shop_redactsSku(arcs.showcase.typevariables.VariableTest)
java.lang.NoClassDefFoundError: Could not initialize class org.robolectric.util.reflector.UnsafeAccess
	at org.robolectric.util.reflector.Reflector.defineViaUnsafe(Reflector.java:127)
	at org.robolectric.util.reflector.Reflector.createReflectorClass(Reflector.java:119)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:65)
	at org.robolectric.util.reflector.Reflector.reflector(Reflector.java:49)
	at org.robolectric.shadows.ShadowArscAssetManager9.reset(ShadowArscAssetManager9.java:232)
	at org.robolectric.Shadows.reset(Shadows.java:2297)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:335)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:333)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
### Steps to Reproduce
I'm not sure how to reproduce _exactly_. This appears on my and a teammate's machine. Most of the folks on our project have test working without any fuss. 

Error occurs when running `tools/bazelisk test //javatests/arcs/showcase/typevariables:VariableTest`.
More instructions in the public repo link section.

### Robolectric & Android Version
Mac OS Catalina
RE 4.4-alpha-2
Bazel 3.4.1
IntelliJ 2019.3.5
Android SDK 29 (test seems to run with 28)
Kotlin 1.3.30
JVMs installed (`/usr/libexec/java_home -V`). IDE is pointing to Java 1.8 but tests are running with Java 14: 
```
Matching Java Virtual Machines (11):
    14, x86_64: "OpenJDK 14"    /Library/Java/JavaVirtualMachines/adoptopenjdk-14.jdk/Contents/Home
    12.0.1, x86_64:     "OpenJDK 12.0.1"        /Library/Java/JavaVirtualMachines/openjdk-12.0.1.jdk/Contents/Home
    11.0.4, x86_64:     "Java SE 11.0.4"        /Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home
    11.0.4, x86_64:     "Java SE 11.0.4"        /Library/Java/JavaVirtualMachines/jdk-11-latest/Contents/Home
    10.0.1, x86_64:     "Java SE 10.0.1"        /Library/Java/JavaVirtualMachines/jdk-10-latest/Contents/Home
    10.0.1, x86_64:     "Java SE 10.0.1"        /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
    9, x86_64:  "Java SE 9"     /Library/Java/JavaVirtualMachines/jdk-9-latest/Contents/Home
    9, x86_64:  "Java SE 9"     /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home
    1.8.0_221, x86_64:  "Java SE 8"     /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home
    1.8.0_221, x86_64:  "Java SE 8"     /Library/Java/JavaVirtualMachines/default/Contents/Home
    1.8.0_221, x86_64:  "Java SE 8"     /Library/Java/JavaVirtualMachines/jdk-8-latest/Contents/Home
```

Our Bazel workspace is defined here (has dependency versions): https://github.com/PolymerLabs/arcs/blob/master/WORKSPACE
Our team uses this setup script to install the project: https://github.com/PolymerLabs/arcs/blob/master/tools/setup

### Link to a public git repo demonstrating the problem:
Public repo: https://github.com/PolymerLabs/arcs

**Comment by alxrsngrtn** [comment]
I changed my Java version to 11, and things started working.

**Comment by hoisie** [comment]
Fixed in #5805

**Comment by Abhimanyu14** [comment]
@hoisie ,
Still getting this error. Is this fix released?

**Comment by yolapop** [comment]
I'm using Robolectric 4.4 and still getting this error

**Comment by hoisie** [comment]
Can you provide a stack trace?

**Comment by yolapop** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class com.package.MyClass
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.robolectric.internal.SandboxTestRunner.invokeAfterClass(SandboxTestRunner.java:127)
	at org.robolectric.internal.SandboxTestRunner.access$100(SandboxTestRunner.java:48)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:101)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
```

and other

```
java.lang.NoClassDefFoundError: Could not initialize class com.package.MyClass
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.createTest(RobolectricTestRunner.java:561)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:329)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.methodBlock(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:259)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hoisie** [comment]
@yolapop that is not the same exception as this issue. This issue is about UnsafeAccess errors in JDK 9+. The stack trace you posted seems to be an issue in your test or app code.

**Comment by yolapop** [comment]
To be fair the only changes I did was upgrading Robolectric from 4.3.1 to 4.4. I'll dig around more.

**Comment by liduer** [comment]
I'm using testng  7.4.0 and still getting this error
Btrace version : 2.2.1
jdk version : 
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

Exception in thread "Thread-0" java.lang.NoClassDefFoundError: org/openjdk/btrace/libs/org/jctools/util/UnsafeAccess
        at org.openjdk.btrace.libs.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields.<clinit>(BaseMpscLinkedArrayQueue.java:55)
        at org.openjdk.btrace.runtime.BTraceRuntimeImplBase.<init>(BTraceRuntimeImplBase.java:413)
        at org.openjdk.btrace.runtime.BTraceRuntimeImpl_11.<init>(BTraceRuntimeImpl_11.java:101)
        at org.openjdk.btrace.runtime.BTraceRuntimeImpl_11$Factory.getRuntime(BTraceRuntimeImpl_11.java:72)
        at org.openjdk.btrace.runtime.BTraceRuntimeImpl_11$Factory.getRuntime(BTraceRuntimeImpl_11.java:59)
        at org.openjdk.btrace.runtime.BTraceRuntimes.getRuntime(BTraceRuntimes.java:51)
        at org.openjdk.btrace.agent.Client.loadClass(Client.java:351)
        at org.openjdk.btrace.agent.Client.loadClass(Client.java:320)
        at org.openjdk.btrace.agent.RemoteClient.<init>(RemoteClient.java:146)
        at org.openjdk.btrace.agent.RemoteClient.getClient(RemoteClient.java:94)
        at org.openjdk.btrace.agent.Main.startServer(Main.java:858)
        at org.openjdk.btrace.agent.Main.lambda$main$1(Main.java:161)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by PauloLinhares09** [comment]
I have the sabe bug:

java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.jce.provider.BouncyCastleProvider
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState...
	
---------
Im using jdk 11,
Robolectric: 4.7.3

Somebody can help ?

**Comment by hoisie** [comment]
@PauloLinhares09 that is not the same stack trace as this issue. Please file a new issue with clear repro instructions.
