### ISSUE TITLE
4.4-alpha2: NoClassDefFoundError: android/telephony/TelephonyManager$CellInfoCallback

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#5832]
Getting a crash on 4.4-alpha-2 when testing UI that needs `Linkify` to create URL / Tel links on a project that is still SDK 28:

```
java.lang.NoClassDefFoundError: android/telephony/TelephonyManager$CellInfoCallback
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:304)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:273)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:250)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:145)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.app.SystemServiceRegistry$39.createService(SystemServiceRegistry.java:505)
	at android.app.SystemServiceRegistry$39.createService(SystemServiceRegistry.java:502)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:1098)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:1014)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1721)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:290)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:41)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:51)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:74)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:728)
	at pkg.RoboTest.foo(RoboTest.kt:39)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:550)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyManager$CellInfoCallback
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:189)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:133)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:119)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:119)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethod(Class.java:2128)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:304)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:273)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:250)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:145)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.app.SystemServiceRegistry$39.$$robo$$android_app_SystemServiceRegistry_39$createService(SystemServiceRegistry.java:505)
	at android.app.SystemServiceRegistry$39.createService(SystemServiceRegistry.java)
	at android.app.SystemServiceRegistry$39.createService(SystemServiceRegistry.java:502)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.$$robo$$android_app_SystemServiceRegistry_CachedServiceFetcher$getService(SystemServiceRegistry.java:1098)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java)
	at android.app.SystemServiceRegistry.$$robo$$android_app_SystemServiceRegistry$getSystemService(SystemServiceRegistry.java:1014)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java)
	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$getSystemService(ContextImpl.java:1721)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:290)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:41)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:51)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:74)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.$$robo$$android_content_ContextWrapper$getSystemService(ContextWrapper.java:728)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java)
	at pkg.RoboTest.foo(RoboTest.kt:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 11 more
```

Code to reproduce:

```kotlin
@RunWith(RobolectricTestRunner::class)
class RoboTest {
    @Test
    fun foo() {
        ApplicationProvider.getApplicationContext<Application>().getSystemService(Context.TELEPHONY_SERVICE) as TelephonyManager
    }
}
```

**Comment by realdadfish** [comment]
It's important that this is fixed, because SDK 28 is the last SDK where JDK 8 is still supported and many projects still couldn't make a move to a newer JDK, so they'd be stuck with Robolectric 4.3.x.

**Comment by hoisie** [comment]
I am quite surprised (and a little discouraged) that this wasn't caught internally at Google. 

This should be fixed by https://github.com/robolectric/robolectric/pull/5835/files#diff-ff963823cc2741db0ae984bc950f0011.
