### ISSUE TITLE
Robolectric Powermock classloader issue

### ISSUE THREAD

**Issue by yangsong551** [robolectric/robolectric#5919]
### Description
java.lang.ClassCastException: com.example.myapplication.MyApplication cannot be cast to com.example.myapplication.MyInterface

	at com.example.myapplication.MainActivity.testInterfact(MainActivity.java:19)
	at com.example.myapplication.MainActivity.onCreate(MainActivity.java:14)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:702)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:106)
	at org.robolectric.shadows.ShadowLegacyLooper.runPaused(ShadowLegacyLooper.java:322)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:106)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:111)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:251)
	at com.example.myapplication.ExampleUnitTest.testMakeE911Call(ExampleUnitTest.java:60)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:83)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1863)
	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:825)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:690)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
	at org.powermock.classloading.AbstractClassloaderExecutor.getResult(AbstractClassloaderExecutor.java:76)
	at org.powermock.classloading.AbstractClassloaderExecutor.invokeWithClassLoader(AbstractClassloaderExecutor.java:64)
	at org.powermock.classloading.AbstractClassloaderExecutor.executeWithClassLoader(AbstractClassloaderExecutor.java:56)
	at org.powermock.classloading.SingleClassloaderExecutor.execute(SingleClassloaderExecutor.java:33)
	at org.powermock.classloading.AbstractClassloaderExecutor.execute(AbstractClassloaderExecutor.java:40)
	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:75)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Test method
<pre>
@RunWith(RobolectricTestRunner.class)
@Config(shadows = {ShadowLog.class}, sdk = 28)
@PowerMockIgnore({"org.mockito.*", "org.robolectric.*", "android.*"})
@PrepareForTest(Utils.class)
public class ExampleUnitTest {
  @Rule
  public PowerMockRule rule = new PowerMockRule();

  @Before
  public void setUp() {
    ShadowLog.stream = System.out;
    MockitoAnnotations.initMocks(this);
  }

  @Test
  public void testMakeE911Call() {
    RttManager rtt = PowerMockito.spy(RttManager.getInstance());
    Whitebox.setInternalState(RttManager.class, "instance", rtt);
    Mockito.when(rtt.getC(Mockito.any(Context.class))).thenReturn(true);

    PowerMockito.spy(Utils.class);
    Mockito.when(Utils.getLable(Mockito.any(Context.class))).thenReturn("aaaa");

    MainActivity activity = Robolectric.buildActivity(MainActivity.class).setup().get();
  }
}
</pre>

MainActivity.java
<pre>
public class MainActivity extends AppCompatActivity {

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    testInterfact();
  }
  public void testInterfact(){
    ((MyInterface)getApplicationContext()).getA();// this code will be crash if we run test case
  }
</pre>

MyApplication
<pre>
public class MyApplication extends Application implements MyInterface {
  @Override
  public String getA() {
    return "AA";
  }
}
</pre>

### Robolectric & Android Version
    testImplementation 'junit:junit:4.13'
    testImplementation "org.robolectric:robolectric:4.3.1"
    testImplementation 'org.powermock:powermock-core:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4:2.0.7'
    testImplementation 'org.powermock:powermock-api-mockito2:2.0.7'
    testImplementation 'org.powermock:powermock-module-junit4-rule:2.0.7'
    testImplementation "org.powermock:powermock-classloading-xstream:2.0.7"

### Link to a public git repo demonstrating the problem:

This is Robolectric framework class loader issue， But I don’t have any way to solve it, unless I give up using Powermock or mock framework.

**Comment by hoisie** [comment]
As I have mentioned before on related issues with other mocking frameworks, solving this issue would require deep technical knowledge of Powermock, which is not something that I have ever used.

It would be really helpful if you or someone else takes the first dive to try to root cause what is happening here.

**Comment by yangsong551** [comment]
> As I have mentioned before on related issues with other mocking frameworks, solving this issue would require deep technical knowledge of Powermock, which is not something that I have ever used.
> 
> It would be really helpful if you or someone else takes the first dive to try to root cause what is happening here.

For Robolectric, I am a beginner. It is really frustrating to encounter this problem. I have been researching for 1 week and there is still no solution.

**Comment by hoisie** [comment]
Are you doing `Config(application = MyApplication.class)`?

If possible can you avoid using PowerMock and extending https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowWifiRttManager.java?

**Comment by yangsong551** [comment]
> Are you doing `@Config(application = MyApplication.class)`?
> 
> If possible can you avoid using PowerMock and extending https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowWifiRttManager.java?
> 
> It seems like you are trying to use a mocking framework to override the behavior of an Android object, which is effectively exactly what Robolectric does as well. Why not just use Robolectric?

I think you are right. There will be many unknown problems when using powermock and Robolectric framework at the same time. But I want to mock static methods in Robolectric. Do you have any suggestions for this ?

**Comment by yangsong551** [comment]
> > Are you doing `@Config(application = MyApplication.class)`?
> > If possible can you avoid using PowerMock and extending https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowWifiRttManager.java?
> > It seems like you are trying to use a mocking framework to override the behavior of an Android object, which is effectively exactly what Robolectric does as well. Why not just use Robolectric?
> 
> I think you are right. There will be many unknown problems when using powermock and Robolectric framework at the same time. But I want to mock static methods in Robolectric. Do you have any suggestions for this ?

**Comment by yangsong551** [comment]
> > > Are you doing `@Config(application = MyApplication.class)`?
> > > If possible can you avoid using PowerMock and extending https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowWifiRttManager.java?
> > > It seems like you are trying to use a mocking framework to override the behavior of an Android object, which is effectively exactly what Robolectric does as well. Why not just use Robolectric?
> > 
> > 
> > I think you are right. There will be many unknown problems when using powermock and Robolectric framework at the same time. But I want to mock static methods in Robolectric. Do you have any suggestions for this ?

Sorry, my understanding of Robolectric is too superficial, The shadow can realize it.

**Comment by hoisie** [comment]
You probably already saw this, but check out the `Custom Shadows` section here:

http://robolectric.org/extending/

You can then create a MyShadowWifiRttManager that extends Robolectric's ShadowWifiRttManager to have the behavior and the test APIs that you'd like.

**Comment by yangsong551** [comment]
> You probably already saw this, but check out the `Custom Shadows` section here:
> 
> http://robolectric.org/extending/
> 
> You can then create a MyShadowWifiRttManager that extends Robolectric's ShadowWifiRttManager to have the behavior and the test APIs that you'd like.

I have solved this problem with Custom Shadows, thank you very much for your help
