### ISSUE TITLE
Robolectric does not work on JDK 15

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#5931]
### Description

```
java.lang.NoClassDefFoundError: android/util/TypedValue
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3220)
	at java.base/java.lang.Class.getDeclaredField(Class.java:2567)
	at org.robolectric.shadows.ShadowAssetManager$_AssetManager_$$Reflector0.setSystem(Unknown Source)
	at org.robolectric.shadows.ShadowArscAssetManager.reset(ShadowArscAssetManager.java:92)
	at org.robolectric.Shadows.reset(Shadows.java:2302)
	at org.robolectric.android.internal.AndroidTestEnvironment.resetState(AndroidTestEnvironment.java:518)
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:349)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:347)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:272)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: couldn't load android.util.TypedValue
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:147)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 16 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 59
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
	at org.robolectric.internal.bytecode.ClassNodeProvider.createClassNode(ClassNodeProvider.java:24)
	at org.robolectric.internal.bytecode.ClassNodeProvider.getClassNode(ClassNodeProvider.java:16)
	at org.robolectric.internal.bytecode.InstrumentingClassWriter.typeInfo(InstrumentingClassWriter.java:115)
	at org.robolectric.internal.bytecode.InstrumentingClassWriter.getCommonSuperClass(InstrumentingClassWriter.java:36)
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
	at org.objectweb.asm.Frame.merge(Frame.java:1299)
	at org.objectweb.asm.Frame.merge(Frame.java:1244)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:764)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:408)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrumentToBytes(ClassInstrumentor.java:80)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$maybeInstrumentClass$2(SandboxClassLoader.java:139)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:138)
	... 20 more
```

### Steps to Reproduce

Run a robolectric test with JDK 15

### Robolectric & Android Version

4.4, any version

**Comment by hoisie** [comment]
Looks like we need to update asm?

**Comment by ZacSweers** [comment]
yeah likely

**Comment by hoisie** [comment]
Can this be closed?

**Comment by ZacSweers** [comment]
Yeah I think so, though would be good to get a release of some sort available with the fix

**Comment by hoisie** [comment]
[4.5-alpha-1](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.5-alpha-1) is available which contains that update.

**Comment by ZacSweers** [comment]
Confirmed that this works (on linux) now with 4.5-alpha-1 👍

**Comment by satur9nine** [comment]
Robolectric 4.5 works but this seems broken again as of Robolectric 4.6 onwards. Tested up to 4.7.3.

**Comment by hoisie** [comment]
@satur9nine can you file a new issue, and include a stack trace and repo instructions? Robolectric 4.7.3 uses [ASM 9.2](https://github.com/robolectric/robolectric/blob/master/buildSrc/build.gradle#L16), so you are probably facing a separate issue.

**Comment by mjayansf** [comment]
Is there an update on this? I'm facing the same error on 4.7.3 from 4.3.1

**Comment by utzcoz** [comment]
> Is there an update on this? I'm facing the same error on 4.7.3 from 4.3.1

@mjayansf Could you file a new issue with your stacktrace for your problem? Some folks has confirmed that 4.7.1 can work with JDK 16.
