### ISSUE TITLE
Idle throwing suggestion of adding idle

### ISSUE THREAD

**Issue by darakeon** [robolectric/robolectric#5938]
### Description

It says that idle is missing but actually it happens inside idle
```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
Caused by: java.lang.IllegalStateException: The specified message queue synchronization  barrier token has not been posted or has already been removed.
	at android.os.MessageQueue.removeSyncBarrier(MessageQueue.java:515)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1454)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:305)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:270)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:87)
	at com.darakeon.dfm.testutils.robolectric.WaitTasksFinishKt.waitTasksFinish(waitTasksFinish.kt:12)
	at com.darakeon.dfm.base.BaseActivityTest.onCreateSetMenuLongClicksLogout(BaseActivityTest.kt:213)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.darakeon.dfm.testutils.LogRule$apply$1.invoke(LogRule.kt:19)
	at com.darakeon.dfm.testutils.LogRule$apply$1.invoke(LogRule.kt:15)
	at com.darakeon.dfm.testutils.LogRule$processInStatement$1.evaluate(LogRule.kt:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
```

### Steps to Reproduce

It's actually randomly happening on my tests.

### Robolectric & Android Version

- Robolectric 4.4
- Android: api 28

### Link to a public git repo demonstrating the problem:

https://github.com/darakeon/dfm/blob/4.3.0.0/android/App/src/test/kotlin/com/darakeon/dfm/settings/SettingsActivityTest.kt#L148

https://github.com/darakeon/dfm/blob/4.3.0.0/android/TestUtils/src/main/kotlin/com/darakeon/dfm/testutils/robolectric/waitTasksFinish.kt

I intent to try to dig robolectric code to understand it better (maybe try to fix), but if someone else know how to or see something I'm doing wrong, I'm getting crazy about this stuff

**Comment by darakeon** [comment]
One thing: this fails if I run a bunch of tests. If one test is ran alone, it passes without problem. Still trying to figure out why.

**Comment by hoisie** [comment]
Are animations being run? Any time you see Choreographer in the stack trace that there's an active animation.

**Comment by hoisie** [comment]
Do not use mock activities. Use real Activities and either Robolectric.setupActivity or ActivityScenario.

Activities set up ViewRootImpl objects, which may explain why you're getting stack traces in that area.

**Comment by darakeon** [comment]
https://github.com/darakeon/dfm/blob/4.3.0.0/android/TestUtils/src/main/kotlin/com/darakeon/dfm/testutils/robolectric/ActivityMock.kt

This is ActivityMock, just encapsulating robolectric

**Comment by darakeon** [comment]
I used `buildActivity`, could this be the problem?

**Comment by hoisie** [comment]
Maybe try setupActivity? (which does create/start/resume/visible/etc..)

**Comment by darakeon** [comment]
I copied this stacktrace from circleCI, locally it does not have Choreographer at stacktraces.

A local example:

```
java.lang.IllegalStateException: The specified message queue synchronization  barrier token has not been posted or has already been removed.

	at android.os.MessageQueue.removeSyncBarrier(MessageQueue.java:515)
	at android.view.ViewRootImpl.unscheduleTraversals(ViewRootImpl.java:1445)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3854)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6753)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:6730)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:124)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:290)
	at org.robolectric.internal.bytecode.ShadowImpl.directlyOn(ShadowImpl.java:50)
	at org.robolectric.shadow.api.Shadow.directlyOn(Shadow.java:56)
	at org.robolectric.shadows.ShadowWindowManagerImpl.removeViewImmediate(ShadowWindowManagerImpl.java:71)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java)
	at android.app.Dialog.dismissDialog(Dialog.java:375)
	at android.app.Dialog.dismiss(Dialog.java:358)
	at android.app.Dialog$GeneratedProxy/385344239.dismiss(Unknown Source)
	at org.robolectric.shadows.ShadowDialog.dismiss(ShadowDialog.java:69)
	at android.app.Dialog.dismiss(Dialog.java)
	at com.darakeon.dfm.base.UIHandler.closeDialog(UIHandler.kt:75)
	at com.darakeon.dfm.base.UIHandler.endUIWait(UIHandler.kt:68)
	at com.darakeon.dfm.base.BaseActivity.endWait(BaseActivity.kt:226)
	at com.darakeon.dfm.lib.api.ResponseHandler.onFailure(ResponseHandler.kt:47)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onFailure$1(DefaultCallAdapterFactory.java:88)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:305)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:270)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:87)
	at com.darakeon.dfm.testutils.robolectric.WaitTasksFinishKt.waitTasksFinish(waitTasksFinish.kt:12)
	at com.darakeon.dfm.moves.MovesActivityTest.save(MovesActivityTest.kt:917)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.darakeon.dfm.testutils.LogRule$apply$1.invoke(LogRule.kt:19)
	at com.darakeon.dfm.testutils.LogRule$apply$1.invoke(LogRule.kt:15)
	at com.darakeon.dfm.testutils.LogRule$processInStatement$1.evaluate(LogRule.kt:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by darakeon** [comment]
Is there a chance that some cleanup is needed after tests? Because it is a random error AND if I run just the failed tests, they succeed

**Comment by hoisie** [comment]
I can't repro the failures in that git rep. What's the gradle command to demonstrate the failures? What Java version is this?

**Comment by darakeon** [comment]
Java 8, or at least it is what is in gradle, so I think should be this.

But I'm thinking: Lib project does not throws this stuff. So it is about something I have on the BaseActivity of the App.

I'm running the tests at Android Studio. Still digging. And I'll keep digging for the night (it's 22h24 here right now).

**Comment by darakeon** [comment]
Discovered. It is about ResponseHandler of api mock calls. Some of the responses were arriving just after the test finished, I had to add the waiting for idle at more places.

To discover which places, I printed the caller identifier when init of ResponseHandler and at Success/Fail responses, so I could see which tests were invading which spaces.

So I'm closing this issue, giving this is no issue at all. If someone is having same error, start printing identifiers of stuff that do async job at it's constructor and it's responses, so you can see if is there anyone invading another things spaces.

**Comment by darakeon** [comment]
Check `logDebug` function uses [here](https://github.com/darakeon/dfm/blob/4.3.0.0/android/Lib/src/main/kotlin/com/darakeon/dfm/lib/api/ResponseHandler.kt) (if the branch is deleted, check [here](https://github.com/darakeon/dfm/blob/main/android/Lib/src/main/kotlin/com/darakeon/dfm/lib/api/ResponseHandler.kt))
