### ISSUE TITLE
ParameterizedRobolectricTestRunner doesn't work with inline classes

### ISSUE THREAD

**Issue by lwasyl** [robolectric/robolectric#5942]
The following test:

```kotlin
@RunWith(ParameterizedRobolectricTestRunner::class)
class NotWorking(
    val duration: kotlin.time.Duration,
) {

    companion object {

        @JvmStatic
        @ParameterizedRobolectricTestRunner.Parameters
        fun data(): Collection<Array<Any>> = listOf(
            arrayOf(10.hours),
        )
    }

    @Test
    fun test() {
        println(duration)
    }
}
```

fails with 

```java
java.lang.IllegalArgumentException: wrong number of arguments

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.ParameterizedRobolectricTestRunner$TestClassRunnerForParameters.createTestInstance(ParameterizedRobolectricTestRunner.java:105)
	at org.robolectric.ParameterizedRobolectricTestRunner$TestClassRunnerForParameters.access$300(ParameterizedRobolectricTestRunner.java:89)
	at org.robolectric.ParameterizedRobolectricTestRunner$TestClassRunnerForParameters$1.createTest(ParameterizedRobolectricTestRunner.java:251)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
	at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
	at org.robolectric.internal.SandboxTestRunner$HelperTestRunner.methodBlock(SandboxTestRunner.java:329)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner.methodBlock(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:259)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The issue is with `kotlin.time.Duration` being an `inline class`, as the following test passes:

```kotlin
class NonInlineWrapper(val duration: Duration)

@RunWith(ParameterizedRobolectricTestRunner::class)
class NotWorking(
    val wrapper: NonInlineWrapper,
) {

    companion object {

        @JvmStatic
        @ParameterizedRobolectricTestRunner.Parameters
        fun data(): Collection<Array<Any>> = listOf(
            arrayOf(NonInlineWrapper(10.hours)),
        )
    }

    @Test
    fun test() {
        println(wrapper.duration)
    }
}
```

Robolectric 4.4

**Comment by hoisie** [comment]
I am not a Kotlin expert so I'd probably suggest searching Github for usages of `ParameterizedRobolectricTestRunner::class` and see what works there: https://github.com/search?q=%40RunWith%28ParameterizedRobolectricTestRunner%3A%3Aclass%29&type=code

In general I advise folks to avoid using ParameterizedRobolectricTestRunner because it has some limitations. Mainly you cannot have Android objects be parameters due to ClassLoader isolation issues.

**Comment by lwasyl** [comment]
I'm not sure I follow - I know how `ParameterizedRobolectricTestRunner` works and I do use it occasionally. I also do know how to workaround this issue, and I believe it's pretty clear that the problem is using inline class as one of the parameters. It looks like a problem with Robolectric so I opened an issue. I understand if it can't be addressed right now because inline classes are still technically in alpha, but I figured it's something Robolectric maintainers and users should be aware of.

**Comment by hoisie** [comment]
Sounds good :) If you find out the root cause we would happily accept a PR
as the current Robolectric maintainers are not Kotlin experts :)

**Comment by realdadfish** [comment]
If one decompiles that to Java, then one sees that in the constructor the inline class is shrinked down to the actual underlying type of the inline class

```java
   public NotWorking(double duration, DefaultConstructorMarker $constructor_marker) {
      this(duration);
   }
```

while the construct `array(10.hours)` is compiled down to

```java
new Duration[]{Duration.box-impl(DurationKt.getHours(10))};
```

The Kotlin compiler might be smart enough to figure out what to do, but the Java-Interop might not, especially since the instantiation of the test class here has to happen via Java-based reflection.

Since inline classes are still experimental IIRC, I don't know how well this interop use case is actually supported yet by Kotlin (see also https://discuss.kotlinlang.org/t/inline-classes-tedious-to-use-considering-java-interop/9382 for reference).
