### ISSUE TITLE
OutOfMemoryError when using ShadowCameraDeviceImpl#createCaptureRequest on sdk lower than P

### ISSUE THREAD

**Issue by elson-dsouza** [robolectric/robolectric#5950]
### Description
OutOfMemoryError when using ShadowCameraDeviceImpl#createCaptureRequest on sdk lower than P

### Steps to Reproduce
Run the following test
```
private static final String CAMERA_ID_0 = "cameraId0";
private final CameraManager cameraManager =
      (CameraManager)
          ApplicationProvider.getApplicationContext().getSystemService(Context.CAMERA_SERVICE);

private final CameraCharacteristics characteristics =
      ShadowCameraCharacteristics.newCameraCharacteristics();
private CameraDevice cameraDevice;
private CameraCaptureSession captureSession;
private CaptureRequest.Builder builder;
private CameraDevice.StateCallback stateCallback;

@Before
public void setUp() throws CameraAccessException {
    stateCallback = createMockCameraDeviceCallback();
    shadowOf(cameraManager).addCamera(CAMERA_ID_0, characteristics);
    cameraManager.openCamera(CAMERA_ID_0, stateCallback, new Handler());
    shadowOf(Looper.getMainLooper()).idle();
}

private CameraDevice.StateCallback createMockCameraDeviceCallback() {
    CameraDevice.StateCallback mockCallback = mock(CameraDevice.StateCallback.class);
    doAnswer(
            args -> {
              cameraDevice = args.getArgument(0);
              return null;
            })
        .when(mockCallback)
        .onOpened(any(CameraDevice.class));
    doAnswer(
            args -> {
              fail();
              return null;
            })
        .when(mockCallback)
        .onDisconnected(any(CameraDevice.class));
    doAnswer(
            args -> {
              fail();
              return null;
            })
        .when(mockCallback)
        .onError(any(CameraDevice.class), anyInt());

    return mockCallback;
}

@Test 
@Config(sdk = VERSION_CODES.LOLLIPOP_MR1)
public void createCaptureRequest() {
    builder = cameraDevice.createCaptureRequest(CameraDevice.TEMPLATE_RECORD);
    CaptureRequest request = builder.build();
    assertThat(request.getLogicalCameraId()).isEqualTo(CAMERA_ID_0);
}
```
Running this test we get stack trace
```
java.lang.OutOfMemoryError: Failed to allocate native CameraMetadata
	at android.hardware.camera2.impl.CameraMetadataNative.__constructor__(CameraMetadataNative.java:264)
	at android.hardware.camera2.impl.CameraMetadataNative.<init>(CameraMetadataNative.java)
	at org.robolectric.shadows.ShadowCameraDeviceImpl.createCaptureRequest(ShadowCameraDeviceImpl.java:30)
	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java)
```
### Robolectric & Android Version
Reproduced using Robolectric 4.4 and sdk LOLLIPOP_MR1

**Comment by hoisie** [comment]
Looks like the minSdk for https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowCameraMetadataNative.java#L15-L18 needs to be bumped down significantly. Can you send a PR to do that?

**Comment by hoisie** [comment]
FWIW this is not a real OOM, it's thrown explicitly:

http://androidxref.com/5.1.1_r6/xref/frameworks/base/core/java/android/hardware/camera2/impl/CameraMetadataNative.java#264
