### ISSUE TITLE
com.almworks.sqlite4java.SQLiteException: no such table error running DB tests with Robolectric in Android Studio

### ISSUE THREAD

**Issue by santiagoluisfina** [robolectric/robolectric#5960]
### Description
I have an app that run without this DB errors in a mobile, but I'm trying to add tests without the use of a mobile for future releases. I'm getting this error running a Test of a function Database using Robolectric.

### Steps to Reproduce
Run test ExampleUnitTest

### Robolectric & Android Version
Robolectric org.robolectric:robolectric:4.2.1
Android Studio 4.0.1
minSdkVersion 17
targetSdkVersion 28
Gradle 4

### Link to a public git repo demonstrating the problem:
https://github.com/santiagoluisfina/androidSQLTest

### error log:
[Robolectric] com.systango.androidsqlitedbtester.ExampleUnitTest.obt_ok: sdk=28; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28

android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: 1

	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getSqliteException(ShadowSQLiteConnection.java:761)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:731)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:720)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:417)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:89)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1408)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1255)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1126)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1294)
	at com.systango.androidsqlitedbtester.ExampleUnitTest.getLibro(ExampleUnitTest.kt:47)
	at com.systango.androidsqlitedbtester.ExampleUnitTest.obt_ok(ExampleUnitTest.kt:39)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:256)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() SELECT ID_LIBRO, LIBRO, ABREVIATURA FROM TBL_LIBROS WHERE id_libro = ? [no such table: TBL_LIBROS]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:199)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getFuture(ShadowSQLiteConnection.java:726)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:720)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:417)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:89)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$acquirePreparedStatement(SQLiteConnection.java:903)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$prepare(SQLiteConnection.java:514)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java)
	at android.database.sqlite.SQLiteSession.$$robo$$android_database_sqlite_SQLiteSession$prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java)
	at android.database.sqlite.SQLiteProgram.$$robo$$android_database_sqlite_SQLiteProgram$__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.$$robo$$android_database_sqlite_SQLiteDirectCursorDriver$query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$rawQueryWithFactory(SQLiteDatabase.java:1408)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$queryWithFactory(SQLiteDatabase.java:1255)
	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$query(SQLiteDatabase.java:1126)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$query(SQLiteDatabase.java:1294)
	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java)
	at com.systango.androidsqlitedbtester.ExampleUnitTest.getLibro(ExampleUnitTest.kt:47)
	at com.systango.androidsqlitedbtester.ExampleUnitTest.obt_ok(ExampleUnitTest.kt:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 14 more
Caused by: com.almworks.sqlite4java.SQLiteException: [1] DB[1] prepare() SELECT ID_LIBRO, LIBRO, ABREVIATURA FROM TBL_LIBROS WHERE id_libro = ? [no such table: TBL_LIBROS]
	at com.almworks.sqlite4java.SQLiteConnection.throwResult(SQLiteConnection.java:1309)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:487)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:542)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:529)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:420)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:417)
	... 5 more

Disconnected from the target VM, address: '127.0.0.1:2840', transport: 'socket'

Process finished with exit code -1

**Comment by hoisie** [comment]
I don't think this has anything to do with Robolectric. It seems like you're trying to replace the database file with a custom database `DBtester.db`. I have not seen that type of approach before and would recommend using sql statements in the code to initialize the database.

**Comment by santiagoluisfina** [comment]
Hi Hoisie, I give you more context from my needs: I'm testing a database migration from an existing DB with data... so, I need a base DB to later apply the migration scripts, and the usual approach to do that is to copy a base DB from Assets, (specially if your DB need to be initally preloaded with data). And this test works without any problem using a mobile, but fail when I'm trying to use Robolectric to avoid the mobile... any other idea? Thanks in advance.

**Comment by santiagoluisfina** [comment]
Finally was an execution sequence error in my code, because using the copy in onCreate method executed again onCreate method resulting in a corrupted DB file. Finally I moved the copy code to the getReadableDatabase method and leave the onCreate empty and all works OK. Thanks for your answer.
