### ISSUE TITLE
Sqlite-using tests no longer work with Robolectric 4.5-alpha-1

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#5961]
### Description

We have some tests that hit sqlite classes. When running on JDK 11, we get a failure like this on macOS catalina

```
java.lang.IllegalArgumentException: resource sqlite4java/osx/libsqlite4java.jnilib not found.

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.common.io.Resources.getResource(Resources.java:195)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.getLibraryByteSource(SQLiteLibraryLoader.java:64)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:51)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:73)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:669)
	at android.database.sqlite.SQLiteDatabase.create(SQLiteDatabase.java:828)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:215)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.<init>(SqliteJobQueue.java:49)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.LineCuttingSqlPriorityQueueImpl.<init>(LineCuttingSqlPriorityQueueImpl.kt:39)
	at com.slack.jobqueue.queues.LineCuttingSqlPriorityQueue.<init>(LineCuttingSqlPriorityQueue.kt:39)
	at com.slack.jobqueue.queues.LineCuttingSqlPriorityQueueTest$1.invoke(LineCuttingSqlPriorityQueueTest.kt:13)
	at com.slack.jobqueue.queues.LineCuttingSqlPriorityQueueTest$1.invoke(LineCuttingSqlPriorityQueueTest.kt:10)
	at com.slack.jobqueue.queues.BaseLineCuttingQueueTest.createNewJobQueueWithSessionId(BaseLineCuttingQueueTest.kt:41)
	at com.slack.jobqueue.queues.BaseLineCuttingQueueTest.createNewJobQueue(BaseLineCuttingQueueTest.kt:45)
	at com.slack.jobqueue.queues.BaseLineCuttingQueueTest.testDelayUntilWithNetworkRequirementAndRegularDelayedJob(BaseLineCuttingQueueTest.kt:975)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Steps to Reproduce

Run a test that hits `SQLiteOpenHelper.getWritableDatabase`

### Robolectric & Android Version

4.5-alpha-1, android version R

**Comment by ZacSweers** [comment]
This may be an Android R issue too, I'm not 100% sure

**Comment by hoisie** [comment]
My guess is that it's related to #5216. cc @georgi-neykov-hub . Probably just need to update the dylib path on mac.

**Comment by ZacSweers** [comment]
If you have snapshots available, I can try #5962 once it's merged

**Comment by hoisie** [comment]
I believe 4.5-SNAPSHOT should be available from the snapshots repo.

**Comment by hoisie** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/robolectric/robolectric/4.5-SNAPSHOT/

**Comment by ZacSweers** [comment]
Just tried, looks good 👍
