### ISSUE TITLE
java.lang.ClassNotFoundException: android.telephony.TelephonyDisplayInfo on 4.5-alpha-1

### ISSUE THREAD

**Issue by aaronweihe** [robolectric/robolectric#5968]
### Description
Upgrading to 4.5-alpha-1, but running into this exception when `TelephonyManager` is mocked.

```
Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyDisplayInfo
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:163)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:129)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:304)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:273)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:250)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:145)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.telephony.TelephonyManager.<clinit>(TelephonyManager.java)
	at android.text.util.Linkify.$$robo$$android_text_util_Linkify$gatherTelLinks(Linkify.java:542)
	at android.text.util.Linkify.gatherTelLinks(Linkify.java)
	at android.text.util.Linkify.$$robo$$android_text_util_Linkify$addLinks(Linkify.java:256)
	at android.text.util.Linkify.addLinks(Linkify.java)
	at android.text.util.Linkify.$$robo$$android_text_util_Linkify$addLinks(Linkify.java:226)
	at android.text.util.Linkify.addLinks(Linkify.java)
	at androidx.core.text.util.LinkifyCompat.$$robo$$androidx_core_text_util_LinkifyCompat$addLinks(LinkifyCompat.java:116)
	at androidx.core.text.util.LinkifyCompat.addLinks(LinkifyCompat.java)
```
### Steps to Reproduce
Mock `TelephonyManager` in the test.

### Robolectric & Android Version
Robolectric: 4.5-alpha-1
Android: 29(compile and target)
JDK 11

### Link to a public git repo demonstrating the problem:
https://github.com/aaronweihe/AGPPlayground/blob/robolectric-4-5-alpha-1-telephony/app/src/test/java/org/aaronhe/ExampleTest.kt

**Comment by aaronweihe** [comment]
An interesting note is the `TelephonyDisplayInfo` is only added in API 30. Tried configuring the test running on sdk 29 but no luck

**Comment by hoisie** [comment]
If you really want to mock TelephonyManager (I strongly recommend **not** mocking any Android objects) you need to bump things in your `dependencies.gradle` to 30. 

```
ext.versions = ['buildTools': '29.0.3',
                'compileSdk': 30,
                'targetSdk' : 30,
                'minSdk'    : 23]
```

**Comment by hoisie** [comment]
Actually, this is definitely issue, we shouldn't force people to upgrade to Android R to use TelephonyManager.

This causes the same exception as well:

```
  @Test
  fun example() {
    val telephonyManager = RuntimeEnvironment.application.getSystemService(Context.TELEPHONY_SERVICE);
  }
```

**Comment by aaronweihe** [comment]
> If you really want to mock TelephonyManager (I strongly recommend **not** mocking any Android objects) you need to bump things in your `dependencies.gradle` to 30.
> 
> ```
> ext.versions = ['buildTools': '29.0.3',
>                 'compileSdk': 30,
>                 'targetSdk' : 30,
>                 'minSdk'    : 23]
> ```
> 
> It would be better to use Robolectric to get the functionality you want from TelephonyManager than to mock it. Mocking it causes the Android classes to be instrumented multiple times, which can lead to some very unpredictable interactions.

Yea understood. This was from a piece of legacy code. Ran into this when we were upgrading from 4.4 to 4.5-alpha-1.
