### ISSUE TITLE
Unable to run with RobolectricTestRunner (NoSuchMethodError: No getAnnotatedParameterTypes())

### ISSUE THREAD

**Issue by jhchee** [robolectric/robolectric#5999]
### Description
@RunWith(RobolectricTestRunner::class) returns the following error.
```
java.lang.NoSuchMethodError: No virtual method getAnnotatedParameterTypes()[Ljava/lang/reflect/AnnotatedType; in class Ljava/lang/reflect/Executable; or its super classes (declaration of 'java.lang.reflect.Executable' appears in /apex/com.android.runtime/javalib/core-oj.jar)
	at org.robolectric.util.inject.Injector.resolveDependencies(Injector.java:286)
	at org.robolectric.util.inject.Injector.inject(Injector.java:248)
	at org.robolectric.util.inject.Injector.lambda$memoized$1$Injector(Injector.java:232)
	at org.robolectric.util.inject.-$$Lambda$Injector$9adlN9c5JSO7J0D33kkXKLULCCM.get(Unknown Source:4)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:202)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:75)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:103)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:98)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at androidx.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:63)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at androidx.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:153)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2204)

Tests ran to completion.
```
Navigating into Injector.java, getAnnotatedParameterTypes method is marked as unresolved.

![image](https://user-images.githubusercontent.com/33974196/96536614-0c5ac800-12c7-11eb-9321-760a057720aa.png)

Am I missing something?

### Robolectric & Android Version
robolectric version: 4.4
minSdkVersion 21
targetSdkVersion 30

**Comment by jhchee** [comment]
The AnnotatedType interface is present within the reflect package. Seems like something is preventing robolectric from accessing it.

![image](https://user-images.githubusercontent.com/33974196/96539735-5b582b80-12ce-11eb-8aa3-2492033c65bf.png)

**Comment by hoisie** [comment]
Is this Robolectric in the Android framework? It looks like you are running a Robolectric with libcore (core-oj)?

`declaration of 'java.lang.reflect.Executable' appears in /apex/com.android.runtime/javalib/core-oj.jar`

**Comment by jhchee** [comment]
I'm using Robolectric for Android instrumentation test. How do I differentiate between Robolectric Android and Robolectric with libcore?

**Comment by hoisie** [comment]
You cannot use Robolectric in Android instrumentation tests. It does not operate on Android VMs or real Android devices. It only runs on the host JVM (e.g. desktop machines).

**Comment by jhchee** [comment]
Oh I see, I have mixed up Robolectric and instrumentation test. Thanks for clarifying this.
