### ISSUE TITLE
Tests with LiveData do not work when using Robolectric 4.4

### ISSUE THREAD

**Issue by ludovicroland** [robolectric/robolectric#6000]
### Description

I have and Android application in which one I use Robolectric in order to test my AndroidViewModel classes on the JVM using Robolectric 4.3.1.

When I update the dependency of Robolectric from 4.3.1 to 4.4, my tests fail. LiveData cannot be tested anymore.

### Robolectric & Android Version

I am using Robolectric 4.3.1 and then Robolectric 4.4.

I am using the JDK in version 11 and the following robolectric.properties file:

```
sdk=29
```

Here a very simple code to reproduce :

```kotlin
package com.myapp

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.MutableLiveData
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.myapp.utils.getOrAwaitValue
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

@RunWith(AndroidJUnit4::class)
@Config(application = Application::class)
class RobotTest
{

  class RobotViewModel(application: Application)
    : AndroidViewModel(application)
  {

    val robotLiveData = MutableLiveData<Boolean>().apply {
      postValue(false)
    }

  }

  @Test
  fun theRobotTest()
  {
    val robotViewModel = RobotViewModel(ApplicationProvider.getApplicationContext())

    robotViewModel.robotLiveData.postValue(true)
    Assert.assertTrue(robotViewModel.robotLiveData.getOrAwaitValue())

    robotViewModel.robotLiveData.postValue(false)
    Assert.assertFalse(robotViewModel.robotLiveData.getOrAwaitValue())
  }

}
```

The `getOrAwaitValue()` is an extension method from a blog post from Google:

```kotlin
package com.myapp

import androidx.lifecycle.LiveData
import androidx.lifecycle.Observer
import java.util.concurrent.CountDownLatch
import java.util.concurrent.TimeUnit
import java.util.concurrent.TimeoutException

//source : https://medium.com/androiddevelopers/unit-testing-livedata-and-other-common-observability-problems-bb477262eb04
fun <T> LiveData<T>.getOrAwaitValue(time: Long = 2, timeUnit: TimeUnit = TimeUnit.SECONDS): T
{
  var data: T? = null
  val latch = CountDownLatch(1)

  val observer = object : Observer<T>
  {

    override fun onChanged(o: T?)
    {
      data = o
      latch.countDown()
      this@getOrAwaitValue.removeObserver(this)
    }

  }

  this.observeForever(observer)

  // Don't wait indefinitely if the LiveData is not set.
  if (!latch.await(time, timeUnit))
  {
    throw TimeoutException("LiveData value was never set.")
  }

  @Suppress("UNCHECKED_CAST")
  return data as T
}
```

With Robolectric 4.3.1, the test is OK with the following warnings:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.robolectric.util.ReflectionHelpers$6 (file:/C:/Users/rolan/.gradle/caches/modules-2/files-2.1/org.robolectric/shadowapi/4.3.1/a93e55b36c418aa3afc17c26eac82590a3bfb63e/shadowapi-4.3.1.jar) to method java.lang.ClassLoader.getPackage(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.robolectric.util.ReflectionHelpers$6
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Robolectric] com.myapp.RobotTest.theRobotTest: sdk=29; resources=BINARY
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=29
```

With Robolectric 4.4, the test is KO with the following stackstrace:

```
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=29

java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException: LiveData value was never set.
	at com.myapp.android.utils.LiveDataExtKt.getOrAwaitValue(LiveDataExt.kt:36)
	at com.myapp.android.utils.LiveDataExtKt.getOrAwaitValue$default(LiveDataExt.kt:14)
	at com.myapp.android.RobotTest.theRobotTest(RobotTest.kt:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
```

I also tested with Robolectric 4.5-SNAPSHOT. The test is KO with the following stackstrace: 

```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException: LiveData value was never set.
	at com.myapp.android.utils.LiveDataExtKt.getOrAwaitValue(LiveDataExt.kt:36)
	at com.myapp.android.utils.LiveDataExtKt.getOrAwaitValue$default(LiveDataExt.kt:14)
	at com.myapp.android.RobotTest.theRobotTest(RobotTest.kt:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more

Process finished with exit code -1
```

**Comment by hoisie** [comment]
Did you try adding a call to shadowOf(getMainLooper()).idle()?

**Comment by ludovicroland** [comment]
@hoisie : Thank you for your answer. Where should I call this line? At the beginning of the test?

**Comment by hoisie** [comment]
I'm guessing after each call to robotViewModel.robotLiveData.postValue(true)

**Comment by ludovicroland** [comment]
@hoisie,

Unfortunately it does not work. I have update the sample test like this:

 ```kotlin
  @Test
  fun theRobotTest()
  {
    val robotViewModel = RobotViewModel(ApplicationProvider.getApplicationContext())

    robotViewModel.robotLiveData.postValue(true)
    Assert.assertTrue(robotViewModel.robotLiveData.getOrAwaitValue())
    Shadows.shadowOf(Looper.getMainLooper()).idle()

    robotViewModel.robotLiveData.postValue(false)
    Assert.assertFalse(robotViewModel.robotLiveData.getOrAwaitValue())
    Shadows.shadowOf(Looper.getMainLooper()).idle()
  }
```

But the result is the same:

```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.

	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException: LiveData value was never set.
	at com.myapp.android.utils.LiveDataExtKt.getOrAwaitValue(LiveDataExt.kt:36)
	at com.myapp.utils.LiveDataExtKt.getOrAwaitValue$default(LiveDataExt.kt:14)
	at com.myapp.RobotTest.theRobotTest(RobotTest.kt:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
```

**Comment by ludovicroland** [comment]
@hoisie,

Thank you for your message. It seems to work.

Here the test after the update:

```
  @Test
  fun theRobotTest()
  {
    val robotViewModel = RobotViewModel(ApplicationProvider.getApplicationContext())

    robotViewModel.robotLiveData.postValue(true)
    Shadows.shadowOf(Looper.getMainLooper()).idle()
    Assert.assertTrue(robotViewModel.robotLiveData.getOrAwaitValue())

    robotViewModel.robotLiveData.postValue(false)
    Shadows.shadowOf(Looper.getMainLooper()).idle()
    Assert.assertFalse(robotViewModel.robotLiveData.getOrAwaitValue())
  }
```

Now the test is OK. 

Thank you again. I am closing this issue.

**Comment by vinaygopinath** [comment]
I wasn't able to fix the issue by calling `Shadows.shadowOf(Looper.getMainLooper()).idle()` after the `LiveData.postValue` change. What worked was adding `InstantTaskExecutorRule`

```kotlin
import androidx.arch.core.executor.testing.InstantTaskExecutorRule

class SomeClassTest {
    
  // Refer https://developer.android.com/reference/androidx/arch/core/executor/testing/InstantTaskExecutorRule
  @get: Rule
  val instantExecutorRule = InstantTaskExecutorRule()

  // create viewModel instance

  @Test
  fun `should apply LiveData changes`() {
    viewModel.liveData.postValue("New value")
    
    Assert.assertEquals(viewModel.liveData.value, "New value")
  } 
}
```

**Comment by RameshAran** [comment]
Thanks @vinaygopinath . 
`@get: Rule
    val instantExecutorRule = InstantTaskExecutorRule()`

Adding InstantTaskExecutorRule works for me.

**Comment by aljohnston112** [comment]
Adding the InstantTaskExecutorRule gets me a "No tests found for given includes: ..." message. Removing it lets the test be found, but obviously that is broken.
