### ISSUE TITLE
Activity Instantiation

### ISSUE THREAD

**Issue by mgood7123** [robolectric/robolectric#6021]
### Description

can robolectric be used to instantiate activities from within a running Android Application on an Android Operating System?

            // both Fragments and Activities require an Activity to be attached
            //
            //      Caused by: java.lang.IllegalStateException: No activity
            //        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1626)
            //        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
            //        at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2999)
            //        at android.app.FragmentController.dispatchCreate(FragmentController.java:173)
            //        at android.app.Activity.onCreate(Activity.java:1478)
            //
            // with Fragment we get
            //     Your activity is not yet attached to the Application instance.
            //     You can't request ViewModel before onCreate call.

```java
public class ApplicationEmulationEngine {
    public String TAG = "ApplicationEmulationEngine";

    Thread main = null;
    private ApplicationEmulationEngine(boolean mainThread, VST vst, Class callback, ViewGroup contentRoot) {
        Log.d(TAG, "ApplicationEmulationEngine() launched as mainThread = [" + mainThread + "], with: vst = [" + vst + "], callback = [" + callback + "], contentRoot = [" + contentRoot + "]");
        // we know that callback extends activity, lets try to emulate the launch of one

        try {
            main = Thread.currentThread();

            // cannot start activity in a thread that has not called Looper.prepare()
            Looper.prepare();
            Log.i(TAG, "ApplicationEmulationEngine: prepared looper");

            // Looper.loop() blocks
//        Looper.loop();

            ReflectionUtils ref = new ReflectionUtils();

            // both Fragments and Activities require an Activity to be attached
            //
            //      Caused by: java.lang.IllegalStateException: No activity
            //        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1626)
            //        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
            //        at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2999)
            //        at android.app.FragmentController.dispatchCreate(FragmentController.java:173)
            //        at android.app.Activity.onCreate(Activity.java:1478)
            //
            // with Fragment we get
            //     Your activity is not yet attached to the Application instance.
            //     You can't request ViewModel before onCreate call.

            Object instance = callback.getDeclaredConstructors()[0].newInstance();
            Method m = callback.getSuperclass().getSuperclass().getDeclaredMethod("attachBaseContext", Context.class);
            m.setAccessible(true);
            m.invoke(instance, vst.applicationContext);
            m.setAccessible(false);
            Field f = callback.getSuperclass().getDeclaredField("mActivityInfo");
            f.setAccessible(true);
            ComponentName componentName = ComponentName.createRelative(vst.applicationContext, callback.getName());
            ActivityInfo activityInfo = vst.mPackageManager.getActivityInfo(componentName, 0);
            Log.d(TAG, "vst.mApplicationInfo = [" + activityInfo + "]");
            f.set(instance, activityInfo);
            f.setAccessible(false);
            if (instance != null) {
                Method onCreate = ref.fetchMethod(instance, "onCreate", Bundle.class);
                // Caused by: java.lang.IllegalStateException: No activity
                ref.invokeMethod(onCreate, instance, "onCreate", (Bundle) null);
            }
        } catch (Exception exception) {
            Log.e(TAG, "ApplicationEmulationEngine: caught unknown exception", exception);
        }
        if (Looper.getMainLooper().isCurrentThread()) {
            Log.i(TAG, "ApplicationEmulationEngine: terminating main looper");
            Looper.getMainLooper().quitSafely();
        }
        if (Looper.myLooper() != null) {
            if (Looper.myLooper().isCurrentThread()) {
                Log.i(TAG, "ApplicationEmulationEngine: terminating my looper");
                Looper.myLooper().quitSafely();
            }
        }
    }

    public ApplicationEmulationEngine(VST vst, Class callback, ViewGroup contentRoot) {
        // we know that we MIGHT be executing in a new thread
        // execute our self in a new thread of execution to be 100% sure
        Log.d(TAG, "ApplicationEmulationEngine: restarting myself in a new thread");
        new Thread(
                () -> new ApplicationEmulationEngine(true, vst, callback, contentRoot)
        ).start();
    }
}
```

### Robolectric & Android Version
Android 10

### Link to a public git repo demonstrating the problem:

**Comment by hoisie** [comment]
Please check out http://robolectric.org/writing-a-test/
