### ISSUE TITLE
java.lang.IllegalArgumentException: File C:\Users\TLP 67\AppData\Local\Temp\robolectric-Method/database.db contains a path separator

### ISSUE THREAD

**Issue by Prashantgupta6877** [robolectric/robolectric#6053]
**Description**
When I run the unit test then I got below error,

```
java.lang.IllegalArgumentException: File C:\Users\TLP 67\AppData\Local\Temp\robolectric-Method/database.db contains a path separator
	at android.app.ContextImpl.makeFilename(ContextImpl.java:2366)
	at android.app.ContextImpl.validateFilePath(ContextImpl.java:2350)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1137)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.j256.ormlite.android.AndroidConnectionSource.getReadWriteConnection(AndroidConnectionSource.java:68)
	at com.j256.ormlite.android.AndroidConnectionSource.getReadOnlyConnection(AndroidConnectionSource.java:55)
	at com.j256.ormlite.dao.BaseDaoImpl.countOf(BaseDaoImpl.java:794)
	at com.demo.msource.service.DbService.initDatabaseHack(DbService.java:200)
	at com.demo.msource.BaseMainApp.onCreate(BaseMainApp.kt:67)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:288)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:288)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Steps to Reproduce**
When we run the test cases on a windows machine then it shows the above error.

**Robolectric & Android Version**
Robolectric Version : 4.4.
Android Version: 29.

**Comment by hoisie** [comment]
Can you please follow https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues and provide a sample app that demonstrates the issue?
