### ISSUE TITLE
TypeNotPresentException: Type org.robolectric.RobolectricTestRunner not present

### ISSUE THREAD

**Issue by victorkifer** [robolectric/robolectric#6060]
### Description

When running Robolectric test for the first time on the new computer (in terms there was no other project using Robolectric previously) from Android Studio, the exception like below is thrown.

```
java.lang.TypeNotPresentException: Type org.robolectric.RobolectricTestRunner not present

	at sun.reflect.annotation.TypeNotPresentExceptionProxy.generateException(TypeNotPresentExceptionProxy.java:46)
	at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84)
	at com.sun.proxy.$Proxy2.value(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: org.robolectric.RobolectricTestRunner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:439)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:420)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:349)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:219)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	... 3 more
```

### Robolectric & Android Version

Robolectric 4.4
SDK=O_MR1
Android Studio 4.1.1
Android Gradle Plugin 4.1.0
Compile/Target SDK 29

**Comment by hoisie** [comment]
Is Robolectric in your build.gradle? Seems like a classpath issue.

**Comment by victorkifer** [comment]
Yes, and gradle sync finished.

I'm not sure what exactly helped, but after cleaning/building the project/cleaning caches/restarting studio/switching robolectric version it eventually started robolectric `android-all` downloads and ran the tests successfully.

**Comment by victorkifer** [comment]
I can confirm though that this issue occurred on computers of my colleagues (also no robolectric used previously) as well after they pulled the code.

**Comment by hoisie** [comment]
Without a repro project I am not really sure how to help with this issue. From the description it seems like more of an Android Studio issue. Does the test run in the gradle command line?

**Comment by utzcoz** [comment]
@victorkifer if you can reproduce this problem currently, you can attach your reproduce project to here, and reopen this issue for continuous discussion.
