### ISSUE TITLE
Unmarschall parcelable is always successfull

### ISSUE THREAD

**Issue by charbgr** [robolectric/robolectric#6072]
### Description

I ran into an issue where Robolectric + ActivityScenario always unmarshall a Parcelable correctly despite the location of Creator.

### Steps to Reproduce

Parcelable:
```kotlin
data class Foo(val x: String) : Parcelable {
  constructor(parcel: Parcel) : this(parcel.readString()!!)
  override fun writeToParcel(parcel: Parcel, flags: Int) {
    parcel.writeString(x)
  }
  override fun describeContents(): Int = 0
  companion object {
    val CREATOR = object : Creator<Foo> {
      override fun createFromParcel(parcel: Parcel): Foo = Foo(parcel)
      override fun newArray(size: Int): Array<Foo?> = arrayOfNulls(size)
    }
  }
}
```

Test:
```kotlin

@Test 
fun test_too_unmarshall() {
    val passedFoo = Foo("a")
    val intent = Intent(context, TestFooActivity::class.java)
    intent.putExtra("foo", passedFoo)
    
    val activityScenario = launchActivity<A>(intent)
    activityScenario.moveToState(Lifecycle.State.STARTED)
    activityScenario.onActivity { activity ->
      val parceledFoo = activity.intent.getParcelableExtra<Foo>("foo")

      assertThat(parceledFoo).isNotNull()
      assertThat(parceledFoo).isEqualTo(passedFoo)
    }
    activityScenario.close()
}
```

On a real device navigating to TestFooActivity throws an exception of 

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{xx/xx.TestFooActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class Foo

### Robolectric & Android Version

Robolectric: 4.4
Android: P (28)

### Link to a public git repo demonstrating the problem:

None

**Comment by hoisie** [comment]
Seems like the issue is somewhere here: https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcel.java#L77. Can you set a breakpoint there and determine what is causing the creator field to be found?

**Comment by charbgr** [comment]
@hoisie seems that it does not go through ShadowParcel. Should I do pass a shadow of parcelable or something?

**Comment by hoisie** [comment]
A more primitive test seems to work as expected:

```kt
  @Test
  fun test_to_unmarshal() {
    val parcel = Parcel.obtain()
    parcel.writeParcelable(Foo("a"), 0)
    parcel.setDataPosition(0)
    parcel.readParcelable<Foo>(Foo.javaClass.classLoader)
  }
```


Results in:
```
Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.google.android.simple.Foo
android.os.BadParcelableException: 
	at org.robolectric.shadows.ShadowParcel.readParcelableCreator(ShadowParcel.java:128)
	at android.os.Parcel.readParcelableCreator(Parcel.java)
	at android.os.Parcel.readParcelable(Parcel.java:2964)
	at com.google.android.simple.ParcelTest.test_to_unmarshal(ParcelTest.kt:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:57)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:59)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Maybe something higher level is swallowing the exception?

**Comment by hoisie** [comment]
@charbgr you do not need to explicitly interact with the `protected` methods on shadows, they are called implicitly by Robolectric instead of the real Android methods.

**Comment by charbgr** [comment]
I will try to reproduce in a sample project!

**Comment by hoisie** [comment]
Another possibility is that on real Android, starting an Activity goes through ActivityManagerService, which may require passing the intent through binder calls. In Robolectric, maybe the intent is never serialized / deserialized when starting an activity?

**Comment by charbgr** [comment]
@hoisie that seems more reasonable to me!

**Comment by lsuski** [comment]
I found another problem with `ShadowParcel`. Starting from Android T `Parcel.getParcelable` method requries `Class<T>` parameter. In the body of the method there is:
```
 if (creator != null) {
            if (clazz != null) {
                Class<?> parcelableClass = creator.getClass().getEnclosingClass();
                if (!clazz.isAssignableFrom(parcelableClass)) {
                    throw new BadTypeParcelableException("Parcelable creator " + name + " is not "
                            + "a subclass of required class " + clazz.getName()
                            + " provided in the parameter");
                }
            }
            return (Parcelable.Creator<T>) creator;
        }
```
if CREATOR class is not anonymous and placed inside parcelable class then it crashes with NPE. Robolectric `ShadowParcel` does not have such logic

**Comment by utzcoz** [comment]
> if CREATOR class is not anonymous and placed inside parcelable class then it crashes with NPE. Robolectric ShadowParcel does not have such logic

@lsuski Could you file a new issue for this problem?

**Comment by lsuski** [comment]
https://github.com/robolectric/robolectric/issues/7802
