### ISSUE TITLE
Error initializing FragmentScenario

### ISSUE THREAD

**Issue by guillaume-tgl** [robolectric/robolectric#6109]
### Description

I've just upgraded to Robolectric 4.4, AndroidX Test libraries to 1.3.0 and Fragment testing to 1.3.0-beta02, and I'm starting seeing errors in all of my tests which use FragmentScenario: 

``` 
java.lang.NoClassDefFoundError: Could not initialize class androidx.fragment.app.testing.FragmentScenario
```

Here is a more advanced stack trace:
```
Caused by: java.lang.ExceptionInInitializerError
	at com.myapp.MyTest(MyTest.kt:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:166)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at androidx.fragment.app.testing.FragmentScenario.<clinit>(FragmentScenario.kt)
	... 16 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:163)
	... 18 more
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.fragment.app.testing.FragmentScenario$Companion
	at androidx.fragment.app.testing.FragmentScenario$Companion.<init>(FragmentScenario.kt)
	at androidx.fragment.app.testing.FragmentScenario.__staticInitializer__(FragmentScenario.kt)
	... 24 more
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.DefaultConstructorMarker from class androidx.fragment.app.testing.FragmentScenario$Companion
	... 26 more
```

### Steps to Reproduce

Simply call `FragmentScenario.launchInContainer` from a java or Kotlin test.

### Robolectric & Android Version

org.robolectric:robolectric:4.4
androidx.fragment:fragment-testing:1.3.0-beta02

**Comment by hoisie** [comment]
Is the code using an inline class? I think this type of thing has come up in other issues (https://github.com/robolectric/robolectric/issues/5942).

**Comment by hoisie** [comment]
This issue as well seems related: https://github.com/robolectric/robolectric/issues/4340

**Comment by hoisie** [comment]
Looks like FragmentScenario has been converted to Kotlin a couple months back.
https://cs.android.com/androidx/platform/frameworks/support/+/11ed4f0320671e0f0a1de751ff6e8111497b60b2

The fix should be something like:
https://github.com/robolectric/robolectric/issues/4340#issuecomment-709634338

**Comment by guillaume-tgl** [comment]
Thanks, I was able to fix my tests using the following runner:

```

public class GSTestRunner extends RobolectricTestRunner {

    public GSTestRunner(Class<?> testClass) throws InitializationError {
        super(testClass);
    }

    public GSTestRunner(Class<?> testClass, Injector injector) throws InitializationError {
        super(testClass, injector);
    }

    @Nonnull
    @Override
    protected InstrumentationConfiguration createClassLoaderConfig(FrameworkMethod method) {
        InstrumentationConfiguration config = super.createClassLoaderConfig(method);
        InstrumentationConfiguration.Builder builder = new InstrumentationConfiguration.Builder(config);

        builder.doNotInstrumentPackage("androidx.fragment");

        return builder.build();
    }
}
```

If I use this runner for all my test classes, it works perfectly fine. However, if I use this runner only in test classes where I use the `androidx.fragment` and use the default `RobolectricTestRunner` in other classes, I get the same error back in tests where I use `FragmentScenario`. I don't understand...

Anyway, thanks for your help.
Would you like a PR with this change?

**Comment by hoisie** [comment]
@guillaume-tgl coincidentally we just ran into this issue in Google as well so I put a PR
