### ISSUE TITLE
Unit Test are not getting Executed for Android  'R' i.e. API-30 : java.lang.IllegalArgumentException: API level 30 is not available

### ISSUE THREAD

**Issue by puneet-kr-sh** [robolectric/robolectric#6125]
### Description
When I try to execute my unit tests for API-30, These tests gets failed. 

### Steps to Reproduce
Set Test Config as follows :

> @RunWith(AndroidJUnit4::class)
> @LooperMode(LooperMode.Mode.PAUSED)
> @Config(manifest = Config.NONE, sdk = [Build.VERSION_CODES.R])

### Robolectric & Android Version

- robolectric : 4.4
- jdk-11.0.9.jdk
- Android Studio 4.1.1
- compileSdkVersion 30
- minSdkVersion 21
- targetSdkVersion 30
- testOptions {
        unitTests.returnDefaultValues = true
        unitTests.includeAndroidResources = true
    }

### Error  for each Test
java.lang.IllegalArgumentException: API level 30 is not available

	at org.robolectric.plugins.UnknownSdk.verifySupportedSdk(UnknownSdk.java:45)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:278)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:64)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:226)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:99)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:154)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

**Comment by hoisie** [comment]
You will need to use 4.5-alpha-3 to run tests on SDK 30. 4.4 only supports
up to SDK 29.

**Comment by puneet-kr-sh** [comment]
Thanks, using '4.5-alpha-3' has worked for me.
