### ISSUE TITLE
java.io.FileNotFoundException(The requested operation cannot be performed on a file with a user-mapped section open)

### ISSUE THREAD

**Issue by Prashantgupta6877** [robolectric/robolectric#6179]
### Description
When the path to the current Windows user's profile folder contains a space (e.g. C:\Users\TLP 67), trying to run Robolectric tests will fail:

java.lang.RuntimeException: java.io.FileNotFoundException: java.io.FileNotFoundException: C:\Users\TLP 67\AppData\Local\Temp\robolectric-Method_appl12315957548976809745\external-files\database.db-shm (The requested operation cannot be performed on a file with a user-mapped section open)
It appears that the path is being inappropriately URL-encoded, replacing spaces with %20. We have worked around the problem by creating a symbolic link from e.g. TLP%2067 to TLP 67, but this is obviously not ideal.

### Steps to Reproduce
Log into Windows as a user whose profile folder name contains a space
Run any Robolectric test suite in Android Studio

### Robolectric & Android Version
Robolectric 4.1, Android API level 29, JUnit 4.13, Windows 10

### Link to a public git repo demonstrating the problem:
The problem does not appear to be related to any specific Robolectric-based test suite.

**Comment by utzcoz** [comment]
From the failed information, the name of Windows user has empty space, and it can't process it correctly. Maybe you should replace empty space with %20 of path to make it URL-encoded compatibility before using it.

**Comment by Prashantgupta6877** [comment]
Hello,
I have replaced the empty space with "%20" but still, it shows the same error.

**Comment by utzcoz** [comment]
https://github.com/robolectric/robolectric/issues/4589
Looks like the 4.2.1 has fixed this problem.

**Comment by Prashantgupta6877** [comment]
I had tried with the 4.2.1 version as well but still it showing this issue.

**Comment by utzcoz** [comment]
> I had tried with the 4.2.1 version as well but still it showing this issue.

Could you help to paste full stack trace?

**Comment by Prashantgupta6877** [comment]
java.io.FileNotFoundException: C:\Users\TLP-67\AppData\Local\Temp\robolectric-Method_test5834861450422359639\external-files\database.db (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:276)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:220)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:170)
	at com.msource.util.IOUtil.copyInputStreamToFile(IOUtil.java:94)
	at com.TestkitJunit$PlatformNavigation.initializeDB(TestkitJunit.java:1167)
	at com.TestkitJunit$PlatformNavigation.openStudy(TestkitJunit.java:1143)
	at com.mons.testkit.workers.AbstractWorker.openStudy(AbstractWorker.java:114)
	at com.mons.testkit.workers.AutoFillWorker.test_autoFill_triggered_only_where_data_is_entered_for_subject_navigation2(AutoFillWorker.java:995)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.mons.testkit.WorkerConsumer.processValidTest(WorkerConsumer.java:162)
	at com.mons.testkit.WorkerConsumer.consume(WorkerConsumer.java:123)
	at com.mons.testkit.TestKitFacade.runAutoFillTests(TestKitFacade.java:149)
	at com.TestkitJunit.testAutoFill(TestkitJunit.java:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by Prashantgupta6877** [comment]
I had removed the white space between the username in the path and tried but still, it shows the same error.
Eg. previously my windows profile username is "TLS 67" but then I have changed to "TLS-67" and "pgupta" but it shows the same error.

**Comment by hoisie** [comment]
I am not seeing any Android code in that stack trace. Looks like a bug in
TestkitJunit.

**Comment by Prashantgupta6877** [comment]
I have tried to run same code on Mac machine and it's working as expected. Only facing issue when we run code on windows machine so, I guess it's not Android code problem.

If possible, can we have a call to discuss it in brief?

**Comment by hoisie** [comment]
I don't think a call is necessary, this seems like straightforward bug in your project's test code (TestkitJunit). TestkitJunit encodes database path files in a way that breaks on Windows. I am not sure what we can do on the Robolectric side.
