### ISSUE TITLE
Tests are failing on AGP 7.0.0-alpha09 

### ISSUE THREAD

**Issue by aconda-mercari** [robolectric/robolectric#6277]
### Description
Tests are failing on AGP 7.0.0-alpha09 

```
java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: /home/circleci/code/domain_base/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ (at Binary XML file line #9): <instrumentation> does not specify targetPackage
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:69)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:326)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:296)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:294)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:195)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:269)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: android.content.pm.PackageParser$PackageParserException: /home/circleci/code/domain_base/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ (at Binary XML file line #9): <instrumentation> does not specify targetPackage
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1340)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1299)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1022)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1042)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
	... 13 more
```

### Steps to Reproduce
Update AGP to 7.0.0-alpha09

### Robolectric & Android Version
Robolectric=4.5.1
Android Gradle Plugin=7.0.0-alpha09

**Comment by utzcoz** [comment]
It looks like your `AndroidManifest.xml` needs set `targetPackage` for `instrumentation` tag.

**Comment by hoisie** [comment]
I would either delete the `<instrumentation>` tag (Robolectric does need it) or ensure it is properly set up.

**Comment by giljulio** [comment]
> I would either delete the `<instrumentation>` tag (Robolectric does need it) or ensure it is properly set up.

@hoisie I'm getting the same issue with `7.0.0-alpha09` but no error with `7.0.0-alpha08`. No `<instrumentation>` tags in the project neither.

**Comment by ParaskP7** [comment]
👋 @hoisie 

> @hoisie I'm getting the same issue with 7.0.0-alpha09 but no error with 7.0.0-alpha08. No <instrumentation> tags in the project neither.

Same fore me ([playground repo](https://github.com/ParaskP7/sample-code-movies)).

**Comment by jossiwolf** [comment]
Same here! Here's an issue in the AGP component in the issuetracker: https://issuetracker.google.com/issues/182468430

**Comment by hoisie** [comment]
Reopened, seems a like a bunch of folks are having this issue. Looks like it's primarily an issue with AGP. I can try getting more visibility into this issue or helping find the AGP change that caused it. We may be able to work around it in Robolectric because Robolectric fakes Instrumentation ( it's mainly done for some AndroidXTest interop ).

**Comment by hoisie** [comment]
I believe I was able to locate the AGP change that caused this, and will try to follow up next week. From a cursory glance it seems like a quick fix.

**Comment by hoisie** [comment]
Looks like there has been some activity on  https://issuetracker.google.com/issues/182468430. My guess is that it will be fixed relatively soon.

**Comment by apkelly** [comment]
Its still broken on 7.0.0-alpha10, fingers crossed for 7.0.0-alpha11 soon.

**Comment by jschmid** [comment]
FYI it's fixed with 7.0.0-alpha12
