### ISSUE TITLE
Unable to run tests with 4.5.1

### ISSUE THREAD

**Issue by elson-dsouza** [robolectric/robolectric#6317]
### Description
I upgraded to Robolectric 4.5.1 from 4.4 and now see an error when running tests on a Java 8 environment. The stack trace is

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: couldn't load org.robolectric.android.internal.AndroidTestEnvironment

	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:43)
	at org.robolectric.internal.AndroidSandbox.<init>(AndroidSandbox.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:250)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:232)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
	at org.robolectric.util.inject.Injector.access$700(Injector.java:96)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:564)
	at org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:547)
	at com.sun.proxy.$Proxy18.build(Unknown Source)
	at org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:57)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:279)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:64)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:240)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: couldn't load org.robolectric.android.internal.AndroidTestEnvironment
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:142)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:115)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:115)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at org.robolectric.internal.bytecode.Sandbox.bootstrappedClass(Sandbox.java:41)
	... 34 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70)
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57)
	at org.robolectric.internal.bytecode.ClassDetails$AnnotationVisitor.<init>(ClassDetails.java:52)
	at org.robolectric.internal.bytecode.ClassDetails.hasAnnotation(ClassDetails.java:40)
	at org.robolectric.internal.bytecode.InstrumentationConfiguration.shouldInstrument(InstrumentationConfiguration.java:91)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:134)
	... 39 more
```
On debugging found the root cause to be inside org.objectweb.asm where api is 589824 (ASM.9) causing this issue

### Steps to Reproduce
Write any basic test case and run

### Robolectric & Android Version
Robolectric 4.5.1
Android O

**Comment by elson-dsouza** [comment]
Figured out that `org.ow2.asm:asm` was forced to 7 causing the issue. Not a Robolectric issue
