### ISSUE TITLE
Requires newer sdk version #30 (current version is #28)

### ISSUE THREAD

**Issue by danilobertelli** [robolectric/robolectric#6339]
### Description
When trying to use Robolectric in my project, I got the following issue:

java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: C:\Dev\Danilo\MyApp\libraries\deviceprovider\build\intermediates\apk_for_local_test\debugUnitTest\apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #30 (current version is #28)

at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:69)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:326)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:296)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:294)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:195)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.content.pm.PackageParser$PackageParserException: C:\Dev\Danilo\MyApp\libraries\deviceprovider\build\intermediates\apk_for_local_test\debugUnitTest\apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #30 (current version is #28)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1340)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1299)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1022)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1042)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
	... 13 more

### Steps to Reproduce
Set project target and min SDK to 30.

Write the test:
`
package com.myapp.deviceprovider

import android.os.Build
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [Build.VERSION_CODES.P])
class MyProviderTest {

    @Before
    fun setup() {
        println("setup")
    }

    @Test
    fun verify_if_works() {
        println("test 1")
    }
}
`

### Robolectric & Android Version
Robolectric and libs version:
testImplementation 'junit:junit:4.13.2'
testImplementation 'androidx.test:core:1.3.0'
testImplementation 'androidx.test.ext:junit-ktx:1.1.2'
testImplementation 'org.robolectric:robolectric:4.4'

compileSDK, targetSDK and minSDK set to 30.

**Comment by adielwesley** [comment]
Any update on this? @danilobertelli

**Comment by danilobertelli** [comment]
Not from my side.. I had to skip some testing for now.

**Comment by utzcoz** [comment]
@danilobertelli If you set your `minSDK` to 30, your tests can only run on API 30 and above. It's the same as you can't install and run one app with `minSDK` to 30  on a device with platform sdk less than 30. The checking is here: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PackageParser.java;l=2627?q=PackageParser.java&ss=android.

**Comment by hoisie** [comment]
If you want to use SDK 30 in tests you need to update to Robolectric 4.5.

Also is there a specific reason why your manifest is setting `android:minSdkVersion="30"`? That seems rather constraining.

**Comment by danilobertelli** [comment]
> @danilobertelli If you set your `minSDK` to 30, your tests can only run on API 30 and above. It's the same as you can't install and run one app with `minSDK` to 30 on a device with platform sdk less than 30. The checking is here: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PackageParser.java;l=2627?q=PackageParser.java&ss=android.

Yes, I was doing that, running on API 30, there was an incompatibility with Robolectric, but it seems to be fixed on version 4.5.

> If you want to use SDK 30 in tests you need to update to Robolectric 4.5.
> 
> Also is there a specific reason why your manifest is setting `android:minSdkVersion="30"`? That seems rather constraining.

Thanks @hoisie I will check on version 4.5 and the reason on fixing minSDK=30 is totally on the business case of the project.

**Comment by adielwesley** [comment]
@hoisie I tried to run Robolectric 4.5 with SDK 30 but the error persists.

**Error**

java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: .../myProject/libraries/device/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #30 (current version is #28)

	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:69)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:326)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:296)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:294)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:195)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:269)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: android.content.pm.PackageParser$PackageParserException: /home/adielsilva/gerrit/AIServices/libraries/device/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ (at Binary XML file line #5): Requires newer sdk version #30 (current version is #28)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1340)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1299)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1022)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1042)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
	... 13 more

**Robolectric & Android Version**

Roboelectric 4.5.1
Android Studio 4.1.2
'compileSdk' : 30,
'minSdk' : 30,
'targetSdk' : 30
testImplementation 'junit:junit:4.12'
testImplementation 'androidx.test:core:1.1.0'
testImplementation 'androidx.test.ext:junit:1.1.1'

**Comment by utzcoz** [comment]
@adielwesley could you change your min SDK to  30 in your test config ?

**Comment by hoisie** [comment]
Also, without a sample app that captures the problem there's likely not much we can really do:
https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues

**Comment by androidparth90** [comment]
Hello Guys,
What worked for me was to tell Roboelectric that i was using the API level 30 
So i modified this line as follows:

@config(sdk = [Build.VERSION_CODES.R])

There after it worked for me.
My config was as follows:

Roboelectric 4.5.1
Android Studio 4.1.2
'compileSdk' : 30,
'minSdk' : 30,
'targetSdk' : 30
testImplementation 'junit:junit:4.12'
testImplementation 'androidx.test:core:1.1.0'
testImplementation 'androidx.test.ext:junit:1.1.1'


Also one needs to add the below mentioned dependency in the build.gradle file 

dependencies {
    val fragment_version = "1.3.4"
    debugImplementation("androidx.fragment:fragment-testing:$fragment_version")
}

Reference link: https://developer.android.com/guide/fragments/test#kts

**Comment by fejd** [comment]
I had the same issue and in my case it was caused by another module declaring sdk=28 in its robolectric.properties file, which caused the runtimeSdk to be 28 and compileSdk to be 30. I noticed that while debugging in RobolectricTestRunner.getConfiguration and HierarchicalConfigurationStrategy. Updating the robolectric.properties sdk value to 30 resolved it.

**Comment by helenchen-okta** [comment]
You can/should set `sdk` property in `robolectric.properties` equal to your app's min sdk level. This will apply for all your tests, and if specific tests needs a different config then use the `@config` annotation.

**Comment by utzcoz** [comment]
https://github.com/robolectric/robolectric/issues/6339#issuecomment-854404040, https://github.com/robolectric/robolectric/issues/6339#issuecomment-871252929 and https://github.com/robolectric/robolectric/issues/6339#issuecomment-898664875 provide some insights and workaround. If you encountered similar problem, please read those comments firstly. If they can't help to fix your problem, feel free to reopen this issue or file a new issue with your sample app that can reproduce your problem.
