### ISSUE TITLE
Running service from AsyncTask$doInBackground doesn't work with Robolectric 4.5.1

### ISSUE THREAD

**Issue by ShivamPokhriyal** [robolectric/robolectric#6359]
### Description
I'm using `Robolectric.buildService` to create a service from inside of `AsyncTask#doInBackground` but it fails with `UnsupportedOperationException`
```
Caused by: java.lang.UnsupportedOperationException
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:202)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
	at org.robolectric.android.controller.ServiceController.create(ServiceController.java:59)
```

### Steps to Reproduce

It's pretty simple to reproduce. When you try to start a service from `doInBackground` it crashes. 
I used the [MyService](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/android/controller/ServiceControllerTest.java#L113) class from `ServiceControllerTest`
```
    private static MyService startService() {
        Intent startIntent =
                new Intent(RuntimeEnvironment.application, MyService.class);
        ServiceController<MyService> serviceController =
                Robolectric.buildService(MyService.class, startIntent);
        serviceController
                .create()
                .startCommand(3, 4);
        return serviceController.get();
    }

    @Test
    public void testWithoutAsync() {
        startService();
        ShadowLooper.idleMainLooper();
    }

    @Test
    public void testWithAsync() {
        Async async = new Async();
        try {
            async.execute().get();
        } catch (ExecutionException e) {
            e.printStackTrace();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    class Async extends AsyncTask<Void, Void, Void> {
        @Override
        protected Void doInBackground(Void... voids) {
            startService();
            return null;
        }
    }
```
And here `testWithoutAsync` test passes but `testWithAsync` method fails with exception
```
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at android.os.AsyncTask.get(AsyncTask.java:483)
	at PACKAGE_NAME.testWithAsync
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:202)
	at org.robolectric.android.controller.ComponentController.invokeWhilePaused(ComponentController.java:50)
	at org.robolectric.android.controller.ServiceController.create(ServiceController.java:59)
	at PACKAGE_NAME.startService
	at PACKAGE_NAME.access$000
	at PACKAGE_NAME$Async.doInBackground
	at PACKAGE_NAME$Async.doInBackground
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	... 3 more

``` 

### Robolectric & Android Version
Robolectric version 4.5.1

**Comment by hoisie** [comment]
cc @brettchabot

**Comment by hoisie** [comment]
Maybe we need to update the controller methods to only use the `runPaused` methods if it is running with legacy looper?

**Comment by ShivamPokhriyal** [comment]
@hoisie @brettchabot Any updates on this?

**Comment by hoisie** [comment]
@ShivamPokhriyal this is not currently supported with paused looper
