### ISSUE TITLE
Robolectric 4.6-alpha-1 Injector attempts to load now-deleted InstrumentationProvider class

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#6507]
We have no usages of `InstrumentationProvider` in our codebase, but robolectric attempts to load it in some classes for unknown reasons

```
java.lang.NoClassDefFoundError: androidx/test/platform/app/InstrumentationProvider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2699)
	at java.lang.Class.getConstructors(Class.java:1679)
	at org.robolectric.util.inject.Injector.findConstructor(Injector.java:262)
	at org.robolectric.util.inject.Injector.inject(Injector.java:243)
	at org.robolectric.util.inject.Injector.lambda$new$0(Injector.java:126)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:202)
	at org.robolectric.internal.AndroidSandbox.lambda$new$0(AndroidSandbox.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: androidx.test.platform.app.InstrumentationProvider
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:182)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:140)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$loadClass$0(SandboxClassLoader.java:126)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:126)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
```

**Comment by dmeng** [comment]
@ZacSweers Out of curiosity, is your codebase using Android X Test 1.4.0-beta01? 4.6-alpha-1 isn't compatible with that release specifically because of InstrumentationProvider getting removed.

We removed InstrumentationProvider from Robolectric in commit 57e0191f8b02c2a697b0aaa5ba41524718187473, so 4.6-alpha-2 should work with Android X Test 1.4.0-beta01 once it's out.

**Comment by ZacSweers** [comment]
Ahh that'll do it, thanks
