### ISSUE TITLE
System services not available to Activities before onCreate()

### ISSUE THREAD

**Issue by mattelacchiato** [robolectric/robolectric#651]
Hi,

I have a ListActivity and in its onCreate()-method I want to create a new ListAdapter:

``` java
    adapter = new ExpenditureListAdapter(getLayoutInflater(), expenditures);
```

When I run my tests with Robolectric 2.1.1, it throws an exception:

```
    java.lang.IllegalStateException: System services not available to Activities before onCreate()
```

Full stacktrace is pasted here: https://gist.github.com/mattelacchiato/577526a3390dd71eeb13 

Okay, obviously Robolectric don't like it this way. Am I using it the wrong way? Or shouldn't it be possible to retrieve the LayoutInflater in onCreate()?

I'm using Robolectric 2.1.1

**Comment by BinapaniBeria** [comment]
TEST CODE:

private ShadowAsyncTask shadowAsyncTaskMonitorMobiControl;
private StartApplication.MonitorMobiControl monitorMobiControl;

@Before
    public void setUp() throws Exception {
        monitorMobiControl = new StartApplication().new MonitorMobiControl();
        shadowAsyncTaskMonitorMobiControl = shadowOf(monitorMobiControl);
   
    }
@Test
    public void checkOutputOfFunctionIsMobiControlRunningWhenItIsNotRunning() throws Exception {
        assertNotNull(monitorMobiControl.isMobiControlRunning());
//        assertFalse(monitorMobiControl.isMobiControlRunning());
    }

–––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
ERROR
---- IntelliJ IDEA coverage runner ---- 
sampling ...
include patterns:
com\.tesco\.monitoringapplication\..*
exclude patterns:
java.lang.IllegalStateException: System services not available to Activities before onCreate()

	at android.app.Activity.getSystemService(Activity.java:5915)
	at com.tesco.monitoringapplication.StartApplication$MonitorMobiControl.isMobiControlRunning(StartApplication.java:135)
	at com.tesco.monitoringapplication.StartApplicationUnitTest.checkOutputOfFunctionIsMobiControlRunningWhenItIsNotRunning(StartApplicationUnitTest.java:135)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:253)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
