### ISSUE TITLE
androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching

### ISSUE THREAD

**Issue by johnjeremih** [robolectric/robolectric#6576]
### Description
I'm getting this error, I thought it was the XML that wasn't set up correctly, but that is not the problem
### Steps to Reproduce
The way I reproduced the error was using Firebase Test Lab Robo testing. The crash occurred using the Samsung Phone Model SM-G935T API Level 26. I tried a Pixel and it worked fine

### Robolectric & Android Version
 API Level 26
### Link to a public git repo demonstrating the problem:
Here is the Stack trace
`Fatal Exception: androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (view.getClass().getName() matches: is "android.webkit.WebView" and view.getId() is <2131361871/com.programproductions.nativeandroid:id/activity_oauth_webview> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "androidx.coordinatorlayout.widget.CoordinatorLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "androidx.appcompat.widget.ContentFrameLayout" and view.getId() is <16908290/android:id/content> and is a child at 1th index of the matching parent: (view.getClass().getName() matches: is "androidx.appcompat.widget.FitWindowsLinearLayout" and view.getId() is <2131361845/com.programproductions.nativeandroid:id/action_bar_root> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "android.widget.FrameLayout" and view.getId() is <-1 (resource name not found)> and is a child at 1th index of the matching parent: (view.getClass().getName() matches: is "android.widget.LinearLayout" and view.getId() is <-1 (resource name not found)> and is a child at 0th index of the matching parent: (view.getClass().getName() matches: is "com.android.internal.policy.DecorView" and view.getId() is <-1 (resource name not found)> and view.getRootView() to equal view)))))))

View Hierarchy:
+>DecorView{id=-1, visibility=VISIBLE, width=1248, height=1008, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=WM.LayoutParams{(0,0)(wrapxwrap) gr=#11 sim=#20 ty=2 fl=#1820002 fmt=-3 wanim=0x10302fe needsMenuKey=2 colorMode=0 naviIconColor=0}, tag=null, root-is-layout-requested=false, has-input-connection=false, x=0.0, y=0.0, child-count=1} 
|
+->FrameLayout{id=-1, visibility=VISIBLE, width=1152, height=912, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enable<truncated: 10657 chars>
       at androidx.test.espresso.NoMatchingViewException$Builder.build(NoMatchingViewException.java:5)
       at androidx.test.espresso.base.ViewFinderImpl.getView(ViewFinderImpl.java:21)
       at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:4)
       at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
       at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by johnjeremih** [comment]
I figured it out. I had to use FrameLayout and then the Webview.

**Comment by Showy-raul** [comment]
@johnjeremih https://stackdev.space/questions/adjust-the-framelayout-to-fit-the-size-of-the-parent-container
