### ISSUE TITLE
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2

### ISSUE THREAD

**Issue by ck1703** [robolectric/robolectric#6595]
First test runs fine, remaining test fails due to java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2 

2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]     java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2-thread-4,5,SDK 28] []
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:497)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at com.excelfore.esync.agent.JoynextUpdateApp.isWorkScheduled(JoynextUpdateApp.java:246)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at com.excelfore.esync.agent.JoynextUpdateApp.onCreate(JoynextUpdateApp.java:227)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$0(AndroidTestEnvironment.java:288)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:288)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-07-06T13:17:28.941+0530 [DEBUG] [TestEventLogger]          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at java.lang.Thread.run(Thread.java:748)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]     Caused by: java.lang.IllegalStateException: Illegal connection pointer 1. Current pointers for thread Thread[pool-2-thread-4,5,SDK 28] []
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at org.robolectric.shadows.ShadowSQLiteConnection$Connections.getConnection(ShadowSQLiteConnection.java:369)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:419)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:90)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:562)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:549)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:460)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.beginTransaction(FrameworkSQLiteDatabase.java:69)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:354)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.model.WorkSpecDao_Impl.getWorkStatusPojoForTag(WorkSpecDao_Impl.java:1033)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.StatusRunnable$3.runInternal(StatusRunnable.java:130)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.StatusRunnable$3.runInternal(StatusRunnable.java:125)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.StatusRunnable.run(StatusRunnable.java:47)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]          ... 3 more
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger] 
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger] com.excelfore.esync.agent.test.PREH2_1147 > test STANDARD_OUT
2021-07-06T13:17:28.945+0530 [DEBUG] [TestEventLogger]     21-07-06 13:17:28.943 <SDK 28 Main Thread> D/eSync: workmanager state:false
2021-07-06T13:17:28.9

I closed database connection after unit test. still same issue is seen

**Comment by hoisie** [comment]
You are probably trying to reuse the same database object across multiple test. Is the database object static? After each test, robolectric deletes the temp directory used to store app files, so my guess is that that directory is being deleted but the database object is reused.

Anyway, without a sample app it is impossible to know exactly.

**Comment by ck1703** [comment]
Here is code:
    private MyDataBase database;
    database = Room.databaseBuilder(this, MyDataBase.class, MyDataBase.NAME)
                .addMigrations(MyDataBase.MIGRATION_1_2).build().setApp(this);
    executorService = Executors.newFixedThreadPool(Constants.GENERAL_WORK_THREADS);


I also tried closing the database after unit test. Still same issue is seen.

**Comment by hoisie** [comment]
Ah so there is a thread leak occurring and a background thread tries to perform a DB operation on a DB that has been deleted.

I would recommend shutting down the executor after each test, or using [MoreExecutors.directExecuto](https://guava.dev/releases/19.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#directExecutor()) in a test environment.

**Comment by ck1703** [comment]
I already tried shutting down executorservice after each unit test. First
test runs fine. 2nd test fails in this case.

Thanks & Regards,

Chethan Kumar

Senior Member of Technical Staff

Sirius / Excelfore India

**Comment by hoisie** [comment]
If you think this is an issue in Robolectric please post a sample app demonstrating the issue. Otherwise we cannot debug it. Closing for now, I will reopen when a sample app is available.

See:
https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues
