### ISSUE TITLE
java.lang.UnsupportedOperationException: Compression not supported.

### ISSUE THREAD

**Issue by bacecek** [robolectric/robolectric#6600]
### Description
After updating Robolectric from 4.5.1 to 4.6.1 version some tests has failed with similar stacktrace:
```
java.lang.UnsupportedOperationException: Compression not supported.

	at javax.imageio.ImageWriteParam.setCompressionMode(ImageWriteParam.java:914)
	at org.robolectric.shadows.ImageUtil.writeToStream(ImageUtil.java:134)
	at org.robolectric.shadows.ShadowBitmap.compress(ShadowBitmap.java:199)
	at android.graphics.Bitmap.compress(Bitmap.java)
	at com.example.BitmapWriterTest.testWriteToFile(BitmapWriterTest.java:30)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It seems to me that the reason is [this pull request](https://github.com/robolectric/robolectric/pull/6147). I took a simple test [from the comments in this pull request](https://github.com/robolectric/robolectric/pull/6147#issuecomment-758790298) and the test also fails. On 4.5.1 version all is ok.

Code of this test:
```
  @Test
  public void testWriteToFile() throws IOException {
    byte[] bitmapData = new byte[] {23, 100, 23, 52, 23, 18, 76, 43};
    Bitmap bitmap1 = BitmapFactory.decodeByteArray(bitmapData, 0, bitmapData.length);
    Path tempFile = Files.createTempFile("bitmap", null);
    FileOutputStream fileOutputStream = new FileOutputStream(tempFile.toFile());
    bitmap1.compress(Bitmap.CompressFormat.PNG, 100, fileOutputStream); // lossless compression
    fileOutputStream.close();
    Bitmap bitmap2 = BitmapFactory.decodeFile(tempFile.toAbsolutePath().toString());

    ByteBuffer buffer1 = ByteBuffer.allocate(bitmap1.getHeight() * bitmap1.getRowBytes());
    bitmap1.copyPixelsToBuffer(buffer1);

    ByteBuffer buffer2 = ByteBuffer.allocate(bitmap2.getHeight() * bitmap2.getRowBytes());
    bitmap2.copyPixelsToBuffer(buffer2);
    assertThat(buffer1.array()).isEqualTo(buffer2.array());
  }
```

**Comment by bacecek** [comment]
@hoisie @utzcoz Do you know anything about this?

**Comment by utzcoz** [comment]
It's weired, there is a similar test to test this occasion, https://github.com/robolectric/robolectric/blob/7697d1217c5eb0dee454004efe60ba219f398255/robolectric/src/test/java/org/robolectric/shadows/ShadowBitmapFactoryTest.java#L426-L431 , and it has run some months. It is stable. I copied your test method to 'ShadowBitmapFactoryTest', and it passed withour error. And I also copied your test method to a sample app, and it also passed with Robolectric. Could you provide a sample app that can reproduce this problem?

**Comment by bacecek** [comment]
It seems that the problem is in the Java version. PNGImageWriter does not support setCompressionMode in Java 8 but it supports in 11 version.
Given that the target sdk S and AGP 7.0 requires Java 11, this problem is not very relevant.
