### ISSUE TITLE
4.6.1 ExceptionInInitializerError when building database

### ISSUE THREAD

**Issue by edwnmrtnz** [robolectric/robolectric#6684]
### Description
4.6.1 ExceptionInInitializerError when building database

### Error
```
java.lang.ExceptionInInitializerError
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:171)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
	at com.edwnmrtnz.helper.EmployeeDao_Impl.save(EmployeeDao_Impl.java:45)
	at com.edwnmrtnz.helper.EmployeeRepository.save(EmployeeRepository.kt:6)
	at com.edwnmrtnz.helper.EmployeeRepoTest.save(EmployeeRepoTest.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:181)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.database.CursorWindow.<clinit>(CursorWindow.java)
	at android.database.AbstractWindowedCursor.$$robo$$android_database_AbstractWindowedCursor$clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java)
	at android.database.sqlite.SQLiteCursor.$$robo$$android_database_sqlite_SQLiteCursor$fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java)
	at android.database.sqlite.SQLiteCursor.$$robo$$android_database_sqlite_SQLiteCursor$getCount(SQLiteCursor.java:133)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java)
	at android.database.AbstractCursor.$$robo$$android_database_AbstractCursor$moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java)
	at android.database.AbstractCursor.$$robo$$android_database_AbstractCursor$moveToFirst(AbstractCursor.java:236)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:171)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getWritableDatabase(SQLiteOpenHelper.java:164)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
	at com.edwnmrtnz.helper.EmployeeDao_Impl.save(EmployeeDao_Impl.java:45)
	at com.edwnmrtnz.helper.EmployeeRepository.save(EmployeeRepository.kt:6)
	at com.edwnmrtnz.helper.EmployeeRepoTest.save(EmployeeRepoTest.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	... 43 more
Caused by: java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1019)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceValue(ShadowLegacyAssetManager.java:319)
	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
	at android.content.res.Resources.getValue(Resources.java:1009)
	at android.content.res.Resources.getInteger(Resources.java:820)
	at android.database.CursorWindow.__staticInitializer__(CursorWindow.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.database.CursorWindow.<clinit>(CursorWindow.java)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:171)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:622)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:399)
	at com.edwnmrtnz.helper.EmployeeDao_Impl.save(EmployeeDao_Impl.java:45)
	at com.edwnmrtnz.helper.EmployeeRepository.save(EmployeeRepository.kt:6)
	at com.edwnmrtnz.helper.EmployeeRepoTest.save(EmployeeRepoTest.kt:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 13 more


com.edwnmrtnz.helper.EmployeeRepoTest > save FAILED
    java.lang.ExceptionInInitializerError at EmployeeRepoTest.kt:30
        Caused by: java.lang.RuntimeException at EmployeeRepoTest.kt:30
            Caused by: java.lang.reflect.InvocationTargetException at EmployeeRepoTest.kt:30
                Caused by: java.lang.NullPointerException at EmployeeRepoTest.kt:30
```

### Steps to Reproduce

Use the following dependency:
```
    testImplementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.3.1' // had to import this to resolve livedata test issues
    testImplementation "org.robolectric:robolectric:4.6.1"
    testImplementation 'androidx.test:core:1.4.0'
    testImplementation 'junit:junit:4.13.2'

    testImplementation 'androidx.room:room-testing:2.3.0'
    implementation 'androidx.room:room-runtime:2.3.0'
    kapt 'androidx.room:room-compiler:2.3.0'
```
Here's sample classes

```
@Entity(tableName = "employees")
data class Employee (
    @PrimaryKey
    @ColumnInfo(name = "name")
    val name : String
)

@Dao
interface EmployeeDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun save(employee: Employee)

    @Query("SELECT * FROM employees")
    fun get() : List<Employee>
}

@Database(
    entities = [Employee::class],
    version = 1,
    exportSchema = false
)
abstract class EmployeeDatabase : RoomDatabase() {
    abstract fun dao() : EmployeeDao
}

class EmployeeRepository (private val dao : EmployeeDao) {
    fun save(employee: Employee) {
        dao.save(employee)
    }
    fun get(): List<Employee> {
        return dao.get()
    }
}

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [Config.OLDEST_SDK], manifest = Config.NONE)
class EmployeeRepoTest {
    private lateinit var sut : EmployeeRepository
    
    @Before
    fun setup() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        val database = Room.inMemoryDatabaseBuilder(context, EmployeeDatabase::class.java)
            .allowMainThreadQueries().build()
        sut = EmployeeRepository(database.dao())
    }

    @Test
    fun save() {
        val employee = Employee("John Doe")
        sut.save(employee)
        println(sut.get())
        Assert.assertEquals(1, sut.get().size)
    }
}

```

### Robolectric & Android Version
Robolectric: 4.6.1
Room: 2.2.5 or above

**Comment by edwnmrtnz** [comment]
Additional: I had to use 4.5.1 to make everything work for now.

**Comment by hoisie** [comment]
Can you try turning on binary resources?

**Comment by edwnmrtnz** [comment]
> Can you try turning on binary resources?

Adding this worked. TYSM!

```
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
```
