### ISSUE TITLE
NPE when a getString() is called inside a Fragment Class

### ISSUE THREAD

**Issue by madhurgupta10** [robolectric/robolectric#6702]
### Description
I am getting NPE when a `getString()` is called inside a Fragment Class

### Steps to Reproduce
```
Caused by: java.lang.IllegalStateException: Fragment SomeFragment{1df37025} (29efd1d0-77c1-4293-a0f6-b808c7559cf4)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:869)
	at androidx.fragment.app.Fragment.getString(Fragment.java:891)
```

```
    @Before
    fun setUp() {
        val activity = Robolectric.buildActivity(SomeActivity::class.java).create().get()
        fragment = SomeFragment()
        fragmentManager = activity.supportFragmentManager
        val fragmentTransaction: FragmentTransaction = fragmentManager.beginTransaction()
        fragmentTransaction.add(fragment, null)
        fragmentTransaction.commit()
    }
    
    @Test
    @Throws(Exception::class)
    fun someTest() {
        fragment.someMethod()
    }
```

```
    public void someMethod() {
        getString(R.string.some_res)
    }
```

### Robolectric & Android Version
`org.robolectric:robolectric:4.5.1`

**Comment by hoisie** [comment]
This needs to go through the whole activity lifecycle (e.g. `start` and `resume`). Call Robolectric.setupActivity instead of just buildActivity.

**Comment by madhurgupta10** [comment]
> SomeActivity needs to go through the whole activity lifecycle (e.g. `start` and `resume`). Call Robolectric.setupActivity instead of just buildActivity.

Hi, thanks for the answer, unfortunately, I am still getting the same issue after making the following change

```
val activity = Robolectric.setupActivity(SomeActivity::class.java)
```
