### ISSUE TITLE
Hilt support (feasible?)

### ISSUE THREAD

**Issue by ragunathjawahar** [robolectric/robolectric#6705]
### Description
I tried writing tests for a [Hilt](https://dagger.dev/hilt/) Android application, but the test crashes when the Hilt Gradle plugin is applied.

**Trace**
```
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" kotlin.UninitializedPropertyAccessException: lateinit property catchUpPreferences has not been initialized
	at io.sweers.catchup.app.CatchUpApplication.getCatchUpPreferences$catchup_debug(CatchUpApplication.kt:60)
	at io.sweers.catchup.app.CatchUpApplication$onCreate$2.invokeSuspend(CatchUpApplication.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" kotlin.UninitializedPropertyAccessException: lateinit property catchUpPreferences has not been initialized
	at io.sweers.catchup.app.CatchUpApplication.getCatchUpPreferences$catchup_debug(CatchUpApplication.kt:60)
	at io.sweers.catchup.app.CatchUpApplication$onCreate$2.invokeSuspend(CatchUpApplication.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

I tried changing the application to use the non-Gradle plugin format but the failure just keeps shifting to other Dagger modules.

**From**
```kotlin
@HiltAndroidApp
class CatchUpApplication : Application() {
  /…
}
```

**To**
```kotlin
@HiltAndroidApp(Application::class)
class CatchUpApplication : Hilt_CatchUpApplication() {
  /…
}
```

But the crash moves to a different module.
```
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" kotlin.UninitializedPropertyAccessException: lateinit property catchUpPreferences has not been initialized
	at io.sweers.catchup.app.CatchUpApplication.getCatchUpPreferences$catchup_debug(CatchUpApplication.kt:60)
	at io.sweers.catchup.app.CatchUpApplication$onCreate$2.invokeSuspend(CatchUpApplication.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" kotlin.UninitializedPropertyAccessException: lateinit property catchUpPreferences has not been initialized
	at io.sweers.catchup.app.CatchUpApplication.getCatchUpPreferences$catchup_debug(CatchUpApplication.kt:60)
	at io.sweers.catchup.app.CatchUpApplication$onCreate$2.invokeSuspend(CatchUpApplication.kt:97)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### Steps to Reproduce
Clone the repository following repository,
[https://github.com/ragunathjawahar/CatchUp](https://github.com/ragunathjawahar/CatchUp)

Checkout `rj/robolectric` and run the `CanaryRobolectricTest` class.

### Robolectric & Android Version
4.4 & API level 31

### Link to a public git repo demonstrating the problem:
[https://github.com/ragunathjawahar/CatchUp](https://github.com/ragunathjawahar/CatchUp)

**Comment by utzcoz** [comment]
Hi @ragunathjawahar the [hilt-testing section on developer.android.com](https://developer.android.com/training/dependency-injection/hilt-testing) shows how to test `Hilt` with `Robolectric`. What about trying it?

**Comment by hoisie** [comment]
Please follow all directions here: https://developer.android.com/training/dependency-injection/hilt-testing#robolectric-tests

You probably need to use the special codegen'd Hilt application, e.g. `@Config(application = SomeCodeGenApplication::class`. This application has special logic that initializes the object graph when the application is created.

Closing this because this is not a Robolectric issue/bug, it's a Hilt/Gradle/CatchUp issue.

**Comment by ragunathjawahar** [comment]
Thank you @utzcoz and @hoisie for the info.
