### ISSUE TITLE
BluetoothAdapter.getProfileProxy throws IllegalArgumentException when running as SDK 18

### ISSUE THREAD

**Issue by breenger** [robolectric/robolectric#6743]
### Description
Appears to be related to the changes made in this ticket:
https://github.com/robolectric/robolectric/pull/5053

When attempting to get a BluetoothProfile from the BluetoothAdapter.getProfileProxy() method, when configured to run on Android SDK 18, it will throw an IllegalArgumentException.  When running as any version higher than this, it succeeds.

Note, the targetSdkVersion for this project is set to 23 in its gradle file

### Steps to Reproduce
Code throwing exception:
```
@Config(sdk = [18])
public class BluetoothTest {
  @Test
  void setupBluetooth() {
    BluetoothAdapter.getDefaultAdapter().getProfileProxy(ApplicationProvider.getApplicationContext(), new ServiceListener() {
      @Override
      public void onServiceDisconnected(int profile) {
      }
      @Override
      public void onServiceConnected(int profile, BluetoothProfile proxy) {
      }
    }, BluetoothProfile.A2DP);
  }
}
```

### Stacktrace
```
Service Intent must be explicit: Intent { act=android.bluetooth.IBluetoothA2dp }
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.bluetooth.IBluetoothA2dp }
	at org.robolectric.shadows.ShadowContextImpl.validateServiceIntent(ShadowContextImpl.java:347)
	at org.robolectric.shadows.ShadowContextImpl.bindService(ShadowContextImpl.java:326)
	at android.app.ContextImpl.bindService(ContextImpl.java)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:496)
	at android.bluetooth.BluetoothA2dp.__constructor__(BluetoothA2dp.java:160)
	at android.bluetooth.BluetoothA2dp.<init>(BluetoothA2dp.java)
	at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java:1165)
	at android.bluetooth.BluetoothAdapter$GeneratedProxy/0x00000008004f3c40.getProfileProxy(Unknown Source)
	at org.robolectric.shadows.ShadowBluetoothAdapter.getProfileProxy(ShadowBluetoothAdapter.java:425)
	at android.bluetooth.BluetoothAdapter.getProfileProxy(BluetoothAdapter.java)
	at com.videri.icanvasplayer.vservice.command_handlers.CommandHandlerTest.testBluetooth(CommandHandlerTest.kt:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Robolectric & Android Version
Roboelectric 4.6.1
Android SDK 18

**Comment by hoisie** [comment]
Looks like this line may be the problem:
https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowContextImpl.java#L343

Instead of:
`realContextImpl.getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.LOLLIPOP`

Perhaps it should be:
`RuntimeEnvironment.getApiLevel() >= Build.VERSION_CODES.LOLLIPOP`
