### ISSUE TITLE
ExpectedLogMessagesRuleTest failed on Windows 10

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6751]
### Description

I tried to test `./gradlew.bat test -PSKIP_JAVADOC=true` on Windows 10 in Windows Terminal, and I found there are tests failed on Windows 10.

Failed 1: `ExpectedLogMessagesRuleTest#testExpectedLogMessageWithMatcherFailureOutput`

```
java.lang.AssertionError: 
Expected: Matches ExpectedLogMessagesRule:
[\s\S]*Expected, and observed:\s+\[LogItem\{\s+timeString='.+'\s+type=6\s+tag='Mytag'\s+msg='message1'\s+throwable=null\s+\}\][\s\S]*
[\s\S]*Observed, but not expected:\s+\[LogItem\{\s+timeString='.+'\s+type=6\s+tag='Mytag'\s+msg='message2'\s+throwable=java.lang.IllegalArgumentException(\s+at .*\)\n)+\s+\}\][\s\S]*
[\s\S]*Expected, but not observed: \[ExpectedLogItem\{timeString='.+', type=6, tag='Mytag', msg='message2', throwable=.*UnsupportedOperationException.*\}\][\s\S]*
     but: was <java.lang.AssertionError: Expected and observed logs did not match.
Expected:                   [ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message2', throwable=an instance of java.lang.UnsupportedOperationException}, ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message1'}]
Expected, and observed:     [LogItem{
  timeString='null'
  type=6
  tag='Mytag'
  msg='message1'
  throwable=null
}]
Expected, but not observed: [ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message2', throwable=an instance of java.lang.UnsupportedOperationException}]
Observed, but not expected: [LogItem{
  timeString='null'
  type=6
  tag='Mytag'
  msg='message2'
  throwable=java.lang.IllegalArgumentException
	at org.robolectric.junit.rules.ExpectedLogMessagesRuleTest.testExpectedLogMessageWithMatcherFailureOutput(ExpectedLogMessagesRuleTest.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.junit.rules.ExpectedLogMessagesRule$1.evaluate(ExpectedLogMessagesRule.java:44)
        .....

}]>
Stacktrace was: java.lang.AssertionError: Expected and observed logs did not match.
Expected:                   [ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message2', throwable=an instance of java.lang.UnsupportedOperationException}, ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message1'}]
Expected, and observed:     [LogItem{
  timeString='null'
  type=6
  tag='Mytag'
  msg='message1'
  throwable=null
}]
Expected, but not observed: [ExpectedLogItem{timeString='null', type=6, tag='Mytag', msg='message2', throwable=an instance of java.lang.UnsupportedOperationException}]
Observed, but not expected: [LogItem{
  timeString='null'
  type=6
  tag='Mytag'
  msg='message2'
  throwable=java.lang.IllegalArgumentException
	at org.robolectric.junit.rules.ExpectedLogMessagesRuleTest.testExpectedLogMessageWithMatcherFailureOutput(ExpectedLogMessagesRuleTest.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.junit.rules.ExpectedLogMessagesRule$1.evaluate(ExpectedLogMessagesRule.java:44)
        .....

}]
	at org.robolectric.junit.rules.ExpectedLogMessagesRule$1.evaluate(ExpectedLogMessagesRule.java:83)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
       .....
```

### Steps to Reproduce

Download current master branch within 4.7-SNAPSHOT development, setup it OpenJDK 11 for Windows 10,  and run ` ./gradlew.bat test -PSKIP_JAVADOC=true` in Windows Terminal. 

### Robolectric & Android Version

4.7-SNAPTSHOT

### Link to a public git repo demonstrating the problem:

`Robolectric` itself.

cc @hoisie .

**Comment by utzcoz** [comment]
Another thing related Windows to run CI jobs on Windows instance. It is also useful when we start to support native sqlite supporting for Windows.

**Comment by utzcoz** [comment]
`ShadowSharedMemoryTest` case moved to https://github.com/robolectric/robolectric/issues/7856.
