### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.sortedCopyOf(Ljava/util/Comparator;Ljava    /lang/Iterable;)Lcom/google/common/collect/ImmutableList;

### ISSUE THREAD

**Issue by Prat-JD** [robolectric/robolectric#6832]
I'm able run unit test through test runner and getting coverage as well. However when I try to run with JaCoCo through CLI `gradlew jacocoTestReportDebug --debug`, getting error.

Using Android Studio Version Android Studio 4.1.2
```
Build #AI-201.8743.12.41.7042882, built on December 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true, external.system.auto.import.disabled=true
Non-Bundled Plugins: PerforceIC, com.thoughtworks.gauge, org.intellij.plugins.markdown
```

### Error

 ```
   java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.sortedCopyOf(Ljava/util/Comparator;Ljava    /lang/Iterable;)Lcom/google/common/collect/ImmutableList;

	at org.robolectric.internal.bytecode.ShadowProviders.<init>(ShadowProviders.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.robolectric.util.inject.Injector.inject(Injector.java:250)
	at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:232)
	at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
	at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
	at org.robolectric.util.inject.Injector.getInstance(Injector.java:202)
	at org.robolectric.internal.SandboxTestRunner.<init>(SandboxTestRunner.java:78)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:103)
	at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:98)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

```

I'm using 

```
dependencies {
        classpath ("com.android.tools.build:gradle:4.1.3") {
        }
}
```

```
    testImplementation 'androidx.test:core:1.3.0'
    testImplementation 'org.mockito:mockito-core:3.4.0'
    testImplementation 'org.mockito:mockito-inline:3.4.0'
    testImplementation 'androidx.test.ext:junit:1.1.2'
    testImplementation('org.robolectric:robolectric:4.5.1') {
       // exclude group: 'com.google.guava', module: 'guava'
    }
   testImplementation 'androidx.test.ext:truth:1.3.0'
```

```
testOptions {

        animationsDisabled true

        unitTests {
            includeAndroidResources = true
        }
        unitTests.all {
            //systemProperty 'robolectric.enabledSdks', '28'
            // jvmArgs '-noverify'
            //systemProperty 'user.home', System.getenv('HOME')

            jacoco {
                includeNoLocationClasses = true
            }
        }
        unitTests.returnDefaultValues = true
    }

```

```
compileSdkVersion 28
    //buildToolsVersion "30.0.3"

    //testOptions.unitTests.includeAndroidResources = true

    defaultConfig {
        applicationId "com.cepheid.epsilon"
        minSdkVersion 25
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
       
    }
```

Please help me resolve!

**Comment by Prat-JD** [comment]
Similar to #5147

**Comment by hoisie** [comment]
This is happening because there is more than one version of Guava on your classpath. One of them is being included by Gradle, and the other is likely part of some other jar file. You need to iterate over your jar file dependencies and figure out where the other guava is coming from, and then remove that.

There are many techniques you can use to do this, such as printing the classpath before the errornand calling `jar tf <jar>` and grep for guava

Closing this as it is not a Robolectric issue. If you can provide a minimal repro and still feel it is a Robolectric issue, I'll reopen.
