### ISSUE TITLE
Room cannot be mocked since Robolectric 4.6

### ISSUE THREAD

**Issue by wjlight** [robolectric/robolectric#6861]
I want test room, in path src/test/java ,  like below:
```
    @Mock
    protected AppDatabase mDatabase;

    @Rule
    public InstantTaskExecutorRule instantTaskExecutorRule = new InstantTaskExecutorRule();

    @Before
    public void initDb() throws Exception {
        mDatabase = Room.inMemoryDatabaseBuilder(RuntimeEnvironment.application,
                AppDatabase.class)
                .allowMainThreadQueries()
                .build();
    }
```

Use Robolectric 4.5  run ok， but since 4.6 ，there is error：
```
Could not initialize class android.database.CursorWindow
java.lang.NoClassDefFoundError: Could not initialize class android.database.CursorWindow
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281
```
```

java.lang.ExceptionInInitializerError
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at com.wps.woa.db.dao.AppDownloadedDao_Impl.insert(AppDownloadedDao_Impl.java:74)
	at com.wps.koa.db.AppDownloadedDaoTest.testInsert(AppDownloadedDaoTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:570)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:181)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.database.CursorWindow.<clinit>(CursorWindow.java)
	at android.database.AbstractWindowedCursor.$$robo$$android_database_AbstractWindowedCursor$clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java)
	at android.database.sqlite.SQLiteCursor.$$robo$$android_database_sqlite_SQLiteCursor$fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java)
	at android.database.sqlite.SQLiteCursor.$$robo$$android_database_sqlite_SQLiteCursor$getCount(SQLiteCursor.java:133)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java)
	at android.database.AbstractCursor.$$robo$$android_database_AbstractCursor$moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java)
	at android.database.AbstractCursor.$$robo$$android_database_AbstractCursor$moveToFirst(AbstractCursor.java:236)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getWritableDatabase(SQLiteOpenHelper.java:164)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at com.wps.woa.db.dao.AppDownloadedDao_Impl.insert(AppDownloadedDao_Impl.java:74)
	at com.wps.koa.db.AppDownloadedDaoTest.testInsert(AppDownloadedDaoTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	... 15 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	... 44 more
Caused by: java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1019)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceValue(ShadowLegacyAssetManager.java:319)
	at android.content.res.AssetManager.getResourceValue(AssetManager.java)
	at android.content.res.Resources.getValue(Resources.java:1009)
	at android.content.res.Resources.getInteger(Resources.java:820)
	at android.database.CursorWindow.__staticInitializer__(CursorWindow.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.database.CursorWindow.<clinit>(CursorWindow.java)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:196)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:236)
	at androidx.room.RoomOpenHelper.hasEmptySchema(RoomOpenHelper.java:196)
	at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:73)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:252)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at com.wps.woa.db.dao.AppDownloadedDao_Impl.insert(AppDownloadedDao_Impl.java:74)
	at com.wps.koa.db.AppDownloadedDaoTest.testInsert(AppDownloadedDaoTest.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	... 15 more


```

#### Robolectric & Android Version
Android Gradle Plugin : 7.0.2
Robolectric 4.6
Java 11

**Comment by hoisie** [comment]
The solution for this is to switch to binary resources:

```
    testOptions  {
        unitTests {
            includeAndroidResources = true
        }
    }
```

My guess is that the error occurs when calling CursorWindiow.geCursorWindowSize:

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/database/CursorWindow.java;l=807-815;bpv=1;bpt=1?q=cursorwindow.java

**Comment by oth-libs** [comment]
hmm why is this not mentioned anywhere? seems very important. is there any downside?
