### ISSUE TITLE
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class modifiers

### ISSUE THREAD

**Issue by bacecek** [robolectric/robolectric#6863]
### Description
After updating Robolectric from 4.6.1 to 4.7 Mockito cannot mock class `android.animation.ObjectAnimator`. Full stacktrace:
```
Mockito cannot mock this class: class android.animation.ObjectAnimator.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 11.0.11+9
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.11+9
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.16


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class android.animation.ObjectAnimator, interface org.robolectric.internal.bytecode.ShadowedObject, class java.lang.Object, interface android.animation.AnimationHandler$AnimationFrameCallback, class android.animation.ValueAnimator, interface org.robolectric.internal.bytecode.InstrumentedInterface, class android.animation.Animator, interface java.lang.Cloneable]
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class android.animation.ObjectAnimator.

If you're not sure why you're getting this error, please report to the mailing list.


Java               : 11
JVM vendor name    : AdoptOpenJDK
JVM vendor version : 11.0.11+9
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 11.0.11+9
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.16


You are seeing this disclaimer because Mockito is configured to create inlined mocks.
You can learn about inline mocks and their limitations under item #39 of the Mockito class javadoc.

Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class android.animation.ObjectAnimator, interface org.robolectric.internal.bytecode.ShadowedObject, class java.lang.Object, interface android.animation.AnimationHandler$AnimationFrameCallback, class android.animation.ValueAnimator, interface org.robolectric.internal.bytecode.InstrumentedInterface, class android.animation.Animator, interface java.lang.Cloneable]
	at app.bacecek.TestClass.testAndroidAnimator(TestClass.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.mockito.exceptions.base.MockitoException: Could not modify all classes [class android.animation.ObjectAnimator, interface org.robolectric.internal.bytecode.ShadowedObject, class java.lang.Object, interface android.animation.AnimationHandler$AnimationFrameCallback, class android.animation.ValueAnimator, interface org.robolectric.internal.bytecode.InstrumentedInterface, class android.animation.Animator, interface java.lang.Cloneable]
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	... 16 more
Caused by: java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class modifiers
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:276)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.mockClass(InlineBytecodeGenerator.java:213)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.lambda$mockClass$0(TypeCachingBytecodeGenerator.java:47)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:153)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:366)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:175)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:377)
	at org.mockito.internal.creation.bytebuddy.TypeCachingBytecodeGenerator.mockClass(TypeCachingBytecodeGenerator.java:40)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMockType(InlineDelegateByteBuddyMockMaker.java:389)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.doCreateMock(InlineDelegateByteBuddyMockMaker.java:349)
	at org.mockito.internal.creation.bytebuddy.InlineDelegateByteBuddyMockMaker.createMock(InlineDelegateByteBuddyMockMaker.java:328)
	at org.mockito.internal.creation.bytebuddy.InlineByteBuddyMockMaker.createMock(InlineByteBuddyMockMaker.java:56)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:53)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:84)
	at org.mockito.Mockito.mock(Mockito.java:1956)
	at org.mockito.Mockito.mock(Mockito.java:1871)
	... 16 more
```

### Steps to Reproduce
Sample test:
```
@RunWith(RobolectricTestRunner.class)
@Config(sdk = Build.VERSION_CODES.S, manifest = Config.NONE)
public class TestClass {

    @Test
    public void testAndroidAnimator() {
        ObjectAnimator mock = Mockito.mock(ObjectAnimator.class);
    }
}
```

build.gradle file:
```
dependencies {
     ...
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.robolectric:robolectric:4.7'
    testImplementation 'org.mockito:mockito-core:4.0.0'
    testImplementation 'org.mockito:mockito-inline:4.0.0'
}
```

### Robolectric & Android Version
Robolectric 4.7
Mockito 4.0.0

### Link to a public git repo demonstrating the problem:
https://github.com/bacecek/sample-checking-assistant-role/tree/robolectric_47

**Comment by hoisie** [comment]
Hi @bacecek, thank you for the detailed bug report. This is the same issue as #858, and there are some more details there. I will close this one to dedupe.

We've identified the issue and have a fix -- my plan is to release 4.7.1 some time today with a fix for this issue.
