### ISSUE TITLE
java.lang.RuntimeException: no artifacts found for DependencyJar{org.robolectric:android-all:10-robolectric-5803371}

### ISSUE THREAD

**Issue by arjit-meesho** [robolectric/robolectric#6886]
### Description

After updating to JDK 11 and compiling SDK 31 (Android S). I am getting the following issue.

```
java.lang.RuntimeException: no artifacts found for DependencyJar{org.robolectric:android-all:10-robolectric-5803371}
	at org.robolectric.internal.dependency.PropertiesDependencyResolver.getLocalArtifactUrl(PropertiesDependencyResolver.java:61)
	at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:89)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:127)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:321)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$1(AndroidTestEnvironment.java:296)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:294)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:195)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:171)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:319)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:254)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Robolectric & Android Version

Roboelectric Version - 4.4
Target SDK Version - 30
Compile SDK Version - 31

**Comment by hoisie** [comment]
SDK 31 requires Robolectric 4.7.3.

**Comment by arjit-meesho** [comment]
@hoisie In the release notes it says support for API 31 was added in Roboelectriv 4.7. I have tried compiling with 4.7 and got the same error.

May be it is because of hermetic setup we have on CI:

```
def robolectricVersion = versions.robolectricVersion

def androidSdkVersions = [
        '7.0.0_r1-robolectric-r1',
        '8.1.0-robolectric-4611349'
]

def shadowArtifacts = [

]

repositories {
    mavenLocal()
    jcenter()
}

configurations {
    sandbox
}

def allSdkConfigurations = []

androidSdkVersions.forEach { version ->
    allSdkConfigurations << configurations.create(version)
    dependencies.add(version, "org.robolectric:android-all:${version}")
    dependencies.add('sandbox', "org.robolectric:android-all:${version}")
}

task createRobolectricDeps {
}

task copyLibs(type: Copy) {
    into "$projectDir/libs/robolectric_libs"
    from configurations.compile
}

task copySdks(type: Copy) {
    into "$projectDir/src/test/resources/robolectric_sdks"
    from allSdkConfigurations

    doLast {
        def f = new File("$projectDir/src/test/resources/robolectric-deps.properties")
        f.delete()

        allSdkConfigurations.forEach { config ->
            config.allDependencies.forEach { dep ->
                def files = new ArrayList(config.files)
                if (files.size != 1) {
                    throw new RuntimeException("huh, more than one file in ${dep}? ${files}")
                }
                def file = files[0]
                f << "${dep.group}\\:${dep.name}\\:${dep.version}=robolectric_sdks/${file.name}\n"
            }
        }
    }
}

task filesForHermeticBuild {
    dependsOn createRobolectricDeps
    dependsOn copyLibs
    dependsOn copySdks
}


import java.util.concurrent.TimeUnit

// Log timings per task.
class TimingsListener implements TaskExecutionListener, BuildListener {
    private long startTime
    private timings = []

    @Override
    void beforeExecute(Task task) {
        startTime = System.nanoTime()
    }

    @Override
    void afterExecute(Task task, TaskState taskState) {
        def ms = TimeUnit.MILLISECONDS.convert(System.nanoTime() - startTime, TimeUnit.NANOSECONDS)
        timings.add(new Tuple2<Integer, String>(ms, task.path))
        task.project.logger.warn "${task.path} took ${getDisplayTime(ms)}"
    }

    @Override
    void buildFinished(BuildResult result) {
        println "Task timings:"
        def tmp = timings.toSorted(new Comparator<Tuple2<Integer, String>>() {
            @Override
            int compare(Tuple2<Integer, String> o, Tuple2<Integer, String> t1) {
                return o.first - t1.first
            }
        })
        for (timing in tmp) {
            printf "%s  %s\n", getDisplayTime(timing.first), timing.second
        }
    }

    static String getDisplayTime(long ms) {
        if (ms >= 1000) {
            return String.format("%ss", ms / 1000)
        } else {
            return String.format("%sms", ms)
        }
    }

    @Override
    void buildStarted(Gradle gradle) {}

    @Override
    void projectsEvaluated(Gradle gradle) {}

    @Override
    void projectsLoaded(Gradle gradle) {}

    @Override
    void settingsEvaluated(Settings settings) {}
}

boolean timeLogs = hasProperty('timeLogs') ? property('timeLogs').toBoolean() : false

if (timeLogs) {
    gradle.addListener new TimingsListener()
}

```

**Comment by hoisie** [comment]
```
def androidSdkVersions = [
        '7.0.0_r1-robolectric-r1',
        '8.1.0-robolectric-4611349'
]
```

This only includes Android N and O_MR1. If you want S, you will need version 12.

**Comment by JohnZhang1000** [comment]
I 'm sorry to disturbing you , I want to know how can we build a jar lilkes android-all-10-robolectric-5803371.jar for Android S, I saw some scripts shell here https://github.com/robolectric/robolectric/blob/master/scripts/build-android.sh ,but its doesn't show how  to build a jar for Android S. Does any one knows how to do it?   I would  be appreciated.

**Comment by hoisie** [comment]
@JohnZhang1000 I believe it is the result of running `m -j robolectric-host-android_all` from an Android platform checkout, i.e.:

https://cs.android.com/android/platform/superproject/+/master:external/robolectric-shadows/Android.bp;l=113

**Comment by JohnZhang1000** [comment]
@hoisie You are the greatest. Thank you for helping me :)
