### ISSUE TITLE
Invalid sqliteBlobTooBigException when using Sqlite Native mode with Robolectric 4.7

### ISSUE THREAD

**Issue by kenyee** [robolectric/robolectric#6899]
### Description
When enabling Native mode, Robolectric throws an incorrect BlobTooBigException.  Disabling Native mode (comment out the annotation in the repro code below) lets the test pass.
Default max cursor size for Sqlite should be 2GB.  This retrieves data that is only 5000 bytes.

### Steps to Reproduce
Run this code in a unit test with Robolectric 4.7.3:
```
package com.example.robolectricsqlbug

import android.content.ContentValues
import android.database.sqlite.SQLiteCursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteDatabase.CursorFactory
import org.assertj.core.api.Assertions.assertThat
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.SQLiteMode
import java.io.File
import java.io.IOException

@RunWith(RobolectricTestRunner::class)
class DBUnitTest {
    private val tempFile = File.createTempFile("tmp", "tmp")

    @Test
    @Throws(IOException::class)
    @SQLiteMode(SQLiteMode.Mode.NATIVE)
    fun testDefaultWindowValidationFails() {
        createDatabase(null).use { db ->
            val sqlCursor = db.query("test_table", null, null, null, null, null, null)
                as SQLiteCursor
            sqlCursor.use { cursor ->
                // Check that the default cursor fails to validate the position.
                val result = cursor.onMove(0, 20)
                assertThat(result).isTrue
            }
        }
    }

    @Throws(IOException::class)
    private fun createDatabase(factory: CursorFactory?): SQLiteDatabase {
        val db = SQLiteDatabase.openOrCreateDatabase(tempFile, factory)
        db.execSQL("CREATE TABLE test_table (_id INTEGER PRIMARY KEY AUTOINCREMENT, data BLOB);")
        val values = ContentValues()
        values.put("data", ByteArray(500))
        (0..9).forEach { _ ->
            db.insert("test_table", null, values)
        }
        return db
    }
}
```

### Robolectric & Android Version
4.7.3
Android Studio Arctic Fox and Chipmunk

### Link to a public git repo demonstrating the problem:
See short repro unit test above

**Comment by hoisie** [comment]
This same error also occurs on a real device, from SDKs 28-31:

IMO this is native SQLite working as intended :) It is more realistic.

```
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=20, totalRows=10
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:128)
	at android.database.SQLiteDatabaseTest.testDefaultWindowValidationFails(SQLiteDatabaseTest.java:156)
```

**Comment by kenyee** [comment]
oops...should have tried this on a real device to confirm...sorry about that :-(

Hmm..what should the error message be?  I'm guessing something like "cursor out of range"?

**Comment by kenyee** [comment]
one other thing...in robolectric.properties, we have:
sdk=27

so maybe that explains why it works in non-native mode...I didn't realize this behavior changed in sdk28.

**Comment by utzcoz** [comment]
@kenyee Looks like it is not a Robolectric bug. Feel free to reopen it if you think there are other things we should discuss at this issue.
