### ISSUE TITLE
NoSuchMethodException for SpannableStringBuilder when Jetpack Compose also available in app

### ISSUE THREAD

**Issue by simtse** [robolectric/robolectric#6901]
### Description
Noticed that our robolectric test where the system under test used `SpannableStringBuilder` would fail when Jetpack Compose was also enabled and built. When Jetpack Compose was not enabled, the issue would disappear.

```kotlin
    var getSpanEndCount = 0
    val spanString = "@myuseri"
    val editable = object : SpannableStringBuilder(SpannableString(spanString)) {
      override fun getSpanEnd(what: Any?): Int {
        getSpanEndCount++
        if (getSpanEndCount > 2) {
          // reason)
          return -1
        }
        return super.getSpanEnd(what)
      }
    }
    editable.setSpan(userSpan, 0, spanString.length, 0)
    view.getText() returns editable

    underTest.verifyTagSpans()

    verify(view, never()).restartInput()
```

☝️ would fail

But if we add the following, the test would pass and the method is found and the test would pass. 

```kotlin
      override val length: Int
        get() = spanString.length
```

The exact error was the following:

```
'int slack.app.PresenterTest$verifyTagSpans - when span should be removed but span is already removed - does nothing$editable$1.getLength()'
java.lang.NoSuchMethodError: 'int slack.app.PresenterTest$verifyTagSpans - when span should be removed but span is already removed - does nothing$editable$1.getLength()'
	at slack.app.PresenterTest$verifyTagSpans - when span should be removed but span is already removed - does nothing$editable$1.length(PresenterTest.kt:416)
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1306)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
	at slack.app.PresenterTest.verifyTagSpans - when span should be removed but span is already removed - does nothing(PresenterTest.kt:430)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Not sure what is causing it to happen yet. This happens with 

### Robolectric & Android Version
Kotlin 1.5.31
Robolectric 4.7
Android Api level 31

**Comment by hoisie** [comment]
Can you capture this issue in a small sample app or a test case in Robolectric? This issue isn't actionable as-is.

**Comment by utzcoz** [comment]
@simtse Please try the latest Robolectric and check whether this issue still exists. You also can try native graphics mode for your test code with Jetpack Compose. If it still exists, please reopen this issue and attach your minimal reproducible app/sample, and the team can investigate it with your app/sample.
