### ISSUE TITLE
Legacy resource mode NPE w/ Robolectric 4.7.3

### ISSUE THREAD

**Issue by kenyee** [robolectric/robolectric#6916]
### Description
We ran into this because we're using the android-all jar and Robolectric tests in a JVM-only module (no Android stuff) so we can't do "includeAndroidResources" to kick it into binary resources mode.
Trying to do this causes no resources to be found:
systemProperty("robolectric.resourcesMode", "binary")

### Steps to Reproduce
Run test in repro project.

One of our folks worked around this by replacing uses of the resourceTable field with calls to the getResourceTable() method in the shadow asset manager class.

### Robolectric & Android Version
4.7.3.

### Link to a public git repo demonstrating the problem:
see attached repro project
[robolectricLegacyResourcesBug.zip](https://github.com/robolectric/robolectric/files/7669544/robolectricLegacyResourcesBug.zip)

**Comment by hoisie** [comment]
Just for full transparency, legacy resources has been deprecated for years and is not under development any more. If you use legacy resources, it is not surprising that resources are not found. This is exactly the reason binary resources was developed, so Robolectric had a predictable place to find all app and system resources.

I would strongly encourage you to investigate a way to migrate to binary resources, i.e. find a way to use AGP.

If that's not possible, you are welcome to investigate the root cause for this issue. I'd recommend setting breakpoints in the legacy resources logic and see which paths are being searched for XML resources.

**Comment by kenyee** [comment]
This is how it manifests in a jvm only (non-android) gradle module.  There are no resources so Robolectric defaults to legacy mode.  If we set robolectric to use binary mode resources, it can't find any tests :-(

I can submit a PR that fixes the legacy mode NPE if that helps...

Would love it if there were an official way to run robolectric tests in jvm only gradle modules...

**Comment by hoisie** [comment]
Stack trace:

```
 
 com.example.robolectricsqlbug.DBUnitTest > testDefaultWindowValidationFails FAILED
     java.lang.NullPointerException
         at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1106)
         at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceText(ShadowLegacyAssetManager.java:285)
         at android.content.res.AssetManager.getResourceText(AssetManager.java)
         at android.content.res.Resources.getText(Resources.java:225)
         at android.content.res.Resources.getString(Resources.java:313)
         at android.database.sqlite.SQLiteGlobal.getDefaultJournalMode(SQLiteGlobal.java:74)
         at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:287)
         at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
         at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
         at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
         at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
         at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
         at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
         at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
         at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
         at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:709)
         at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:702)
         at com.example.robolectricsqlbug.DBUnitTest.createDatabase(DBUnitTest.kt:38)
         at com.example.robolectricsqlbug.DBUnitTest.testDefaultWindowValidationFails(DBUnitTest.kt:25)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
         at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
         at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
         at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
         at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
         at java.base/java.lang.Thread.run(Thread.java:830)
 
 com.example.robolectricsqlbug.DBUnitTest FAILED
 

```

**Comment by hoisie** [comment]
So it looks like the failure happens when Android code tries to look up a system string resource (`com.android.internal.R.string.db_default_journal_mode`)

The logic that sets up the system resource table for legacy resources appears to be here:

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java#L418

You are welcome to debug that to see why `db_default_journal_mode` is not picked up. It's possible that the system resources are not found at all.

**Comment by kenyee** [comment]
Put up a PR to fix the ShadowLegacyAssetManager.

Hopefully, you folks will have some official guidance on trying to run Robolectric tests in a JVM only module at some point.  Our use case is for testing Sqlite code.

**Comment by hoisie** [comment]
Re-opening, I may do a git bisect to find the CL and see what the underlying issue may be.

**Comment by hoisie** [comment]
Looks like this was broken some time in between 4.5 and 4.6. That test works on 4.5.1, but is broken in 4.6.

Simpler repro:

```
    @Test
    fun testDefaultWindowValidationFails() {
      val s : String = ReflectionHelpers.callStaticMethod(Class.forName("android.database.sqlite.SQLiteGlobal"), "getDefaultJournalMode");
    }
```

**Comment by kenyee** [comment]
Oops...yes...sorry, should have mentioned this was broken in 4.6 as well (I tested up to 4.5.1 w/o hitting this issue).
I thought it had to do w/ the preinstrumented jars but doesn't sound like it if that's the repro...

**Comment by hoisie** [comment]
The culprit is 9c7c35ae8a0afc9b4de6aa9c7e70b7090663eed4. This was an initial PR to support Android S.

Looks like by default, in that kind of Java project, the API level is **16**. You can see this by running `System.err.println("API level = " + RuntimeEnvironment.getApiLevel());`. Maybe we should default to a newer SDK version in this type of project.

If you change that test to use `@Config(manifest = Config.NONE, sdk=[30])`, the test passes. So it seems like those changes had issues in very early API levels.

At this point I don't think it's worth investigating fixing issues with SDK 16.

Anyway I'll close this for now. I would still encourage you to find a way to make an empty shell project using AGP that contains the Robolectric test for this project which uses binary resources.

**Comment by cesar1000** [comment]
One question: why defaulting to legacy mode unconditionally if the resources are not defined? If legacy resources are not meant to be used anymore, why not allowing execution in binary mode with an empty resource table?

**Comment by hoisie** [comment]
@cesar1000 those are all very good points, I don't have a good reason for any of them :) We should probably update the defaults, especially if we plan to finally remove legacy resources. For system resources we do have access to the binary versions (they are embedded in the android_all jars), so we should at least default to using that, and an empty app resource table.

@kenyee does this project reference any legacy app resources?

**Comment by kenyee** [comment]
> I would still encourage you to find a way to make an empty shell project using AGP that contains the Robolectric test for this project which uses binary resources.

That's what we're planning on doing.  They're only in JVM only modules for faster compilation and so we can include these JVM only modules (mostly a custom sqlite framework) can be included by other JVM only modules.

> does this project reference any legacy app resources?

no...we're just in this legacy asset manager because the tests in the JVM only modules caused Robolectric to default to legacy mode.  Defaulting to an empty app resource table sounds like the right thing to do 🙂

**Comment by cesar1000** [comment]
This particular module is JVM-only because it's a dependency of an annotation processor, so we didn't really have a choice! Spitting tests off to an Android module is a possibility, just not ideal.

It feels reasonable that using legacy mode should be an explicit choice. Making the binary mode the default in every situation, whether resources are configured explicitly or not, would be awesome – even if a breaking change.

**Comment by hoisie** [comment]
@kenyee out of curiosity can you also try doing:
```
test {
    systemProperty "robolectric.resourcesMode", "binary"
}
```

And see if that fixes it? That should switch you to binary resources mode as well.

**Comment by cesar1000** [comment]
That won't work, since the test selection logic will currently only schedule a test to run in binary mode if the apk file is available. Forcing the mode to binary with no apk file results in no tests running at all (which looks like a bug in itself).

**Comment by kenyee** [comment]
> @kenyee out of curiosity can you also try doing:
>     systemProperty "robolectric.resourcesMode", "binary"
> And see if that fixes it? That should switch you to binary resources mode as well.

+1 what Cesar said.  I tried that initially and mentioned it when I wrote this up this issue.  It finds no tests (which is probably a bug since legacy mode finds tests in these jvm-only modules)...

**Comment by hoisie** [comment]
Thanks, I filed #6934 for silently skipping tests if app resources are not found.

**Comment by hoisie** [comment]
I dug around a bit more on this issue.

The root cause seems to be that, while creating the system context in AndroidTestEnvironment:

    Context systemContextImpl = reflector(_ContextImpl_.class).createSystemContext(activityThread);

```
    	at org.robolectric.shadows.ShadowLegacyAssetManager.__constructor__(ShadowLegacyAssetManager.java:254)
    	at android.content.res.AssetManager.<init>(AssetManager.java)
    	at android.content.res.AssetManager.$$robo$$android_content_res_AssetManager$ensureSystemAssets(AssetManager.java:102)
    	at android.content.res.AssetManager.ensureSystemAssets(AssetManager.java)
    	at android.content.res.AssetManager.$$robo$$android_content_res_AssetManager$getSystem(AssetManager.java:126)
    	at android.content.res.AssetManager.getSystem(AssetManager.java)
    	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:78)
    	at android.content.res.Resources.getSystem(Resources.java)
    	at android.app.ContextImpl.$$robo$$android_app_ContextImpl$createSystemContext(ContextImpl.java:1536)
    	at android.app.ContextImpl.createSystemContext(ContextImpl.java)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector4.createSystemContext(Unknown Source)
    	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:249)
    	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
    	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
    	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
    	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
    	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
    	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
    	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
    	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
    	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    	at java.base/java.lang.Thread.run(Thread.java:830)
```

In 9c7c35a, the call to `createSystemContext` got moved a lot higher in AndroidTestEnvironment, which means that the system resource table was not initialized. Seems like the system resource table, in legacy resources mode, has to be initialized before `createSystemContext` is called.

It is unfortunate that this issue was not identified and root caused as part of 9c7c35 :(

@cesar1000 it would be interesting to get some more details about this use case. Why do you need a Robolectric environment to test an annotation processor?

**Comment by cesar1000** [comment]
Hey @hoisie, sorry about the slow response – catching up after a long vacation!

The module we're using Robolectric on is a runtime library that contains classes referenced from the generated code. The annotation processor has a dependency on this module, since classes are referenced directly by the code generators – which forces us to declare this library as a Java module, even if it's essentially an Android module.

Our assumption was that this is a relatively typical need in Android annotation processors which it would make sense for Robolectric to cater to and, at least until recently, there was nothing preventing it from doing so.
