### ISSUE TITLE
NullPointerException throws by ShadowLegacyAsyncTask

### ISSUE THREAD

**Issue by ericntd** [robolectric/robolectric#6917]
### Description
More specifically `ShadowLegacyLooper.getBackgroundThreadScheduler()`
```
java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLegacyAsyncTask.execute(ShadowLegacyAsyncTask.java:100)
	at com.myapp.shadows.MyShadowAsyncTask.executeOnExecutor(CmbShadowAsyncTask.java:19)
	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java)
```
MyShadowAsyncTask
```java
@Implements(AsyncTask.class)
public class MyShadowAsyncTask<Params, Progress, Result>
    extends ShadowLegacyAsyncTask<Params, Progress, Result> {

  @Implementation
  @SuppressWarnings("unchecked")
  public AsyncTask<Params, Progress, Result> executeOnExecutor(
      Executor executor, Params... params) {
    return super.execute(params);
  }
}
```

### Steps to Reproduce
Just run any test with
```
@RunWith(RobolectricTestRunner.class)
@Config(

    sdk = Build.VERSION_CODES.N_MR1,
    shadows = {MyShadowAsyncTask.class}
)
```

### Robolectric & Android Version
Robolectric 4.7.2
compile and target sdk : 30

### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
Thanks, I filed #6934 for silently skipping tests if app resources are not found.
