### ISSUE TITLE
java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore

### ISSUE THREAD

**Issue by ericntd** [robolectric/robolectric#6925]
### Description
Been using Java 1.8 and upgrading to Java 11 now
```
huh? java 11, need help!
java.lang.RuntimeException: huh? java 11, need help!
	at org.robolectric.util.reflector.UnsafeAccess$Danger11Plus.throwException(UnsafeAccess.java:92)
	at org.robolectric.util.reflector.UnsafeAccess.throwException(UnsafeAccess.java:30)
	at org.robolectric.internal.bytecode.Sandbox.runOnMainThread(Sandbox.java:102)
	at org.robolectric.internal.bytecode.Sandbox.runOnMainThread(Sandbox.java:88)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:226)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:100)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: huh? java 11, need help!
	at org.robolectric.util.reflector.UnsafeAccess$Danger11Plus.throwException(UnsafeAccess.java:92)
	at org.robolectric.util.reflector.UnsafeAccess.throwException(UnsafeAccess.java:30)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:261)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: java.lang.NullPointerException: No password supplied for PKCS#12 KeyStore.
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at okhttp3.internal.platform.Platform.platformTrustManager(Platform.kt:80)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:222)
	at com.perimeterx.msdk.g.j.<init>(Unknown Source)
	at com.perimeterx.msdk.g.j.m(Unknown Source)
	at com.perimeterx.msdk.PXManager.setBackButtonDisabled(Unknown Source)
	at com.myapp.bakery.MyApplication.setupPX(MyApplication.java:173)
	at com.myapp.bakery.MyApplication.onCreate(MyApplication.java:144)
	at com.myapp.bakery.ApplicationBakeryDebug.onCreate(MyApplicationDebug.java:11)
	at org.robolectric.android.internal.AndroidEnvironment.lambda$installAndCreateApplication$0(AndroidEnvironment.java:253)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:75)
	at org.robolectric.android.internal.AndroidEnvironment.installAndCreateApplication(AndroidEnvironment.java:253)
	at org.robolectric.android.internal.AndroidEnvironment.setUpApplicationState(AndroidEnvironment.java:149)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:298)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:247)
	... 5 more
```

### Steps to Reproduce
1. Have a test with following config
```
@RunWith(RobolectricTestRunner.class)
@Config( sdk = Build.VERSION_CODES.N_MR1)
```
2. Upgrade from Java 1.8 to Java 11
3. Tried changing SDK from Build.VERSION_CODES.N_MR1 to Build.VERSION_CODES.O_MR1 but problem persisted
4. Tried adding `-Djavax.net.ssl.trustStoreType=JKS` as suggested by [this thread](https://github.com/robolectric/robolectric/issues/5496) and [this thread](https://github.com/robolectric/robolectric/issues/5115) to gradle.properties but it didn't work either

### Robolectric & Android Version
AGP 4.3.1 and Gradle 6.7.1
compileSdk 30
Robolectric 4.2

### Link to a public git repo demonstrating the problem:
N/A

**Comment by hoisie** [comment]
Can you try upgrading to the latest version of Robolectric (4.7.3)? It sort of reminds me of https://github.com/robolectric/robolectric/issues/5456, which was fixed in 4.4.

**Comment by ericntd** [comment]
I did @hoisie  and ran into other problems starting with https://stackoverflow.com/questions/70311538/robolectric-shadowasynctask-this-action-is-not-supported-in-paused-mode
Any clue? 🙏

**Comment by hoisie** [comment]
Have you tried switching to extend `ShadowLwgactAsyncTask` and using `@LooperMode(LEGACY)` so the legacy looper/asynctask shadows get used?

**Comment by ericntd** [comment]
Thanks @hoisie
I have not, trying out now...

**Comment by ericntd** [comment]
I'm getting
```
Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:502)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:581)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:263)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
which is quite clear

It's gonna be a hassle to apple this to hundreds of test classes (thousands of methods) but I guess there is no better/ faster way right 😅 

To wrap up, an you point me to a good resource on how to migrate away from ShadowLegacyAsyncTask btw? 🙏

**Comment by ericntd** [comment]
Sorry @hoisie , last question: what to do about
```
Robolectric.flushBackgroundThreadScheduler();
    Robolectric.flushForegroundThreadScheduler();
```
? 🙏

**Comment by hoisie** [comment]
@ericntd i don't think `Robolectric.flushBackgroundThreadScheduler` have any effect when using PAUSED looper mode

**Comment by ericntd** [comment]
Got it, thanks @hoisie
