### ISSUE TITLE
Can't load font after updating to Android 12 

### ISSUE THREAD

**Issue by ShivamPokhriyal** [robolectric/robolectric#6953]
### Description
After targetting Android 12, and using robolectric 4.7.3, I'm getting `Resources$NotFoundException`. 
Full stacktrace: 
```
Font resource ID #0x7f080000 could not be retrieved.
android.content.res.Resources$NotFoundException: Font resource ID #0x7f080000 could not be retrieved.
	at androidx.core.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:537)
	at androidx.core.content.res.ResourcesCompat.getFont(ResourcesCompat.java:372)
	at com.example.sample_lib.CommonFont.getFont(CommonFont.kt:7)
	at com.example.sampleapp.MainActivity.updateTextView(MainActivity.kt:18)
	at com.example.sampleapp.MainActivity.onCreate(MainActivity.kt:12)
	at android.app.Activity.performCreate(Activity.java:8051)
	at android.app.Activity.performCreate(Activity.java:8031)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:284)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:113)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:203)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:113)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:118)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:103)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:33)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:38)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:265)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:195)
	at com.example.sampleapp.MainActivityTest.testTextView(MainActivityTest.kt:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```
I created a minimal reproducible sample on github https://github.com/ShivamPokhriyal/SampleApp

Surprisingly, Adding @Config(sdk = [30]) annotation to the test works. 

I also checked the `apk-for-local-test.ap_` robo test apk to see if the font exists there and it did. 
```
➜ aapt2 dump resources apk-for-local-test.ap_ | grep 0x7f080000
    resource 0x7f080000 font/bogle
```
I could also see all the fonts that I've added to the project in the test apk.
```
➜ aapt2 dump resources apk-for-local-test.ap_ | grep font
    resource 0x7f030186 attr/font
    resource 0x7f030187 attr/fontFamily
    resource 0x7f030188 attr/fontProviderAuthority
    resource 0x7f030189 attr/fontProviderCerts
    resource 0x7f03018a attr/fontProviderFetchStrategy
    resource 0x7f03018b attr/fontProviderFetchTimeout
    resource 0x7f03018c attr/fontProviderPackage
    resource 0x7f03018d attr/fontProviderQuery
    resource 0x7f03018e attr/fontProviderSystemFontFamily
    resource 0x7f03018f attr/fontStyle
    resource 0x7f030190 attr/fontVariationSettings
    resource 0x7f030191 attr/fontWeight
    resource 0x7f0600ae dimen/material_filled_edittext_font_1_3_padding_bottom
    resource 0x7f0600af dimen/material_filled_edittext_font_1_3_padding_top
    resource 0x7f0600b0 dimen/material_filled_edittext_font_2_0_padding_bottom
    resource 0x7f0600b1 dimen/material_filled_edittext_font_2_0_padding_top
    resource 0x7f0600b2 dimen/material_font_1_3_box_collapsed_padding_top
    resource 0x7f0600b3 dimen/material_font_2_0_box_collapsed_padding_top
    resource 0x7f0600b5 dimen/material_helper_text_font_1_3_padding_horizontal
    resource 0x7f0600b6 dimen/material_helper_text_font_1_3_padding_top
  type font id=08 entryCount=3
    resource 0x7f080000 font/bogle
      () (file) res/font/bogle.xml type=XML
      (v22) (file) res/font-v22/bogle.xml type=XML
    resource 0x7f080001 font/bogle_bold
      () (file) res/font/bogle_bold.ttf
    resource 0x7f080002 font/bogle_regular
      () (file) res/font/bogle_regular.ttf
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif-light"
        fontFamily(0x7f030187)="sans-serif-light"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif-medium"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif"
        fontFamily(0x7f030187)="sans-serif-medium"
```

Perhaps the reason why it's happening is because the ShadowFontLoader https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowFontBuilder.java#L27 has a constraint `maxSdk = Q`

### Steps to Reproduce

Test any code that access a `font.xml` file using `ResourcesCompat.getFont(context, R.font.font_name)`. 

For simplicity, clone this repo https://github.com/ShivamPokhriyal/SampleApp and run `./gradlew :app:testDebugUnitTest --info`

### Robolectric & Android Version
robolectric version: 4.7.3
Android version: 12

### Link to a public git repo demonstrating the problem:
https://github.com/ShivamPokhriyal/SampleApp

**Comment by utzcoz** [comment]
@ShivamPokhriyal Thanks for pointing out this problem. Your problem looks like related to `ShadowFontBuilder`. But `maxSdk=Q` doesn't work for SDK 30, because Q is SDK 29. I will test it locally with your sample app.

**Comment by utzcoz** [comment]
After testing, I found the test failed on SDK 31 only, the same as your testing result, and it failed only when there are multiple fonts in `font/bogle.xml`. If I removed one `font` item from `font/bogle.xml` and left only one font, it will pass on SDK 31. Looks like Roboolectric can't process multi fonts in one font family on SDK 31.

**Comment by utzcoz** [comment]
I pushed a PR(https://github.com/robolectric/robolectric/pull/6954) to cover this test case for later investigating.

**Comment by ShivamPokhriyal** [comment]
Thanks for picking it up @utzcoz

**Comment by utzcoz** [comment]
`ResourcesCompat#getFont` calls `TypefaceCompatApi29Impl#createFromFontFamilyFilesResourceEntry` to load all fonts from `font-family` tags. It's very strange that `platformFont` generated by https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:core/core/src/main/java/androidx/core/graphics/TypefaceCompatApi29Impl.java;l=119-123?q=createFromFontFamilyFilesResourceEntry&ss=androidx is `ShadowFont`, and `FontFamily.Builder#addFont` calls its `toSting` method that raises NPE. I have tried to add `toString` for `ShadowFont` to validate call stack:
![Screenshot from 2022-01-03 19-11-29](https://user-images.githubusercontent.com/43091780/147924676-706d57ae-d964-41b8-948f-6efb90b63edf.png)

This modification raises another problem: `ShadowFont` is already added.

**Comment by utzcoz** [comment]
Oh, maybe something is wrong. The log tells me that `ShadowWrangle` picks null for `Font#toString`.

**Comment by ShivamPokhriyal** [comment]
Interesting, just curious what happens when you remove the `ShadowFont` class, like don't provide any shadow for the font?

**Comment by utzcoz** [comment]
> Interesting, just curious what happens when you remove the `ShadowFont` class, like don't provide any shadow for the font?

From current debugging, it is more related to `Font`. Looks like `Font#getBuffer` called by `Font#toString` raises NPE at following statement: 

```java
mBuffer = fromNative.asReadOnlyBuffer();
```

It uses `DirectuBuffer` known from source code comment. It's interesting that `ShadowFontBuilder#createBuffer` is re-implemented to avoid using `DirectByteBuffer#array`. Maybe we should re-implemented `getBuffer` or related native method for `Font` to reuse `ByteBuffer` created by `ShadowFontBuilder#createBuffer`.

**Comment by utzcoz** [comment]
https://cs.android.com/android/_/android/platform/frameworks/base/+/1dd39f3bded10f829d920941359e4393c79b2c42 and its ancestor commits use native `MinikinFont` to store `Font`, and restore from it with bound pointer address from Android S(SDK 31). I have updated the same PR(https://github.com/robolectric/robolectric/pull/6954) to add interception code to store `Font` states at Java level, and add methods to restore those states for shadowed native code. @ShivamPokhriyal maybe it needs some time to review and discuss, and you can use config to avoid running related test code with SDK 31 temporarily.

**Comment by ShivamPokhriyal** [comment]
Awesome, thanks @utzcoz

**Comment by ShivamPokhriyal** [comment]
@utzcoz Thanks for the fix. Do you know when is the next release?

**Comment by utzcoz** [comment]
> @utzcoz Thanks for the fix. Do you know when is the next release?

Hi @hoisie will we have a 4.7.4 release for this issue?
