### ISSUE TITLE
ShadowSQLiteConnectionTest run and failed on macOS with M1 chipset

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#6967]
### Description

The `ShadowSQLiteConnectioinTest` is used for testing legacy sqlite4java, but it is run on macOS with M1 chipset that sqlite4java doesn't support. So tests of `ShadowSQLiteConnectionTest` failed.

It's not urgent, but it maybe important for potential contributor who uses macOS with M1 chipset. For example, I found this problem when I am trying to develop Robolectric with my macBook Air.

There is a failed log:

```
org.robolectric.shadows.ShadowSQLiteConnectionTest > reset_closesConnection FAILED
    java.lang.RuntimeException: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/.../libsqlite4java.dylib: dlopen(/private/var/folders/r8/.../libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/r8/.../libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java.dylib' (no such file)
        at org.robolectric.shadows.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:92)
        at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:55)
        at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
        at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:70)
        at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:83)
        at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:807)
        at org.robolectric.shadows.ShadowSQLiteConnectionTest.createDatabase(ShadowSQLiteConnectionTest.java:200)
        at org.robolectric.shadows.ShadowSQLiteConnectionTest.setUp(ShadowSQLiteConnectionTest.java:43)
```

### Steps to Reproduce

Run `./gradlew test` on macOS with M1 chipset.

### Robolectric & Android Version

Current Robolectric master branch

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by utzcoz** [comment]
The potential solution is to add a method called `hasLegacyLibrary` in `SQLiteLibraryLoader` to check whether there is a sqlite4java native library for current running OS with specific architecture, and use it to ignore tests in `ShadowSQLiteConnectionTest` if it returns false, what represents sqlite4java doesn't support current OS with specific architecture.

**Comment by hoisie** [comment]
Should we add a call to `assumeThat` to skip ShadowSQLiteConnectionTest  on M1?

**Comment by hoisie** [comment]
ShadowSQLiteConnectionTest will pass with native sqlite on m1, so maybe we should not even allow using legacy sqlite on M1.

**Comment by utzcoz** [comment]
> ShadowSQLiteConnectionTest will pass with native sqlite on m1, so maybe we should not even allow using legacy sqlite on M1.

Agreed. We can add a util method to check whether legacy sqlite support current OS and architecture, and use [`assumeTrue`](https://github.com/robolectric/robolectric/issues/6967#issuecomment-1008337369) with this method for legacy sqlite tests to ensure they run on supported OS and architecture, and skip/ignore on M1 macOS.

**Comment by wiensmit** [comment]
We use this method to generate a contentful preseeded database, with currently doesn't work on M1 machines.
Is there any schedule of fixing this in an upcoming version?

```
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib: dlopen(/private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java.dylib' (no such file)
java.lang.RuntimeException: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib: dlopen(/private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/2v/jtp7sr711lvcx22478k2ncjc0000gp/T/1643709119658-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/libsqlite4java.dylib' (no such file)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:92)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:55)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativeOpen(ShadowSQLiteConnection.java:73)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:680)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.contentful.vault.SyncRunnable.<init>(SyncRunnable.java:76)
	at com.contentful.vault.SyncRunnable$Builder.build(SyncRunnable.java:575)
	at com.contentful.vault.Vault.requestSync(Vault.java:173)
	at com.hotels.app.content.db.DBExporter.export(DBExporter.kt:37)
	at com.hotels.app.content.db.ContentfulPreSeedingTest$syncContentfulDatabase$1.invokeSuspend(ContentfulPreSeedingTest.kt:23)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.hotels.app.content.db.ContentfulPreSeedingTest.syncContentfulDatabase(ContentfulPreSeedingTest.kt:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:575)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:278)

```

**Comment by hoisie** [comment]
@wiensmit Robolectric 4.7.3 supports SQLite on Mac M1.

**Comment by wiensmit** [comment]
Thanks! Seems we had a duplicate entry in our dependencies file causing a lower version being used. 

Sorry for bothering you (:

**Comment by utzcoz** [comment]
FYI, @wiensmit I think I will try to fix this problem this weekend.
