### ISSUE TITLE
 Robolectric 4.7.3 @Config(sdk=28) - java.lang.NoClassDefFoundError: android/text/TextUtils 

### ISSUE THREAD

**Issue by felipezad** [robolectric/robolectric#6977]
### Description

With Robolectric 4.7.3 and @Config(sdk=28), I get the following exceptions when running unit tests.

Similar to: java.lang.NoClassDefFoundError: android/text/TextUtils #4085

```
java.lang.ExceptionInInitializerError
	at net.openid.appauth.Preconditions.checkNotEmpty(Preconditions.java:68)
	at net.openid.appauth.AuthorizationRequest$Builder.setClientId(AuthorizationRequest.java:614)
	at net.openid.appauth.AuthorizationRequest$Builder.<init>(AuthorizationRequest.java:586)
	at net.openid.appauth.AuthorizationRequest.jsonDeserialize(AuthorizationRequest.java:1056)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:181)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.text.TextUtils.<clinit>(TextUtils.java)
	... 21 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	... 23 more
Caused by: java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1106)
	at org.robolectric.shadows.ShadowLegacyAssetManager.getResourceText(ShadowLegacyAssetManager.java:285)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:225)
	at android.content.res.Resources.getString(Resources.java:313)
	at android.text.TextUtils.__staticInitializer__(TextUtils.java:1704)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.internal.bytecode.RobolectricInternals.performStaticInitialization(RobolectricInternals.java:61)
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:178)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at android.text.TextUtils.<clinit>(TextUtils.java)
	at net.openid.appauth.Preconditions.checkNotEmpty(Preconditions.java:68)
	at net.openid.appauth.AuthorizationRequest$Builder.setClientId(AuthorizationRequest.java:614)
	at net.openid.appauth.AuthorizationRequest$Builder.<init>(AuthorizationRequest.java:586)
	at net.openid.appauth.AuthorizationRequest.jsonDeserialize(AuthorizationRequest.java:1056)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```
### Robolectric & Android Version

```
OpenJDK version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
```
```
Gradle 6.5
------------------------------------------------------------

Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4

Kotlin:       1.5.31
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.12 (Homebrew 11.0.12+0)
OS:           Mac OS X 11.6 x86_64
```

**Comment by utzcoz** [comment]
@felipezad Thanks for pointing out this problem. Could you help to provide a minimum project to reproduce this problem by following https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues?

**Comment by utzcoz** [comment]
> Caused by: java.lang.NullPointerException
	at org.robolectric.shadows.ShadowLegacyAssetManager.getAndResolve(ShadowLegacyAssetManager.java:1106)

Looks like your app uses legacy resource manager. Could you enable `includeAndroidResources = true` to test it with new resource manager, we maintain and develop now and future? There is an example:

```groovy
android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

**Comment by felipezad** [comment]
Thanks, @utzcoz. This change fixed the problem! 

>Could you help to provide a minimum project to reproduce this problem by 

You were faster than me, so I'll close it.

If I find something similar, I'll report it again.
