### ISSUE TITLE
java.lang.NoClassDefFoundError: sun/misc/SharedSecrets

### ISSUE THREAD

**Issue by ck1703** [robolectric/robolectric#6997]
I am using ANDROID-12 WITH JDK-11. i am seeing below error

2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]             Caused by:
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]             java.lang.NoClassDefFoundError: sun/misc/SharedSecrets
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.JLogger$MyLogRecord.inferCaller(JLogger.java:174)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.JLogger$MyLogRecord.getSourceClassName(JLogger.java:147)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.JFormatter.format(JFormatter.java:52)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.Log$1.publish(Log.java:48)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at java.logging/java.util.logging.Logger.log(Logger.java:980)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.JLogger.log(JLogger.java:118)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.Log.info(Log.java:145)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.log.LogC.info(LogC.java:97)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 at com.example.api.lib.util.json.JsonThings.<clinit>(JsonThings.java:95)
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger]                 ... 23 more
2022-01-21T17:10:32.797+0530 [DEBUG] [TestEventLogger] 
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                 Caused by:
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                 java.lang.ClassNotFoundException: sun.misc.SharedSecrets
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     at org.robolectric.internal.bytecode.SandboxClassLoader.loadClass(SandboxClassLoader.java:135)
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
2022-01-21T17:10:32.798+0530 [DEBUG] [TestEventLogger]                     ... 32 more

Could you please help to resolve this?

**Comment by utzcoz** [comment]
https://stackoverflow.com/questions/46612648/javalangaccess-and-sharedsecrets-in-java-9 Looks like `SharedSecrets` is moved into `jdk.internal.misc` and not exposed public default because of JDK's module system. I don't find the `SharedSecrets` usage of Robolectric from your error stack. Does your code use `SharedSecrets` directly? If yes, you can try https://discuss.gradle.org/t/gradle-doesnt-add-modules-to-module-path-during-compile/27382/8 to expose related module to your projects. If not, please link a minimal project to reproduce this problem.

**Comment by hoisie** [comment]
It looks like `com.example.api.lib.util.log` is using unsupported APIs that do not work any more in Java 8 on the JVM.  The solution is to update that logging logic to use APIs that are compatible with Java 9+.
