### ISSUE TITLE
Declare JDK prerequisites in contributing guidelines for both IDE and command line

### ISSUE THREAD

**Issue by ZSmallX** [robolectric/robolectric#6999]
### Description
Without JDK prerequisites of JDK 11 or newer, contributors can be confused when importing robolectric project in both command line and IDE can lead to an error.

### Steps to Reproduce

For command line, running `./gradlew` with JDK8:

Error message:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zsmallx/code/robolectric/errorprone/build.gradle' line: 35

* What went wrong:
A problem occurred evaluating project ':errorprone'.
> Could not find method compile() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

For IDE (Intellij IDEA), running in JDK8:
The same error with the command line output.

![image](https://user-images.githubusercontent.com/14019790/150792665-721f291d-e7f4-4647-898e-305fced93894.png)

### Robolectric & Android Version

The latest commit of master branch.

### Link to a public git repo demonstrating the problem:

None.

### correct behaviors:

Add JDK prerequisites in both README.md and contributing guidelines, with command line and IDE guidelines. Installing JDK 11 or newer or specifying the JDK 11 runtime in command line and IDE can help it out.

Fix the deprecated method from`compile` to `implementation` of Gradle.

**Comment by utzcoz** [comment]
@ZSmallX could you help send a PR for it?

**Comment by ZSmallX** [comment]
> @ZSmallX could you help send a PR for it?

Yes, I'm so glad to do that. I will try to figure it out and solve this in my spare time.

**Comment by ZSmallX** [comment]
Note that robolectric master uses AGP 7.x for project building, while IDE support for AGP 7.x only available in Android Studio BumbleBee.

See Android Studio release note in stable channel:
https://android-developers.googleblog.com/2022/01/android-studio-bumblebee-202111-stable.html

In lower version of Android Studio, like Android Studio Arctic Fox, the Gradle Sync can not work for IDE version check in Gradle Plugin.

Look like this:
With hint:

`The version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.`

![gQ1bDJ6ibs](https://user-images.githubusercontent.com/14019790/151115475-f09c22e8-c8c9-4d24-aeeb-70b71def3a2c.png)

The minimum Intellij IDEA version that supports AGP 7.x need more investigation.

**Comment by ZSmallX** [comment]
Investigation:

Note that the latest stable version of Android Studio still have some problem with AGP 7.1.0 as robolectric uses.

```
Android Studio Bumblebee | 2021.1.1
Build #AI-211.7628.21.2111.8092744, built on January 19, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry: external.system.auto.import.disabled=true, gradle.tooling.custom.serializer=false
```

The IDEA log looks like it's a problem with the Gradle Tooling API error:
```
2022-01-26 15:03:45,518 [ 156054]   WARN - e.project.sync.GradleSyncState - Unsupported method: IdeaContentRoot.getGeneratedSourceDirectories().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. 
com.intellij.openapi.externalSystem.model.ExternalSystemException: Unsupported method: IdeaContentRoot.getGeneratedSourceDirectories().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionErrorHandler.createUserFriendlyError(GradleExecutionErrorHandler.java:153)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectImportErrorHandler.createUserFriendlyError(AbstractProjectImportErrorHandler.java:46)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.doGetUserFriendlyError(BaseProjectImportErrorHandler.java:167)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.getUserFriendlyError(BaseProjectImportErrorHandler.java:48)
	at org.jetbrains.plugins.gradle.service.project.BaseProjectImportErrorHandler.checkErrorsWithoutQuickFixes(BaseProjectImportErrorHandler.java:62)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$1.getUserFriendlyError(GradleProjectResolver.java:832)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:779)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:751)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.lambda$execute$0(GradleExecutionHelper.java:119)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.maybeApplyUserDirWorkaround(GradleExecutionHelper.java:141)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.lambda$execute$1(GradleExecutionHelper.java:119)
	at org.jetbrains.plugins.gradle.GradleConnectorService$Companion.withGradleConnection(GradleConnectorService.kt:178)
	at org.jetbrains.plugins.gradle.GradleConnectorService.withGradleConnection(GradleConnectorService.kt)
	at org.jetbrains.plugins.gradle.service.execution.GradleExecutionHelper.execute(GradleExecutionHelper.java:115)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:145)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.resolveProjectInfo(GradleProjectResolver.java:67)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.lambda$resolveProjectInfo$0(RemoteExternalSystemProjectResolverImpl.java:37)
	at com.intellij.openapi.externalSystem.service.remote.AbstractRemoteExternalSystemService.execute(AbstractRemoteExternalSystemService.java:43)
	at com.intellij.openapi.externalSystem.service.remote.RemoteExternalSystemProjectResolverImpl.resolveProjectInfo(RemoteExternalSystemProjectResolverImpl.java:36)
	at com.intellij.openapi.externalSystem.service.remote.wrapper.ExternalSystemProjectResolverWrapper.resolveProjectInfo(ExternalSystemProjectResolverWrapper.java:48)
	at com.intellij.openapi.externalSystem.service.internal.ExternalSystemResolveProjectTask.doExecute(ExternalSystemResolveProjectTask.java:115)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:151)
	at com.intellij.openapi.externalSystem.service.internal.AbstractExternalSystemTask.execute(AbstractExternalSystemTask.java:135)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.executeImpl(ExternalSystemUtil.java:569)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.lambda$execute$1(ExternalSystemUtil.java:397)
	at com.intellij.openapi.project.DumbServiceHeavyActivities.suspendIndexingAndRun(DumbServiceHeavyActivities.java:21)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:189)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:397)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: IdeaContentRoot.getGeneratedSourceDirectories().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
	at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:33)
	at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:435)
	at com.sun.proxy.$Proxy254.getGeneratedSourceDirectories(Unknown Source)
	at com.android.tools.idea.gradle.model.java.JavaModuleContentRoot.copy(JavaModuleContentRoot.java:53)
	at com.android.tools.idea.gradle.project.model.IdeaJavaModuleModelFactory.getContentRoots(IdeaJavaModuleModelFactory.java:103)
	at com.android.tools.idea.gradle.project.model.IdeaJavaModuleModelFactory.create(IdeaJavaModuleModelFactory.java:70)
	at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.createJavaModuleModel(AndroidGradleProjectResolver.java:444)
	at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.createAndAttachModelsToDataNode(AndroidGradleProjectResolver.java:389)
	at com.android.tools.idea.gradle.project.sync.idea.AndroidGradleProjectResolver.createModule(AndroidGradleProjectResolver.java:257)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.kotlin.android.configure.KotlinAndroidMPPGradleProjectResolver.createModule(KotlinAndroidMPPGradleProjectResolver.kt:38)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.AbstractProjectResolverExtension.createModule(AbstractProjectResolverExtension.java:80)
	at org.jetbrains.plugins.gradle.service.project.TracedProjectResolverExtension.createModule(TracedProjectResolverExtension.java:37)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.convertData(GradleProjectResolver.java:374)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.doResolveProjectInfo(GradleProjectResolver.java:303)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver$ProjectConnectionDataNodeFunction.fun(GradleProjectResolver.java:768)
	... 39 more
```

Since there is no new updates from stable or beta channel, I'm not gonna to try the dev or canary channel.

And the IDEA stable channel has no updates for AGP 7.1.0, too.

Anyway the command line should be the most popular way to build robolectric, we can wait for updates from IDE side.

**Comment by hoisie** [comment]
Yeah this is not a great developer experience for potential contributors :( Sorry about that. 

At work I develop Robolectric using an Android Studio with Bazel/Blaze plugin, not gradle, so I do not run into these types of issues :(

I generally use the command-line + vim when working with the Robolectric gradle build, but then you can't really use step by step debugging.

**Comment by ZSmallX** [comment]
I'm trying to add JDK11 as one of the prerequisites for project building, in both command line and IDE way.

@utzcoz @hoisie please help and check if JDK11 is the recommended or the minimum version which robolectric building supports.

Here's my PR.

#7009

**Comment by ZSmallX** [comment]
> Yeah this is not a great developer experience for potential contributors :( Sorry about that.
> 
> At work I develop Robolectric using an Android Studio with Bazel/Blaze plugin, not gradle, so I do not run into these types of issues :(
> 
> I generally use the command-line + vim when working with the Robolectric gradle build, but then you can't really use step by step debugging.

Yeah, it's OK.
I hope I can help improving this by the way.

And had already submit this issue to Android Studio:   
https://issuetracker.google.com/issues/216325970

But IDEA not yet, Android Studio is good enough.
