### ISSUE TITLE
java.util.jar.JarException: 

### ISSUE THREAD

**Issue by ck1703** [robolectric/robolectric#7020]
I am building application for Android 12 . I am using jdk11. i am seeing below error

```
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger] 
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger] com.example.test.WrongFlavor > test FAILED
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger]     java.lang.RuntimeException: java.security.NoSuchProviderException: JCE cannot authenticate the provider AndroidKeyStore
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger]         at com.example.MasterKeyMaker.generate(MasterKeyMaker.java:36)
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger]         at com.example.testApp.onCreate(testApp.java:250)
2022-01-31T11:21:23.188+0530 [DEBUG] [TestEventLogger]         at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$2(AndroidTestEnvironment.java:350)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:350)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         at java.base/java.lang.Thread.run(Thread.java:844)
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger] 
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         Caused by:
2022-01-31T11:21:23.189+0530 [DEBUG] [TestEventLogger]         java.security.NoSuchProviderException: JCE cannot authenticate the provider AndroidKeyStore
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at java.base/javax.crypto.KeyGenerator.getInstance(KeyGenerator.java:287)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at androidx.security.crypto.MasterKeys.generateKey(MasterKeys.java:138)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at androidx.security.crypto.MasterKeys.getOrCreate(MasterKeys.java:97)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at androidx.security.crypto.MasterKey$Builder.buildOnM(MasterKey.java:357)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at androidx.security.crypto.MasterKey$Builder.build(MasterKey.java:314)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             at com.example.MasterKeyMaker.generate(MasterKeyMaker.java:32)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             ... 17 more
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger] 
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             Caused by:
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]             java.util.jar.JarException: file:/home/test/.gradle/caches/transforms-3/821a0b8a1ea9354ee931579bc0076f95/transformed/jetified-fake-keystore-2.0.1-runtime.jar is not signed.
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:433)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:215)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:127)
2022-01-31T11:21:23.190+0530 [DEBUG] [TestEventLogger]                 ... 23 more
```

 java.security.NoSuchProviderException: i am using bouncyCastle

**Comment by hoisie** [comment]
@ck1703 please follow https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues

The way these issues are reported of are not actionable.

More generally, the Robolectric issues page is not a general support forum for Android testing questions. The `fake-keystore-2.0.1` is a third party library and we cannot provide debugging support for that project.

If you can reduce the problem into something that only involves the Android platform (no arbitrary third-party libraries), and provide a clear repro case with instructions, I'd be happy to reopen this issue.
