### ISSUE TITLE
org.robolectric.shadows.httpclient.ShadowDefaultRequestDirectorTest failed on macOS

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7205]
### Description

```
org.robolectric.shadows.httpclient.ShadowDefaultRequestDirectorTest > shouldSupportRealHttpRequests FAILED
    java.lang.AssertionError: expected java.io.IOException to be thrown, but nothing was thrown
        at org.junit.Assert.assertThrows(Assert.java:1028)
        at org.junit.Assert.assertThrows(Assert.java:981)
        at org.robolectric.shadows.httpclient.ShadowDefaultRequestDirectorTest.shouldSupportRealHttpRequests(ShadowDefaultRequestDirectorTest.java:399)

53 tests completed, 1 failed
```

I don't know whether it is related to M1 or not before investigating into it.

### Steps to Reproduce

Run `./gradlew :shadows:httpclient:test`.

### Robolectric & Android Version

Robolectric latest master branch.

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by utzcoz** [comment]
This test failed because I setup some network config locally, and it will pass if I remove those network configs on my development machine.
