### ISSUE TITLE
It does not well adapt supporting type RES_TABLE_LIBRARY_TYPE .

### ISSUE THREAD

**Issue by cheers-huang** [robolectric/robolectric#7308]
### Description
I add another resouce apk which contain type RES_TABLE_LIBRARY_TYPE = 0x0203 with packageId=0x2.
When I load this apk, it will crash with java.lang.NullPointerException.
### Steps to Reproduce
Resource apk(example-res.apk) contain type RES_TABLE_LIBRARY_TYPE with packageId=0x2
CppApkAssets cppApkAssets = CppApkAssets.Load("example-res.apk", true);
exception is following:
java.lang.NullPointerException
	at org.robolectric.res.android.LoadedArsc$LoadedPackage.Load(LoadedArsc.java:728)
	at org.robolectric.res.android.LoadedArsc.LoadTable(LoadedArsc.java:911)
	at org.robolectric.res.android.LoadedArsc.Load(LoadedArsc.java:957)
	at org.robolectric.res.android.CppApkAssets.LoadImpl_measured(CppApkAssets.java:266)
	at org.robolectric.res.android.CppApkAssets.lambda$LoadImpl$0(CppApkAssets.java:205)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.res.android.CppApkAssets.LoadImpl(CppApkAssets.java:202)
	at org.robolectric.res.android.CppApkAssets.Load(CppApkAssets.java:117)

Check the code: resources/src/main/java/org/robolectric/res/android/LoadedArsc.java:728. 
It does not well adapt supporting type RES_TABLE_LIBRARY_TYPE .

### Robolectric & Android Version
V 4.7.3

**Comment by utzcoz** [comment]
@cheers-huang Could you attach a reproduceable-demo by following https://github.com/robolectric/robolectric/wiki/How-to-Report-Issues?

**Comment by utzcoz** [comment]
@cheers-huang Please attach the reproducable app for this issue and reopen it again. Before that, I decide to close this issue first.
