### ISSUE TITLE
Room unit test fails on M1 but passes on Intel Macbook / CI

### ISSUE THREAD

**Issue by JosephRoskopf** [robolectric/robolectric#7408]
### Description

I have created a sample project with a unit test around Room migrations that fails on a M1 machine, but passes on my Intel laptop.

We first noticed this on our team when a PR was merged in that started to fail locally for our developers with M1 machines. 

| Intel | M1 |
| - | - |
|<img width="588" alt="Screen Shot 2022-06-18 at 3 48 13 PM" src="https://user-images.githubusercontent.com/86580192/174456745-72860808-c5f8-4473-a313-bee95cea9094.png">|<img width="683" alt="Screen Shot 2022-06-18 at 3 48 42 PM" src="https://user-images.githubusercontent.com/86580192/174456757-c5e346a5-6868-4b64-9387-1df81114a8f8.png">|

This happens both when the tests are run via AS and when run via the `testDebugUnitTest` gradle task.

The test failure / output on the M1 is:

```
Migration didn't properly handle: task_events(com.example.roomtestfailure.room.TaskEntity).
 Expected:
TableInfo{name='task_events', columns={secondIndexId=Column{name='secondIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, firstIndexId=Column{name='firstIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}}, foreignKeys=[], indices=[Index{name='index_task_events_firstIndexId_secondIndexId', unique=true, columns=[firstIndexId, secondIndexId], orders=[ASC, ASC]}]}
 Found:
TableInfo{name='task_events', columns={firstIndexId=Column{name='firstIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, secondIndexId=Column{name='secondIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
java.lang.IllegalStateException: Migration didn't properly handle: task_events(com.example.roomtestfailure.room.TaskEntity).
 Expected:
TableInfo{name='task_events', columns={secondIndexId=Column{name='secondIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, firstIndexId=Column{name='firstIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}}, foreignKeys=[], indices=[Index{name='index_task_events_firstIndexId_secondIndexId', unique=true, columns=[firstIndexId, secondIndexId], orders=[ASC, ASC]}]}
 Found:
TableInfo{name='task_events', columns={firstIndexId=Column{name='firstIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, id=Column{name='id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, secondIndexId=Column{name='secondIndexId', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[]}
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:103)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:183)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at com.example.roomtestfailure.MigrationTest.thisTestFails(MigrationTest.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Where the difference is in the indices between what it found and what it expected.

In the sample project, adding the sql statement to the 1->2 migration in `ExampleDatabase.kt` fixes the problem:

```kotlin
                database.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS index_task_events_firstIndexId_secondIndexId ON task_events (firstIndexId,secondIndexId)"
                )
```

Which makes sense to me, but I'm not sure why the test would pass on Intel machines. 

### Steps to Reproduce

Clone this project: https://github.com/JosephRoskopf/RoomRobolectricTestFailure

run the unit test located in `app/src/test/java/com.example.roomtestfailure.MigrationTest`

### Robolectric & Android Version

Robolectric version: 4.7.3

### Link to a public git repo demonstrating the problem:

https://github.com/JosephRoskopf/RoomRobolectricTestFailure

**Comment by JosephRoskopf** [comment]
I also tried the sample project with the latest Robolectric version (4.8.1) and the issue still persists.

**Comment by utzcoz** [comment]
@JosephRoskopf The failure reason is the validation for your new table `task_events` failed, because of your created table by SQL sequences in your migration method doesn't include indexes defined in your `TaskEntity`. You can append next SQL sequences in your migration method and the test will pass:

```
database.execSQL(
     "CREATE UNIQUE INDEX IF NOT EXISTS index_task_events_firstIndexId_secondIndexId " +
         "ON task_events(firstIndexId, secondIndexId)"
 )
```

I have tested it on M1 machine with command `./gradlew testDebug`(Looks like you don't setup room schema directory for release variant).

If you have test it on Intel macOS, and it passed, it maybe caused by room or its sqlite implementation/dependency for room-testing. IMO, I don't think it is related to Robolectric.

I will close this issue, and feel free to reopen it if you have other questions.

**Comment by JosephRoskopf** [comment]
@utzcoz Hey! that totally makes sense. I agree the M1 behavior is what I'd expect given the room migration isn't adding the key as defined in the entity. However, I thought this was a Robolectric issue because once Robolectric is taken out of the equation, the behavior no longer exists.

On the most recent commit of that sample project (https://github.com/JosephRoskopf/RoomRobolectricTestFailure/commit/b48adf0aad27c72ab4265099ce9f5f3d66a328f4) Robolectric is removed from the project and the test in question is moved to `androidTest` and when that test is run on a real device, it fails on both my intel and M1 machine.

If you check out the initial commit before that (https://github.com/JosephRoskopf/RoomRobolectricTestFailure/commit/e61d449f5496bc70fb7bfde2d67c9484174081dd) where Robolectric is added to the project and the test lives in the `test` folder, we see the original behavior of failing on M1 but passing on intel.

**Comment by utzcoz** [comment]
> On the most recent commit of that sample project (https://github.com/JosephRoskopf/RoomRobolectricTestFailure/commit/b48adf0aad27c72ab4265099ce9f5f3d66a328f4) Robolectric is removed from the project and the test in question is moved to androidTest and when that test is run on a real device, it fails on both my intel and M1 machine.

It fails maybe because of your test is not correct, and can't be run on real device, it is not related your M1 or intel  device, and it is only related to the Emulator you run.

 > If you check out the initial commit before that (https://github.com/JosephRoskopf/RoomRobolectricTestFailure/commit/e61d449f5496bc70fb7bfde2d67c9484174081dd) where Robolectric is added to the project and the test lives in the test folder, we see the original behavior of failing on M1 but passing on intel.

The failure on M1 maybe because of the sqlite implementation/faker that room-testing depends on has a different behavior on M1 than intel device. Actually, the in-memory database implementation for sqlite(sqlite4java) used by Robolectric can't run M1 machine, and we only can run native SQLite mode on M1 machine.  You can try `SQLiteMode.LEGACY` and `SQLiteMode.NTAIVE` for your tests to check different sqlite implementation behavior of Robolectric. IMO the failure of your test is related to room part, at least I don't find directly relationship with Roboletric from log and your tests. If you can find the relationship between them, I can continue to investigate this problem.

**Comment by JosephRoskopf** [comment]
I agree the overall behavior of the app / test is not correct, but I'd expect the results of running the test (via instrumentation test) on a real device without Robolectric to be the same as the results of running the test (via unit test) on my laptops with Robolectric. I definitely don't have a great understanding of how Robolectric + Room are interacting in this scenario, but I am also unsure of where else the issue could be.

When I annotate my test on the intel machine with `@SQLiteMode(SQLiteMode.Mode.LEGACY)`, it still passes as expected. But when I annotate with the test with `@SQLiteMode(SQLiteMode.Mode.NATIVE)`, it fails with the stack trace I'd expect (the same one as when run without any annotation on the M1 machine). Does that shed any more insight into where the issue might be?

**Comment by utzcoz** [comment]
@JosephRoskopf Could you run it on M1 with different `SQLiteMode`? If there are exception stack(not the same validation error we have observe d before ), you can post it here.

**Comment by JosephRoskopf** [comment]
@utzcoz running the test on my M1 with `LEGACY` yields the following error:

```
com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib: dlopen(/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
java.lang.RuntimeException: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib: dlopen(/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at org.robolectric.shadows.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:92)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:55)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:70)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:83)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:752)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:373)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at androidx.room.testing.MigrationTestHelper.openDatabase(MigrationTestHelper.java:410)
	at androidx.room.testing.MigrationTestHelper.createDatabase(MigrationTestHelper.java:266)
	at com.example.roomtestfailure.MigrationTest.thisTestFails(MigrationTest.kt:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.almworks.sqlite4java.SQLiteException: [-91] cannot load library: java.lang.UnsatisfiedLinkError: /private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib: dlopen(/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at app//com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:97)
	at app//com.almworks.sqlite4java.SQLite.getSQLiteVersion(SQLite.java:114)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.loadFromDirectory(SQLiteLibraryLoader.java:90)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.doLoad(SQLiteLibraryLoader.java:55)
	at org.robolectric.shadows.util.SQLiteLibraryLoader.load(SQLiteLibraryLoader.java:39)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:70)
	at org.robolectric.shadows.ShadowLegacySQLiteConnection.nativeOpen(ShadowLegacySQLiteConnection.java:83)
	at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$open(SQLiteConnection.java:205)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java)
	at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
	at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openInner(SQLiteDatabase.java:919)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$open(SQLiteDatabase.java:899)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openDatabase(SQLiteDatabase.java:763)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openDatabase(SQLiteDatabase.java:752)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getDatabaseLocked(SQLiteOpenHelper.java:373)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
	at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getWritableDatabase(SQLiteOpenHelper.java:316)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at androidx.room.testing.MigrationTestHelper.openDatabase(MigrationTestHelper.java:410)
	at androidx.room.testing.MigrationTestHelper.createDatabase(MigrationTestHelper.java:266)
	at com.example.roomtestfailure.MigrationTest.thisTestFails(MigrationTest.kt:47)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.12/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.12/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.12/java.lang.reflect.Method.invoke(Method.java:566)
	... 14 more
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib: dlopen(/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib, 0x0001): tried: '/private/var/folders/sk/vzqpxpr950171hdcpdy5cz400000gp/T/1655645126700-0/libsqlite4java.dylib' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.almworks.sqlite4java.Internal.tryLoadFromPath(Internal.java:340)
	at com.almworks.sqlite4java.Internal.loadLibraryX(Internal.java:110)
	at com.almworks.sqlite4java.SQLite.loadLibrary(SQLite.java:95)
	... 52 more
```

Running with the `NATIVE` mode provides the same validation error we have observed before

**Comment by utzcoz** [comment]
@JosephRoskopf Looks like Robolectric uses `NATIVE` mode on M1 default(https://github.com/robolectric/robolectric/commit/4043d1969ed116dde49490cebf37a40dfa9307b3), and `NATIVE` mode causes your test failed. Thanks for testing, I will investigate it with your demo. It's recommended to add explicit index command for your room migration as a workaround before this problem fixed and released.

**Comment by JosephRoskopf** [comment]
It is definitely appreciated! Thank you again for the help. Please let me know if there is anything else I can help with

**Comment by hoisie** [comment]
I vaguely recall seeing this issue once when migrating tests at Google to use mat ve SQLite. Its possible that it's a bug in Room itself. Room may have some Robolectric specific logic that may depend on legacy SQLite.

**Comment by utzcoz** [comment]
@hoisie Some room core libraries, like `androidx.room:room-compiler`, depends on `org.xerial:sqlite-jdbc` which is forked from `com.almworks.sqlite4java` that Robolectric uses for legacy SQLite supporting.

**Comment by utzcoz** [comment]
In `LEGACY` mode, the room will generate null indices because it can't get column index of `origin`. And room's `TableInfo#equals` will returns true when validation with `talbeInfo.indices == null`:

```
        if (indices == null || tableInfo.indices == null) {
            // if one us is missing index information, seems like we couldn't acquire the
            // information so we better skip.
            return true;
        }
```

But in `NATIVE` mode, the room can generate `origin` column index and generate valid indices, and above `equals` will return false when validation, and it causes the failure exception we have saw at the top.

**Comment by hoisie** [comment]
We should probably default to native sqlite everywhere we can. It won't work on Windows for now, though, but I think that tradeoff is worth it.

**Comment by utzcoz** [comment]
> I vaguely recall seeing this issue once when migrating tests at Google to use native SQLite. Its possible that it's a bug in Room itself. Room may have some Robolectric specific logic that may depend on legacy SQLite.

Could we contact Room team to discuss this problem?

> We should probably default to native sqlite everywhere we can. It won't work on Windows for now, though, but I think that tradeoff is worth it.

We can enable native SQLite for Linux at next step, and keep Windows with LEGACY mode. We also can document it at robolectric.org.

**Comment by MGaetan89** [comment]
Native SQLite is the default for Linux/Mac since Roboelctric 4.9 (https://github.com/robolectric/robolectric/commit/f723f8aefb9029b8606c895a0548d78aedc6c92a), it is supported on Windows since Robolectric 4.12 (https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12), and will be the default for all platforms in Robolectric 4.15 (https://github.com/robolectric/robolectric/commit/f6faa783503397c7fc33935bb617900f54d9d749).

So probably this issue is now resolved and can be closed @hoisie @utzcoz?
