### ISSUE TITLE
Since Gradle 7.5, robolectric needs -add-opens options 

### ISSUE THREAD

**Issue by ganadist** [robolectric/robolectric#7456]
### Description
Since gradle 7.5 ( and Java 9+), jvm behavior of test runner was changed.
https://docs.gradle.org/7.5/userguide/upgrading_version_7.html#removes_implicit_add_opens_for_test_workers
```
Prior to Gradle 7.5, JDK modules java.base/java.util and java.base/java.lang were automatically opened
in test workers on JDK9+ by passing --add-opens CLI arguments.
This meant any tests were able to perform deep reflection on JDK internals 
without warning or failing. 
This caused tests to be unreliable by allowing code to pass when it would otherwise fail 
in a production environment.
```

On JVM 15 or lower version, test runner will just print  warnings.
But, on JVM 16 or higher version, test runner will failed by classloader

* Is it possible to add `--add-opens` jvm options automatically by robolectric test runner?
* Or this should be documented 
```
android {
  testOptions {
    unitTests.all {
        jvmArgs ["--add-opens=java.base/java.lang=ALL-UNNAMED", "--add-opens=java.base/java.util=ALL-UNNAMED"]
    }
  }
}
```

**Comment by hoisie** [comment]
What is the actual error message that happens if you try to run a Robolectric test in Gradle 7.5? Ideally Robolectric should not be doing any illegal reflective operation.

**Comment by ganadist** [comment]
> Ideally Robolectric should not be doing any illegal reflective operation.

AFAIK, `robolectric runner` is just another Android Runtime.

For example, `Method.setAccessible()` is Java API, but it is also public API of Android Platform.
So, target code of test can include `Method.setAccessible()`
IMHO, robolectric should be able to invoke `Method.setAccessible()` without additional setting.

**Comment by hoisie** [comment]
We should probably get ahead of this issue before users start to update to JDK 17. Currently if you try to run Robolectric tests with JDK 17, many things will not work, such as ShadowParcelFileDescriptor due to the use of reflection to access java.io internals:
https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowParcelFileDescriptor.java#L162

Maybe we should start running CI on JDK 17 to collect the access violations and then try to get AGP to add the necessary `--add-opens` flags.

**Comment by utzcoz** [comment]
@hoisie https://github.com/pinterest/ktlint/pull/1590/files is an example to add `--add-opens` for tests. We might add it, and then enable CI tests to catch compatibility problems.

**Comment by hoisie** [comment]
We can do it for Robolectric's test, but the issue is that end-users will hit this type of issue as well, and they will need to use add-opens, which can be confusing. Ideally AGP would add the necessary ones for Robolectric.

**Comment by utzcoz** [comment]
There are two articles that we can refer to: https://blogs.oracle.com/javamagazine/post/a-peek-into-java-17-continuing-the-drive-to-encapsulate-the-java-runtime-internals https://blogs.oracle.com/javamagazine/post/the-unsafe-class-unsafe-at-any-speed. @hoisie We might need to migrate our reflection code to `Unsafe` likes cashapp and powermock, examples provided by Zac at https://github.com/robolectric/robolectric/issues/7456#issuecomment-1252726608.

**Comment by hoisie** [comment]
@utzcoz Unsafe.staticFieldOffset is going away also. I would like to remove most of the code in [ReflectionHelpers.makeFieldVeryAccessible](https://github.com/robolectric/robolectric/blob/master/shadowapi/src/main/java/org/robolectric/util/ReflectionHelpers.java#L453-L465https://bugs.openjdk.org/browse/JDK-8277863). Robolectric should not be in the business of removing `final` using hacks. People who want to remove `final` should use some form of instrumentation, either Robolectric's, Powermock, or some custom agent-based instrumentation.

**Comment by utzcoz** [comment]
@ganadist Does 4.10 still need above `--add-opens`? Looks like there are many reflection code were been removed.

**Comment by ganadist** [comment]
@utzcoz 

Uhhh.
I didn't mention the robotics itself, but I did mention the application code.
As mentioned in https://github.com/robolectric/robolectric/issues/7456#issuecomment-1191001974, [reflect](https://developer.android.com/reference/java/lang/reflect/package-summary) package is a part of Android platform API.
And regardless of Java's behaviour, Android applications/libraries can call this API. 

So I think Robolectric environment would allow calls to `reflect` APIs by default.

**Comment by utzcoz** [comment]
> So I think Robolectric environment would allow calls to reflect APIs by default.

@ganadist I think it might be different than the real Android environment because of reflection restriction rules. In Android, there are many special rules like blacklist, whitelist, etc. Logically, you can use many tools to do reflections for some hidden but allowed APIs, but I recommend you to use Emulators or real phones to do these tests.

AFAIK, many Robolectric reflection APIs were removed, so I want to close this issue. @ZacSweers do you still face this issue in Slack with latest Robolectric?

**Comment by ganadist** [comment]
> @ganadist I think it might be different than the real Android environment because of reflection restriction rules. In Android, there are many special rules like blacklist, whitelist, etc. Logically, you can use many tools to do reflections for some hidden but allowed APIs, but I recommend you to use Emulators or real phones to do these tests.

The "reflect" API is not just used to access hidden Android System APIs.
But, also some well-known libraries are using `reflect` for their internal implementation such as
* [gson](https://github.com/search?q=repo%3Agoogle%2Fgson+path%3Agson%2Fsrc%2Fmain%2Fjava+%22java.lang.reflect%22&type=code)
* [retrofit](https://github.com/search?q=repo%3Asquare%2Fretrofit+path%3Aretrofit%2Fsrc%2Fmain%2Fjava+%22java.lang.reflect%22&type=code)

And I think that most developers want to use these libraries with robolectric without special settings.

**Comment by utzcoz** [comment]
> And I think that most developers want to use these libraries with robolectric without special settings.

If reflection APIs are used by third-party libraries like gson and retrofit, IMO it's their responsibility to highlight adding extra `-add-opens` configuration. For example, many applications start to use AGP 8.x, and it requires Gradle 8.x and JDK 17 what need applications to add extra `-add-opens` configuration if they have code/dependencies that use reflection APIs or APIs from non-core modules. From AGP 8.x, it will become a common configuration.

**Comment by francescocervone** [comment]
> AFAIK, many Robolectric reflection APIs were removed, so I want to close this issue. @ZacSweers do you still face this issue in Slack with latest Robolectric?

@utzcoz The issue still happens on Robolectric 4.11.1 if you just use a `ParcelFileDescriptor`, as already said in https://github.com/robolectric/robolectric/issues/7456#issuecomment-1251822296

For instance:

```kotlin
parcelFileDescriptor.use { }
```

causes the following stacktrace:
```java
Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @6a0aab20
java.lang.reflect.InaccessibleObjectException: Unable to make field private int java.io.FileDescriptor.fd accessible: module java.base does not "opens java.io" to unnamed module @6a0aab20
	at org.robolectric.interceptors.AndroidInterceptors$FileDescriptorInterceptor.moveField(AndroidInterceptors.java:79)
	at org.robolectric.interceptors.AndroidInterceptors$FileDescriptorInterceptor.release(AndroidInterceptors.java:111)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:304)
	at libcore.io.IoUtils.close(IoUtils.java:180)
	at libcore.io.IoUtils.closeQuietly(IoUtils.java:214)
	at android.os.ParcelFileDescriptor.closeWithStatus(ParcelFileDescriptor.java:826)
	at android.os.ParcelFileDescriptor.close(ParcelFileDescriptor.java:792)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowParcelFileDescriptor$ParcelFileDescriptorReflector$$Reflector14.close(Unknown Source)
	at org.robolectric.shadows.ShadowParcelFileDescriptor.close(ShadowParcelFileDescriptor.java:266)
	at android.os.ParcelFileDescriptor.close(ParcelFileDescriptor.java)
	at kotlin.io.CloseableKt.closeFinally(Closeable.kt:56)
        ...
```

**Comment by Xinkle** [comment]
I couldn't understand the entire conversation, but at least I resolved an issue with `ParcelFileDescriptor` by adding the option "--add-opens=java.base/java.io=ALL-UNNAMED"

**Comment by francescocervone** [comment]
@utzcoz yeah, thanks. We worked around the issue exactly like that back then, as written also in the issue opening comment.
