### ISSUE TITLE
measureLimit (11) is out of start (0) and limit (0) bounds java.lang.IndexOutOfBoundsException: measureLimit (11) is out of start (0) and limit (0) bounds

### ISSUE THREAD

**Issue by eliascoelho911** [robolectric/robolectric#7461]
### Description
Hi!

I'm getting the following exception when I try to run a test with an interface with compose (note: when I run the same test on a device, it passes normally)

```
measureLimit (11) is out of start (0) and limit (0) bounds
java.lang.IndexOutOfBoundsException: measureLimit (11) is out of start (0) and limit (0) bounds
	at android.text.TextLine.handleRun(TextLine.java:1106)
	at android.text.TextLine.measureRun(TextLine.java:528)
	at android.text.TextLine.measure(TextLine.java:326)
	at android.text.Layout.getHorizontal(Layout.java:1184)
	at android.text.Layout.getHorizontal(Layout.java:1162)
	at android.text.Layout.getPrimaryHorizontal(Layout.java:1133)
	at android.text.Layout.getPrimaryHorizontal(Layout.java:1123)
	at androidx.compose.ui.text.android.LayoutHelper.getDownstreamHorizontal(LayoutHelper.kt:344)
	at androidx.compose.ui.text.android.LayoutHelper.getHorizontalPosition(LayoutHelper.kt:226)
	at androidx.compose.ui.text.android.TextLayout.getPrimaryHorizontal(TextLayout.kt:330)
	at androidx.compose.ui.text.android.TextLayout.getPrimaryHorizontal$default(TextLayout.kt:329)
	at androidx.compose.ui.text.platform.AndroidParagraph.getCursorRect(AndroidParagraph.android.kt:328)
	at androidx.compose.ui.text.MultiParagraph.getCursorRect(MultiParagraph.kt:613)
	at androidx.compose.ui.text.TextLayoutResult.getCursorRect(TextLayoutResult.kt:529)
	at androidx.compose.foundation.text.TextFieldScrollKt.getCursorRectInScroller(TextFieldScroll.kt:207)
	at androidx.compose.foundation.text.TextFieldScrollKt.access$getCursorRectInScroller(TextFieldScroll.kt:1)
	at androidx.compose.foundation.text.HorizontalScrollLayoutModifier$measure$1.invoke(TextFieldScroll.kt:179)
	at androidx.compose.foundation.text.HorizontalScrollLayoutModifier$measure$1.invoke(TextFieldScroll.kt:178)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer(Placeable.kt:393)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeWithLayer$default(Placeable.kt:266)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:407)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier$measure$1.invoke(GraphicsLayerModifier.kt:406)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative(Placeable.kt:359)
	at androidx.compose.ui.layout.Placeable$PlacementScope.placeRelative$default(Placeable.kt:179)
	at androidx.compose.foundation.layout.SizeModifier$measure$1.invoke(Size.kt:783)
	at androidx.compose.foundation.layout.SizeModifier$measure$1.invoke(Size.kt:782)
	at androidx.compose.ui.layout.MeasureScope$layout$1.placeChildren(MeasureScope.kt:70)
	at androidx.compose.ui.node.ModifiedLayoutNode.placeAt-f8xVGno(ModifiedLayoutNode.kt:101)
	at androidx.compose.ui.layout.Placeable.access$placeAt-f8xVGno(Placeable.kt:31)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50(Placeable.kt:370)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:161)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.access$placeOuterWrapper-f8xVGno(OuterMeasurablePlaceable.kt:28)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:149)
	at androidx.compose.ui.node.OuterMeasurablePlaceable$placeAt$1.invoke(OuterMeasurablePlaceable.kt:148)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeLayoutModifierSnapshotReads$ui_release(OwnerSnapshotObserver.kt:59)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.placeAt-f8xVGno(OuterMeasurablePlaceable.kt:148)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.replace(OuterMeasurablePlaceable.kt:173)
	at androidx.compose.ui.node.LayoutNode.replace$ui_release(LayoutNode.kt:826)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:280)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.kt:317)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.kt:325)
	at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(AndroidComposeView.android.kt:773)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:106)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1366)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:115)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.foundation.layout.UnspecifiedConstraintsModifier.measure-3p2s80s(Size.kt:979)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.PaddingModifier.measure-3p2s80s(Padding.kt:364)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.FillModifier.measure-3p2s80s(Size.kt:658)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1428)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1427)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1427)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1366)
	at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.measure-3p2s80s(RowColumnImpl.kt:89)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.foundation.ScrollingLayoutModifier.measure-3p2s80s(Scroll.kt:345)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:405)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:417)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1428)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1427)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1427)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1381)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1372)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:187)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:274)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.kt:317)
	at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(AndroidComposeView.android.kt:773)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:106)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.measure-BRTryo0(OuterMeasurablePlaceable.kt:75)
	at androidx.compose.ui.node.LayoutNode.measure-BRTryo0(LayoutNode.kt:1366)
	at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:115)
	at androidx.compose.ui.node.InnerPlaceable.measure-BRTryo0(InnerPlaceable.kt:44)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:405)
	at androidx.compose.ui.node.ModifiedLayoutNode.measure-BRTryo0(ModifiedLayoutNode.kt:53)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1428)
	at androidx.compose.ui.node.LayoutNode$performMeasure$1.invoke(LayoutNode.kt:1427)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2101)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:110)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:78)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:66)
	at androidx.compose.ui.node.LayoutNode.performMeasure-BRTryo0$ui_release(LayoutNode.kt:1427)
	at androidx.compose.ui.node.OuterMeasurablePlaceable.remeasure-BRTryo0(OuterMeasurablePlaceable.kt:94)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1381)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1372)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:187)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:274)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:38)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:208)
	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(AndroidComposeView.android.kt:806)
	at android.view.View.measure(View.java:23169)
	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(ComposeView.android.kt:298)
	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(ComposeView.android.kt:285)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:461)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:716)
	at android.view.View.measure(View.java:23169)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1572)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1855)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowChoreographer$ChoreographerReflector$$Reflector31.doFrame(Unknown Source)
	at org.robolectric.shadows.ShadowChoreographer.lambda$doFrame$0(ShadowChoreographer.java:93)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.shadows.ShadowChoreographer.doFrame(ShadowChoreographer.java:93)
	at android.view.Choreographer.doFrame(Choreographer.java)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
	at org.robolectric.android.internal.LocalControlledLooper.drainMainThreadUntilIdle(LocalControlledLooper.java:18)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:29)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:21)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:97)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.waitForIdle(AndroidComposeTestRule.android.kt:284)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.access$waitForIdle(AndroidComposeTestRule.android.kt:150)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidTestOwner.getRoots(AndroidComposeTestRule.android.kt:476)
	at androidx.compose.ui.test.TestContext.getAllSemanticsNodes$ui_test_release(TestOwner.kt:95)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNodes$ui_test_release(SemanticsNodeInteraction.kt:79)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
	at androidx.compose.ui.test.SemanticsNodeInteraction.fetchSemanticsNode(SemanticsNodeInteraction.kt:96)
	at androidx.compose.ui.test.TextActionsKt.sendTextInputCommand(TextActions.kt:101)
	at androidx.compose.ui.test.TextActionsKt.performTextInput(TextActions.kt:40)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenRobot$enterEmail$1.invoke(LoginScreenRobot.kt:30)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenRobot$enterEmail$1.invoke(LoginScreenRobot.kt:29)
	at com.github.eliascoelho911.bluetaxi.commons.test.BaseRobotScreen.withRule(BaseRobotScreen.kt:13)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenRobot.enterEmail(LoginScreenRobot.kt:29)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenTest$givenInvalidEmailAndAnyPassword_whenTryToLogin_shouldDisplayInvalidEmailAlertAndDisableLogin$1$1.invoke(LoginScreenTest.kt:35)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenTest$givenInvalidEmailAndAnyPassword_whenTryToLogin_shouldDisplayInvalidEmailAlertAndDisableLogin$1$1.invoke(LoginScreenTest.kt:33)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenRobotKt.loginScreenRobot(LoginScreenRobot.kt:22)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenTest$givenInvalidEmailAndAnyPassword_whenTryToLogin_shouldDisplayInvalidEmailAlertAndDisableLogin$1.invoke(LoginScreenTest.kt:33)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenTest$givenInvalidEmailAndAnyPassword_whenTryToLogin_shouldDisplayInvalidEmailAlertAndDisableLogin$1.invoke(LoginScreenTest.kt:23)
	at com.github.eliascoelho911.bluetaxi.commons.test.BaseComposableTest.composableTest(BaseComposableTest.kt:18)
	at com.github.eliascoelho911.bluetaxi.auth.ui.login.LoginScreenTest.givenInvalidEmailAndAnyPassword_whenTryToLogin_shouldDisplayInvalidEmailAlertAndDisableLogin(LoginScreenTest.kt:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$AndroidComposeStatement.evaluate(AndroidComposeTestRule.android.kt:337)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$TextInputServiceStatement.evaluate(AndroidComposeTestRule.android.kt:417)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$ComposeIdlingResourceStatement.evaluate(AndroidComposeTestRule.android.kt:402)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$RecomposerStatement.evaluateWithWindowRecomposer(AndroidComposeTestRule.android.kt:374)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$RecomposerStatement.evaluate(AndroidComposeTestRule.android.kt:364)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$CleanupCoroutinesStatement.evaluate(AndroidComposeTestRule.android.kt:388)
	at androidx.compose.ui.test.junit4.IdlingResourceRegistry$getStatementFor$1.evaluate(IdlingResourceRegistry.jvm.kt:160)
	at androidx.compose.ui.test.junit4.ComposeRootRegistry$getStatementFor$1.evaluate(ComposeRootRegistry.android.kt:149)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Steps to Reproduce
```
fun test() {
    //using onNode to fetch a TextField
    onNodeWithText("Email").performTextInput("email@email.com")
    onNodeWithText("Password").performTextInput("123456")
}
```

### Robolectric & Android Version

- Robolectric : 4.8.1
- Compose: 1.1.1
- JDK 11

### Link to a public git repo demonstrating the problem:
https://github.com/eliascoelho911/BlueTaxi/blob/master/auth/src/test/java/com/github/eliascoelho911/bluetaxi/auth/ui/login/LoginScreenTest.kt

**Comment by hoisie** [comment]
`android.text.TextLine` seems to use `TextPaint`, which extends `Paint`, and this is all implemented in native code using Skia + Minikin + Harfbuzz I believe.

We may be able to improve the simulation here to not crash at least.

At the moment native graphics is not supported in Robolectric, but this is something we have been experimenting with a lot with recently.

**Comment by eliascoelho911** [comment]
OK, thanks for clarifying. Is there anything I can do at the moment or will I have to test on the device myself?

**Comment by hoisie** [comment]
cc @jfresen

**Comment by hoisie** [comment]
This failure can be reduced down to this one-liner:
```java
  @Test
  @Config(sdk = 28)
  public void testStaticLayout() {
    StaticLayout.Builder.obtain("invalidEmail", 0, 12, new TextPaint(), 256)
        .build()
        .getPrimaryHorizontal(12);
  }
```

The error message is slightly different on newer SDK levels.

**Comment by vincent-paing** [comment]
I'm also facing same problem with executing `performTextInput` method. Have you found a workaround?

**Comment by eliascoelho911** [comment]
> This failure can be reduced down to this:
> 
> ```java
>   @Test
>   @Config(sdk = 28)
>   public void testStaticLayout() {
>     StaticLayout.Builder.obtain("invalidEmail", 0, 12, new TextPaint(), 256)
>         .build()
>         .getPrimaryHorizontal(12);
>   }
> ```
> 
> The error message is slightly different on newer SDK levels.

I'm not sure I understand exactly what it does. Does this code block populate the TextField?

**Comment by eliascoelho911** [comment]
> I'm also facing same problem with executing `performTextInput` method. Have you found a workaround?

Unfortunately not. Currently I'm doing all the tests on the emulator.

**Comment by hoisie** [comment]
This seems to be coming up a lot. We need to improve the simulation of LineBreaker/StaticLayout. The real implementation is in native code so the goal should be to simulate it enough to prevent crashes. I can try to take a stab at this.

**Comment by dazza5000** [comment]
thank you for all of your work @hoisie

I've updated to the latest release of Robolectric and still experience similar exceptions to the one in this issue - does anyone know if these changes have made it out into the wild?

**Comment by hoisie** [comment]
@dazza5000 if you are doing any kind of Compose testing with Robolectric, you should be using `@GraphicsMode(NATIVE)` or the system property `robolectric.graphicsMode=NATIVE`. Compose depends on a realistic Canvas, which native graphics provides.

**Comment by utzcoz** [comment]
Looks like `@GraphicsMode(NATIVE)` can help to fix this issue. And feel free to reopen this issue it native graphics mode doesn't work for this issue.

**Comment by alwa** [comment]
> Looks like `@GraphicsMode(NATIVE)` can help to fix this issue. And feel free to reopen this issue it native graphics mode doesn't work for this issue.

This is blocked by https://github.com/robolectric/robolectric/issues/8312 on Windows
