### ISSUE TITLE
RobolectricTestRunnerMultiApiTest causing massive amounts of noise in Gradle tests

### ISSUE THREAD

**Issue by hoisie** [robolectric/robolectric#7562]
`./gradlew :robolectric:test --tests='*RobolectricTestRunnerMultiApiTest*'`

`less ./robolectric/build/reports/tests/test/classes/org.robolectric.RobolectricTestRunnerMultiApiTest.html`

There are a lot of noisy log statements which make it impossible to read test output in GitHub CI.
```
java.lang.NumberFormatException: For input string: &quot;@drawable/ic_lockscreen_chevron_right&quot;
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at org.robolectric.res.ResType.inferFromValue(ResType.java:56)
        at org.robolectric.res.ResType.inferType(ResType.java:30)
        at org.robolectric.res.StaxArrayLoader$1.onEnd(StaxArrayLoader.java:29)
        at org.robolectric.res.StaxDocumentLoader.doParse(StaxDocumentLoader.java:68)
        at org.robolectric.res.StaxDocumentLoader.loadResourceXmlFile(StaxDocumentLoader.java:32)
        at org.robolectric.res.DocumentLoader.loadFile(DocumentLoader.java:41)
        at org.robolectric.res.DocumentLoader.load(DocumentLoader.java:20)
        at org.robolectric.res.ResourceTableFactory.parseResourceFiles(ResourceTableFactory.java:214)
        at org.robolectric.res.ResourceTableFactory.lambda$newFrameworkResourceTable$0(ResourceTableFactory.java:27)
        at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
        at org.robolectric.res.ResourceTableFactory.newFrameworkResourceTable(ResourceTableFactory.java:13)
        at org.robolectric.android.internal.AndroidTestEnvironment.getSystemResourceTable(AndroidTestEnvironment.java:413)
        at org.robolectric.android.internal.AndroidTestEnvironment.injectResourceStuffForLegacy(AndroidTestEnvironment.java:438)
        at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:384)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:377)
        at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
        at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:377)
        at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:274)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:246)
        at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
        at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:243)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
        at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:72)
        at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:211)
        at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:327)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:277)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by utzcoz** [comment]
@hoisie We can try-catch `ResType.inferFromValue` or upper calling chain to ignore this error with error-message only.

**Comment by hoisie** [comment]
I have a fix for this, sending a PR.
