### ISSUE TITLE
androidx.compose.ui.test.performScrollTo doesn't work if composable uses nested scrolling

### ISSUE THREAD

**Issue by alixwar** [robolectric/robolectric#7567]
### Description
I'm not sure if this should be reported to Google or if it should be reported here.

### Steps to Reproduce
I have a composable layout with buttons that are only accessible from tests if scrolling. 
After I converted my layout to use (works fine when deployed on a phone):

```
   modifier = Modifier
                .verticalScroll(scrollableState)
```

to

```
   modifier = Modifier
                .nestedScroll(scrollBehavior.nestedScrollConnection)
```

then the tests no longer work:

```
Semantic Node has no parent layout with a Scroll SemanticsAction
java.lang.AssertionError: Semantic Node has no parent layout with a Scroll SemanticsAction
	at androidx.compose.ui.test.ActionsKt.scrollToNode(Actions.kt:81)
	at androidx.compose.ui.test.ActionsKt.performScrollTo(Actions.kt:70)
```

### Robolectric & Android Version
- Robolectric 4.8.1
- Android version: (SDK config = 30)
- Compose version: 1.3.0-beta01
- Material3: 1.0.0-beta01

**Comment by alixwar** [comment]
Looks like this could be a red herring. Possibly my layout no longer needs scrolling in these cases because of UI adjustments... Closing this for now
