### ISSUE TITLE
java.lang.NoClassDefFoundError: libcore/util/EmptyArray on api 31

### ISSUE THREAD

**Issue by wijnanb** [robolectric/robolectric#7572]
### Description

We upgraded compileSdkVersion from 29 to 31.
Now creating a ApplicationInfo object will fail the unit test with this error:

```
libcore/util/EmptyArray
  java.lang.NoClassDefFoundError: libcore/util/EmptyArray
  at android.util.ArrayMap.<init>(ArrayMap.java:341)
  at android.util.ArrayMap.<init>(ArrayMap.java:329)
  at android.util.ArrayMap.<clinit>(ArrayMap.java:93)
  at com.android.internal.util.Parcelling$Cache.<clinit>(Parcelling.java:59)
  at android.content.pm.ApplicationInfo.<clinit>(ApplicationInfo.java:61)
```

### Steps to Reproduce

set compileSdkVersion 31
`ApplicationInfo applicationInfo = new ApplicationInfo();`

### Robolectric & Android Version

robolectric 4.8.2

**Comment by hoisie** [comment]
A demo app would be helpful to debug here. It appears you have some Android code running outside the context of a Robolectric sandbox. Is this a static member or a static function? Can you print the full stack trace?

**Comment by utzcoz** [comment]
@wijnanb I don't reproduce this problem with normal testing that has `compileSdkVersion 31`. I saw parcel calling stack from your above mentioned stacktrace, did you encounter this problem when creating `ApplicationInfo` from parcel instead of creating directly? The `Parcelling.java` actually uses `ArrayMap` that might calls `EmptyArray`. But `EmptyArray` is packaged into Robolectric's android-all jars. It's better if you can provide a minimal reproduce app, and we can investigate this issue.

**Comment by wijnanb** [comment]
I tried reproducing it with an empty Application, but there the problem was not found.
The issue was caused by the Robolectric ApplicationContext getting mixed up with a Mockito mocked Context.

Thanks for your replies!
