### ISSUE TITLE
Support AppComponentFactory or ignore BroadcastReceivers with custom constructors

### ISSUE THREAD

**Issue by ZacSweers** [robolectric/robolectric#7581]
### Description

When using Android 28+'s `AppComponentFactory`, it becomes possible to constructor-inject `BroadcastReceiver` instance. However, Robolectric seems to assume that these must all have empty constructors and tries to instantiate them all at test init.

I think Robolectric should ignore these or offer a way to handle them.

### Steps to Reproduce

Add a custom receiver with a non-empty constructor on the classpath, then try to run any test using `RobolectricTestRunner`. Observe a trace like this

```
java.lang.NoSuchMethodException: slack.browser.chrome.ChromeTabBroadcastReceiver.<init>()
java.lang.RuntimeException: java.lang.NoSuchMethodException: slack.browser.chrome.ChromeTabBroadcastReceiver.<init>()
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:434)
	at org.robolectric.internal.bytecode.ShadowImpl.newInstanceOf(ShadowImpl.java:18)
	at org.robolectric.shadow.api.Shadow.newInstanceOf(Shadow.java:35)
	at org.robolectric.android.internal.AndroidTestEnvironment.registerBroadcastReceivers(AndroidTestEnvironment.java:675)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:339)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:229)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:226)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:194)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:325)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:265)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: slack.browser.chrome.ChromeTabBroadcastReceiver.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:420)
	... 17 more
```

### Robolectric & Android Version

4.8.2, android API 28

**Comment by ZacSweers** [comment]
Note that trying to set `@Config(manifest = Config.NONE)` doesn't appear to work around it either

**Comment by erhiteshkumar** [comment]
I am also facing the same issue.

**Comment by utzcoz** [comment]
@ZacSweers @erhiteshkumar Thanks for reporting this issue. Although Robolectric can get parameter types list of constructor, there are some problems can not be processed easily:

1. Which constructor should be used when creating instance for a class if it has multiple constructors?
2. Which value should be passed for specific type when calling the constructor with input parameters?
3. It's more complicated for question 2 if input class type is a custom class. 

I don't have a great idea how to fix this issue or provide potential method from Robolectric perspective, but I can share what I did before when integrating Robolectric and encountering a similar problem: using annotation processor to add empty constructor for testing code. There is an example that I wrote to try to fix a similar issue: https://github.com/utzcoz/robolectric-with-junitparams/blob/master/junitparamsprocessor/src/main/java/com/utzcoz/robolectric/junitparamsprocessor/RobolectricJUnitParamsProcessor.java#L74-L85.

**Comment by ZacSweers** [comment]
Is there any reason it couldn't just use appcomponentfactory if available and otherwise refuse to load any receivers that don't have no-arg constructors available?

**Comment by utzcoz** [comment]
> if available and otherwise refuse to load any receivers that don't have no-arg constructors available?

@ZacSweers I sent a PR(https://github.com/robolectric/robolectric/pull/7860) to skip initialization for instances that don't have empty constructor. Could you help to check whether it can fix your problem with local maven snapshot building? Thanks.

**Comment by utzcoz** [comment]
Hi @ZacSweers , I try a custom receiver with a non-empty constructor, and the `AppComponentFactory` also throws an exception to me when running it on Emulator:

```
Process: com.demo.myapplication, PID: 6868
java.lang.RuntimeException: Unable to instantiate receiver com.demo.myapplication.CustomConstructorReceiver: java.lang.InstantiationException: java.lang.Class<com.demo.myapplication.CustomConstructorReceiver> has no zero argument constructor
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4292)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.InstantiationException: java.lang.Class<com.demo.myapplication.CustomConstructorReceiver> has no zero argument constructor
    at java.lang.Class.newInstance(Native Method)
    at android.app.AppComponentFactory.instantiateReceiver(AppComponentFactory.java:110)
    at androidx.core.app.CoreComponentFactory.instantiateReceiver(CoreComponentFactory.java:60)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:4285)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loopOnce(Looper.java:201) 
    at android.os.Looper.loop(Looper.java:288) 
    at android.app.ActivityThread.main(ActivityThread.java:7872) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
``` 

I also check `AppComponentFactory` code, and it also assumes that the receiver instance should have a constructor without parameters. 

> When using Android 28+'s AppComponentFactory, it becomes possible to constructor-inject BroadcastReceiver instance. 

Could you provide a sample with this scenario? I can validate its behavior and check whether there are something that Robolectric can do. The previous solution doesn't look like great.

**Comment by ZacSweers** [comment]
You should be implementing your own AppComponentFactory that can instantiate those classes and pointing your manifest's `android:appComponentFactory` at it. The default behavior assumes no-arg constructors, but custom once's can provide ways of instantiating ones with arguments.

Not a broadcast receiver, but similar use with activities: https://github.com/slackhq/circuit/blob/main/samples/star/src/main/kotlin/com/slack/circuit/star/di/StarAppComponentFactory.kt

**Comment by utzcoz** [comment]
@ZacSweers Thanks for providing this information. Looks like the ideal solution is to support `AppComponentFactory` in Robolectric likes: https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/app/ActivityThread.java;l=4284-4285?q=ActivityThread&ss=android.

**Comment by utzcoz** [comment]
@ZacSweers The fix will be released in 4.10. Please help to try it and send feedback to us when it is released. Thanks.

**Comment by ZacSweers** [comment]
Awesome!

**Comment by ZacSweers** [comment]
@utzcoz very late but I'm finally around to test this out again. Unfortunately it does not work as-is because while the `loadedApk.getAppFactory()` calls are in place for all the core components, it is _not_ in place for the callback for `instantiateApplication`. This effectively breaks meaningful use of these APIs in tests because most factories rely on retrieving the singleton Application instance after it's been created

**Comment by ZacSweers** [comment]
Specifically, this bit in AndroidTestEnvironment is where I would assume such a call would happen

<img width="1666" height="696" alt="Image" src="https://github.com/user-attachments/assets/ca584ec3-897d-4503-9af5-318bc9ab62cc" />

**Comment by ZacSweers** [comment]
Opened a PR that I think should cover it here: #10833
