### ISSUE TITLE
Exception in thread "ResizeFrame" java.lang.NullPointerException

### ISSUE THREAD

**Issue by charlesng** [robolectric/robolectric#7695]
### Description

I got a strange exception error after I upgraded to robolectric 4.9 and test will fail if it is following a **specific ordering**  When the tests are running in different ordering, the test can pass. I am finding the pattern and ordering at the moment to make a reproducible test case

```
Exception in thread "ResizeFrame" java.lang.NullPointerException
	at android.view.Choreographer.getRefreshRate(Choreographer.java:293)
	at android.view.Choreographer.__constructor__(Choreographer.java:280)
	at android.view.Choreographer.<init>(Choreographer.java)
	at android.view.Choreographer$1.initialValue(Choreographer.java:116)
	at android.view.Choreographer$1.initialValue(Choreographer.java:109)
	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
	at android.view.Choreographer.getInstance(Choreographer.java:304)
	at org.robolectric.shadows.ShadowBackdropFrameRenderer.run(ShadowBackdropFrameRenderer.java:37)
	at com.android.internal.policy.BackdropFrameRenderer.run(BackdropFrameRenderer.java)
``` 

### Steps to Reproduce

Finding the pattern and will update in here

### Robolectric & Android Version
- Robolectric 4.9
- Android SDK 33 (T)

### Link to a public git repo demonstrating the problem:
N/A

**Comment by utzcoz** [comment]
Hi @charlesng , when you find the pattern, please attach a reproduce app for this problem. It might be a corner case.

**Comment by utzcoz** [comment]
@charlesng Feel free to reopen this issue if you find stable pattern to reproduce this issue, and attach your reproducable sample. Thanks.
