### ISSUE TITLE
Problems using latest Robolectric snapshot with ActionBarSherlock

### ISSUE THREAD

**Issue by Moredread** [robolectric/robolectric#770]
Hi,

I'm trying to add ActionBarSherlock to my android project. I tried using the latest snapshot of robolectric from the sonatype repo and also tried a version I compiled locally. Both give the following and similar errors on running tests.

```
android.view.InflateException: XML file jar:/home/travis/.m2/repository/org/robolectric/android-res/4.1.2_r1_rc/android-res-4.1.2_r1_rc-real.jar!/res/layout/screen_title.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
	at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:161)
	at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:52)
	at org.robolectric.shadows.ShadowResources$ShadowTheme.obtainStyledAttributes(ShadowResources.java:465)
	at android.content.res.Resources$Theme.obtainStyledAttributes(Resources.java)
	at android.content.Context.obtainStyledAttributes(Context.java:374)
	at android.view.View.__constructor__(View.java:3297)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.shadows.ShadowView.__constructor__(ShadowView.java:61)
	at android.view.View.<init>(View.java:3295)
	at android.view.ViewGroup.<init>(ViewGroup.java:427)
	at android.widget.FrameLayout.<init>(FrameLayout.java:101)
	at android.widget.FrameLayout.<init>(FrameLayout.java:97)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
	at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:38)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2784)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2844)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:252)
	at com.actionbarsherlock.internal.ActionBarSherlockNative.setContentView(ActionBarSherlockNative.java:133)
	at com.actionbarsherlock.app.SherlockActivity.setContentView(SherlockActivity.java:229)
	at name.apb.android.ponytime.scala.PonyTime.onCreate(PonyTime.scala:43)
	at android.app.Activity.performCreate(Activity.java:5008)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:116)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:256)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at name.apb.android.ponytime.scala.db.CategoryTest.setUp(CategoryTest.scala:44)
```

You can find the pom.xml I'm using in the repo under https://github.com/Moredread/PonyTime and a full log of a compilation run under https://travis-ci.org/Moredread/PonyTime/builds/12808324

Strangely it works after compiling with IntelliJ Idea, even using maven after that, but I have no idea why.

Is this a problem with robolectric or with my build system?

Best regards,
Moredread

**Comment by erd** [comment]
As @awrichar mentioned, this sounds like Robolectric is not configured correctly with the paths needed to resolve ABS resources. Please take a look at the docs: http://robolectric.org/using-libraries/
