### ISSUE TITLE
OutOfMemoryError after upgrade to 4.9

### ISSUE THREAD

**Issue by lsuski** [robolectric/robolectric#7702]
### Description

This issue did not occur with Robolectric 4.8.2.

After upgrading to 4.9 when I run all the tests after some time it fails with
```
java.lang.OutOfMemoryError: Failed to load /home/jenkins/.m2/repository/org/robolectric/android-all-instrumented/13-robolectric-9030017-i4/android-all-instrumented-13-robolectric-9030017-i4.jar
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:275)
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:293)
	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
	at android.content.res.ApkAssets.__constructor__(ApkAssets.java:296)
	at android.content.res.ApkAssets.<init>(ApkAssets.java)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector321.loadFromPath(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:239)
	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:178)
	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:237)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
	at android.content.res.AssetManager.createSystemAssetsInZygoteLocked(AssetManager.java:249)
	at android.content.res.AssetManager.getSystem(AssetManager.java:276)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:83)
	at android.content.res.Resources.getSystem(Resources.java)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.onCreate(RoboMonitoringInstrumentation.java:70)
	at org.robolectric.android.internal.AndroidTestEnvironment.createInstrumentation(AndroidTestEnvironment.java:571)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:199)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:331)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:278)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

### Steps to Reproduce

Run about 1000 tests

### Robolectric & Android Version

Robolectric 4.9
Android target sdk 33

**Comment by hoisie** [comment]
Can you add `-XX:+HeapDumpOnOutOfMemoryError` to your jvm flags and then rerun tests? We can then take a look at the hprof file with visual vm

**Comment by lsuski** [comment]
I've added this flag however I can't find hprof file anywhere even when I specify path to it.  I run tests using gradle testDebugUnitTest task via Android Studio

**Comment by lsuski** [comment]
It looks like I  have to add
```
tasks.withType(Test) {
    jvmArgs += ['-XX:+HeapDumpOnOutOfMemoryError']
}
```
to build.gradle. However hprof file is quite big (>=300MB). Maybe should I run it via console

**Comment by hoisie** [comment]
Nice, if you have a hprof, feel free to zip it up and share it with me in a google drive.

See https://github.com/robolectric/robolectric/issues/6872 for more details.

**Comment by hoisie** [comment]
Also what's the max heap size available for your tests? i.e. `-Xmx4G`? At Google we have max heap size 8GiB by default.

**Comment by lsuski** [comment]
I'll share it tomorrow. I use default settings. Sometimes tests pass however it's strange that issue appeared for version 4.9 for the same settings. If there are some changes in robolectric which requires more memory then I will increase heap size. My first observation is that it could be related with tests that ran with different api specified in `@Config`. I have such tests and OOM is raised after them

**Comment by hoisie** [comment]
Do you have multi-sdk tests (e.g. `@Config(minSdk=...)`)with 4.9, since T is available, that could push it over the edge

**Comment by lsuski** [comment]
I have tests with `@Config(sdk = [24])` and other apis. I don't have tests with `@Config(sdk = [33])` as `33` is the default. I've sent hprof

**Comment by hoisie** [comment]
Just some immediate though:

1) It looks like you experienced an OOM after only 563MB. My first suggestion would be to bump the max heap size up by a considerable margin, to at least 2 or 4 GiB. Like I mentioned before, Robolectric does consume a lot of memory, as it manages a potentially large collection of Android framework jars, each of which are ~150MB uncompressed. Because Robolectric processes are short-lived, there is really no downside to letting it consume more memory, as the process will end soon and the memory will be reclaimed. Also with lower memory, more time is spent in GC, slowing things down.

2) All the memory is being used on ZipFile.entries associated with binary resources. Do you have a large amount of data being stored in your resources? e.g. large images, audio data, or other assets? AGP will generate a file called `apk-for-local-test.ap_` that Robolectric uses. In my sample project it is only ~500k:
```
 $ ls -alh ./app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
-rw-r----- 1 hoisie primarygroup 493K Apr 27 10:23 ./app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
```
If that file is large, you can see what is taking up most of the size:

`unzip -vl ./app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_ | sort -n`

**Comment by lsuski** [comment]
It's multimodule library so it have almost no resources. AFAIK by default gradle has Xmx 1G.  If I use ` org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m` it also fails

**Comment by lsuski** [comment]
For now I've set `-Xmx4g` but it didn't helped. What helped me was removeing 2 tests for api 22 and 23

**Comment by artour-bakiev** [comment]
I observe the same issue with these params for JVM `org.gradle.jvmargs=-Xms3072m -Xmx3584m` :

```
java.lang.OutOfMemoryError: Failed to load /root/.m2/repository/org/robolectric/android-all-instrumented/12.1-robolectric-8229987-i4/android-all-instrumented-12.1-robolectric-8229987-i4.jar
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:275)
	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:293)
	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
	at android.content.res.ApkAssets.__constructor__(ApkAssets.java:295)
	at android.content.res.ApkAssets.<init>(ApkAssets.java)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector4.loadFromPath(Unknown Source)
	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$3(ShadowArscApkAssets9.java:239)
	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:178)
	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:237)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
	at android.content.res.AssetManager.createSystemAssetsInZygoteLocked(AssetManager.java:241)
	at android.content.res.AssetManager.getSystem(AssetManager.java:268)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:83)
	at android.content.res.Resources.getSystem(Resources.java)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.onCreate(RoboMonitoringInstrumentation.java:70)
	at org.robolectric.android.internal.AndroidTestEnvironment.createInstrumentation(AndroidTestEnvironment.java:571)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(Android
```

**Comment by utzcoz** [comment]
There is another sample with similar problem: https://github.com/robolectric/robolectric/issues/7909.

**Comment by agrieve** [comment]
Hitting this in Chrome's robolectric tests as well.

We run with 1G heap, but restrict runs to tests that use the same SDK and no more than 150 test methods.

Googlers can see more details here: https://bugs.chromium.org/p/chromium/issues/detail?id=1463771

I captured a heap dump and it shows most memory is taken by identically sized `byte[]` objects, which leads me to think that robolectric is not reusing resource-related things between tests when it probably should be.

One thing I thought might be related, is zip compression. We use the `android-all-instrumented-` .jar files distributed by robolectric, which compress `resources.arsc`. However, I tried modifying them to have their resources stored uncompressed and aligned instead, but it didn't make much difference. I tried the same with our apps' `.ap_` file, but also no noticeable effect (tried 16 byte alignment).

Here's the OOM stack we're seeing:

```
0| java.lang.OutOfMemoryError: Java heap space
 0| Dumping heap to java_pid3919144.hprof ...
 0| java.lang.OutOfMemoryError: Failed to load /usr/local/google/code/clankium1/src/out-gn/Release/obj/chrome/android/chrome_junit_tests.robo.ap_
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:275)
 0| 	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
 0| 	at android.content.res.ApkAssets.__constructor__(ApkAssets.java:116)
 0| 	at android.content.res.ApkAssets.<init>(ApkAssets.java)
 0| 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:48)
 0| 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector571.loadFromPath(Unknown Source)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9.lambda$loadFromPath$0(ShadowArscApkAssets9.java:190)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9.getFromCacheOrLoad(ShadowArscApkAssets9.java:178)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9.loadFromPath(ShadowArscApkAssets9.java:188)
 0| 	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java)
 0| 	at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1588)
 0| 	at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1561)
 0| 	at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:899)
 0| 	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1289)
 0| 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1022)
 0| 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1042)
 0| 	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:410)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:382)
 0| 	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:382)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:279)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:251)
 0| 	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:248)
 0| 	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
 0| 	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:79)
 0| 	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:216)
 0| 	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:340)
 0| 	at org.chromium.base.test.BaseRobolectricTestRunner.beforeTest(BaseRobolectricTestRunner.java:103)
 0| 	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:281)
 0| 	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
 0| 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
 0| 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 0| 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 0| 	at java.base/java.lang.Thread.run(Thread.java:1623)
 0| Caused by: java.lang.OutOfMemoryError: Java heap space
 0| 	at org.robolectric.res.android.FileMap.getDataPtr(FileMap.java:413)
 0| 	at org.robolectric.res.android.Asset$_FileAsset.openChunk(Asset.java:734)
 0| 	at org.robolectric.res.android.Asset.createFromUncompressedMap(Asset.java:507)
 0| 	at org.robolectric.res.android.CppApkAssets.Open(CppApkAssets.java:317)
 0| 	at org.robolectric.res.android.CppApkAssets.LoadImpl_measured(CppApkAssets.java:246)
 0| 	at org.robolectric.res.android.CppApkAssets.lambda$LoadImpl$0(CppApkAssets.java:206)
 0| 	at org.robolectric.res.android.CppApkAssets$$Lambda$103/0x00000008014270d0.get(Unknown Source)
 0| 	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
 0| 	at org.robolectric.res.android.CppApkAssets.LoadImpl(CppApkAssets.java:203)
 0| 	at org.robolectric.res.android.CppApkAssets.Load(CppApkAssets.java:117)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9.nativeLoad(ShadowArscApkAssets9.java:272)
 0| 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000801479c00.invokeStatic(LambdaForm$DMH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x000000080147b800.guardWithCatch(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x000000080147d800.reinvoke(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x000000080147dc00.guard(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x000000080147e000.linkToCallSite(LambdaForm$MH)
 0| 	at android.content.res.ApkAssets.nativeLoad(ApkAssets.java)
 0| 	at android.content.res.ApkAssets.$$robo$$android_content_res_ApkAssets$__constructor__(ApkAssets.java:116)
 0| 	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000801475000.invokeSpecial(LambdaForm$DMH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000801477000.guardWithCatch(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000801479000.reinvoke(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000801479400.guard(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000801479800.linkToCallSite(LambdaForm$MH)
 0| 	at android.content.res.ApkAssets.<init>(ApkAssets.java)
 0| 	at android.content.res.ApkAssets.$$robo$$android_content_res_ApkAssets$loadFromPath(ApkAssets.java:48)
 0| 	at java.base/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
 0| 	at java.base/java.lang.invoke.LambdaForm$MH/0x00000008013ff800.invoke(LambdaForm$MH)
 0| 	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
 0| 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:155)
 0| 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
 0| 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
 0| 	at org.robolectric.shadows.ShadowArscApkAssets9$_ApkAssets_$$Reflector571.loadFromPath(Unknown Source)
```

Our `.ap_` file is 28mb with all entries uncompressed, so it really shouldn't account for 100s of mb of heap.

Also notable is that there are 12 byte[] of size 23850880 in my heap dump, which is the exact size of our `resources.arsc`.

**Comment by agrieve** [comment]
Forgot to mention we are using Robolectric 4.10.3

**Comment by artour-bakiev** [comment]
It seems I have found a workaround for the Android platform. Replacing the `RobolectricTestRunner` with the `androidx.test.ext.junit.runners.AndroidJUnit4` runner fixes this issue for us.

***Before***
```kotlin
@RunWith(RobolectricTestRunner::class)
```

***After***
```kotlin
@RunWith(AndroidJUnit4::class)
```

**Comment by artour-bakiev** [comment]
Yes, I also tried v4.11. Unfortunately, it didn't work for us. The only solution that worked for us was using `AndroidJUnit4` instead of `RobolectricTestRunner`.
