### ISSUE TITLE
File I/O exceptions when testing non-application module

### ISSUE THREAD

**Issue by dellisd** [robolectric/robolectric#7730]
### Description
Some File-related method calls fail during tests when running tests on a non-application module (e.g. a library or dynamic feature module).

Some stacktraces that we've seen:

Here Picasso can create a `StatFs` instance, but this method call fails.
```
'long android.os.StatFs.getBlockCountLong()'
java.lang.NoSuchMethodError: 'long android.os.StatFs.getBlockCountLong()'
	at com.squareup.picasso3.Utils.calculateDiskCacheSize(Utils.kt:138)
	at com.squareup.picasso3.Picasso$Builder.build(Picasso.kt:648)
        [omitted test calls]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
 ```

This fails when calling `context.getDatabasePath(dbName).createNewFile()`, seemingly because the path that is returned (`{tmpdir}/databases`) doesn't exist (although the temporary directory does exist).

```
No such file or directory
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1035)
	[omitted test calls]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Steps to Reproduce

See stacktraces above and the methods that were called which resulted in an exception.

### Robolectric & Android Version

Robolectric 4.7.3 & 4.9, Android 32

### Link to a public git repo demonstrating the problem:

Currently unavailable

**Comment by hoisie** [comment]
> when running tests on a non-application module

Does this mean running the tests from Android Studio? Do the tests work when running from the command line with graddle?

**Comment by hoisie** [comment]
Looks like [StatFs#getBlockCountLong](https://developer.android.com/reference/android/os/StatFs#getBlockCountLong()) was added in API level 18, which means your tests are likely running in in SDK level 16 (you can try printing `RuntimeEnvironment.getApiLevel()`

How is the SDK level being specified in this test? Is it the `android:targetSdkVersion` in the manifest? I vaguely recall that some library modules run using legacy resources, which means that Robolectric won't know which SDK level to use, so it defaults to 16.

Are binary resources being used duri
I vaguely recall that sometimes running tests in library modules cause binary resources not to be used, and so if the only hint that Robolectric has that

**Comment by hoisie** [comment]
This is the issue I was thinking of:
https://github.com/robolectric/robolectric/issues/5624

**Comment by hoisie** [comment]
Do you know why the tests are using legacy resources? It could be a bug in Android Studio or AGP.

**Comment by dellisd** [comment]
I'm not sure why it's running in legacy mode. Does excluding resources from the tests cause legacy mode to be enabled?

Stepping back for a moment, even though the `NoSuchMethodError` problem was caused by the tests being run on API 16, it doesn't explain why running the tests on a dynamic feature module would cause that to happen when the tests ran normally when the module was a `com.android.application` module.

Overall there seem to be a lot of unexpected and inconsistent behaviours with running robolectric tests in dynamic feature modules.
