### ISSUE TITLE
SSL Issues with Wiremock after upgrading from Robolectric 4.8.1 to 4.9

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#7819]
I upgraded Robolectric to 4.9 recently and see permanent regressions in my wiremock-based API tests.

Wiremock is configured like this:

```
WireMockRule(wireMockConfig().enforceTls12().dynamicHttpsPort())
```

This is the error I'm seeing:

```
javax.net.ssl.SSLHandshakeException: connection closed
	at ???(Coroutine boundary.?(?)
	at my.app.tech.logging.DeviceLogSender.sendNextBatch(DeviceLogSender.kt:49)
	at my.app.tech.logging.DeviceLogSender.sendBatches(DeviceLogSender.kt:24)
	at my.app.tech.logging.DeviceLogSenderTest$should clear logs after sending$1.invokeSuspend(DeviceLogSenderTest.kt:106)
	at my.app.test.support.coroutines.TestCoroutineUtils$runBlockingWithTimeout$1.invokeSuspend(TestCoroutineUtils.kt:34)
Caused by: javax.net.ssl.SSLHandshakeException: connection closed
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:361)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:232)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:209)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		... 23 more
	Caused by: java.io.EOFException: connection closed
		... 22 more
Caused by: java.io.EOFException: connection closed
	... 22 more
```

**Comment by realdadfish** [comment]
Ok, annotating the tests with `@ConscryptMode(ConscryptMode.Mode.OFF)` fixed these issues for me.
