### ISSUE TITLE
Can't test DatePicker/DatePickerDialog

### ISSUE THREAD

**Issue by coreydowning** [robolectric/robolectric#783]
Tried killing the shadowed constructor and ran into some "sorry" exceptions.

Was trying to test updating the date in the DatePicker inside a DatePickerDialog:

``` java
DatePickerDialog datePickerDialog = (DatePickerDialog) ShadowAlertDialog.getLatestAlertDialog();
datePickerDialog.updateDate(1932, 3, 14);
```

The second line blows up because the dialog does not have a DatePicker.

Trying to inflate a layout with a DatePicker in it will throw the "sorry" exception:

```
android.view.InflateException: XML file ./res/layout/create_account_activity.xml line #-1 (sorry, not yet implemented): Error inflating class <unknown>
    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
    at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:38)
    at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
...
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at android.view.LayoutInflater.$$robo$$LayoutInflater_1d1f_createView(LayoutInflater.java:594)
    at android.view.LayoutInflater.createView(LayoutInflater.java)
    at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:38)
...
Caused by: java.lang.NullPointerException
    at android.text.format.DateUtils.getMonthString(DateUtils.java:286)
    at android.widget.DatePicker.setCurrentLocale(DatePicker.java:482)
    at android.widget.DatePicker.__constructor__(DatePicker.java:152)
    at android.widget.DatePicker.<init>(DatePicker.java:149)
    at android.widget.DatePicker.<init>(DatePicker.java:145)
    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
    at org.robolectric.shadows.RoboLayoutInflater.onCreateView(RoboLayoutInflater.java:38)
```

**Comment by kappsy** [comment]
Hi Any update on this issue ?
I am facing this issue while testing my application which uses DatePicker

**Comment by xian** [comment]
Robolectric's handling of locales has significantly improved; please try with Robolectric 4.0.

If you feel this has been closed in error please feel free to reopen. Sample code running against 4.0 would make it easiest for us to diagnose any issues. Thanks!
