### ISSUE TITLE
ShadowSharedMemoryTest failed on Windows 10

### ISSUE THREAD

**Issue by utzcoz** [robolectric/robolectric#7856]
### Description

I tried to test ./gradlew.bat test -PSKIP_JAVADOC=true on Windows 10 in Windows Terminal, and I found there are tests failed on Windows 10.

`ShadowSharedMemoryTest#create_shouldIgnoreDebugNameForIdentity`:

```
expected: 1234
but was : 5678
	at org.robolectric.shadows.ShadowSharedMemoryTest.create_shouldIgnoreDebugNameForIdentity(ShadowSharedMemoryTest.java:89)
```

`ShadowSharedMemoryTest#readFromParcel_shouldSupport`:

```
java.lang.IllegalArgumentException: Unable to create SharedMemory from closed FileDescriptor
	at android.os.SharedMemory.__constructor__(SharedMemory.java:55)
	at android.os.SharedMemory.<init>(SharedMemory.java)
	at android.os.SharedMemory$1.createFromParcel(SharedMemory.java:295)
	at android.os.SharedMemory$1.createFromParcel(SharedMemory.java:291)
	at android.os.Parcel.readParcelable(Parcel.java:3281)
	at org.robolectric.shadows.ShadowSharedMemoryTest.readFromParcel_shouldSupport(ShadowSharedMemoryTest.java:160)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:591)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:274)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:88)
        ......
```

### Steps to Reproduce

Download current master branch within 4.10-SNAPSHOT development, setup it OpenJDK 11 for Windows 10, and run `./gradlew.bat test -PSKIP_JAVADOC=true` in `msys2 64bit` terminal.

### Robolectric & Android Version

4.10-SNAPTSHOT

### Link to a public git repo demonstrating the problem:

Robolectric itself.

**Comment by utzcoz** [comment]
@arsalanahmad4 You can check https://robolectric.org/ to learn basic usage and official guidance of Robolectric. Before you start to contribute core Robolectric, it's recommended to use Robolectric at your projects.

**Comment by arsalanahmad4** [comment]
@utzcoz I am familiar  using Robolectric in android projects and looking for some beginner friendly issues to contribute  to the organization. It would be of so much help if you could help me get started

**Comment by utzcoz** [comment]
There are some issues labeled with `help wanted` that need community's help: https://github.com/robolectric/robolectric/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22. There are also some issues labeled with `starter issue` that can be good starting issues: https://github.com/robolectric/robolectric/issues?q=is%3Aopen+is%3Aissue+label%3A%22starter+issue%22.

**Comment by arsalanahmad4** [comment]
@utzcoz Thanks for the boost would look into it and contribute to the community. Looking forward to having a detailed discussion on the solution to the issue in futre
