### ISSUE TITLE
"multiple instances" error when removing value during unit testing

### ISSUE THREAD

**Issue by ziglee** [robolectric/robolectric#7919]
### Description
When trying to remove some key from datastore-preferences during unittest I'm getting an error about "multiple instances" of the datastore.

### Steps to Reproduce
Call `dataStore.edit` more than one time during a unit test causes error.

`
Unable to rename C:\Users\xyz\AppData\Local\Temp\robolectric-Method_Given_there_session_and_user_When_clearing_them_Should_return_null10240656663476257733\com.nautiluslog.data.test-dataDir\files\datastore\DATASTORE_PREF_FILE_NAME.preferences_pb.tmp.This likely means that there are multiple instances of DataStore for this file. Ensure that you are only creating a single instance of datastore for this file.
java.io.IOException: Unable to rename C:\Users\xyz\AppData\Local\Temp\robolectric-Method_Given_there_session_and_user_When_clearing_them_Should_return_null10240656663476257733\com.nautiluslog.data.test-dataDir\files\datastore\DATASTORE_PREF_FILE_NAME.preferences_pb.tmp.This likely means that there are multiple instances of DataStore for this file. Ensure that you are only creating a single instance of datastore for this file.
	at androidx.datastore.core.SingleProcessDataStore.writeData$datastore_core(SingleProcessDataStore.kt:433)
	at androidx.datastore.core.SingleProcessDataStore.transformAndWrite(SingleProcessDataStore.kt:410)
	at androidx.datastore.core.SingleProcessDataStore.handleUpdate(SingleProcessDataStore.kt:276)
	at androidx.datastore.core.SingleProcessDataStore.access$handleUpdate(SingleProcessDataStore.kt:76)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invokeSuspend(SingleProcessDataStore.kt:242)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(SingleProcessDataStore.kt)
	at androidx.datastore.core.SingleProcessDataStore$actor$3.invoke(SingleProcessDataStore.kt)
	at androidx.datastore.core.SimpleActor$offer$2.invokeSuspend(SimpleActor.kt:122)
`

### Robolectric & Android Version
Robolectricv4.9
Android compileSdk 33
Windows 11 Pro

### Link to a public git repo demonstrating the problem:
https://gist.github.com/ziglee/5270e6fefba92bb201f3f3d43db76419

**Comment by alwa** [comment]
> On android the behavior of File.renameTo should not fail because of this, and I think robolectric should handle this correctly. DataStore relies on this functionality for atomic reads/writes. If robolectric can't fix this, please follow up and maybe we could special case windows.

See: https://issuetracker.google.com/issues/185414033
