### ISSUE TITLE
ActionBarSherlock and Robolectric within Gradle context

### ISSUE THREAD

**Issue by tbruyelle** [robolectric/robolectric#795]
While initializing an activity or a fragment in a junit with Robolectric 2.3-SNAPSHOT and ActionbarSherlock 4.4.0, in a project which uses the Gradle build, I get some exceptions like : 

```
java.lang.RuntimeException: java.io.FileNotFoundException: AndroidManifest.xml (No such file or directory)
	at org.robolectric.res.XmlLoader.parse(XmlLoader.java:39)
	at org.robolectric.res.builder.XmlFileBuilder.getXmlResourceParser(XmlFileBuilder.java:56)
	at org.robolectric.shadows.ShadowAssetManager.openXmlResourceParser(ShadowAssetManager.java:174)
	at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java)
	at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:444)
	at com.actionbarsherlock.internal.ResourcesCompat.loadLogoFromManifest(ResourcesCompat.java:120)
	at com.actionbarsherlock.internal.widget.ActionBarView.<init>(ActionBarView.java:189)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
...
```

It seems the `AndroidManifest.xml` file is not search at the right place, which is, in a Gradle context, `build/manifests/debug/`.

I already use @JakeWharton 's `gradle-android-test-plugin` and some others tests I wrote work well with my project resources inside the `build` dir.

The current issue really seems to be linked to some methods invoked inside ActionBarSherlock.

**Comment by jaredsburrows** [comment]
@tbruyelle What is the status of this?

@JakeWharton's test plugin is deprecated/

@erd Can we close this since ActionBarSherlock is deprecated?

**Comment by tbruyelle** [comment]
I have no idea, I think you can close it safely since all mentionned items are deprecated !

**Comment by jaredsburrows** [comment]
@tbruyelle It is your issue, you can close it. I am not an `owner`. @erd

**Comment by tbruyelle** [comment]
Closed as no more relevant
