### ISSUE TITLE
How to write the shaodow class with a final static member variable

### ISSUE THREAD

**Issue by wxhhh729** [robolectric/robolectric#7996]
### Description
When I write a custom shadow class named ShadowFoo.java for testing Foo.java, in the origin Foo, there is a public final static member variable named FIELD_A, some other class just invoke the FIELD_A directly by Foo.FIELD_A. And, there is some other method in Foo.java that the source which I tested is inoked, so I have to use shadow. I' ve tried much and can't find a way to resolve the member variable in shadow class, could someone know how to deal with it?

### Steps to Reproduce
1. I copy the Foo.java into test directories, and delete other method only keep the member variable. When I run the test case, it worked correctly.
2. I wrote a same type and same name member variable in ShadowFoo.java,  use @Config(shadows = {ShadowFoo.class}) to deploy the shadow class, and it shows the error info.

PS: The names of class and variable in my description is just for convenient to describe my problem. The real error info are copied from android studio as follow.

java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.robolectric.internal.bytecode.ShadowWrangler.classInitializing(ShadowWrangler.java:186)
	at org.robolectric.internal.bytecode.RobolectricInternals.classInitializing(RobolectricInternals.java:21)
	at com.oplus.wrapper.os.UserHandle.<clinit>(Unknown Source)
	at com.oplus.aod.cache.db.AodDBHelper.getInstance(AodDBHelper.java:22)
	at com.oplus.aod.cache.db.AodDBManager.<init>(AodDBManager.java:34)
	at com.oplus.aod.AodApplication.onCreate(AodApplication.kt:31)

### Robolectric & Android Version
testImplementation 'org.robolectric:robolectric:4.9'
testImplementation 'org.robolectric:annotations:4.9'

minSdkVersion 30
targetSdkVersion 33

### Link to a public git repo demonstrating the problem:
AodDBHelper.java
public static AodDBHelper getInstance(Context context) {
        USER_ID = UserHandle.USER_SYSTEM;           //The UserHandle is not android.os.UserHandle, we do some override, and it is the Foo I memtioned
        if (sAodDBHelper == null) {
            sAodDBHelper = new AodDBHelper(context);
        }
        return sAodDBHelper;
}

1.Copied the UserHandle.java and worked correctly
public class UserHandle {

    public static final int USER_SYSTEM = 0;         //just the one line of source code
}

2.Delete the UserHandle.java in test directories, write a ShadowUserHandle.java and runs error
@Implements(UserHandle.class)
public class ShadowUserHandle {
    public static final int USER_SYSTEM = 0;

    @Implementation
    ....       //other methods which do not effect the error test case
}

**Comment by utzcoz** [comment]
@wxhhh729 Please attach a minimal reproducible app for this issue, and we can investigate it with your sample.
