### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.robolectric.nativeruntime.SQLiteConnectionNatives

### ISSUE THREAD

**Issue by OliverKoo** [robolectric/robolectric#8046]
I am on Linux aarch64 (AWS Graviton) using RobolectircTestRunner 

```
...
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.ConscryptMode

@RunWith(RobolectricTestRunner::class)
@ConscryptMode(ConscryptMode.Mode.OFF)
class MyDBTest {
...
}
```

Got the following error
```


com.myorg.database.MyDBTest > test  FAILED
--
  | java.lang.NoClassDefFoundError: Could not initialize class org.robolectric.nativeruntime.SQLiteConnectionNatives
  | at org.robolectric.shadows.ShadowNativeSQLiteConnection.lambda$nativeOpen$0(ShadowNativeSQLiteConnection.java:31)
  | at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
  | at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:27)
  | at org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(ShadowNativeSQLiteConnection.java:49)
  | at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
  | at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
  | at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:195)
  | at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
  | at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
  | at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
  | at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
  | at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
  | at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:739)
  | at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:729)
  | at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
  | at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
  | at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:231)
  | at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:189)
  | at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
  | at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
  | at androidx.room.testing.MigrationTestHelper.openDatabase(MigrationTestHelper.java:440)
  | at androidx.room.testing.MigrationTestHelper.createDatabase(MigrationTestHelper.java:271)
  | at com.myorg.database.MyDBTest.test  TestA(MyDBTest.kt:56)


```

I am on Robolectric 4.9, any idea how I can get pass this?

**Comment by utzcoz** [comment]
@OliverKoo Could you provide a minimal app that can reproduce this issue? We can investigate it.

**Comment by hoisie** [comment]
Ugh, Linux aarch64 is not supported in Robolectric, and it is very unlikely that it will be any time soon.

**Comment by utzcoz** [comment]
> Ugh, Linux aarch64 is not supported in Robolectric, and it is very unlikely that it will be any time soon.

@OliverKoo As @hoisie said, please use x86 Linux to use native SQLite, or you can disable native SQLite with config like `@SQLiteMode(Mode.LEGACY)` to check whether legacy SQLite can work on Linux aarch64, although I think it might not support.

**Comment by OliverKoo** [comment]
@utzcoz using @SQLiteMode(Mode.LEGACY worked! Thank you.

FWIW I am currently using Roboletric on Graviton and all our tests are working if we turn off ConscryptMode. For very few of our DB tests we have to roll back using @SQLiteMode(Mode.LEGACY) too. 

Some info that might be helpful moving forward for those that are looking - 
Conscrypt seems to be one of the major hurdle for Robolectric to support aarch64 but Google Conscrypt [just recently started to support MacOS m1 arm64 (3 weeks ago) ](https://github.com/google/conscrypt/commit/7ffa282ce3c9348f1743625c154c314f6a24722c) and this lay the foundation making supporting linux aarch64 more obtainable. [From this thread - it looks Google Conscrypt instead to support aarch64 in the near future. ](https://github.com/google/conscrypt/pull/1100)

I am unblocked atm but maybe this helps to factor in when deciding supporting Linux aarch64. 

related to https://github.com/robolectric/robolectric/issues/7204 open by you @utzcoz

**Comment by hoisie** [comment]
I am not sure how `@SQLiteMode(Mode.LEGACY)` works in Linux+arm64. Legacy SQLite also has native libraries, and it does not include a Linux arm64 version:

https://github.com/robolectric/robolectric/blob/master/shadows/framework/build.gradle#L61-L65

Thanks for the heads up about Conscrypt. When the next version is released we can use it by default for Mac M1 also.

**Comment by OliverKoo** [comment]
ah yep I doubled check and realized I was wrong the test did not work, it was just not ran before so I thought it passed.

```
java.lang.UnsupportedOperationException: Architecture 'aarch64' is not supported by SQLite library
```

this is the only thing blocking me migrating our fleet into Graviton. Linux aarch64 is not new so some other company must ran into this before, @hoisie do you know what other orgs do? is there a undocumented way to get pass this?

**Comment by hoisie** [comment]
> Linux aarch64 is not new so some other company must ran into this before

This is the first time I have ever ran across this issue :)

>  is there a undocumented way to get pass this

The workaround is to use Linux x86_64 for Robolectric tests

**Comment by hoisie** [comment]
@OliverKoo If you are open to it, you could try to build the nativeruntime from 4.9.2 in a Linux arm64 environment. If it works maybe we can release a 4.9.3 with support for Linux arm64. Getting 4.10 to work on arm64 would be very challenging.
