### ISSUE TITLE
Layout aliasing causes UnsupportedOperationException

### ISSUE THREAD

**Issue by marcoRS** [robolectric/robolectric#805]
Hello, I'm trying to test a fragment that uses a layout that has alias name. I have a values folder with a xml file called "layout.xml" that defines the following layout: 

``` xml
<item name="fragment_login" type="layout">@layout/fragment_login_port</item>
```

and I have another folder called "values-land" that has the layout definition: 

``` xml
 <item name="fragment_login" type="layout">@layout/fragment_login_land</item>
```

The app runs correctly and switches properly depending on the orientation however when I try to test the fragment I get an exception. 

I have created a test application that reproduces this exception: https://dl.dropboxusercontent.com/u/9726572/github-issues/robolectric-test.zip

I get the following exception in command line running "mvn clean install" as well as in Android Studio: 

java.lang.UnsupportedOperationException: ugh, this doesn't work still? at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:276) at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:259) at org.robolectric.shadows.ShadowAssetManager.getResourceValue(ShadowAssetManager.java:85)
    at android.content.res.AssetManager.getResourceValue(AssetManager.java)
    at android.content.res.Resources.getValue(Resources.java:1009)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2098)
    at android.content.res.Resources.getLayout(Resources.java:852)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
    at com.droidtest.LoginFragment.onCreateView(LoginFragment.java:18)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1478)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1460)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
    at org.robolectric.util.Scheduler.postDelayed(Scheduler.java:37)
    at org.robolectric.shadows.ShadowLooper.post(ShadowLooper.java:198)
    at org.robolectric.shadows.ShadowHandler.postDelayed(ShadowHandler.java:56)
    at org.robolectric.shadows.ShadowHandler.post(ShadowHandler.java:51)
    at android.os.Handler.post(Handler.java)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1366)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:595)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:574)
    at com.roboletrictests.unit.LoginTest.setUp(LoginTest.java:30)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

Is there a workaround for this? I have quite a few layout aliases.

**Comment by jongerrish** [comment]
We've revamped resources in Robolectric 4.0 to process the binary resource files + arsc table produced by aapt and the resource handling code is now much closer to that of the framework. This includes changes to parse the merged manifest using the Android platform code.

Mind giving this a try with 4.0 + binary resources by configuring your gradle.build as follows:-

```groovy
testImplementation "org.robolectric:robolectric:4.0"

android {
  enableUnitTestBinaryResources=true
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}
```

We're doing a big bug scrub and trying to be aggressive about it so apologies if this was closed in error, in which case feel free to reopen.

If this is still an issue an example project with failing test would be most helpful.
