### ISSUE TITLE
androidx.mediarouter doesn't appear to work with Robolectric

### ISSUE THREAD

**Issue by yschimke** [robolectric/robolectric#8130]
### Description

androidx.media router should be a clean modern API for detecting the media routes.

https://developer.android.com/jetpack/androidx/releases/mediarouter

### Steps to Reproduce

```
        context = InstrumentationRegistry.getInstrumentation().targetContext
        mediaRouterLegacy =
            context.getSystemService(Context.MEDIA_ROUTER_SERVICE) as MediaRouterLegacy

        audioManager =
            context.getSystemService(Context.AUDIO_SERVICE) as AudioManager

        mediaRouter = MediaRouter.getInstance(context)
   
        Shadows.shadowOf(mediaRouterLegacy).addBluetoothRoute()
        Shadows.shadowOf(audioManager).apply {
            setStreamMaxVolume(5)
            setStreamMaxVolume(10)
        }

        assertThat(mediaRouter.selectedRoute.deviceType)
            .isEqualTo(MediaRouter.RouteInfo.DEVICE_TYPE_BLUETOOTH)    
```        

### Robolectric & Android Version

Robolectric 4.10.0-alpha01
API 30, 33

### Link to a public git repo demonstrating the problem:

https://github.com/google/horologist/blob/b26fe608fba91ea2074387664bdf43a8d00694ea/audio/src/test/java/com/google/android/horologist/audio/SystemAudioRepositoryTest.kt#L78

**Comment by utzcoz** [comment]
Looks like `selectedRoute` is not called to update `selectedRoute` of the `MediaRoute`.

**Comment by utzcoz** [comment]
There is a [regression test](https://github.com/robolectric/robolectric/blob/03b6aefc444f42becc2450f145c6f5e130c4c2ae/robolectric/src/test/java/org/robolectric/shadows/ShadowMediaRouterTest.java#L73-L82) to ensure `addBluetoothRoute` will call `selectRoute` correctly. I think you can use `mediaRouteLegacy.selectedRoute.deviceType` to pass the test. For AndroidX `MediaRoute`, it might have a compatibility issue.

**Comment by yschimke** [comment]
Should I file that with the androidx project, or is robolectric support not a requirement?

**Comment by utzcoz** [comment]
> Timed out waiting for 2000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 2000 ms
	(Coroutine boundary)
	at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:403)
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.first(Reduce.kt:183)
	at com.google.android.horologist.audio.SystemAudioRepositoryTest$testVolumeRepository$2$newVolume$1$1.invokeSuspend(SystemAudioRepositoryTest.kt:97)
	at com.google.android.horologist.audio.SystemAudioRepositoryTest$testVolumeRepository$2$newVolume$1.invokeSuspend(SystemAudioRepositoryTest.kt:93)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 2000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)


It's timeout issue not `selectedRoute`

**Comment by yschimke** [comment]
Thanks, I'll try to work it out. I really struggle with robolectric threading.

Sorry for the false report.

**Comment by utzcoz** [comment]
@yschimke After some debugging, I found that `increaseVolume` calls `MediaRouter.RouteInfo#requestUpdateVolume` to update `volume`. Looks like `requestUpdateVolume` is not supported by the Robolectric. I am trying to write a custom `ShadowMediaRouter` for horologist to check whether I can fix it temporarily with custom shadow.

**Comment by yschimke** [comment]
Thanks.  Im able to see bluetooth activate, but blocked at volume as you point out.

```
    @Test
    fun testVolumeRepository() {
        Shadows.shadowOf(mediaRouterLegacy).addBluetoothRoute()
        Shadows.shadowOf(audioManager).apply {
            setStreamVolume(5)
            setStreamMaxVolume(10)
        }

        assertThat(mediaRouter.selectedRoute.deviceType)
            .isEqualTo(MediaRouter.RouteInfo.DEVICE_TYPE_BLUETOOTH)
        assertThat(mediaRouter.selectedRoute.volume)
            .isEqualTo(5)
    }
```

It fails on the last line, which matches what you point out.

**Comment by utzcoz** [comment]
@yschimke Yep. From my current debugging result,  volume states are stored in `ShadowAudioManager`. I need to write an instrumentation tests for normal volume changing logic to check the AOSP's logic to pass volume state between `AudioManager` and `MediaRouter`.

**Comment by utzcoz** [comment]
@hoisie @brettchabot Would you help to contact folks from AndroidX media team to help this issue? I am very busy recent weeks, and I don't have enough time for this issue. If we can fix this issue, I think @yschimke will adopt the Robolectric more for watch libraries.
