### ISSUE TITLE
NoClassDefFoundError for VibrationEffectSegment when configured SDK is < 32

### ISSUE THREAD

**Issue by cmathew** [robolectric/robolectric#8137]
### Description
On Android SDK < 32, calling something like `getSystemService(VIBRATOR_SERVICE) as Vibrator` results in an exception at runtime. Stacktrace:
```
android/os/vibrator/VibrationEffectSegment
java.lang.NoClassDefFoundError: android/os/vibrator/VibrationEffectSegment
	at android.os.Vibrator.<init>(Vibrator.java)
	at android.os.SystemVibrator.<init>(SystemVibrator.java)
	at android.app.SystemServiceRegistry$44.createService(SystemServiceRegistry.java:522)
	at android.app.SystemServiceRegistry$44.createService(SystemServiceRegistry.java:519)
	at android.app.SystemServiceRegistry$CachedServiceFetcher.getService(SystemServiceRegistry.java:928)
	at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:880)
	at android.app.ContextImpl.getSystemService(ContextImpl.java:1651)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector6.getSystemService(Unknown Source)
	at org.robolectric.shadows.ShadowContextImpl.getSystemService(ShadowContextImpl.java:88)
	at android.app.ContextImpl.getSystemService(ContextImpl.java)
	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:708)
        ...
```

### Steps to Reproduce
Have a test that runs some production code like:
```
@JvmStatic
fun getDefaultVibrator(context: Context): Vibrator = with(context) {
  return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
    val vibratorManager =
      getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager
    vibratorManager.defaultVibrator
  } else {
    @Suppress("DEPRECATION")
    getSystemService(VIBRATOR_SERVICE) as Vibrator
  }
}
```
Observe that SDK >= 32 can run the code inside the "else" condition without error, whereas it fails for < 32.

### Robolectric & Android Version
Robolectric: 4.10
Configured SDK via robolectric.properties: 26

### Link to a public git repo demonstrating the problem:
Run ExampleUnitTest here: https://github.com/cmathew/VibrationEffectSegmentSample

**Comment by utzcoz** [comment]
@cmathew I think it is a common but not easy regressed issue when integrating new APIs supporting defined from a newer Android SDK to the Robolectric. The `VibrationEffectSegment` was introduced from SDK 32/Android S(see https://cs.android.com/android/_/android/platform/frameworks/base/+/bd992109e08d0435a474f6350a4c39098a3f6e40). I will take look at this issue this weekend.

**Comment by utzcoz** [comment]
@cmathew Please check 4.10.1 for this issue.
