### ISSUE TITLE
Cannot set manufacturer via ShadowBuild

### ISSUE THREAD

**Issue by danijel-vrecic** [robolectric/robolectric#8175]
### Description
Cannot set the value of final field public static final java.lang.String android.os.Build.MANUFACTURER
### Steps to Reproduce
```    
@Test
fun `Shadow manufacturer`() {
    ShadowBuild.setManufacturer("robo")
    assertEquals(Build.MANUFACTURER, "robo")
}
```

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot set the value of final field public static final java.lang.String android.os.Build.MANUFACTURER
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Cannot set the value of final field public static final java.lang.String android.os.Build.MANUFACTURER
	at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:227)
	at org.robolectric.shadows.ShadowBuild.setManufacturer(ShadowBuild.java:76)
	at si.hub.utils.DummyTest.Set manufacturer dummy test(DummyTest.kt:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
```
### Robolectric & Android Version

**Robolectric version:** 4.10

**Android Studio Flamingo | 2022.2.1**
Build #AI-222.4459.24.2221.9862592, built on March 31, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    gradle.version.catalogs.dynamic.support=true

Non-Bundled Plugins: idea.plugin.protoeditor (222.4459.16)

**Comment by danijel-vrecic** [comment]
Clearing the cache solved the error.

**Comment by mitchellplass** [comment]
Which cache did you clear? I'm currently facing the same issue and can't solve it.
