### ISSUE TITLE
Flaky SHA mismatch on CI builds when retrieving Maven artifacts since upgrading to 4.10.x

### ISSUE THREAD

**Issue by mannodermaus** [robolectric/robolectric#8205]
### Description
A few days ago, I've started to experience flaky failures in some unit tests backed by Robolectric after having updated from 4.9 to 4.10.2. The failure has yet to happen on my local environment, but CI logs point to a failure when trying to download Robolectric files via `MavenArtifactFetcher`. The example below points to Android 11, but I've seen this error happen with other SDK levels, too.

For reference, my project is using JDK 17, Android Gradle Plugin 8.0.1 and Gradle 8.1.1.

```
DefaultBiometricManagerTestsApi30 > weak face recognition FAILED
    java.lang.AssertionError: Failed to fetch maven artifact org.robolectric:android-all-instrumented:11-robolectric-6757853-i4
        at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:115)
        at org.robolectric.internal.dependency.MavenDependencyResolver.lambda$getLocalArtifactUrls$0(MavenDependencyResolver.java:93)
        at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:113)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:88)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:78)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrl(MavenDependencyResolver.java:129)
        at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:89)
        at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:148)
        at org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader.<init>(AndroidSandbox.java:128)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.robolectric.util.inject.Injector.inject(Injector.java:250)
        (...)
        
        Caused by:
        java.util.concurrent.ExecutionException: java.lang.AssertionError: SHA512 mismatch for JAR file fetched in org.robolectric:android-all-instrumented:11-robolectric-6757853-i4
            at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
            at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
            at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
            at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:107)
            ... 77 more

            Caused by:
            java.lang.AssertionError: SHA512 mismatch for JAR file fetched in org.robolectric:android-all-instrumented:11-robolectric-6757853-i4
                at org.robolectric.internal.dependency.MavenArtifactFetcher.lambda$fetchArtifact$0(MavenArtifactFetcher.java:93)
                at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:165)
                at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:153)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce
I'm not sure, as it only happens once every five or six attempts.

### Robolectric & Android Version
- Robolectric 4.10.2
- Observed with artifact versions `11-robolectric` and `8-robolectric`

### Link to a public git repo demonstrating the problem:
-/-

**Comment by hoisie** [comment]
If this is happening it means that the android-all jar files, which are fetched by Robolectric during runtime, are either incomplete or get corrupted. If you have access to the CI machines, you could ssh to them after the error happens and check out what's in `$HOME/.m2/repository/org/robolectric/android-all-instrumented` and see what is happening with the files.

**Comment by mannodermaus** [comment]
Thanks for the quick response! It took several attempts, but eventually I was able to encounter an SSH-enabled CI run that triggered the issue again.

The files look okay and the fingerprint seems to match the `.jar.sha512` file downloaded into the M2 repository. There is no newline at the end of the checksum, but I don't know if that's expected or not. Regardless of the matching data, the job itself failed with the same trace mentioned above:

```
java.lang.AssertionError: Failed to fetch maven artifact org.robolectric:android-all-instrumented:7.0.0_r1-robolectric-r1-i4
        at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:115)
        Caused by:
        java.util.concurrent.ExecutionException: java.lang.AssertionError: SHA512 mismatch for JAR file fetched in org.robolectric:android-all-instrumented:7.0.0_r1-robolectric-r1-i4
```

Does any of the following screenshots look odd to you? If not, it may be possible that the CI simply ran out of memory while trying to do the SHA512 verification.

<img width="900" alt="Screenshot 2023-05-15 at 10 06 24" src="https://github.com/robolectric/robolectric/assets/3897705/d6407cf4-a917-412f-b232-86a4eda927ed">



<img width="900" alt="Screenshot 2023-05-15 at 10 01 11" src="https://github.com/robolectric/robolectric/assets/3897705/bb2c2bb5-05d4-440d-bd00-bb1d602c1b92">



<img width="900" alt="Screenshot 2023-05-15 at 10 06 55" src="https://github.com/robolectric/robolectric/assets/3897705/4bcd5e57-d800-44cc-ba28-8c1d5097ed5d">

**Comment by hoisie** [comment]
@mannodermaus as a workaround, you could use a script to pre-fetch the instrumented JARS. I could be a step in the CI.

See @utzcoz's script: https://github.com/utzcoz/robolectric-android-all-fetcher/blob/main/fetch-robolectric-preinstrumented-dependencies.sh

It would be useful to have more debugging info for this situation, e.g. what is the expected SHA-512, and what the actual value is. It could potentially be a file system / file syncing issue.

**Comment by mannodermaus** [comment]
Thanks @hoisie, I've added a CI step based on the link you shared and will observe if it improves the reliability of the unit tests. My reminder is set to 1 week from now, let's see where this goes. 🙇‍♂️

**Comment by hoisie** [comment]
FYI we are probably going to release a 4.10.3 for some other minor fixes, I'll add some additional logging for this issue and maybe add an `File.sync` to see if that helps.

**Comment by hoisie** [comment]
FYI 4.10.3 was released which added a FileDescriptor.sync call and additional logging. Are you able to give it a try?

**Comment by mannodermaus** [comment]
Thanks for the ping @hoisie. I unearthed a former branch where I had encountered the issue (prior to adding the CI step mentioned above), updated it to 4.10.3 and gave it a couple of spins. Within a few tries, the issue did in fact happen again. Interestingly, the SHAs reported by `MavenArtifactFetcher` are actually different. Stack trace below.

```
    java.lang.AssertionError: Failed to fetch maven artifact org.robolectric:android-all-instrumented:11-robolectric-6757853-i4
        at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:129)
        at org.robolectric.internal.dependency.MavenDependencyResolver.lambda$getLocalArtifactUrls$0(MavenDependencyResolver.java:93)
        at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:113)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:88)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:78)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrl(MavenDependencyResolver.java:129)
        at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:89)
        at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:148)
        at org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader.<init>(AndroidSandbox.java:128)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        ...

        Caused by:
        java.util.concurrent.ExecutionException: ja
va.lang.AssertionError: SHA-512 mismatch for POM file for org.robolectric:android-all-instrumented:11-robolectric-6757853-i4, expected SHA-512=836f65c0786b4d66c46617e76b26be06a3125dba2434e169e901e5432b9d847202b5c8e5fa473fd312ae3aeececb415b2c85070a2877834a80757819557c31f9, actual SHA-512=5b992e15f0a46c808066620650898aad1a3f323d3e219199979f255d5cecc4990b477707cc48ed51f034185c52c1ce83e8d8950c384729b8fa5a995556841c0d
            at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
            at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
            at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
            at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:121)
            ... 77 more

            Caused by:
            java.lang.AssertionError: SHA-512 mismatch for POM file for org.robolectric:android-all-instrumented:11-robolectric-6757853-i4, expected SHA-512=836f65c0786b4d66c46617e76b26be06a3125dba2434e169e901e5432b9d847202b5c8e5fa473fd312ae3aeececb415b2c85070a2877834a80757819557c31f9, actual SHA-512=5b992e15f0a46c808066620650898aad1a3f323d3e219199979f255d5cecc4990b477707cc48ed51f034185c52c1ce83e8d8950c384729b8fa5a995556841c0d
                at org.robolectric.internal.dependency.MavenArtifactFetcher.lambda$fetchArtifact$0(MavenArtifactFetcher.java:107)
                at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:165)
                at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:153)
                at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by hoisie** [comment]
Weird, I am not 100% sure what is going on here.  I am not sure where `5b992e15f0a46c808066620650898aad1a3f323d3e219199979f255d5cecc4990b477707cc48ed51f034185c52c1ce83e8d8950c384729b8fa5a995556841c0d` is coming from. Perhaps it is the jar file but truncated?

```sh
$ curl https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented/11-robolectric-6757853-i4/android-all-instrumented-11-robolectric-6757853-i4.jar.sha512
836f65c0786b4d66c46617e76b26be06a3125dba2434e169e901e5432b9d847202b5c8e5fa473fd312ae3aeececb415b2c85070a2877834a80757819557c31f9
```

If pre-fetching the android-all works for you I'd recommend sticking to that for now. Maybe if other people run into this issue we can investigate. I can potentially see some kind of retry mechanism, but if we don't understand the root cause her we'd just be taking stabs in the dark.

**Comment by mannodermaus** [comment]
Given the other symptoms of the CI machine when this issue occurs, I still think that it runs out of memory at some point and doesn't grasp the entire file when calculating the SHA-512 hash. I feel like the additional logging is already proof enough that the mechanism in Robolectric seems to work fine and it's likely tied to external circumstances.

Thanks again for investigating this!

**Comment by hoisie** [comment]
@mannodermaus I don't think calculating the SHA-512 should take up too much memory. It does it block-by-block, and it doesn't keep the entire file in memory.

**Comment by utzcoz** [comment]
@mannodermaus @hoisie Is it possible to meld the binary of these two files? Maybe we can learn more with diff result.

**Comment by mikolajdemkowww** [comment]
We have similar problem with our CI builds. Should we disable somehow downloading artifacts during tests after doing prefetching @hoisie ? Or will robolectric check itself that the deps are already there?

**Comment by CoenQian** [comment]
```shell
ERROR: Failed to fetch maven artifact org.robolectric:android-all-instrumented:14-robolectric-10818077-i4
java.util.concurrent.ExecutionException: java.lang.AssertionError: SHA-512 mismatch for POM file for org.robolectric:android-all-instrumented:14-robolectric-10818077-i4, expected SHA-512=4a97051b94f5cf3e69770aff8df96e89954ed4ea315fee48959350fdc9d63a151468a11e30126e80655628ca01c983bbcda44cc9614f4ce6e06daaa5e49d1c5b, actual SHA-512=7859ffb02ba36151931fc637921f88c7f59b33d1ebb6197e38b477646d696969386cdf28f9b3bff200992227a65cb26a5ab06a9bc40b3f8ac4bcba3fc7d1dc09
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
	at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:121)
	at org.robolectric.internal.dependency.MavenDependencyResolver.lambda$getLocalArtifactUrls$0(MavenDependencyResolver.java:93)
	at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:113)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:88)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:78)
	at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrl(MavenDependencyResolver.java:129)
	at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:95)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:143)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:414)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:389)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:389)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:278)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:250)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:247)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.robolectric.RuntimeEnvironment.lambda$getApplication$0(RuntimeEnvironment.java:80)
	at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1201)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:80)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:215)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:340)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:281)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: SHA-512 mismatch for POM file for org.robolectric:android-all-instrumented:14-robolectric-10818077-i4, expected SHA-512=4a97051b94f5cf3e69770aff8df96e89954ed4ea315fee48959350fdc9d63a151468a11e30126e80655628ca01c983bbcda44cc9614f4ce6e06daaa5e49d1c5b, actual SHA-512=7859ffb02ba36151931fc637921f88c7f59b33d1ebb6197e38b477646d696969386cdf28f9b3bff200992227a65cb26a5ab06a9bc40b3f8ac4bcba3fc7d1dc09
	at org.robolectric.internal.dependency.MavenArtifactFetcher.lambda$fetchArtifact$0(MavenArtifactFetcher.java:107)
	at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:165)
	at com.google.common.util.concurrent.CombinedFuture$AsyncCallableInterruptibleTask.runInterruptibly(CombinedFuture.java:153)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	... 3 more
``` 

jdk: 17
gradle: 8.5

we have similar issue, files are downloaded from listed urls:

```kotlin
https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented/14-robolectric-10818077-i4/android-all-instrumented-14-robolectric-10818077-i4.jar

https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented/14-robolectric-10818077-i4/android-all-instrumented-14-robolectric-10818077-i4.jar.sha512

https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented/14-robolectric-10818077-i4/android-all-instrumented-14-robolectric-10818077-i4.pom

https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented/14-robolectric-10818077-i4/android-all-instrumented-14-robolectric-10818077-i4.pom.sha512
```
