### ISSUE TITLE
not support for queryIntentActivities(Intent intent, ResolveInfoFlags flags) of Android 13

### ISSUE THREAD

**Issue by qq549631030** [robolectric/robolectric#8215]
### Description
when calling packageManager.queryIntentActivities(intent, ResolveInfoFlags.of(PackageManager.MATCH_DEFAULT_ONLY)) on Android 13，it is fail
```
Caused by: java.lang.UnsupportedOperationException: sorry, not supporting public abstract android.content.pm.ParceledListSlice android.content.pm.IPackageManager.queryIntentActivities(android.content.Intent,java.lang.String,long,int) throws android.os.RemoteException yet!
	at org.robolectric.shadows.ShadowActivityThread$1.invoke(ShadowActivityThread.java:89)
	at jdk.proxy4/jdk.proxy4.$Proxy82.queryIntentActivities(Unknown Source)
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1432)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1417)
```

### Steps to Reproduce
just call packageManager.queryIntentActivities(intent, ResolveInfoFlags.of(PackageManager.MATCH_DEFAULT_ONLY)) on Android 13
### Robolectric & Android Version
robolectric 4.10.2
### Link to a public git repo demonstrating the problem:
none

**Comment by utzcoz** [comment]
I think it needs an extra support at `ShadowActivityThread#getPackageManager`. @qq549631030 Would you like to send a PR to support it?

**Comment by qq549631030** [comment]
here is the PR [8409](https://github.com/robolectric/robolectric/pull/8409)

**Comment by mikehardy** [comment]
I just bumped into this! Thank you @qq549631030 for logging it and for a PR, and @utzcoz for the responsive review, magnificent. Looking forward to the next release
