### ISSUE TITLE
Robolectric Tests which are using Databinding are failing with latest version

### ISSUE THREAD

**Issue by venugopalraog** [robolectric/robolectric#8232]
### Description
After updating Robolectric version to 4.9.2 and databinding-compiler to 7.4.1 it is giving error whenever I run tests on classes which has DataBinding implemented.

Can someone please suggest if there is any work around available for this issue?

### Steps to Reproduce

Updated Gradle plugin  - 7.4.1, robolectric to 4.9.2 and databinding-compiler to 7.4.1 getting below error.
error: 
data
java.lang.NoSuchFieldError: data
...
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:510)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:623)
...
at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:580)
at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:287)
at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.

**Comment by venugopalraog** [comment]
Closing the defect. It is fixed now.
