### ISSUE TITLE
Getting android.view.InflateException for a custom view in library (.aar)

### ISSUE THREAD

**Issue by sitaram168** [robolectric/robolectric#8238]
### Description
Hello, 

I have a multi modular app. I am trying to write UI test in one module. In the test environment, this module can access all the other modules of the app. 
Code under test is using a custom view present in a library (.aar). I am getting android.view.InflateException at the point when it's trying to inflate a layout in/of library. Found older discussions on using exploded aar or using enableUnitTestBinaryResources. But unfortunatly they all are deprecated now and not working. Here's the exception

```
android.view.InflateException: Binary XML file line #18 in....
Error inflating class com.abc.xyz.CustomView
...
...
Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```

Please let me know if I am missing anything here.

### Steps to Reproduce
Create a fragment and use a custom view from a library in the fragment's layout file.
Use activity scenario to launch host activity
Use fragment transaction to add fragment. (can't use fragment scenario in my case)
write any assertion like fragment visible or not.
Issue - Fragment creation fails when inflating the layout.

### Robolectric & Android Version
Robo : 4.8.x and 4.10.3
Android target SDK : 33

**Comment by hoisie** [comment]
It seems like you excluded most of the stack trace, which is the most important part. As-is this issue isn't actionable. Setting up activities and fragments is very well supported in Robolectric.

**Comment by hoisie** [comment]
Looks like this is a custom view that is missing a constructor. Ensure that your custom view has all the necessary constructors.

**Comment by sitaram168** [comment]
Actually it works fine when running the app. 

Also, i noticed below part of stack trace, which i think is the main reason. Layout which is failing to inflate is using styled attributes from the app theme. But even when i apply the theme i get this exception :(. 
```
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f040171 a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:597)
	at android.widget.TextView.readTextAppearance(TextView.java:3989)
	at android.widget.TextView.__constructor__(TextView.java:1089)
	at android.widget.TextView.<init>(TextView.java)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:108)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:103)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:201)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:121)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1569)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1620)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
```

**Comment by sitaram168** [comment]
Issue solved. as mentioned, it was due to missing theme in the module under test. when applying the right theme, issue got fixed. Thanks for the help.

**Comment by acquired-2d-games** [comment]
@hoisie https://stackdev.space/questions/update-the-textview-element-in-contentmainxml-from-mainactivityjava
