### ISSUE TITLE
API 28 UI Tests Failing with Crash

### ISSUE THREAD

**Issue by gavinweng** [robolectric/robolectric#8253]
### Description
When an activity's content view contains `android.widget.ProgressBar`, the activity creation will fail.

```
                    Caused by:
                    android.content.res.Resources$NotFoundException: File res/drawable/progress_medium_material.xml from drawable resource ID #0x10806b2
                        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:847)
                        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:631)
                        at java.base@11.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at java.base@11.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at java.base@11.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at org.robolectric.shadows.ShadowArscResourcesImpl$ResourcesImplReflector$$Reflector71.loadDrawable(Unknown Source)
                        at org.robolectric.shadows.ShadowArscResourcesImpl.loadDrawable(ShadowArscResourcesImpl.java:169)
                        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
                        at android.content.res.Resources.loadDrawable(Resources.java:897)
                        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:955)
                        at android.content.res.TypedArray.getDrawable(TypedArray.java:930)
                        at android.widget.ProgressBar.__constructor__(ProgressBar.java:281)
                        at android.widget.ProgressBar.<init>(ProgressBar.java)
                        at java.base@11.0.6/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                        ......

                        Caused by:
                        android.view.InflateException: Class not found com.android.internal.graphics.drawable.AnimationScaleListDrawable
                            at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:222)
                            at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:139)
                            at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
                            at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
                            at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:833)
                            ... 43 more

                            Caused by:
                            java.lang.ClassNotFoundException: com.android.internal.graphics.drawable.AnimationScaleListDrawable
                                at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
                                at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
                                at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
                                at android.graphics.drawable.DrawableInflater.$$robo$$android_graphics_drawable_DrawableInflater$inflateFromClass(DrawableInflater.java:203)
                                at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java)
                                at android.graphics.drawable.DrawableInflater.$$robo$$android_graphics_drawable_DrawableInflater$inflateFromXmlForDensity(DrawableInflater.java:139)
                                at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java)
                                at android.graphics.drawable.Drawable.$$robo$$android_graphics_drawable_Drawable$createFromXmlInnerForDensity(Drawable.java:1332)
                                at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java)
                                at android.graphics.drawable.Drawable.$$robo$$android_graphics_drawable_Drawable$createFromXmlForDensity(Drawable.java:1291)
                                at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java)
                                at android.content.res.ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadDrawableForCookie(ResourcesImpl.java:833)
                                at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java)
                                at android.content.res.ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadDrawable(ResourcesImpl.java:631)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                at org.robolectric.shadows.ShadowArscResourcesImpl$ResourcesImplReflector$$Reflector71.loadDrawable(Unknown Source)
                                at org.robolectric.shadows.ShadowArscResourcesImpl.loadDrawable(ShadowArscResourcesImpl.java:169)
                                at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java)
                                at android.content.res.Resources.$$robo$$android_content_res_Resources$loadDrawable(Resources.java:897)
                                at android.content.res.Resources.loadDrawable(Resources.java)
                                at android.content.res.TypedArray.$$robo$$android_content_res_TypedArray$getDrawableForDensity(TypedArray.java:955)
                                at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java)
                                at android.content.res.TypedArray.$$robo$$android_content_res_TypedArray$getDrawable(TypedArray.java:930)
                                at android.content.res.TypedArray.getDrawable(TypedArray.java)
                                at android.widget.ProgressBar.$$robo$$android_widget_ProgressBar$__constructor__(ProgressBar.java:281)
                                at android.widget.ProgressBar.<init>(ProgressBar.java)
                                at android.widget.ProgressBar.<init>(ProgressBar.java)
                                at android.widget.ProgressBar.<init>(ProgressBar.java)
```
### Steps to Reproduce
Write a test activity with `android.widget.ProgressBar`, confirm that on API 24 (@Config(sdk = 24)), the creation doesn't fail, but on API 28+ the creation fail with the above stacktrace.

### Robolectric & Android Version
Robolectric: 4.10.3
Android version: 28+
Android Gradle Plugin: 7.1.3

**Comment by utzcoz** [comment]
Or what about checking whether you have enable includeAndroidResources as https://github.com/robolectric/robolectric/issues/3939 said.

**Comment by hoisie** [comment]
Can you please capture this issue as a failing test, or provide the problematic snippet of layout XML? Which attributes of ProgressBar is being used? There is test coverage for ProgressBar here, so it is known to work:

https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowProgressBarTest.java

**Comment by gavinweng** [comment]
After some debugging, finally figure out the culprit.

In our app code, we are creating our own implementation of `Resources` via 
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/res/Resources.java;l=315
 
Unfortunately, this ends up with
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/res/Resources.java;l=330
`mClassLoader = classLoader == null ? ClassLoader.getSystemClassLoader() : classLoader;`
Hence, the drawable inflater in the test is actually not using the correct class loader, hence causing the problem.

We can close this issue.

**Comment by utzcoz** [comment]
@gavinweng Thanks for your confirmation. IMO, I don't recommend to shadow custom internal classes except you need some special fixes or configurations but upstream doesn't have. If you have these needs, we recommend to send a PR to upstream them, and we can release a new version for it if it is very important to you.
