### ISSUE TITLE
Robolectric NATIVE GraphicsMode fails when running on Windows machine

### ISSUE THREAD

**Issue by luizgrp** [robolectric/robolectric#8312]
### Description

Contributors to our project using Windows machine [reported](https://github.com/google/horologist/pull/1423#discussion_r1233190184) the following issue when trying to run our test suite:

```
resource native/windows/x86_64/robolectric-nativeruntime.dll not found.
java.lang.IllegalArgumentException: resource native/windows/x86_64/robolectric-nativeruntime.dll not found.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at com.google.common.io.Resources.getResource(Resources.java:194)
	at org.robolectric.nativeruntime.DefaultNativeRuntimeLoader.loadLibrary(DefaultNativeRuntimeLoader.java:154)
```

```
'long org.robolectric.nativeruntime.RenderNodeNatives.nCreate(java.lang.String)'
java.lang.UnsatisfiedLinkError: 'long org.robolectric.nativeruntime.RenderNodeNatives.nCreate(java.lang.String)'
	at org.robolectric.nativeruntime.RenderNodeNatives.nCreate(Native Method)
	at org.robolectric.shadows.ShadowNativeRenderNode.nCreate(ShadowNativeRenderNode.java:22)
	at android.graphics.RenderNode.nCreate(RenderNode.java)
```

### Steps to Reproduce

1. Open project from repository: https://github.com/google/horologist
2. Run any test class that inherits [ScreenshotBaseTest](https://github.com/google/horologist/blob/3fdf591068b735d4b72fd2c75aaee226aae87e0d/roboscreenshots/src/main/java/com/google/android/horologist/screenshots/ScreenshotBaseTest.kt), e.g. [ChipA11yTest](https://github.com/google/horologist/blob/3fdf591068b735d4b72fd2c75aaee226aae87e0d/compose-material/src/test/java/com/google/android/horologist/compose/material/ChipA11yTest.kt).

### Robolectric & Android Version

4.10.3
API 30

### Link to a public git repo demonstrating the problem:

- Repository: https://github.com/google/horologist
- Test: [ChipA11yTest](https://github.com/google/horologist/blob/3fdf591068b735d4b72fd2c75aaee226aae87e0d/compose-material/src/test/java/com/google/android/horologist/compose/material/ChipA11yTest.kt)
- Details of the robolectric configuration: [ScreenshotBaseTest](https://github.com/google/horologist/blob/3fdf591068b735d4b72fd2c75aaee226aae87e0d/roboscreenshots/src/main/java/com/google/android/horologist/screenshots/ScreenshotBaseTest.kt);
- Failure in CI: https://github.com/google/horologist/pull/1432

**Comment by utzcoz** [comment]
@luizgrp Sorry, RNR doesn't support Windows platform now. cc @hoisie will RNR have a plan to support windows?

**Comment by yschimke** [comment]
Does it work in WSL?

https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html#local_project

**Comment by utzcoz** [comment]
@yschimke I think it might support as RNR only needs necessary common so files.

**Comment by sergio-sastre** [comment]
@hoisie @utzcoz 
Any hints on what need to be adjusted?
I use a Windows PC for work and support with finding a fix for this (I can actually reproduce the error), but I do not know what needs to be done 😅

**Comment by yschimke** [comment]
Is this the artifact with libraries? https://mvnrepository.com/artifact/org.robolectric/nativeruntime-dist-compat/1.0.1

Seems to have only linux and mac.

```
./linux
./linux/x86_64
./linux/x86_64/librobolectric-nativeruntime.so
./mac
./mac/x86_64
./mac/x86_64/librobolectric-nativeruntime.dylib
./mac/aarch64
./mac/aarch64/librobolectric-nativeruntime.dylib
```

**Comment by hoisie** [comment]
Unfortunately native graphics mode is not supported on Windows at the moment. It is only supported on Mac and Linux. We should probably be more explicit about this. It is technically feasible to support it, but it just requires a nontrivial amount of developer time. There are some things in the future that may help with supporting Windows, but we don't anticipate it being supported any time in the near future.

**Comment by yschimke** [comment]
I confirmed this is working perfectly well on WSL 2. 

WSL is supported by Jetbrains, so both Intellij and Android Studio work fine. https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html

**Comment by yschimke** [comment]
That's great thanks. Really appreciated.
