### ISSUE TITLE
Process 'Gradle Test Executor XX' finished with non-zero exit value 10

### ISSUE THREAD

**Issue by alwa** [robolectric/robolectric#8395]
### Description
With a larger test suite (my project has 3000+ tests) Gradle seems to give up and ultimately crashes. This is likely due to a memory leak somewhere but very difficult to pinpoint since single test classes pass when run in isolation.

Crash log below obtained using `--debug`

```
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@2a728e8e.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: processTestClass(DefaultTestClassRunInfo(com.mycompany.MyTest))].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 24' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.1.1/userguide/java_testing.html#sec:test_execution
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:161)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.processTestClass(RestartEveryNTestClassProcessor.java:55)
	at jdk.internal.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	... 10 more
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@1f5a2b69.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: stop()].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 36' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
```

Gradle config (Kotlin DSL):

```
    testOptions {
        unitTests.isReturnDefaultValues = true
        unitTests.isIncludeAndroidResources = true
        unitTests.all { test ->
            test.failFast = false
            test.testLogging {
                events.addAll(listOf(PASSED, SKIPPED, FAILED))
                showCauses = true
                showExceptions = true
                exceptionFormat = FULL
            }
            test.forkEvery = 18L
            test.maxHeapSize = "3g"
            // Workaround from https://github.com/robolectric/robolectric/issues/5456#issuecomment-1096432087
            test.systemProperty("robolectric.dependency.repo.id'", "mavenCentral")
            test.systemProperty(
                "robolectric.dependency.repo.url",
                "https://artifacts.assaabloy.net/nexus/repository/maven-central/"
            )
        }
    }
```

Note: Removing `test.forkEvery` causes the tests to fail even sooner.

### Steps to Reproduce
Big suite of tests where individually executed tests pass

### Robolectric & Android Version
Robolectric 4.10.3
minSdk 30
targetSdk 34
JDK 17

Related:
https://github.com/gradle/gradle/issues/16397

**Comment by alwa** [comment]
> @alwa Could you rerun them with JDK 11 to test crash behavior? I also suspect similar issues when trying to use JDK 17 + AGP 8.x to run Robolectric repository's tests.

Unfortunately Android Gradle Plugin 8.1.0 doesn't allow it:

> com.android.builder.errors.EvalIssueException: Android Gradle plugin requires Java 17 to run. You are currently using Java 11.

I'll see how easy it is for  me to downgrade to test it...

**Comment by alwa** [comment]
After downgrading AGP to 7.4.2 and a few dependencies (newer versions compiled for Java 17) I was able to run the test suite without any other code changes.

What I notice in the logs is that there are a few issues also when running on Java  11 but they do not fail the build so it looks like it affects only test fixture teardown:

Issue 1:
```
com.mycompany.MyTest2 >testName PASSED
ERROR: Failed to destroy temp directory
java.nio.file.FileSystemException: C:\Users\MyUser\AppData\Local\Temp\robolectric-MyTestName_17851688733026503335\com.mycompany-dataDir\databases\mixpanel: Det går inte att komma åt filen eftersom den
används av en annan process.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1141)
	at org.robolectric.util.TempDirectory$1.visitFile(TempDirectory.java:122)
	at org.robolectric.util.TempDirectory$1.visitFile(TempDirectory.java:119)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:119)
	at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
It says that the file is used by another process and therefore cannot be deleted. Mixpanel in this case refers to a dependency used in the project: https://github.com/mixpanel/mixpanel-android

Issue 2:
```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:53162'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: En befintlig anslutning tvingades att st�nga av fj�rrv�rddatorn
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:148)
	at com.esotericsoftware.kryo.io.Input.require(Input.java:178)
	at com.esotericsoftware.kryo.io.Input.readByte(Input.java:295)
	at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readByte(KryoBackedDecoder.java:88)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:64)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 6 more
Caused by: java.io.IOException: En befintlig anslutning tvingades att st�nga av fj�rrv�rddatorn
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:196)
	at com.esotericsoftware.kryo.io.Input.fill(Input.java:146)
	... 12 more
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:53162'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:140)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:333)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: En befintlig anslutning tvingades att st�nga av fj�rrv�rddatorn
	at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:279)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:267)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:261)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:138)
	... 6 more
> Task :application:testDebugUnitTest
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@3fff3e9f.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: stop()].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 3' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.1.1/userguide/java_testing.html#sec:test_execution
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:161)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	... 10 more
Could not stop org.gradle.internal.actor.internal.DefaultActorFactory$NonBlockingActor@3404f3f6.
org.gradle.internal.dispatch.DispatchException: Could not dispatch message [MethodInvocation method: stop()].
	at org.gradle.internal.dispatch.ExceptionTrackingFailureHandler.dispatchFailed(ExceptionTrackingFailureHandler.java:35)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:32)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 2' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.1.1/userguide/java_testing.html#sec:test_execution
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:161)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	... 10 more
 ```
This looks related to the fatal issue(s) in Java 17

The whole build fails with:
```
com.assaabloy.stg.cliq.go.android.VersionTest > meta - always - version code always follows scheme SKIPPED
> Task :application:testDebugUnitTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':application:testDebugUnitTest'.
> Process 'Gradle Test Executor 5' finished with non-zero exit value 10
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.1.1/userguide/java_testing.html#sec:test_execution
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':application:testDebugUnitTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 5' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
Please refer to the test execution section in the User Manual at https://docs.gradle.org/8.1.1/userguide/java_testing.html#sec:test_execution
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:161)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.stop(RestartEveryNTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.FailureHandlingDispatch.dispatch(FailureHandlingDispatch.java:30)
	at org.gradle.internal.dispatch.AsyncDispatch.dispatchMessages(AsyncDispatch.java:87)
	at org.gradle.internal.dispatch.AsyncDispatch.access$000(AsyncDispatch.java:36)
	at org.gradle.internal.dispatch.AsyncDispatch$1.run(AsyncDispatch.java:71)
	at org.gradle.internal.concurrent.InterruptibleRunnable.run(InterruptibleRunnable.java:42)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
* Get more help at https://help.gradle.org
BUILD FAILED in 13m 15s
```

**Comment by alixwar** [comment]
> @alixwar I have tried `org.gradle.caching=false`, but it didn't work for me. I think we might need to find the root cause of this issue.

Sure, just keep in mind that enabling caching may impact whether or not the issue is reproducible. At least it was in my case. But I can easily trigger the problem again even without cache but at least the result is deterministic w/o cache.

**Comment by alixwar** [comment]
FYI: I'm still seeing this issue on Gradle 8.7 / Robolectric 4.12.1 / AGP 8.3.2

**Comment by RngNoah** [comment]
Is there any way to solve this problem?

**Comment by patrickpilch** [comment]
This occurred for me after I introduced a [StrictMode.VmPolicy](https://developer.android.com/reference/android/os/StrictMode.VmPolicy) with [policyDeath](https://developer.android.com/reference/android/os/StrictMode.VmPolicy.Builder#penaltyDeath()). 

[The implementation](https://github.com/aosp-mirror/platform_frameworks_base/blob/211ebf1318d828edbca2508f7c815ba371019e82/core/java/android/os/StrictMode.java#L2450-L2454) calls `System.exit(10)` which explained my error code.

**Comment by imansdn** [comment]
I added `@org.robolectric.annotation.experimental.LazyApplication` to the test class and it resolved the issue.

**Comment by rwrx** [comment]
I do have the same issue:

```
Invalid ID 0x00000000.
Invalid ID 0x00000000.
ERROR: Failed to destroy temp directory
java.nio.file.DirectoryNotEmptyException: /tmp/robolectric-nativeruntime6870907116209885458/fonts
	at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:246)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at org.robolectric.util.TempDirectory$1.postVisitDirectory(TempDirectory.java:174)
	at org.robolectric.util.TempDirectory$1.postVisitDirectory(TempDirectory.java:160)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:158)
	at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:141)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

gradle.properties:

```
org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
```

Robolectric and Android Version

```
Robolectric 4.13
minSdk 23
targetSdk 34
JDK 17
```

I have also tried to set `org.gradle.caching=false`. But it did not helped. Is there a fix for this issue?

**Comment by carstenhag** [comment]
I tried pretty much everything mentioned here, apart from downgrading AGP/Gradle. This issue is only occurring for me on a CI pipeline, and only on a PR where I am modifying some existing tests and classes. I've set `@Ignore`, `org.gradle.caching=false`, `@LazyApplication` etc.

Robolectric `4.14.1`, OpenJDK 17 on ubuntu 24.04, AGP 8.9.0 

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:testBrandB2CEnvIntegrationDebugUnitTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:130)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:293)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:128)
...

Caused by: org.gradle.process.internal.ExecException: Process 'Gradle Test Executor 1' finished with non-zero exit value 10
This problem might be caused by incorrect test process configuration.
For more on test execution, please refer to https://docs.gradle.org/8.13/userguide/java_testing.html#sec:test_execution in the Gradle documentation.
	at org.gradle.api.internal.tasks.testing.worker.ForkingTestClassProcessor.stop(ForkingTestClassProcessor.java:161)
	at org.gradle.api.internal.tasks.testing.processors.RestartEveryNTestClassProcessor.endBatch(RestartEveryNTestClassProcessor.java:77)
...

```

**Comment by carstenhag** [comment]
I troubleshooted further and found that the issue was not appearing when running tests via the Android Studio UI, but the error did occur by running the exact same gradle task via CLI.

Some tests were throwing `MockKException` -- but this was not shown on the regular logs. I had to run `./gradlew testDebugUnitTest -d` to get these logs:


```
2025-05-19T13:45:48.011+0200 [DEBUG] [TestEventLogger] TripPlannerViewModelTest > selectStop_poolDataAvailable_notCurrentPool_selectStation STANDARD_ERROR
2025-05-19T13:45:48.011+0200 [DEBUG] [TestEventLogger]     Exception in thread "Test worker @coroutine#32" io.mockk.MockKException: no answer found for IFavoriteFillingStationService(favoriteFillingStationService#171).getFavorites() among the configured answers: ()
2025-05-19T13:45:48.011+0200 [DEBUG] [TestEventLogger]     	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:93)
```

After fixing the mocking errors it worked flawlessly.


Weirdly enough, when I ran tests for a specific package containing the tests (~50 tests, see command below) or ran a specific test, it did not fail even via CLI.   
But as soon as I ran a package containing hundreds or all tests, it failed.

`./gradlew :app:testBrandB2CEnvIntegrationDebugUnitTest --tests "com.bmw.chargenow.presentation.views.tripplanner.*" -d`

**Comment by alixwar** [comment]
To leave some breadcrumbs for myself (and others) I thought I'd give an update on this ticket.
I'm no longer seeing this issue. Here's my current tech stack:

```
Robolectric 4.16.1
minSdk 33
targetSdk 36
JDK 21
AGP 8.13.2
Gradle 9.5.1
```

In general I think this issue can happen when coroutines are not carefully managed. Coroutine scopes should be injected into tests.
Also, I found a "fix", that helped for me, for addressing possibly related heap space issues on large test suites:

Previous config, that failed me:
```
 unitTests.all { test ->
                test.also { testTask ->
                    testTask.maxHeapSize = "4g"
               }
}
```

New config that works much better:
```
unitTests.all { test ->
                test.also { testTask ->
                    testTask.maxHeapSize = "1536m"
                    testTask.forkEvery = 1L
                    testTask.maxParallelForks = 1
                    testTask.jvmArgs(
                        "-XX:+UseG1GC",
                        "-XX:MaxMetaspaceSize=512m",
                        "-XX:-DoEscapeAnalysis"
                    )
                }
}
```

**Comment by utzcoz** [comment]
@alixwar If you think your scenario is related to coroutine management, have you tried coroutine testing library and run your tests with `runTest`?

**Comment by alixwar** [comment]
@utzcoz Yes, definitely. Primarily for unit tests for suspend functions. But even with couroutines-test / runTest you can get into trouble.

**Comment by utzcoz** [comment]
@alixwar If you can provide a stable reproducible demo, I can try to analysis it this weekend.

**Comment by alixwar** [comment]
@utzcoz Thanks, but I'm currently not affected. Will do if it happens again! But most likely you need lots of tests, possibly also a combination of Mockk, Robolectric and maybe more, which is problematic
