### ISSUE TITLE
How to make robolectric work with ActionBarActivity

### ISSUE THREAD

**Issue by ufo22940268** [robolectric/robolectric#840]
When i using robolectric testing ActionBarActivity from support v7 package, it always gives the following error.

java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:102)
        at android.support.v7.app.ActionBarActivityDelegateICS.onCreate(ActionBarActivityDelegateICS.java:58)
        at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:98)
        at me.biubiubiu.rms.BaseActivity.onCreate(BaseActivity.java:59)
        at me.biubiubiu.rms.ItemBaseActivity.onCreate(ItemBaseActivity.java:54)
        at android.app.Activity.performCreate(Activity.java:5008)
        at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
        at org.robolectric.util.ActivityController$1.run(ActivityController.java:116)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:256)
        at org.robolectric.util.ActivityController.create(ActivityController.java:111)
        at org.robolectric.util.ActivityController.create(ActivityController.java:123)
        at me.biubiubiu.rms.ModelTest.clickingButton_shouldChangeResultsViewText(ModelTest.java:79)

And here is the code i use to launch this activity. 

`@Test
  public void clickingButton_shouldChangeResultsViewText() throws Exception {
    Activity activity = Robolectric.buildActivity(MyActivity.class).create().get();
  }`

**Comment by krzysztof-jelski** [comment]
Still present with 2.4.
I've started a fresh project in IDEA with Android support, generated an Activity with Fragment (which happens to extend ActionBarActivity), and experience the same error when running a test that creates the Activity.
Of course the app itself runs fine.
I suggest reopening the issue. It's also mentioned (and unanswered) in the [forums](https://groups.google.com/forum/#!searchin/robolectric/Theme.AppCompat/robolectric/HIhBIJDoAlU/2SuPekeDceMJ).

**Comment by erd** [comment]
This is working in 3.0-rc2. See the `android-appcompat-v7` sample in the `robolectric/robolectric-samples` repository.

**Comment by krzysztof-jelski** [comment]
Confirmed, works fine with 3.0-rc2.

**Comment by kluz88** [comment]
No, it's still present. I have this issue with 3.0-rc2 with AppCompatActivity from android-appcompat-v7 version 22.2.0.

**Comment by JaapWeijland** [comment]
I got the same problem with 3.0-rc2. Not fixed.

**Comment by dmapr** [comment]
I don't have a problem with the activity itself, but using the android.support.v7.app.AlertDialog causes the error.
```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
	at android.support.v7.app.AppCompatDialog.__constructor__(AppCompatDialog.java:48)
	at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java)
	at android.support.v7.app.AlertDialog.<init>(AlertDialog.java)
	at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:882)
```

**Comment by JorgeCastilloPrz** [comment]
Still happening for AppCompat lib. Using version 2.4 of Robolectric.
```java
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:122)
	at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
	at com.oneupsports.coreapp.ui.MainActivity.onCreate(MainActivity.java:47)
	at android.app.Activity.performCreate(Activity.java:5008)
	at org.robolectric.internal.ReflectionHelpers$3.run(ReflectionHelpers.java:64)
	at org.robolectric.internal.ReflectionHelpers.traverseClassHierarchy(ReflectionHelpers.java:114)
	at org.robolectric.internal.ReflectionHelpers.callInstanceMethodReflectively(ReflectionHelpers.java:59)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:115)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:268)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:122)
	at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:1388)
	at com.oneupsports.coreapp.XmlConfigurationParserTest.setup(XmlConfigurationParserTest.java:24)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by juanmendez** [comment]
What I did was to include the AndroidManifest.xml

@RunWith(RobolectricTestRunner.class)
@Config(manifest="app/src/main/AndroidManifest.xml")
public class TestMainActivity 

Then I got a runtimeexception saying it couldn't find any resource from reference ResName.

So What i did next was to go to the path of my project
app/src/main, so created a new file (project.properties) which is at the same level as the manifest file.

There I added in the new file the following.
android.library.reference.1=../../build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.0

and it worked!

And it worked..

**Comment by maboueita** [comment]
The problem still exists with AppCompatActivity and ActionBarActivity. Robolectric 3.0 and target SDK 22.

**Comment by juanmendez** [comment]
I don't see that problem @maboueita using

dependencies {
    .........
    testCompile "org.robolectric:robolectric:3.0-rc2"
    testCompile "junit:junit:4.12";
}

**Comment by wxsyy** [comment]
It works with @juanmendez 's method

**Comment by juanmendez** [comment]
I'm glad it worked for you @wxsyy !

**Comment by maboueita** [comment]
@juanmendez Unfortunately still not working, after double checking the dependencies and adding 
@Config(manifest="app/src/main/AndroidManifest.xml") to the Activity under test.

**Comment by juanmendez** [comment]
@maboueita hi, please look at my app which is being tested in Android 1.3

https://github.com/juanmendez/jm_android_dev/tree/master/10.services/02.intentService

make sure you have
https://github.com/juanmendez/jm_android_dev/tree/master/10.services/02.intentService/app/src/main

declare accordingly your robolectric dependency.
https://github.com/juanmendez/jm_android_dev/blob/master/10.services/02.intentService/app/build.gradle

check annotations on top of this class.
https://github.com/juanmendez/jm_android_dev/blob/master/10.services/02.intentService/app/src/test/java/ContentProviderTest.java

I hope this helps.

**Comment by krzysztof-jelski** [comment]
@juanmendez have you tried upgrading to robolectric-3.0? You still use 3.0-rc2 in your example.
I can't make it working with 3.0.

**Comment by juanmendez** [comment]
Is 3.0 an upgrade? or a downgrade? anyways I tried it and it also worked.

**Comment by juanmendez** [comment]
![capture](https://cloud.githubusercontent.com/assets/3371622/9330668/7e4c6a6e-4580-11e5-90f1-7a9d56b9a03e.PNG)
