### ISSUE TITLE
Robolectric Tests which are using Databinding are failing with latest version

### ISSUE THREAD

**Issue by lvankayala19** [robolectric/robolectric#8449]
### Description
After updating Robolectric version to 4.9.2 and databinding-compiler to 7.4.2 and gradleplugin is 7.4.2 it is giving error whenever I run tests on classes which has DataBinding implemented.

### Steps to Reproduce
Updated Gradle plugin - 7.4.2 robolectric to 4.9.2 and databinding-compiler to 7.4.2 getting below error.

java.lang.NoSuchFieldError: viewModel

	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1901)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1819)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1731)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:317)
	at com.intuit.coresdk.unitTestSupport.CoreSdkFragmentScenario$Companion.internalLaunch$lambda$2(CoreSdkFragmentScenario.kt:484)
	at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$androidx-test-core-app-ActivityScenario(ActivityScenario.java:789)

### Robolectric & Android Version
4.9.2

**Comment by MGaetan89** [comment]
@lvankayala19 did you try to apply the suggestion from the stacktrace?
> Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
