### ISSUE TITLE
Setting width or height in qualifier cause dialog with text field in compose test to freeze

### ISSUE THREAD

**Issue by vincent-paing** [robolectric/robolectric#8460]
### Description

Compose test  for Dialog and text field freeze with `AppIdleException` when specific size of width and height are configured in qualifier. 

### Steps to Reproduce

Run the following test and wait for a few minute, test will fail after app has timeout waiting for idle state

```kotlin
@RunWith(AndroidJUnit4::class)
@Config(qualifiers = "w360dp-h640dp", sdk = [30, 31, 32, 33])
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class ExampleTest {

  @get:Rule
  val composeTestRule = createComposeRule()

  @Test
  fun freezingTest() {
    composeTestRule.setContent {
      Mdc3Theme {
        Dialog(onDismissRequest = {}) {
          BasicTextField(value = "some value", onValueChange = {
          })
        }
      }
    }
  }
}
```

Removing the qualifier fixed the problem. The test freeze only if the text field is inside Dialog, maybe a specific interaction between `Dialog` and `TextField`.

### Robolectric & Android Version
Robolectric : 4.10.3
Android version: All version maybe but I tested on 30 - 33.

**Comment by saket** [comment]
Here's the error stacktrace for completeness:

```
androidx.test.espresso.AppNotIdleException: Compose did not get idle after 368330 attempts in 60 SECONDS. Please check your measure/layout lambdas, they may be causing an infinite composition loop. Or set Espresso's master idling policy if you require a longer timeout. The following Idle Conditions failed .
  at androidx.test.espresso.AppNotIdleException.create(AppNotIdleException.java:11)
  at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:55)
  at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
  at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:33)
  at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy.runUntilIdle(RobolectricIdlingStrategy.android.kt:48)
  at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.waitForIdle(ComposeUiTest.android.kt:336)
```

**Comment by hoisie** [comment]
Some of the Compose test utils assume that there is a separation between the test thread and the UI thread (e.g. it blocks the test thread to wait for UI events).

I think @brettchabot 's `@LooperMode(INSTRUMENTATION_TEST)` may help here.

**Comment by saket** [comment]
Sorry I don't think I fully understand this, how is the idling strategy affected by device qualifiers?

`LooperMode.Mode.INSTRUMENTATION_TEST` also seems to be incompatible with `ComposeUiTest` right now:

```
Method cannot be called on the main application thread (on: SDK 31 Main Thread) when running in LooperMode.INSTRUMENTATION_TEST
java.lang.IllegalStateException: Method cannot be called on the main application thread (on: SDK 31 Main Thread) when running in LooperMode.INSTRUMENTATION_TEST
	at com.google.common.base.Preconditions.checkState(Preconditions.java:601)
	at org.robolectric.android.internal.RobolectricThreadChecker.checkNotMainThread(RobolectricThreadChecker.java:31)
	at androidx.test.internal.util.Checks.checkNotMainThread(Checks.java:130)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:4)
	at androidx.test.espresso.Espresso.onIdle(Espresso.java:1)
	at androidx.compose.ui.test.junit4.EspressoLink_androidKt.runEspressoOnIdle(EspressoLink.android.kt:92)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:66)
	at androidx.compose.ui.test.junit4.RobolectricIdlingStrategy$runUntilIdle$1.invoke(RobolectricIdlingStrategy.android.kt:48)
	at androidx.compose.ui.test.junit4.AndroidSynchronization_androidKt.runOnUiThread$lambda$0(AndroidSynchronization.android.kt:37)
```

This crash originates from [ComposeUiTest.android.kt#L316](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-test-junit4/src/androidMain/kotlin/androidx/compose/ui/test/ComposeUiTest.android.kt;l=316;drc=76bc6975d1b520c545b6f8786ff5c9f0bc22bd1f).

**Comment by dennismozart1994** [comment]
Is there any updates on this? Before the `LooperMode.Mode.INSTRUMENTATION_TEST` was working as expected, but after updating compose that doesn't seem to be working any longer due to the exact same error described by @saket

**Comment by dennismozart1994** [comment]
just an FYI, it seems that with Compose 1.6.4 if we use the `LooperMode.Mode.LEGACY`, even though it's deprecated it seems to bypass this `AppNotIdleException` for the majority of the tests facing this issue. However, it needs to be added on case-by-case scenario (per test, not a single looper notation into the entire class) as some tests are just not working with the LEGACY looper (probably due to the lack of support) since some mocked android pointers are always null with that and the tests that were working can fail with a `NullPointerException` or another type of exception when using the deprecated LEGACY looper.

**Comment by adecker89** [comment]
Just ran into this on robolectric 4.16 with compose 1.9.1 and it took quite a while to figure out what was going on.
Luckily the `LooperMode.Mode.LEGACY` workaround did work for my use case, thanks for posting that.

**Comment by Toshik1978** [comment]
Still reproduces on Robolectric 4.16.1 / Compose Multiplatform 1.12.0 / Kotlin 2.4.10, SDK 35. Spent a few hours digging into it, then found this thread. But the workaround doesn't help, unfortunately. So, asked my LLM to prepare evidence. Maybe it can be helpful.

---
Narrowing it down, one variable at a time. The case I varied:

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35], qualifiers = "w340dp") // only this line changes below
class DialogFieldTest {
    @get:Rule val rule = createComposeRule()

    @Test
    fun loops() {
        rule.setContent {
            Dialog(onDismissRequest = {}) {
                BasicTextField(value = "x", onValueChange = {})
            }
        }
    }
}
```


**It's width only — not height, despite the title.**

| qualifier | result |
|---|---|
| `w300dp` | pass |
| `w320dp` | pass |
| `w340dp` | **loops** |
| `w360dp`, `w400dp`, `w480dp` | **loops** |
| `h891dp` (height only) | pass |
| `xhdpi` (density only) | pass |

So the threshold sits between 320dp and 340dp — 320dp being Robolectric's default window width — and height-only or density-only qualifiers are harmless. The title's "width **or** height" looks like it should just be "width".

**Also irrelevant:** `createComposeRule()` vs `createAndroidComposeRule<ComponentActivity>()` (identical behaviour), Material decoration (`BasicTextField` loops the same as `OutlinedTextField`), the floating label, and `AlertDialog` vs raw `Dialog`.

**Not the text input session:** `enabled = false` and `readOnly = true` both still loop. A `Modifier.focusTarget()` that isn't a text field does *not* loop, and `AlertDialog` with plain `Text` does not either.

**What avoids it**, all at `w411dp`:

```kotlin
// passes — takes the dialog window's own sizing out of it
Dialog(onDismissRequest = {}, properties = DialogProperties(usePlatformDefaultWidth = false)) {
    BasicTextField(value = "x", onValueChange = {})
}

// passes — an absolute width is independent of the incoming constraints
BasicTextField(value = "x", onValueChange = {}, modifier = Modifier.width(240.dp))

// STILL LOOPS — fillMaxWidth resolves against those constraints, which are what oscillate
BasicTextField(value = "x", onValueChange = {}, modifier = Modifier.fillMaxWidth())
```

**`@LooperMode(LooperMode.Mode.LEGACY)` did not work for me**, on either compose rule — same `AppNotIdleException`, ~658k attempts in 60s. Flagging it since it's the workaround recommended above and it cost me a while to rule out.

Worth noting for anyone landing here from a CI timeout: this fails after 60s with a clear `AppNotIdleException`, it does not hang indefinitely.
