### ISSUE TITLE
ContentProvider registered in AndroidManifest.xml is not initialized before application#onCreate

### ISSUE THREAD

**Issue by likai79511** [robolectric/robolectric#8461]
### Description
Some initial logic exist in `ContentProvider#onCreate`,  but found it was not called before `Application#onCreate`. 
If there is solution?

### Robolectric & Android Version
Robolectric: 4.10.3
Android: 33

**Comment by kfaraj** [comment]
This is really annoying because it does not respect the lifecycle of an Android app.

Consider the following example using Firebase Analytics:
```
class LauncherApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        val firebaseAnalytics = Firebase.analytics
        firebaseAnalytics.setAnalyticsCollectionEnabled(
            applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE !=
                    ApplicationInfo.FLAG_DEBUGGABLE
        )
    }
}

class LauncherActivity : FragmentActivity(R.layout.activity_launcher)

@RunWith(RobolectricTestRunner::class)
class LauncherActivityTest {
    @Test
    fun launchActivity() {
        launchActivity<LauncherActivity>()
    }
}
```

Every test will fail with the following error:
```
Default FirebaseApp is not initialized in this process null. Make sure to call FirebaseApp.initializeApp(Context) first.
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process null. Make sure to call FirebaseApp.initializeApp(Context) first.
	at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:179)
	at com.google.firebase.FirebaseKt.getApp(Firebase.kt:39)
	at com.google.firebase.analytics.AnalyticsKt.getAnalytics(com.google.android.gms:play-services-measurement-api@@21.5.0:5)
	at com.kfaraj.launcher.LauncherApplication.onCreate(LauncherApplication.kt:18)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callApplicationOnCreate(RoboMonitoringInstrumentation.java:148)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$installAndCreateApplication$2(AndroidTestEnvironment.java:381)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:379)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:250)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:247)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.robolectric.RuntimeEnvironment.lambda$getApplication$0(RuntimeEnvironment.java:80)
	at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1201)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:80)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:215)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:340)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:281)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This is because Firebase should be initialized during `FirebaseInitProvider.onCreate` which is not called since content providers are not created with `RobolectricTestRunner`.

**Comment by kfaraj** [comment]
Maybe it could be done in `AndroidTestEnvironment.installAndCreateApplication` just before the `application` is created.

https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java

**Comment by hoisie** [comment]
Yes this is a known issue. Only broadcast receivers are instantiated before tests start. Content providers have to manually registered.

**Comment by hoisie** [comment]
@kfaraj I experimented with that a bit and the problem is that some widely used libraries (e.g. AndroidX activity) contain content providers that will crash in a Robolectric environment. For various reasons. So we never got too far with that.

**Comment by kfaraj** [comment]
@hoisie thanks for the feedback, is there a way to manually create a content provider before the application is created?

With the same example, using `Before` is too late because the `application` depending on `Firebase.analytics` already tried to be created, while using `BeforeClass` is too early because of the following error:
```
Cannot invoke "org.robolectric.internal.TestEnvironment.resetState()" because the return value of "org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod.getTestEnvironment()" is null
java.lang.NullPointerException: Cannot invoke "org.robolectric.internal.TestEnvironment.resetState()" because the return value of "org.robolectric.RobolectricTestRunner$RobolectricFrameworkMethod.getTestEnvironment()" is null
	at org.robolectric.RobolectricTestRunner.lambda$finallyAfterTest$0(RobolectricTestRunner.java:370)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:86)
	at org.robolectric.RobolectricTestRunner.finallyAfterTest(RobolectricTestRunner.java:368)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:298)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by TedaLIEz** [comment]
Any update on this issue? I came across with this same error as our project heavily depends on the InitialzationProvider, (https://developer.android.com/reference/androidx/startup/InitializationProvider) which is part of the App Startup framework (https://developer.android.com/topic/libraries/app-startup), WorkManager is also depending on this for initialzation.
