### ISSUE TITLE
Crash when ripples are drawn with Robolectric Native Graphics enabled

### ISSUE THREAD

**Issue by saket** [robolectric/robolectric#8501]
### Description

When a screenshot is taken right after a button is clicked, Robolectric runs into a crash that seems to be related to how ripples are drawn. 

### Steps to Reproduce

```kotlin
composeTestRule.setContent {
  MaterialTheme {
    Icon(
      modifier = Modifier
        .testTag("icon")
        .clickable { },
      imageVector = Icons.Filled.Anchor,
      contentDescription = null,
    )
  }
}

composeTestRule.onNodeWithTag("anchor").performClick()
composeTestRule.runOnIdle {
  captureDeviceScreenshot()
}
```

### Robolectric & Android Version
Android API level: 34
Robolectric version: 4.10.3

### Link to a public git repo demonstrating the problem:

https://github.com/saket/cascade/blob/eef81d677aadff4d1b5338468ce782fb67db1bad/cascade-compose/src/test/java/me/saket/cascade/RobolectricCompatibilityTest.kt#L73-L113

This crash can be worked around by removing ripples from buttons ([example](https://github.com/saket/cascade/commit/eef81d677aadff4d1b5338468ce782fb67db1bad)).

### Stacktrace

```
java.lang.IllegalArgumentException: error: 20: floating-point value is too large: 5.3987
1 error

	at org.robolectric.nativeruntime.RuntimeShaderNatives.nativeCreateBuilder(Native Method)
	at org.robolectric.shadows.ShadowNativeRuntimeShader.nativeCreateBuilder(ShadowNativeRuntimeShader.java:155)
	at android.graphics.RuntimeShader.nativeCreateBuilder(RuntimeShader.java)
	at android.graphics.RuntimeShader.__constructor__(RuntimeShader.java:270)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:297)
	at org.robolectric.internal.bytecode.ShadowImpl.invokeConstructor(ShadowImpl.java:73)
	at org.robolectric.shadow.api.Shadow.invokeConstructor(Shadow.java:75)
	at org.robolectric.shadows.ShadowNativeRuntimeShader.__constructor__(ShadowNativeRuntimeShader.java:143)
	at android.graphics.RuntimeShader.<init>(RuntimeShader.java)
	at android.graphics.drawable.RippleShader.<init>(RippleShader.java)
	at android.graphics.drawable.RippleDrawable.createAnimationProperties(RippleDrawable.java:974)
	at android.graphics.drawable.RippleDrawable.drawPatterned(RippleDrawable.java:900)
	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:804)
	at android.view.View.drawBackground(View.java:23426)
	at android.view.View.draw(View.java:23187)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowView$_View_$$Reflector21.draw(Unknown Source)
	at org.robolectric.shadows.ShadowView.draw(ShadowView.java:254)
	at android.view.View.draw(View.java)
	at androidx.compose.material.ripple.AndroidRippleIndicationInstance.drawIndication(Ripple.android.kt:204)
	at androidx.compose.foundation.IndicationModifier.draw(Indication.kt:183)
	at androidx.compose.ui.node.BackwardsCompatNode.draw(BackwardsCompatNode.kt:349)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:365)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawContent(LayoutNodeDrawScope.kt:66)
	at androidx.compose.foundation.BackgroundNode.draw(Background.kt:155)
	at androidx.compose.ui.node.LayoutNodeDrawScope.drawDirect-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:105)
	at androidx.compose.ui.node.LayoutNodeDrawScope.draw-x_KDEd0$ui_release(LayoutNodeDrawScope.kt:86)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:365)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.performDraw(LayoutModifierNodeCoordinator.kt:182)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
	at androidx.compose.ui.node.NodeCoordinator.access$drawContainedDrawModifiers(NodeCoordinator.kt:54)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:384)
	at androidx.compose.ui.node.NodeCoordinator$invoke$1.invoke(NodeCoordinator.kt:383)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2299)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:467)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:383)
	at androidx.compose.ui.node.NodeCoordinator.invoke(NodeCoordinator.kt:54)
	at androidx.compose.ui.platform.RenderNodeLayer.drawLayer(RenderNodeLayer.android.kt:280)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:349)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
	at androidx.compose.ui.node.InnerNodeCoordinator.performDraw(InnerNodeCoordinator.kt:174)
	at androidx.compose.ui.node.NodeCoordinator.drawContainedDrawModifiers(NodeCoordinator.kt:362)
	at androidx.compose.ui.node.NodeCoordinator.draw(NodeCoordinator.kt:354)
	at androidx.compose.ui.node.LayoutNode.draw$ui_release(LayoutNode.kt:922)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1133)
	at android.view.View.draw(View.java:23198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowView$_View_$$Reflector21.draw(Unknown Source)
	at org.robolectric.shadows.ShadowView.draw(ShadowView.java:254)
	at android.view.View.draw(View.java)
	at android.view.View.draw(View.java:23068)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23066)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23198)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowView$_View_$$Reflector21.draw(Unknown Source)
	at org.robolectric.shadows.ShadowView.draw(ShadowView.java:254)
	at android.view.View.draw(View.java)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at org.robolectric.shadows.ShadowUiAutomation.takeScreenshot(ShadowUiAutomation.java:132)
	at android.app.UiAutomation.takeScreenshot(UiAutomation.java)
```

**Comment by hoisie** [comment]
Thanks for reporting this issue, RNG should never crash in native code.

**Comment by ralf-at-android** [comment]
I've been trying to repro this to debug the issue, and I can't make it crash. I've created an Android Studio gradle compose skeleton project, and added this test:

```
package com.example.composetest4

import android.graphics.Bitmap
import androidx.activity.ComponentActivity
import androidx.compose.foundation.clickable
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountBox
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import org.junit.Rule
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import org.robolectric.annotation.GraphicsMode
import androidx.compose.ui.test.junit4.createAndroidComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import androidx.test.platform.app.InstrumentationRegistry
import org.junit.Assert
import org.junit.Test

object RobolectricDeviceQualifiers {
  const val Pixel7 = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"
}

@RunWith(RobolectricTestRunner::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(
  qualifiers = RobolectricDeviceQualifiers.Pixel7,
  manifest = Config.NONE,
  sdk = [33]
)
class RobolectricIssues8501Test {
  @get:Rule val rule = createAndroidComposeRule<ComponentActivity>()

  /// Repro issue https://github.com/robolectric/robolectric/issues/8501
  @Test
  fun testNativeRuntimeShader_doesNotThrow() {
    rule.setContent {
      MaterialTheme {
        Icon(
          modifier = Modifier.testTag("icon").clickable {},
          imageVector = Icons.Filled.AccountBox,
          contentDescription = null,
        )
      }
    }

    rule.onNodeWithTag("icon").performClick()
    rule.runOnIdle {
      captureDeviceScreenshot()
    }

    Assert.fail("expected to crash before this")
  }

  private fun captureDeviceScreenshot(): Bitmap {
    return InstrumentationRegistry.getInstrumentation().uiAutomation.takeScreenshot()
  }
}
```

Here's the `build.grade.kts`:
```
plugins {
  id("com.android.application")
  id("org.jetbrains.kotlin.android")
}

android {
  namespace = "com.example.composetest4"
  compileSdk = 34

  defaultConfig {
    applicationId = "com.example.composetest4"
    minSdk = 31
    targetSdk = 34
    versionCode = 1
    versionName = "1.0"

    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    vectorDrawables { useSupportLibrary = true }
  }

  buildTypes {
    release {
      isMinifyEnabled = false
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
    }
  }
  compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
  }
  kotlinOptions { jvmTarget = "1.8" }
  buildFeatures { compose = true }
  composeOptions { kotlinCompilerExtensionVersion = "1.4.3" }
  packaging { resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" } }
  testOptions {
    animationsDisabled = true
    unitTests {
      isIncludeAndroidResources = true // Required by Robolectric.
    }
  }
}

dependencies {
  implementation("androidx.core:core-ktx:1.12.0")
  implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.6.2")
  implementation("androidx.activity:activity-compose:1.8.1")
  implementation(platform("androidx.compose:compose-bom:2023.03.00"))
  implementation("androidx.compose.ui:ui")
  implementation("androidx.compose.ui:ui-graphics")
  implementation("androidx.compose.ui:ui-tooling-preview")
  implementation("androidx.compose.material3:material3")

  testImplementation("junit:junit:4.13.2")
  testImplementation("org.robolectric:robolectric:4.10.3")
  testImplementation("androidx.compose.ui:ui-test-junit4")

  androidTestImplementation("androidx.test.ext:junit:1.1.5")
  androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
  androidTestImplementation(platform("androidx.compose:compose-bom:2023.03.00"))
  androidTestImplementation("androidx.compose.ui:ui-test-junit4")
  debugImplementation("androidx.compose.ui:ui-tooling")
  debugImplementation("androidx.compose.ui:ui-test-manifest")
}
```

This test passes just fine. 

I'd be interested in reproducing the original crash. What am I missing?

**Comment by saket** [comment]
Hmm it's difficult to tell what's different about your code. Are you able to reproduce the crash by running this?

https://github.com/saket/cascade/blob/eef81d677aadff4d1b5338468ce782fb67db1bad/cascade-compose/src/test/java/me/saket/cascade/RobolectricCompatibilityTest.kt#L73-L113

**Comment by ralf-at-android** [comment]
Yep, it works just fine from a straight checkout:

```
$ java --version # ==> 17
$ git clone https://github.com/saket/cascade.git 
$ cd cascade ; ./gradlew test
```

I get 22 failures in CascadeDropdownMenuTest yet all success in RobolectricCompatibilityTest.

```
Class                                               Tests   Failures    Ignored Duration    Success rate
me.saket.cascade.CascadeDropdownMenuTest            22      22          0       0.090s      0%
me.saket.cascade.RobolectricCompatibilityTest       2       0           0       9.608s      100%
me.saket.cascade.internal.ScreenRelativeOffsetTest  1       0           0       0.009s      100%
```

**Comment by saket** [comment]
Hmm considering that this was a native crash, I wonder if it was related to my JDK? Here's my java version:

```
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)
```

**Comment by ralf-at-android** [comment]
The crash from the Skia Shader Language parser. This is trying to render a shader, probably with some script from one of your libraries. My guess is that you're on a fairly newer API but the Robolectric code is based on an older version of the native code, which could explain a discrepancy in the shader language supported.

Actually in your code sample you have Icons.Filled.Anchor but I did not find any such icon in Material3. Do you know which library you're getting that icon from?

**Comment by saket** [comment]
> The crash is from the Skia Shader Language parser. This is trying to render a shader, probably with some script from one of your libraries. My guess is that you're on a fairly newer API but the Robolectric code is based on an older version of the native code, which could explain a discrepancy in the shader language supported.

If the source of the crash was local to the project then shouldn't you also be able to reproduce the crash in `cascade`?

> Actually in your code sample you have Icons.Filled.Anchor but I did not find any such icon in Material3. Do you know which library you're getting that icon from?

Material has an extended library for all of its icons:

```
androidx.compose.material:material-icons-extended
```
