### ISSUE TITLE
NoClassDefFoundError for PixelCopy$Request when using Robolectric 4.11 with SDK 30

### ISSUE THREAD

**Issue by takahirom** [robolectric/robolectric#8577]
### Description
With Robolectric 4.11 and SDK level 30, a NoClassDefFoundError is encountered when calling PixelCopy.request. This error does not occur when using SDK level 34 or when capturing screenshots via View.draw as shown in [this pull request](https://github.com/takahirom/roborazzi/pull/199/files). I would prefer to use Robolectric's native mechanisms for screenshot capture in the Roborazzi library whenever possible.

### Steps to Reproduce
1. Configure a test to use Robolectric 4.11 with SDK level 30 or lower.
2. Invoke PixelCopy.request.
3. Observe that the NoClassDefFoundError for android/view/PixelCopy$Request occurs.

Example failure:

```
android/view/PixelCopy$Request
java.lang.NoClassDefFoundError: android/view/PixelCopy$Request
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodDeclaredOnClass(ShadowWrangler.java:338)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethod(ShadowWrangler.java:307)
	at org.robolectric.internal.bytecode.ShadowWrangler.pickShadowMethod(ShadowWrangler.java:284)
	at org.robolectric.internal.bytecode.ShadowWrangler.lambda$findShadowMethodHandle$0(ShadowWrangler.java:222)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.ShadowWrangler.findShadowMethodHandle(ShadowWrangler.java:216)
	at org.robolectric.internal.bytecode.RobolectricInternals.findShadowMethodHandle(RobolectricInternals.java:36)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bindCallSite(InvokeDynamicSupport.java:161)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.lambda$bootstrapStatic$2(InvokeDynamicSupport.java:104)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.InvokeDynamicSupport.bootstrapStatic(InvokeDynamicSupport.java:98)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:109)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at android.view.PixelCopy.request(PixelCopy.java)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:201)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmapFromPixelCopy(ViewScreenshot.kt:184)
	at com.github.takahirom.roborazzi.ViewScreenshotKt.generateBitmap(ViewScreenshot.kt:122)
```

### Robolectric & Android Version

Robolectric version: 4.11
Android SDK tested: 30

### Link to a public git repo demonstrating the problem:
https://github.com/takahirom/roborazzi/actions/runs/6686917489/job/18166895974
https://github.com/takahirom/roborazzi/blob/14a62c6c069422089b71f25a0f7f01310966b6f8/include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ViewScreenshot.kt#L200-L206

**Comment by takahirom** [comment]
shadowClass
<img width="1155" alt="image" src="https://github.com/robolectric/robolectric/assets/1386930/4f476a1d-4de7-4fe1-93b4-6dffd7c735d8">
methodName
<img width="1086" alt="image" src="https://github.com/robolectric/robolectric/assets/1386930/ea710332-cde4-420c-8b52-27e67a5bd153">
paramClasses
<img width="1172" alt="image" src="https://github.com/robolectric/robolectric/assets/1386930/9868940b-05b2-4d9d-a0ec-0a16ae01b8cb">
The result of invocation of the method
<img width="1172" alt="image" src="https://github.com/robolectric/robolectric/assets/1386930/6a49372d-cd90-4db0-8d1b-3fa3567f7ee4">

**Comment by takahirom** [comment]
I'm not certain, but it may be necessary to create a separate ShadowPixelCopy for SDK 34.

**Comment by hoisie** [comment]
Thanks for the detailed report. We probably need to remove references to `PixelCopy$Request` from ShadowPixelCopy and use Object instead. Cc @JuliaSullivanGoogle

**Comment by takahirom** [comment]
Thank you for the quick response! We are deliberating whether to release the draw()-based capture on the Roborazzi side, and if the release of Robolectric's updates seems like it's going to be delayed for several weeks, we are considering releasing on the Roborazzi side. Do you have any idea how long it might take or any updates on the situation?

**Comment by takahirom** [comment]
@hoisie 
Thank you for the quick fix! 
We are deliberating whether to release the draw()-based capture on the Roborazzi side, and if the release of Robolectric's updates seems like it's going to be delayed for several weeks, we are considering releasing on the Roborazzi side. Do you have any idea how long it might take or any updates on the situation?

**Comment by hoisie** [comment]
@takahirom I am planning to get a 4.11.1 release out tomorrow with this fix and a couple of other fixes.

**Comment by hoisie** [comment]
@takahirom 4.11.1 was just released that should contain a fix for this issue

**Comment by takahirom** [comment]
I've checked it, and it works! Thank you for handling the matter.
