### ISSUE TITLE
ShadowInstrumentation provides null binder on bindService

### ISSUE THREAD

**Issue by AndreasBBS** [robolectric/robolectric#8608]
### Description

When I try to test the `onServiceConnection` call through `bindService` on an Activity I get an error like `java.lang.NullPointerException: Cannot invoke "com.demo.app.ForegroundService$LocalBinder.log()" because "binder" is null`

The stack trace looks like:
```
java.lang.NullPointerException: Cannot invoke "com.demo.app.ForegroundService$LocalBinder.log()" because "binder" is null
	at com.demo.app.Main$1.onServiceConnected(Main.java:21)
	at org.robolectric.shadows.ShadowInstrumentation.lambda$bindService$0(ShadowInstrumentation.java:738)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at org.robolectric.shadows.ShadowPausedLooper$IdlingRunnable.run(ShadowPausedLooper.java:368)
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:402)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:93)
	at com.demo.app..MainOnStartTests.startsAndBindsToService(MainOnStartTests.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:580)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:287)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce
TestActivity:
```java
public class Main extends AppCompatActivity {
    protected ServiceConnection connection = new ServiceConnection() {
        @Override
        public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
            ForegroundService.LocalBinder binder = (ForegroundService.LocalBinder) iBinder;
            binder.log()
        }

        @Override
        public void onServiceDisconnected(ComponentName componentName) {}
    };

    @Override
    protected void onStart() {
        super.onStart();

        Intent intent = new Intent(this, ForegroundService.class);
        bindService(intent, connection, Context.BIND_AUTO_CREATE);
    }
}
```

TestService:
```java
public class ForegroundService extends Service {
    public class LocalBinder extends Binder {
        void log() {
            Log.d("ForegroundService.LocalBinder", "log: Log function successfully called");
        }
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return new LocalBinder();
    }
}
```

Test:
```java
@RunWith(RobolectricTestRunner.class)
public class MainOnStartTests {

    Application context;
    private ActivityController<Main> controller;
    private ShadowContextWrapper shadowContextWrapper;

    @Before
    public void setUp() {
        context = ApplicationProvider.getApplicationContext();
        controller = Robolectric.buildActivity(Main.class);
        shadowContextWrapper = Shadow.extract(context);
    }

    @Test
    public void startsAndBindsToService() {
        assertEquals(0, shadowContextWrapper.getAllStartedServices().size());
        controller.create().start();
        assertEquals(1, shadowContextWrapper.getAllStartedServices().size());
        shadowMainLooper().idle();
    }
}
```

### Robolectric & Android Version
Robolectric: `org.robolectric:robolectric:4.10.3`
Android: `compileSdk 33`

**Comment by hoisie** [comment]
Hi @AndreasBBS you may need to do something like call [ShadowInstrumentation.setComponentNameAndServiceForBindService](https://github.com/robolectric/robolectric/blob/master/shadows/framework/src/main/java/org/robolectric/shadows/ShadowInstrumentation.java#L687)

You can see some examples of this in [ShadowApplicationTest](https://github.com/robolectric/robolectric/blob/master/robolectric/src/test/java/org/robolectric/shadows/ShadowApplicationTest.java#L201)
