### ISSUE TITLE
org.robolectric.res.android.LoadedArsc$TypeSpec.GetFlagsForEntryIndex - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by eugene-krivobokov** [robolectric/robolectric#8659]
### Description

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(application = android.app.Application::class, sdk = [28])
class Test { }
```

- `isIncludeAndroidResources = true`
- No dynamic features in the app

```

android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /Users/.../app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
java.lang.RuntimeException: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /Users/.../app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:68)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage_measured(AndroidTestEnvironment.java:410)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$loadAppPackage$3(AndroidTestEnvironment.java:382)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.loadAppPackage(AndroidTestEnvironment.java:382)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:279)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:251)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:248)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:79)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:216)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:340)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:281)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to read manifest from /Users/.../app/build/intermediates/apk_for_local_test/debugUnitTest/apk-for-local-test.ap_
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1243)
	at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1189)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1093)
	at android.content.pm.PackageParser.parsePackage(PackageParser.java:1102)
	at org.robolectric.shadows.ShadowPackageParser.callParsePackage(ShadowPackageParser.java:47)
	... 18 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -32690 out of bounds for length 41991
	at org.robolectric.res.android.LoadedArsc$TypeSpec.GetFlagsForEntryIndex(LoadedArsc.java:115)
	at org.robolectric.res.android.CppAssetManager2.FindEntry(CppAssetManager2.java:693)
	at org.robolectric.res.android.CppAssetManager2.GetResource(CppAssetManager2.java:860)
	at org.robolectric.res.android.CppAssetManager2.ResolveReference(CppAssetManager2.java:918)
	at org.robolectric.res.android.AttributeResolution10.RetrieveAttributes(AttributeResolution10.java:493)
	at org.robolectric.shadows.ShadowArscAssetManager10.nativeRetrieveAttributes(ShadowArscAssetManager10.java:1592)
	at android.content.res.AssetManager.nativeRetrieveAttributes(AssetManager.java)
	at android.content.res.AssetManager.retrieveAttributes(AssetManager.java:1188)
	at android.content.res.Resources.obtainAttributes(Resources.java:2120)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowResources$ResourcesReflector$$Reflector7.obtainAttributes(Unknown Source)
	at org.robolectric.shadows.ShadowResources.obtainAttributes(ShadowResources.java:98)
	at android.content.res.Resources.obtainAttributes(Resources.java)
	at android.content.pm.PackageParser.parseActivity(PackageParser.java:4288)
	at android.content.pm.PackageParser.parseBaseApplication(PackageParser.java:3776)
	at android.content.pm.PackageParser.parseBaseApkCommon(PackageParser.java:2021)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1912)
	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:1227)
	... 22 more
```

### Robolectric & Android Version

Robolectric versions: 4.10.3, 4.11.1

Config.sdk = 24: works correctly
Config.sdk = 28, 33: fails

### Link to a public git repo demonstrating the problem:

Can't reproduce in a public repo.

**Comment by MGaetan89** [comment]
Hey @eugene-krivobokov,

I've tried you can snippet with the latest Robolectric version, and the test seems to pass.
Can you check if Robolectric 4.14.1 works for you too?

**Comment by eugene-krivobokov** [comment]
Hey @MGaetan89 ,

Thanks for checking it. I don't have an ability to check it again.
I'll reopen if it reproduces on the latest version.
