### ISSUE TITLE
SOCK5 support (compatible with Gradle itself)

### ISSUE THREAD

**Issue by tprochazka** [robolectric/robolectric#8750]
Gradle itself has SOCK5 support simply by adding this to gradle.properties

```
systemProp.socksProxyHost=#.#.#.#
systemProp.socksProxyPort=1080
org.gradle.jvmargs=-DsocksProxyHost=#.#.#.# -DsocksProxyPort=1080
```

But Robolectric failing with
`Failed to fetch maven artifact org.robolectric:android-all-instrumented:4.4_r1-robolectric-r2-i4`

Why is it simply not using the existing dependency fetching mechanism directly from Gradle which will automatically work in this situation?

**Comment by hoisie** [comment]
@tprochazka I am not aware of any standard `socksProxy{Host,Port}` system property. Looks like Robolectric supports `robolectric.dependency.proxy.host` and `robolectric.dependency.proxy.port` (https://github.com/robolectric/robolectric/blob/master/plugins/maven-dependency-resolver/src/main/java/org/robolectric/MavenRoboSettings.java#L25-L30).

If there is an improvement/enhancement related to Maven/Gradle we always welcome to PRs. A lot of teams have custom maven environments that involve caching and have sent us PR to improve support.

FWIW, fetching android-all jars happens lazily because they tend to be quite large (e.g. ~150MiB for Android U). If we were to fetch them all upfront it would be many gigabytes and  it's possible many of them would be unused. As a general rule, it is very difficult to know upfront which SDKs are required for a test suite, as there are five or six ways to configure the SDK level last time I checked.

**Comment by tprochazka** [comment]
I'm using this setup
``` 
systemProp.socksProxyHost=10.253.0.2
systemProp.socksProxyPort=1080

org.gradle.jvmargs=-Xmx21g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:+UseCompressedOops -Dfile.encoding=UTF-8 -DsocksProxyHost=10.253.0.2 -DsocksProxyPort=1080
kotlin.daemon.jvmargs=-Xmx21g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:+UseCompressedOops -Dfile.encoding=UTF-8
```
Everything works great, except Robolectric tests, it failing on


```
 ERROR: Failed to fetch maven artifact org.robolectric:android-all-instrumented:9-robolectric-4913185-2-i6
    java.util.concurrent.ExecutionException: java.net.ConnectException: Connection timed out: connect
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:594)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:573)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:110)
        at org.robolectric.internal.dependency.MavenArtifactFetcher.fetchArtifact(MavenArtifactFetcher.java:121)
        at org.robolectric.internal.dependency.MavenDependencyResolver.lambda$getLocalArtifactUrls$0(MavenDependencyResolver.java:93)
        at org.robolectric.internal.dependency.MavenDependencyResolver.whileLocked(MavenDependencyResolver.java:113)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:88)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrls(MavenDependencyResolver.java:78)
        at org.robolectric.internal.dependency.MavenDependencyResolver.getLocalArtifactUrl(MavenDependencyResolver.java:129)
        at org.robolectric.plugins.LegacyDependencyResolver.getLocalArtifactUrl(LegacyDependencyResolver.java:95)
        at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.getJarPath(DefaultSdkProvider.java:143)
        at org.robolectric.internal.AndroidSandbox$SdkSandboxClassLoader.<init>(AndroidSandbox.java:128)
        at jdk.internal.reflect.GeneratedConstructorAccessor9.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
```
I'm using this 
```
            testOptions {
                unitTests.all {
                    it.systemProperty("robolectric.dependency.repo.url", repoUrl)
                }
            }
```

to set our company mirror of the maven central.
Which needs socks5 proxy to access it.

Normal maven dependencies are downloaded, but Robolectic not.

**Comment by tprochazka** [comment]
@hoisie 

> Looks like Robolectric supports robolectric.dependency.proxy.host and robolectric.dependency.proxy.port

This is for normal HTTP proxy, not for SOCK5 support, it is because I'm creating this issue. 

The best would be to reuse `systemProp.socksProxyHost` and `systemProp.socksProxyPort` to be compatible with Gradle.
