### ISSUE TITLE
Resources, NotFoundException when inflating menu with ActionBarSherlock.

### ISSUE THREAD

**Issue by arichiardi** [robolectric/robolectric#898]
Hello, it seems there is no issue open on this. However, lurking returns some problem related to ActionBarSherlock.

When I inflate my menu like the following:
```
@Override public boolean onCreateOptionsMenu(com.actionbarsherlock.view.Menu menu) {
        getSupportMenuInflater().inflate(R.menu.main_menu, menu);
        return true;
    }
```
And call Activity.create.start.
```
mActivity = Robolectric.buildActivity(GLarmMain.class)
                .create()
                .start()
                .resume()
                .visible()
                .get();
```
I get:

---
android.content.res.Resources$NotFoundException: Resource ID #0x7f100001
	at android.content.res.Resources.getValue(Resources.java:1013)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2098)
	at android.content.res.Resources.getLayout(Resources.java:852)
	at com.actionbarsherlock.view.MenuInflater.inflate(MenuInflater.java:109)
	at ar.android.app.glarm.ui.GLarmMain.onCreateOptionsMenu(GLarmMain.java:147)
	at android.support.v4.app.Watson.onCreatePanelMenu(Watson.java:44)
	at com.actionbarsherlock.ActionBarSherlock.callbackCreateOptionsMenu(ActionBarSherlock.java:560)
	at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchCreateOptionsMenu(ActionBarSherlockNative.java:64)
	at com.actionbarsherlock.app.SherlockFragmentActivity.onCreatePanelMenu(SherlockFragmentActivity.java:164)
	at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:393)
	at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:747)
	at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:2913)
	at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:162)
	at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:107)
	at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:92)
	at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:68)
	at org.robolectric.util.Scheduler.unPause(Scheduler.java:25)
	at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:219)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:258)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at ar.android.app.glarm.test.GLarmMainTests.setUp(GLarmMainTests.java:29)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by jaredsburrows** [comment]
So based on @sneuberger-amazon suggestion:

### Add Class to Package:

    package org.robolectric.shadows;

    import org.robolectric.annotation.Implementation;
    import org.robolectric.annotation.Implements;

    import android.support.v7.internal.view.SupportMenuInflater;
    import android.view.Menu;

    @Implements(SupportMenuInflater.class)
    public class ShadowSupportMenuInflater extends ShadowMenuInflater {
        @Implementation
        public void inflate(int menuRes, Menu menu) {
            super.inflate(menuRes, menu);
        }
    }

Under `androidTest/java/org/robolectric/shadows/`

Eg. `androidTest/java/org/robolectric/shadows/ShadowSupportMenuInflater.java`

### Run my Test:

In my `androidTest/java/<test package>`:

    @RunWith(RobolectricTestRunner.class)
    @Config(emulateSdk = 18, reportSdk = 18)
    public class ExampleActivityTest {
     
    }

**Comment by erd** [comment]
> Will this be added on Robolectric 3.0?

This doesn't require a shadow for `SupportMenuInflater.java` - Look at https://github.com/robolectric/robolectric-samples/tree/master/android-appcompat-v7 for a working example. I can't speak to ActionBarSherlock (since that is what this issue was initially concerned with), but AppCompat works fine.

**Comment by jaredsburrows** [comment]
I have seen the App Compat example but here is the error I get which is similar to this issue:

    android.content.res.Resources$NotFoundException: Resource ID #0x7f0d0002
        at android.content.res.Resources.getValue(Resources.java:1118)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2304)
        at android.content.res.Resources.getLayout(Resources.java:934)
        at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:115)
        at <package>.MainActivity.onCreateOptionsMenu(MainActivity.java:441)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2504)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
        at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
        at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
        at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
        at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
        at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
        at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
        at org.robolectric.util.ActivityController.visible(ActivityController.java:166)
        at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:1388)
        at org.robolectric.util.FragmentTestUtil.buildSupportFragmentManager(FragmentTestUtil.java:64)
        at org.robolectric.util.FragmentTestUtil.startFragment(FragmentTestUtil.java:31)
        at <package>.FragmentTest.testFragmentStart(FragmentTest.java:35)

ActivityExampleTest(runs fine separately):

    @RunWith(RobolectricTestRunner.class)
    @Config(emulateSdk = 18, reportSdk = 18)
    public class MainActivityTest {

        private MainActivity mainActivity;

        @Before
        public void setUp() {
            this.mainActivity = buildActivity(MainActivity.class).create().get();
        }

        @Test
        public void testNull() {
            assertThat(this.mainActivity, not(nullValue()));
        }
    }

FragmentExampleTest(runs fine separately):

    @RunWith(RobolectricTestRunner.class)
    @Config(emulateSdk = 18, reportSdk = 18)
    public class FragmentTest {

        @Test
        public void testFragmentStart() {
            final TestFragment testFragment = new TestFragment();

            startFragment(testFragment, FragmentActivity.class);

            assertThat(testFragment, not(nullValue()));
        }
    }

When I ignore the `ActivityExampleTest` test, the `FragmentExampleTest` runs fine. When both are ran via `gradlew clean testDebug`, one of them always fails. Why am I seeing this behavior?

**Comment by jongerrish** [comment]
Are you using 3.0 snapshot?

What gradle plugin?

**Comment by jaredsburrows** [comment]
Currently I am using Robolectric 2.4. I'll switch to Robolectric 3.0 when it is released.

**Gradle Dependency:**

`androidTestCompile 'org.robolectric:robolectric:2.4'`

**Gradle Plugin:**

`classpath 'org.robolectric:robolectric-gradle-plugin:0.14.1'`

**Comment by jongerrish** [comment]
You'll need to add the ShadowSupportMenuInflater.class to the shadows
attribute of the @Config annotation.

**Comment by jaredsburrows** [comment]
@jongerrish  Based on @erd  previous answer, it looks like it will be supported in 3.0?

ActivityExampleTest(runs fine separately):

    @RunWith(RobolectricTestRunner.class)
    @Config(emulateSdk = 18, reportSdk = 18, shadows = {ShadowSupportMenuInflater.class})
    public class MainActivityTest {

        private MainActivity mainActivity;

        @Before
        public void setUp() {
            this.mainActivity = buildActivity(MainActivity.class).create().get();
        }

        @Test
        public void testNull() {
            assertThat(this.mainActivity, not(nullValue()));
        }
    }

FragmentExampleTest(runs fine separately):

    @RunWith(RobolectricTestRunner.class)
    @Config(emulateSdk = 18, reportSdk = 18, shadows = {ShadowSupportMenuInflater.class})
    public class FragmentTest {

        @Test
        public void testFragmentStart() {
            final TestFragment testFragment = new TestFragment();

            startFragment(testFragment, FragmentActivity.class);

            assertThat(testFragment, not(nullValue()));
        }
    }

After adding the shadows, I receive a new error. I have tried this before:

    java.lang.NullPointerException
        at <package>.MainActivity.onCreateOptionsMenu(MainActivity.java:447)
        at android.app.Activity.onCreatePanelMenu(Activity.java:2504)
        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:275)
        at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:276)
        at android.support.v7.app.ActionBarActivityDelegate$1.onCreatePanelMenu(ActionBarActivityDelegate.java:79)
        at android.support.v7.widget.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:49)
        at android.support.v7.internal.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:459)
        at android.support.v7.internal.app.ToolbarActionBar$1.run(ToolbarActionBar.java:69)
        at org.robolectric.util.Scheduler$PostedRunnable.run(Scheduler.java:182)
        at org.robolectric.util.Scheduler.runOneTask(Scheduler.java:125)
        at org.robolectric.util.Scheduler.advanceTo(Scheduler.java:110)
        at org.robolectric.util.Scheduler.advanceToLastPostedRunnable(Scheduler.java:86)
        at org.robolectric.util.Scheduler.unPause(Scheduler.java:26)
        at org.robolectric.shadows.ShadowLooper.unPause(ShadowLooper.java:231)
        at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:270)
        at org.robolectric.util.ActivityController.visible(ActivityController.java:166)
        at org.robolectric.util.ActivityController.setup(ActivityController.java:202)
        at org.robolectric.Robolectric.setupActivity(Robolectric.java:1388)
        at org.robolectric.util.FragmentTestUtil.buildSupportFragmentManager(FragmentTestUtil.java:64)
        at org.robolectric.util.FragmentTestUtil.startFragment(FragmentTestUtil.java:31)
        at <package>.FragmentTest.testFragmentStart(FragmentTest.java:36)

The line `447` in my `MainActivity` is:
   
        this.searchView.setSearchableInfo(searchManager.getSearchableInfo(this.getComponentName()));

Now it complains about inflating this view? Checking for `null` allows the test to pass but why is the view no longer being initiated properly?

**Comment by jaredsburrows** [comment]
@jongerrish and @erd I got forgot to post my temporary solution:

        /* Robolectric fails to inflate view via 2.4 ShadowSupportMenuInflator */
        if (this.searchView != null) {
            this.searchView.setSearchableInfo(searchManager.getSearchableInfo(this.getComponentName()));
            this.searchView.setQueryHint(this.getString(R.string.fragment_search));
            this.searchView.setOnQueryTextListener(this.onQueryTextListener);
        }

**Comment by abrahamks** [comment]
Hi all,
I encountered a similar problem with ABS 4.4 and Robolectrics 2.4. It seems the Robolectric has some problems with manifest / ABS?

I have an EditText which changes depend on user's location. Here is my test code 
```
package com.secqme.client.andrioid;

import android.widget.EditText;

import org.hamcrest.MatcherAssert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import static org.hamcrest.Matchers.*;

@RunWith(RobolectricTestRunner.class)
@Config(manifest = "../app/src/main/AndroidManifest.xml", emulateSdk = 18, reportSdk = 18)
public class LogInActivityTest {

    private LogInActivity logInActivity;
    @Test
    public void firstTest() throws Exception {
        logInActivity = Robolectric.setupActivity(LogInActivity.class);
        EditText countryCode = (EditText) logInActivity.findViewById(R.id.logInCountryCode);
        String testCountryCode = countryCode.getText().toString();
        MatcherAssert.assertThat(testCountryCode, equalTo("Malaysia"));
    }
}
```

After I ran the test, the error code is like this
```
WARNING: no system properties value for ro.build.date.utc
DEBUG: Loading resources for com.example.blablabla from ./../app/src/main/res...
DEBUG: Loading resources for android.support.v4 from ./../app/src/main/../../build/intermediates/exploded-aar/com.android.support/support-v4/20.0.0/res...
java.lang.NullPointerException
	at org.robolectric.AndroidManifest$MetaData.init(AndroidManifest.java:736)
	at org.robolectric.AndroidManifest.initMetaData(AndroidManifest.java:395)
	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:366)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:68)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

java.lang.RuntimeException: java.lang.NullPointerException
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:226)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.NullPointerException
	at org.robolectric.AndroidManifest$MetaData.init(AndroidManifest.java:736)
	at org.robolectric.AndroidManifest.initMetaData(AndroidManifest.java:395)
	at org.robolectric.res.builder.RobolectricPackageManager.addManifest(RobolectricPackageManager.java:366)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:68)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:440)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:222)
	... 19 more


Process finished with exit code 255

```
When I looked at AndroidManifest.java:737, the code showed this
```
 switch (typedRes.getResType()) {
                  case BOOLEAN: case COLOR: case INTEGER: case FLOAT:
                    valueMap.put(entry.getKey(),parseValue(typedRes.getData().toString()));
                    break;
                  default:
                    valueMap.put(entry.getKey(),typedRes.getData());
                }
```
Any advices how to solve this problem?

Thanks

**Comment by erd** [comment]
Cleaning up old issues.

**Comment by samygj** [comment]
I have the same issue. I've created ShadowSupportMenuInflater under org.robolectric.shadows and I've added the new class to the annotation. But it still doesn't work. Please suggest.

**Comment by jaredsburrows** [comment]
@samygj  Upgrade to Robolectric 3.0, you do not need to create a `ShadowSupportMenuInflater` anymore.
