### ISSUE TITLE
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no flutter in java.library.path: 

### ISSUE THREAD

**Issue by darshan281293** [robolectric/robolectric#8983]
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no flutter in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:360)
	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setUpFlutterEngine(FlutterActivityAndFragmentDelegate.java:323)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:188)
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:634)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:377)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:138)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:227)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:136)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:146)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:340)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:127)
	at com.appreciatewealth.android.activity.minimodule.FlutterSdkEntryMiniModuleActivityTest.setUp(FlutterSdkEntryMiniModuleActivityTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:588)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: no flutter in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:248)
	at io.flutter.embedding.engine.FlutterEngineGroup.<init>(FlutterEngineGroup.java:63)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setUpFlutterEngine(FlutterActivityAndFragmentDelegate.java:323)
	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:188)
	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:634)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Activity.$$robo$$android_app_Activity$performCreate(Activity.java:8573)
	at android.app.Activity.performCreate(Activity.java)
	at android.app.Instrumentation.$$robo$$android_app_Instrumentation$callActivityOnCreate(Instrumentation.java:1456)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:377)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:138)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:227)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:136)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:146)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:340)
	at org.robolectric.Robolectric.setupActivity(Robolectric.java:127)
	at com.appreciatewealth.android.activity.minimodule.FlutterSdkEntryMiniModuleActivityTest.setUp(FlutterSdkEntryMiniModuleActivityTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	... 13 more
Caused by: java.lang.UnsatisfiedLinkError: no flutter in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:145)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:191)
	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:184)
	... 4 more

**I'm facing this issue while initialising activity which is point to FlutterActivity. Below is my code snippet.

FlutterActivity activity = Robolectric.setupActivity(FlutterSdkEntryMiniModuleActivity.class);**

**Comment by hoisie** [comment]
Flutter is not supported on Robolectric.

**Comment by darshan281293** [comment]
We're not integrating Flutter, but the FlutterActivity(which extends Activity) is within our scope. We're working on writing test cases for it. Are you suggesting that test cases for FlutterActivity are also supported?
