### ISSUE TITLE
Improve error message for `Robolectric.buildActivity()` if provided an abstract class

### ISSUE THREAD

**Issue by david-allison** [robolectric/robolectric#8997]
**Is your feature request related to a problem? Please describe.**
A developer wanted help with their code producing the following error message

```kotlin
        val controller = Robolectric.buildActivity(AbstractClass::class.java)
```

```
java.lang.RuntimeException: error instantiating com.example.AbstractClass
	at org.robolectric.util.ReflectionHelpers.callConstructor(ReflectionHelpers.java:440)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:113)
	at org.robolectric.Robolectric.buildActivity(Robolectric.java:78)
```

**Describe the solution you'd like**
The error message should state that the provided class is abstract (and that abstract classes are not supported)

**Describe alternatives you've considered**
N/A

**Additional context**

Sample `isAbstract` checking code

```java
java.lang.reflect.Modifier.isAbstract(clazz.getModifiers())
```

https://stackoverflow.com/a/1072895

**Comment by david-allison** [comment]
seems reproducible in Java

```java
package com.ichi2.anki.dialogs.tags;

import android.app.Activity;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;

import androidx.test.ext.junit.runners.AndroidJUnit4;

@RunWith(AndroidJUnit4.class)
public class ActivityJavaTest {

    @Test
    public void robolectricTest() {
        Robolectric.buildActivity(TestActivity.class);
    }
}

abstract class TestActivity extends Activity {

}
```
