### ISSUE TITLE
Robolectric SQLiteDatabase#rawQuery does not work when the query is a JOIN

### ISSUE THREAD

**Issue by BrantApps** [robolectric/robolectric#906]
Just came across the following exception when testing a DAO with the underlying query performing a `LEFT OUTER JOIN` and can confirm that any `JOIN` query exhibits the same problem.

``` java
java.lang.RuntimeException: SQL exception in setResultSet
    at org.robolectric.shadows.ShadowSQLiteCursor.setResultSet(ShadowSQLiteCursor.java:198)
    at org.robolectric.shadows.ShadowSQLiteDatabase.rawQueryWithFactory(ShadowSQLiteDatabase.java:362)
    at org.robolectric.shadows.ShadowSQLiteDatabase.rawQuery(ShadowSQLiteDatabase.java:331)
    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java)
    at com.oceanlife.service.SupportedBuoyService.listSupported(SupportedBuoyService.java:222)
    at com.oceanlife.service.SupportedBuoyService.findNearestSupportedBuoys(SupportedBuoyService.java:515)
    at com.oceanlife.service.TestSupportedBuoyService.findNearestSupportedBuoys(TestSupportedBuoyService.java:159)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at com.oceanlife.testing.rules.StoutLoggingRule$1.evaluate(StoutLoggingRule.java:25)
    at com.oceanlife.testing.rules.InjectorRule$1.evaluate(InjectorRule.java:28)
    at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.sql.SQLException: ambiguous column: 'id'
    at org.sqlite.RS.findColumn(RS.java:117)
    at org.sqlite.RS.getObject(RS.java:387)
    at org.robolectric.shadows.ShadowSQLiteCursor.fillRowValues(ShadowSQLiteCursor.java:163)
    at org.robolectric.shadows.ShadowSQLiteCursor.fillRows(ShadowSQLiteCursor.java:176)
    at org.robolectric.shadows.ShadowSQLiteCursor.setResultSet(ShadowSQLiteCursor.java:196)
    at org.robolectric.shadows.ShadowSQLiteDatabase.rawQueryWithFactory(ShadowSQLiteDatabase.java:362)
    at org.robolectric.shadows.ShadowSQLiteDatabase.rawQuery(ShadowSQLiteDatabase.java:331)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.robolectric.bytecode.ShadowWrangler$ShadowMethodPlan.run(ShadowWrangler.java:456)
    at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java)
    at com.oceanlife.service.SupportedBuoyService.listSupported(SupportedBuoyService.java:222)
    at com.oceanlife.service.SupportedBuoyService.findNearestSupportedBuoys(SupportedBuoyService.java:515)
    at com.oceanlife.service.TestSupportedBuoyService.findNearestSupportedBuoys(TestSupportedBuoyService.java:159)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
        ... 24 more
```

**To replicate**
- Using robolectric 2.2 and an in-memory database exercise code which runs the native command `SQLiteDatabase#rawQuery` where the raw query is a join against two tables under test. 

**Expected result**
- Robolectric behaves like the real SQLite database running on a device and the query executes without a problem.

**Actual result**
- The `JOIN` statement causes the test to fail noting an "ambiguous 'id' column" (see stack trace) despite no such ambiguity in the query and the real device also not exhibiting the problem.

**Comment by jongerrish** [comment]
Closing this as it hasn't been updated in a while. If its still an issue with Robolectric 4.0 please reopen with a reproducible test case and we'll prioritize.
