### ISSUE TITLE
UnsatisfiedLinkError when try to access native library

### ISSUE THREAD

**Issue by ShaliniRamasamy** [robolectric/robolectric#9099]
Getting UnsatisfiedLinkError when try to access native library in unit test case

 compileSdkVersion = 32
 junitVersion = '4.13.1'
 robolectric_version = "4.8"
mediapipe:tasks-vision = "0.10.0"

java.lang.UnsatisfiedLinkError: no mediapipe_tasks_vision_jni in java.library.path: [/Users/shalini/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2678)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1890)
	at com.google.mediapipe.tasks.vision.core.BaseVisionTaskApi.<clinit>(BaseVisionTaskApi.java:37)
	at com.roche.coresdk.mediapipe.FaceLandmarkerHelper.setupFaceLandmarker(FaceLandmarkerHelper.kt:125)
	at com.roche.coresdk.mediapipe.FaceLandmarkerHelper.<init>(FaceLandmarkerHelper.kt:52)
	at com.roche.coresdk.mediapipe.FaceLandmarkerHelperTest.setup(FaceLandmarkerHelperTest.kt:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:580)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:287)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by MGaetan89** [comment]
Hey @ShaliniRamasamy 
Out of curiosity, have you try with Robolectric's latest version (4.12.2) to see if the problem still exists?

**Comment by ShaliniRamasamy** [comment]
Any update on this please

**Comment by hoisie** [comment]
In Robolectric, if you want to use System.loadLibrary, you need to ensure that the native library is available and the path is set using `-Djava.library.path=/path/to/directory/that/contains/mediapipe_tasks_vision_jni`.

When an app is launched in Android, the system library path is updated to include the jni files in the app, but Robolectric has no idea what jni is used by your app.

**Comment by MGaetan89** [comment]
> In Robolectric, if you want to use System.loadLibrary, you need to ensure that the native library is available and the path is set using `-Djava.library.path=/path/to/directory/that/contains/mediapipe_tasks_vision_jni`.
> 
> When an app is launched in Android, the system library path is updated to include the jni files in the app, but Robolectric has no idea what jni is used by your app.

@ShaliniRamasamy does this answer your question? Or do you need more help linking native libraries with Robolectric?

**Comment by MGaetan89** [comment]
I'm closing this, since an answer was provided by @hoisie.

@ShaliniRamasamy if you need more help regarding your question, don't hesitate to reopen this ticket with more details.
