### ISSUE TITLE
"no androidx.graphics.path in java.library.path" when using PathIterator

### ISSUE THREAD

**Issue by LouisCAD** [robolectric/robolectric#9336]
### Description

Hello,
I'd like to use `iterator()` on the `Path` type from the `androidx.compose.ui.graphics` package.

Unfortunately, it leads me to this runtime error:
```
java.lang.UnsatisfiedLinkError: no androidx.graphics.path in java.library.path: /Users/me/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.:/Users/Louis/AndroidStudioProjects/SomeProject/src/testDebug/jniLibs:/Users/Louis/AndroidStudioProjects/SomeProject/src/test/jniLibs
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2434)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
	at java.base/java.lang.System.loadLibrary(System.java:2015)
	at androidx.graphics.path.PathIteratorImpl.<clinit>(PathIteratorImpl.kt:49)
	at androidx.graphics.path.PathIterator.<init>(PathIterator.kt:42)
	at androidx.compose.ui.graphics.AndroidPathIterator.<init>(AndroidPathIterator.android.kt:36)
	at androidx.compose.ui.graphics.AndroidPathIterator_androidKt.PathIterator(AndroidPathIterator.android.kt:27)
	at androidx.compose.ui.graphics.AndroidPathIterator_androidKt.PathIterator$default(AndroidPathIterator.android.kt:23)
	at androidx.compose.ui.graphics.Path.iterator(Path.kt:346)
```

### Steps to Reproduce

Add this import:
```kotlin
import androidx.compose.ui.graphics.Path
```
Then, in some function, call `Path().iterator()`.

### Robolectric & Android Version

Version 4.13 with compileSdk 34

Could for path iteration be supported, please?
That would be nice to test stuff around with path animations, something that is not so easy to get right without tests.

Thank you and have a nice day!

Louis CAD

**Comment by yschimke** [comment]
Is the Robolectric shadow policy documented somewhere publicly?

I see https://github.com/robolectric/robolectric/pull/5458#pullrequestreview-359478111

>  It is also intentional that there hasn't been an androidx variant of that artifact created. In general, it has not been recommended to shadow non android framework classes like android.support and gmscore, as they have proven to be brittle.

**Comment by hoisie** [comment]
This issue has come up a few times in the past. The best workaround is to disable custom Compose transitions in Robolectric tests. AndroidX's [PathIteratorImpl](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:graphics/graphics-path/src/main/java/androidx/graphics/path/PathIteratorImpl.kt;l=48?q=%22androidx.graphics.path%22) is loading a custom JNI library, but they do not provide one for host platforms. We have been asked not to shadow AndroidX code. cc @nadewad.

**Comment by yschimke** [comment]
Just hit this myself, would a shadow based on android.graphics.PathIterator be possible, since it's already in robolectric?

**Comment by hoisie** [comment]
cc @alanv from AndroidX

@yschimke to be honest the situation with the `androidx.graphics.path` library and `android.graphics.PathIterator` is kind of a mess. Both of these are highly coupled to Android and cannot easily work in JVM environments (layoutlib, Robolectric).

For SDKs 33 and below, my opinion is that it's not worth trying to support AndroidX's PathIteratorImpl on the JVM. The only way to do that is to shadow AndroidX classes, but we have been asked not to do that. Maybe AndroidX's PathIteratorImpl could add add a try/catch around the System.loadLIbrary, since I am not sure how it would be possible to generate a library for host platforms.

For SDK 34 and above, Robolectric would need to support [PathIterator](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/graphics/java/android/graphics/PathIterator.java). The problem with this, however, is that it uses [VMRuntime.newNonMovableArray]((https://cs.android.com/android/platform/superproject/main/+/main:libcore/libart/src/main/java/dalvik/system/VMRuntime.java;drc=efb735f4d5a2f04550e33e8aa9485f906018fe4e;l=578), which does not exist on the JVM, since the JVM can move primitive arrays around during GC. I am not 100% sure how to support that in Robolectric. It would could involve some kind of direct ByteBuffer, but it would be nontrivial.

**Comment by yschimke** [comment]
@hoisie thanks, that great context.

How far is CachedPathIteratorFactory from the needed data?

**Comment by LouisCAD** [comment]
@hoisie isn't that already solved within the shadow implementation of `Bitmap` and other things?

From the JavaDoc of VMRuntime.newNonMovableArray that you linked just above:

> Returns an array allocated in an area of the Java heap where it will never be moved.
     * This is used to implement native allocations on the Java heap, such as DirectByteBuffers
     * and Bitmaps.

**Comment by yschimke** [comment]
The [snapshot](https://github.com/robolectric/robolectric?tab=readme-ov-file#using-snapshots) appears to work somewhat for the Platform API, but will likely require a Shadow as @hoisie mentioned to avoid the Androidx code failing loading a native library.

```
        init {
            /**
             * The native library is used mainly for pre-API34, but we also rely
             * on the conic conversion code in API34+, thus it is initialized here.
             */
            System.loadLibrary("androidx.graphics.path")
        }
```

**Comment by yschimke** [comment]
For now I'm using

```
@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")

import org.robolectric.annotation.Implements
import androidx.graphics.path.PathIteratorImpl
import org.robolectric.util.reflector.Static

@Implements(value = PathIteratorImpl::class)
class ShadowPathIteratorImpl {

    companion object {
        @JvmStatic
        @Static
        fun __staticInitializer__(): Unit {
        }
    }
}
```

**Comment by yschimke** [comment]
I also needed this to open up some JDK types.

```
tasks.withType<Test>().configureEach {
  jvmArgs(
    "--add-opens=java.base/java.util=ALL-UNNAMED",
    "--add-opens=java.base/java.nio=ALL-UNNAMED",
  )
}
```

**Comment by luizgrp** [comment]
For now, adding dependency on [androidx.graphics:graphics-path:1.1.0-alpha01](https://developer.android.com/jetpack/androidx/releases/graphics#graphics-path-1.1.0-alpha01) should fix this issue.

Once `androidx.graphics:graphics-path` releases a stable version, `androidx.compose.ui.graphics` will release a version with the fix, then the extra dependency won't be necessary.

**Comment by anthonymonori** [comment]
@luizgrp thanks for the last update!

> Once androidx.graphics:graphics-path releases a stable version, androidx.compose.ui.graphics will release a version with the fix, then the extra dependency won't be necessary.

I see now that `androidx.graphics:graphics-path` has released a stable version now. 

https://developer.android.com/jetpack/androidx/releases/graphics#1.1.0

Any chance of `androidx.compose.ui.graphics` already shipping the proposed changes? Would it reference this issue in the release notes by any chance?

**Comment by luizgrp** [comment]
@anthonymonori that 1.1.0 version is for graphics-shape. The graphics-path is still on 1.1.0-beta01. There might be an update soon, I will keep you posted. Thanks for the patience!

**Comment by MGaetan89** [comment]
FYI: the `graphics-path` version 1.1.0 was released back in May: https://developer.android.com/jetpack/androidx/releases/graphics#graphics-path-1.1.0

But the latest stable version of `androidx.compose.ui:ui-graphics-android` (1.11.4) still depends on version 1.0.1. Same for the beta version of 1.12.0.

**Comment by MGaetan89** [comment]
I've submitted https://github.com/androidx/androidx/pull/901 to update `androidx.graphics:graphics-path` in `androidx.compose.ui:ui-graphics-android`.
The PR was merged, and will hopefully be included in the next 1.13.0 alpha release.

**Comment by MGaetan89** [comment]
> I've submitted [androidx/androidx#901](https://github.com/androidx/androidx/pull/901) to update `androidx.graphics:graphics-path` in `androidx.compose.ui:ui-graphics-android`. The PR was merged, and will hopefully be included in the next 1.13.0 alpha release.

The dependency update is part of `androidx.compose.ui:ui-graphics-android:1.13.0-alpha02`.
