### ISSUE TITLE
Injection fails due to missing @Inject annotation: multiple public constructors

### ISSUE THREAD

**Issue by sebastianharder** [robolectric/robolectric#9405]
### Description
I try to migrate from Robolectric 4.1 to 4.13. The problem appears since 4.2-alpha-2 however ([changes since 4.2-alpha-1](https://github.com/robolectric/robolectric/compare/robolectric-4.2-alpha-1...robolectric-4.2-alpha-2)).

All tests fail with:
```
org.robolectric.internal.AndroidSandbox$TestEnvironmentSpec: multiple public constructors
org.robolectric.util.inject.InjectionException: org.robolectric.internal.AndroidSandbox$TestEnvironmentSpec: multiple public constructors
	at app//org.robolectric.util.inject.Injector.findConstructor(Injector.java:284)
	at app//org.robolectric.util.inject.Injector.inject(Injector.java:252)
	at app//org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:239)
	at app//org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:506)
	at app//org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:230)
	at app//org.robolectric.util.inject.Injector.resolveDependencies(Injector.java:305)
	at app//org.robolectric.util.inject.Injector.inject(Injector.java:257)
	at app//org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:239)
	at app//org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:506)
	at app//org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:230)
	at app//org.robolectric.util.inject.Injector.getInstance(Injector.java:214)
	at app//org.robolectric.util.inject.Injector.access$700(Injector.java:96)
	at app//org.robolectric.util.inject.Injector$ScopeBuilderProvider.create(Injector.java:575)
	at app//org.robolectric.util.inject.Injector$ScopeBuilderProvider.lambda$get$0(Injector.java:558)
	at app/jdk.proxy3/jdk.proxy3.$Proxy20.build(Unknown Source)
	at app//org.robolectric.internal.SandboxManager.getAndroidSandbox(SandboxManager.java:67)
	at app//org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:248)
	at app//org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:61)
	at app//org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:246)
	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at app//org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:103)
	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
```

I debugged the `Injector` class and it never finds any constructor with an `@Inject` annotation for any class. The annotation seems to be simply ignored or missing.

Since I cannot find a single result via internet search, I hope someone here has an idea what's going on.

### Steps to Reproduce
n/a

### Robolectric & Android Version
Robolectric: 4.2-alpha-2 .. 4.13
AGP: 7.4 .. 8.5.1
compileSdk: 34

**Comment by hoisie** [comment]
TestEnvironmentSpec has a single `@Inject` constructor, so I am confused about which one it is finding: 
https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/AndroidSandbox.java#L109-L112

What JVM are you using, and what OS?

**Comment by hoisie** [comment]
@sebastianharder do you perform any bytecode operations as part of your build, e.g. appreduce or something to optimize things?

**Comment by sebastianharder** [comment]
>  TestEnvironmentSpec has a single `@Inject` constructor, so I am confused about which one it is finding: 
> https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/internal/AndroidSandbox.java#L109-L112
> 
> What JVM are you using, and what OS?

It finds both constructors, but none of them has an @Inject annotation according to reflection, this throwing the exception.

I was trying 
- JDK 11 with AGP 7.4 and Robo 4.2.*
- JDK 17 with AGP 8.5.1 and Robo 4.13.

OS is latest macOS.

I am not doing any special bytecode manipulation that I am aware of. The project is pretty huge though.

**Comment by sebastianharder** [comment]
Found the root cause: using the very old Toothpick 2.x dependency injection framework which [replaces the "javax.inject" annotations with its own](https://github.com/stephanenicolas/toothpick/wiki/Toothpick-javax-Annotations), that do not have runtime retention.
