### ISSUE TITLE
Robolectric fails when using HarmonizedColors

### ISSUE THREAD

**Issue by mtotschnig** [robolectric/robolectric#9552]
### Description

Testing a project configured for dynamic and harmonized colors as explained in: https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md fails.

### Steps to Reproduce

Basically, in your activity's onCreate

        DynamicColors.applyToActivityIfAvailable(
            this,
            DynamicColorsOptions.Builder().apply {
                setContentBasedSource(Color.GREEN)
            }
                .setOnAppliedCallback {
                    HarmonizedColors.applyToContextIfAvailable(
                        this,
                        HarmonizedColorsOptions.Builder()
                            .setColorResourceIds(
                                intArrayOf(
                                    R.color.black,
                                    R.color.white
                                )
                            )
                            .build()
                    )
                }
                .build()
        )

Then any test instantiating that activity, for example with

    @Test
    fun runAppWithDynamicColors() {
        Robolectric.buildActivity(MainActivity::class.java).use { controller ->
            controller.setup() // Moves the Activity to the RESUMED state

            controller.get()
        }
    }

will fail with

```
java.lang.AssertionError
	at org.robolectric.res.android.Util.CHECK(Util.java:96)
	at org.robolectric.shadows.ShadowArscAssetManager10.nativeThemeApplyStyle(ShadowArscAssetManager10.java:1605)
	at android.content.res.AssetManager.nativeThemeApplyStyle(AssetManager.java)
	at android.content.res.AssetManager.applyStyleToTheme(AssetManager.java:1218)
	at android.content.res.ResourcesImpl$ThemeImpl.applyStyle(ResourcesImpl.java:1368)
	at android.content.res.Resources$Theme.applyStyle(Resources.java:1560)
	at com.google.android.material.color.ThemeUtils.applyThemeOverlay(ThemeUtils.java:45)
	at com.google.android.material.color.ResourcesLoaderColorResourcesOverride.applyIfPossible(ResourcesLoaderColorResourcesOverride.java:50)
	at com.google.android.material.color.DynamicColors.applyToActivityIfAvailable(DynamicColors.java:310)
	at com.example.robolectricwithdynamiccolors.MainActivity.onCreate(MainActivity.kt:32)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.callActivityOnCreate(RoboMonitoringInstrumentation.java:382)
	at org.robolectric.android.controller.ActivityController.lambda$create$0(ActivityController.java:138)
	at org.robolectric.shadows.ShadowPausedLooper.runPaused(ShadowPausedLooper.java:243)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:136)
	at org.robolectric.android.controller.ActivityController.create(ActivityController.java:146)
	at org.robolectric.android.controller.ActivityController.setup(ActivityController.java:341)
	at com.example.robolectricwithdynamiccolors.ExampleUnitTest.runAppWithDynamicColors(ExampleUnitTest.kt:15)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:291)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	Suppressed: org.robolectric.android.internal.AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.

```

### Robolectric & Android Version

Robolectric 4.13
sdk >= 31

### Link to a public git repo demonstrating the problem:

Can push by experiment to a public repo, if above information is not sufficient.

**Comment by MGaetan89** [comment]
Did you try to apply what the exception suggests?
```
AndroidTestEnvironment$UnExecutedRunnablesException: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(Looper.getMainLooper()).idle() call.
```

**Comment by mtotschnig** [comment]
Tried to add this in the two positions indicated below. Did not make a difference.

    fun runAppWithDynamicColors() {
        //shadowOf(Looper.getMainLooper()).idle()
        Robolectric.buildActivity(MainActivity::class.java).use { controller ->
            //shadowOf(Looper.getMainLooper()).idle()
            controller.setup() // Moves the Activity to the RESUMED state

            controller.get()
        }
    }
