### ISSUE TITLE
WakeLock.toString() throws an error

### ISSUE THREAD

**Issue by ydanneg** [robolectric/robolectric#9566]
### Description
 `PowerManager.WakeLock.toString()` throws `NullPointerException`
```
Cannot enter synchronized block because "this.mToken" is null
java.lang.NullPointerException: Cannot enter synchronized block because "this.mToken" is null
	at android.os.PowerManager$WakeLock.toString(PowerManager.java:3884)
	at org.robolectric.shadows.ShadowPowerManagerTest.toString_shouldWork(ShadowPowerManagerTest.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:502)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
### Steps to Reproduce
```
Index: robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java b/robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java
--- a/robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java	(revision 967ba2a0b57e36ddcb1545890d6e7b54d3cfc5aa)
+++ b/robolectric/src/test/java/org/robolectric/shadows/ShadowPowerManagerTest.java	(date 1726059038354)
@@ -53,6 +53,12 @@
     powerManager = (PowerManager) context.getSystemService(Context.POWER_SERVICE);
   }
 
+  @Test
+  public void toString_shouldWork() {
+    PowerManager.WakeLock lock = powerManager.newWakeLock(0, "TAG");
+    assertThat(lock.toString()).isNotEmpty();
+  }
+
   @Test
   public void acquire_shouldAcquireAndReleaseReferenceCountedLock() {
     PowerManager.WakeLock lock = powerManager.newWakeLock(0, "TAG");
```

### Robolectric & Android Version
Robolectric: 4.13
JDK17

**Comment by samr874** [comment]
@ydanneg  what is the status of this issues is it assigned to someone ?? are the contributions still active

**Comment by ydanneg** [comment]
> @ydanneg  what is the status of this issues is it assigned to someone ?? are the contributions still active

waiting for the second approval from @hoisie

**Comment by MGaetan89** [comment]
My understanding was more that the current approach is not the right way to fix this, and that some fields need to be initialized instead: https://github.com/robolectric/robolectric/pull/9573#discussion_r1758195554

**Comment by samr874** [comment]
Are the contributions still active? @MGaetan89 could you please tell me??

**Comment by MGaetan89** [comment]
> Are the contributions still active? @MGaetan89 could you please tell me??

@ydanneg submitted https://github.com/robolectric/robolectric/pull/9573, which is in review

**Comment by hoisie** [comment]
@utzcoz sure I'd be happy to do another point release that includes this and some other commits.
