### ISSUE TITLE
Run a robolectric unit test from the Java command line?

### ISSUE THREAD

**Issue by artsmvch** [robolectric/robolectric#9572]
**Is your feature request related to a problem? Please describe.**
I am trying to run a robolectric unit using Junit from the Java command line (as described [here](https://github.com/junit-team/junit4/wiki/Getting-started#run-the-test)).
Here is the test code:
```
package com.sample.robolectric

import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [29])
class RobolectricSimpleTest {
    @Test
    fun test() {
        println("Hello world!")
    }
}
```

I am using the following dependencies for `classpath` when running `java`:
* `junit` and `hamcrest` jars;
* `robolectric` jar: https://repo1.maven.org/maven2/org/robolectric/robolectric/4.8.2/
* `android-all`: https://repo1.maven.org/maven2/org/robolectric/android-all/10-robolectric-5803371/android-all-10-robolectric-5803371.jar
* The compiled test itself.

But I am getting `initializationError`:
```
There was 1 failure:
1) initializationError(com.sample.robolectric.RobolectricSimpleTest)
org.robolectric.util.inject.InjectionException: Key<class org.robolectric.internal.SandboxManager>: Failed to resolve dependency: SandboxManager/SdkCollection/SdkProvider
        at org.robolectric.util.inject.Injector$UnsatisfiedDependencyException.asInjectionException(Injector.java:589)
        at org.robolectric.util.inject.Injector.getInstance(Injector.java:210)
        at org.robolectric.util.inject.Injector.getInstance(Injector.java:202)
        at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:115)
        at org.robolectric.RobolectricTestRunner.<init>(RobolectricTestRunner.java:104)
        ... 20 trimmed
Caused by: org.robolectric.util.inject.Injector$UnsatisfiedDependencyException: Key<class org.robolectric.internal.SandboxManager>
        at org.robolectric.util.inject.Injector.resolveDependencies(Injector.java:298)
        at org.robolectric.util.inject.Injector.inject(Injector.java:248)
        at org.robolectric.util.inject.Injector.lambda$memoized$1(Injector.java:232)
        at org.robolectric.util.inject.Injector$MemoizingProvider.get(Injector.java:498)
        at org.robolectric.util.inject.Injector.getInstanceInternal(Injector.java:224)
        at org.robolectric.util.inject.Injector.getInstance(Injector.java:208)
        ... 24 more
```

**Describe the solution you'd like**
I'd like to be able to run a robolectric unit test from the Java command line. I don't wanna use Gradle or any other build systems.
If it's possible, please provide a link to the doc that explains how to do it. Any help in solving the above problem is appreciated.

**Comment by hoisie** [comment]
It is doable, but you need to have all the right jars on the classpath, and there are likely some system properties that need to be set.

**Comment by artsmvch** [comment]
Thanks @hoisie, I fixed the `InjectionException` by providing all the right jars on the classpath.

However, the test method is not called. Here is the output after running the test from the Java command line:
```
JUnit version 4.13.2
WARNING: No manifest file found at ./AndroidManifest.xml.
Falling back to the Android OS resources only.
To remove this warning, annotate your test class with @Config(manifest=Config.NONE).
.
Time: 0,031

OK (1 test)

```
Do you happen to know why the test method is not be called?
