### ISSUE TITLE
java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory

### ISSUE THREAD

**Issue by hafiz013** [robolectric/robolectric#9628]
### Description
java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"
java.lang.RuntimeException: java.lang.IllegalAccessException: class org.robolectric.res.ResourceTableFactory cannot access a member of class android.R$styleable with modifiers "private static transient"

### Steps to Reproduce
When running coverage report got above error but when running unit test so far ok no problem.

### Robolectric & Android Version
org.robolectric:robolectric:4.7.3
org.jacoco:org.jacoco.core:0.8.8
JAVA_JDK = 17

**Comment by MGaetan89** [comment]
@hafiz013 can you try with the latest version of Robolectric (4.13) to see if this issue still happens?
If it does, are you able to provide a small reproducer for this issue?

**Comment by MGaetan89** [comment]
This is no longer specific to Robolectric, but probably more a setup in your project.
Following the link in the error, you can find this issue: https://issuetracker.google.com/issues/346686142
Which redirects to: https://issuetracker.google.com/issues/294342862
I think that you need to update AGP as well

**Comment by hafiz013** [comment]
My agp is use 7.4.2, May i know which version are still compatible with this agp? @MGaetan89

**Comment by MGaetan89** [comment]
The latest version of Robolectric that uses AGP 7.4.2 is Robolectric 4.10.3: https://github.com/robolectric/robolectric/blob/robolectric-4.10.3/build.gradle#L14

**Comment by hafiz013** [comment]
@MGaetan89 After I update to 4.12.2 my coverage report error reduce from 5 failure into 2 failure which is brought this error

```
Bad return type
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @1010: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @1010
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', '[I', '[Z', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b200 7fc7 000b 1281 b800 87b3 007f b200
    0000010: 7f3a 05b8 008b 3a06 1905 1102 5d5c 2e04
    0000020: 604f 2cb4 01b0 c700 06a7 0010 1905 1102
    0000030: 5e5c 2e04 604f a700 4419 0511 025f 5c2e
    0000040: 0460 4f19 0611 0172 0454 1905 1102 605c
    0000050: 2e04 604f bb04 3159 bb01 2259 b701 2313
    0000060: 0433 b601 292c b402 bcb6 0186 b601 33b7
    0000070: 0434 1906 1101 7304 54bf 1905 1102 615c
    0000080: 2e04 604f 2cb4 01b0 b901 b101 003a 0719
    0000090: 0511 0262 5c2e 0460 4f01 3a08 1906 1101
    00000a0: 7404 5419 0511 0263 5c2e 0460 4f14 01d9
    00000b0: 1907 b801 e219 0611 0175 0454 1905 1102
    00000c0: 645c 2e04 604f 1907 1303 7ab6 037e 9900
    00000d0: 06a7 0010 1905 1102 655c 2e04 604f a702
    00000e0: 8819 0511 0266 5c2e 0460 4f19 0611 0176
    00000f0: 0454 1905 1102 675c 2e04 604f 2a19 071d
    0000100: 2cb4 01ae 1304 36b6 0382 3a09 1906 1101
    0000110: 7704 5419 0511 0268 5c2e 0460 4f19 09b8
    0000120: 043c 3a0a 1906 1101 7804 5419 0511 0269
    0000130: 5c2e 0460 4f19 09b9 043f 0100 5936 0b05
    0000140: a000 06a7 0010 1905 1102 6a5c 2e04 604f
    0000150: a700 1719 0511 026b 5c2e 0460 4f19 0611
    0000160: 0179 0454 a700 3715 0b04 a000 06a7 0010
    0000170: 1905 1102 6c5c 2e04 604f a700 1719 0511
    0000180: 026d 5c2e 0460 4f19 0611 017a 0454 a700
    0000190: 0d19 0611 017b 0454 a7ff 9319 0511 026e
    00001a0: 5c2e 0460 4f15 0b05 9f00 06a7 0010 1905
    00001b0: 1102 6f5c 2e04 604f a700 3019 0511 0270
    00001c0: 5c2e 0460 4f19 0611 017c 0454 1905 1102
    00001d0: 715c 2e04 604f bb03 c259 1304 41b7 0442
    00001e0: 1906 1101 7d04 54bf 1905 1102 725c 2e04
    00001f0: 604f 1909 b904 4501 003a 0c19 0611 017e
    0000200: 0454 1905 1102 735c 2e04 604f 190c 1304
    0000210: 47b6 0199 9900 06a7 0010 1905 1102 745c
    0000220: 2e04 604f a700 3419 0511 0275 5c2e 0460
    0000230: 4f19 0611 017f 0454 1905 1102 765c 2e04
    0000240: 604f 2b19 0919 0a19 04b8 044d 3a08 1906
    0000250: 1101 8004 54a7 0060 1905 1102 775c 2e04
    0000260: 604f 190c 1304 4fb6 0199 9a00 06a7 0010
    0000270: 1905 1102 785c 2e04 604f a700 1719 0511
    0000280: 0279 5c2e 0460 4f19 0611 0181 0454 a700
    0000290: 2719 0611 0182 0454 1905 1102 7a5c 2e04
    00002a0: 604f 2b19 0919 0a19 04b8 0452 3a08 1906
    00002b0: 1101 8304 5419 0511 027b 5c2e 0460 4f19
    00002c0: 09b9 0389 0100 a701 0919 0511 027d 5c2e
    00002d0: 0460 4f3a 0919 0611 0184 0454 1905 1102
    00002e0: 7e5c 2e04 604f 1401 d9b8 026c 1906 1101
    00002f0: 8504 5419 0511 027f 5c2e 0460 4fbb 0016
    0000300: 59bb 0122 59b7 0123 1301 b7b6 0129 1907
    0000310: b601 2913 0454 b601 291d 1906 1101 8604
    0000320: 5419 0511 0280 5c2e 0460 4fb8 012f b601
    0000330: 29b6 0133 b701 363a 0a19 0611 0187 0454
    0000340: 1905 1102 815c 2e04 604f 190a 1909 b601
    0000350: cf57 1905 1102 825c 2e04 604f 190a 1906
    0000360: 1101 8804 54bf 1905 1102 835c 2e04 604f
    0000370: 1401 d9b8 026c 1906 1101 8904 5419 0511
    0000380: 0284 5c2e 0460 4fbb 0016 59bb 0122 59b7
    0000390: 0123 1301 b7b6 0129 1907 b601 2913 01cb
    00003a0: b601 291d 1906 1101 8a04 5419 0511 0285
    00003b0: 5c2e 0460 4fb8 012f b601 2913 041e b601
    00003c0: 29b6 0133 b701 3619 0611 018b 0454 bf19
    00003d0: 0511 0286 5c2e 0460 4f14 01d9 b802 6c19
    00003e0: 0511 0287 5c2e 0460 4f19 0819 0611 018c
    00003f0: 0454 b0                                
  Exception Handler Table:
    bci [235, 710] => handler: 713
  Stackmap Table:
    same_frame(@14)
    append_frame(@44,Object[#279],Object[#280])
    same_frame(@57)
    same_frame_extended(@122)
    append_frame(@212,Object[#199],Null)
    same_frame(@225)
    append_frame(@299,Object[#904],Object[#1113])
    append_frame(@326,Integer)
    same_frame(@339)
    same_frame(@359)
    same_frame(@368)
    same_frame(@381)
    same_frame(@401)
    same_frame(@411)
    same_frame(@430)
    same_frame(@443)
    same_frame(@488)
    append_frame(@538,Object[#199])
    same_frame(@551)
    same_frame(@600)
    same_frame(@624)
    same_frame(@637)
    same_frame(@657)
    full_frame(@693,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4],Object[#904],Object[#1113],Integer,Object[#199]},{})
    full_frame(@713,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4]},{Object[#334]})
    full_frame(@870,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Null},{})
    full_frame(@975,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4],Object[#904],Object[#1113],Integer,Object[#199]},{})

java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    android/content/res/ResourcesImpl.$$robo$$android_content_res_ResourcesImpl$loadComplexColorForCookie(Landroid/content/res/Resources;Landroid/util/TypedValue;ILandroid/content/res/Resources$Theme;)Landroid/content/res/ComplexColor; @1010: areturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'android/content/res/ComplexColor' (from method signature)
  Current Frame:
    bci: @1010
    flags: { }
    locals: { 'android/content/res/ResourcesImpl', 'android/content/res/Resources', 'android/util/TypedValue', integer, 'android/content/res/Resources$Theme', '[I', '[Z', 'java/lang/String', 'java/lang/Object', 'android/content/res/XmlResourceParser', 'android/util/AttributeSet', integer, 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b200 7fc7 000b 1281 b800 87b3 007f b200
    0000010: 7f3a 05b8 008b 3a06 1905 1102 5d5c 2e04
    0000020: 604f 2cb4 01b0 c700 06a7 0010 1905 1102
    0000030: 5e5c 2e04 604f a700 4419 0511 025f 5c2e
    0000040: 0460 4f19 0611 0172 0454 1905 1102 605c
    0000050: 2e04 604f bb04 3159 bb01 2259 b701 2313
    0000060: 0433 b601 292c b402 bcb6 0186 b601 33b7
    0000070: 0434 1906 1101 7304 54bf 1905 1102 615c
    0000080: 2e04 604f 2cb4 01b0 b901 b101 003a 0719
    0000090: 0511 0262 5c2e 0460 4f01 3a08 1906 1101
    00000a0: 7404 5419 0511 0263 5c2e 0460 4f14 01d9
    00000b0: 1907 b801 e219 0611 0175 0454 1905 1102
    00000c0: 645c 2e04 604f 1907 1303 7ab6 037e 9900
    00000d0: 06a7 0010 1905 1102 655c 2e04 604f a702
    00000e0: 8819 0511 0266 5c2e 0460 4f19 0611 0176
    00000f0: 0454 1905 1102 675c 2e04 604f 2a19 071d
    0000100: 2cb4 01ae 1304 36b6 0382 3a09 1906 1101
    0000110: 7704 5419 0511 0268 5c2e 0460 4f19 09b8
    0000120: 043c 3a0a 1906 1101 7804 5419 0511 0269
    0000130: 5c2e 0460 4f19 09b9 043f 0100 5936 0b05
    0000140: a000 06a7 0010 1905 1102 6a5c 2e04 604f
    0000150: a700 1719 0511 026b 5c2e 0460 4f19 0611
    0000160: 0179 0454 a700 3715 0b04 a000 06a7 0010
    0000170: 1905 1102 6c5c 2e04 604f a700 1719 0511
    0000180: 026d 5c2e 0460 4f19 0611 017a 0454 a700
    0000190: 0d19 0611 017b 0454 a7ff 9319 0511 026e
    00001a0: 5c2e 0460 4f15 0b05 9f00 06a7 0010 1905
    00001b0: 1102 6f5c 2e04 604f a700 3019 0511 0270
    00001c0: 5c2e 0460 4f19 0611 017c 0454 1905 1102
    00001d0: 715c 2e04 604f bb03 c259 1304 41b7 0442
    00001e0: 1906 1101 7d04 54bf 1905 1102 725c 2e04
    00001f0: 604f 1909 b904 4501 003a 0c19 0611 017e
    0000200: 0454 1905 1102 735c 2e04 604f 190c 1304
    0000210: 47b6 0199 9900 06a7 0010 1905 1102 745c
    0000220: 2e04 604f a700 3419 0511 0275 5c2e 0460
    0000230: 4f19 0611 017f 0454 1905 1102 765c 2e04
    0000240: 604f 2b19 0919 0a19 04b8 044d 3a08 1906
    0000250: 1101 8004 54a7 0060 1905 1102 775c 2e04
    0000260: 604f 190c 1304 4fb6 0199 9a00 06a7 0010
    0000270: 1905 1102 785c 2e04 604f a700 1719 0511
    0000280: 0279 5c2e 0460 4f19 0611 0181 0454 a700
    0000290: 2719 0611 0182 0454 1905 1102 7a5c 2e04
    00002a0: 604f 2b19 0919 0a19 04b8 0452 3a08 1906
    00002b0: 1101 8304 5419 0511 027b 5c2e 0460 4f19
    00002c0: 09b9 0389 0100 a701 0919 0511 027d 5c2e
    00002d0: 0460 4f3a 0919 0611 0184 0454 1905 1102
    00002e0: 7e5c 2e04 604f 1401 d9b8 026c 1906 1101
    00002f0: 8504 5419 0511 027f 5c2e 0460 4fbb 0016
    0000300: 59bb 0122 59b7 0123 1301 b7b6 0129 1907
    0000310: b601 2913 0454 b601 291d 1906 1101 8604
    0000320: 5419 0511 0280 5c2e 0460 4fb8 012f b601
    0000330: 29b6 0133 b701 363a 0a19 0611 0187 0454
    0000340: 1905 1102 815c 2e04 604f 190a 1909 b601
    0000350: cf57 1905 1102 825c 2e04 604f 190a 1906
    0000360: 1101 8804 54bf 1905 1102 835c 2e04 604f
    0000370: 1401 d9b8 026c 1906 1101 8904 5419 0511
    0000380: 0284 5c2e 0460 4fbb 0016 59bb 0122 59b7
    0000390: 0123 1301 b7b6 0129 1907 b601 2913 01cb
    00003a0: b601 291d 1906 1101 8a04 5419 0511 0285
    00003b0: 5c2e 0460 4fb8 012f b601 2913 041e b601
    00003c0: 29b6 0133 b701 3619 0611 018b 0454 bf19
    00003d0: 0511 0286 5c2e 0460 4f14 01d9 b802 6c19
    00003e0: 0511 0287 5c2e 0460 4f19 0819 0611 018c
    00003f0: 0454 b0                                
  Exception Handler Table:
    bci [235, 710] => handler: 713
  Stackmap Table:
    same_frame(@14)
    append_frame(@44,Object[#279],Object[#280])
    same_frame(@57)
    same_frame_extended(@122)
    append_frame(@212,Object[#199],Null)
    same_frame(@225)
    append_frame(@299,Object[#904],Object[#1113])
    append_frame(@326,Integer)
    same_frame(@339)
    same_frame(@359)
    same_frame(@368)
    same_frame(@381)
    same_frame(@401)
    same_frame(@411)
    same_frame(@430)
    same_frame(@443)
    same_frame(@488)
    append_frame(@538,Object[#199])
    same_frame(@551)
    same_frame(@600)
    same_frame(@624)
    same_frame(@637)
    same_frame(@657)
    full_frame(@693,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4],Object[#904],Object[#1113],Integer,Object[#199]},{})
    full_frame(@713,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4]},{Object[#334]})
    full_frame(@870,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Null},{})
    full_frame(@975,{Object[#2],Object[#24],Object[#427],Integer,Object[#27],Object[#279],Object[#280],Object[#199],Object[#4],Object[#904],Object[#1113],Integer,Object[#199]},{})

	at android.content.res.Resources.__constructor__(Resources.java:220)
	at android.content.res.Resources.<init>(Resources.java:219)
	at org.robolectric.shadows.ShadowResources.getSystem(ShadowResources.java:85)
	at android.content.res.Resources.getSystem(Resources.java)
	at android.app.LoadedApk.__constructor__(LoadedApk.java:205)
	at android.app.LoadedApk.<init>(LoadedApk.java:184)
	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2244)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.robolectric.shadows.ShadowContextImpl$_ContextImpl_$$Reflector32.createSystemContext(Unknown Source)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:298)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:282)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:279)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at org.robolectric.RuntimeEnvironment.lambda$getApplication$0(RuntimeEnvironment.java:76)
	at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1190)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:76)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:249)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:283)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:285)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

Note: When use 4.10.3 error become 5 by the way, running all unit test so far ok only problem coverage report. By the way, what does mean above error?

**Comment by MGaetan89** [comment]
In that case, you can check this issue #3023. It provides various workarounds for this issue:
- Add the `-noverify` option: https://github.com/robolectric/robolectric/issues/3023#issuecomment-356931811
- Specify which package to cover: https://github.com/robolectric/robolectric/issues/3023#issuecomment-1289562232
- Exclude `android.*` packages: https://github.com/robolectric/robolectric/issues/3023#issuecomment-1503021021

An issue has been filled on JetBrains' side: https://youtrack.jetbrains.com/issue/IDEA-349117

**Comment by MGaetan89** [comment]
Do you need any more help with this issue @hafiz013?

**Comment by hafiz013** [comment]
I just need to add -noverify in gradle it is fix my issue. tq can close this ticket.
