### ISSUE TITLE
FocusRequester is not initialized

### ISSUE THREAD

**Issue by eygraber** [robolectric/robolectric#9703]
### Description

I have the following function that I use in my Compose code:

```kotlin
@Composable
fun initialFocusRequester(): FocusRequester =
  remember { FocusRequester() }.apply {
    LaunchedEffect(this) {
      requestFocus()
    }
  }
```

It is typically used as follows:

```kotlin
@Composable
fun MyComposable() {
  val focusRequester = initialFocusRequester()

  TextField(
    state = rememberTextFieldState(),
    modifier = Modifier.focusRequester(focusRequester)
  )
}
```

However when running a Robolectric local test:

```kotlin
@RunWith(AndroidJUnit4::class)
class MyTest {
  @get:Rule val composeTestRule = createComposeRule()

  @Test
  fun test() {
    composeTestRule.setContent {
      MyComposable()
    }
  }
}
```

I get the following crash:

```
   FocusRequester is not initialized. Here are some possible fixes:

   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   2. Did you forget to add a Modifier.focusRequester() ?
   3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }

java.lang.IllegalStateException: 
   FocusRequester is not initialized. Here are some possible fixes:

   1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
   2. Did you forget to add a Modifier.focusRequester() ?
   3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }

	at androidx.compose.ui.focus.FocusRequester.findFocusTargetNode$ui_release(FocusRequester.kt:255)
	at androidx.compose.ui.focus.FocusRequester.focus$ui_release(FocusRequester.kt:67)
	at androidx.compose.ui.focus.FocusRequester.requestFocus(FocusRequester.kt:63)
	at com.me.InitialFocusRequesterKt$initialFocusRequester$2$1$1.invokeSuspend(InitialFocusRequester.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at androidx.compose.ui.test.ApplyingContinuationInterceptor$SendApplyContinuation.resumeWith(ApplyingContinuationInterceptor.kt:52)
	at androidx.compose.ui.test.FrameDeferringContinuationInterceptor$FrameDeferredContinuation.resumeWith(FrameDeferringContinuationInterceptor.jvm.kt:185)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:263)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:358)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:124)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at androidx.compose.runtime.LaunchedEffectImpl.onRemembered(Effects.kt:272)
	at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberList(RememberEventDispatcher.kt:175)
	at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberObservers(RememberEventDispatcher.kt:168)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:1041)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1064)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1109)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:674)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:613)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:127)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:118)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1718)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:118)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:172)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:315)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:193)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:125)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:118)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1797)
	at android.view.View.$$robo$$android_view_View$dispatchAttachedToWindow(View.java:18347)
	at android.view.View.dispatchAttachedToWindow(View.java)
	at android.view.ViewGroup.$$robo$$android_view_ViewGroup$dispatchAttachedToWindow(ViewGroup.java:3397)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java)
	at android.view.ViewGroup.$$robo$$android_view_ViewGroup$dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java)
	at android.view.ViewGroup.$$robo$$android_view_ViewGroup$addViewInner(ViewGroup.java:5077)
	at android.view.ViewGroup.addViewInner(ViewGroup.java)
	at android.view.ViewGroup.$$robo$$android_view_ViewGroup$addView(ViewGroup.java:4865)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.robolectric.shadows.ShadowViewGroup$ViewGroupReflector$$Reflector23.addView(Unknown Source)
	at org.robolectric.shadows.ShadowViewGroup.lambda$addView$0(ShadowViewGroup.java:30)
	at org.robolectric.shadows.ShadowViewGroup.addView(ShadowViewGroup.java:35)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at android.view.ViewGroup.$$robo$$android_view_ViewGroup$addView(ViewGroup.java:4837)
	at android.view.ViewGroup.addView(ViewGroup.java)
	at com.android.internal.policy.PhoneWindow.$$robo$$com_android_internal_policy_PhoneWindow$setContentView(PhoneWindow.java:451)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java)
	at android.app.Activity.$$robo$$android_app_Activity$setContentView(Activity.java:2807)
	at android.app.Activity.setContentView(Activity.java)
	at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:456)
	at androidx.activity.compose.ComponentActivityKt.setContent(ComponentActivity.kt:70)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl$setContent$3.invoke(ComposeUiTest.android.kt:569)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl$setContent$3.invoke(ComposeUiTest.android.kt:568)
	at androidx.compose.ui.test.AndroidSynchronization_androidKt.runOnUiThread(AndroidSynchronization.android.kt:35)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidTestOwner.runOnUiThread(ComposeUiTest.android.kt:619)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.runOnUiThread(ComposeUiTest.android.kt:473)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.setContent(ComposeUiTest.android.kt:568)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule.setContent(AndroidComposeTestRule.android.kt:419)
	at com.me.MyTest$test$1.invokeSuspend(MyTest.kt:38)
	at com.me.MyTest$test$1.invoke(MyTest.kt)
	at com.me.MyTest$test$1.invoke(MyTest.kt)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$1.invokeSuspend(TestBuilders.kt:318)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.test.TestDispatcher.processEvent$kotlinx_coroutines_test(TestDispatcher.kt:24)
	at kotlinx.coroutines.test.TestCoroutineScheduler.tryRunNextTaskUnless$kotlinx_coroutines_test(TestCoroutineScheduler.kt:99)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$workRunner$1.invokeSuspend(TestBuilders.kt:327)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:47)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersJvmKt.createTestResult(TestBuildersJvm.kt:10)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:310)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0(TestBuilders.kt:168)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0(Unknown Source)
	at kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt.runTest-8Mi8wO0$default(TestBuilders.kt:160)
	at kotlinx.coroutines.test.TestBuildersKt.runTest-8Mi8wO0$default(Unknown Source)
	at com.me.MyTest.test(MyTest.kt:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:295)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1$evaluate$1.invoke(AndroidComposeTestRule.android.kt:295)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:585)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:372)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:441)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:371)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:415)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:370)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:428)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:369)
	at androidx.compose.ui.test.IdlingStrategy.withStrategy(IdlingStrategy.android.kt:55)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:368)
	at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:146)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:367)
	at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:137)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:366)
	at androidx.compose.ui.test.junit4.AndroidComposeTestRule$apply$1.evaluate(AndroidComposeTestRule.android.kt:295)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:291)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
```

If I call `delay(1_000)` before calling `requestFocus`, or if I wrap the call to `requestFocus` in a `Handler.post` then I don't get the crash.

### Robolectric & Android Version
Robolectric - 4.13
Compose - 2024.10.00 Alpha BOM

**Comment by takahirom** [comment]
I encountered the same issue and was able to work around it by using `createComposeRule` with `effectContext`.

```kotlin
val effectTestDispatcher = StandardTestDispatcher()

@get:Rule
val composeRule = createComposeRule(effectTestDispatcher)

effectTestDispatcher.scheduler.advanceUntilIdle()
```

**Comment by MahdiIranmanesh** [comment]
> I encountered the same issue and was able to work around it by using `createComposeRule` with `effectContext`.
> 
> ```kotlin
> val effectTestDispatcher = StandardTestDispatcher()
> 
> @get:Rule
> val composeRule = createComposeRule(effectTestDispatcher)
> 
> effectTestDispatcher.scheduler.advanceUntilIdle()
> ```

where did you exactly put the `effectTestDispatcher.scheduler.advanceUntilIdle()`?

**Comment by takahirom** [comment]
You can set the timing for when you want to run the `LaunchedEffect` block. I usually do this after launching an Activity in Robolectric.

**Comment by MGaetan89** [comment]
Hey @eygraber,

I tried your code sample with the latest `master` of Robolectric and Compose 2024.11.00, and the test passes.
Can you check with Robolectric 4.14.1 to see if you still have this issue?

Here's the code I've used:
```kotlin
package org.robolectric.integrationtests.composeui

import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.test.junit4.createComposeRule
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

@RunWith(RobolectricTestRunner::class)
class FocusRequesterTest {
  @get:Rule val composeTestRule = createComposeRule()

  @Test
  fun test() {
    composeTestRule.setContent { MyComposable() }
  }

  @Composable
  private fun MyComposable() {
    val focusRequester = initialFocusRequester()

    TextField(value = "", onValueChange = {}, modifier = Modifier.focusRequester(focusRequester))
  }

  @Composable
  private fun initialFocusRequester(): FocusRequester {
    return remember { FocusRequester() }.apply { LaunchedEffect(this) { requestFocus() } }
  }
}
```

**Comment by MGaetan89** [comment]
I'm closing to close this, since it seems to be working fine now.
Feel free to reopen or open a new issue if needed.

**Comment by eygraber** [comment]
The issue is still happening in 4.14.1

I will share a repro soon.

**Comment by MGaetan89** [comment]
> The issue is still happening in 4.14.1
> 
> I will share a repro soon.

Did you have a chance to come up with a repro?

**Comment by eygraber** [comment]
I have a sticky note on my desk reminding me to do this 🙈 

I'll put one together later today.

**Comment by eygraber** [comment]
If you run `./gradlew :ui:compose:testDevDebugUnitTest` you should see the crash.

[repro.zip](https://github.com/user-attachments/files/19491606/repro.zip)

**Comment by MGaetan89** [comment]
It's because your `FocusRequester` is not used. So calling `requestFocus()` on it crashes.
If I add the following to your `initialFocusRequesterTest`, the test passes:
```kotlin
Text(
  text = "Hello, Kotlin",
  modifier = Modifier.focusRequester(focusRequester),
)
```

**Comment by eygraber** [comment]
Hmm I tried to keep it as minimal as possible, but it was crashing even when it was used. I'll try again.

**Comment by eygraber** [comment]
This is closer to my actual code and is crashing.

[repro.zip](https://github.com/user-attachments/files/19493582/repro.zip)

**Comment by eygraber** [comment]
Looks like it might be because `Scaffold` is a `SubcomposeLayout`, so it gets delayed a little bit? Doesn't happen on regular builds, but only with Robolectric.

**Comment by MGaetan89** [comment]
Thanks for the repro. Adding the `Scaffold` to the test I added back in #9847 also reproduces the issue.
I'll look into this and see what I can do.

**Comment by MGaetan89** [comment]
I found the exact use case on Google's [issue tracker](https://issuetracker.google.com/issues/206249038).

As you predicted, it is because `Scaffold` is a `SubcomposeLayout`. So the `focusRequester` `Modifier` is not attached when the `requestFocus()` call is made.
The suggested solution is to move the creation of the `FocusRequester` inside the `Scaffold`.

**Comment by eygraber** [comment]
Well there we go 😅 

Thanks for the help!
