### ISSUE TITLE
NPE when creating activity based on MapActivity

### ISSUE THREAD

**Issue by ryazmin** [robolectric/robolectric#972]
Activity is very simple without map view in layout, it's just extends com.google.android.maps.MapActivity

the test code

    @Test
    public void launchActivity() throws Exception {
		Robolectric.buildActivity(SimpleActivity.class).create().visible().start().resume().get();
    }

Issue looks similar to https://github.com/robolectric/robolectric/issues/918
and similar question on SO: http://stackoverflow.com/questions/21791942/testing-my-mapactivity-with-robolectric

Exception stack trace:
java.lang.NullPointerException
	at android.app.Activity.attach(Activity.java:4967)
	at org.fest.reflect.method.Invoker.invoke(Invoker.java:112)
	at org.robolectric.util.ActivityController.attach(ActivityController.java:90)
	at org.robolectric.util.ActivityController$1.run(ActivityController.java:114)
	at org.robolectric.shadows.ShadowLooper.runPaused(ShadowLooper.java:256)
	at org.robolectric.util.ActivityController.create(ActivityController.java:111)
	at org.robolectric.util.ActivityController.create(ActivityController.java:123)
	at com.mytests.activity.SimpleActivityTest.launchActivity(SimpleActivityTest.java:37)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:234)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:175)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by jaredsburrows** [comment]
@ryazmin Do you still need that Shadow with Robolectric 3.0?

If so, submit a PR.

**Comment by erd** [comment]
Closing this since it seems like there is a workaround.

**Comment by nikhilbalyan** [comment]
I resolved it by creating using the ControllerActivity and passing the intent inside the withIntent()
