### ISSUE TITLE
WebView inside Compose not testable via Espresso-Web and Robolectric

### ISSUE THREAD

**Issue by realdadfish** [robolectric/robolectric#9738]
When I try to test an Android `WebView` embedded  in a `AndroidView` composable, I encounter multiple issues.

First is that Espresso-Web fails early because it figures out the WebView is not hardware-accelerated. I can work around this by subclassing `WebView` and overriding `isHardwareAccelerated` with `true`. Then, Espresso-Web complains that the test code is running on the main thread. I worked around this by adding `@LooperMode(LooperMode.Mode.INSTRUMENTATION_TEST)` to my test, but then, the test fails with a timeout exception:

```
java.util.concurrent.TimeoutException: Waited 10000000000 nanoseconds (plus 5098041 nanoseconds delay) for androidx.concurrent.futures.ResolvableFuture@3827a6b1[status=PENDING]
java.lang.RuntimeException: java.util.concurrent.TimeoutException: Waited 10000000000 nanoseconds (plus 5098041 nanoseconds delay) for androidx.concurrent.futures.ResolvableFuture@3827a6b1[status=PENDING]
	at androidx.test.espresso.web.sugar.Web$WebInteraction$ExceptionPropagator.<init>(Web.java:338)
	at androidx.test.espresso.web.sugar.Web$WebInteraction.doEval(Web.java:314)
	at androidx.test.espresso.web.sugar.Web$WebInteraction.check(Web.java:291)
	at eu.gls.parcelos.android.transport.drivercheckout.ui.webview.WebViewScreenTest.should_show_legal_information$lambda$0(WebViewScreenTest.kt:28)
	at androidx.compose.ui.test.ComposeUiTest_androidKt$runAndroidComposeUiTest$1.invoke(ComposeUiTest.android.kt:114)
	at androidx.compose.ui.test.ComposeUiTest_androidKt$runAndroidComposeUiTest$1.invoke(ComposeUiTest.android.kt:112)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:585)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:372)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:441)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:371)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:415)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:370)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:428)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:237)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:369)
	at androidx.compose.ui.test.IdlingStrategy.withStrategy(IdlingStrategy.android.kt:55)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:368)
	at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:146)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:367)
	at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:137)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:366)
	at androidx.compose.ui.test.ComposeUiTest_androidKt.runAndroidComposeUiTest(ComposeUiTest.android.kt:112)
	at androidx.compose.ui.test.ComposeUiTest_androidKt.runComposeUiTest(ComposeUiTest.android.kt:53)
	at androidx.compose.ui.test.ComposeUiTest_androidKt.runComposeUiTest$default(ComposeUiTest.android.kt:52)
	at my.company.WebViewScreenTest.should show legal information(WebViewScreenTest.kt:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.koin.test.mock.MockProviderRule$apply$1.evaluate(MockProviderRule.kt:28)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:489)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:291)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.TimeoutException: Waited 10000000000 nanoseconds (plus 5098041 nanoseconds delay) for androidx.concurrent.futures.ResolvableFuture@3827a6b1[status=PENDING]
	at androidx.concurrent.futures.AbstractResolvableFuture.get(AbstractResolvableFuture.java:456)
	at androidx.test.espresso.web.util.concurrent.ChainingListenableFuture.get(ChainingListenableFuture.java:123)
	at androidx.test.espresso.web.action.AtomAction.get(AtomAction.java:193)
	at androidx.test.espresso.web.sugar.Web$WebInteraction.doEval(Web.java:305)
	... 45 more
```

This is my test code:

```kotlin
@RunWith(RobolectricTestRunner::class)
@Config(
    qualifiers = "w360dp-h640dp-320dpi",
    manifest = Config.NONE,
    // do not use the Application class registered in the manifest, as this starts Koin
    application = Application::class,
    // because of https://github.com/robolectric/robolectric/issues/8071
    shadows = [ShadowPixelCopy::class]
)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@LooperMode(LooperMode.Mode.INSTRUMENTATION_TEST)
class WebViewTest {
    @Test
    fun `should show legal information`() {
        runComposeUiTest {
            setupScreen(R.raw.some_resource)

            onWebView()
                .check(webMatches(getTitle(), containsString("Some Title")))
        }
    }

    private fun ComposeUiTest.setupScreen(@RawRes htmlResource: Int) {
        setContent {
            WebViewScreen(htmlResource)
        }
    }
}
```

This is my implementation:

```
@Composable
internal fun WebViewScreen(
    @RawRes htmlResource: Int
) {
    val context = LocalContext.current
    val html = remember { context.resources.openRawResource(htmlResource).reader().readText() }
    Column(
        modifier =
        Modifier
            .fillMaxSize()
            .padding(32.dp)
    ) {
        ComposeWebView(
            modifier =
            Modifier
                .fillMaxSize(),
            html = html
        )
    }
}

@SuppressLint("SetJavaScriptEnabled")
@Composable
private fun ComposeWebView(modifier: Modifier = Modifier, html: String) {
    val context = LocalContext.current
    val client =
        remember {
            object : WebViewClient() {
                 /* ... */
                }
            }
        }

    val webView = remember { mutableStateOf<WebView?>(null) }
    AndroidView(
        factory = { context ->
            FixedWebView(context).apply {
                webViewClient = client
            }.also {
                // needed for testing purposes
                it.settings.javaScriptEnabled = true
                webView.value = it
            }
        },
        modifier = modifier
    )
   
    webView.value?.let { wv ->
        LaunchedEffect(wv) {
            wv.loadData(html, "text/html", "UTF-8")
        }
    }
}

class FixedWebView(context: Context) : WebView(context) {
    override fun isHardwareAccelerated(): Boolean = true
}
```

**Comment by JuliaSullivanGoogle** [comment]
WebViews are not supported in Robolectric. Also, you shouldn't need to turn on native graphics explicitly, it's the default. Also the shadow for ShadowPixelCopy should be obsolete now as ShadowPixelCopy is well supported in native graphics.

**Comment by hoisie** [comment]
@JuliaSullivanGoogle native graphics is not the default for third-party.
