### ISSUE TITLE
huh? can't find parent for StyleData

### ISSUE THREAD

**Issue by macosgrove** [robolectric/robolectric#979]
I'm trying to run Robolectric tests with the Android Studio project structure. I have a separate module for my Robolectric tests as I am also running instrument tests which now live in the main project.
I've set up org.robolectric.Config.properties to point Robolectric to my AndroidManifest in the main project. That's working fine.

But when I try to create my Activity I get this:

```
WARNING: no system properties value for ro.build.date.utc
DEBUG: Loading resources for com.thoughtworks.androidbootcamp from ./../AndroidBootcamp/src/main/res...

java.lang.RuntimeException: huh? can't find parent for StyleData{name='AppTheme', parent='Theme_AppCompat_Light_DarkActionBar'}
    at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getParent(ShadowAssetManager.java:351)
    at org.robolectric.shadows.ShadowAssetManager$StyleResolver.getAttrValue(ShadowAssetManager.java:336)
    at org.robolectric.shadows.ShadowResources.findAttributeValue(ShadowResources.java:293)
    at org.robolectric.shadows.ShadowResources.attrsToTypedArray(ShadowResources.java:196)
    at org.robolectric.shadows.ShadowResources.access$000(ShadowResources.java:55)
...
```

If we remove AppCompat the issue goes away.

I'm using the 2.3-SNAPSHOT

**Comment by simtse** [comment]
Hello @erd , I have a standard gradle setup in Android Studio but I still have to do what @meonlol has suggested. You mentioned that resources need to be in the project.properties or in the @Config, where can I find information about this @config and how to set it up?

Also, what gradle plugin do you mean?
