### ISSUE TITLE
Warning about being unable to delete a temp directory

### ISSUE THREAD

**Issue by ansman** [robolectric/robolectric#9831]
### Description
After a recent robolectric update (possibly 4.14.1) we're seeing this being printed when running some tests:
```
    ERROR: Failed to destroy temp directory
    java.nio.file.DirectoryNotEmptyException: /var/folders/08/4ywlgg256hv6d9jvsnxnw96r0000gp/T/robolectric-nativeruntime212045869758686408
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:290)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1153)
        at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:141)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1575)
```
The directory in question only contains `librobolectric-nativeruntime.dylib`.

### Steps to Reproduce
I don't have stable repro steps.

### Robolectric & Android Version
4.14.1, compile SDK 35

### Link to a public git repo demonstrating the problem:
n/a

**Comment by Arka-Saha** [comment]
hey there, can you please elaborate the changes needed a bit.. and im ready to work on it. Can it be assigned to me?

**Comment by JesusOnt** [comment]
Hi I'm having the same issue since 4.14 I actually have 4.16, I can't share some example because is flaky on CI. Bu I hope this more logs helps to find the solution.
> java.nio.file.DirectoryNotEmptyException: /tmp/robolectric-nativeruntime5549766690171490010/fonts
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at org.robolectric.util.TempDirectory$1.postVisitDirectory(TempDirectory.java:177)
        at org.robolectric.util.TempDirectory$1.postVisitDirectory(TempDirectory.java:160)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2803)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2857)
        at org.robolectric.util.TempDirectory.clearDirectory(TempDirectory.java:158)
        at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:141)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

> ERROR: Failed to destroy temp directory
java.nio.file.DirectoryNotEmptyException: /tmp/robolectric-nativeruntime5373512758897403989
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at org.robolectric.util.TempDirectory.destroy(TempDirectory.java:142)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

This is the crash on the JVM that does the build fails 

```
Current thread (0x00007e320d5beea0):  JavaThread "WM.task-1"        [_thread_in_native, id=16742, stack(0x00007e33d7800000,0x00007e33d7900000) (1024K)]

Stack: [0x00007e33d7800000,0x00007e33d7900000],  sp=0x00007e33d78fbf00,  free space=1007k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
j  org.robolectric.nativeruntime.SQLiteConnectionNatives.nativeOpen(Ljava/lang/String;ILjava/lang/String;ZZII)J+0
j  org.robolectric.shadows.ShadowNativeSQLiteConnection.lambda$nativeOpen$0(Ljava/lang/String;ILjava/lang/String;ZZII)Ljava/lang/Long;+35
j  org.robolectric.shadows.ShadowNativeSQLiteConnection$$Lambda+0x00007e338cbc99b0.get()Ljava/lang/Object;+28
J 12025 c2 org.robolectric.util.PerfStatsCollector.measure(Ljava/lang/String;Lorg/robolectric/util/PerfStatsCollector$ThrowingSupplier;)Ljava/lang/Object; (101 bytes) @ 0x00007e33f4f93180 [0x00007e33f4f92f80+0x0000000000000200]
j  org.robolectric.shadows.ShadowNativeSQLiteConnection.nativeOpen(Ljava/lang/String;ILjava/lang/String;ZZII)J+57
j  java.lang.invoke.LambdaForm$DMH+0x00007e338cb88000.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;IIII)J+22 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338cb8a400.guardWithCatch(Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;IIII)J+51 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338cb8c400.reinvoke(Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;IIII)J+31 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338cb8c800.guard(Ljava/lang/Object;Ljava/lang/Object;ILjava/lang/Object;IIII)J+94 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338cb8cc00.linkToCallSite(Ljava/lang/Object;ILjava/lang/Object;IIIILjava/lang/Object;)J+25 java.base@21.0.3
j  android.database.sqlite.SQLiteConnection.nativeOpen(Ljava/lang/String;ILjava/lang/String;ZZII)J+10
j  android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$open()V+56
J 14112 c2 java.lang.invoke.DirectMethodHandle$Holder.invokeSpecial(Ljava/lang/Object;Ljava/lang/Object;)V java.base@21.0.3 (14 bytes) @ 0x00007e33f47eeff0 [0x00007e33f47eefa0+0x0000000000000050]
J 14232 c2 java.lang.invoke.LambdaForm$MH+0x00007e338c1b9000.guardWithCatch(Ljava/lang/Object;Ljava/lang/Object;)V java.base@21.0.3 (71 bytes) @ 0x00007e33f45b9848 [0x00007e33f45b97e0+0x0000000000000068]
J 5020 c1 java.lang.invoke.LambdaForm$MH+0x00007e338c1b9c00.reinvoke(Ljava/lang/Object;Ljava/lang/Object;)V java.base@21.0.3 (23 bytes) @ 0x00007e33ed269d44 [0x00007e33ed269900+0x0000000000000444]
J 14231 c2 java.lang.invoke.LambdaForm$MH+0x00007e338c1ba000.guard(Ljava/lang/Object;Ljava/lang/Object;)V java.base@21.0.3 (93 bytes) @ 0x00007e33f45b9134 [0x00007e33f45b9060+0x00000000000000d4]
J 14194 c2 java.lang.invoke.LambdaForm$MH+0x00007e338c1ba400.linkToCallSite(Ljava/lang/Object;Ljava/lang/Object;)V java.base@21.0.3 (17 bytes) @ 0x00007e33f45be6e0 [0x00007e33f45be6a0+0x0000000000000040]
j  android.database.sqlite.SQLiteConnection.open()V+1
j  android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$open(Landroid/database/sqlite/SQLiteConnectionPool;Landroid/database/sqlite/SQLiteDatabaseConfiguration;IZ)Landroid/database/sqlite/SQLiteConnection;+15
j  java.lang.invoke.LambdaForm$DMH+0x00007e338cb84000.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;II)Ljava/lang/Object;+16 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338c401000.guardWithCatch(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;II)Ljava/lang/Object;+45 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338c401c00.reinvoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;II)Ljava/lang/Object;+25 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338c402000.guard(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;II)Ljava/lang/Object;+82 java.base@21.0.3
j  java.lang.invoke.LambdaForm$MH+0x00007e338c402400.linkToCallSite(Ljava/lang/Object;Ljava/lang/Object;IILjava/lang/Object;)Ljava/lang/Object;+19 java.base@21.0.3
j  android.database.sqlite.SQLiteConnection.open(Landroid/database/sqlite/SQLiteConnectionPool;Landroid/database/sqlite/SQLiteDatabaseConfiguration;IZ)Landroid/database/sqlite/SQLiteConnection;+4
j  android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$openConnectionLocked(Landroid/database/sqlite/SQLiteDatabaseConfiguration;Z)Landroid/database/sqlite/SQLiteConnection;+16

```
Additionally I start to see from 4.14 this warnings
```
System.logW: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'SQLiteConnection.close' not called
        at dalvik.system.CloseGuard.$$robo$$dalvik_system_CloseGuard$openWithCallSite(CloseGuard.java:288)
        at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java)
        at dalvik.system.CloseGuard.$$robo$$dalvik_system_CloseGuard$open(CloseGuard.java:257)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.robolectric.shadows.ShadowCloseGuard$CloseGuardReflector$$Reflector38.open(Unknown Source)
        at org.robolectric.shadows.ShadowCloseGuard.open(ShadowCloseGuard.java:38)
        at dalvik.system.CloseGuard.open(CloseGuard.java)
        at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$__constructor__(SQLiteConnection.java:182)
        at android.database.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:173)
        at android.database.sqlite.SQLiteConnection.$$robo$$android_database_sqlite_SQLiteConnection$open(SQLiteConnection.java:202)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$openConnectionLocked(SQLiteConnectionPool.java:512)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$open(SQLiteConnectionPool.java:210)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteConnectionPool.$$robo$$android_database_sqlite_SQLiteConnectionPool$open(SQLiteConnectionPool.java:202)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openInner(SQLiteDatabase.java:1085)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$open(SQLiteDatabase.java:1065)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openDatabase(SQLiteDatabase.java:929)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteDatabase.$$robo$$android_database_sqlite_SQLiteDatabase$openDatabase(SQLiteDatabase.java:918)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java)
        at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getDatabaseLocked(SQLiteOpenHelper.java:373)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java)
        at android.database.sqlite.SQLiteOpenHelper.$$robo$$android_database_sqlite_SQLiteOpenHelper$getReadableDatabase(SQLiteOpenHelper.java:340)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java)
        at androidx.media3.datasource.cache.CachedContentIndex$DatabaseStorage.exists(CachedContentIndex.java:788)
        at androidx.media3.datasource.cache.CachedContentIndex.initialize(CachedContentIndex.java:203)
        at androidx.media3.datasource.cache.SimpleCache.initialize(SimpleCache.java:549)
        at androidx.media3.datasource.cache.SimpleCache.access$000(SimpleCache.java:51)
        at androidx.media3.datasource.cache.SimpleCache$1.run(SimpleCache.java:235)
```
