### ISSUE TITLE
How to avoid "Do not declare it as part of the package or test app manifest."

### ISSUE THREAD

**Issue by song-water** [robolectric/robolectric#9880]
### Description
1. Our project use platform permission like "android.permission.CONTROL_KEYGUARD" because special customized business needs.
2. robolectric 4.11.1 is okay.
3. robolectric 4.14.1 throw exception like "Permission android.permission.CONTROL_KEYGUARD is a platform permission. Do not declare it as part of the package or test app manifest."
4. I found that https://github.com/robolectric/robolectric/pull/9256 is the "platform permission implementation".

**My question is:
1 - How to avoid "Do not declare it as part of the package or test app manifest." if wanna use robolectric 4.14.1 with platform permission?
2 - Is it possible to down this "IllegalArgumentException" to warning or note?**

### Steps to Reproduce

Ditto, and the exception like below:
`
Permission android.permission.CONTROL_KEYGUARD is a platform permission. Do not declare it as part of the package or test app manifest.
java.lang.IllegalArgumentException: Permission android.permission.CONTROL_KEYGUARD is a platform permission. Do not declare it as part of the package or test app manifest.
	at org.robolectric.shadows.ShadowPackageManager.addPackage(ShadowPackageManager.java:1004)
	at org.robolectric.shadows.ShadowPackageManager.addPackageNoDefaults(ShadowPackageManager.java:983)
	at org.robolectric.shadows.ShadowPackageManager.installPackage(ShadowPackageManager.java:945)
	at org.robolectric.shadows.ShadowPackageManager.addPackageInternal(ShadowPackageManager.java:1411)
	at org.robolectric.android.internal.AndroidTestEnvironment.installAndCreateApplication(AndroidTestEnvironment.java:347)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$0(AndroidTestEnvironment.java:262)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:51)
	at org.robolectric.android.internal.AndroidTestEnvironment.lambda$createApplicationSupplier$1(AndroidTestEnvironment.java:259)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
	at org.robolectric.RuntimeEnvironment.lambda$getApplication$0(RuntimeEnvironment.java:71)
	at org.robolectric.shadows.ShadowInstrumentation.runOnMainSyncNoIdle(ShadowInstrumentation.java:1190)
	at org.robolectric.RuntimeEnvironment.getApplication(RuntimeEnvironment.java:71)
	at org.robolectric.android.internal.AndroidTestEnvironment.setUpApplicationState(AndroidTestEnvironment.java:230)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:284)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:279)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:104)
`

### Robolectric & Android Version
Project env list
Robolectric : 4.14.1
Android target sdk : 35
Android gradle plugin :  8.4.2
gradle version 8.6 :

**Comment by Pasha831** [comment]
hi, still no solutions?

**Comment by Pasha831** [comment]
you can override `robolectric.allowPlatformPermissions` with `test.systemProperty` inside gradle like this:

```gradle
android {
  testOptions {
    unitTests.all {
       ...
       test.systemProperty("robolectric.allowPlatformPermissions", "true")
    }
  }
}
```

and everything will work fine, the solution was introduced [here](https://github.com/robolectric/robolectric/pull/10312)

**Comment by laqr** [comment]
I had to update Robolectric to 4.15.1, and this worked like a charm. Thanks!

**Comment by song-water** [comment]
Thank you so much. 
Robolectric 4.16 is work for my case.
